### DISCUSSION TITLE
Daily energy consumption using statistics

### DISCUSSION THREAD

**Discussion by tomlevels** [dbuezas/lovelace-plotly-graph-card#131] [Show and tell]
I have a card that shows the energy consumption for the last days:
![image](https://user-images.githubusercontent.com/3691709/200612093-1452c7ca-4288-4974-bce6-3665c7c1aa34.png)

This is my config:
 ```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.airco_beneden_daily
    statistic: state
    period: day
    type: bar
    texttemplate: '%{y}'
hours_to_show: 240
defaults:
  entity:
    line:
      width: 2
  yaxes:
    fixedrange: true
 ```
(edit: removed workaround, as #129 is fixed)

**Comment by tomlevels** [comment]
This is what I use for hourly image consumption:
![image](https://user-images.githubusercontent.com/3691709/201531144-de4a5fdf-50a8-4803-b9d7-c86a160404b0.png)

For this, I add the last hour in a separate entity, only taking the last hour (which is in another color, but you could make it the same if wanted):
```
type: custom:plotly-graph
entities:
  - entity: sensor.airco_beneden_hourly
    statistic: state
    name: Hourly
    period: hour
    type: bar
    texttemplate: '%{y}'
    lambda: (ys) => ys.slice(0, -1)
  - entity: sensor.airco_beneden_hourly
    type: bar
    name: Current hour
    texttemplate: '%{y}'
    lambda: |-
      (ys,xs) => {
        const slicedx = xs.slice(-1)
        const slicedy = ys.slice(-1)
        slicedx[0].setMinutes(0)
        return {x:slicedx, y:slicedy};
      }
hours_to_show: 8
defaults:
  entity:
    line:
      width: 2
  yaxes:
    fixedrange: true
```
