### DISCUSSION TITLE
How to write a lambda to calculate the Abs. Humidity from the LTS temp and Rel. humidity values?

### DISCUSSION THREAD

**Discussion by netweaver1970** [dbuezas/lovelace-plotly-graph-card#140] [Q&A] [answered]
hi, 
as this is not an issue but a request, I'll put it here, so more people can see it/learn from your answer.
I want to plot absolute humidity based on my Relative humidity and temp LTS values. 

I've found this formula (as well as the usual psychrometric diagrams, unusable for computer use):

Absolute Humidity (grams/m3) = (6.112 × e^[(17.67 × T)/(T+243.5)] × rh × 2.1674)/(273.15+T).
(from https://carnotcycle.wordpress.com/2012/08/04/how-to-convert-relative-humidity-to-absolute-humidity/)

I know it would be most efficient to have the Abs Hum to be calculated using a template sensor in HA at data point storage time and then the LTS of them being used for plotting. 
But if I do that, then I have to wait a long time till I build up enough history to be useful.

If it's part of a lambda as well (initially), then I could use the stored LTS values to calculate it on-the-fly, at run-time, also for my historic values. It might be (too) slow, but I think if I keep the number of data points per graph low, it might be feasible. In the meantime, I'll build up my history using the template sensor(s). 

Unfortunately, I don't know enough about the lambda syntax to convert the formula into working code. For lambdas, I used normally the good old copy-paste-adjust adagio.... Poor me. But it works!

Thanks.

PS, this is the current result. The colours for Temp and humidity are not matching 100%, but that will be a small fix. The Abs. Humidity will be a 3rd graph, below the current 2:
![image](https://user-images.githubusercontent.com/18028618/201534373-63bf7048-c6bf-4905-862c-0db2e36759fd.png)

Yes, it's rather cold in the house, but I'm away for 2 weeks, since 9th (evening), so very little natural and no artificial heating, in a 1970's house...

**Comment by dbuezas** [comment, marked as answer]
Setting the period to 5minutes (implies statistic: mean) makes the timestamps of both sensor to align perfectly, allowing to easily make mathematical operations using both sensors

![Screenshot_20221113-183235_Home Assistant](https://user-images.githubusercontent.com/777196/201535691-cf69897b-d29e-4b6e-a16b-24351a6b4727.jpg)


```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.wintergarten_clima_temperature
    period: 5minute
    lambda: |-
      (ys ,xs) => {
        window.temperature = {xs,ys};
        return ys;
      }
  - entity: sensor.wintergarten_clima_humidity
    period: 5minute
    name: Absolute Hty
    unit_of_measurement: g/m³
    lambda: |-
      (ys, xs) => {
        const t = window.temperature;
        const h = {xs, ys:ys.map(parseFloat)};
        return h.ys.map((rh, i) => {
          const T = parseFloat(t.ys[i-1]);
          return (6.112 * Math.exp((17.67 * T)/(T+243.5)) * rh * 2.1674)/(273.15+T);
        }) 
      }
  - entity: sensor.wintergarten_clima_humidity
    period: 5minute
hours_to_show: 24

```
