### DISCUSSION TITLE
Plot of the downloads of github any repo.

### DISCUSSION THREAD

**Discussion by dbuezas** [dbuezas/lovelace-plotly-graph-card#150] [Show and tell]
Using this repo as example:

# Create template sensor
In `configuration.yaml`
```yaml
sensor:
  - platform: rest
    resource: https://api.github.com/repos/dbuezas/lovelace-plotly-graph-card/releases/latest
    name: Plotly Graph Card Latest Downloads
    value_template: "{{ value_json.assets[0].download_count }}"
    headers:
      Content-Type: application/json
      Authorization: !secret github_public_access_token # OPTIONAL. Without a token, you may get rate limited 
```

# Plot
<img width="405" alt="image" src="https://user-images.githubusercontent.com/777196/202246699-f9133d10-f952-46c1-9168-ec1437f55381.png">

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.plotly_graph_card_latest_downloads
    show_value: true

hours_to_show: 4
```
