### DISCUSSION TITLE
How to display a bar graph using a template sensor

### DISCUSSION THREAD

**Discussion by Jn115759** [dbuezas/lovelace-plotly-graph-card#155] [Q&A]
Dear all, I am trying to get some more experience with this wonderfull plotly integration.
However, I am struggling with some aspects of it. Hope some of you are prepared to share your knowledge and help me out. 

I want to achieve a bar graph with the daily net energy consumption.
For this I am using a template sensor [sensor.energy_grid_net_consumption_x] which is based on 2 utility meters being reset every day.

```
- sensor:
    - name: "Energy Grid Net Consumption (x)"
      unit_of_measurement: "kWh"
      state: >
        {{ (states('sensor.energy_grid_import_x')|float - states('sensor.energy_grid_return_x')|float) | round(2) }}
      device_class: energy
      unique_id: "x202211121744"
```
 
This sensor is working fine. I can display the value over the day ;-)
![image](https://user-images.githubusercontent.com/91130738/202914481-cd5a6376-4535-4340-b17c-a2a5505f4af6.png)

However, I would now like to display a bar chart with a daily consumption, meaning I need to display the max of the sensor since the value of the sensor accumulates and is reset at 12pm.

```
type: custom:plotly-graph
entities:
  - entity: sensor.energy_grid_net_consumption_x
    statistic: max
    period: day
    type: bar
hours_to_show: 288
title: Daily NET energy consumption
refresh_interval: 30
```

However, this does not seem to work. I only got an empty graph.
Any feedback is very appreciated.

![image](https://user-images.githubusercontent.com/91130738/202914716-c443a938-fbf2-4fdc-b796-9a438dd07ad8.png)

**Comment by miljbee** [comment]
Hello,

Need to be improved, but you'll have a good starting point:

![image](https://user-images.githubusercontent.com/637997/206728626-b2b3b544-541a-4697-9cea-4c48d6623b2a.png)

```
type: custom:plotly-graph
entities:
  - entity: sensor.pm_main_kwh
    statistic: sum
    period: hour
    lambda: |-
      (ys, xs) => {
        last = ys[0]
        xs.shift()
        ys.shift()
        y = ys.map(y => {
          ret = y-last
          last = y
          return ret
        } )
        return { x: xs, y:y}
      }
    type: bar
hours_to_show: 24
refresh_interval: 10

**Comment by bazcurtis** [comment]
I have a similar issue. I tried to follow the above, but lambda is now longer used. I am trying to replicate these cards.

This is the yaml I tried for the bottom one

```
type: custom:plotly-graph
entities:
  - entity: sensor.ts_todays_electricity_fixed_export_compensation
    statistic: state
    period: day
    type: bar
  - entity: sensor.ts_todays_electricity_credit_or_debit
    statistic: state
    period: day
    type: bar
hours_to_show: 168
refresh_interval: 30
title: Energy Cost
```

![Screenshot 2024-11-07 at 09 14 13](https://github.com/user-attachments/assets/21e6b136-511d-4d7b-a286-ca22dd57a4c7)

**Reply by dbuezas** [reply]
To replace lambdas see the filters section in the readme. You can either code a filter yourself (harder) or use a combination of filters (easier) to do maths on the data.

For the indicators at the top see: https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/364#discussioncomment-8231838

If you get weird bar widths, see https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/314#discussioncomment-8697420

**Reply by bazcurtis** [reply]
Thanks for the quick reply. I am new to this so still trying to work it out. I think once I have a few migrated I will have a good foundation.

**Reply by dbuezas** [reply]
There's an index of discussions with images linked in the readme, that can be useful.
Good luck!

**Reply by bazcurtis** [reply]
Sorry, one more question. What am I trying to achieve with the filter? Why is a template sensor different to a normal sensor?

**Reply by dbuezas** [reply]
If you use filters you don't need a template sensor

**Reply by bazcurtis** [reply]
So I just do the maths with the sensors I used to make the template sensor? If those sensors get reset to zero, say via a reboot Plotly will remember the previous value? You can see this template sensor is made up of two other template sensors.

```
# Today's Electricity Credit or Debit
  - trigger:
      - platform: state
        entity_id:
          - sensor.ts_todays_total_electricity_cost
          - sensor.ts_todays_electricity_fixed_export_compensation
        to:
    sensor:
      - name: "TS Todays Electricity Credit or Debit"
        unique_id: ts_todays_electricity_credit_or_debit
        state: >-
          {{ states('sensor.ts_todays_total_electricity_cost') | float(0) - states('sensor.ts_todays_electricity_fixed_export_compensation') | float(0) }}
        unit_of_measurement: 'GBP' 
        device_class: "monetary"
```

**Reply by dbuezas** [reply]
Plotly won't remember anything, but the sensor history db will.

**Reply by dbuezas** [reply]
Of course this doesn't apply it you use the template sensors for other things (e.g automations)
The cool thing is that you don't need to wait for the template sensor to gather data

**Reply by bazcurtis** [reply]
That for helping out. Really appreciate it. I think I have made some progress. The result looks weird, but I will look at your previous answer for that. I don't think I have the multiplier correct.

```
type: custom:plotly-graph
entities:
  - entity: sensor.lux_power_to_grid_daily
    filters:
      multiply: 0.15
    name: |
      $ex "Export"  + " " + "(" + ys.at(-2) +")p" 
    statistic: state
    period: day
    type: bar
  - entity: sensor.octopus_energy_electricity_21m02794_current_accumulative_cost
    name: |
      $ex "Daily Cost" + " (" + parseFloat(ys.at(-1)).toFixed(2) + ")p"
    statistic: state
    period: day
    type: bar
hours_to_show: 10d
refresh_interval: 30
title: Energy Cost
```
<img width="472" alt="Screenshot 2024-11-07 at 17 39 52" src="https://github.com/user-attachments/assets/af0bd35b-5223-435a-87fe-2b449b29d835">

**Reply by dbuezas** [reply]
getting there!
you forgot the `-` (minus) before `multiply`
```yaml
filters:
     - multiply: 0.15
```

the skinny bar is because home assistant invents a datapoint at the start of the requested time interval. You can add a another filter to discard the first datapoint:
```yaml
filters:
    - multiply: 0.15
    - filter: i >0

```

**Reply by bazcurtis** [reply]
I think I cracked it. I have missing an orange bar to the left, but I am not too fuzzed about that. Unfortunately not enough exporting this time of year to really see it properly. The orange bar can go negative in the summer. Sorry about the missing -, silly mistake.

Off to swap over another ApexChart card 😀

Is there somewhere I can post a screenshot and the code to help others?

```
type: custom:plotly-graph
entities:
  - entity: sensor.lux_power_to_grid_daily
    unit_of_measurement: GBP
    filters:
      - multiply: 0.15
      - filter: i >0
    name: |
      $ex " Export" + " (" + parseFloat(ys.at(-1)).toFixed(2) + ")p"
    statistic: state
    period: day
    type: bar
  - entity: >-
      sensor.octopus_energy_electricity_21m0279424_current_accumulative_cost
    name: |
      $ex "Cost" + " (" + parseFloat(ys.at(-1)).toFixed(2) + ")p"
    statistic: state
    period: day
    type: bar
hours_to_show: 10d
refresh_interval: 30
title: Energy Cost
```
<img width="384" alt="Screenshot 2024-11-07 at 19 51 17" src="https://github.com/user-attachments/assets/1817af7d-0b8e-4503-80e9-38ee5d8194b0">
<img width="391" alt="Screenshot 2024-11-07 at 19 52 48" src="https://github.com/user-attachments/assets/a63dfe50-edb3-4c99-a17b-5c8a075129b5">
