### DISCUSSION TITLE
Skipping x-axis values where y-value is non-existing, rangebreaks

### DISCUSSION THREAD

**Discussion by Joc007** [dbuezas/lovelace-plotly-graph-card#159] [Q&A] [answered]
Hi!

I can not figure out how to configure [rangebreaks](https://plotly.com/python/reference/layout/xaxis/#layout-xaxis-rangebreaks) (also [explained here](https://plotly.com/python/time-series/)).

My use case is the following. I have the sensor that provides data very sparsely (max 2 times per day, usually 2-3 times per week). I am not interested in the gaps between updates, I'm interested in comparing subsequent readouts.
I'm monitoring bilge pump operation: whenever the pump does a "cycle" (off->on->off), the sensor (ESP home) reports, average current and number of seconds the pump was operational. If the current and/or duration starts acting funny, I know that I should be carefully observing what is going on...

I think it would need to be something like this:
```
layout:
  xaxis:
    type: date
    rangebreaks:
       <- cannot figure this part ->

```
I tried alternative option, which works kind-of OK, though it hinders time-panning capabilities:
```
layout:
  xaxis:
    type: category
```

Also, perhaps I should use lambda and x,y mapping...

I'd appreciate any hint. Thanks,
 Joc.

**Comment by Joc007** [comment]
Hm... just realized that if I would want also to plot 1 month or 1 year of data, I'd need to store data somewhere else than in the `recorder` component :(  Since I have already InfluxDB and Grafana installed, I guess that would now be the way to explore in parallel.

Still looking forward to get any hints wrt `rangebreaks`

**Comment by dbuezas** [comment, marked as answer]
Hi Joc,
I didn't know about rangebreaks, nice finding!
I played with it a bit and I first missed the fact that rangebreaks is actually an array:
```yaml
layout:
  xaxis:
    rangebreaks:
      - pattern: day of week
        bounds: # this will hide Saturdays and Sundays.
          - sat
          - mon
```

Regarding "older" data, try using long term statistics:
```yaml
- entity: sensor.thing
  statistic: mean
```

More [here](https://github.com/dbuezas/lovelace-plotly-graph-card#statistics-support)
