### DISCUSSION TITLE
End the graph line with a marker and current value

### DISCUSSION THREAD

**Discussion by dbuezas** [dbuezas/lovelace-plotly-graph-card#16] [Show and tell]
Extract from #15 

![image](https://user-images.githubusercontent.com/777196/147880424-6d4a1e15-7d64-420a-ae78-ac949ee1cbc5.png)

```yaml
type: custom:plotly-graph-dev
entities:
  - entity: sensor.openweathermap_temperature # the lines
    legendgroup: sensor.openweathermap_temperature
    yaxis: y1
    line:
      color: '#1f77b4'
  - entity: sensor.openweathermap_temperature # the text
    legendgroup: sensor.openweathermap_temperature
    yaxis: y1
    unit_of_measurement: W floor
    mode: text+markers
    texttemplate: '%{y}'
    textposition: middle right
    showlegend: false
    marker:
      color: '#1f77b4'
    textfont:
      color: '#1f77b4'
    lambda: (ys) => ys.map((y,i)=> (i=== ys.length-1) && y)
  - entity: sensor.openweathermap_temperature # the invisible marker to make space for the text
    legendgroup: sensor.openweathermap_temperature
    yaxis: y1
    mode: markers
    showlegend: false
    marker:
      opacity: 0
      size: 50
    lambda: (ys, xs) => ys.map((y,i)=> (i=== ys.length-1) && y)
hours_to_show: 24
refresh_interval: 10

```
