### DISCUSSION TITLE
Filters

### DISCUSSION THREAD

**Discussion by dbuezas** [dbuezas/lovelace-plotly-graph-card#168] [Announcements]
## What's Changed
* Filters suport
* Deprecated lambdas - WARNING there may be some incompatibilities

Instructions in the readme of the draft branch [here](https://github.com/dbuezas/lovelace-plotly-graph-card/blob/feat/add-esphome-style-filters/readme.md#filters)

**Full Changelog**: https://github.com/dbuezas/lovelace-plotly-graph-card/compare/v1.8.4...v2.0.0-beta

<hr /><em>This discussion was created from the release <a href='https://github.com/dbuezas/lovelace-plotly-graph-card/releases/tag/v2.0.0-beta'>Filters</a>.</em>

**Comment by dbuezas** [comment]
# Warning: beta version, some filters may change before production release

# Examples

## Celcious to farenheit

```yaml
- entity: sensor.wintergarten_clima_temperature
  unit_of_measurement: °F
  filters: # °F = °C×(9/5)+32
    - multiply: 1.8
    - add: 32
```

alternatively,

```yaml
- entity: sensor.wintergarten_clima_temperature
  unit_of_measurement: °F
  filters: # °F = °C×(9/5)+32
    - map_y_numbers: y * 9/5 + 32
```

## Energy from power

```yaml
- entity: sensor.fridge_power
  filters:
    - integrate:
        unit: h # resulting unit_of_measurement will be W/h
```

## Using state attributes

```yaml
- entity: climate.loungetrv_climate
  attribute: current_temperature # an attribute must be set to ensure attributes are fetched.
  filters:
    - map_y_numbers: state.state === "heat" ? state.attributes.current_temperature : 0
```

## more in the branch's readme [here](https://github.com/dbuezas/lovelace-plotly-graph-card/blob/feat/add-esphome-style-filters/readme.md#filters)!

**Reply by mwrben** [reply]
Thanks for this, plotly is marvellous! I can't see quite how to convert lambda: '(ys) => ys.map(y => (y == ''on'') ? 1 : 0)' to a filter. I tried          - map_y: y === "on" ? 1 : 0 but that didn't work. It's for converting a binary on / off value to either 1 or 0 on the plot

**Reply by dbuezas** [reply]
Thanks! I'm really happy with how the filters worked out.
The issue is likely just yaml not liking the colon. Here are some variations:
```yaml
type: custom:plotly-graph-dev
title: binary sensor
entities:
  - entity: binary_sensor.flur_motion
    filters:
      - map_y: |- 
          y === "on" ? 1 : 0
  - entity: binary_sensor.flur_motion
    filters:
      - map_y: y === "on" ? 3:2
  - entity: binary_sensor.flur_motion
    filters:
      - map_y: 'y === "on" ? 5 : 4' # yaml doesn't like the colon when written like this and unescaped  
```
![image](https://user-images.githubusercontent.com/777196/211142846-cf74599e-7031-4005-ae10-05b9ff44a10c.png)

---
BTW, next time please paste your yaml and/or a screenshot. It's easy to know what went wrong :) 
Did you pick this from an example? If so, feel free to correct it by clicking on the pencil at the top right of the readme, then editing, and then "create branch and start a pull request"

**Reply by mwrben** [reply]
Thank you. Your suggestion of how to write it into yaml worked.

On a separate (minor) note, I think the yaml example in the readme needs re-aligning. Presumably the line starting filters: needs to be 
re-aligned further along. 

type: custom:plotly-graph
entities:
  - entity: sensor.temperature_in_celsius
  filters:
    # The filters below will only be applied to numeric values. Missing (unavailable) and non-numerics will be left untouched
    - add: 5 # adds 5 to each datapoint

**Reply by dbuezas** [reply]
Can you edit your message like this:
` ```yaml ` 
`like: this`
` ``` `

It's hard to read otherwise:)

**Reply by dbuezas** [reply]
Also, please try editing the readme yourself. You can do it from the browser. I'll review it make any necessary correction and merge it :)

**Reply by dbuezas** [reply]
Oh, I see, the example in the readme was missing the outer quotes. I fixed it now.

**Comment by dbuezas** [comment]
Small example of how simple it will be to do complex operations

<img width="395" alt="image" src="https://user-images.githubusercontent.com/777196/210340817-b4a8adb7-2fb9-4134-b7e3-59eb181b6b9e.png">

```yaml
type: custom:plotly-graph
title: Smoothing
entities:
  - entity: sensor.openweathermap_wind_speed
  - entity: sensor.openweathermap_wind_speed
    name: Moving window average
    filters:
      - sliding_window_moving_average:
          extended: true
          window_size: 20
  - entity: sensor.openweathermap_wind_speed
    name: Moving window median
    filters:
      - median:
          extended: true
          window_size: 20

hours_to_show: 240

```

**Comment by dbuezas** [comment]
<img width="387" alt="image" src="https://user-images.githubusercontent.com/777196/210430540-e70c049a-b6b6-4ed6-aca4-b2ba3fd0c86b.png">

```yaml
type: custom:plotly-graph
title: Forecast
offset: 1.5d
entities:
  - entity: sensor.openweathermap_rain
    legendgroup: 1
    name: Precipitation
  - entity: weather.openweathermap
    legendgroup: 1
    showlegend: false
    name: Precipitation
    line:
      dash: dot
      shape: spline
    unit_of_measurement: mm
    filters:
      - fn: |-
          ({ meta }) => ({
            xs: meta.forecast.map(({ datetime }) => new Date(datetime)),
            ys: meta.forecast.map(({ precipitation }) => precipitation),
          })
  - entity: sensor.openweathermap_temperature
    legendgroup: 2
    name: Temperature
  - entity: weather.openweathermap
    legendgroup: 2
    showlegend: false
    name: Temperature
    line:
      dash: dot
      shape: spline
    unit_of_measurement: °C
    filters:
      - fn: |-
          ({ meta }) => ({
            xs: meta.forecast.map(({ datetime }) => new Date(datetime)),
            ys: meta.forecast.map(({ temperature }) => temperature),
          })
  - entity: sensor.openweathermap_wind_speed
    legendgroup: 3
    name: Wind speed
  - entity: weather.openweathermap
    legendgroup: 3
    showlegend: false
    name: Wind speed
    line:
      dash: dot
      shape: spline
    unit_of_measurement: m/s
    filters:
      - fn: |-
          ({ meta }) => ({
            xs: meta.forecast.map(({ datetime }) => new Date(datetime)),
            ys: meta.forecast.map(({ wind_speed }) => wind_speed),
          })
color_scheme:
  - '#1f77b4'
  - '#1f77b4'
  - '#d62728'
  - '#d62728'
  - '#7fc97f'
  - '#7fc97f'
hours_to_show: 72
```

**Comment by b3nn0** [comment]
Just upgraded to the new version and started to replace my Lambdas.
AWESOME! it's so much simpler. THANK YOU!

I only failed replacing one of them. Now I wonder if I'm missing something, or if it might be a nice feature suggestion:
With Statistics and auto-ranging, the X axis interval can be quite flexible, showing 5 minute to monthly intervals depending on zoom.
I have a water meter (and gas meter) delivering an absolute value, and I'm creating a bar chart by derivative of the statistics sensor.
To do so, I simply subtract the "previous" value from each value. And due to auto-ranging, I get a "5 minute water usage" bar chart or a "monthly water usage bar chart".

However, the derivative-function of the filters seems to require a time-unit, so I can only create fixed bar charts (e.g. water usage per hour).
Would it be able to add a "derivative from last value" option or something, so this becomes possible?
Or is there another way to achieve something like this?

Yaml:
```
type: custom:plotly-graph
title: Wasserverbrauch
entities:
  - entity: sensor.wasserzahler
    name: Wasserverbrauch
    statistic: sum
    unit_of_measurement: L
    period: auto
    showlegend: false
    show_value: false
    type: bar
    texttemplate: '%{y}'
    lambda: |-
      (ys, xs) => {
        const res = []
        for (let i = 1; i < ys.length; i++) {
          res.push((ys[i] - ys[i-1]) * 1000)
        }
        xs.shift()
        return {x: xs, y: res }
      }
defaults:
  yaxes:
    fixedrange: true
hours_to_show: 48
refresh_interval: 10
```

Additionally, the unit seems to not work correctly for me in the derivate filter..
If I just put `derivate:` in there, I get a hourly derivate graph (L/h).
However, if I put anything else there (including unit: h), I get no graph at all:

![grafik](https://user-images.githubusercontent.com/1858945/211145109-678b4715-dc57-42a7-ba09-af249826ed96.png)
![grafik](https://user-images.githubusercontent.com/1858945/211145127-f3df615e-e42b-4556-9a58-5aad26422c97.png)


EDIT: Oops: If I indent the "unit:" one less, I do get a graph, but it's always hourly..?

**Reply by dbuezas** [reply]
The indentation was correct, I think the issue here is a misunderstanding: the unit doesn't determine how many columns you have, it determines the scaling factor.
For example: you can plot km/h with a datapoint each minute, but you can plot km/h with a datapoint per day. I think what you are after is `- resample: 1d` (see more in the readme). 
Something like this:
```yaml
  - entity: sensor.wasserzahler
     filters:
       - resample: 1d
       - derivate:
            unit: d
```

**Reply by b3nn0** [reply]
Hmm, not sure what the scaling factor means in that context, or what difference it would make (per day derivative is the same, no matter if I have 1d samples or 1h samples, no?)

Anyway, this one:
```
       - resample: 1d
       - derivate:
            unit: d
```
produces the same result for me: a completely empty graph.
Removing the "unit: d" creates a daily "L/h" graph - just the same as without "resample: 1d". E.g. if I use 240L/d, it will show "10.0", because 24*10L = 240L.

And it also doesn't really solve the nice behaviour of `period: auto` statistics, with "dynamic resampling duration depending on zoom".

I'm fine with keeping it a lambda for now, so at least the `period: auto` part isn't too important, just nice to have.
But I just can't seem to get any thing to work when specifying `unit: ...`?

**Reply by b3nn0** [reply]
Ah.. that's why:
Error: Filter 'derivat must be [force_numeric,add,multiply,calibrate_linear,derivate,integrate,sliding_window_moving_average,median,exponential_moving_average,map_y_numbers,map_y,map_x,resample,store_var,fn,filter]

EDIT: never mind.. that was just while typing.. it shows no error in the console.

**Reply by dbuezas** [reply]
> not sure what the scaling factor means in that context

It is exactly what you wrote below: `I use 240L/d, it will show "10.0", because 24*10L = 240L.`

> But I just can't seem to get any thing to work when specifying unit: ...?

Mmmm you may have found a bug. Would you rise an issue so I don't forget to look into it?

**Reply by dbuezas** [reply]
Ohhhh nevermind, the readme is wrong. It should be `derivate: 1d` without the `unit` subobject.

**Reply by dbuezas** [reply]
I updated the readme, thanks for reporting this! I think I misunderstood you the first time, I thought you expected to have one bar a day with `derivate: 1d`.
Regarding dynamic resampling, I could add it if you convince me of its utility :). Feel free to open a feature request and put some screenshots and scribbles of what you intend to do with it.

**Comment by kaijk** [comment]
I'm trying to move kWh bar charts for daily, and hourly, and stacked daily and hourly (by time of day) energy from lambda to filters.  No joy.  The data come from Watt readings.  What I'm trying to accomplish is to have bar graphs begin at midnight 'x'  days or months, or some hours ago and continue through the current partial period, with multiple traces stacked by separate on-peak, off-peak accumulations (for which I have separate Watt sensors).
  
Here is my simplest setup, trying to achieve one column per day with a single series, no stacking. In HA I use the Rhimann integration with the `left` method against this same sensor to get energy: 
```
 - type: custom:plotly-graph
    entities:
      - entity: sensor.power_meter_total_watts
        type: bar
        filters:
          - integrate: d
    hours_to_show: 72
    refresh_interval: 30
    title: Energy Consumption Daily
    layout:
      yaxis:
        title: Wh per Day
```
This produces three days of continuously increasing interval data, not binned by day, but in bar format by native intervals that looks more like a fill.
![image](https://user-images.githubusercontent.com/49624034/211213810-07dfdf74-2b26-4969-b51c-43eaf6e96c25.png)
Removing the `type: bar` just removes the "fill" appearance.
![image](https://user-images.githubusercontent.com/49624034/211213675-a8058413-5353-4d38-b349-d93969291607.png)

If I use `integrate: 1d` as noted above for `derivate`, I get a graph full of NANs. (BTW, I like the idea of `xd` to specify a multi-day period over which to integrate (or `0d` for just the current day) ).
![image](https://user-images.githubusercontent.com/49624034/211213713-ff6a6b97-d372-4f15-8867-7d65b093f112.png)

This is the most complex example I'm trying to reproduce that uses lambda. It happens to be hourly, but I also want monthly and daily by Bus and by TOD, stacked.  Computation efficiency is important to not overwhelm my RasPi 4, if possible.
![image](https://user-images.githubusercontent.com/49624034/211214223-effd50da-ea5e-4821-bd4c-b0562d872814.png)
