### DISCUSSION TITLE
Heatpump data with multiple axes and end value

### DISCUSSION THREAD

**Discussion by markuska00** [dbuezas/lovelace-plotly-graph-card#17] [Show and tell]
I want to start with thanking for a fantastic custom graph card!! 😃 👍 

I like the multiple axes function which is amazing when going forward and backward in time.

And being able to show the current value at the end of the line is perfect for me.

![Skärmbbbbklipp](https://user-images.githubusercontent.com/37914650/148646429-34f32f23-20b8-4171-87d3-ca69d8ab34b1.JPG)

```
type: custom:plotly-graph
entities:
  - entity: sensor.nibe_36061_40004
    yaxis: y1
    unit_of_measurement: Yttertemp
    line:
      color: steelblue
  - entity: sensor.nibe_36061_40004
    yaxis: y1
    mode: text+markers
    texttemplate: <b> %{y} </b>°C
    textposition: middle right
    marker:
      color: steelblue
    textfont:
      color: steelblue
    lambda: (ys) => ys.map((y,i)=> (i=== ys.length-1) && y)
  - entity: sensor.nibe_36061_40004
    yaxis: y1
    mode: markers
    marker:
      opacity: 0
      size: 55
    lambda: (ys, xs) => ys.map((y,i)=> (i=== ys.length-1) && y)
  - entity: sensor.nibe_36061_43005
    yaxis: y2
    line:
      color: orange
    unit_of_measurement: Gradminuter
  - entity: sensor.nibe_36061_43005
    yaxis: y2
    mode: text+markers
    texttemplate: <b> %{y} </b>GM
    textposition: middle right
    marker:
      color: orange
    textfont:
      color: orange
    lambda: (ys) => ys.map((y,i)=> (i=== ys.length-1) && y)
  - entity: sensor.nibe_36061_43009
    yaxis: y3
    line:
      color: deepskyblue
    unit_of_measurement: Framledning
  - entity: sensor.nibe_36061_43009
    yaxis: y3
    mode: text+markers
    texttemplate: <b> %{y:.3} </b>°C
    textposition: middle right
    marker:
      color: deepskyblue
    textfont:
      color: deepskyblue
    lambda: (ys) => ys.map((y,i)=> (i=== ys.length-1) && y)
  - entity: sensor.nibe_36061_40008
    yaxis: y3
    line:
      color: green
    unit_of_measurement: Framledning
  - entity: sensor.nibe_36061_40008
    yaxis: y3
    mode: text+markers
    texttemplate: <b> %{y:.3} </b>°C
    textposition: middle right
    marker:
      color: green
    textfont:
      color: green
    lambda: (ys) => ys.map((y,i)=> (i=== ys.length-1) && y)
  - entity: sensor.nibe_36061_43123
    yaxis: y4
    line:
      color: orange
    unit_of_measurement: Kompressor
  - entity: sensor.nibe_36061_43123
    yaxis: y4
    mode: text+markers
    texttemplate: <b> %{y} </b>Hz
    textposition: middle right
    marker:
      color: orange
    textfont:
      color: orange
    lambda: (ys) => ys.map((y,i)=> (i=== ys.length-1) && y)
  - entity: sensor.nibe_36061_43136
    yaxis: y4
    line:
      color: steelblue
    unit_of_measurement: Kompressor
  - entity: sensor.nibe_36061_43136
    yaxis: y4
    mode: text+markers
    texttemplate: <b> %{y} </b>Hz
    textposition: middle right
    marker:
      color: steelblue
    textfont:
      color: steelblue
    lambda: (ys) => ys.map((y,i)=> (i=== ys.length-1) && y)
  - entity: sensor.varmepump_pris_kw
    yaxis: y5
    unit_of_measurement: kr/timma
    line:
      color: steelblue
  - entity: sensor.varmepump_pris_kw
    yaxis: y5
    mode: text+markers
    texttemplate: <b> %{y:.3} </b>kr
    textposition: middle right
    marker:
      color: steelblue
    textfont:
      color: steelblue
    lambda: (ys) => ys.map((y,i)=> (i=== ys.length-1) && y)
  - entity: sensor.pris_varmepump_snitt_dygn
    yaxis: y5
    line:
      color: deepskyblue
  - entity: sensor.pris_varmepump_snitt_dygn
    yaxis: y5
    mode: text+markers
    texttemplate: <b> %{y:.3} </b>kr
    textposition: middle right
    marker:
      color: deepskyblue
    textfont:
      color: deepskyblue
    lambda: (ys) => ys.map((y,i)=> (i=== ys.length-1) && y)
  - entity: sensor.nibe_36061_43084
    yaxis: y5
    line:
      color: orange
    unit_of_measurement: kr/timma
  - entity: sensor.nibe_36061_43084
    yaxis: y5
    mode: text+markers
    texttemplate: <b> %{y} </b>kW
    textposition: middle right
    marker:
      color: orange
    textfont:
      color: orange
    lambda: (ys) => ys.map((y,i)=> (i=== ys.length-1) && y)
  - entity: sensor.nibe_36061_10069
    yaxis: y6
    unit_of_measurement: Elpris
    line:
      color: green
  - entity: sensor.nibe_36061_10069
    yaxis: y6
    mode: text+markers
    texttemplate: <b> %{y:.3} </b>öre
    textposition: middle right
    marker:
      color: green
    textfont:
      color: green
    lambda: (ys) => ys.map((y,i)=> (i=== ys.length-1) && y)
  - entity: sensor.nordpool_dygnspris_el
    yaxis: y6
    line:
      color: deepskyblue
  - entity: sensor.nordpool_dygnspris_el
    yaxis: y6
    mode: text+markers
    texttemplate: <b> %{y:.3} </b>öre
    textposition: middle right
    marker:
      color: deepskyblue
    textfont:
      color: deepskyblue
    lambda: (ys) => ys.map((y,i)=> (i=== ys.length-1) && y)
no_default_layout: true
default_trace:
  line:
    width: 1.5
layout:
  plot_bgcolor: white
  dragmode: pan
  margin:
    t: 30
    l: 55
    r: 30
    b: 50
    pad: 5
  showlegend: false
  height: 650
  yaxis:
    gridcolor: whitesmoke
    zeroline: false
    fixedrange: true
  yaxis2:
    gridcolor: whitesmoke
    fixedrange: true
    zeroline: false
  yaxis3:
    gridcolor: whitesmoke
    zeroline: false
    range:
      - 24
      - 40
    fixedrange: true
  yaxis4:
    gridcolor: whitesmoke
    zeroline: false
    fixedrange: true
  yaxis5:
    gridcolor: whitesmoke
    zeroline: false
    fixedrange: true
  yaxis6:
    gridcolor: whitesmoke
    zeroline: false
    fixedrange: true
  yaxis7:
    gridcolor: whitesmoke
    fixedrange: true
  grid:
    ygap: 0.07
    rows: 6
    columns: 1
    pattern: coupled
    roworder: top to bottom
  xaxis:
    gridcolor: whitesmoke
    rangeselector:
      'y': 1.01
      buttons:
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
hours_to_show: 12
refresh_interval: 60
```

**Comment by dbuezas** [comment]
Wow!

**Comment by dbuezas** [comment]
I think your use case is a really good one and you made use of all features! 🎉 

I'm not that happy with how repetitive the yaml gets, I may consider adding some extra configs at some point to auto generate this kinds of configs. It is such a pitty that yaml [anchors](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/) get expanded when one saves the configs in lovelace.

If you have ideas on how the configuration may look like, let me know!

I was thinking in something like:
```yaml
defaults:
  entities:
     entity:
       trace: ...#default for all traces
       last_value_text:
         show: true
         texttemplate: ...
  layout:
      yaxes: ...#default for all y axes

```

**Comment by dbuezas** [comment]
btw, did you find a better way to have enough right margin in the x-axis for the text?

**Comment by markuska00** [comment]
It would have been great with common settings.  😃 


To adjust the right margin I tried to force
```
xaxis: 
  range:
    - "2022-01-08 04:00:00.0000"
    - "2022-01-08 18:00:00.0000"
```
(When the time is 16:00)

So I chose 14 hours in range even though I have 12 hours on the hours_to_show:. 

But I never managed to get the time on range to change automatically.

**Comment by dbuezas** [comment]
Oh, you gave me an Idea!
Add another entity and use the new secondary lambda signature:
```js
(ys, xs)=> ({ x: [xs[xs.length-1] + 1000*60*60*2], y: ys.slice(-1) })
```
Then color: transparent.
This extra entity will be 2 hours into the future but not visible. Ugly as hell, but it should work.

I'll think about this for a while. I calculate the range internally and could add an option for this in the future, but until then, this should do it :)

**Reply by markuska00** [reply]
> 

This lambda give me error

**Reply by dbuezas** [reply]
Oh I wrote it my phone so I didn't test it. The x axis are dates, so adding like I had makes a mess with strings.

Here's the fixed version:
```yaml
 - entity: sensor.whatever  
   lambda: |-
      (ys, xs)=> ({ x: [+xs[xs.length-1] + 1000*60*60*2], y: ys.slice(-1) })
```
where `1000*60*60*2` means 2 hours (1000ms * 60 * 6 * 2 = 2h)

**Comment by dbuezas** [comment]
Btw, I currently use the right axis for all entities with a different unit_of_measurement than the first one, I could change it to this swimlane style. Then this would happen automatically. And an extra option for the number value at the end. I'll think about this.

**Comment by dbuezas** [comment]
Just released the new version!

you can remove all your helper traces and just add:
```yaml
defaults:
  entity:
    show_value: true
```

and if you'd like to try new colors, use
```yaml
color_scheme: 3 # or any number between 0 and 24
```

**Comment by dbuezas** [comment]
You can now also do 
```yaml
defaults:
  yaxis:
    gridcolor: whitesmoke
    zeroline: false
    fixedrange: true
```
and remove all your individual yaxis1,2,3,45,6,7 fixes

**Comment by markuska00** [comment]
Very nice  😄 

Much cleaner configuration

It is noticeable that on mobile_app everything flows much better now.




Some errors I found.

On the new "defaults:"
gridcolor does not work.
"line with" does not work

I prefer bold text on "show value"
If 2 texts end up just above each other, you see them better with bold text.

The left field that was previously "unit".
Can you have any other text there now?

I still do not manage to get the lambda from above to work to create space to the right.



```
type: custom:plotly-graph
entities:
  - entity: sensor.nibe_36061_40004
    yaxis: y1
    unit_of_measurement: ' GM'
    line:
      color: steelblue
    show_value: true
  - entity: sensor.nibe_36061_43005
    yaxis: y2
    line:
      color: orange
    unit_of_measurement: ' GM'
    show_value: true
  - entity: sensor.nibe_36061_43009
    yaxis: y3
    line:
      color: deepskyblue
    show_value: true
    unit_of_measurement: ' °C'
  - entity: sensor.nibe_36061_40008
    yaxis: y3
    line:
      color: green
    show_value: true
    unit_of_measurement: ' °C'
  - entity: sensor.nibe_36061_43123
    yaxis: y4
    line:
      color: orange
    unit_of_measurement: ' Hz'
  - entity: sensor.nibe_36061_43136
    yaxis: y4
    line:
      color: steelblue
    unit_of_measurement: ' Hz'
  - entity: sensor.varmepump_pris_kw
    yaxis: y5
    unit_of_measurement: ' kr'
    line:
      color: steelblue
  - entity: sensor.pris_varmepump_snitt_dygn
    yaxis: y5
    line:
      color: deepskyblue
    unit_of_measurement: ' kr'
  - entity: sensor.nibe_36061_43084
    yaxis: y5
    line:
      color: orange
    unit_of_measurement: ' kW'
  - entity: sensor.nibe_36061_10069
    yaxis: y6
    unit_of_measurement: ' öre'
    line:
      color: green
  - entity: sensor.nordpool_dygnspris_el
    yaxis: y6
    line:
      color: deepskyblue
    unit_of_measurement: ' öre'
no_default_layout: true
defaults:
  line:
    width: 3
  entity:
    show_value: true
  yaxis:
    gridcolor: smokewhite
    zeroline: false
    fixedrange: true
layout:
  plot_bgcolor: white
  dragmode: pan
  margin:
    t: 30
    l: 55
    r: 30
    b: 50
    pad: 5
  showlegend: false
  height: 650
  yaxis3:
    range:
      - 24
      - 40
  grid:
    ygap: 0.07
    rows: 6
    columns: 1
    pattern: coupled
    roworder: top to bottom
  xaxis:
    gridcolor: whitesmoke
    rangeselector:
      'y': 1.01
      buttons:
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
hours_to_show: 12
refresh_interval: 60

```

![Skäq23123rmklipp](https://user-images.githubusercontent.com/37914650/148688937-e4b7baba-e2d2-423c-b63a-68fe8f950739.JPG)

**Reply by dbuezas** [reply]
> It is noticeable that on mobile_app everything flows much better now.

Yey! It's more efficient when done in the source :)

> On the new "defaults:" gridcolor does not work. 

Oh I probably priotitized the config order wrong. Will fix soon

> "line with" does not work

It goes inside entity
```yaml
defaults:
  entity:
    line:
      width: 3
```

> I prefer bold text on "show value"
 If 2 texts end up just above each other, you see them better with bold text.

You can use texttemplate in the entity, the properties are transfered to the tex trace

> The left field that was previously "unit". Can you have any other text there now?

Oh, did the units disappear?
That's layout.yaxis.title.text. by default I use the units, but you can override them.
https://plotly.com/javascript/figure-labels/

> I still do not manage to get the lambda from above to work to create space to the right.

Can you send me the yaml with the lambda? It works for me so it may be something else.

Thanks for the feedback! It's much more fun when others use it too :)

**Comment by markuska00** [comment]
Here is with lambda and a texttemplate.  😄 
They do not work for me.


```
type: custom:plotly-graph
entities:
  - entity: sensor.nibe_36061_40004
    lambda: '(ys, xs)=> ({ x: [+xs[xs.length-1] + 1000*60*60*2], y: ys.slice(-1) })'
    yaxis: y1
  - entity: sensor.nibe_36061_40004
    yaxis: y1
    unit_of_measurement: ' GM'
    line:
      color: steelblue
    show_value: true
    texttemplate: <b> %{y} </b>°C
  - entity: sensor.nibe_36061_43005
    yaxis: y2
    line:
      color: orange
    unit_of_measurement: ' GM'
    show_value: true
  - entity: sensor.nibe_36061_43009
    yaxis: y3
    line:
      color: deepskyblue
    show_value: true
    unit_of_measurement: ' °C'
  - entity: sensor.nibe_36061_40008
    yaxis: y3
    line:
      color: green
    show_value: true
    unit_of_measurement: ' °C'
  - entity: sensor.nibe_36061_43123
    yaxis: y4
    line:
      color: orange
    unit_of_measurement: ' Hz'
  - entity: sensor.nibe_36061_43136
    yaxis: y4
    line:
      color: steelblue
    unit_of_measurement: ' Hz'
  - entity: sensor.varmepump_pris_kw
    yaxis: y5
    unit_of_measurement: ' kr'
    line:
      color: steelblue
  - entity: sensor.pris_varmepump_snitt_dygn
    yaxis: y5
    line:
      color: deepskyblue
    unit_of_measurement: ' kr'
  - entity: sensor.nibe_36061_43084
    yaxis: y5
    line:
      color: orange
    unit_of_measurement: ' kW'
  - entity: sensor.nibe_36061_10069
    yaxis: y6
    unit_of_measurement: ' öre'
    line:
      color: green
  - entity: sensor.nordpool_dygnspris_el
    yaxis: y6
    line:
      color: deepskyblue
    unit_of_measurement: ' öre'
no_default_layout: true
defaults:
  entity:
    show_value: true
    line:
      width: 1.5
  yaxis:
    gridcolor: black
    zeroline: false
    fixedrange: true
layout:
  plot_bgcolor: white
  dragmode: pan
  margin:
    t: 30
    l: 55
    r: 30
    b: 50
    pad: 5
  showlegend: false
  height: 650
  yaxis3:
    range:
      - 24
      - 40
  grid:
    ygap: 0.07
    rows: 6
    columns: 1
    pattern: coupled
    roworder: top to bottom
  xaxis:
    gridcolor: whitesmoke
    rangeselector:
      'y': 1.01
      buttons:
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
hours_to_show: 12
refresh_interval: 60

**Comment by markuska00** [comment]
With the lambda entity

![Skärdfgdfgmklipp](https://user-images.githubusercontent.com/37914650/148924059-816afaca-b0d6-4a7d-94c6-7e9299ce7d71.JPG)

**Comment by dbuezas** [comment]
I released a new version that should fix the problems you described. For now I marked it as beta.
Can you try it and let me know if it works? I'll also test myself and move it out of beta soon.

![image](https://user-images.githubusercontent.com/777196/149003528-ebf07981-a98a-4127-9ba6-117a328abe05.png)


```yaml
   show_value:
     right_margin: 10 # in percentage of width
```
More here: https://github.com/dbuezas/lovelace-plotly-graph-card#extra-entity-attributes

**Comment by markuska00** [comment]
Right_margin and Texttample  works perfekt  😃 😃 

But still some problem with 
defaults:    yaxis:
    fixedrange: true
    gridcolor: black
    zeroline: false
Nothing in the yaxis works.
Fixedrange did work in the last version but not now.



![Skärmfghfklipp](https://user-images.githubusercontent.com/37914650/149007881-4c7b65c2-ce4a-4b9f-844b-299b81d12c3a.JPG)

```
type: custom:plotly-graph
entities:
  - entity: sensor.nibe_36061_40004
    yaxis: y1
    unit_of_measurement: °C
    line:
      color: steelblue
    show_value:
      right_margin: 10
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
  - entity: sensor.nibe_36061_43005
    yaxis: y2
    line:
      color: orange
    unit_of_measurement: GM
    show_value: true
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
  - entity: sensor.nibe_36061_43009
    yaxis: y3
    line:
      color: deepskyblue
    show_value: true
    unit_of_measurement: °C
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
  - entity: sensor.nibe_36061_40008
    yaxis: y3
    line:
      color: green
    show_value: true
    unit_of_measurement: °C
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
  - entity: sensor.nibe_36061_43123
    yaxis: y4
    line:
      color: orange
    unit_of_measurement: Hz
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
  - entity: sensor.nibe_36061_43136
    yaxis: y4
    line:
      color: steelblue
    unit_of_measurement: Hz
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
  - entity: sensor.varmepump_pris_kw
    yaxis: y5
    unit_of_measurement: kr
    line:
      color: steelblue
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
  - entity: sensor.pris_varmepump_snitt_dygn
    yaxis: y5
    line:
      color: deepskyblue
    unit_of_measurement: kr
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
  - entity: sensor.nibe_36061_43084
    yaxis: y5
    line:
      color: orange
    unit_of_measurement: kW
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
  - entity: sensor.nibe_36061_10069
    yaxis: y6
    unit_of_measurement: öre
    line:
      color: green
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
  - entity: sensor.nordpool_dygnspris_el
    yaxis: y6
    line:
      color: deepskyblue
    unit_of_measurement: öre
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
no_default_layout: true
defaults:
  entity:
    show_value: true
    line:
      width: 1.5
  yaxis:
    fixedrange: true
    gridcolor: black
    zeroline: false
layout:
  plot_bgcolor: white
  dragmode: pan
  margin:
    t: 30
    l: 55
    r: 30
    b: 50
    pad: 5
  showlegend: false
  height: 650
  yaxis:
    gridcolor: whitesmoke
    title:
      text: Utetemp
  yaxis2:
    title:
      text: Gradminuter
  yaxis3:
    title:
      text: Framledning
    range:
      - 24
      - 40
  yaxis4:
    title:
      text: Kompressor
  yaxis5:
    title:
      text: kr/timma
  yaxis6:
    title:
      text: Elpris
  grid:
    ygap: 0.07
    rows: 6
    columns: 1
    pattern: coupled
    roworder: top to bottom
  xaxis:
    gridcolor: whitesmoke
    rangeselector:
      'y': 1.01
      buttons:
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
hours_to_show: 12
refresh_interval: 20

**Reply by dbuezas** [reply]
2 steps forward, 1 back. It looks like I need to start putting tests in place...
I'll fix that soon then. Thanks for the report! :)

**Comment by markuska00** [comment]
Another question.    😄 
On the texttemplate
Is it possible to use data from Home Assistant?
For example state from another sensor

**Reply by dbuezas** [reply]
Not at the moment, but doable for sure. Can you write down how you envision the yaml for that?

**Reply by markuska00** [reply]
If it had been possible to write  %{states.sensor.whatever.state}  it would have been great.  😄

**Reply by dbuezas** [reply]
Oh. That would be cool, I'd need to parse the templates and fetch the data, match the closest timestamps and inject it in the right place. Unfortunately not enough time for that at the moment.
You can achieve something similar by adding the other entity, then making it transparent, and then changing hovermode to `x`.

```yaml
entities:
    - entity: sensor.toplot
    - entity: sensor.the_hidden_one
       line:
         color: transparent
layout:
  hovermode: x
```

**Comment by dbuezas** [comment]
@markuska00 please try v1.1.2
Note that you can now remove a lot of config.
Also note that `defaults/yaxis` is now called `default/yaxes`
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.nibe_36061_40004
    yaxis: y1
  - entity: sensor.nibe_36061_43005
    yaxis: y2
  - entity: sensor.nibe_36061_43009
    yaxis: y3
  - entity: sensor.nibe_36061_40008
    yaxis: y3
  - entity: sensor.nibe_36061_43123
    yaxis: y4
  - entity: sensor.nibe_36061_43136
    yaxis: y4
  - entity: sensor.varmepump_pris_kw
    yaxis: y5
  - entity: sensor.pris_varmepump_snitt_dygn
    yaxis: y5
  - entity: sensor.nibe_36061_43084
    yaxis: y5
  - entity: sensor.nibe_36061_10069
    yaxis: y6
  - entity: sensor.nordpool_dygnspris_el
    yaxis: y6
no_default_layout: true
defaults:
  entity:
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
    show_value:
      right_margin: 10
    line:
      width: 1.5
  yaxes:
    fixedrange: true
    gridcolor: black
    zeroline: false
layout:
  plot_bgcolor: white
  dragmode: pan
  margin:
    t: 30
    l: 55
    r: 30
    b: 50
    pad: 5
  showlegend: false
  height: 650
  yaxis:
    gridcolor: whitesmoke
    title:
      text: Utetemp
  yaxis2:
    title:
      text: Gradminuter
  yaxis3:
    title:
      text: Framledning
    range:
      - 24
      - 40
  yaxis4:
    title:
      text: Kompressor
  yaxis5:
    title:
      text: kr/timma
  yaxis6:
    title:
      text: Elpris
  grid:
    ygap: 0.07
    rows: 6
    columns: 1
    pattern: coupled
    roworder: top to bottom
  xaxis:
    gridcolor: whitesmoke
    rangeselector:
      'y': 1.01
      buttons:
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
hours_to_show: 12
refresh_interval: 20
```

**Comment by markuska00** [comment]
Thank you very much  😄 

I found one small bug

The range on the first yaxis get wrong

```
type: custom:plotly-graph
entities:
  - entity: sensor.nibe_36061_40004
    yaxis: y1
  - entity: sensor.nibe_36061_43005
    yaxis: y2
  - entity: sensor.nibe_36061_43009
    yaxis: y3
  - entity: sensor.nibe_36061_40008
    yaxis: y3
  - entity: sensor.nibe_36061_43123
    yaxis: y4
  - entity: sensor.nibe_36061_43136
    yaxis: y4
  - entity: sensor.varmepump_pris_kw
    yaxis: y5
  - entity: sensor.pris_varmepump_snitt_dygn
    yaxis: y5
  - entity: sensor.nibe_36061_43084
    yaxis: y5
  - entity: sensor.nibe_36061_10069
    yaxis: y6
  - entity: sensor.nordpool_dygnspris_el
    yaxis: y6
no_default_layout: true
defaults:
  entity:
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
    show_value:
      right_margin: 10
    line:
      width: 1.5
  yaxes:
    fixedrange: true
    gridcolor: whitesmoke
    zeroline: false
layout:
  plot_bgcolor: white
  dragmode: pan
  margin:
    t: 30
    l: 55
    r: 30
    b: 50
    pad: 5
  showlegend: false
  height: 650
  yaxis:
    gridcolor: whitesmoke
    title:
      text: Utetemp
  yaxis2:
    title:
      text: Gradminuter
  yaxis3:
    title:
      text: Framledning
    range:
      - 24
      - 40
  yaxis4:
    title:
      text: Kompressor
  yaxis5:
    title:
      text: kr/timma
  yaxis6:
    title:
      text: Elpris
  grid:
    ygap: 0.07
    rows: 6
    columns: 1
    pattern: coupled
    roworder: top to bottom
  xaxis:
    gridcolor: whitesmoke
    rangeselector:
      'y': 1.01
      buttons:
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
hours_to_show: 12
refresh_interval: 20
```

![Skärdfgdfgdfgmklipp](https://user-images.githubusercontent.com/37914650/149397672-33cc58a9-1001-47fa-a7f5-06f6cf3e5896.JPG)



But if I move the     "show_value:   right_margin: 10"  the range is correct

```
type: custom:plotly-graph
entities:
  - entity: sensor.nibe_36061_40004
    yaxis: y1
    show_value:
      right_margin: 10
  - entity: sensor.nibe_36061_43005
    yaxis: y2
  - entity: sensor.nibe_36061_43009
    yaxis: y3
  - entity: sensor.nibe_36061_40008
    yaxis: y3
  - entity: sensor.nibe_36061_43123
    yaxis: y4
  - entity: sensor.nibe_36061_43136
    yaxis: y4
  - entity: sensor.varmepump_pris_kw
    yaxis: y5
  - entity: sensor.pris_varmepump_snitt_dygn
    yaxis: y5
  - entity: sensor.nibe_36061_43084
    yaxis: y5
  - entity: sensor.nibe_36061_10069
    yaxis: y6
  - entity: sensor.nordpool_dygnspris_el
    yaxis: y6
no_default_layout: true
defaults:
  entity:
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
    show_value: true
    line:
      width: 1.5
  yaxes:
    fixedrange: true
    gridcolor: whitesmoke
    zeroline: false
layout:
  plot_bgcolor: white
  dragmode: pan
  margin:
    t: 30
    l: 55
    r: 30
    b: 50
    pad: 5
  showlegend: false
  height: 650
  yaxis:
    gridcolor: whitesmoke
    title:
      text: Utetemp
  yaxis2:
    title:
      text: Gradminuter
  yaxis3:
    title:
      text: Framledning
    range:
      - 24
      - 40
  yaxis4:
    title:
      text: Kompressor
  yaxis5:
    title:
      text: kr/timma
  yaxis6:
    title:
      text: Elpris
  grid:
    ygap: 0.07
    rows: 6
    columns: 1
    pattern: coupled
    roworder: top to bottom
  xaxis:
    gridcolor: whitesmoke
    rangeselector:
      'y': 1.01
      buttons:
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
hours_to_show: 12
refresh_interval: 20
```

![Skärsdfsfsdfsdmklipp](https://user-images.githubusercontent.com/37914650/149398077-9186caff-bda2-4c67-9a80-4b7b6cbc1fb3.JPG)

**Reply by dbuezas** [reply]
Oh yes. That's because the fake elements don't know which yaxis they belong to and they all land in yaxis1. I found this by accident today but thought it didn't matter. Now you proved it does, good finding!. I'll fix that next

**Reply by dbuezas** [reply]
Fixed in v1.1.4

**Comment by markuska00** [comment]
One small amateur hack to avoid text collisions on "show_value"  😄 
Not so nice but it works
The lowest value gets a "< br >" at the start of the text template

Maybe something for the future?
But in a better way.
Maybe parameter text position can be changed automatically if the values are too close?




![sdsdfsdf](https://user-images.githubusercontent.com/37914650/149399515-15a4f755-0aa6-42ad-bb9c-7fc2a30e91cb.JPG)

```
type: custom:config-template-card
entities:
  - sensor.nibe_36061_43009
  - sensor.nibe_36061_40008
  - sensor.nibe_36061_10069
  - sensor.nordpool_dygnspris_el
card:
  type: custom:plotly-graph
  entities:
    - entity: sensor.nibe_36061_40004
      yaxis: y1
    - entity: sensor.nibe_36061_43005
      yaxis: y2
    - entity: sensor.nibe_36061_43009
      yaxis: y3
      texttemplate: >-
        "${states['sensor.nibe_36061_43009'].state -
        states['sensor.nibe_36061_40008'].state >= 0 ? '<b> %{y}</b>
        %{customdata.unit_of_measurement}' : '<br><b> %{y}</b>
        %{customdata.unit_of_measurement}'}"
    - entity: sensor.nibe_36061_40008
      texttemplate: >-
        "${states['sensor.nibe_36061_40008'].state -
        states['sensor.nibe_36061_43009'].state > 0 ? '<b> %{y}</b>
        %{customdata.unit_of_measurement}' : '<br><b> %{y}</b>
        %{customdata.unit_of_measurement}'}"
      yaxis: y3
    - entity: sensor.nibe_36061_43123
      yaxis: y4
    - entity: sensor.nibe_36061_43136
      yaxis: y4
    - entity: sensor.varmepump_pris_kw
      yaxis: y5
    - entity: sensor.pris_varmepump_snitt_dygn
      yaxis: y5
    - entity: sensor.nibe_36061_43084
      yaxis: y5
    - entity: sensor.nibe_36061_10069
      yaxis: y6
      texttemplate: >-
        "${states['sensor.nibe_36061_10069'].state -
        states['sensor.nordpool_dygnspris_el'].state >= 0 ? '<b> %{y}</b>
        %{customdata.unit_of_measurement}' : '<br><b> %{y}</b>
        %{customdata.unit_of_measurement}'}"
    - entity: sensor.nordpool_dygnspris_el
      yaxis: y6
      texttemplate: >-
        "${states['sensor.nordpool_dygnspris_el'].state -
        states['sensor.nibe_36061_10069'].state > 0 ? '<b> %{y}</b>
        %{customdata.unit_of_measurement}' : '<br><b> %{y}</b>
        %{customdata.unit_of_measurement}'}"
  no_default_layout: true
  defaults:
    entity:
      texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
      show_value:
        right_margin: 10
      line:
        width: 1.5
    yaxes:
      fixedrange: true
      gridcolor: whitesmoke
      zeroline: false
  layout:
    plot_bgcolor: white
    dragmode: pan
    margin:
      t: 30
      l: 55
      r: 30
      b: 50
      pad: 5
    showlegend: false
    height: 650
    yaxis:
      gridcolor: whitesmoke
      title:
        text: Utetemp
    yaxis2:
      title:
        text: Gradminuter
    yaxis3:
      title:
        text: Framledning
      range:
        - 24
        - 40
    yaxis4:
      title:
        text: Kompressor
    yaxis5:
      title:
        text: kr/timma
    yaxis6:
      title:
        text: Elpris
    grid:
      ygap: 0.07
      rows: 6
      columns: 1
      pattern: coupled
      roworder: top to bottom
    xaxis:
      gridcolor: whitesmoke
      rangeselector:
        'y': 1.01
        buttons:
          - count: 1
            step: hour
          - count: 6
            step: hour
          - count: 12
            step: hour
          - count: 1
            step: day
  hours_to_show: 12
  refresh_interval: 20

**Reply by dbuezas** [reply]
Oh wow, I didn't know one could use yaml templates like these in lovelace configs! This is amazing! 😮 
I don't see any general way to do this better internally with more than 2 traces per subplot, but thanks for showing me this trick. 
I think you can achieve what you wanted before with this "On the texttemplate
Is it possible to use data from Home"
Also thanks for the idea with the last value as text. I'm using this quite a bit myself.

**Reply by DeFlanko** [reply]
This is all very impressive! Is there anyway to make the lines smooth?

**Reply by DeFlanko** [reply]
ahh i found the answer form that Plotly URL you had:
```YAML
defaults:
  entity:
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
    show_value:
      right_margin: 10
    line:
      shape: spline
      width: 3
      #optional smoothing, default is set to 1
      smoothing: 1
```
Make the line a shape: spline first, then adjust smoothing -- default is 1 when changed to spline. 
![image](https://user-images.githubusercontent.com/5233969/152725095-fce145ef-9ce6-4a46-96e8-bc0a29dc2e5e.png)

**Comment by dbuezas** [comment]
In V3.0.0, these yaxis defaults are required:
```yaml
defaults:
  yaxes:
    side: left
    overlaying: 'y'
    visible: true
```
