### DISCUSSION TITLE
Setting bar width and alignment

### DISCUSSION THREAD

**Discussion by elbertov** [dbuezas/lovelace-plotly-graph-card#184] [Q&A] [answered]
Hi David,

First of all: very nice card with great possiblities! I love it and try to implement it in my Energy overviews everywhere!
I discovered it only a couple of days ago and I am already a huge fan :-)

I'm trying to built a barchart like this:

![image](https://user-images.githubusercontent.com/58105716/211383409-3530bc37-bafd-44ff-9b53-4ce2872d0ba0.png)

So I think I'll have to use _barmode: overlay_ and have to set different widths for the bars, I first tried without specifying  the widths:

![image](https://user-images.githubusercontent.com/58105716/211383380-c2153071-061b-4a44-8d9b-963b35abd968.png)

Then i tried to set the individual widths of the bars, but no matter what I put there for number , the results are the same: a very small bar:

![image](https://user-images.githubusercontent.com/58105716/211383695-1978c02e-bec8-42ee-afdf-5058ed52f7b9.png)

![image](https://user-images.githubusercontent.com/58105716/211384048-810290f6-2e6f-4b1f-b17d-8f1b81a026be.png)

So, my questions are:

1. Is it possible to set the individual widths of the bars
2. Is it possible to make the barchart I want? The bars should align in the middle and have different widths

And I think the _barmode: group_ doesn't work, it looks the same as _barmode: overlay_ (or I'm do something wrong of course :-)):

![image](https://user-images.githubusercontent.com/58105716/211384228-f4a8bfb3-b73f-4689-b2f3-0b072c9c9a8b.png)

grtz,
Martin

**Comment by dbuezas** [comment]
Hi there, happy to hear you are enjoying it!

I think what you are trying to achieve should be possible by:
* Setting the width. You are doing this already, but you got the unit wrong, it is in milliseconds! If you want it to be 1 day wide, that's 1000*60*60*24 = 86400000. It may be possible to write `24h` instead, I'm not sure.
* And then either using `offset: 12h` in the entity to shift the data (which is a config specific to this custom card), or xperiod and xperiodalinment (which are plotlyjs configs) [more here](https://plotly.com/javascript/reference/#scatter-xperiod)

Pro tip: if you want to style plots, google for "plotlyjs how to xyz". That usually will get you in the right direction quite quickly :)

I'm moving this issue to the discussion section since it is more a question than a bug report or feature request.

**Comment by elbertov** [comment]
Hi David,

Thx for the quick response! I had the unit wrong for sure:

![image](https://user-images.githubusercontent.com/58105716/211403408-bdc510a4-940d-4673-ac82-5135763ebfdf.png)

grtz Martin

**Reply by dbuezas** [reply]
Oh, alignment wasn't even necessary!

**Comment by miljbee** [comment]
Hello,

I am also trying to plot 2 series as bar. Like @elbertov, I can't get "barmode: group" to work. @dbuezas Do you have some advice ? 
I read that if offset is defined, barmode falls back to overlay: https://plotly.com/javascript/reference/bar/#bar-offset
I have tried with two series without offset, and still can't get my bars side by side.

**Reply by dbuezas** [reply]
Sure, please share your yaml, and a screenshot. The offset their docs talk about is a different thing as this card's offset btw.

**Reply by miljbee** [reply]
````yaml
type: custom:plotly-graph
entities:
  - entity: sensor.plu_machinealaver_energy
    statistic: sum
    period: day
    type: bar
    opacity: 0.5
    filters:
      - fn: |-
          ({ys, states}) => {
            prev = ys[0]
            return { ys: ys.map(y => { result = y-prev; prev = y; return result })}
          }
  - entity: sensor.plu_lavevaiselle_energy
    statistic: sum
    period: day
    type: bar
    opacity: 0.5
    filters:
      - fn: |-
          ({ys, states}) => {
            prev = ys[0]
            return { ys: ys.map(y => { result = y-prev; prev = y; return result })}
          }
layout:
  barmode: group
hours_to_show: 168
refresh_interval: 10
````
![image](https://user-images.githubusercontent.com/637997/214141839-ff63fc65-edf4-4560-93fb-ea74369da7d9.png)

Thanks for your help.

**Reply by dbuezas** [reply]
I think the issue is that I didn't realise plotly already had an offset attribute for bar charts and it is colliding with the offset feature from this card. That's kind of bad to be honest, but there is a workaround:
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor. plu_machinealaver_energy
    filters:
      - fn: |-
          ({ys, xs}) => {
            prev = ys[0]
            return {
              ys: ys.map(y => {
                result = y-prev;
                prev = y;
                return result
              }),
            }
          }
  - entity: sensor. plu_lavevaiselle_energy
    filters:
      - fn: |-
          ({ys, xs}) => {
            prev = ys[0]
            return {
              ys: ys.map(y => {
                result = y-prev;
                prev = y;
                return result
              }),
              xs: xs.map(x=>+x-30000000)
            }
          }
defaults:
  entity:
    statistic: sum
    period: day
    type: bar
    width: 30000000
    
hours_to_show: 168
```
<img width="322" alt="image" src="https://user-images.githubusercontent.com/777196/214264831-14325c7f-a994-4817-98cb-89b7bd94b60e.png">
I set a bar width and apply an offset in the x-axis

**Reply by miljbee** [reply]
Ok, thanks for your help.

**Reply by dbuezas** [reply]
@miljbee: in V3, the offset property is freed, so the hack of sliding the x values won't be needed anymore.

(the one for offsetting time is now called offset_time).

**Reply by miljbee** [reply]
Hello,

Thanks for the new version, really great. I'm trying a few things, and barmode group is still difficult ...
It seems to work, but the bars are so thin that its not usable. Setting width is kind of worst since the bars overlaps:

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.plu_machinealaver_energy
    statistic: sum
    period: day
    type: bar
    opacity: 0.5
    filters:
      - force_numeric
      - delta
  - entity: sensor.plu_lavevaiselle_energy
    statistic: sum
    period: day
    type: bar
    opacity: 0.5
    filters:
      - force_numeric
      - delta
layout:
  barmode: group
hours_to_show: 168
refresh_interval: 10
````
![image](https://user-images.githubusercontent.com/637997/215590719-b543844a-b6c0-4b38-ac7b-4745e7180341.png)
Manually zooming inside shows it works, just the bars are too thin:
![image](https://user-images.githubusercontent.com/637997/215590965-ed50d3fa-e3ba-4556-89cc-285c20d1522b.png)

Playing with width:
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.plu_machinealaver_energy
    statistic: sum
    period: day
    type: bar
    opacity: 0.5
    width: $fn () => 24*3600*400
    filters:
      - force_numeric
      - delta
  - entity: sensor.plu_lavevaiselle_energy
    statistic: sum
    period: day
    type: bar
    opacity: 0.5
    width: $fn () => 24*3600*400
    filters:
      - force_numeric
      - delta
layout:
  barmode: group
hours_to_show: 168
refresh_interval: 10
```
![image](https://user-images.githubusercontent.com/637997/215591316-66be0f7e-ea15-4ad4-a373-39512ef37a3f.png)

I also noticed in V3 that my other 'simple' bar charts now needs a width parameter, otherwise bars are too thin.

Thanks for your help ;)

**Reply by thecem** [reply]
isn´t "group" not a standard setting? In My case only "stack" changes the bar. But even with my charts in version 3.0.2 the bars are beside each other, but to thin and with a width (but witout barmode group): 

```YAML
    width: $fn () => 24*3600*800
```
![grafik](https://user-images.githubusercontent.com/46648579/215678640-64b30f2c-ed69-4855-83d0-6726f68256e7.png)

or with width and barmode group:

```YAML
    width: $fn () => 24*3600*800
layout:
  barmode: group
```

![grafik](https://user-images.githubusercontent.com/46648579/215679401-f3005f22-a18a-48cb-82d8-0d82beee86da.png)

**Comment by thecem** [comment]
I have following bar chart. In previous version the bars where nice and alligned, now there are realy smal:

![grafik](https://user-images.githubusercontent.com/46648579/215591729-f2eafd4e-e3bb-4aae-a287-9d95cbf800f5.png)


Is this a config problem (Heat Energy and Heizöl)?

```YAML
type: custom:plotly-graph
entities:
  - entity: sensor.hmip_sens_out_stho_temperature
    statistic: mean
    period: hour
    name: Aussentemp
  - entity: sensor.at_yesterday
    statistic: mean
    period: day
    time_offset: '-1d'
    extend_to_present: true
    show_value: true
  - entity: sensor.eg_energy_daily
    statistic: state
    period: day
    filters:
      - store_var: egenergy
  - entity: sensor.odg_energy_daily
    statistic: state
    period: day
  - entity: sensor.odg_energy_daily
    statistic: state
    period: day
    type: bar
    opacity: 0.5
    texttemplate: '%{y:0.1f}'
    name: Heating Energy
    filters:
      - map_y: y + vars.egenergy.ys[i]
  - entity: sensor.daily_heizoel
    statistic: state
    period: day
    unit_of_measurement: kWh
    name: Heizöl
    texttemplate: '%{y:0.1f}'
    type: bar
    opacity: 0.5
    filters:
      - map_y_numbers: y * 10
title: Heat Energy LTS
hours_to_show: 576
refresh_interval: 10
defaults:
  entity:
    show_value: true

```

**Comment by dbuezas** [comment, marked as answer]
Ok, that was hard:
## Problems
* The home assistant API assigns a timestamp to the first datapoint which is not the start of the day, but the start of the period queried. This means there are usually two bars very close together, and plotly is forced to make thin bars
* you had a "show_value" in the defaults, which makes no sense for bar charts, and adds more bars at the end of the chart, which also confuses plotly.

## Solution 
<img width="514" alt="image" src="https://user-images.githubusercontent.com/777196/215741967-b043a87e-dd86-4ba4-b41e-493c593cfd0a.png">

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.energy_heating_oil
    statistic: state
    period: day
    type: bar
    opacity: 0.5
    texttemplate: '%{y:0.1f}'
    filters:
      - delta
      - filter: i>0 # the first value has the timestamp of the beginning of the plot, not the day (home assistant API)
  - entity: sensor.energy_house
    statistic: state
    period: day
    texttemplate: '%{y:0.1f}'
    type: bar
    opacity: 0.5
    filters:
      - delta
      - filter: i>0
      
layout:
  barmode: group
title: Heat Energy LTS
hours_to_show: 100
refresh_interval: 10
```

**Reply by dbuezas** [reply]
Show&Tell post so others can use it too? :)

**Reply by thecem** [reply]
fixing the sceen! THX! 

![grafik](https://user-images.githubusercontent.com/46648579/215748536-e60d7920-2938-482e-98a6-b179c396569b.png)

```YAML
type: custom:plotly-graph
entities:
  - entity: sensor.hmip_sens_out_stho_temperature
    statistic: mean
    period: hour
    name: Aussentemp
    show_value: true
  - entity: sensor.at_yesterday
    statistic: mean
    period: day
    time_offset: '-1d'
    extend_to_present: true
    show_value: true
  - entity: sensor.eg_energy_daily
    statistic: state
    period: day
    filters:
      - store_var: egenergy
    show_value: true
  - entity: sensor.odg_energy_daily
    statistic: state
    period: day
    show_value: true
  - entity: sensor.odg_energy_daily
    statistic: state
    period: day
    type: bar
    opacity: 0.5
    texttemplate: '%{y:0.1f}'
    name: Heating Energy
    filters:
      - filter: i>0
      - map_y: y + vars.egenergy.ys[i]
  - entity: sensor.daily_heizoel
    statistic: state
    period: day
    unit_of_measurement: kWh
    name: Heizöl
    texttemplate: '%{y:0.1f}'
    type: bar
    opacity: 0.5
    filters:
      - filter: i>0
      - map_y_numbers: y * 10
title: Heat Energy LTS
hours_to_show: 576
refresh_interval: 10

```

**Reply by dbuezas** [reply]
Please post in Show&tell

**Reply by miljbee** [reply]
Thanks a lot for your support

**Reply by dbuezas** [reply]
Gladly! This is very fun, particularly when it's appreciated :)

Btw, I just realized that the delta filter should remove the first timestamp instead of making it have an NaN value. I should fix that.

**Comment by miljbee** [comment]
Hello,

Sorry to bother you again David, but the problem with barmode group is still alive :(
When series have different units, the problem is back:

```yaml
entities:
  - entity: sensor.pm_main_kwh
    name: energy
    statistic: sum
    period: day
    type: bar
    opacity: 0.5
    filters:
      - delta
  - entity: sensor.pm_main_kwh_cost
    name: cost
    statistic: sum
    period: day
    type: bar
    opacity: 0.5
    filters:
      - delta
layout:
  barmode: group
hours_to_show: 10d
refresh_interval: auto
title: Daily Energy
```
![image](https://user-images.githubusercontent.com/637997/216158486-ad359438-82d4-4cf8-aadc-bebfa5ab1c28.png)

I fixed it with time_offset and width, so not a big deal ....

**Reply by thecem** [reply]
Did you try to add:


```YAML
filters:
  - filter: i>0
```

**Reply by miljbee** [reply]
yep

**Reply by dbuezas** [reply]
Well, they are in different yaxes, so they are unaware of each other.
I'm affraid that's a plotly thing, so there's nothing I can do about it without fundamentally changing the library's behaviour (which will cause a lot of corner cases, and is not the point of this card).

The way to think about different yaxes (or xaxes) is as different layers on top of each other. As they share the x-axis, both layers get "synchronized" on that axis only. That's roughly how these things are implemented in d3, which is the "low level" svg framework used by plotly.

I think working with widths and offsets is the only way to go in this case :)

**Reply by miljbee** [reply]
Ok, thanks for your response

**Reply by miljbee** [reply]
in fact it's easy to fix, there is a setting for that problem: offsetgroup
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.pm_main_kwh
    name: energy
    statistic: sum
    period: day
    type: bar
    offsetgroup: 1
    opacity: 0.5
    filters:
      - delta
  - entity: sensor.pm_main_kwh_cost
    name: cost
    statistic: sum
    period: day
    type: bar
    offsetgroup: 2
    opacity: 0.5
    filters:
      - delta
layout:
  barmode: group
hours_to_show: 10d
refresh_interval: auto
title: Daily Energy
```
![image](https://user-images.githubusercontent.com/637997/216410591-53b6901a-c19e-4c4e-a66b-ccde6d2268b8.png)
