### DISCUSSION TITLE
Statistic period per YEAR and derivate Y possible?

### DISCUSSION THREAD

**Discussion by elbertov** [dbuezas/lovelace-plotly-graph-card#189] [Q&A]
Hi,

I'm trying to make a barchart chart for ANNUAL gas consumption, like this:

![image](https://user-images.githubusercontent.com/58105716/211587922-e9c7ae17-bc97-41eb-9fbb-da1257192451.png)

For my monthly overview I use:

![image](https://user-images.githubusercontent.com/58105716/211586763-573be89a-42fa-4aec-8bbb-b974eb8f01b0.png)

I tried the following for an overview per year, but this is unfortunately not possible :-(

![image](https://user-images.githubusercontent.com/58105716/211586853-a29e29aa-723b-4ef3-a10d-4be26eb9ee8f.png)

Is there a way to get a result per year? 

grtz Martin

**Comment by dbuezas** [comment]
There's unfortunately no year period for statistics. See [here](https://github.com/home-assistant/core/blob/b94e1e9ef839270290f8570afba165fb6e955dd3/tests/components/recorder/common.py#L147)
At the moment there is no in-built filter to do that. Issue #181 is a similar request but for the integrator. Feel free to drop a request to aggregate with resets/intervals and I'll pick it up in some days :)

In the meanwhile, I think you could achieve the same by:
```yaml
- entity: ...
  filters:
    - resample: 1y # this will leave only the datapoint at the beginning of each year
    - derivate: y # this you had already
   offset: -1y # this will move everything to the left by 1 year, so that that each year shows the value for that year and not the previous one
```
