### DISCUSSION TITLE
view history data

### DISCUSSION THREAD

**Discussion by michapr** [dbuezas/lovelace-plotly-graph-card#19] [Q&A]
Hi,
thank you for this great integration!

A question - what will happen with older data removed from states table in database?
Is it possible to view the history data from statistics / statistics_short_term tables? Will it taken by default then?

(Could not try it because I just some days ago try to move to HA ;) ...)

Thanks!

**Comment by dbuezas** [comment]
That's a brilliant idea!
At the moment, the card only reads from the "short term" history [from here](https://developers.home-assistant.io/docs/api/rest/), namely `/api/history/period/<timestamp>`

Do you know how to access the [statistics](https://data.home-assistant.io/docs/statistics/) via the API?

**Reply by michapr** [reply]
No idea, I think there should be done a request about this,...

BTW: could it be possible to add the option to use any custom data for display it? As sample any array as result of a JavaScript function?
(as sample as it was realized in APEX graph), Then we could use any custom generated CSV file - as sample....

Thanks!

**Reply by dbuezas** [reply]
Well, i didn't have this case in mind, but you can do this:

I put this here:  https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/26
![image](https://user-images.githubusercontent.com/777196/153462813-bed78405-7b90-452b-a472-f1e380367824.png)

**Reply by michapr** [reply]
thanks,... yes, just tried, it is working as shown...
But all the time formatting is lost, isn't it?
In normal case I will get from database the timestamp and the value. 
Or is here any way to use this data like the sensor data?

Thanks!

**Reply by dbuezas** [reply]
If the x coordinate values look like dates, you should have date formatting

**Reply by michapr** [reply]
![grafik](https://user-images.githubusercontent.com/11854556/153489873-6d8296b8-946f-4b95-b03e-2e0c1a3e3ffd.png)

right... should be converted before in CSV data file. (timestamp would be of course better - with possible local time conversion ;) ...)
Thanks!

**Reply by dbuezas** [reply]
I'm not quite sure what you are after. Could you invent a yaml that would do what you need? (Just assume the feature existed)

**Reply by michapr** [reply]
Hi, I have no ready yaml for this.
I made an additional table in SQL database for ("middle-term") statistics - it will not be purged by system after x-days. So I have the short-term values from HA, the long term values from HA (grouped by 1h) - and my values (grouped by 10min - for 30days). 
For create a chart I make device.csv for these devices and read this csv via JavaScript call. This is realized just now in ApexChart.

Additional want to show the average value of 2 sensors (temperature) and the minimum value of sensors in greenhouse - without creating a new sensor with template. This are only a few ideas - what could be possible if make the data generation dynamic (like in ApexCharts).

So this is not a real missing feature, but a "nice to have" ;)

**Reply by dbuezas** [reply]
I see. you can make javascript calls inside the lambda, and then map the timestamps in the x axis to dates.
`{x: xs.map(x => new Date(x)), y: your_y_array}´ 
Check the docs for Date [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date).

To be honest, native support for that is a bit far fetch at the moment. It depends too much on your specific use case. But still thanks for the suggestions!

**Reply by michapr** [reply]
Ah, ok, if I can make javascript calls inside here - all is fine!

The more interesting part (for most users, I think,...) is the statistics table access below ;)

THANKS!

**Reply by dbuezas** [reply]
yes, the lambda is pure javascript! you can share things between plots by writing things to window (`window.chart1 = {x,y}`)  it is very hacky, but it will work.
And yes, the statistics table is really interesting. I'm short on time at the moment but will take a look when I can :)

**Comment by michapr** [comment]
I have seen that in statistics-graph the statistics table seems to be used. Maybe you can check it - how they access to it?

Would be really nice to have the possibility to check older data ;)

**Reply by dbuezas** [reply]
Good lead. I found how it's done. It's not through the rest api but websockets instead.
https://developers.home-assistant.io/docs/api/websocket/

Subscription message:
```yaml
id: 33
period: "hour"
start_time: "2019-05-17T15:57:33.798Z"
statistic_ids: ["sensor.electricity_usage"]
0: "sensor.electricity_usage"
type: "history/statistics_during_period"
````

and this comes back:
```yaml
{
  "id": 33,
  "type": "result",
  "success": true,
  "result": {
    "sensor.electricity_usage": [
      {
        "statistic_id": "sensor.electricity_usage",
        "start": "2021-11-12T11:00:00+00:00",
        "end": "2021-11-12T12:00:00+00:00",
        "mean": 1172.771566910447,
        "min": 0,
        "max": 6827.880371,
        "last_reset": null,
        "state": null,
        "sum": null
      } //, ...
    ]
  }
}
```

Maybe I should move the whole card to web sockets 🤔
