### DISCUSSION TITLE
How to set default "Range Selector"

### DISCUSSION THREAD

**Discussion by patfelst** [dbuezas/lovelace-plotly-graph-card#190] [Q&A] [answered]
I may have missed it, but how do you set the default range selector button?

This [post](https://community.plotly.com/t/rangeselector-change-default-value/2785) indicates you can set "active: true" however it doesn't work for me.

```yaml
layout:
  xaxis:
    rangeselector:
      # see examples: https://plotly.com/javascript/range-slider/
      # see API: https://plotly.com/javascript/reference/layout/xaxis/#layout-xaxis-rangeselector
      "y": 1.2
      buttons:
        - count: 1
          step: minute
        - count: 1
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
          active: true # Should this set the "day" as default?
        - count: 7
          step: day
```
