### DISCUSSION TITLE
Solar / Grid Power with hourly yield / consumption overlay

### DISCUSSION THREAD

**Discussion by rwegnerGermany** [dbuezas/lovelace-plotly-graph-card#191] [Show and tell]
Hi,
I had a graph for solar power production (raw and 10min avg) and the yield forecast overlayed.
To check the quality of the yield forecast, I had the idea to also overlay the actual hourly yield.

![pv](https://user-images.githubusercontent.com/69688683/212552262-86aec6f0-b26e-43b1-b9a7-e18c3207c3f7.png)

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.sma_daily_yield # this is of type total_increasing and resets at midnight
    name: SMA Hourly Yield
    statistic: state
    period: hour
    filters:
      - fn: |-
          (params) => {
            const ys = [];
            ys.push(0); # to have same number of elements as xs
            # compute delta to previous hour
            for (let i = 1; i < params.statistics.length; i++){
              ys.push(params.statistics[i].state-params.statistics[i-1].state);
            }
            return { ys };
          }
    type: bar
    marker:
      color: rgba(44,160,44,0.6)
  - entity: sensor.stp6_0_3av_40_223_grid_power
    line:
      color: rgb(31,119,180)
  - entity: sensor.sma_grid_power_10min_avg
    show_value:
      right_margin: 15
    line:
      color: rgb(255,127,14)
      width: 1.5
  - entity: sensor.energy_next_hour
    line:
      color: rgb(44,160,44)
      width: 1.5
refresh_interval: 10
hours_to_show: 14

# want to have the bar plot in the background and on yaxis2 which is plotted on top.
# Solution: kWh on yaxis1 and switch axis' positions.
layout:
  height: 400
  yaxis:
    showgrid: false
    side: right
    rangemode: nonnegative
  yaxis2:
    showgrid: true
    side: left
    rangemode: nonnegative
```

**Comment by dbuezas** [comment]
Really cool, thanks for sharing!

By the way, to get syntax colouring in the code snippet you have to write it like this:
` ```yaml `
` <your yaml> `
` ``` `  
(I added it to your post already)

**Comment by gllmlbrt** [comment]
Hi, this looks cool @rwegnerGermany !
I tried to achieve the same with my sensors but once the max of teh day is achieved, then it keeps showing the max for all consecutive hours of the day until midnight...

It just shows the cummulative value, rather than the hourly yield... but that happens only after midnight :
![image](https://user-images.githubusercontent.com/58825251/216532728-9e3ec767-80d5-4e9a-8e27-f755f72da8a2.png)
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.solarnet_energy_day
    name: Hourly Yield
    statistic: state
    period: hour
    filters:
      - fn: |-
          (params) => {
            const ys = [];
            ys.push(0); # to have same number of elements as xs
            # compute delta to previous hour
            for (let i = 1; i < params.statistics.length; i++){
              ys.push(params.statistics[i].state-params.statistics[i-1].state);
            }
            return { ys };
          }
    type: bar
    marker:
      color: orange
  - entity: sensor.solarnet_power_photovoltaics
    line:
      width: 2
      color: tomato
  - entity: sensor.sh_used_power_1min
    line:
      width: 1
      color: cyan
  - entity: sensor.solcast_forecast_next_hour
    time_offset: 45m
    line:
      color: MediumSeaGreen
      width: 1.5
refresh_interval: 10
hours_to_show: 14
layout:
  height: 650
  yaxis:
    showgrid: false
    side: right
    rangemode: nonnegative
  yaxis2:
    showgrid: true
    side: left
    rangemode: nonnegative
  dragmode: pan
  xaxis:
    rangeselector:
      'y': 1.2
      buttons:
        - count: 1
          step: minute
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 1
          step: day
        - count: 3
          step: day
```

**Reply by rwegnerGermany** [reply]
Hm, I am affraid you have to look into the debugger. In may case the state field was the only filled one in statistics. The others are null. Which maybe is reasonable with "state" statistics?!

Maybe try other statistic types. I first tried "max" to get the end of the current hour but I got no data there.

My input entity sensor.sma_daily_yield is:

state_class: total_increasing
unit_of_measurement: kWh
device_class: energy

**Comment by gllmlbrt** [comment]
No sorry I was not clear. I think the sensor is ok. It works fineish diring the day (showing properly values each hours), but At midnight starts to display the cumulated values.
![image](https://user-images.githubusercontent.com/58825251/216676330-4b8d8587-8bdc-441b-8554-7e0bb3aa84e8.png)
But you can see in the image it displays the last hourly yield on the hours afterwards, after the procduction is 0.

**Reply by dbuezas** [reply]
I think @rwegnerGermany 's suggestion still applies. Home assistant is most likely returning wrong values. How does the sensor work?
If it counts pulses of a meter, it may be that it is missing a timeout: at night, no energy is generated, so the sensor sees no pulses, and therefore gets no new timestamp to calculate pulses per second. Therefore the value doesn't change.

I'm making a lot of assumptions here, but it does look like a wrongly configured esphome pulse meter sensor :)

**Reply by dbuezas** [reply]
can you post another picture where the timestamps are visible? I don't know where (and which trace) I should look at

**Reply by gllmlbrt** [reply]
Thanks, that's right the entity is a sensor geenrate by the official fronius integration (It has the right class and units etc..), but at night when the power production stops, the energy daily sensor stops creating new timestamps I think. Because the power in W is not 0,  but "unknown".
![image](https://user-images.githubusercontent.com/58825251/216757159-88c6f099-44c9-4f13-aac9-202224e6a7fd.png)

I have now created a new separate ulitily meter sensor and I will see how that works.

**Comment by rwegnerGermany** [comment]
To be precise, this template sensor is the input for my bar chart statistics. It's just to convert the Wh from the inverter to kWh.

```yaml
- name: "SMA daily Yield"
      unique_id: stp6_0_3av_40_223_daily_yield_kwh
      device_class: ENERGY
      unit_of_measurement: "kWh"
      state: "{{ states('sensor.stp6_0_3av_40_223_daily_yield') | float/1000 }}"
      state_class: total_increasing
```

The values is reset by the inverter at midnight. According to history, there is no useless (because constant) data points when dark, but I think thats normal behaviour of the recorder.
![Zwischenablage03](https://user-images.githubusercontent.com/69688683/216701066-005031ca-780b-4d17-8976-3220687e7bad.png)


![Zwischenablage01](https://user-images.githubusercontent.com/69688683/216702228-bcff3d6e-731a-4222-99e5-278a15efe825.png)

**Reply by dbuezas** [reply]
And that curve looks like the bar chart above. It shows accumulated values. I'm still failing to grasp what the issue is. If you have the accumulated values and you want the hourly rate you can use the derivative or delta filters.

Maybe start over and make a squiggle showing what you expect to see, and a very short text explaining what you see and what you expect/need :)

**Comment by rwegnerGermany** [comment]
But I do have a different problem:
The bar width is wrong most if the time. Applies to iOS app as well as Windows Firefox, Edge.

bar_gap: 0.05 # should almost touch each other

Sometimes they are so narrow you can barly see them.
Sometimes page reload helps. It's somewhat random.
![IMG_3652](https://user-images.githubusercontent.com/69688683/216703107-e2060c11-056f-4343-a0f0-62dca3edc994.png)

**Reply by dbuezas** [reply]
the unit for barwidth and offsets is milliseconds. do you see the same behaviour if you use a larger number?
I haven't used bar_gap myself, but can you confirm you are doing the `filter: i>0` trick here too just in case?

**Comment by rwegnerGermany** [comment]
Basic configuration:

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.sma_daily_yield
    name: SMA Hourly Yield
    statistic: state
    period: hour
    filters:
      - fn: |-
          (params) => {
            const ys = [];
            ys.push(0);
            for (let i = 1; i < params.statistics.length; i++){
              ys.push(params.statistics[i].state-params.statistics[i-1].state);
            }
            return { ys };
          }
    type: bar
    marker:
      color: rgba(44,160,44,0.6)
refresh_interval: 30
hours_to_show: 14
layout:
  height: 400

```

![Zwischenablage01](https://user-images.githubusercontent.com/69688683/216726474-58eab33c-8636-4a48-bace-3fb0aaf11ece.png)


Just a few page reloads and a bit of luck. Haven't even entered card code editing in between of these 2 screen shots.

![Zwischenablage02](https://user-images.githubusercontent.com/69688683/216727173-ac006c15-02ea-4240-8a10-ad4efcfc4030.png)


Ah, funny. By accident I just zoomed with my touchpad and the bars became narrow and stayed like this. But not allways and clicking reset usually sets to normal width. After each zoom operation the bar width is somewhat random.

**Reply by dbuezas** [reply]
Try replacing your filters with this:
```yaml
filters:
  - delta
  - filter: i>0
```
The reason for which a reload changes the width is likely because Home Assistant creates a fake data point with the timestamp of the lower edge of the requested time interval
