### DISCUSSION TITLE
Graph per YEAR

### DISCUSSION THREAD

**Discussion by elbertov** [dbuezas/lovelace-plotly-graph-card#198] [Show and tell]
Hi all,

Unfortunately there is no statistic period per YEAR and derivate Y possible (See #189 ).
So I decided to write a little bit of code to to achieve the task at hand :-)

![image](https://user-images.githubusercontent.com/58105716/214285487-5d2d71b0-195d-4451-aeca-85273940c894.png)

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.gas_consumed
    show_value: true
    type: bar
    statistic: state
    period: month
    filters:
      - derivate: M
      - fn: |-
          (params) => {
            const ys = [];
            const xs = [];
            var yeartotal=0;   // The calculated total in a year
            var year=0;        // The year for which the total has to be calculated

            // Loop through the datapoints, calculate the yeartotals and place the yeartotal on a (new) timeline
            for (i=0; i<params.statistics.length; i++)
            {
              if (i==0)
              {
                // Initializingstuff at the first datapoint
                yeartotal = 0;                             // set the yeartotal so far to zero
                year = params.xs[i].getFullYear();         // the (first) year that has to be calculated
              }
              else
              {
                if (params.xs[i].getFullYear() == year)
                {
                  // datapoint is in the same year as the previous datapoint so add it to the total
                  yeartotal += params.ys[i];              
                }
                else
                {
                  // datapoint is NOT in the same year as the previous datapoint
                  // push it on the new time line on January 1st of that year
                  xs.push(new Date("01-01-" + year + " 00:00:00"));
                  ys.push(yeartotal);

                  // reset for a new year to calculate
                  year      = params.xs[i].getFullYear(); // remember the new year that was to be calculated
                  yeartotal = params.ys[i];               // the current datapoint is already of the new year
                }
              }
            }

            // Add the last year
            xs.push(new Date("01-01-" + year + " 00:00:00"));
            ys.push(yeartotal);

            // And done - return the new graph data
            return {xs, ys};
          }
hours_to_show: 28000
layout:
  height: 600
```

The only thing is the "hours_to_show", I cannot calculate it I think, so I put it there manually.

**Comment by dbuezas** [comment]
Very nice!

PS: I fixed the code block in your post.
The syntax is:
````
```yaml
[your yaml here]
```
````

**Reply by dbuezas** [reply]
I think something like this may also work:
```yaml
filters:
  - integrate
  - resample: 1y
  - derivate
```

**Comment by eiderterra** [comment]
Hello,
I would also like to display the annual values in the chart, but so far I haven't been able to get the correct values.
Option 1:
```
type: custom:plotly-graph
defaults:
  yaxes:
    fixedrange: true
  entity:
    period: month
    type: bar
    unit_of_measurement: kWh
    statistic: state
    texttemplate: "%{y:.1f}"
    textposition: auto
entities:
  - entity: sensor.senec_webapi_consumption_total
    name: Verbrauch
    marker:
      color: "#428c75"
      opacity: 2
    filters:
      - filter: i>=0
      - derivate: M
      - fn: |-
          (params) => {
            const ys = [];
            const xs = [];
            var yeartotal=0;   // The calculated total in a year
            var year=0;        // The year for which the total has to be calculated

            // Loop through the datapoints, calculate the yeartotals and place the yeartotal on a (new) timeline
            for (i=0; i<params.statistics.length; i++)
            {
              if (i==0)
              {
                // Initializingstuff at the first datapoint
                yeartotal = 0;                             // set the yeartotal so far to zero
                year = params.xs[i].getFullYear();         // the (first) year that has to be calculated
              }
              else
              {
                if (params.xs[i].getFullYear() == year)
                {
                  // datapoint is in the same year as the previous datapoint so add it to the total
                  yeartotal += params.ys[i];              
                }
                else
                {
                  // datapoint is NOT in the same year as the previous datapoint
                  // push it on the new time line on January 1st of that year
                  xs.push(new Date("01-01-" + year + " 00:00:00"));
                  ys.push(yeartotal);

                  // reset for a new year to calculate
                  year      = params.xs[i].getFullYear(); // remember the new year that was to be calculated
                  yeartotal = params.ys[i];               // the current datapoint is already of the new year
                }
              }
            }

            // Add the last year
            xs.push(new Date("01-01-" + year + " 00:00:00"));
            ys.push(yeartotal);

            // And done - return the new graph data
            return {xs, ys};
          }
    time_offset: 0h
layout:
  paper_bgcolor: rgba(0,0,0,0)
  plot_bgcolor: rgba(0,0,0,0)
  barmode: stack
  bargap: 0.1
  bargroupgap: 0
  uniformtext:
    minsize: 10
    mode: show
  modebar:
    orientation: v
    remove: zoom
  margin:
    t: 25
    l: 50
    r: 60
  height: 500
  legend:
    "y": -0.5
    x: 0.02
  xaxis:
    rangeselector:
      "y": 1.15
      buttons:
        - count: 1
          step: year
        - count: 2
          step: year
        - count: 3
          step: year
    gridcolor: rgba(238,235,235,0.3)
    autorange: true
    showgrid: true
    linewidth: 0
    linecolor: null
    nticks: 6
    tickformat: |-

      %Y
    range:
      - 2030
  xaxis2:
    visible: false
    matches: x
  yaxis:
    side: left
    visible: true
  yaxis2:
    range:
      - 0
      - 100
  yaxis3:
    visible: false
    side: left
    matches: "y"
hours_to_show: 3y
refresh_interval: 60
title: Energiedaten jährlich
view_layout:
  position: main
modebar:
  orientation: h
  remove: pan

```
Result 
<img width="1223" height="556" alt="Unbenannt" src="https://github.com/user-attachments/assets/d5f50fb8-e7c6-4c52-92fc-945332213621" />

Option2:

```
type: custom:plotly-graph
defaults:
  yaxes:
    fixedrange: true
  entity:
    period: month
    type: bar
    unit_of_measurement: kWh
    statistic: state
    texttemplate: "%{y:.1f}"
    textposition: auto
entities:
  - entity: sensor.senec_webapi_consumption_total
    name: Verbrauch
    marker:
      color: "#428c75"
      opacity: 2
    time_offset: "-365d"
    filters:
      - resample: 1y
      - derivate: "y"
layout:
  paper_bgcolor: rgba(0,0,0,0)
  plot_bgcolor: rgba(0,0,0,0)
  barmode: stack
  bargap: 0.1
  bargroupgap: 0
  uniformtext:
    minsize: 10
    mode: show
  modebar:
    orientation: v
    remove: zoom
  margin:
    t: 25
    l: 50
    r: 60
  height: 500
  legend:
    "y": -0.5
    x: 0.02
  xaxis:
    rangeselector:
      "y": 1.15
      buttons:
        - count: 1
          step: year
        - count: 2
          step: year
        - count: 3
          step: year
    gridcolor: rgba(238,235,235,0.3)
    autorange: true
    showgrid: true
    linewidth: 0
    linecolor: null
    nticks: 6
    tickformat: |-

      %Y
    range:
      - 2030
  xaxis2:
    visible: false
    matches: x
  yaxis:
    side: left
    visible: true
  yaxis2:
    range:
      - 0
      - 100
  yaxis3:
    visible: false
    side: left
    matches: "y"
hours_to_show: 3y
refresh_interval: 60
title: Energiedaten jährlich
view_layout:
  position: main
modebar:
  orientation: h
  remove: pan
```
Result
<img width="1202" height="551" alt="Unbenannt2" src="https://github.com/user-attachments/assets/8b1e9857-fe17-46f8-999d-038520ea4b58" />

The data here is correct, but the year 2026 is missing.
The correct data would be:
2024     732.0 
2025     5284.8 
2026     369.4 

However, the data for 2024 does not start on January 1.
I would be grateful for any help.

Stunden später!!
I have now found the solution myself for option 1:
**period: day
derivate: d**

this is how it works for me
