### DISCUSSION TITLE
Binary Sensor (on/off) count multiply and per day.

### DISCUSSION THREAD

**Discussion by thecem** [dbuezas/lovelace-plotly-graph-card#205] [Q&A] [answered]
Hi,

thanks for helping in advance!!
To intergrate the new function of trendline to get a Idea of the heatload of a building.
I searching for a solution to use a "binary_sensor" wich counts with every "on" 0,1 m3 of gas.
(reason behind this is taht the sensor status is recorded since 2 years, but not to a number.) 
Now I try to count all "on" per day, to get the value of amount of qubic meter of gas. 
I try to do this with a filter to show the daly consumption in a graph for gas in m³ and kWh (9,9228)

```
type: custom:plotly-graph
entities:
  - entity: binary_sensor.lumi_lumi_magnet_acn001_iaszone
    filters:
      - map_y: |- 
          y === "on" ? 1 : 0
      - multiply: 0.1
```

Q&A:

Q1: How to count the "on"? (or maybe the "change")
Q2: Do I have to translate on:off to 1 and 0 ? 
Q3: How to count the "on" per day?

Thank you for your help!

**Comment by dbuezas** [comment, marked as answer]
oh, to count per day, you'll need #181, which I still need to implement.
As a hack, you could do the following (in the new v3.0.0 release)
```yaml
type: custom:plotly-graph
entities:
  - entity: binary_sensor.lumi_lumi_magnet_acn001_iaszone
     unit_of_measurement: m³
     filters:
      - map_y: y === "on" ? 1 : 0
      - integrate: 1d # will accumulate in units per day
      - resample: 1d #will keep 1 measurement per day only
      - delta # will subtract each two consecutive values
      - multiply: 0.1
      - store_var: gas
  - entity: ""
     filters:
      - load_var: gas
      - trendline

```

**Reply by dbuezas** [reply]
Mmmm you could also do something like this:
```yaml
- map_y: y === "on" ? 1 : 0
- integrate: 1d
- force_numeric # removes unavailable datapoints to avoid the next function to return NaN
- fn: |
     ({ xs,ys }) => {
         let valueAtEndOfLastDay = 0;
         return {
            ys: ys.map((y,i) => {
               if (i>0 && xs[i-1].getUTCDate() !== xs[i].getUTCDate()){
                  valueAtEndOfLastDay = ys[i-1];
               }
               return y - valueAtEndOfLastDay;
            }
         }
     }
```

I didn't test it, but I think something like that should do the job if the granularity of the previous one doesn't cut it

**Reply by dbuezas** [reply]
> Q1: How to count the "on"? (or maybe the "change")

`(y != ys[i-1] && y === "on") ? 1 : 0`

> Q2: Do I have to translate on:off to 1 and 0 ?

What you did is 👌 

> Q3: How to count the "on" per day?

See two options above

**Reply by thecem** [reply]
This is the basis:

![grafik](https://user-images.githubusercontent.com/46648579/215400441-85dab59a-1cad-44d8-80f7-b65c0448a825.png)

First answer show following:

![grafik](https://user-images.githubusercontent.com/46648579/215400074-773be17d-f5fa-4bfd-a948-5b4170c283e3.png)

Second answer:

![grafik](https://user-images.githubusercontent.com/46648579/215401858-0fc6b56a-a55f-4f8c-8a4d-a1f45e918ee8.png)

**Comment by dbuezas** [comment]
You need tu upgrade to v3.0.0

**Comment by thecem** [comment]
Yes you are right, I forgot to update. After update I tried following:

![grafik](https://user-images.githubusercontent.com/46648579/215561776-9f881c93-281d-4aae-ad95-d63a6090347c.png)

why is it not counting a complete number, but a fraction of 1 ?

![grafik](https://user-images.githubusercontent.com/46648579/215562375-7616df85-f744-479a-b79c-10c462ac7b36.png)

Here is something missing but even no success.

![grafik](https://user-images.githubusercontent.com/46648579/215562677-dd659590-3ec8-41dd-86f9-79779c04858e.png)


May the first step should count the on per day....

thx a lot for you help!

**Reply by dbuezas** [reply]
Sure, no problem :)

> why is it not counting a complete number, but a fraction of 1 ?

the unit is m3 per day. It integrates over time, so it measures for how long the sensor was on.

> Here is something missing but even no success.

closing parenthesis missing in lie 18

**Reply by thecem** [reply]
So instead of an integrate we have to use a derivate? Since not the time, but every change to on, is 0,1 m3. If we could count the result would be y * 0,1 m3, let’s say 800 “on” are 80m3, if this is counted per day we have 80m3/d.
Is counting the “on” to a number available?

**Reply by dbuezas** [reply]
Oh I see. There's no filter to count, but it's easy enough to make as a fn. But you won't be able to use the new reset_every option in the integrate filter.

```yaml
fn: |
    ({ ys }) => {
      let count=0;
      return {
          ys: ys.map(y => {
              if (y=="on") count++;
              return count
          })
       };
    } 
```

And compose that with the previous ones to reset every day

**Reply by thecem** [reply]
I tried first to get a count value:

```YAML
type: custom:plotly-graph
entities:
  - entity: binary_sensor.lumi_lumi_magnet_acn001_iaszone
    filters:
      - fn: |
          ({ ys }) => { let count=0; 
          return ys.map(y => { if (y=="on") count++;
          return count }) }
hours_to_show: 240
refresh_interval: 10
title: Gas
```
but no number! 

![1D48A00E-B445-40B3-87C9-C9F241839DA2](https://user-images.githubusercontent.com/46648579/215737122-9ec49b00-0803-4eef-bcca-e7af3d194b34.jpeg)
