### DISCUSSION TITLE
Weather forecast plot (`meta` and nested attributes)

### DISCUSSION THREAD

**Discussion by dbuezas** [dbuezas/lovelace-plotly-graph-card#213] [Show and tell]
<img width="493" alt="image" src="https://user-images.githubusercontent.com/777196/215556691-16bc19b6-40a5-4184-87e2-87df7a6ed3da.png">

```yaml
type: custom:plotly-graph
title: Forecast
time_offset: 1.5d
entities:
  - entity: sensor.openweathermap_temperature
    legendgroup: 2
    name: 🌡 Temperature
    filters:
      - store_var: temperature
    fill: tozeroy
    fillcolor: rgba(214, 39, 40,.6)
    line:
      color: rgba(214, 39, 40, 1)
  - entity: weather.openweathermap
    legendgroup: 2
    showlegend: false
    name: Temperature
    fill: tozeroy
    fillcolor: rgba(214, 39, 40, .3)
    line:
      color: rgba(214, 39, 40, 1)
      dash: dot
    unit_of_measurement: °C
    filters:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [vars.temperature.xs.slice(-1)[0],...meta.forecast.map(({ datetime }) => new Date(datetime))],
            ys: [vars.temperature.ys.slice(-1)[0],...meta.forecast.map(({ temperature }) => temperature)],
          })
  - entity: sensor.openweathermap_rain
    fillcolor: rgba(31, 119, 180,.6)
    line:
      color: rgba(31, 119, 180, 1)
    legendgroup: 1
    name: 🌧 Precipitation
    filters:
      - store_var: precipitation
    fill: tozeroy
  - entity: weather.openweathermap
    legendgroup: 1
    showlegend: false
    name: Precipitation
    fill: tozeroy
    fillcolor: rgba(31, 119, 180,.3)
    line:
      color: rgba(31, 119, 180, 1)
      dash: dot
    unit_of_measurement: mm
    filters:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [vars.precipitation.xs.slice(-1)[0],...meta.forecast.map(({ datetime }) => new Date(datetime))],
            ys: [vars.precipitation.ys.slice(-1)[0],...meta.forecast.map(({ precipitation }) => precipitation)],
          })
defaults:
  entity:
    show_value: true
    line:
      shape: spline
layout:
  legend:
    itemwidth: 30
hours_to_show: 48
```

## Update 

In newer HA versions you'll need a template sensor since the forecast attributes are not stored automatically.

```yaml
# in your configuration.yaml

# from https://community.home-assistant.io/t/how-to-handle-deprecation-of-the-weather-forecast-attribute-for-plotly-card/626002/5?u=fillr
# by Arrow1024
template:
  - trigger:
      - platform: state
        entity_id:
          - weather.weather_channel
    action:
      - service: weather.get_forecasts
        data:
          type: hourly
        target:
          entity_id: weather.weather_channel
        response_variable: hourly
    sensor:
      - name: Weather Channel Forecast Hourly
        unique_id: weather_channel_forecast_hourly
        state: "{{ now() }}"
        attributes:
          forecast: "{{ hourly['weather.weather_channel'].forecast }}"
```

**Comment by Arrow-hub** [comment]
This is awesome! I use it to display the forecast for three different weather stations since they're all so different. I have temperature, humidity, dew point and precipitation probability. (I know, not the prettiest way to display, but I like it). 

![Screenshot_20231011_092013](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/63028327/da908234-a6b6-49d6-b3d3-4f2ea3063856)

Question. What will become of this with the new weather entities that no longer have a "forecast" attribute, and instead needs to call a service? Any known workaround?

**Reply by dbuezas** [reply]
Wow, that's really cool!
I don't know of any workarounds for that (didn't even know about that change). The mos obvious naive way would be to make an automation that calls the service and puts the result in a helper entity somehow

**Reply by dbuezas** [reply]
I guess you should ask in the Home Assistant forums for a better answer

**Comment by wrowlands3** [comment]
Hi @dbuezas the pirate weather integration provides individual sensors for forecast - the sensor name then appended with _1d, _2d etc up to _7d and _1h, _2h etc up to _48h. I feel this should be easy to map into a forecast in plotly but the filter fn coding is beyond me. Do you have any insight how to vary your above example please?

**Reply by dbuezas** [reply]
Here's an idea:
Add all entities but mark them as internal. Use time_offset to offset each forecast to the date and time it forecasts.  Use a filter to pick the last value of each and vars to accumulate them into an array. 
Add a final empty `entity: ''`, load the whole array for plotting the vars.

I suggest you read the docs section about filters and $fn / $ex first.

Wish you luck!

**Comment by Arrow-hub** [comment]
Here's what I've done

In configuration.yaml
```yaml
- trigger:
      - platform: state
        entity_id:
          - weather.weather_channel
    action:
      - service: weather.get_forecasts
        data:
          type: hourly
        target:
          entity_id: weather.weather_channel
        response_variable: hourly
```

In the chart card
```yaml
- entity: sensor.weather_channel_forecast_hourly
    showlegend: false
    legendgroup: 1
    line:
      color: '#ffcfb2'
      width: 1
    unit_of_measurement: °F
    filters:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [...meta.forecast.map(({ datetime }) => new Date(datetime))],
            ys: [...meta.forecast.map(({ temperature }) => temperature)],
          })
```

![Screenshot_20240224_073823](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/63028327/13e1308b-f99e-4d2b-a36c-3e0cfa596448)

**Comment by wrowlands3** [comment]
Thanks both for your pointers!
I got mine working like this:
![Capture](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86292646/1430aa61-c369-4bf3-9eed-e9a50837e3a2)
There's unfortunately a lot of code as I couldn't get the meta or map function to work, but this method works at least.

```type: custom:plotly-graph
title: Forecast
time_offset: 2d
entities:
  - entity: sensor.my_weather_temperature_0h
    internal: false
    showlegend: false
    time_offset: 0h
    line:
      color: rgba(255, 0, 0, 1)
      width: 3
      shape: spline
      dash: solid
    filters:
      - sliding_window_moving_average:
          window_size: 1
          extended: true
      - sliding_window_moving_average:
          window_size: 3
          extended: true
  - entity: ''
    name: Now
    yaxis: y1
    internal: false
    showlegend: false
    line:
      width: 2
      dash: dot
      color: black
    x: $ex [Date.now(), Date.now()]
    'y':
      - 0
      - 10
  - entity: ''
    name: Freezing Theshold
    internal: false
    showlegend: false
    yaxis: y1
    line:
      width: 1
      color: deepskyblue
    x: $ex get('visible_range')
    'y':
      - 0
      - 0
  - entity: sensor.my_weather_temperature_0h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempa
  - entity: sensor.my_weather_temperature_1h
    time_offset: 1h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempb
  - entity: sensor.my_weather_temperature_2h
    time_offset: 2h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempc
  - entity: sensor.my_weather_temperature_3h
    time_offset: 3h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempd
  - entity: sensor.my_weather_temperature_4h
    time_offset: 4h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempe
  - entity: sensor.my_weather_temperature_5h
    time_offset: 5h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempf
  - entity: sensor.my_weather_temperature_6h
    time_offset: 6h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempg
  - entity: sensor.my_weather_temperature_7h
    time_offset: 7h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: temph
  - entity: sensor.my_weather_temperature_8h
    time_offset: 8h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempi
  - entity: sensor.my_weather_temperature_9h
    time_offset: 9h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempj
  - entity: sensor.my_weather_temperature_10h
    time_offset: 10h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempk
  - entity: sensor.my_weather_temperature_11h
    time_offset: 11h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: templ
  - entity: sensor.my_weather_temperature_12h
    time_offset: 12h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempm
  - entity: sensor.my_weather_temperature_13h
    time_offset: 13h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempn
  - entity: sensor.my_weather_temperature_14h
    time_offset: 14h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempo
  - entity: sensor.my_weather_temperature_15h
    time_offset: 15h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempp
  - entity: sensor.my_weather_temperature_16h
    time_offset: 16h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempq
  - entity: sensor.my_weather_temperature_17h
    time_offset: 17h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempr
  - entity: sensor.my_weather_temperature_18h
    time_offset: 18h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: temps
  - entity: sensor.my_weather_temperature_19h
    time_offset: 19h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempt
  - entity: sensor.my_weather_temperature_20h
    time_offset: 20h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempu
  - entity: sensor.my_weather_temperature_21h
    time_offset: 21h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempv
  - entity: sensor.my_weather_temperature_22h
    time_offset: 22h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempw
  - entity: sensor.my_weather_temperature_23h
    time_offset: 23h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempx
  - entity: sensor.my_weather_temperature_24h
    time_offset: 24h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempy
  - entity: sensor.my_weather_temperature_25h
    time_offset: 25h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempz
  - entity: sensor.my_weather_temperature_26h
    time_offset: 26h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempaa
  - entity: sensor.my_weather_temperature_27h
    time_offset: 27h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempbb
  - entity: sensor.my_weather_temperature_28h
    time_offset: 28h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempcc
  - entity: sensor.my_weather_temperature_29h
    time_offset: 29h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempdd
  - entity: sensor.my_weather_temperature_30h
    time_offset: 30h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempee
  - entity: sensor.my_weather_temperature_31h
    time_offset: 31h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempff
  - entity: sensor.my_weather_temperature_32h
    time_offset: 32h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempgg
  - entity: sensor.my_weather_temperature_33h
    time_offset: 33h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: temphh
  - entity: sensor.my_weather_temperature_34h
    time_offset: 34h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempii
  - entity: sensor.my_weather_temperature_35h
    time_offset: 35h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempjj
  - entity: sensor.my_weather_temperature_36h
    time_offset: 36h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempkk
  - entity: sensor.my_weather_temperature_37h
    time_offset: 37h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: templl
  - entity: sensor.my_weather_temperature_38h
    time_offset: 38h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempmm
  - entity: sensor.my_weather_temperature_39h
    time_offset: 39h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempnn
  - entity: sensor.my_weather_temperature_40h
    time_offset: 40h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempoo
  - entity: sensor.my_weather_temperature_41h
    time_offset: 41h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: temppp
  - entity: sensor.my_weather_temperature_42h
    time_offset: 42h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempqq
  - entity: sensor.my_weather_temperature_43h
    time_offset: 43h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: temprr
  - entity: sensor.my_weather_temperature_44h
    time_offset: 44h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempss
  - entity: sensor.my_weather_temperature_45h
    time_offset: 45h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: temptt
  - entity: sensor.my_weather_temperature_46h
    time_offset: 46h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempuu
  - entity: sensor.my_weather_temperature_47h
    time_offset: 47h
    filters:
      - map_y: ys[ys.length-1]
      - map_x: xs[xs.length-1]
      - store_var: tempvv
  - entity: ''
    internal: false
    name: Temperature
    line:
      color: rgba(255, 0, 0, 1)
      width: 3
      shape: spline
    unit_of_measurement: °C
    filters:
      - fn: >-
          ({vars}) =>  ({   
          xs: [vars.tempa.xs[0],
          vars.tempb.xs[0], vars.tempc.xs[0], vars.tempd.xs[0],
          vars.tempe.xs[0], vars.tempf.xs[0], vars.tempg.xs[0],
          vars.temph.xs[0], vars.tempi.xs[0], vars.tempj.xs[0],
          vars.tempk.xs[0], vars.templ.xs[0], vars.tempm.xs[0],
          vars.tempn.xs[0], vars.tempo.xs[0], vars.tempp.xs[0],
          vars.tempq.xs[0], vars.tempr.xs[0], vars.temps.xs[0],
          vars.tempt.xs[0], vars.tempu.xs[0], vars.tempv.xs[0],
          vars.tempw.xs[0], vars.tempx.xs[0], vars.tempy.xs[0],
          vars.tempz.xs[0], vars.tempaa.xs[0], vars.tempbb.xs[0],
          vars.tempcc.xs[0], vars.tempdd.xs[0], vars.tempee.xs[0],
          vars.tempff.xs[0], vars.tempgg.xs[0], vars.temphh.xs[0],
          vars.tempii.xs[0], vars.tempjj.xs[0], vars.tempkk.xs[0],
          vars.templl.xs[0], vars.tempmm.xs[0], vars.tempnn.xs[0],
          vars.tempoo.xs[0], vars.temppp.xs[0], vars.tempqq.xs[0],
          vars.temprr.xs[0], vars.tempss.xs[0], vars.temptt.xs[0],
          vars.tempuu.xs[0], vars.tempvv.xs[0]],     
          ys: [vars.tempa.ys[0],
          vars.tempb.ys[0], vars.tempc.ys[0], vars.tempd.ys[0],
          vars.tempe.ys[0], vars.tempf.ys[0], vars.tempg.ys[0],
          vars.temph.ys[0], vars.tempi.ys[0], vars.tempj.ys[0],
          vars.tempk.ys[0], vars.templ.ys[0], vars.tempm.ys[0],
          vars.tempn.ys[0], vars.tempo.ys[0], vars.tempp.ys[0],
          vars.tempq.ys[0], vars.tempr.ys[0], vars.temps.ys[0],
          vars.tempt.ys[0], vars.tempu.ys[0], vars.tempv.ys[0],
          vars.tempw.ys[0], vars.tempx.ys[0], vars.tempy.ys[0],
          vars.tempz.ys[0], vars.tempaa.ys[0], vars.tempbb.ys[0],
          vars.tempcc.ys[0], vars.tempdd.ys[0], vars.tempee.ys[0],
          vars.tempff.ys[0], vars.tempgg.ys[0], vars.temphh.ys[0],
          vars.tempii.ys[0], vars.tempjj.ys[0], vars.tempkk.ys[0],
          vars.templl.ys[0], vars.tempmm.ys[0], vars.tempnn.ys[0],
          vars.tempoo.ys[0], vars.temppp.ys[0], vars.tempqq.ys[0],
          vars.temprr.ys[0], vars.tempss.ys[0], vars.temptt.ys[0],
          vars.tempuu.ys[0], vars.tempvv.ys[0]]  })
      - sliding_window_moving_average:
          window_size: 1
          extended: true
      - sliding_window_moving_average:
          window_size: 3
          extended: true
      - sliding_window_moving_average:
          window_size: 3
          extended: true
defaults:
  entity:
    show_value: false
    internal: true
    yaxis: y1
    line:
      dash: dot
layout:
  legend:
    itemwidth: 3
  yaxis:
    title: Temperature °C
hours_to_show: 72
```

**Reply by dbuezas** [reply]
Very cool!

Here's a way to reduce the yaml size a bit:

```yaml
- entity: sensor.my_weather_temperature_0h
  filters:
    - fn:  "({xs, ys, vars}) => { vars.xs=[]; vars.ys=[];  }"
    - fn:  "({xs, ys, vars}) => { vars.xs.push(xs.at(-1)); vars.ys.push(ys.at(-1)); }"
- entity: sensor.my_weather_temperature_1h
  time_offset: 1h
  filters:
    - fn:  "({xs, ys, vars}) => { vars.xs.push(xs.at(-1)); vars.ys.push(ys.at(-1)); }"
- entity: sensor.my_weather_temperature_2h
  time_offset: 2h
  filters:
    - fn:  "({xs, ys, vars}) => { vars.xs.push(xs.at(-1)); vars.ys.push(ys.at(-1)); }"
#... etc
- entity: ''
  internal: false
  ...
  filters:
    - fn: "({vars}) => vars"
```

**Comment by wrowlands3** [comment]
I've got @Arrow-hub's method of forecast working - I want to plot 120 hourly datapoints into the future so even with @dbuezas's streamlined version of my code it gets a bit too chunky.
I've been trying to plot a forecast of the sun's elevation to use as a vars to combine with another forecasted attribute, but nowhere provides the elevation as an attribute. (It only varies by 1degree at noon over those 5 days, I don't need it more accurate, it's more to use for time of day that will remain accurate throughout the seasons)
I've tried time_offset:5d and map_x: new Date(+x + (5 * 24 * 60 * 60 * 1000)) both of which give me the correct plot and therefore vars, but as soon as I scroll back on the x-axis the plot remains fine but the vars function jumps around.

![correct2](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86292646/72a181da-c1f6-4d90-a0a2-207894941ea0)
This is the 'correct' plot
![notcorrect2](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86292646/e5e48df4-61da-4e55-bf07-5af11947a109)
Scrolling back 24 hours and then back to the start gives this

I've tried all variations of map_x and resample and !=null but to no avail.

```  
- entity: sensor.weather_forecast_tomorrowio_hourly
    line:
      color: orange
   filters:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [...meta.timelines[0].intervals.map(({ startTime }) => new Date(startTime))],
            ys: [...meta.timelines[0].intervals.map(({ values }) => 100-values.cloudCover)],
          })
      - resample: 5m
      - store_var: cloud
  - entity: sensor.sun_solar_elevation
    name: solar forecast
    line:
      color: blue
    time_offset: 5d
    internal: false
    filters:
      - resample: 5m
      - filter: y !== null
      - map_y: 'y >= 0 ? y : 0'
      - store_var: solar
  - entity: sensor.weather_forecast_tomorrowio_hourly
    name: The product that jumps around when scrolled
    fillcolor: blue
    fill: tozeroy
    line:
      color: red
    filters:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [...meta.timelines[0].intervals.map(({ startTime }) => new Date(startTime))],
            ys: [...meta.timelines[0].intervals.map(({ values }) => 100-values.cloudCover)],
          })
      - resample: 5m
      - map_y: (y)*vars.solar.ys[i]/100```
 ```
     
Since I want to plot vars.solar.ys onto vars.cloud.xs, I have made a rough equation that takes hass states of the various sun entities to give a y value with the only variable changing per data point the timestamp of the x value, but how would I plot that array for 120 datapoints provided by xs: [...meta.timelines[0].intervals.map(({ startTime }) => new Date(startTime))]?

This is the code I would use to make y, and hopefully include in fn: ys::
``` 
{% if datetime+Xhr > as_timestamp(states('sensor.sun_next_noon')) %}
{{ states('sensor.sun_solar_elevation')|float * (as_timestamp(states('sensor.sun_next_setting'))|float - datetime+Xhr) / (as_timestamp(states('sensor.sun_next_setting')) - as_timestamp(states('sensor.sun_next_noon'))) }}
{% else %}
{{ states('sensor.sun_solar_elevation')|float * (datetime+Xhr - as_timestamp(states('sensor.sun_next_rising'))) / (as_timestamp(states('sensor.sun_next_noon')) - as_timestamp(states('sensor.sun_next_rising'))) }}
{% endif %} ```
I would make a template sensor with these hours as attributes but I can't get a for loop to work well in the sensor template.

**Reply by dbuezas** [reply]
Sorry I have no idea what this is about 😅

**Reply by wrowlands3** [reply]
I'm trying to plot a forecast of 'sunlight'*'sun's elevation' to get the strength of the sun hourly over the next 5 days.
I have a forecast for the sunlight (or rather cloud cover %) but the sun's elevation is just the standard home assistant default sensor that reports past/current elevation. Because the elevation at any hour this week is so close to the same hour in the previous week, I have just time_offset this sensor 5d before storing as vars and multiplying with the cloud cover forecast. 

This works well until I drag plotly along the x-axis, which seems to throw the x-alignments of the new forecast out of sync as older 'suns elevation' sensor data is loaded. So for example if I drag the plot 12hours past, now the original plots remain accurate, though the time_offset elevation sensor now loads older data into that 12 hour history, while the cloud cover forecast remains just a forecast (not filling in the old 12 hours). But the vars product of the two sensors I want to show now has this 12 hour difference between the elevation and the cloud cover.

How can I ensure the two sensor x values remain in sync? I have tried many possible solutions but no luck yet.

**Reply by dbuezas** [reply]
is data available for all sensors in the past (when you scroll)?
Otherwise, the resample will unfortunately not know when to start and it will just pick the first available value.
You could try a `- map_y: 'i == 0 && !y ? -1 : y'` before the resample to test it

**Reply by wrowlands3** [reply]
Thanks, I managed to sort it. Another unrelated question though 😅 my forecast is a work in progress and I use a fill: tonexty that looks great:

![chopnot](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86292646/f81b5f62-90db-4b51-946f-ab6b3424aa6f)

but I want to use rangebreaks as I'm only interested in viewing daytime hours.
When I use xaxis rangbreaks the fill: tonexty no longer fills between the two grey lines. Any idea how to workaround this?

![chop](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86292646/f5e2c2e1-8e0c-4253-80c8-98fb818a01d6)

**Reply by dbuezas** [reply]
Mmmm that's a plotly limitation. You may be able to work around that by adding another trace with a transparent line and without rangebreaks.

**Reply by wrowlands3** [reply]
I got it! If anyone else finds this looking for answers. All it took was connectgaps: true.
It seems connectgaps: true connects across the rangebreaks

![Capture](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86292646/51f28fcf-c093-4c66-9059-18bf95f8880c)

**Comment by hughc-hub** [comment]
hi!

Today I've updated home assistant to latest:
Core 2024.4.0
Supervisor 2024.03.1
Operating System 12.1
Frontend 20240403.1

And now I have an error in all the cards that I had with a forecast line on them...
This part of the code:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [vars.temperature.xs.slice(-1)[0],...meta.forecast.map(({ datetime }) => new Date(datetime))],
            ys: [vars.temperature.ys.slice(-1)[0],...meta.forecast.map(({ temperature }) => temperature)],
          })

I receive this ERROR:
Error: at [entities.1.filters.0]: Error in filter: TypeError: undefined is not an object (evaluating 'meta.forecast.map')

Do you have the same issue? do you know how to solve it?
Thanks a lot!

**Reply by dbuezas** [reply]
The data is probably under a different key. You can try outputting the meta object to the console (see the debugging section in the readme)

**Reply by hughc-hub** [reply]
I think that it seems to be the weather forecast command.. now has been deleted in latest version. 
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/72790437/75e0104b-d259-44b2-a37b-fbc5552d6a6b)
Now we need to create a template triggered sensor to store forecast values... Then, add that sensor to the Plotly card and the code should keep working

thanks

**Reply by dbuezas** [reply]
The only thing that comes to mind is to use the hacs object directly to hack a call.
I think you'll be better off with a template sensor

**Reply by FillR2** [reply]
Same error here, **the plotly forecast card is so useful**, I hope someone will provide a solution !

**Reply by dbuezas** [reply]
You'll need a template sensor and an automation as the home assistant docs recommend

**Reply by FillR2** [reply]
Got the solution here;

https://community.home-assistant.io/t/how-to-handle-deprecation-of-the-weather-forecast-attribute-for-plotly-card/626002/5?u=fillr

**Reply by dbuezas** [reply]
Added it to the post

**Comment by JensAtHome** [comment]
Here is my flavour of the forecast plot

<img width="1004" height="640" alt="grafik" src="https://github.com/user-attachments/assets/ffd7a655-9772-4ff2-82b9-1703b6857234" />

I added an upper and lower forecast range, which spreads further in the future, reflecting the temperature offset to the weather station a few kilometers away and the increasing forecast uncertainty. I also added a gradient colorfill.

There is still one thing I would like to improve: omit the hover text for the error range plots. I could minimize it by using `hovertemplate: <extra></extra>. However, there is still a small arrow remaining, which is shown when hovering over the graph

<img width="150" height="183" alt="grafik" src="https://github.com/user-attachments/assets/a54d7229-57be-45d8-9077-8ed56fccaa46" />

Is there a way to completely disable the hover text?

Full code:

```
description: Load sensor data in first entity, save them as variable and reuse later
type: custom:plotly-graph
title: Wettervorhersage
time_offset: 9d
entities:
  - entity: sensor.dwd_forecast_hourly
    internal: true
    filters:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [...meta.forecast.map(({ datetime }) => new Date(datetime))],
            ys: [...meta.forecast.map(({ temperature }) => temperature)],
          })
      - store_var: temp_forecast
  - entity: sensor.gw2000a_outdoor_temperature
    legendgroup: 2
    name: 🌡 Temperatur
    line:
      color: rgba(214, 39, 40, 1)
  - entity: ""
    internal: true
    fn: $ex vars.offset = 1;
  - entity: ""
    internal: true
    fn: $ex vars.gradient = 0.25;
  - entity: ""
    legendgroup: 2
    showlegend: false
    name: Temperature forecast
    line:
      color: rgba(214, 39, 40, 1)
      dash: dot
    unit_of_measurement: °C
    filters:
      - load_var: temp_forecast
      - map_y: y = y + vars.offset + i/24 * vars.gradient
      - store_var: temphigh
    hovertemplate: <extra></extra>
  - entity: ""
    internal: true
    filters:
      - load_var: temphigh
      - store_var: max_temp
    statistic: max
  - entity: ""
    internal: true
    filters:
      - load_var: temp_forecast
      - map_y: y = y - vars.offset - i/24 * vars.gradient
      - store_var: templow
  - entity: ""
    internal: true
    filters:
      - load_var: templow
      - store_var: min_temp
    statistic: min
  - entity: ""
    legendgroup: 2
    showlegend: false
    name: Min. temperature forecast
    fill: tonexty
    fillgradient:
      start: vars.min_temp
      stop: vars.max_temp
      colorscale:
        - - 0
          - rgba(40, 39, 255, 1);
        - - 0.5
          - rgba(255, 255, 0, 1)
        - - 1
          - rgba(214, 39, 40, 1)
      type: vertical
    line:
      color: rgba(40, 39, 214, 1)
      dash: dot
    unit_of_measurement: °C
    filters:
      - load_var: templow
    hovertemplate: <extra></extra>
  - entity: ""
    legendgroup: 2
    showlegend: false
    name: Temperature forecast
    line:
      color: rgba(0, 0, 0, 1)
      dash: line
    unit_of_measurement: °C
    filters:
      - load_var: temp_forecast
  - entity: sensor.gw2000a_hourly_rain_piezo
    line:
      color: rgba(31, 119, 180, 1)
      width: 3
    legendgroup: 1
    name: 🌧 Niederschlag
    filters:
      - store_var: precipitation
  - entity: sensor.dwd_forecast_hourly
    legendgroup: 1
    showlegend: false
    name: Precipitation
    line:
      color: rgba(31, 119, 180, 1)
      dash: longdashdot
      width: 3
    unit_of_measurement: mm
    filters:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [vars.precipitation.xs.slice(-1)[0],...meta.forecast.map(({ datetime }) => new Date(datetime))],
            ys: [vars.precipitation.ys.slice(-1)[0],...meta.forecast.map(({ precipitation }) => precipitation)],
          })
  - entity: ""
    name: Now
    yaxis: y9
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: $ex [Date.now(), Date.now()]
    "y":
      - 0
      - 1
defaults:
  entity:
    show_value: false
    line:
      shape: spline
layout:
  legend:
    itemwidth: 30
hours_to_show: 240
refresh_interval: 900
```
