### DISCUSSION TITLE
Histogram view optimising

### DISCUSSION THREAD

**Discussion by thecem** [dbuezas/lovelace-plotly-graph-card#216] [Q&A]
I Love this histogram!!

![grafik](https://user-images.githubusercontent.com/46648579/215578608-7716169f-ecc3-4546-aea9-001f7beba547.png)

But the main graph is not aligned.

```YAML
type: custom:plotly-graph
entities:
  - entity: sensor.hmip_sens_out_stho_temperature
    period: day
    internal: true
    fn: $fn ({ ys, vars }) => vars.temperature = ys
  - entity: sensor.heizung_oil_consumption_in_energy
    filters:
      - resample: 1d
      - derivate: d
    internal: true
    fn: $fn ({ ys, vars }) => vars.oil = ys
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': $fn ({ vars }) => vars.oil
    mode: markers
    name: points
    marker:
      color: rgb(102,0,0)
      size: 2
      opacity: 0.4
    type: scatter
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': $fn ({ vars }) => vars.oil
    name: density
    ncontours: 20
    colorscale: YlGnBu
    nbinsx: 20
    nbinsy: 20
    reversescale: true
    showscale: false
    line:
      color: null
    type: histogram2dcontour
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    name: x density
    marker:
      color: "rgb(40\t57\t143\t)"
    yaxis: y2
    opacity: 1
    type: histogram
  - entity: ''
    x: undefined
    'y': $fn ({ vars }) => vars.oil
    name: y density
    marker:
      color: "rgb(40\t57\t143\t)"
    xaxis: x2
    type: histogram
hours_to_show: 4800
title: >-
  $fn({getFromConfig})=>`Heating - Last ${getFromConfig('hours_to_show')/24}
  days`
raw_plotly_config: true
layout:
  margin:
    t: 10
    l: 70
    r: 0
    b: 70
  height: 400
  bargap: 0.1
  showlegend: false
  xaxis:
    title:
      text: Outside Temperature (°C)
    autorange: true
    domain:
      - 0
      - 0.85
    showgrid: false
    zeroline: false
  yaxis:
    title:
      text: Oil burned (kWh per day)
    domain:
      - 0
      - 0.85
    showgrid: false
    zeroline: false
  xaxis2:
    domain:
      - 0.85
      - 1
    showgrid: false
    zeroline: false
  yaxis2:
    domain:
      - 0.85
      - 1
    showgrid: false
    zeroline: false

```

**Comment by dbuezas** [comment]
🤔 Did you save the yaml and reloaded the page? maybe the plot froze somehow?

**Reply by dbuezas** [reply]
Here that yaml works as intended 😕

**Comment by thecem** [comment]
I reloaded every chart, restart FF and tried in edge, same result.
the rest seems to working:
![grafik](https://user-images.githubusercontent.com/46648579/215585217-f060a972-301d-4d5e-aeca-2dd174db9995.png)

but maybe the data is not syncronized in a timely manner...

**Reply by thecem** [reply]
even I expect more bars for the consumption... because there is data for more than 200 days...

**Reply by dbuezas** [reply]
Different sensors maybe then? I'm not sure how this reacts with unavailable states (null)

**Reply by thecem** [reply]
the sensor don´t have state of 0 or unavailable...

**Reply by dbuezas** [reply]
Can you try  force_numeric anyway? Just in case. Also, fn: console.log and paste the generated x,y,z arrays. That way I can try to reproduce it

**Reply by thecem** [reply]
I tried force_numeric but no success.
Could you help me with `fn: console.log` where could I Found the output and on which entity I have to configure this?

**Reply by dbuezas** [reply]
Here: https://github.com/dbuezas/lovelace-plotly-graph-card#debugging

**Reply by thecem** [reply]
so with debuging I found the problem: My DATA!! 👿
But no problem I use diffrent data with the same result: 😍 

![grafik](https://user-images.githubusercontent.com/46648579/215758144-9bfeab1c-e8a0-4778-8ed5-29043435de51.png)


Guess whats missing in the chart:

The trendline set for filters in markers but not shown... any idea?

```YAML
type: custom:plotly-graph
entities:
  - entity: sensor.hmip_sens_out_stho_temperature
    statistic: mean
    period: day
    filters:
      - filter: i>0
    time_offset: '-1d'
    fn: $fn ({ ys, vars }) => vars.temperature = ys
  - entity: sensor.daily_heizoel
    statistic: state
    period: day
    unit_of_measurement: kWh
    name: Heizöl
    internal: true
    filters:
      - filter: i>0
      - map_y_numbers: y * 10
    fn: $fn ({ ys, vars }) => vars.oil = ys
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': $fn ({ vars }) => vars.oil
    mode: markers
    name: points
    marker:
      color: rgb(102,0,0)
      size: 3
      opacity: 0.4
    filters:
      - trendline
    type: scatter
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': $fn ({ vars }) => vars.oil
    name: density
    ncontours: 20
    colorscale: YlGnBu
    nbinsx: 20
    nbinsy: 20
    reversescale: true
    showscale: false
    line:
      color: null
    type: histogram2dcontour
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    name: x density
    marker:
      color: "rgb(40\t57\t143\t)"
    yaxis: y2
    opacity: 1
    type: histogram
  - entity: ''
    x: undefined
    'y': $fn ({ vars }) => vars.oil
    name: y density
    marker:
      color: "rgb(40\t57\t143\t)"
    xaxis: x2
    type: histogram
hours_to_show: 4800
title: >-
  $fn({getFromConfig})=>`Heating - Last ${getFromConfig('hours_to_show')/24}
  days`
raw_plotly_config: true
layout:
  margin:
    t: 10
    l: 70
    r: 10
    b: 70
  height: 400
  bargap: 0.1
  showlegend: false
  xaxis:
    title:
      text: Outside Temperature (°C)
    autorange: true
    domain:
      - 0
      - 0.85
    showgrid: false
    zeroline: false
  yaxis:
    title:
      text: Oil burned (kWh per day)
    domain:
      - 0
      - 0.85
    showgrid: false
    zeroline: false
  xaxis2:
    domain:
      - 0.85
      - 1
    showgrid: false
    zeroline: false
  yaxis2:
    domain:
      - 0.85
      - 1
    showgrid: false
    zeroline: false

```

**Reply by dbuezas** [reply]
Cool! I think height: 600 will look even better.

For the trendline you'll have to pick up the xs and ys inside a filter (instead of just x and y at the entity level)
I know that's not very intuitive, maybe I change that at dome point in the future

**Reply by dbuezas** [reply]
Or increase the nbinsx to 40

**Reply by thecem** [reply]
something like this to get the trendline?

```YAML
    filters:
      - fn: |
         ({ys, xs, vars}) => {
           return {xs: vars.temperaure, ys: vars.oil};
         }
      - trendline
```

**Reply by dbuezas** [reply]
Exactly. I think it should work. But it doesn't.
It is an ugly mess and doesn't really work well 
```yaml
  - entity: ''
    filters:
      - fn: |
          ({vars}) => {
            const xs = vars.temperature;
            const ys = vars.oil;
            const pairs = xs.map((x, i) => [x,ys[i]])
              .filter( ([x,y]) => Number.isFinite(x) && Number.isFinite(y)) // unavailables in the x axis break trendlines
              .sort((a,b)=>a[0]-b[0]); // the trendline filter expects the x axis to be sorted
            const r = {
              xs: pairs.map(([x,y])=>x),
              ys: pairs.map(([x,y])=>y),
            };
            console.log(r);
            return r;
          }
      - trendline
      - store_var: trend
    x: $fn ({ vars }) => vars.trend.xs.map(x=>+x) // the trendline made dates out of the x axis
    'y': $fn ({ vars }) => vars.trend.ys // and since this is a raw_plotly_config, we need to set x and y ourselves
```
<img width="486" alt="image" src="https://user-images.githubusercontent.com/777196/215863682-2a2e091c-999b-491d-b773-4726e6ee9997.png">

The release is only a couple of days old and you already reached its limits it seems

**Reply by MarkoPaasila** [reply]
What does `filter: i>0` do?

**Reply by dbuezas** [reply]
`i` is the index. `filter: i>0` means remove the first data point (the one with index 0), so the left most value

**Comment by thecem** [comment]
Actual I get following error:

![grafik](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/46648579/1fd95d5e-e80c-4292-a873-38fd8ba19029)


<details>
  <summary>config</summary>

```
type: custom:plotly-graph
entities:
  - entity: sensor.at_yesterday
    statistic: mean
    period: day
    time_offset: '-1d'
    internal: true
    filters:
      - filter: i>0
    fn: $fn ({ ys, vars }) => vars.temperature = ys
  - entity: sensor.gas_verbrauch_kwh
    statistic: state
    period: day
    name: Gas
    internal: true
    filters:
      - filter: i>0
      - derivate: d
    fn: $fn ({ ys, vars }) => vars.gas = ys
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': $fn ({ vars }) => vars.gas
    mode: markers
    name: points
    marker:
      color: rgb(102,0,0)
      size: 3
      opacity: 0.4
    type: scatter
  - entity: ''
    line:
      shape: linear
      color: blue
    filters:
      - fn: |
          ({ys, xs, vars}) => {
            return {xs: vars.temperature, ys: vars.gas};
          }
      - trendline
  - entity: ''
    filters:
      - fn: |
          ({vars}) => {
            const xs = vars.temperature;
            const ys = vars.gas;
            const pairs = xs.map((x, i) => [x,ys[i]])
              .filter( ([x,y]) => Number.isFinite(x) && Number.isFinite(y)) // unavailables in the x axis break trendlines
              .sort((a,b)=>a[0]-b[0]); // the trendline filter expects the x axis to be sorted
            const r = {
              xs: pairs.map(([x,y])=>x),
              ys: pairs.map(([x,y])=>y),
            };
            console.log(r);
            return r;
          }
      - trendline
      - store_var: trend
    x: >-
      $fn ({ vars }) => vars.trend.xs.map(x=>+x) // the trendline made dates out
      of the x axis
    'y': >-
      $fn ({ vars }) => vars.trend.ys // and since this is a raw_plotly_config,
      we need to set x and y ourselves
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': $fn ({ vars }) => vars.gas
    name: density
    ncontours: 40
    colorscale: YlGnBu
    nbinsx: 15
    nbinsy: 15
    reversescale: true
    showscale: false
    line:
      color: lightgray
    type: histogram2dcontour
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    name: x density
    texttemplate: '%{x:0.0f}'
    marker:
      color: "rgb(40\t57\t143\t)"
    yaxis: y2
    opacity: 1
    type: histogram
  - entity: ''
    x: undefined
    'y': $fn ({ vars }) => vars.gas
    name: y density
    texttemplate: '%{y:0.0f}'
    marker:
      color: "rgb(40\t57\t143\t)"
    xaxis: x2
    type: histogram
hours_to_show: 2112
title: >-
  $fn({getFromConfig})=>`Heating - Last ${getFromConfig('hours_to_show')/24}
  days`
raw_plotly_config: true
layout:
  margin:
    t: 20
    l: 70
    r: 20
    b: 70
  height: 400
  bargap: 0.1
  showlegend: false
  xaxis:
    title:
      text: Outside Temperature (°C)
    autorange: true
    domain:
      - 0
      - 0.85
    showgrid: false
    zeroline: false
  yaxis:
    title:
      text: Gas burned (kWh per day)
    domain:
      - 0
      - 0.85
    showgrid: false
    zeroline: false
  xaxis2:
    domain:
      - 0.85
      - 1
    showgrid: false
    zeroline: false
  yaxis2:
    domain:
      - 0.85
      - 1
    showgrid: false
    zeroline: false

```
</details>

May you could help me with the newest filters?

**Reply by dbuezas** [reply]
Apply resample to both series before storing it to vars. This will ensure they have the same amount of datapoints, and that they are aligned in time.

**Reply by thecem** [reply]
Actual I get following:

![grafik](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/46648579/da89d818-1f1a-4b69-beb3-051168108bcb)


<details>
  <summary>config</summary>

```
type: custom:plotly-graph
entities:
  - entity: sensor.hmip_sens_out_stho_temperature
    statistic: mean
    period: day
    time_offset: '-1d'
    fn: $fn ({ ys, vars }) => vars.temperature = ys
  - entity: sensor.daily_heizoel
    statistic: state
    period: day
    unit_of_measurement: kWh
    name: Heizöl
    internal: true
    filters:
      - map_x: x > 10
      - filter: i>0
      - map_y_numbers: y * 10
    fn: $fn ({ ys, vars }) => vars.oil = ys
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': $fn ({ vars }) => vars.oil
    mode: markers
    name: points
    marker:
      color: rgb(102,0,0)
      size: 3
      opacity: 0.4
    type: scatter
  - entity: ''
    line:
      shape: linear
      color: blue
    filters:
      - fn: |
          ({ys, xs, vars}) => {
            return {xs: vars.temperature, ys: vars.oil};
          }
      - trendline
  - entity: ''
    line:
      color: green
    filters:
      - fn: |
          ({vars}) => {
            const xs = vars.temperature;
            const ys = vars.oil;
            const pairs = xs.map((x, i) => [x,ys[i]])
              .filter( ([x,y]) => Number.isFinite(x) && Number.isFinite(y)) // unavailables in the x axis break trendlines
              .sort((a,b)=>a[0]-b[0]); // the trendline filter expects the x axis to be sorted
            const r = {
              xs: pairs.map(([x,y])=>x),
              ys: pairs.map(([x,y])=>y),
            };
            console.log(r);
            return r;
          }
      - trendline
      - store_var: trend
    x: >-
      $fn ({ vars }) => vars.trend.xs.map(x=>+x) // the trendline made dates out
      of the x axis
    'y': >-
      $fn ({ vars }) => vars.trend.ys // and since this is a raw_plotly_config,
      we need to set x and y ourselves
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': $fn ({ vars }) => vars.oil
    name: density
    ncontours: 40
    colorscale: YlGnBu
    nbinsx: 40
    nbinsy: 40
    reversescale: true
    showscale: false
    line:
      color: lightgray
    type: histogram2dcontour
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    name: x density
    texttemplate: '%{x:0.0f}°C'
    marker:
      color: "rgb(40\t57\t143\t)"
    yaxis: y2
    opacity: 1
    type: histogram
  - entity: ''
    x: undefined
    'y': $fn ({ vars }) => vars.oil
    name: y density
    texttemplate: '%{y:0.0f}kWh'
    marker:
      color: "rgb(40\t57\t143\t)"
    xaxis: x2
    type: histogram
hours_to_show: 8760
title: >-
  $fn({getFromConfig})=>`Heating - Last ${getFromConfig('hours_to_show')/24}
  days`
raw_plotly_config: true
layout:
  margin:
    t: 20
    l: 70
    r: 20
    b: 70
  height: 600
  bargap: 0.1
  showlegend: false
  xaxis:
    title:
      text: Outside Temperature (°C)
    autorange: true
    domain:
      - 0
      - 0.85
    showgrid: false
    zeroline: false
  yaxis:
    title:
      text: Oil burned (kWh per day)
    domain:
      - 0
      - 0.85
    showgrid: false
    zeroline: false
  xaxis2:
    domain:
      - 0.85
      - 1
    showgrid: false
    zeroline: false
  yaxis2:
    domain:
      - 0.85
      - 1
    showgrid: false
    zeroline: false

```
</details>

How could I filter values starting with 10kWh and don´t show the 0 kWh values?

Would it be possible to show a second graph with the new heatpump and the same for period x in the past with the old oil heating system?

THX!
