### DISCUSSION TITLE
Show the current day from midnight to midnight

### DISCUSSION THREAD

**Discussion by elbertov** [dbuezas/lovelace-plotly-graph-card#220] [Show and tell]
Hi,

If you want to show the current day from midnight to midnight you will have to set _hours_to_show_ to 24 and the _time_offset_ to the remaining hours on the day, so this depends on what time it is when you are looking at the graph. You can calculate the remaining hours  using a universal function.

```yaml
type: custom:plotly-graph
title: Outside temperature
hours_to_show: 24
time_offset: |-
  $fn () =>  { 
    now = new Date(); 
    tomorrow = new Date(now);
    tomorrow.setDate(tomorrow.getDate() + 1); 
    tomorrow.setHours(0,0,0,0);                                           // midnight
    HoursLeftToday = (tomorrow.getTime() - now.getTime()) / 1000 / 3600;  // milliseconds to hours
    return HoursLeftToday.toFixed(1) + "h";                               // only 1 decimal allowed for 'hours_to_show'
  }
entities:
  - entity: sensor.buienradar_temperature
    time_offset: 1d
    name: yesterday
  - entity: sensor.buienradar_temperature
    name: today
```

Be aware that the _time_offset_ with the universal funcion has to be before the ```entities``` due to order dependencies.

![image](https://user-images.githubusercontent.com/58105716/215713944-53c842e1-919d-449f-9d5f-a60c27edeb1b.png)

**Comment by miljbee** [comment]
Hello,

Thanks for sharing, I suggest a shorter version for the time_offset and some other small improvements:
````yaml
type: custom:plotly-graph
time_offset: $fn () => (86400000-(Date.now() % 86400000)).toFixed(0) + 'ms'
entities:
  - entity: sensor.tmp_dehors_temperature
    name: Hier
    time_offset: 1d
    filters:
      - force_numeric
      - resample: 5m
      - sliding_window_moving_average:
          window_size: 15
          extended: true
          centered: true
    type: line
  - entity: sensor.tmp_dehors_temperature
    name: Today
    filters:
      - force_numeric
      - store_var: today
      - resample: 5m
      - sliding_window_moving_average:
          window_size: 15
          extended: true
          centered: true
    type: line
    showlegend: false
  - entity: sensor.nothing_now
    name: now
    yaxis: y9
    showlegend: false
    line:
      width: 1.5
      dash: dot
      color: '#e68a00'
    filters:
      - force_numeric
      - fn: () => { return {xs:[Date.now(),Date.now()], ys:[0,1]} }
layout:
  showlegend: true
  yaxis9:
    rangemode: tozero
  xaxis:
    nticks: 3
  dragmode: false
config:
  scrollZoom: false
hours_to_show: 24
refresh_interval: auto
title: $fn ( { vars } ) => 'Températures Today ' + vars.today.ys.slice(-1) + '°C'
````
![image](https://user-images.githubusercontent.com/637997/215761538-ba7478e0-01d4-48c4-96dc-e08d8fd042e0.png)

**Reply by dbuezas** [reply]
Really cool! You could even make the `time_offset` pick the constant from `hours_to_show`, see [getFromConfig](https://github.com/dbuezas/lovelace-plotly-graph-card#everywhere)
I'm so happy to see such advanced stuff done with the universal functions so quickly after the release :)

**Reply by dbuezas** [reply]
For the "nothing_now" trace, check out the [new example](https://github.com/dbuezas/lovelace-plotly-graph-card#now-line) in the readme. I think it is slightly less hacky

**Comment by elbertov** [comment]
Hi Miljbee,

Thx for the nice suggestions!

The short version: `$fn () => (86400000-(Date.now() % 86400000)).toFixed(0) + 'ms'` should do the job one would say, but the graph shifts 1 hour, so the graphs starts on 1am and ends on 1am. It's a timezone thing I think...

**Comment by miljbee** [comment]
Good catch, I should have think twice before posting. I will try to fix
it...

**Comment by dbuezas** [comment]
I think this works fine:
```yaml
type: custom:plotly-graph
hours_to_show: 24
time_offset: |-
  $fn ({ getFromConfig }) => {
    const ms_to_show = getFromConfig('hours_to_show') * 60 * 60 * 1000;
    const now_utc = Date.now() - new Date().getTimezoneOffset() * 60 * 1000;
    return ms_to_show - now_utc % ms_to_show + 'ms'
  }
title: $fn({getFromConfig}) => 'Showing ' + getFromConfig('hours_to_show')+'h'
entities:
  - entity: sensor.openweathermap_temperature
```
<img width="469" alt="image" src="https://user-images.githubusercontent.com/777196/215845126-2bc4c752-5226-4ffe-ad3e-deb9596a31a9.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/777196/215845212-6c739a07-8d8a-4246-b749-35d843f1d356.png">
<img width="464" alt="image" src="https://user-images.githubusercontent.com/777196/215845180-ccd12423-f62c-40d9-8cd9-d414b1bee2c0.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/777196/215845289-2fba5cb5-d65c-4454-8b72-d84476b13049.png">

But it obviously doesn't work for weeks, months or years.

**Comment by dbuezas** [comment]
For the config support of this, I'm think of something like this to get the start of the range:

```js
// Alternatives welcome. Javascript's Date class is so cumbersome.
year = new Date(new Date().setMonth(0,1)).setHours(0,0,0,0);
month = new Date(new Date().setDate(0)).setHours(0,0,0,0);
week = new Date(new Date().setDate(new Date().getDate() + 1 - new Date().getDay())).setHours(0,0,0,0);
day = new Date().setHours(0,0,0,0);
hour = new Date().setMinutes(0,0,0);
minute = new Date().setSeconds(0,0);
```
<img width="574" alt="image" src="https://user-images.githubusercontent.com/777196/215849135-c875cda4-01f9-4ff2-8605-bbb6b622d3ee.png">

And similarly for the end dates. Then the equivalency should be:
```js
hours_to_show = end - start;
time_offset = end - now - timezoneOffset ;
```

**Reply by elbertov** [reply]
Sounds good, does it follow the `first_weekday` in the config of the user this way?

**Reply by dbuezas** [reply]
oh, there's that too? 🤦

**Reply by dbuezas** [reply]
I think I got the dates math mostly right, but the code is absolutely impossible to read. I'll use date-fns instead:
https://date-fns.org/v2.29.3/docs/endOfMinute

It's supposed to be an efficient lib, and plotlyjs is huge anyway, so I rather pick their work. It's easier for me to maintain this and avoid bugs

**Reply by miljbee** [reply]
Yeah that would be great if there was an easy way to define the range of the graph. But if you implement something, I think that it may be more explicit to do something like : 
Specify 2 of
- start (now, minute, hour, day, week, month, year)
- end (now, minute, hour, day, week, month, year)
- duration (xU x = number, U = unit: y,d,h,m,s,ms)

hours_to_show could be kept for compatibility reasons. It should be used only if start, end, duration are not specified.

time_offset is not always easy to figure, it seems more obvious for entities, since it's used to 'shift' the raw data, but for the main config, start end, duration seem to make more sense.

`time_offset = end - now - timezoneOffset ;`

why do you remove timezoneOffset, the dates in start and end aren't TZ aware ?

**Reply by dbuezas** [reply]
Correct, date-fns handles the offsets.
The feature looks like this:
```yaml
hours_to_show: current_day
```
And the feature is called `Dynamic Relative Time`. ChatGPT is amazing for brainstorming names of things
<img width="608" alt="image" src="https://user-images.githubusercontent.com/777196/215874404-ee973085-f3f6-4a0a-93ba-436843c9c8de.png">

**Reply by dbuezas** [reply]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/777196/215884204-97b737f7-e2c0-420d-9d7c-68ddd6362959.png">
Then the visible range is set to that, plus the global time_offset.
Aaaaand i forgot about the user configured start of the week.
Let's see how long until someone requests it 😁

**Comment by dbuezas** [comment]
From: https://github.com/dbuezas/lovelace-plotly-graph-card#dynamic-relative-time

> Dynamic Relative Time
> Shows the current day, hour, etc from beginning to end. The options are: current_minute, current_hour, current_day, current_week, current_month, current_quarter, current_year It can be combined with the global time_offset.

Released in v3.1.0

**Comment by elbertov** [comment]
🤣

⁣BlueMail voor Android downloaden ​

Op 31 jan. 2023 21:25, om 21:25, David Buezas ***@***.***> schreef:

**Reply by dbuezas** [reply]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/777196/215886450-d0897c99-8a5a-4ad7-a235-d610ac29dee4.png">

I told you, it can't be shorter. Somebody should use a Universal Function to set the Dynamic Relative Time, also known as "simply setting the time range"

**Reply by elbertov** [reply]
Don't forget to drink a beer before going to sleep, I sent you some 🥇 

![image](https://user-images.githubusercontent.com/58105716/215887844-dc4af7db-22fb-4c15-b5c3-6f87cd84a657.png)

![image](https://user-images.githubusercontent.com/58105716/215887879-b84dcebe-d9ce-48dc-8d91-d060365ae89c.png)

![image](https://user-images.githubusercontent.com/58105716/215887910-8921e0d6-37aa-45a8-968b-c036fc913146.png)

![image](https://user-images.githubusercontent.com/58105716/215887927-ddfc5ff5-ee62-4fe8-a55b-9c45550f9c32.png)

**Reply by dbuezas** [reply]
Haha, thanks! Glad to see it in action so quickly!

**Comment by elbertov** [comment]
Hi David,

When I use this:

```yaml
type: custom:plotly-graph
hours_to_show: current_week
entities:
  - entity: sensor.gas_consumed
    type: bar
    statistic: state
    period: day
    filters:
      - delta
```

I expect to see my gas_consumption per day for every day in the current_week. But initially the first day is not shown, you have to scroll a little:

![current_week_delta](https://user-images.githubusercontent.com/58105716/216782162-4de9a393-4bac-486c-940a-ef2a2e53ba7c.gif)
(In the gif I show this as a bar as well as a line: same effect)

Is this easy to fix for you in the filter? The same for month etc.

_current_year_ has the following effect:
```yaml
type: custom:plotly-graph
hours_to_show: current_year
entities:
  - entity: sensor.gas_consumed
    type: bar
    statistic: state
    period: month
    filters:
      - delta
layout:
  yaxis:
    range:
      - 0
      - 250
```

![current_year_delta](https://user-images.githubusercontent.com/58105716/216782660-29a10dbf-b703-4555-8d2e-e2455521ed61.gif)


It would be nice if the first bar is shown completely, e.g:

![image](https://user-images.githubusercontent.com/58105716/216782396-be335482-8b5c-4e44-8622-6c8d7ef7c9db.png)


regards Martin

**Reply by dbuezas** [reply]
Yes, that's small quirk coming from the fact that the delta needs two values for its first input. The filters are evaluated after the information is fetched, and the cache system is not clever enough to fetch an initial value before the range you are seeing.
A solutions you can apply is to use a global `time_offset: -1d` so that an extra datapoint is fetched (one from before the start of the year)

**Reply by dbuezas** [reply]
Oh, I meant to say that it needs 2 datapoints for the first result (because delta means the difference between two consecutive datapoints).
The global `time_offset` just shifts the whole visible range (not the data), so the cache asks home assistant for the data inside an interval that has been shifted a tad.
BTW, you can do `time_offset: 1s` if you want, it just needs to be an instant before the start of the first day.

**Reply by dbuezas** [reply]
Aaand I just realized which Martin you are
Hi Martin 👋

**Reply by elbertov** [reply]
Hi David 👋 (you will talk to a lot of Martins lol, so no problem :-)),

I understand you, and it works if the previous available data is within that `time_offset`. When the data comes from the statistics table the minimum `time_offset `has to be `-1h`. So `time_offset: -1h` in my previous example gives me the following (bar not completely in sight, but ok):

```yaml
type: custom:plotly-graph
hours_to_show: current_year
time_offset: '-1h'
entities:
  - entity: sensor.gas_consumed
    name: 2023
    type: bar
    statistic: state
    period: month
    filters:
      - delta
layout:
  height: 400
```
![image](https://user-images.githubusercontent.com/58105716/216788452-2ac3f500-06c1-40f1-9114-a110fe426366.png)

What is happening, I think, is that the calculated delta value is shifted 1 hour too, so strictly speaking the values are not correct, but for 1 hour in this example it's not really a problem.

Then the next case, where it goes too much wrong: I want to compare two or more years with `type:bar.` But to create enough space for the bars, I have to increase the `time_offset` a lot..., I'll show you:

```yaml
type: custom:plotly-graph
hours_to_show: current_year
time_offset: '-0d'
entities:
  - entity: sensor.gas_consumed
    name: 2022
    time_offset: 1y
    type: bar
    statistic: state
    period: month
    filters:
      - delta
  - entity: sensor.gas_consumed
    name: 2023
    type: bar
    statistic: state
    period: month
    filters:
      - delta
layout:
  height: 400
```

![image](https://user-images.githubusercontent.com/58105716/216788655-493750f6-fdb3-4a11-9ed7-8157fdded433.png)

(effectively no time_offset, January not visible, december showing the correct value 291.66)

The work-around ```time_offset: -1h```, does the following:

![image](https://user-images.githubusercontent.com/58105716/216788797-8a584996-ab85-4845-9b22-72d20f3ee1bc.png)

One "January-bar" becomes visible, but one is missing (the blue one, left of the orange) and you already see the value of December isn't correct anymore.

If I want to show the entire blue bar, I'll have to use `time_offset: -14d` , but that spoils the calculation of the delta's significantly...
Also the orange January value: from 220 to more then 300...

![image](https://user-images.githubusercontent.com/58105716/216788888-e2853e13-ff60-4ed5-84cf-26a0f8e75f48.png)

So the ```time_offset: -1h``` fetches enough data (if available in database), but the ```type: bar``` has not enough room to show all of the bars...

```type: line``` is fine with ```time_offset: -1h```, but I don't like that :-(

![image](https://user-images.githubusercontent.com/58105716/216789428-18dd4f05-6a6a-40d3-bfc2-c1c6336467a3.png)

So the question is: can you give the bars more room, so the ```time_offset: -1h``` work-around works better for bars?

I want to make a better graph with plotly-graph then the default energy chart lol:
![image](https://user-images.githubusercontent.com/58105716/216789685-0411b25b-f7a8-4918-a8f1-4fc79ccadcf7.png)
