### DISCUSSION TITLE
Auto adjust Y-scale when using rangeselector?

### DISCUSSION THREAD

**Discussion by kuttikutt** [dbuezas/lovelace-plotly-graph-card#221] [Q&A] [answered]
Hello,
I set up a graph like this:

```
type: custom:plotly-graph
title: Netzleistung
entities:
  - entity: sensor.tasmota_ebz_aktuelle_wirkleistung
    line:
      color: red
      width: 1
refresh_interval: 10
hours_to_show: 24
layout:
  xaxis:
    rangeselector:
      'y': 1
      buttons:
        - count: 1
          step: minute
        - count: 1
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 7
          step: day
```

The problem: The usage goes up dan down between +10kW and -10kW
When I click in "1h" it's between like -100 and +500W, but the Y-scale stays at -10kW and +10kW

see:
1d:
![grafik](https://user-images.githubusercontent.com/17554764/215714998-a44ade3c-3cbb-4be3-bd9c-5c67fd458a45.png)
1h:
![grafik](https://user-images.githubusercontent.com/17554764/215716969-031faff7-a78f-47c7-859e-2524625f2a09.png)

but I want it like this (y-scale is set automatically on click on "1h"):
![grafik](https://user-images.githubusercontent.com/17554764/215715374-663a3921-bca3-490b-8c42-00fd5d002dee.png)

I tried several things, but no luck so far :/ any hints?

**Comment by dbuezas** [comment, marked as answer]
try with
```yaml
layout:
  yaxis:
    autorange: true
```
