### DISCUSSION TITLE
Heat Energy Bar chart

### DISCUSSION THREAD

**Discussion by thecem** [dbuezas/lovelace-plotly-graph-card#223] [Show and tell]
![grafik](https://user-images.githubusercontent.com/46648579/215763936-23744107-51a3-49ef-ab21-757c67952df2.png)

```YAML
type: custom:plotly-graph
entities:
  - entity: sensor.hmip_sens_out_stho_temperature
    statistic: mean
    period: hour
    name: Aussentemp
    show_value: true
  - entity: sensor.at_yesterday
    statistic: mean
    period: day
    time_offset: '-1d'
    extend_to_present: true
    show_value: true
  - entity: sensor.eg_energy_daily
    statistic: state
    period: day
    filters:
      - store_var: egenergy
    show_value: true
  - entity: sensor.odg_energy_daily
    statistic: state
    period: day
    show_value: true
  - entity: sensor.odg_energy_daily
    statistic: state
    period: day
    type: bar
    opacity: 0.5
    texttemplate: '%{y:0.1f}'
    name: Heating Energy
    filters:
      - filter: i>0
      - map_y: y + vars.egenergy.ys[i]
  - entity: sensor.daily_heizoel
    statistic: state
    period: day
    unit_of_measurement: kWh
    name: Heizöl
    texttemplate: '%{y:0.1f}'
    type: bar
    opacity: 0.5
    filters:
      - filter: i>0
      - map_y_numbers: y * 10
title: Heat Energy LTS
hours_to_show: 576
refresh_interval: 10
```

To align the bars you have to add  " - filter: i>0" # the first value has the timestamp of the beginning of the plot, not the day (home assistant API)

**Comment by sanderlv** [comment]
Look so cool! I am trying to use your example to visualize my heating system. 

Result so far:
![image](https://github.com/user-attachments/assets/b1cc7032-1486-44a2-9699-e8882e4bd8a2)

What is sensor.odg_energy_daily providing in your setup?
I am trying to view the amount of gas vs the outside temp(s).

```
type: custom:plotly-graph
entities:
  - entity: sensor.zw100_multisensor_6_air_temperature
    statistic: mean
    period: hour
    name: Buiten Temperatuur
    show_value: true
  - entity: sensor.zw100_multisensor_6_air_temperature
    statistic: mean
    period: day
    name: Buiten Temperatuur Gisteren
    time_offset: "-1d"
    extend_to_present: true
    show_value: true
  - entity: sensor.odg_energy_daily
    statistic: state
    period: day
    show_value: true
  - entity: sensor.odg_energy_daily
    statistic: state
    period: day
    type: bar
    opacity: 0.5
    texttemplate: "%{y:0.1f}"
    name: Heating Energy
    filters:
      - filter: i>0
      - map_y: y + vars.egenergy.ys[i]
  - entity: sensor.daily_gas
    statistic: state
    period: day
    unit_of_measurement: kWh
    name: Gas
    texttemplate: "%{y:0.1f}"
    type: bar
    opacity: 0.5
    filters:
      - filter: i>0
      - map_y_numbers: y * 10
title: Gas Heating
hours_to_show: 576
refresh_interval: 10
```
