### DISCUSSION TITLE
My electricity price dashboard (with future prices)

### DISCUSSION THREAD

**Discussion by edwardtfn** [dbuezas/lovelace-plotly-graph-card#224] [Show and tell]
My first time playing with  this card, I've created an electricity price dashboard where we can see the price per kWh and my consumption (also in kWh), so I can take decision on when to run my appliances and try to save some money.
I've also added a line to show now, with the current price.

![DEB80223-29E2-46C9-9D12-56B27F130BB3](https://user-images.githubusercontent.com/94725493/215847713-1cec7016-d71e-4d17-a6a4-abd690159ee3.jpeg)

```yaml
type: custom:plotly-graph
time_offset: 1.5d
refresh_interval: 300
hours_to_show: 84
layout:
  xaxis:
    rangeselector:
      'y': 1.2
      buttons:
        - count: 7
          step: day
        - count: 12
          step: day
  yaxis:
    rangemode: tozero
    tickformat: .1f
  yaxis2:
    rangemode: tozero
    tickformat: .2f
    fixrange: true
  yaxis9:
    visible: false
    fixedrange: true
round: 2
default: null
entities:
  - entity: sensor.total_energy_utility_meter
    name: Energy consumption
    type: bar
    marker:
      color: rgba(165,165,0,0.6)
    texttemplate: ' %{y:.2f} kr/kWh'
    statistic: state
    period: hour
    filters:
      - fn: |-
          (params) => {
            const ys = [];
            ys.push(0); 
            for (let i = 1; i < params.statistics.length; i++){
              ys.push(params.statistics[i].state-params.statistics[i-1].state);
            }
            return { ys };
          }
  - entity: sensor.electricity_price
    yaxis: y2
    unit_of_measurement: kr/kWh
    line:
      color: rgba(255, 165, 0, 1)
      width: 3
    filters:
      - store_var: electricity_price
      - exponential_moving_average:
          alpha: 1
    show_value: true
    texttemplate: ' %{y:.2f} kr/kWh'
  - entity: sensor.electricity_price
    yaxis: y2
    name: Future price
    fill: tozeroy
    fillcolor: rgba(255, 165, 0,.1)
    line:
      color: rgba(255, 165, 0, 1)
      width: 1
      dash: dot
    filters:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [vars.electricity_price.xs.slice(-1)[0],...meta.future_prices.map(({ startsAt }) => new Date(startsAt))],
            ys: [vars.electricity_price.ys.slice(-1)[0],...meta.future_prices.map(({ total }) => total)],
          })
      - exponential_moving_average:
          alpha: 1
  - entity: ''
    name: Now
    yaxis: y9
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: $fn () => [Date.now(), Date.now()]
    'y': $fn () => [0,1]
```

You can find [here my sensors for electricity price from Tibber](https://github.com/edwardtfn/HomeAssistant-Config/blob/main/packages/electricity/tibber.yaml). I'm not using the official Tibber integration for that, as I got more stable/reliable sensors with direct REST queries.
In that same repository you can find all my energy consumption calculations per room and total at home, used in an utility meter and.then used as a sensor in this dashboard.

Don't hesitate to ask if you have any question. I would love to help.

**Comment by princetiwoz** [comment]
@edwardtfn Thanks for the quick reply. I am struggling to get the future prices from the array. I use nordpool data.
I see you created a sensor for future prices or am i getting it wrong?

**Reply by edwardtfn** [reply]
Yes, I have created a sensor for future prices as I use that in some other places, but wait a bit, I will try to adapt this to NordPool... Hold on.

**Reply by Rincovanderbeek** [reply]
Hi edward,  I copied exactly your tibber code but I get a error in plotly.
Checking sensor.electricity_price looks fine, all data is in.
Any chance you can see what's causingthe error?
![Knipsel](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/76967369/7b0ce87a-d88c-44ad-97bc-99a6fab45412)
![Knipsel](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/76967369/9b465b66-f506-4d1f-b0c4-d0eec986525e)

**Reply by dbuezas** [reply]
Check the attributes of your sensor.electricity_price in [![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/).
You are most likely missing the "future_prices" attribute.
I assume you have a different provider and integration

**Reply by Rincovanderbeek** [reply]
Thanks for your quick reply.  
I use tibber, so that should be equal.  I checked teh attribues but future prices are in.
If I move my mouse over the graph, the yellow line states future price which is strange as it is current or past price.

![Knipsel](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/76967369/e4c4ec69-edee-472a-9a4a-60710316283c)
![Knipsel](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/76967369/dca21040-0987-40a7-98ad-8d7fdaaf0a6c)
![Knipsel](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/76967369/4dbabc51-97d6-43b6-966f-5dc96df5ecce)

**Reply by dbuezas** [reply]
It looks like the attribute is called "future", not `future prices`

**Reply by edwardtfn** [reply]
Sorry, but that code is from a while ago, so it isn't in the top of my mind.
I can take a look at this later, but meanwhile you can find the code I'm using now:
- My Tibber sensors: https://github.com/edwardtfn/HomeAssistant-Config/blob/main/packages/electricity/tibber.yaml
- The plot: https://github.com/edwardtfn/HomeAssistant-Config/blob/main/lovelace/library/cards/card_electricity_price_chart.yaml

**Reply by Rincovanderbeek** [reply]
Hi Edward,
Thanks!  This works like a charm.
Fantastic.

**Comment by edwardtfn** [comment]
I just installed the NordPool integration, so I don't have historical data to try it, so please try and let me know the results:

```yaml
type: custom:plotly-graph
time_offset: 1.5d
refresh_interval: 300
hours_to_show: 84
layout:
  xaxis:
    rangeselector:
      'y': 1.2
      buttons:
        - count: 7
          step: day
        - count: 12
          step: day
  yaxis:
    rangemode: tozero
    tickformat: .1f
  yaxis2:
    rangemode: tozero
    tickformat: .2f
    fixrange: true
  yaxis9:
    visible: false
    fixedrange: true
round: 2
default: null
entities:
  - entity: sensor.total_energy_utility_meter
    name: Energy consumption
    type: bar
    marker:
      color: rgba(165,165,0,0.6)
    texttemplate: ' %{y:.2f} kr/kWh'
    statistic: state
    period: hour
    filters:
      - fn: |-
          (params) => {
            const ys = [];
            ys.push(0); 
            for (let i = 1; i < params.statistics.length; i++){
              ys.push(params.statistics[i].state-params.statistics[i-1].state);
            }
            return { ys };
          }
  - entity: sensor.nordpool_kwh_se3_sek_3_10_025
    name: Electricity price
    yaxis: y2
    unit_of_measurement: kr/kWh
    line:
      color: rgba(255, 165, 0, 1)
      width: 3
    filters:
      - store_var: electricity_price
      - exponential_moving_average:
          alpha: 1
    show_value: true
    texttemplate: ' %{y:.2f} kr/kWh'
  - entity: sensor.nordpool_kwh_se3_sek_3_10_025
    yaxis: y2
    name: Future price
    fill: tozeroy
    fillcolor: rgba(255, 165, 0,.1)
    line:
      color: rgba(255, 165, 0, 1)
      width: 1
      dash: dot
    filters:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [vars.electricity_price.xs.slice(-1)[0],...meta.raw_today.concat(...meta.raw_tomorrow).map(({ start }) => new Date(start))],
            ys: [vars.electricity_price.ys.slice(-1)[0],...meta.raw_today.concat(...meta.raw_tomorrow).map(({ value }) => value)],
          })
      - exponential_moving_average:
          alpha: 1
  - entity: ''
    name: Now
    yaxis: y9
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: $fn () => [Date.now(), Date.now()]
    'y': $fn () => [0,1]
```

**Comment by princetiwoz** [comment]
works perfect. Just made minor adjustments to avoid the overlap from the future prices into current prices with a straight line
![Capture](https://user-images.githubusercontent.com/120245251/215866816-171453d7-56ab-49bf-9b34-9b944e08dfbf.PNG)

**Reply by edwardtfn** [reply]
Great!

Please share the adjustments you have made, so others can use it. 😉

**Reply by princetiwoz** [reply]
type: custom:plotly-graph
time_offset: 1.1d
refresh_interval: 10
hours_to_show: 84
layout:
  xaxis:
    rangeselector:
      'y': 1.4
      buttons:
        - count: 7
          step: day
        - count: 12
          step: day
  yaxis:
    rangemode: tozero
    tickformat: .1f
  yaxis2:
    rangemode: tozero
    tickformat: .2f
    fixrange: true
  yaxis9:
    visible: false
    fixedrange: true
round: 2
default: null
entities:
  - entity: sensor.aidon_energy_monthly
    name: Energy consumption
    type: bar
    marker:
      color: rgba(165,165,0,1)
    texttemplate: ' %{y:.2f} kr/kWh'
    statistic: state
    period: hour
    filters:
      - fn: |-
          (params) => {
            const ys = [];
            ys.push(0); 
            for (let i = 1; i < params.statistics.length; i++){
              ys.push(params.statistics[i].state-params.statistics[i-1].state);
            }
            return { ys };
          }
  - entity: sensor.nordpool_kwh_krsand_nok_2_10_025
    name: Electricity price
    yaxis: y2
    unit_of_measurement: kr/kWh
    line:
      color: rgba(255, 165, 0, 1)
      width: 3
    filters:
      - store_var: electricity_price
      - exponential_moving_average:
          alpha: 1
    show_value: true
    texttemplate: ' %{y:.2f} kr/kWh'
  - entity: sensor.nordpool_kwh_krsand_nok_2_10_025
    yaxis: y2
    name: Future price
    fill: tozeroy
    fillcolor: rgba(255, 165, 0,.1)
    line:
      color: rgba(255, 165, 0, 1)
      width: 1
      dash: dot
    filters:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [vars.electricity_price.xs.slice(-24)[0],...meta.raw_today.concat(...meta.raw_tomorrow).map(({ start }) => new Date(start))],
            ys: [vars.electricity_price.ys.slice(-24)[0],...meta.raw_today.concat(...meta.raw_tomorrow).map(({ value }) => value)],
          })
      - exponential_moving_average:
          alpha: 1
  - entity: ''
    name: Now
    yaxis: y9
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: $fn () => [Date.now(), Date.now()]
    'y': $fn () => [0,1]
![Capture](https://user-images.githubusercontent.com/120245251/215867920-b99438e6-63df-4c5c-a6bd-993b97b885fe.PNG)

**Reply by edwardtfn** [reply]
Add a line with \```yaml before your code and another line with ``` after the code in order to format it as yaml. 😉

Like this (with the right Indentation):

\```yaml

type: custom:plotly-graph
time_offset: 1.1d
refresh_interval: 10
hours_to_show: 84
layout:
  xaxis:
    rangeselector:
      'y': 1.4
buttons:
\```

And then it will look like this:
```yaml
type: custom:plotly-graph
time_offset: 1.1d
refresh_interval: 10
hours_to_show: 84
layout:
  xaxis:
    rangeselector:
      'y': 1.4
    buttons:
      - count: 7
```

**Comment by princetiwoz** [comment]
```yaml
type: custom:plotly-graph
time_offset: 1.1d
refresh_interval: 10
hours_to_show: 84
layout:
  xaxis:
    rangeselector:
      'y': 1.4
      buttons:
        - count: 7
          step: day
        - count: 12
          step: day
  yaxis:
    rangemode: tozero
    tickformat: .1f
  yaxis2:
    rangemode: tozero
    tickformat: .2f
    fixrange: true
  yaxis9:
    visible: false
    fixedrange: true
round: 2
default: null
entities:
  - entity: sensor.aidon_energy_monthly
    name: Energy consumption
    type: bar
    marker:
      color: rgba(165,165,0,1)
    texttemplate: ' %{y:.2f} kr/kWh'
    statistic: state
    period: hour
    filters:
      - fn: |-
          (params) => {
            const ys = [];
            ys.push(0); 
            for (let i = 1; i < params.statistics.length; i++){
              ys.push(params.statistics[i].state-params.statistics[i-1].state);
            }
            return { ys };
          }
  - entity: sensor.nordpool_kwh_krsand_nok_2_10_025
    name: Electricity price
    yaxis: y2
    unit_of_measurement: kr/kWh
    line:
      color: rgba(255, 165, 0, 1)
      width: 3
    filters:
      - store_var: electricity_price
      - exponential_moving_average:
          alpha: 1
    show_value: true
    texttemplate: ' %{y:.2f} kr/kWh'
  - entity: sensor.nordpool_kwh_krsand_nok_2_10_025
    yaxis: y2
    name: Future price
    fill: tozeroy
    fillcolor: rgba(255, 165, 0,.1)
    line:
      color: rgba(255, 165, 0, 1)
      width: 1
      dash: dot
    filters:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [vars.electricity_price.xs.slice(-24)[0],...meta.raw_today.concat(...meta.raw_tomorrow).map(({ start }) => new Date(start))],
            ys: [vars.electricity_price.ys.slice(-24)[0],...meta.raw_today.concat(...meta.raw_tomorrow).map(({ value }) => value)],
          })
      - exponential_moving_average:
          alpha: 1
  - entity: ''
    name: Now
    yaxis: y9
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: $fn () => [Date.now(), Date.now()]
    'y': $fn () => [0,1]
```

**Reply by toldenburger** [reply]
Hey Princetiwoz, I love your graph combination. I cannot get it to work though. Can you help me figure it out?
I have the Nordpool price setup, so I changed those out in your script for my local version. But what should I change the entity 'sensor.aidon_energy_monthly' to? Is it total consumed in a month? Can I use my local energy consumption sensor? Thanks!

**Reply by princetiwoz** [reply]
Hi, you can use your energy consumption sensor. Let me know how it looks. What kind of consumption sensor do you have. Is it hourly or monthly.

**Reply by toldenburger** [reply]
Hey Princetiwoz, I use the Tibber Pulse, it gives me hourly and weekly and monthly stats. Which one should I choose?

**Reply by princetiwoz** [reply]
Hi, sorry for late reply. I also have the tibber data even and i have used it below
Use the monthly consumption data

```
type: custom:plotly-graph
time_offset: 1.1d
refresh_interval: 10
hours_to_show: 84
layout:
  xaxis:
    rangeselector:
      'y': 1.4
      buttons:
        - count: 7
          step: day
        - count: 12
          step: day
  yaxis:
    rangemode: tozero
    tickformat: .1f
  yaxis2:
    rangemode: tozero
    tickformat: .2f
    fixrange: true
  yaxis9:
    visible: false
    fixedrange: true
round: 2
default: null
entities:
  - entity: sensor.accumulated_month_consumption
    name: Energy consumption
    type: bar
    marker:
      color: rgba(165,165,0,1)
    texttemplate: ' %{y:.2f} kr/kWh'
    statistic: state
    period: hour
    filters:
      - fn: |-
          (params) => {
            const ys = [];
            ys.push(0); 
            for (let i = 1; i < params.statistics.length; i++){
              ys.push(params.statistics[i].state-params.statistics[i-1].state);
            }
            return { ys };
          }
  - entity: sensor.nordpool_kwh_krsand_nok_2_10_025
    name: Electricity price
    yaxis: y2
    unit_of_measurement: kr/kWh
    line:
      color: rgba(255, 165, 0, 1)
      width: 3
    filters:
      - store_var: electricity_price
      - exponential_moving_average:
          alpha: 1
    show_value: true
    texttemplate: ' %{y:.2f} kr/kWh'
  - entity: sensor.nordpool_kwh_krsand_nok_2_10_025
    yaxis: y2
    name: Future price
    fill: tozeroy
    fillcolor: rgba(255, 165, 0,.1)
    line:
      color: rgba(255, 165, 0, 1)
      width: 1
      dash: dot
    filters:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [vars.electricity_price.xs.slice(-24)[0],...meta.raw_today.concat(...meta.raw_tomorrow).map(({ start }) => new Date(start))],
            ys: [vars.electricity_price.ys.slice(-24)[0],...meta.raw_today.concat(...meta.raw_tomorrow).map(({ value }) => value)],
          })
      - exponential_moving_average:
          alpha: 1
  - entity: ''
    name: Now
    yaxis: y9
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: $fn () => [Date.now(), Date.now()]
    'y': $fn () => [0,1]

```

**Reply by toldenburger** [reply]
Hey, thank you for your reply.
I still receive an error:
`Error: at [entities.2.filters.0]: Error in filter: TypeError: undefined is not an object (evaluating 'meta.raw_today.concat')`
and the graph doesn't look like anything useful yet unfortunately

**Reply by princetiwoz** [reply]
@edwardtfn hi, can you help here

**Reply by edwardtfn** [reply]
Sure!

Looks like the issue is when rendering the forecast prices, which are not part of the standard Tibber integration (at least it wasn't there the last time I've used that integration).

So my suggestion is to either use the [Tibber data integratio](https://github.com/Danielhiversen/home_assistant_tibber_data)n, as used by @princetiwoz (at least this is what I understood) or use a direct API call as the one I've shared on my original post on the beginning of this discussion.

Tibber Pulse will give info about your consumption, which is past data. The error message you shared is related to the future data.

**Comment by princetiwoz** [comment]
![image](https://user-images.githubusercontent.com/120245251/215872647-fcbb904d-d53d-49c3-9bfb-d637f93b7805.png)
Real time meter consumption

**Reply by princetiwoz** [reply]
```yaml
type: custom:plotly-graph
hours_to_show: 6
refresh_interval: 1
entities:
  - entity: sensor.aidon_active_power_import
    show_value: true
    name: Pulse now
    fill: tozeroy
    line:
      color: orange
      dash: solid
      width: 1
layout:
  yaxis:
    fixedrange: true
  xaxis:
    rangeselector:
      'y': 1.2
      buttons:
        - count: 5
          step: minute
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
```
