### DISCUSSION TITLE
Parse a sensor that already gives a list of (timestamp, values)

### DISCUSSION THREAD

**Discussion by r-jean-pierre** [dbuezas/lovelace-plotly-graph-card#229] [Q&A] [answered]
Dear all,

I was wondering if someone could help me to do something with many of the entities I have.
In general, I have something like this:

![2023-02-02 20_50_57-Window](https://user-images.githubusercontent.com/9727894/216435385-73118834-0ed8-4e7e-a387-2155d82acd24.png)

This entity sensor.veolia_daily_consumption is in fact giving me a history of 3 months with the same pattern: day, value a hundred of time
With ApexCharts I started to understand the mechanism map((val, index) => {return [new Date(val[0]).getTime(), val[1]]; but how to do it with plotly-graph? I feel it has something to do with filters and fn, but i didn't find an exemple where a value in y will be cast into a date and then fill the x values

**Comment by dbuezas** [comment, marked as answer]
I think #213 is a good base for this. In this case it should be something like this: (not testee)
```yaml
 filters:
      - fn: |-
          ({ meta }) => ({
            xs: meta.HistoryConsumption.map(([date, value ]) => new Date(date)),
            ys: meta.HistoryConsumption.map(([date, value ]) => value),
          })
```

**Comment by r-jean-pierre** [comment]
Yeaaaaah it works!  Many thanks!
Here is a YAML for those who have exactly the same component from veolia water provider:

```yaml
- type: custom:plotly-graph  # test vdc
    entities:
    - entity: sensor.veolia_daily_consumption
      filters:
        - fn: |-
            ({ meta }) => ({
              xs: meta.historyConsumption.map(([date, value]) => new Date(date)),
              ys: meta.historyConsumption.map(([date, value]) => value)
            })
      show_value: true
    hours_to_show: 2244
```

And the result:

![2023-02-02 21_44_22-Window](https://user-images.githubusercontent.com/9727894/216445413-18988b25-9df1-4308-9d71-2bfdb3831e6a.png)

**Reply by dbuezas** [reply]
Perfect!
Btw, you can now (v3.2.0) write:
`hours_to_show: 10d` (10days) instead.

**Reply by r-jean-pierre** [reply]
Hi!

Here is me again!
I have some cosmetic questions for you :) if you see how to optimize them, it would be wonderful to have some help.
Based on a similar sensor to the previous one, I had to do something again like this:
```yaml
filters:
  - fn: |-
      ({ meta }) => ({
        xs: meta.dailyweek.map((date) => new Date(date)-3600*1000),
        ys: meta.dailyweek_HP.map((value) => value)
      })
```
it renders:
![image](https://user-images.githubusercontent.com/9727894/222263050-a423e516-34c3-42e2-b2d9-54d8ac753366.png)

Cosmetic1: it would be perfect to see the show_value of the last datapoint, and not the first one:
![image](https://user-images.githubusercontent.com/9727894/222263462-a6ae3b95-ae81-40ef-86e6-14deb99a3295.png)

Cosmetic2: assuming it's not possible because of the filter-fn trick, the legend is still "ugly" because it adds the scatter trace information:
![image](https://user-images.githubusercontent.com/9727894/222263838-f943514e-4dac-41e9-8066-526554282a71.png)
note that other points are okay (including last one):
![image](https://user-images.githubusercontent.com/9727894/222264073-563d9890-e677-4fda-902b-76425f7e1604.png)

and for "normal" sensors (i.e. with no need of filters-fn trick ), the last point legend is also totally perfect (but i suppose you knew it already):
![image](https://user-images.githubusercontent.com/9727894/222268134-ca9cca3f-d1c9-4d35-8acd-91c78f3d8c1f.png)


Cosmetic3: in plotly doc (https://plotly.com/python/line-charts/) it seems that we can put markers on top of line (e.g: px.line(df, x='year', y='lifeExp', color='country', **markers**=True) ), could it be possible with the card? I tried to put in the yaml some `markers: true` everywhere but no success... if possible, it would display that:
![image](https://user-images.githubusercontent.com/9727894/222265277-76829cad-aa7d-4d01-b3b3-ce8b1e550d3c.png)

Cosmetic2+cosmetic3 (but this question is probably to new): it sounds like you are able to show the last value with the `show_value: true` so "can we have the min and max value text on top of the curve?" it seems that plotly do not have this option, but they suggest to the users to construct this feature with the add_annotation feature (https://plotly.com/python/text-and-annotations/)
and then, a possible result could be equivalent to:
![image](https://user-images.githubusercontent.com/9727894/222267337-1098afd2-2c1a-4563-b028-a832c235f1e1.png)
