### DISCUSSION TITLE
Zoom limits

### DISCUSSION THREAD

**Discussion by dbuezas** [dbuezas/lovelace-plotly-graph-card#233] [Show and tell]
Proposed by @Rvh91 and originally tracked in #60, it is now possible to implement in yaml by the user (through $fn).

![Kapture 2023-02-01 at 22 13 59](https://user-images.githubusercontent.com/777196/216165224-39f8aaf6-e105-437f-9c95-24479bc18bc3.gif)

In this example, the y axis is dynamically limited to the visible range of the entities, and further constrained to be between 12 to 18
```yaml
type: custom:plotly-graph
hours_to_show: current_week
entities:
  - entity: sensor.senseair_temperature
  - entity: sensor.durchgang_thermometer_temperature
    
layout:
  uirevision: $fn () => Math.random() // force rescale on scroll
  yaxis:
    range: |
        $fn ({ getFromConfig }) => {
          const all = getFromConfig("entities").flatMap(({ y }) => y);
          return [
            Math.max(12, Math.min(...all)), // cap to lowest value, but at least 12
            Math.min(18, Math.max(...all)), // cap to highest value, but at most 18
          ]
        }
```

**Comment by CendaL** [comment]
Here is how you automatically re-scale just visible area - min is set to 0, max to max value in the visible area:

```yaml
    uirevision: $fn ({ getFromConfig }) => getFromConfig('visible_range')[0] // force rescale on scroll only - not when visible entities change or new data point is added
    range: |
      $fn ({ getFromConfig }) => {
        const date_from = new Date(getFromConfig('visible_range')[0]);
        const date_to = new Date(getFromConfig('visible_range')[1]);
        const all = getFromConfig("entities").flatMap(({ x, y }) => x.map((xi, i) => [xi, y[i]]).filter(([d, v]) => d >= date_from && d <= date_to).map(([d, v]) => v));
        return [0, Math.max(...all)]
      }
```
![Animation](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/840665/626f5de3-8715-4ea1-8dbc-a182c15f827a)

**Reply by CendaL** [reply]
Actually this does not work well enough - when you scroll, it resets visible lines which is not what I want. I have found much simpler solution by using `autorange_after_scroll` and `rangemode`.
``` yaml
type: custom:plotly-graph
entities:
  - entity: sensor.total_power
    show_value: true
    name: Total
  - entity: sensor.main_power_channel_a_power
    name: |
      $ex "Phase A " + hass.states['sensor.main_power_channel_a_power'].state
  - entity: sensor.main_power_channel_b_power
    name: |
      $ex "Phase B " + hass.states['sensor.main_power_channel_b_power'].state
  - entity: sensor.main_power_channel_c_power
    name: |
      $ex "Phase C " + hass.states['sensor.main_power_channel_c_power'].state
autorange_after_scroll: true
layout:
  yaxis:
    rangemode: tozero
```
