### DISCUSSION TITLE
Any way to move the value indicator within the hover-over value window?

### DISCUSSION THREAD

**Discussion by onionmad** [dbuezas/lovelace-plotly-graph-card#237] [Q&A] [answered]
The mouse cursor/pointer is sometimes blocking the textual representation of the current value, within the hover/tooltip(?) popup window. Is there any way to move the alignment of the hover-view Y-value representation, to make it center aligned within the box, instead of being left-aligned (or right, where the cursor/pointer also obscures the value in those cases). 

![image](https://user-images.githubusercontent.com/62025572/216808409-82180ce7-67d7-4357-9b2d-ec0ba6198b1d.png)

**Comment by dbuezas** [comment, marked as answer]
Yes! :) 
Plotlyjs offers multiple options to configure the hover tooltip:
* `layout: hoverlabel: align: ...` https://plotly.com/javascript/reference/#layout-hoverlabel-align
* `layout: hovermode: ...`: https://plotly.com/javascript/reference/#layout-hovermode

**Reply by onionmad** [reply]
__Amazing! 
Any chance you could provide a simple dashboard card .yaml where a specific alignment is set? Clearly, I am way off with this attempt: 


```
type: custom:plotly-graph
entities:
  - entity: sensor.outlet_kitchen_table_power
    show_value: true
  - entity: sensor.outlet_kitchen_table_power
    name: (Filtered)
    show_value: false
    filters:
      - resample: 10s
      - exponential_moving_average:
          alpha: 0.1
hours_to_show: 0.5
refresh_interval: auto
layout.hoverlabel.align = "right"
autorange_after_scroll: true
```

**Reply by dbuezas** [reply]
You were close. In yaml you can write it like this:
```yaml
layout:
  hoverlabel:
    align: right
```

I think this should have you the key to try all the other things you can see in the plotly docs :)
