### DISCUSSION TITLE
Adjust the subplot row height in a multiple rows grap

### DISCUSSION THREAD

**Discussion by gllmlbrt** [dbuezas/lovelace-plotly-graph-card#24] [Q&A] [answered]
Hi, I would to plot the state of my climate entity, Heat/off/cooling etc. 
I have done that, but I would like the row height of this subplot to make this one much thinner. (kind o like the history graph for states in the normal Hass graphs.
In the documentation there is a row_heights: XX argument, but I am not sure where to use it as part of a subplot variable.
Additionally I would like to customise the order in which the y axis displays the state ?
 Anyone know how this can be done.

![image](https://user-images.githubusercontent.com/58825251/152130279-943e9c26-91da-4019-b2d5-54f7999a46ec.png)

Or perhaps you have a recommendation that is altogether different for plotting the states ?

**Comment by Photelegy** [comment]
Would love to know this too!

**Comment by dbuezas** [comment]
## Force order of y axis categorical values
```yaml
layout:
  yaxis2:
    categoryorder: array
    categoryarray:
      - 'off'
      - 'on'
      - 'Heat'
      - 'Cooling'
```

**Comment by dbuezas** [comment, marked as answer]
## Subplot row height
This you can't do if you use a grid, you need to manually specify the domain of each y axis
```yaml
no_default_layout: true
layout:
  showlegend: false
  hovermode: x
  dragmode: pan
  margin:
    t: 30
    l: 45
    r: 30
    b: 50
  height: 650
  yaxis:
    domain: [0, .1]
    title:
      text: Short
  yaxis2:
    domain: [.1, .4]
    title:
      text: Mid
  yaxis3:
    domain: [.4, 1]
    title:
      text: Tall
```
<img width="501" alt="image" src="https://user-images.githubusercontent.com/777196/168420635-e8e1cf74-ca00-4fff-9b36-4c68bcab5901.png">

BTW, next time please paste your yaml too, it's easier for me to know what's going on and it serves as an example for anybody who likes the screenshot :)
