### DISCUSSION TITLE
Range / scale limits

### DISCUSSION THREAD

**Discussion by alexruffell** [dbuezas/lovelace-plotly-graph-card#241] [Q&A] [answered]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/4006944/216848522-99b4d16d-c1e0-4014-b0a5-7ee5623af0e2.png">

I am trying to refine the Plotly cards for Temperature and Humidity but can't figure out a couple things:

1) I don't want my temperature scale to adjust too closely to the measured values being displayed because it makes the various measurements look wildly different (far apart) even though they are not. I'd like to default the minimum scale to span about 10-20C (just a guess for now) and be centered on the temperatures being displayed. The scale could increase if the temperature range being displayed were to require it but not decrease below my configured minimum.
2) As I have it configured right now, if I use the mouse wheel to see more days, I end up with a temperature scale that makes no sense... I guess it is zooming in and out instead of compressing the y axis and adjusting the x axis as needed for the data to fit in the scale.

Example:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/4006944/216848933-5106c585-daac-48ce-8f31-4b01679f01cc.png">

3) For the Humidity graph I settled showing 0 to 100% but that results in the lower 0 to 20-30% never being used. If I change the range to go from 30 to 100, then it cuts off when it actually goes under (will it? Not sure). If I don't set a range at all, then I have the same issues as 1 and 2.

4) For both, is there a way for the last data point to always stick to the right? Sometimes, when interacting with the graphs, I end up with the last data point in the middle... and it is undesirable. Would be nice if I could pin it, so to speak, to the right edge.

Example:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/4006944/216849138-a3fee598-c547-4e19-b02f-55314d67c4c2.png">

My existing YAML:

Temperature
```
  - type: custom:plotly-graph
    title: Temperature
    entities:
      - entity: sensor.front_porch_motion_sensor_temperature
        name: Porch
        yaxis: y1
        connectgaps: true
        show_value: false
        line:
          shape: spline
      - entity: sensor.patio_motion_sensor_temperature
        name: Patio
        yaxis: y1
        connectgaps: true
        show_value: false
        line:
          shape: spline
      - entity: sensor.outdoor_sensor_temperature
        name: Outdoors
        yaxis: y1
        connectgaps: true
        show_value: false
        line:
          shape: spline
      - entity: sensor.front_porch_multi_sensor_temperature
        name: Porch Multi
        yaxis: y1
        connectgaps: true
        show_value: false
        line:
          shape: spline
    hours_to_show: 24
    refresh_interval: 10
    config:
      displayModeBar: false
    layout:
      staticPlot: true
      scrollZoom: false
      showlegend: true
      yaxis:
        range:
          - -5
          - 40
    defaults:
      fixedrange: true
```

Humidity
```
  - type: custom:plotly-graph
    title: Humidity
    entities:
      - entity: sensor.outdoor_sensor_humidity
        name: Outdoors
        yaxis: y1
        connectgaps: true
        show_value: false
        line:
          shape: spline
      - entity: sensor.front_porch_multi_sensor_humidity
        name: Porch Multi
        yaxis: y1
        connectgaps: true
        show_value: false
        line:
          shape: spline
      - entity: sensor.indoor_humidity
        name: Indoor
        yaxis: y1
        connectgaps: true
        show_value: false
    hours_to_show: 24
    refresh_interval: 10
    config:
      displayModeBar: false
    layout:
      title:
        font:
          color: red
      staticPlot: true
      showlegend: true
      yaxis:
        range:
          - 0
          - 100
      scrollZoom: false
    defaults:
      yaxes:
        fixedrange: true
    }

```
