### DISCUSSION TITLE
Help needed with 'statistics'

### DISCUSSION THREAD

**Discussion by Rvh91** [dbuezas/lovelace-plotly-graph-card#244] [Q&A] [answered]
Hi all, I've just started to dive into further custimization of plotly. From the repo readme I've found this picture:

![image](https://user-images.githubusercontent.com/99890657/217213626-762f4762-1ca9-46aa-9ea4-225885694ca5.png)

I would like to include the (what I assume to be confidence intervals / standard deviation), of the trace. However, I cannot find in the documentation how to configure this in the yaml config. I would have expected this to be configurable under statistics. Could anyone point me in the right direction?

**Comment by dbuezas** [comment, marked as answer]
The Home Assistant API doesn't expose standard deviation, only `min`, `mean` and `max` for state_class=measurement and `state` and `sum` for state_class=total.

See [here](https://github.com/dbuezas/lovelace-plotly-graph-card#statistics-support)

Computing statistics locally (including mean, std deviation, and intervals of confidence) sound like a good use case for filters. Feel free to raise a feature request issue, make sure to include your suggestion for how you imagine the yaml to look like :)

**Comment by Rvh91** [comment]
But the linked image is one that is already created using the plotly custom card right? So apparently what I am looking for already exists (or is that indeed the min/max values that you mentioned)? :) In which case I still cant find how to enable all of those for the same entity like was shown in the figure.
I've just tried creating a graph with 3 identical entities, but with different statistic (mean, max, min) specified for each, but it doesnt really give me the same behavior as shown in the example.

**Reply by dbuezas** [reply]
Oh, I see. Those are min max values. Yaml here:
https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/81#discussioncomment-3984546

**Reply by Rvh91** [reply]
clear thanks! great to see. Perhaps it would be nice to add this as an option for 'statistics', other than having min,max or mean, include an option for 'all', which essentially does what was shown in the example by r-jean-pierre.

**Reply by dbuezas** [reply]
Sounds like a good idea, make sure to add a feature request issue describing how you imagine the API to be :)

**Reply by Rvh91** [reply]
[Done here!](https://github.com/dbuezas/lovelace-plotly-graph-card/issues/247)
Thanks for you consideration! Not sure if this includes what you mean with API. If anything is unclear, please let me know!

**Reply by dbuezas** [reply]
Yes it's clear. I now understand exactly what you meant. Thanks for writing it down!
I left some discussion points there too :)

**Comment by lennon101** [comment]
I'd love to see an updated and complete example of how to render this. Strugglin to get the plot working:

```yaml
type: vertical-stack
cards:
  - type: custom:plotly-graph  # Kid's room
    entities:
    - entity: sensor.bedroom_temperature
      name: T[°C] (max)
      line:
        color: rgba(81, 117, 159, 0.4)
        width: 1
      statistic: max
      period: hour
      showlegend: false
      show_value: false
    - entity: sensor.bedroom_temperature
      name: T[°C] (min)
      fill: tonexty
      fillcolor : rgba(81, 117, 159, 0.2)
      line:
        color: rgba(81, 117, 159, 0.4)
        width: 1
      statistic: min
      period: hour
      showlegend: false
      show_value: false
    - entity: sensor.bedroom_temperature
      texttemplate: "%{y:.1f}°C"
      name: T[°C] (mean)
      line:
        color: rgba(81, 117, 159, 1.0)
      statistic: mean
      period: hour
      show_value: true

    hours_to_show: 72
    refresh_interval: 30
    title: Bedroom

```

Not working :( 

![2025-03-06_09 58 26_ShareX Overview_–_Home_Assistant_-_Google_Chrome](https://github.com/user-attachments/assets/17d025fd-db65-4d9d-ab81-2e19917293db)
