### DISCUSSION TITLE
Vars x-axis alignment with null values

### DISCUSSION THREAD

**Discussion by wrowlands3** [dbuezas/lovelace-plotly-graph-card#252] [Q&A] [answered]
``I want two plots to be aligned when using vars, and a nice smooth line using window averages. But the raw data comes from an unreliable entity (ble, returns 'unavailable' often). When I use an averaging filter after resample it removes these null values and changes its alignment on the xaxis, with the effect more pronounced historically:

The heating fill in both of the below is correct, but the temperature line has moved significantly
![no averages](https://user-images.githubusercontent.com/86292646/221165652-1079fb1e-dddf-4470-942d-c6c993960a2c.JPG)
![without averaging before resample](https://user-images.githubusercontent.com/86292646/221165658-3ba7a12c-c1ea-4778-ba21-7bf6b0543175.JPG)

An average filter with a window size of 1 before the resample fixes this, and I can apply another averaging filter with a higher number after for a smoother line. This makes historical data align well despite the accumulation of null values:
![Current solution](https://user-images.githubusercontent.com/86292646/221172163-1d31b544-dcfa-4de2-9520-4a3be69041b9.JPG)

However, this solution seems to mess up the alignment a lot more for the current day of the latest data, unless I zoom/pan further out and back in.

Without first averaging (accurate):
![normal vars](https://user-images.githubusercontent.com/86292646/221166765-ee5d9222-0001-42b6-8044-3f626fa5cb8f.JPG)

With first averaging filter (accurate historically, but alignment jumps around with slight dragging of the latest data), again the vars.heating is the fill and it remains in place but the vars temperature moves:
![Current solution misaligns start](https://user-images.githubusercontent.com/86292646/221166927-3b283e33-990b-453a-bae1-44ea6142657f.JPG)

I think the heating vars has the most reliable x-axis, as I have a map_y filter to address the null values; I also use the heating vars as the map_x xs[i] because the data does not extend that far back,  and it keeps the heating vars ys[i] plotted to the correct time when I view before the entity was created and I want to view the temperature earlier than that.

```type: custom:plotly-graph
entities:
  - entity: sensor.heat_trv_position
    internal: true
    line:
      width: 0
    fill: none
    filters:
      - resample: 5m
      - map_y: 'y === null ? 0 : ys[i]'             # seems to make the vars.heating.xs more reliable 
      - sliding_window_moving_average:
          window_size: 2
          extended: true
      - store_var: heating
  - entity: sensor.ble_temperature_hygro_5
    internal: true
    filters:
      - sliding_window_moving_average:       # improves overall accuracy, particularly historical, but gives the issue in the nearer term
          window_size: 1
      - resample: 5m
      - sliding_window_moving_average:
          window_size: 10
          extended: true
      - store_var: temperature
  - entity: sensor.ble_temperature_hygro_5
    line:
      width: 5
      shape: spline
    fill: none
    filters:
      - resample: 5m
      - map_y: vars.temperature.ys[i]
      - map_x: vars.heating.xs[i]      # this seems to have no effect on this query, I use it when viewing the temperature previous to the creation of the heating entity
      - sliding_window_moving_average:
          window_size: 10
          extended: true
  - entity: sensor.ble_temperature_hygro_5
    filters:
      - resample: 5m
      - map_y: 'vars.heating.ys[i] > "71" ? vars.temperature.ys[i] : 0'
      - map_x: vars.heating.xs[i]  # if I map this to vars.temperature.xs, then view before the heating entity was created then vars.heating.ys maps onto the current view and becomes completely unaligned
  - entity: sensor.ble_temperature_hygro_5
    filters:
      - resample: 5m
      - map_y: 'vars.heating.ys[i] > "51" ? vars.temperature.ys[i] : 0'
      - map_x: vars.heating.xs[i]
  - entity: sensor.ble_temperature_hygro_5
    filters:
      - resample: 5m
      - map_y: 'vars.heating.ys[i] > "21" ? vars.temperature.ys[i] : 0'
      - map_x: vars.heating.xs[i]
layout:
  yaxis:
    title:
      text: Temperature °C
      font:
        color: rgba(0, 153, 125,1)
    side: right
    range:
      - 14
      - 24
  paper_bgcolor: rgba(255,255,255,1)
  plot_bgcolor: rgba(0,0,0,0)
defaults:
  entity:
    unit_of_measurement: ' '
    line:
      width: 0
      color: rgba(0, 153, 125,1)
      shape: linear
    fill: tozeroy
    fillcolor: rgba(0, 153, 125,0.25)
hours_to_show: 18
plotly_raw_config: true
```
I'm close to making this stable, it only seems to be the current view can get misaligned, while zooming out and back in (without clicking reset view) to whatever timeframe I want it is perfect!

**Comment by dbuezas** [comment, marked as answer]
Yes moving window averaging adds a "delay" to the data of half the window size. You can compensate for that by adding `centered: true`  to the filter options (next to `extended`)

As you noted, null values affect the moving window. That is because (as you already realized), the first thing that filter does is removing the "unavailable" values, and the window is not time based but element based instead.
Your trick of using resample is the way to fix that, just add  the `centered: true` option and you should be fine :)

**Reply by wrowlands3** [reply]
I hadn't tried that before because I thought it defaulted to `centered: true` anyway. I've tried it in all combinations, even adding it to every entity but it doesn't seem to have made a difference.
Code:
```
  - entity: sensor.heat_trv_position
    internal: true
    line:
      width: 0
    fill: none
    filters:
      - resample: 5m
      - map_y: 'y === null ? 0 : ys[i]'             
      - store_var: heating
  - entity: sensor.ble_temperature_hygro_5
    internal: true
    filters:
      - sliding_window_moving_average:       # Needed to bridge nulls but causes the jumping
          window_size: 1
          centered: true                                  #hasn't helped unfortunately
      - resample: 5m
      - store_var: temperature
 ```

The peak temperature occurs at 8pm, but as I scroll along it displays at 6:30pm
![6pm alignments](https://user-images.githubusercontent.com/86292646/221439817-52a79d79-b537-41b2-b295-5a85dea212a6.JPG)
to 8pm
![8pm alignments](https://user-images.githubusercontent.com/86292646/221439850-eb72cc08-7b7a-430b-9dd3-775d2feb2f05.JPG)
jumping back to 4pm
![4pm alignments](https://user-images.githubusercontent.com/86292646/221439866-ac1482a1-5156-481a-9050-752699596246.JPG)
before finally settling back at the correct 8pm peak
![8pm alignment again](https://user-images.githubusercontent.com/86292646/221439889-3d9ce70f-4103-456c-ac52-6bdb1f49f418.JPG)

I think it may have something to do with the long period of flat temperature before before the rise, the entity only reporting the start and end data points over those many hours making the average have a large lag, even with `centered: true` 
I can live with it if there's no fix but just asking for help if there is another way to make it work! :) thanks for all your great help so far

**Reply by dbuezas** [reply]
Oh you're right, centered is the default.
I think you are right with the long period of inactivity. The solution for that is adding a `resample` filter before the averaging.
You can read more about the reasons and decision here: https://github.com/dbuezas/lovelace-plotly-graph-card/issues/248

In a nutshell, having a `time window` instead of a `data points window` gets messy, and it is equivalent to resampling anyway.

**Reply by dbuezas** [reply]
Also, make a test with  `extended: false` to see what happens when only the parts with the complete window are plotted. The extremes don't have enough data to fill the window so they are only an approximation

**Reply by wrowlands3** [reply]
This is with `extended: false` as with `extended: true` the plot just vanishes. When I add the moving average after resample, it removes any null values which is also an issue. On other plots I used this order:
```
    filters:
      - resample: 5m
      - map_y: 'y === null ? 0 : ys[i]'          
      - sliding_window_moving_average:
```
And that does great, but for my current issue mapping y like that for the temperature is wrong and looks awful. Is there a map_y I could do that would use the last non null value instead?

**Reply by dbuezas** [reply]
Try with:
```yaml
- force_numeric
- resample
- sliding_window_moving_average
```

Alternatively you could use
```yaml
- filter: y !== null
- resample
- sliding_window_moving_average

**Reply by dbuezas** [reply]
Although the averaging filter should do that already 🤔 
What exactly are you going for? Can you make a scribble of what you expect the result to look like?

**Reply by wrowlands3** [reply]
Thanks for the suggestions, I managed to make it work with this:
```
    filters:
      - resample: 5m
      - map_y: 'y === null ? ys[ys.length-1] : ys[i]'  # assigns values to the null points based on the previous data point
      - sliding_window_moving_average:
          window_size: 10           #not needed prior to resample anymore to bridge null points, only for smoothing after
```
This essentially completes what I've been trying to achieve, thanks for all your pointers, I'll detail what I've got now in my original [show and tell](https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/203)
