### DISCUSSION TITLE
Pls help! - Trying to get multiple Y axis

### DISCUSSION THREAD

**Discussion by jazzmonger** [dbuezas/lovelace-plotly-graph-card#254] [General]
What am I doing wrong?? I can't get the graphs to separate - they all end up in the top graph...

![CAA97398-8534-4C68-BFB2-5BDE26B7094B](https://user-images.githubusercontent.com/52110065/221416215-be5bb578-c50c-402a-b406-35f3bd0d9f43.jpeg)

```
type: custom:plotly-graph
hours_to_show: 0.1
defaults:
  entity:
    show_value: true
entities:
  - entity: sensor.kauf_plug_power_2
    name: Battery heaters power
    internal: false
    yaxis: y1
    line:
      color: green
  - entity: sensor.solar_shed_temperature
    name: Shed Temp Sensor
    internal: false
    yaxis: y2
    line:
      color: blue
    smoothing: 1
  - entity: sensor.solar_batt_heat_controller_heater_level_pwm_voltage
    name: PWM Voltage
    internal: false
    yaxis: y3
    line:
      color: red
    smoothing: 1
  - entity: climate.solar_batt_heat_controller_thermostat
    attribute: current_temperature
    name: Probe
    yaxis: y1
    line:
      color: yellow
      width: 2
      smoothing: 1
  - entity: sensor.battery_temperature
    name: BMS Temp
    yaxis: y1
    line:
      color: yellow
      width: 2
      smoothing: 1
  - entity: climate.solar_batt_heat_controller_thermostat
    attribute: temperature
    name: Battery Set Temp
    yaxis: y1
    line:
      color: aqua
      shape: spline
      width: 3
      smoothing: 1
refresh_interval: auto
autorange_after_scroll: true
default_trace:
  line:
    width: 1.5
layout:
  height: 500
  yaxis:
    title: Probe & Set Temps
    zeroline: false
    range:
      - 60
      - 70
    fixedrange: true
  yaxis2:
    gridcolor: whitesmoke
    fixedrange: true
    zeroline: false
    title: Shed Temp Sensor
  yaxis3:
    gridcolor: whitesmoke
    zeroline: false
    fixedrange: true
  grid:
    ygap: 0.07
    rows: 3
    columns: 1
    pattern: coupled
    roworder: top to bottom
  xaxis:
    rangeselector:
      bgcolor: '#474747'
      'y': 1.3
      buttons:
        - count: 5
          step: minute
        - count: 10
          step: minute
        - count: 20
          step: minute
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 5
          step: day
```

**Comment by jazzmonger** [comment]
@dbuezas any advice here?

**Reply by dbuezas** [reply]
Try this: https://github.com/dbuezas/lovelace-plotly-graph-card#no_default_layout

Also, default_trace doesn't exist anymore, I should add it to the deprecations list. It was replaced by `defaults: entity:`

**Reply by jazzmonger** [reply]
@dbuezas It got worse...
EDIT.... I had to change row numbers. Working now.  Thx!
![E8A51966-A5A9-415C-A4A3-41CA00CA2ED8](https://user-images.githubusercontent.com/52110065/222387391-f4e25d8f-8b9b-4d65-818a-881b724ff0e3.jpeg)

**Comment by Saentist** [comment]
@dbuezas 
I have similar problem after update to 3+
First i see error on top about `raw_plotly_config` was needed in place of `no_default_layout`
and all entities was mixed
when set `raw_plotly_config: true` I see both axis but no graph and legend

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.qpigs_bus_voltage_2
    name: BUS V
    yaxis: y1
  - entity: sensor.qpigs_pv_input_voltage_2
    name: PV V
    yaxis: y1
  - entity: sensor.qpigs_inverter_heat_sink_temperature_2
    name: Inv temp
    yaxis: y2
  - entity: sensor.qpigs_ac_output_voltage_2
    yaxis: y1
  - entity: sensor.qpigs_ac_input_voltage_2
    yaxis: y1
  - entity: sensor.aub_2_watt
    yaxis: y1
  - entity: sensor.aubess_20a_2_power
    yaxis: y2
  - entity: sensor.atorch_at4pw_phase_a_power
    yaxis: y2
  - entity: sensor.power_production_now
    name: FS Sun 1h
    yaxis: y2
  - entity: sensor.qpigs_ac_output_active_power_2
    name: Watts out
    yaxis: y1
    line:
      color: red
ha_theme: true
raw_plotly_config: true
hours_to_show: 24
refresh_interval: 6
layout:
  xaxis:
    rangeselector:
      'y': 1.2
      buttons:
        - count: 30
          step: minute
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 3
          step: day
        - count: 7
          step: day
  dragmode: pan
  margin:
    t: 30
    l: 45
    r: 30
    b: 50
  showlegend: true
  height: 850
  legend:
    x: 1
    'y': 0
    bgcolor: rgba(0,0,0,.7)
    orientation: v
    itemsizing: constant
    font:
      size: 10
  grid:
    rows: 2
    columns: 1
    roworder: top to bottom
  yaxes:
    fixedrange: true
  yaxis:
    title:
      text: V / A / W
  yaxis2:
    title:
      text: Temp
color_scheme:
  - '#1f77b4'
  - '#1f77b4'
  - '#aec7e8'
  - '#aec7e8'
  - '#ff7f0e'
  - '#ff7f0e'
  - '#ffbb78'
  - '#ffbb78'
  - '#2ca02c'
  - '#2ca02c'
  - '#98df8a'
  - '#98df8a'
  - '#d62728'
  - '#d62728'
  - '#ff9896'
  - '#ff9896'
  - '#9467bd'
  - '#9467bd'
```

Any ideas what is wrong?

**Reply by dbuezas** [reply]
Yes, see here https://github.com/dbuezas/lovelace-plotly-graph-card#no_default_layout

**Reply by Saentist** [reply]
This helped but now legend is on top of graph
before was on side
![image](https://user-images.githubusercontent.com/16975883/225976151-45870dd7-22a7-44f5-9863-cbc4be7ad9f6.png)
and hide values on bottom chart

**Reply by dbuezas** [reply]
You don't need `raw_plotly_config: true`, remove it

**Reply by Saentist** [reply]
I set it to `false`

``` yaml
type: custom:plotly-graph
defaults:
  entity:
    show_value: true
  yaxes:
    side: left
    overlaying: 'y'
    visible: true
    showgrid: true
entities:
  - entity: sensor.qpigs_bus_voltage_2
    name: BUS V
    yaxis: y1
  - entity: sensor.qpigs_pv_input_voltage_2
    name: PV V
    yaxis: y1
  - entity: sensor.qpigs_inverter_heat_sink_temperature_2
    name: Inv temp
    yaxis: y2
  - entity: sensor.qpigs_ac_output_voltage_2
    yaxis: y1
  - entity: sensor.qpigs_ac_input_voltage_2
    yaxis: y1
  - entity: sensor.aub_2_watt
    yaxis: y1
  - entity: sensor.aubess_20a_2_power
    yaxis: y2
  - entity: sensor.atorch_at4pw_phase_a_power
    yaxis: y2
  - entity: sensor.power_production_now
    name: FS Sun 1h
    yaxis: y2
  - entity: sensor.qpigs_ac_output_active_power_2
    name: Watts out
    yaxis: y1
    line:
      color: red
ha_theme: true
autorange_after_scroll: true
raw_plotly_config: false
hours_to_show: 24
refresh_interval: 6
layout:
  xaxis:
    rangeselector:
      'y': 1.2
      buttons:
        - count: 30
          step: minute
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 3
          step: day
        - count: 7
          step: day
  dragmode: pan
  margin:
    t: 30
    l: 45
    r: 30
    b: 50
  showlegend: true
  height: 850
  legend:
    x: 0
    'y': 0
    bgcolor: rgba(0,0,0,.7)
    orientation: v
    itemsizing: constant
    font:
      size: 10
  grid:
    rows: 2
    columns: 1
    roworder: top to bottom
  yaxes:
    fixedrange: true
  yaxis:
    title:
      text: V / A / W
  yaxis2:
    title:
      text: Temp
color_scheme:
  - '#1f77b4'
  - '#1f77b4'
  - '#aec7e8'
  - '#aec7e8'
  - '#ff7f0e'
  - '#ff7f0e'
  - '#ffbb78'
  - '#ffbb78'
  - '#2ca02c'
  - '#2ca02c'
  - '#98df8a'
  - '#98df8a'
  - '#d62728'
  - '#d62728'
  - '#ff9896'
  - '#ff9896'
  - '#9467bd'
  - '#9467bd'
```
![image](https://user-images.githubusercontent.com/16975883/226040468-62acfe0e-99e7-4d4e-b93a-1dd7d5645a24.png)

but how to set legend not to overlay graph? (I put it on left, for visualization of data values on right)
Is it possible to see values on legend?
