### DISCUSSION TITLE
Step counter Graph

### DISCUSSION THREAD

**Discussion by fifthh** [dbuezas/lovelace-plotly-graph-card#255] [Q&A]
Great card, i use it mainly for temperature sensors and such, however i added the Garmin integration together with a couple of sensors that i’m trying to make graphs for.
For example, how would i make a graph for the steps counter? What i’m looking to get out is total steps each day in a nice bar graph.

This is what i got so far but it´s acting kind of funny with panning and zooming.

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.total_steps
    statistic: state
    period: auto
    type: bar
    texttemplate: '%{y}'
hours_to_show: 168
defaults:
  entity:
    line:
      width: 2
  yaxes:
    fixedrange: true
refresh_interval: 60
fn: |
  $fn({getFromConfig, vars})=> {
    const range = getFromConfig("visible_range");
    const width = range[1] - range[0];
    vars.scroll = (label, p) => ({
      args: [
        {
          layout: {
            "xaxis.range": [range[0] + width*p, range[1] + width*p],
          }
        }, {
          transition: {
            duration: 150,
          }
        }
      ],
      label,
      method: "animate",
    })
    vars.zoom = (label, h) => ({
      args: [
        {
          layout: {
            "xaxis.range": [Date.now()-1000*60*60*h, Date.now()],
          }
        }
      ],
      label,
      method: "animate",
    })
  }
layout:
  updatemenus:
    - buttons:
        - $fn({vars}) => vars.scroll( '<', -.5)
        - $fn({vars}) => vars.scroll( '>', .5)
      direction: right
      active: -1
      pad:
        r: 10
        t: 10
      type: buttons
      x: 1
      xanchor: right
      'y': 1.3
      yanchor: top
    - buttons:
        - $fn({vars}) => vars.zoom( '1d', 24)
        - $fn({vars}) => vars.zoom( '1w', 24*7)
        - $fn({vars}) => vars.zoom( '1m', 24*30)
      direction: right
      active: -1
      pad:
        r: 10
        t: 10
      type: buttons
      x: 0
      xanchor: left
      'y': 1.3
      yanchor: top
```

I would like to use
```
period: day
```
but it gives me inaccurate values and doesn't play nice with panning/zooming either.

**Comment by dbuezas** [comment]
Hi 👋 

> What i’m looking to get out is total steps each day in a nice bar graph.

Look into filters, the delta with reset should do the trick. For the bar chart, I suggest you browse the discussions section for tips and tricks on bar charts, they are a bit particular.

> it´s acting kind of funny with panning and zooming.

can you make a video?

**Reply by fifthh** [reply]
Hi,
I have no ide how to make a video so i took some screenshot, hope it helps to describe my issue.

This is what i see default without doing anything, this is 168 hours displayed (1 week).
![image](https://user-images.githubusercontent.com/57446983/222513264-f91c7820-3f13-481a-bc86-b5a655b533d2.png)

Months button pressed, looks weird.
![image](https://user-images.githubusercontent.com/57446983/222513414-0c321e1c-fe7e-4cd6-8eaf-cbe0d731121d.png)

Week button pressed, this is what i would expect it to look like in the first image.
![image](https://user-images.githubusercontent.com/57446983/222513489-83eefacd-2e97-4cfa-8f20-c1d08621a693.png)

**Reply by dbuezas** [reply]
### 1st plot

Oh right, this is a quirk of the home assistant statistics api. The card asks it for the time range on screen, and the range has `start time` and `end time`. When the `start time` falls somewhere in the middle of the statistic period, the first datapoint has the wrong value and timestamp (e.g at mid day when the period is day). 
You can see that phenomenon in the first chart, there is a tiny bar at the far left in a place it doesn't belong.
Because of that, plotly sees two bars close to each other and decides to make all of them skinny to accommodate for it.

You can remove that datapoint using 
```yaml
filters:
  - filter: i>0
```

but it will come back if you scroll. You may be able to get rid of it by using `resample: 1d`

### 2nd. Mont looks weird

I think this is because you are using `period: auto` and it switched to 1 datapoint per week. What version of the card are you using?
In any case, I suggest you use `period: day` if that behaviour is not what you need.

### 3rd. weeks look good

I think this will be better if you apply the suggestion from the first section.

**Reply by fifthh** [reply]
Thanks for a quick reply, your suggestions seems to be working, however i'm missing current day, is there a fix for this also?
![image](https://user-images.githubusercontent.com/57446983/222531439-3704a429-62ae-417b-8d29-7504ffc46a8e.png)

**Reply by dbuezas** [reply]
Yes, that's because Home Assistant doesn't have a statistic for the day until it ends. The workaround is to attach the current sensor value at the end.
See [here](https://community.home-assistant.io/t/plotly-interactive-graph-card/347746/296)

**Reply by fifthh** [reply]
Thanks for your help 👍

**Reply by dbuezas** [reply]
Wish you luck! let me know if it works for you :)

**Reply by fifthh** [reply]
Works great apart from a glitch, i don't know what's causing it.
2 different days with identical numbers, the second day should have nothing since i didn't use the watch, any ides? Entity logs show nothing for the second day also..
![image](https://user-images.githubusercontent.com/57446983/223211328-0f21f7bf-82cb-46d5-b4ea-f4c3bf57c8b5.png)

```
card:
  type: custom:plotly-graph
  entities:
    - entity: sensor.total_steps
      statistic: state
      period: day
      type: bar
      texttemplate: '%{y}'
      filters:
        - filter: i>0
        - resample: 1d
  hours_to_show: 168
  defaults:
    entity:
      line:
        width: 2
    yaxes:
      fixedrange: true
  refresh_interval: 60
  fn: |
    $fn({getFromConfig, vars})=> {
      const range = getFromConfig("visible_range");
      const width = range[1] - range[0];
      vars.scroll = (label, p) => ({
        args: [
          {
            layout: {
              "xaxis.range": [range[0] + width*p, range[1] + width*p],
            }
          }, {
            transition: {
              duration: 150,
            }
          }
        ],
        label,
        method: "animate",
      })
      vars.zoom = (label, h) => ({
        args: [
          {
            layout: {
              "xaxis.range": [Date.now()-1000*60*60*h, Date.now()],
            }
          }
        ],
        label,
        method: "animate",
      })
    }
  layout:
    updatemenus:
      - buttons:
          - $fn({vars}) => vars.scroll( '<', -.5)
          - $fn({vars}) => vars.scroll( '>', .5)
        direction: right
        active: -1
        pad:
          r: 10
          t: 10
        type: buttons
        x: 1
        xanchor: right
        'y': 1.3
        yanchor: top
      - buttons:
          - $fn({vars}) => vars.zoom( '1d', 24)
          - $fn({vars}) => vars.zoom( '1w', 24*7)
          - $fn({vars}) => vars.zoom( '1m', 24*30)
        direction: right
        active: -1
        pad:
          r: 10
          t: 10
        type: buttons
        x: 0
        xanchor: left
        'y': 1.3
        yanchor: top

```

**Reply by dbuezas** [reply]
Does it happen all the time or only some times?

Btw, y don't need this:
```yaml
filters:
        - filter: i>0 <--- this is usually only used after computing a delta
        - resample: 1d <--- period: day means it is already daily
```

And you can do:
```yaml
hours_to_show: 7d
```

Instead of 168 hours

**Reply by fifthh** [reply]
Well it has happened one time so far in the last 3 weeks i've had this setup.

Without the filter: i>0  i get this:
![image](https://user-images.githubusercontent.com/57446983/223484424-56090a04-9a58-45bb-888a-f9cc43d92239.png)

**Reply by dbuezas** [reply]
Oh, i had forgotten about that gotcha with the statistics API.
The repetition may be an issue related to how that API responds too. Could it be that you observe it if you leave the plot open exactly at midnight?

**Reply by fifthh** [reply]
Perhaps i forgot it opened before i went to bed, let's wait and see if it happens again.
I saw another weird thing with the entity itself in the history tab.
![image](https://user-images.githubusercontent.com/57446983/223518786-29ee203d-0d0c-48da-81ef-e45ceb80b3cb.png)
Between midnight and 1 am it retracts some steps, but not every night.

**Reply by fifthh** [reply]
> Oh, i had forgotten about that gotcha with the statistics API. The repetition may be an issue related to how that API responds too. Could it be that you observe it if you leave the plot open exactly at midnight?

It happendd again, when the value is Null it copies the last real value. For instance, i  don't wear the watch on the weekends, therefor saturday and sunday copies fridays value.

**Reply by dbuezas** [reply]
Ok, I don't understand why. 
Please try the force_numeric filter. It may be that plotly misunderstands null values in bat charts

**Reply by fifthh** [reply]
> Ok, I don't understand why. Please try the force_numeric filter. It may be that plotly misunderstands null values in bat charts

Didn't do anything unfortunetly.
I wonder if it's because the counter doesn't reset and it just takes the previous value.

This is friday -> tuesday
![image](https://user-images.githubusercontent.com/57446983/225098989-62e5bab3-82ef-441d-a23f-cccdfb2dea8c.png)

**Reply by dbuezas** [reply]
It could be, can you mark in that plot what you expect to see?

**Reply by fifthh** [reply]
> It could be, can you mark in that plot what you expect to see?

Well, between the two lines should be 0 steps. I guess it returns value Null? However i'm unable to see the state in the history view.

**Reply by dbuezas** [reply]
Oh, I see. Then just make a filter `map_y: y || 0`

**Reply by fifthh** [reply]
> map_y: y || 0

Doesn't seem to do anything, unless i'm placing it wrong?
Like this? 
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.total_steps
    statistic: state
    period: day
    type: bar
    texttemplate: '%{y}'
    filters:
      - filter: i>0
      - resample: 1d
      - map_y: y || 0
  ```
