### DISCUSSION TITLE
Plot arbitrary data

### DISCUSSION THREAD

**Discussion by dbuezas** [dbuezas/lovelace-plotly-graph-card#26] [Show and tell]
```yaml
type: custom:plotly-graph
entities:
  - entity: custom-data-1 #can be any string 
    lambda: |-
      () => (
        {
          x: [25,25,25,25,25,26,27,29,30,32,34,36,37,39,40,40,40,40,39,38,37,35,33,31,29,28,27,26,25,25,25,25,24,24,24,24,23,22,21,19,18,16,14,12,11,10,9,9,9,9,10,12,13,15,17,19,20,22,23,24,24,24,24],
          y: [25,25,25,26,27,28,30,31,31,31,31,31,30,28,27,25,23,21,19,17,16,14,12,11,9,8,6,5,4,3,3,3,3,3,4,4,5,7,8,9,11,13,14,16,18,19,21,23,25,27,28,30,31,31,31,31,30,29,28,27,26,25,25]
        }
      )
```

![image](https://user-images.githubusercontent.com/777196/153462813-bed78405-7b90-452b-a472-f1e380367824.png)

**Comment by LukeMondy** [comment]
Just sharing my example:

```yaml
type: custom:plotly-graph
refresh_interval: 10
layout:
  yaxis:
    scaleanchor: x
    scaleratio: 1
entities:
  - entity: vacuum.robutt::position
    lambda: |-
      (ys) => (
       {
         x: ys.map(y => y.replace('(','').replace(')','').split(',').map(Number)[0] ),
         y: ys.map(y => y.replace('(','').replace(')','').split(',').map(Number)[1] )
       })
    line:
      width: 3
```
This plots the location of my roomba (from the Home Assistant Roomba integration). I believe the attribute produces data like "(x,y)", hence the `.replace` and mapping it as a number.

![woof](https://user-images.githubusercontent.com/39232534/200156578-b94f6333-bbb8-44cd-b58b-fcc29fde19b7.png)

It would be nice to have the colour fade out or change as the data gets 'older'.

**Reply by dbuezas** [reply]
Very cool, I didn't know you could do this! :)
Suggestion:
Add 
```yaml
line:
  shape: spline #or line
```
To your entity

**Comment by dbuezas** [comment]
without lambdas:
```yaml
type: custom:plotly-graph
hours_to_show: current_day
layout:
  xaxis:
    type: number
    autorange: true
entities:
  - entity: ""
    x: [25,25,25,25,25,26,27,29,30,32,34,36,37,39,40,40,40,40,39,38,37,35,33,31,29,28,27,26,25,25,25,25,24,24,24,24,23,22,21,19,18,16,14,12,11,10,9,9,9,9,10,12,13,15,17,19,20,22,23,24,24,24,24]
    y: [25,25,25,26,27,28,30,31,31,31,31,31,30,28,27,25,23,21,19,17,16,14,12,11,9,8,6,5,4,3,3,3,3,3,4,4,5,7,8,9,11,13,14,16,18,19,21,23,25,27,28,30,31,31,31,31,30,29,28,27,26,25,25]
```

or you can use $ex or $fn if you want to generate the data points procedurally
