### DISCUSSION TITLE
Limit y axis to one graph

### DISCUSSION THREAD

**Discussion by seidler2547** [dbuezas/lovelace-plotly-graph-card#262] [Q&A] [answered]
Hi, I'm trying to have the y axis scale according to only one of the three values I'm plotting. Background is that I plot max_allowed, actual and min_allowed, but most of the time actual is far away from both values. Hence I would like to scale the y axis to only consider the actual graph , with the max and min coming into view when actual is getting close to them. I tried to play around with yaxes functions but haven't found a way to do it.

**Comment by dbuezas** [comment]
You could store the datapoints in vars using a filter and then set the layout:yaxis:range with a $ex.
The drawback is that it will snap back the range if you zoom/scroll

**Comment by seidler2547** [comment]
Hmm, I was looking at this: https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/233
And thought I'd find a way to limit it to use only the first entity, but I don't understand the syntax enough to modify it.

**Reply by dbuezas** [reply]
That's a good starting point, I'll post a solution below

**Comment by dbuezas** [comment, marked as answer]
```yaml
type: custom:plotly-graph
hours_to_show: current_week
entities:
  - entity: sensor.senseair_temperature
  - entity: sensor.durchgang_thermometer_temperature
    
layout:
  uirevision: $fn () => Math.random() // force rescale on scroll
  yaxis:
    range: |
        $fn ({ getFromConfig }) => {
          const all = getFromConfig("entities.1").y;
          return [
            Math.max(12, Math.min(...all)), // cap to lowest value, but at least 12
            Math.min(18, Math.max(...all)), // cap to highest value, but at most 18
          ]
        }
```
