### DISCUSSION TITLE
Text sensor on graphs

### DISCUSSION THREAD

**Discussion by jazzmonger** [dbuezas/lovelace-plotly-graph-card#266] [Q&A] [answered]
**Describe the solution you'd like**

I have complex logic for several sensors that I track in in a graph.  One of them is a text sensor that changes state from idle/heat/cool/off and I'd like to be able to illustrate that in a graph WITH the text. Of course I can represent that with a 1/2/3/4 step function, but knowing when that sensor changes and what the state is would be very cool.

**How would it be defined in yaml?**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.monthly_internet_energy
     entity_feature_config: xxx
global_feature_config: xxx
```

**Scribble**
When applicable, paste a drawing of how the feature would look like 

I'd like to annotate the changing state on a line at the bottom of this graph:

![517E0B54-E982-4826-A965-36755D59221E](https://user-images.githubusercontent.com/52110065/229415794-5321e172-2569-42c9-b1db-13de53490959.jpeg)

**Additional context**

**Comment by dbuezas** [comment, marked as answer]
Hi there 👋 

here's a way of doing it:
```yaml
type: custom:plotly-graph
hours_to_show: 10m
entities:
  - entity: sensor.teich_temperature
    mode: markers+text+lines
    textposition: top
    text: $ex ys
```

<img width="503" alt="image" src="https://user-images.githubusercontent.com/777196/229565228-fb2781e7-1808-4028-a279-ef9d1296e495.png">

the `$ex` you see there means "this is an expression", and `ys` just means "put the array of y values in there". See more about universal functions and expressions [here](https://github.com/dbuezas/lovelace-plotly-graph-card#universal-functions). You can probably combine it with `texttemplate` to format it or just this instead:
```
$ex ys.map(y => `the value is: ${y}`)
```

----

Alternatively you may want to use a bar chart instead and avoid setting the text array yourself, see this Show&Tell: #223
