### DISCUSSION TITLE
Heatmap of 30-Panel Solar Array's Current States

### DISCUSSION THREAD

**Discussion by kaijk** [dbuezas/lovelace-plotly-graph-card#277] [Show and tell]
UPDATED: We have a solution. Big THANKS to @dbuezas for this awesome card and your help with the solution.

Plot a solar panel array's physical layout as a heat map based on the current states of say 30 panels.  Each entity is its own cell in the heat map.

The matrix layout is categorical with three rows and 11 columns (cells [1,2], [1,3], and [6,1] are empty).
Here is the concept
![image](https://user-images.githubusercontent.com/49624034/233813429-1bbd80cf-c87a-4f43-bd1f-ccf20b613a53.png)

Here is the plot showing some evening shading from the west and some overall production decline due to sun angle and a very high pollen count right now that has blanketed the panels. Time to hose them down
![image](https://user-images.githubusercontent.com/49624034/233873781-53d19a32-8e8e-4e44-bb9e-c20a50914212.png)

Here is the code with a couple of slight tweaks from what deuezas came up with below. I wanted to round the values to integers which required testing for empty cells.  That's about it.
```yaml
type: custom:plotly-graph
title: Solar Panels (Watts)
fn: | # fn has no meaning, this is just used to construct the panels matrix once an store them in vars
  $ex {
    vars.z = [[
          // row 3
          '', 'sensor.power_1_2_8', 'sensor.power_1_2_7', 'sensor.power_1_2_6', 'sensor.power_1_2_2', 'sensor.power_1_2_1',
              'sensor.power_1_1_9', 'sensor.power_1_1_8', 'sensor.power_1_1_7', 'sensor.power_1_1_3', 'sensor.power_1_1_2',
        ],[
          // row 2
          '', 'sensor.power_1_2_9',  'sensor.power_1_2_5', 'sensor.power_1_2_4', 'sensor.power_1_2_3', 'sensor.power_1_2_15',
              'sensor.power_1_1_10', 'sensor.power_1_1_6', 'sensor.power_1_1_5', 'sensor.power_1_1_4', 'sensor.power_1_1_1',
        ],[
          // row 1
          'sensor.power_1_2_10', 'sensor.power_1_2_11', 'sensor.power_1_2_12', 'sensor.power_1_2_13', 'sensor.power_1_2_14', '',
          'sensor.power_1_1_11', 'sensor.power_1_1_12', 'sensor.power_1_1_13', 'sensor.power_1_1_14', 'sensor.power_1_1_15',
        ]].map(row=>
          row.map(sensor=>
            isNaN(hass.states[sensor]?.state) ? '' : Math.round(hass.states[sensor]?.state) // Handles empty cells
      )
    )
  }
entities:
  - entity: ""
    z: "$ex vars.z"
    text_auto: true
    type: heatmap
    hoverongaps: false
    xgap: 2
    ygap: 2
    zmax: 400
    zmin:   0
raw_plotly_config: true
refresh_interval: 180 # Data actually updated every 15m
layout:
  annotations: |
    $ex vars.z.flatMap((row, y) => row.map((text="", x) => ({
      x,
      y,
      text,
      font: {
        family: 'Arial',
        size:   '14',
        color:  'black'
      },
      showarrow: false,
    })))
  yaxis:
    showgrid: false
    zeroline: false
    showticklabels: false
    visible: false

  xaxis:
    showgrid: false
    zeroline: false
    showticklabels: false
    ticks: false
    visible: false
  height: 300
  margin:
    t: 20
    l: 20
    b: 20
```

**Comment by dbuezas** [comment]
That's a really cool use case, I'd really like to see the result!
I suggest you 
1. Construct a matrix with the entity IDs of all panels
2. Use map to transform it into a matrix of states using the hass object (e.g `hass.states[entity_ids[i][j]].state`)
3. Post yaml and screenshots :)

**Comment by dbuezas** [comment]
To handle the missing panels, just use empty strings as ids and use the "optional chaining operator" (question mark)
```
hass.states[entity_ids[i][j]]?.state
```

**Comment by dbuezas** [comment]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/777196/233843547-dc4faa3b-495d-4b3d-b939-69dced7863cd.png">

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.openweathermap_temperature

    z: |
      $fn ({ hass }) => {
        const panels = [[
          // row 3
          'sensor.teich_temperature','sensor.living_thermometer_temperature', // add more columns
        ],[
          // row 2
          'sensor.outside_temperature','sensor.keller_temperature',
        ],[
          // row 1
          'sensor.garden_temperature','sensor.senseair_temperature',
        ]]
        return panels.map(row=> 
          row.map(sensor=>
            hass.states[sensor]?.state
          )
        );
      }
    type: heatmap
    hoverongaps: false
raw_plotly_config: true
title: Solar Panels
layout:
  height: 300
  margin:
    t: 20
```

**Comment by kaijk** [comment]
![newplot](https://user-images.githubusercontent.com/49624034/233861219-5223474b-e196-42fb-921e-635c4c7144c2.png)
Thank You!
This works.  However, I thought I could use the same logic to show the current state in each cell with the `text` parameter. No joy there yet, but major progress. (the commented out text sting array doesn't show up either). It seems that `text:` was added in Plotly V5.5.0, FWIW
```yaml
title: Solar Panels (Watts)
entities:
  - entity: ""
    z: |
      $fn ({ hass }) => {
        const panels = [[
          // row 3
          '""', 'sensor.power_1_2_8', 'sensor.power_1_2_7', 'sensor.power_1_2_6', 'sensor.power_1_2_2', 'sensor.power_1_2_1',
                'sensor.power_1_1_9', 'sensor.power_1_1_8', 'sensor.power_1_1_7', 'sensor.power_1_1_3', 'sensor.power_1_1_2',
        ],[
          // row 2
          '""', 'sensor.power_1_2_9',  'sensor.power_1_2_5', 'sensor.power_1_2_4', 'sensor.power_1_2_3', 'sensor.power_1_2_15',
                'sensor.power_1_1_10', 'sensor.power_1_1_6', 'sensor.power_1_1_5', 'sensor.power_1_1_4', 'sensor.power_1_1_1',
        ],[
          // row 1
          'sensor.power_1_2_10', 'sensor.power_1_2_11', 'sensor.power_1_2_12', 'sensor.power_1_2_13', 'sensor.power_1_2_14', '""',
          'sensor.power_1_1_11', 'sensor.power_1_1_12', 'sensor.power_1_1_13', 'sensor.power_1_1_14', 'sensor.power_1_1_15',
        ]]
        return panels.map(row=>
          row.map(sensor=>
            hass.states[sensor]?.state
          )
        );
      }
    text: |
      $fn ({ hass }) => {
        const labels = [[
          // row 3
          '""', 'sensor.power_1_2_8', 'sensor.power_1_2_7', 'sensor.power_1_2_6', 'sensor.power_1_2_2', 'sensor.power_1_2_1',
                'sensor.power_1_1_9', 'sensor.power_1_1_8', 'sensor.power_1_1_7', 'sensor.power_1_1_3', 'sensor.power_1_1_2',
        ],[
          // row 2
          '""', 'sensor.power_1_2_9',  'sensor.power_1_2_5', 'sensor.power_1_2_4', 'sensor.power_1_2_3', 'sensor.power_1_2_15',
                'sensor.power_1_1_10', 'sensor.power_1_1_6', 'sensor.power_1_1_5', 'sensor.power_1_1_4', 'sensor.power_1_1_1',
        ],[
          // row 1
          'sensor.power_1_2_10', 'sensor.power_1_2_11', 'sensor.power_1_2_12', 'sensor.power_1_2_13', 'sensor.power_1_2_14', '""',
          'sensor.power_1_1_11', 'sensor.power_1_1_12', 'sensor.power_1_1_13', 'sensor.power_1_1_14', 'sensor.power_1_1_15',
        ]]
        return labels.map(row=>
          row.map(sensor=>
            hass.states[sensor]?.state
          )
        );
      }

    type: heatmap
    hoverongaps: false
    xgap: 2
    ygap: 2
    zmax: 400
    zmin:   0
    #text:  [[ '1_1_1', '2', '3', '4', '5', '6','7', '8', '9', '10', '11'],
    #        [ '1_1_1', '2', '3', '4', '5', '6','7', '8', '9', '10', '11'],
    #        [ '1_1_1', '2', '3', '4', '5', '6','7', '8', '9', '10', '11']]
raw_plotly_config: true
#hours_to_show: 240
refresh_interval: 90
layout:
  height: 300
  margin:
    t: 20
```

**Comment by dbuezas** [comment]
That was tricky, and fun!
<img width="505" alt="image" src="https://user-images.githubusercontent.com/777196/233864569-903f87e6-c61c-4759-96f6-afb6366da0ee.png">

```yaml
type: custom:plotly-graph
fn: | # fn has no meaning, this is just used to construct the panels matrix once an store then in vars
  $ex {
    vars.z = [[
      // row 3
      '','sensor.teich_temperature','sensor.living_thermometer_temperature', // add more columns
    ],[
      // row 2
      'sensor.outside_temperature','','sensor.keller_temperature',
    ],[
      // row 1
      '', 'sensor.garden_temperature','sensor.senseair_temperature',
    ]].map(row=> 
      row.map(sensor=>
        hass.states[sensor]?.state
      )
    )
  }
entities:
  - entity: ''
    z: "$ex vars.z"
    text_auto: true
    xgap: 2
    ygap: 2
    type: heatmap
    hoverongaps: false
raw_plotly_config: true
title: Solar Panels
layout:
  annotations: |
    $ex vars.z.flatMap((row, y) => row.map((text="", x) => ({
      x,
      y,
      text,
      font: {
        family: 'Arial',
        size: 14,
        color: 'white'
      },
      showarrow: false,
    })))
  yaxis:
    showgrid: false
    zeroline: false
    showticklabels: false
    visible: false

  xaxis:
    showgrid: false
    zeroline: false
    showticklabels: false
    ticks: false
    visible: false

  height: 300
  margin:
    t: 20
    l: 20
    b: 20 

```

**Reply by dbuezas** [reply]
The trick was to put the text inside `layout/annotations`, an as a 1d array (not a matrix). Weird API 🤷 .
I also removed the grids, ticks, labels, etc

**Reply by kaijk** [reply]
Thanks for all your help. I updated the original post to reflect the solution.  I wish I had a prayer of figuring out how you did this.  Are their any resources to help one get a handle on all this mapping?

**Reply by dbuezas** [reply]
Awesome!

Here are the answers to thy prayer
* Use console.log a debugger: see https://github.com/dbuezas/lovelace-plotly-graph-card#debugging
* You can for example console.log before and after each mapping 
* Google "how to do xyz in plotlyjs", then translate to yaml
* In this case I landed on the heatmap examples page of plotly and saw there was a relevant example that used annotations in heatmaps
* Map and flatmap are standard JavaScript functions or arrays, look for help on those too

**Comment by markcocker** [comment]
I would like to click on a heatmap tile to popup the standard Home Assistant entity detail dialogue. I tried the on_click approach shown in https://github.com/dbuezas/lovelace-plotly-graph-card but under text `Alternatively, clicking on points of the trace itself.` it says `this doesn't work`.  Is this still the case, or is there another approach?

BTW, if you want to remove the colour scale,  add `showscale: false`
```yaml
entities:
  - entity: ''
    z: $ex vars.z
    xgap: 2
    ygap: 2
    zmax: 400
    zmin: 0
    type: heatmap
    hoverongaps: false
    showscale: false
```

**Comment by NoUsername10** [comment]
@dbuezas + @kaijk  
Fantastic soulution, great idea and super nice to use!

I added the string ID, then use a graph below to see the individual string health.
Might be busy with that number of panels though :-)

<img width="500" height="auto" alt="info solar panels" src="https://github.com/user-attachments/assets/31943e31-1486-43e0-85f3-8e8b6baa952b" />

<img width="500" height="auto" alt="info DC strings" src="https://github.com/user-attachments/assets/cf089fdb-36e2-49e2-a81e-a55d85492b1e" />




```
type: custom:plotly-graph
title: Solar Panels (DC String Power W)
fn: |
  $ex {
    // Define sensor array
    const sensorArray = [[
          'sensor.slx_powerdc2_SERIALNR',  'sensor.slx_powerdc1_SERIALNR',
        ],[
          'sensor.slx_powerdc1_SERIALNR',  'sensor.slx_powerdc2_SERIALNR',
        ],[
          'sensor.slx_powerdc2_SERIALNR', ''
        ]];

    // Get power values - FIXED: Keep 0 values
    vars.z = sensorArray.map(row =>
      row.map(sensor => {
        if (!sensor) return ''; // Keep empty cells as empty string
        const value = hass.states[sensor]?.state;
        return isNaN(value) ? '' : Math.round(value); // 0 will be 0, not ''
      })
    );

    // Extract sensor names - keep everything after 'slx_power' and replace _ with space
    vars.sensorNames = sensorArray.map(row =>
      row.map(sensor => {
        if (!sensor) return '';
        // Extract everything after 'slx_power'
        const afterPower = sensor.split('slx_power')[1];
        if (!afterPower) return sensor;
      
        // Replace underscores with spaces
        const namePart = afterPower.replace(/_/g, ' ');
        return namePart || sensor;
      })
    );
    const lastUpdated = hass.states['sensor.slx_powerdc2_SERIALNR']?.last_updated;
    vars.updateTime = lastUpdated ? new Date(lastUpdated).toLocaleTimeString() : 'Loading';
  }
entities:
  - entity: ""
    z: $ex vars.z
    text_auto: true
    type: heatmap
    colorscale:
      - - 0
        - cyan
      - - 0.3
        - green
      - - 0.6
        - yellow
      - - 1
        - red
    hoverongaps: false
    xgap: 2
    ygap: 2
    zmax: 500
    zmin: 0
raw_plotly_config: true
refresh_interval: 180
config:
  displayModeBar: false
  staticPlot: true
  scrollZoom: false
  displaylogo: false
layout:
  annotations: |
    $ex [ ... vars.z.flatMap((row, y) => row.map((text="", x) => ({
      x,
      y: y + 0.1,  // Position names below 
      text: text === 0 || text > 0 ? text + " W" : "",  // Explicitly check for 0
      font: {
        family: 'arial',
        size:   '25',
        color:  'black'
      },
      showarrow: false,
    }))),
      // Sensor names below values
      ...vars.sensorNames.flatMap((row, y) => row.map((name="", x) => ({
        x,
        y: y - 0.3,  // Position names below values
        text: name,
        font: {family: 'sans-serif', size: '12', color: 'black'},
        showarrow: false,
      }))),
    // Footer with update time
    {
      x: 0.25,
      y: -0.14,
      text: `Last update: ${vars.updateTime}`,
      font: {family: 'sans-serif', size: '14', color: 'grey'},
      showarrow: false,
      xanchor: 'center',
      xref: 'paper',
      yref: 'paper'
    }
    ]
  yaxis:
    showgrid: false
    zeroline: false
    showticklabels: false
    visible: false
  xaxis:
    showgrid: false
    zeroline: false
    showticklabels: false
    ticks: false
    visible: false
  height: 270
  margin:
    t: 20
    l: 20
    b: 45
    r: 20
```

**Comment by rgr-1** [comment]
<img width="1056" height="361" alt="image" src="https://github.com/user-attachments/assets/1fe64d80-d58d-46fb-b4d7-55b0e6677ac9" />

Micro-inverter's fun

<details><summary>The config of the left:</summary>
<p>

```yml
type: custom:plotly-graph
title: PV Panels power, W
fn: |
  $ex {
    vars.z = [
                  [
                    // row 1
                    'sensor.pv_inv_1_ch1_power', 'sensor.pv_inv_1_ch2_power', 'sensor.pv_inv_1_ch3_power', 'sensor.pv_inv_1_ch4_power'
                  ],
                  [
                    // row 2
                    'sensor.pv_inv_2_ch1_power', 'sensor.pv_inv_2_ch2_power', 'sensor.pv_inv_2_ch3_power', 'sensor.pv_inv_2_ch4_power'
                  ],
                  [
                    // row 3
                    'sensor.pv_inv_3_ch1_power', 'sensor.pv_inv_3_ch2_power', 'sensor.pv_inv_3_ch3_power', 'sensor.pv_inv_3_ch4_power'
                  ],
                  [
                    // row 4
                    'sensor.pv_inv_4_ch1_power', 'sensor.pv_inv_4_ch2_power', 'sensor.pv_inv_4_ch3_power', 'sensor.pv_inv_4_ch4_power'
                  ],
                  [
                    // row 5
                    'sensor.pv_inv_5_ch1_power', 'sensor.pv_inv_5_ch2_power', 'sensor.pv_inv_5_ch3_power', 'sensor.pv_inv_5_ch4_power'
                  ]
        ].map(row=>
          row.map(sensor=>
            isNaN(hass.states[sensor]?.state) ? '' : Math.round(hass.states[sensor]?.state) // Handles empty cells
                )
            )
  }
entities:
  - entity: ""
    z: $ex vars.z
    text_auto: true
    type: heatmap
    hoverongaps: false
    xgap: 2
    ygap: 4
    zmax: 500
    zmin: 0
raw_plotly_config: true
refresh_interval: 180
layout:
  annotations: |
    $ex vars.z.flatMap((row, y) => row.map((text="", x) => ({
      x,
      y,
      text,
      font: {
        family: 'Arial',
        size:   '14',
        color:  'black'
      },
      showarrow: false,
    })))
  yaxis:
    showgrid: false
    zeroline: false
    showticklabels: true
    tickmod: array
    tickvals:
      - 0
      - 1
      - 2
      - 3
      - 4
    ticktext:
      - inv-1
      - inv-2
      - inv-3
      - inv-4
      - inv-5
    visible: true
  xaxis:
    showgrid: false
    zeroline: false
    tickvals:
      - 0
      - 1
      - 2
      - 3
    ticktext:
      - p1
      - p2
      - p3
      - p4
    showticklabels: true
    ticks: true
    visible: true
  height: 300
  margin:
    t: 20
    l: 40
    b: 25
```

</p>
</details> 

FYI
- it's a bit late now - sun is on the other side of the planet
- panels' yield reflects gradual steps of system build and a bit of shading
