### DISCUSSION TITLE
Daily heating consumption

### DISCUSSION THREAD

**Discussion by matteobrusa** [dbuezas/lovelace-plotly-graph-card#28] [Show and tell]
I've got a pellets furnace that provides a sensor with an overall consumption.
I wanted to chart the daily consumption in relationship with the outside temperature, here's how it looks so far:
![image](https://user-images.githubusercontent.com/6077747/153758016-4018d0aa-249e-4849-99b6-731f95a90c6b.png)

I'd like to set the bars color depending on the daily consumption. Any idea?
Also, it seems that the y-axis label on the right side overflows.

```
type: custom:plotly-graph
title: Consumption
hours_to_show: 168
layout:
  xaxis:
    rangeselector:
      'y': 1.25
      buttons:
        - count: 7
          step: day
        - count: 1
          step: month
        - count: 6
          step: month
entities:
  - entity: sensor.eta_total_consumption
    name: Consumption
    unit_of_measurement: Kilograms
    type: bar
    lambda: |-
      (ys, xs) => {

        const DAY= 24*60*60*1000
        let today= xs[0] - (xs[0].getTime() % DAY) 
                  +60*1000* new Date().getTimezoneOffset()

        //console.warn ( "serie: "+ xs.length + " starts at "+  xs[0].toLocaleString())

        const result = {x:[], y:[]}

        let last= parseFloat(ys[0])
        let tomorrow= today + DAY
        let firstday= today

        //console.log("first day to show: " + new Date(firstday).toLocaleDateString())

        let x,y
          
        for (let i = 0; i < xs.length; i+=1) {

           x = xs[i]
           y = parseFloat(ys[i]) 

          if (x>tomorrow){

            //console.log("today "+ new Date(today).toLocaleString() + "   now "+ x.toLocaleString() + "   last: " + last)

            if (firstday != today) {
              result.y.push(y-last)
              result.x.push(new Date(today))
            }

            last = y
            today= tomorrow 
            tomorrow+= DAY
          }
        }   

        // include incomplete today
        result.y.push(y-last)
        result.x.push(new Date(today))
        
        return result
      }
  - entity: sensor.eta_outside_temp
    name: Outside temp

```

**Comment by dbuezas** [comment]
With the new statistics support, this became way easier and more efficient, no lambda required anymore

**Reply by Balou067** [reply]
Hi, I just came across this exemple and the comment that it is now much easier with the statistics support. Do you have a exemple for this?

**Reply by dbuezas** [reply]
```yaml
- entity: sensor.eta_total_consumption
  statistic: sum
  period: day
```
More [here](https://github.com/dbuezas/lovelace-plotly-graph-card#statistics-support)

**Reply by Balou067** [reply]
Thanks for the fast replay.  However, the two different examples do, by me, not lead to the same result. The reason is probably that the sensor has the `state_class: total` and not `total_increasing` (Sensor is defined as `platform: integration` (Rieman integration)).  So with the "statistic: sum Approche" I get the total sum and not the daily difference as with the "lambda Approche".

![image](https://user-images.githubusercontent.com/57370719/198998434-1be29836-7928-4a2c-990b-956ae823edf3.png)

```
# "statistic: sum Approche"
  - type: custom:plotly-graph
    title: Energieverbrauch [kWh] - [with statistic:sum]
    hours_to_show: 168
    defaults:
      yaxes:
        fixedrange: true # disables vertical zoom & scroll
    layout:
      xaxis:
        rangeselector:
          'y': 1.25
          buttons:
            - count: 7
              step: day
            - count: 1
              step: month
            - count: 6
              step: month

    entities:
      - entity: sensor.mystrom_wifi_switch_8a09b8_energy
        statistic: sum
        period: day
        name: Kühlschrank Keller 
        unit_of_measurement: kWh
        type: bar

# "lambda Approche".
  - type: custom:plotly-graph
    title: Energieverbrauch [kWh] - [with lambda]
    hours_to_show: 168
    defaults:
      yaxes:
        fixedrange: true # disables vertical zoom & scroll

    layout:
      xaxis:
        rangeselector:
          'y': 1.25
          buttons:
            - count: 7
              step: day
            - count: 1
              step: month
            - count: 6
              step: month

    entities:
      - entity: sensor.mystrom_wifi_switch_8a09b8_energy
        name: Kühlschrank Keller
        unit_of_measurement: kWh
        type: bar
        lambda: |-
          (ys, xs) => {

            const DAY= 24*60*60*1000
            let today= xs[0] - (xs[0].getTime() % DAY) 
                      +60*1000* new Date().getTimezoneOffset()
.....
```

**Reply by roztobart** [reply]
You'd have to add filters to the entity, ie: 

    entities:
      - entity: sensor.mystrom_wifi_switch_8a09b8_energy
        statistic: sum
        period: day
        name: Kühlschrank Keller 
        unit_of_measurement: kWh
        type: bar
        filters:
         - derivate: d

**Reply by alwa2** [reply]
Can you combine the period switch with the derivate method?  I have some buttons to switch through different time periods. By now there is calculated some kind of average when the time period is different to the day value.

```
entities:
  - entity: sensor.int_level_heizung_summe
    name: Verbrauch
    statistic: sum
    period:
      24h: hour
      7d: day
      1M: week
      6M: week
      1y: month
    type: bar
    filters:
      - derivate: d    
```
Also I wanted to add barcornerradius and I don't know where to put that, any hinds? Thanks

**Reply by dbuezas** [reply]
You can use use $ex `get('visible_range')` to make them both dependent on the zoom level.

**Reply by alwa2** [reply]
Thanks for the quick reply. Where should I put that? When I put it after derivate instead 
of "d"  i get an error:

![Screenshot_20240227_211626_Home Assistant](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/54262510/d362b480-8817-4fd2-891c-7b7fe9eb042c)


```
type: custom:plotly-graph
title: Heizleistung
hours_to_show: 1M
layout:
  dragmode: pan
  yaxis:
    fixedrange: true
  xaxis:
    rangeselector:
      'y': 1.15
      buttons:
        - count: 24
          step: hour
        - count: 7
          step: day
        - count: 1
          step: month
        - count: 6
          step: month
        - count: 1
          step: year
entities:
  - entity: sensor.int_level_heizung_summe
    name: Verbrauch
    statistic: sum
    period:
      24h: hour
      7d: day
      1M: week
      6M: week
      1y: month
    type: bar
    filters:
      - derivate: d
    marker:
      color: rgba(44,160,44,0.6)
      opacity: 0.6
    texttemplate: '%{y:.0f}'
  - entity: sensor.draussen_wetterstation_temperatur
    name: Außentemperatur
    statistic: mean
    period:
      24h: 5minute
      7d: hour
      1M: day
      6M: week
      1y: month
    line:
      width: 2
      color: dodgerblue
      smoothing: 1

```
