### DISCUSSION TITLE
Touch support

### DISCUSSION THREAD

**Discussion by CendaL** [dbuezas/lovelace-plotly-graph-card#293] [Q&A]
I'm struggling to add touch support to see `y` value when touch the graph on phone.

``` yaml
type: custom:plotly-graph
entities:
  - entity: sensor.kotel_venkovni_teplota
    name: Teplota
    statistic: mean
    period: hour
    line:
      shape: spline
    show_value: true
  - entity: sensor.pressure
    name: Tlak
    line:
      shape: spline
    show_value: true
    yaxis: y2
hours_to_show: 72
time_offset: 6h
autorange_after_scroll: true
layout:
  title:
    text: Počasí
    x: 0.05
    'y': 1.3
    xanchor: left
    yanchor: top
  legend:
    x: 0
    'y': -0.3
    xanchor: left
    yanchor: bottom
  yaxis2:
    fixedrange: true
    range:
      - 990
      - 1050
  xaxis:
    rangeselector:
      x: 1.1
      'y': 1.1
      xanchor: right
      yanchor: middle
      buttons:
        - count: 3
          step: day
        - count: 7
          step: day
        - count: 14
          step: day
```

If I doubletouch the graph on phone, sometimes I can briefly see the hover label with value. But more often I see nothing or it zooms in.
I've experimented with `hovermode`, `hoverdistance`, `clickmode`, `dragmode` but not successfully.

Of course, I'd like to keep current behavior when I scroll with drag a graph is auto-zoomed if possible.
