### DISCUSSION TITLE
3D-scatter graph

### DISCUSSION THREAD

**Discussion by aforell57** [dbuezas/lovelace-plotly-graph-card#298] [Q&A] [answered]
That 3D scatter graph in the readme is very nice! What is the yaml code of it? My actual need is to create a 2D scatter, but have not succeeded so far

**Comment by dbuezas** [comment, marked as answer]
I thought no one would ever ask! :) 
This should also give you an idea on how to make a 2d scatter
<img src="https://user-images.githubusercontent.com/777196/215353175-97118ea7-778b-41b7-96f2-7e52c1c396d3.gif" width="300" >

```yaml
type: custom:plotly-graph-dev
entities:
  - entity: sensor.openweathermap_pressure
    internal: true
    filters:
      - resample: 1h
    fn: $fn ({ xs, ys, vars }) => { vars.pressure = ys; vars.xs = xs; }
  - entity: sensor.openweathermap_temperature
    internal: true
    filters:
      - resample: 1h
    fn: $fn ({ ys, vars }) => vars.temperature = ys
  - entity: sensor.openweathermap_humidity
    internal: true
    filters:
      - resample: 1h
    fn: $fn ({ ys, vars }) => vars.humidity = ys
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': $fn ({ vars }) => vars.pressure
    z: $fn ({ vars }) => vars.humidity
    type: scatter3d
    mode: lines+markers
    marker:
      size: 7
    line:
      color: rgba(50, 50, 217, 0.5)
      width: 3
      opacity: 0.8
hours_to_show: 24
raw_plotly_config: true
layout:
  margin:
    t: 0
    l: 0
    r: 0
    b: 0
  height: 500
  scene:
    annotations:
      - x: $fn ({ vars }) => vars.temperature[0]
        y: $fn ({ vars }) => vars.pressure[0]
        z: $fn ({ vars }) => vars.humidity[0]
        text: start
        showarrow: tru
        arrowhead: 1
    xaxis:
      title: Temperature
    yaxis:
      title: Pressure
    zaxis:
      title: Humidity

```

**Reply by aforell57** [reply]
Thanks!
That was very useful.
Cheers!

**Reply by kimhey** [reply]
Thanks @dbuezas for an excellent tool. I was also looking for a way to use your implementation to make ordinary 2D scatter plots (only x-y). In your answer above I understand it as you can, but in your example code it still shows a 3D-scatter. Will you explain a bit more please?

**Reply by dbuezas** [reply]
@kimhey change `type: scatter3d` to `type: scatter` or just remove it

**Comment by dbuezas** [comment]
BTW, if you need a scatter plot, it is likely you'll also find histograms useful
<img width="300" alt="image" src="https://user-images.githubusercontent.com/777196/215352591-4eeec752-6abf-40cf-8214-a38c03d64b43.png" align="left" >
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.openweathermap_temperature
    x: $fn ({ys,vars}) => ys
    type: histogram
title: Temperature Histogram last 10 days
hours_to_show: 240
ha_theme: true
raw_plotly_config: true
layout:
  margin:
    t: 20
    l: 50
    b: 40
  height: 285
  xaxis:
    autorange: true

```

**Comment by jorelvaccaro** [comment]
@dbuezas This is great, thank you for this. Quick note, I just got this working in Home Assistant with the Plotly Graph Card repository in HACS, but I had to remove the "-dev" from the end of the type: line to get it working. Thanks again!

**Reply by dbuezas** [reply]
Oh, good catch!
I have the card installed twice (one for development). I fixed the yaml above now.

**Comment by selzem** [comment]
I love scatter plots! Thank you for making them available in your cards for HA.
I show the supplied heat of my heat pump vs. the outside temperature in the performance field of the heat pump. 
Questions:  1) How can I exclude the data points, when the heat pump is not running and heat load is 0 kW?
2) Is there a simple way to color the dots in relation to time and / or maybe change their size? Current point green and big and older points fading into red or transparent and getting smaller? I think I saw something in one of the many questions, but I cannot find it anymore.
3) How do I move the legend to a different position?

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/154087728/97bbbaa0-ad04-432c-b898-604328658a18)

**Reply by dbuezas** [reply]
Hi, happy to hear you're enjoying the card!

1. to filter the zero points you can
```yaml
entity: 
  - sensor.xyz
    filters:
       - filter: y > 0 # or you could do 0.5 if they are not always exactly zero
```

2. color the dots in relation to time

```yaml
entity: 
  - sensor.xyz
    marker: 
       color: $ex 'xs.map(date => +date)'
```

similar with size, but you'll have to do some maths.

3. move legend:

```yaml
 legend:
   orientation: h
   bgcolor: transparent
   x: 0
   y: 1
   yanchor: bottom
```

See defaults [here ](https://github.com/dbuezas/lovelace-plotly-graph-card/blob/master/src/parse-config/defaults.ts#L115)
Manual [here](https://plotly.com/javascript/legend/) and [here](https://plotly.com/javascript/reference/layout/#layout-legend)

**Updated: fixed indentation**

**Reply by selzem** [reply]
Thanks for the quick reply David! 1 and 3 are quite simple solutions. For 2 I will need a bit more time to make it work, but I will manage with you pointing me in the right direction.

**Reply by selzem** [reply]
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/154087728/aa018883-b134-4452-a134-03acfa6000a5)

It took me longer than I would like to admit, but I finally managed to make the code work.
Here is what I used to make the scatter plot:
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.smart_hygrometer_11ef_temperature
    filters:
      - resample: 15m
    internal: true
    fn: $fn ({ xs, ys, vars }) => { vars.y_axis = ys; vars.xs = xs; }
  - entity: sensor.openweathermap_temperature
    filters:
      - resample: 15m
    internal: true
    fn: |-
      $fn ({xs, ys, vars }) => { vars.x_axis = ys;
       const sz = []
       const op = []
       const clr =[]
      for (let i = 1; i < xs.length; i++){
              sz[i] = 10*((i)/ xs.length)+1;
              op[i] = 0.9*((i)/ xs.length)+0.1;
              if(i < xs.length -1)
              {clr[i] = "darkseagreen"}
              else
              {clr[i] = "crimson"}
       }
       vars.sz = sz;
       vars.op = op;
       vars.clr = clr;
      }
  - entity: ''
    name: Temperature living room vs. outside
    x: $fn ({ vars }) => vars.x_axis
    'y': $fn ({ vars }) => vars.y_axis
    type: scatter
    mode: markers
    marker:
      size: $fn ({ vars }) => vars.sz
      opacity: $fn ({ vars }) => vars.op
      color: $fn ({ vars }) => vars.clr
      line:
        width: 0
  - entity: ''
    name: Ideal temperature
    x:
      - -10
      - 21
      - 21
      - -10
      - -10
    'y':
      - 20.5
      - 20.5
      - 19.5
      - 19.5
      - 20.5
    line:
      color: darkslateblue
hours_to_show: 24
raw_plotly_config: true
ha_theme: true
layout:
  margin:
    t: 10
    l: 70
    r: 0
    b: 70
  height: 500
  yaxis:
    title:
      text: Temperature living room °C
  xaxis:
    title:
      text: Temperature outside °C
    autorange: true
  legend:
    orientation: h
    bgcolor: transparent
    x: 0
    'y': 1
    yanchor: bottom
``` 
Since I use two colors for the markers the marker in the legend is shown as black or is there another reason and it can be fixed?
