### DISCUSSION TITLE
Bar chart of current value with midnight reset

### DISCUSSION THREAD

**Discussion by Elarion245** [dbuezas/lovelace-plotly-graph-card#299] [Q&A] [answered]
Hello,

I am trying to create a bar chart with some history for a measurement sensor. The value of the measurement is changing throughout the day and is naturally reset to 0.0% at midninght.
I am interested in a chart which shows the last value of a day for the past prior days and also the most recent value for the current day.

So far I have tried:
```
type: custom:plotly-graph
title: Eigennutzung Solarenergie
entities:
  - entity: sensor.solarenergie_eigennutzung
    period: day
    type: bar
    texttemplate: '%{y:.2f}'
    filters:
      - filter: i>0
    marker:
      color: orange
hours_to_show: 168
refresh_interval: 60
layout:
  xaxis:
    rangeselector:
      'y': 1.2
      buttons:
        - count: 7
          step: day
        - count: 14
          step: day
        - count: 21
          step: day
        - count: 1
          step: month
        - count: 3
          step: month
        - count: 6
          step: month
```
The bar chart indeed shows up, but the values are wrong. This seems to be related to the period: day property. Apparently it seems to do some computation on the values and does not just take the most recent sample.

How can I achieve what I've described above?

Thanks!
