### DISCUSSION TITLE
Annotation for min and max in a specific timeframe

### DISCUSSION THREAD

**Discussion by marce14git** [dbuezas/lovelace-plotly-graph-card#309] [Q&A] [answered]
I am trying to copy my apexchart graph with annotations/labels at min and max, preferably in the last 24h, or in the next 24h for the forcast 

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/92689239/7f4f960c-7808-47f1-8072-c42fd2446960)

thanks in advance

**Comment by dbuezas** [comment, marked as answer]
Hi Marce,
I don't see any simple way of doing this without using custom functions.
If you want to style the annotations, take a look at these:
* https://plotly.com/javascript/text-and-annotations/
* https://plotly.com/javascript/reference/layout/annotations/#layout-annotations


<img width="446" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/777196/379b48be-4284-43ff-83c0-887daaae5bd7">

```yaml
type: custom:plotly-graph
hours_to_show: 12

entities:
  - entity: sensor.openweathermap_temperature
    fn: |- # put this one at the end of the entity
      $ex {
        let max = {y: -Infinity};
        let min = {y: +Infinity};
        for (let i = 0; i < ys.length; i++){
          const x = xs[i];
          const y = parseFloat(ys[i]);
          if (y > max.y) max = {x, y};
          if (y < min.y) min = {x, y};
        }
        vars.min = min
        vars.max = max
      }

layout:
  annotations:
    - x: $ex vars.min.x
      y: $ex vars.min.y
      text: $ex vars.min.y.toFixed(2)
      ax: -30
      ay: -40
    - x: $ex vars.max.x
      y: $ex vars.max.y
      text: $ex vars.max.y.toFixed(2)
      ax: -30
      ay: -40
```
