### DISCUSSION TITLE
Horizontal lines / thresholds

### DISCUSSION THREAD

**Discussion by Qhilm** [dbuezas/lovelace-plotly-graph-card#311] [Q&A] [answered]
Hello,

I am trying to generate a horizontal line a y=600. The below is not drawing anything it seems, I must be missing something.

```YAML
type: custom:plotly-graph

refresh_interval: 10
title: Irradiance
hours_to_show: 48

entities:
  - entity: sensor.sun_irradiance_home
    showlegend: false
  - entity: ""
    name: closing
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: [0, Date.now()]
    y: [600,600]
```
