### DISCUSSION TITLE
Reducing time window

### DISCUSSION THREAD

**Discussion by JayMcG** [dbuezas/lovelace-plotly-graph-card#312] [Q&A]
Hi! I've created a graph to show my solar production for today vs yesterday. The graph is set to show the `current_day`, however, this isn't really practical as there is a lot of dead space - when the sun is down...

![Capture](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/17012684/66799b16-7519-4cfe-9fee-c2b9f5f7085b)

How would I only show 5am to 6pm and remove this dead space?

Thanks in advance for the assistance! 

```
type: custom:plotly-graph
hours_to_show: current_day
entities:
  - entity: sensor.pv_power
    show_value: true
    fill: tozeroy
    name: Solar Power
    line:
      width: 1
  - entity: sensor.pv_power
    name: Yesterday
    time_offset: 1d
    line:
      width: 1
      color: grey
    opacity: 0.2
  - entity: ''
    name: Now
    yaxis: y9
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: $ex [Date.now(), Date.now()]
    'y':
      - 0
      - 1
defaults:
  yaxes:
    fixedrange: true
config:
  scrollZoom: true
  displayModeBar: false
layout:
  yaxis:
    range:
      - 0
      - 5000

```
