### DISCUSSION TITLE
Non null flat line joining when no data

### DISCUSSION THREAD

**Discussion by Thlerry** [dbuezas/lovelace-plotly-graph-card#317] [Q&A] [answered]
**Describe the bug**
Graph joins non null values, instead of showing zero / null.
I had no power for several hours today between 7am and 12:30pm roughly. So I would have expected the graph to show a dip at zero during that time, but it seems plotly joins the last known value, with the first new one, even several hours apart. Is there a way to prevent this, and show the fact that there was no value during that time, and keep the graph at zero ?
See screenshot below

**Screenshots**
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/96b6f2db-fcf2-45a4-a388-9557dd90a31e)

**yaml**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.tb_house_consumption_kw
    name: Grid
    fill: tozeroy
    line:
      color: '#77aaff'
      shape: spline
    show_value: false
    extend_to_present: false
    on_legend_click: {}
    on_click: {}
    on_dblclick: {}
    filters:
      - resample: 10m
  - entity: sensor.tb_solaredge_ac_power
    name: Solar
    fill: tozeroy
    line:
      shape: spline
      color: '#ff8800'
    show_value: false
    extend_to_present: false
    on_legend_click: {}
    on_click: {}
    on_dblclick: {}
    filters:
      - resample: 10m
  - entity: sensor.tb_house_solar_only_consumption_kw
    name: Self
    fill: tozeroy
    line:
      color: '#00eeee'
      shape: spline
    show_value: false
    extend_to_present: false
    on_legend_click: {}
    on_click: {}
    on_dblclick: {}
    filters:
      - resample: 10m
hours_to_show: current_day
refresh_interval: 1
config:
  scrollZoom: false
  displayModeBar: false
  staticPlot: true
```

**Additional context**
When this happened, I had no electricity during the gap, so HA was not running at all, so nothing should have been recorded in the DB ?

**Comment by Thlerry** [comment]
In the console I see a lot of the following errors:

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/c4b47525-3ea5-47b7-b622-4c7b9f2b5cec)

**Comment by Thlerry** [comment]
I clear the console, and did a refresh and this is what I see:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/e25ee883-ba5a-4155-857c-4c1b89506576)

**Comment by Thlerry** [comment]
Not sure how to get the information you need to debug ?
Would you be able to help ?

**Comment by dbuezas** [comment]
Check out this section: https://github.com/dbuezas/lovelace-plotly-graph-card#debugging

With it you can dump the data to the console for analysis

**Comment by dbuezas** [comment]
The issue may be the resample filter

**Comment by dbuezas** [comment]
I looked at my implementation of resampling, and it should actually add a bunch of nulls, but try without it to narrow this down :)

**Comment by Thlerry** [comment]
With resampling:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/ed32ad74-d364-4e46-8bb1-dd1527e581b8)

Without Resampling:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/8d44412f-15c5-4165-8f1c-8b274c28c4b7)

**Comment by Thlerry** [comment]
here is the graph with nofill / no resampling. This looks correct.

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/02f28c4e-6404-4dd6-87d3-c1c159800198)

**Comment by Thlerry** [comment]
And this is nofill but with resampling.
So it seems one issue is with the resampling, and one issue with the fill option ?

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/034e6f36-415f-4ebb-8f61-212457f7a3f8)

**Comment by dbuezas** [comment]
I see. Maybe you can map all the null values to the number zero before resampling?

**Comment by dbuezas** [comment]
This would give a reasonable result after resampling, even if you use fill

**Comment by Thlerry** [comment]
Is there an easy way to do that, maybe with a filter ?

Would that work ?

    filters:
      - map_y_numbers: 'y == null ? 0 : y'
      - resample: 2m

**Comment by dbuezas** [comment]
Yes, 
But don't use map_y_numbers, that one will already eliminate the nulls

Use map_y instead

**Comment by Thlerry** [comment]
OK, I gave it a go, but still not working.

Here is a simplified graph with various options. Any option used in filters: seems to mess up the line / fill.

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/1347361b-6cbe-436a-b94a-eeac7164e5e1)

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/d8f3005d-4c7b-4c1d-b22b-edda72abef42)

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/5da1c3fe-9b3f-4ecd-8001-d3e0911953ca)

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/ec3c0321-2b63-4125-86e8-a52199d31ba4)

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/d63f89cf-fc93-4af1-a1d0-b4ffcda50add)

**Comment by dbuezas** [comment]
Try 
```yaml
map_y: isNaN(+y) ? 0 : y
```

Maybe y is "unavailable" or something like that.
You may want to check out the "debugging" section in the readme to see the data in the console. Way easier to debug these kinds of issues.

BTW, map_y_numbers is expected to remove nulls, since they are not numbers

**edit: fixed typo isNan => isNaN**

**Comment by Thlerry** [comment]
I am getting this error with isNan function ?

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/3e7c58bd-1311-47f5-9ae3-d4acc2a92fd4)

**Comment by Thlerry** [comment]
I think checking against null or undefined works because the graph changes.
It starts from 0  after the gap, but still links the last valid value to 0. (See below)

How do you use the debugger to check further ? I looked at the debugging section but not sure what to do in the debugger (not used to it)


![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/7c4d8cc0-32a0-46cf-af9b-c497da717cdd)

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/65353ac9-5bbb-45e3-881f-6ee6f3f03909)

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/d272a332-d80b-4f47-82fb-f527cfd7cc3b)

**Comment by Thlerry** [comment]
Were you able to reproduce it ?
You can take any sensor, stop HA for a few minutes to create a gap in values, and restart HA. Pretty easy.

**Comment by dbuezas** [comment]
just a typo, I updated my message above

**Comment by dbuezas** [comment, marked as answer]
Oh I see, you are right, it is working. So it is not that the sensor has "unavailable" datapoints, they are just missing. In this case, joining the lines is actually reasonable behaviour. What you can do is add an extra fake datapoint 
```yaml
filters:
  - fn: |- 
      ({xs, ys}) => ({
          xs: xs.flatMap((x, i) => ys[i+1] === null ? [x,x]:[x]),
          ys: ys.flatMap((y, i) => ys[i+1] === null ? [y,null]:[y])
      })
```

This will insert an extra undefined to the ys array, but set its date to that of the last known value. This should make the gap as wide as the whole missing chunk
