### DISCUSSION TITLE
Multiple graphs (grid)

### DISCUSSION THREAD

**Discussion by damiencorpataux** [dbuezas/lovelace-plotly-graph-card#318] [Q&A] [answered]
Hello,

I need to display multiple graphs and tried this https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/31.

```yaml
  grid:
    rows: 2
    columns: 1
    roworder: top to bottom
```
I thought that this would make it, but it doesn't. Can you help me ?

**Comment by dbuezas** [comment]
~I suggest you start by copying the whole yaml from #31 and then replace the entities and then start deleting unused lines one by one while looking at the results.~

**Comment by damiencorpataux** [comment]
Hmm I see: the yaml is for version < 3.0.0, because I get this kind of errors: 
```Error: at [entities.0.show_value.right_margin]: removed in v3.0.0, use `true` and set the global `time_offset` or `layout.margins.r` to make space at the right. ```

**Comment by dbuezas** [comment]
Oh I see, sorry for the confusion.

This is the code I use now for that plot
```yaml
type: custom:plotly-graph
entities:
  - entity: climate.schlafzimmer
    attribute: temperature
    yaxis: y1
    fill: tozeroy
    line:
      dash: solid
      width: 6
  - entity: sensor.bedroom_air_sensor_temperature
    yaxis: y1
  - entity: sensor.bedroom_air_sensor_temperature
    period: 5minute
    yaxis: y1
  - entity: climate.wintergarten_floor
    attribute: temperature
    yaxis: y2
    fill: tozeroy
    line:
      dash: solid
      width: 6
  - entity: climate.wintergarten_left
    attribute: temperature
    yaxis: y2
    fill: tozeroy
    line:
      dash: solid
      width: 6
  - entity: climate.wintergarten_right
    attribute: temperature
    yaxis: y2
    fill: tozeroy
    line:
      dash: solid
      width: 6
  - entity: sensor.wintergarten_thermometer_temperature
    period: 5minute
    yaxis: y2
  - entity: climate.bad
    attribute: temperature
    yaxis: y3
    fill: tozeroy
    line:
      dash: solid
      width: 6
  - entity: sensor.bathroom_thermometer_temperature
    period: 5minute
    yaxis: y3
  - entity: climate.durchgang_zimmer
    attribute: temperature
    yaxis: y4
    fill: tozeroy
    line:
      dash: solid
      width: 6
  - entity: sensor.durchgang_thermometer_temperature
    period: 5minute
    yaxis: y4
  - entity: climate.living
    attribute: temperature
    yaxis: y5
    fill: tozeroy
    line:
      dash: solid
      width: 6
  - entity: sensor.living_thermometer_temperature
    period: 5minute
    yaxis: y5
  - entity: climate.kitchen
    attribute: temperature
    yaxis: y6
    fill: tozeroy
    line:
      dash: solid
      width: 6
  - entity: sensor.kitchen_thermometer_temperature
    period: 5minute
    yaxis: y6
  - entity: sensor.flur_thermometer_temperature
    period: 5minute
    yaxis: y7
  - entity: sensor.keller_temperature
    period: 5minute
    yaxis: y7
  - entity: sensor.openweathermap_temperature
    period: 5minute
    yaxis: y8
  - entity: sensor.garden_temperature
    period: 5minute
    yaxis: y8
  - entity: sensor.outside_temperature
    period: 5minute
    yaxis: y8
  - entity: sensor.teich_temperature
    period: 5minute
    yaxis: y8
layout:
  dragmode: pan
  margin:
    t: 30
    l: 45
    r: 40
    b: 50
  showlegend: false
  height: 650
  grid:
    rows: 8
    columns: 1
    roworder: top to bottom
  annotations: null
  yaxis:
    title:
      text: Schlafz.
  yaxis2:
    title:
      text: Winterg.
  yaxis3:
    title:
      text: Bad
  yaxis4:
    title:
      text: Dürchgang
  yaxis5:
    title:
      text: Living
  yaxis6:
    title:
      text: Kitchen
  yaxis7:
    title:
      text: Rest
  yaxis8:
    title:
      text: Outside
defaults:
  entity:
    unit_of_measurement: °C
    show_value: true
    texttemplate: |
      $fn ({getFromConfig})=>
        `%{y:.1f} ${getFromConfig('.unit_of_measurement')} ${getFromConfig('.name')}`
    line:
      width: 1
  yaxes:
    fixedrange: false
    autorange: true
    side: left
    overlaying: 'y'
    visible: true
    showgrid: true
title: History
hours_to_show: 1d
refresh_interval: 10
color_scheme: 2
```

**Comment by damiencorpataux** [comment, marked as answer]
It works. Thank you !

Here is a minimal working example:
```yaml
type: custom:plotly-graph
layout:  
  grid:
    rows: 3
    columns: 1
    roworder: top to bottom
defaults:
  yaxes:
    overlaying: 'y'
    showgrid: true
    visible: true
    side: left
entities:
  - entity: sensor.air_quality_temperature_scd
    yaxis: y1
  - entity: sensor.air_quality_humidity_scd
    yaxis: y2
  - entity: sensor.air_quality_co2
    yaxis: y3
```
