### DISCUSSION TITLE
SolarEdge Photovoltaik Production and Consumption as Daily Graph

### DISCUSSION THREAD

**Discussion by citoki** [dbuezas/lovelace-plotly-graph-card#320] [Show and tell]
This is an implementation of Home Assistant Plotly graph library, to show a daily graph in a very similar way like the vendor iOS app is doing it.

| Original Vendor App | Plotly Graph Card |
|:---:|:---:|
|<img src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/7259873/5372d584-92df-4892-852e-712ee716b9f0" alt="solaredge original app picture show graph of production and consumption" width="80%" />|<img width="1400rem" alt="Plotly Custom Graph implementation" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/7259873/e9d7239d-f5ca-4fd6-b113-055fdeee91ba"/>|

```yaml
type: custom:plotly-graph
hours_to_show: 12
refresh_interval: 30
entities:
  - entity: sensor.pv_ac_power_combined_integral
    name: PV Production
    statistic: state
    period: auto
    legendgroup: 1
    filters:
      - derivate
      - store_var: pv_ac_power
    line:
      width: 1
      color: palegreen
      shape: spline
    fill: tonexty
  - entity: sensor.solaredge_m1_exported_kwh
    name: Self Consumption
    statistic: state
    legendgroup: 2
    period: auto
    fill: tozeroy
    filters:
      - derivate: h
      - map_y: parseFloat(vars.pv_ac_power.ys[i]) - parseFloat(ys[i])
      - store_var: selfcons
    line:
      width: 1
      color: dodgerblue
      shape: spline
  - entity: sensor.solaredge_m1_imported_kwh
    name: Import
    statistic: state
    legendgroup: 3
    period: auto
    filters:
      - derivate
      - map_y: '(parseFloat(y[i-1]) === parseFloat(ys[i])) ? 0 : parseFloat(vars.selfconsys[i]) + parseFloat(ys[i])'
    line:
      width: 0
      color: lightsalmon
      shape: spline
    fill: tonexty

```

Some remarks: 
- I used standard CSS colours and didn't go for specific RGBA numbers
- I use (SolarEdge Modbus Multi)[https://github.com/WillCodeForCats/solaredge-modbus-multi] integration to get SolarEdge data directly from the inverters every 10 seconds. It's needed to add RJ45 cable to the inverters, as Modbus isn't available via Wifi anymore
- since I've got two inverters running I combine the photovoltaik production with an template
- the data aggregation for the Solar Edge output API (iOS app) is 15 minutes and cannot be changed, therefore you'll see slightly different graph values

Edit: updated configuration after discussion here with some improvements

**Comment by Thlerry** [comment]
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/cf197fc2-ba31-4876-94c8-b3d685975db8) !
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/6d215fae-a036-4ec2-9151-0e60cb97074c)

Thanks for sharing. This is my version using Plotly-graph and SolarEdge modbus integration.

```
type: custom:plotly-graph
entities:
  - entity: sensor.tb_solaredge_ac_power
    name: Solar
    fill: tozeroy
    line:
      shape: spline
      color: '#ff8800'
    show_value: false
    extend_to_present: false
    on_legend_click: {}
    on_click: {}
    on_dblclick: {}
    filters:
      - fn: |-
          ({xs, ys}) => ({
              xs: xs.flatMap((x, i) => ys[i+1] === null ? [x,x]:[x]),
              ys: ys.flatMap((y, i) => ys[i+1] === null ? [y,null]:[y])
          })
      - map_y: 'y === null ? 0 : y'
      - resample: 2m
      - sliding_window_moving_average: null
      - map_y_numbers: 'y < 0 ? 0 : y'
  - entity: sensor.tb_house_consumption_kw
    name: Grid
    fill: tozeroy
    line:
      color: '#77aaff'
      shape: spline
    show_value: false
    extend_to_present: false
    on_legend_click: {}
    on_click: {}
    on_dblclick: {}
    filters:
      - fn: |-
          ({xs, ys}) => ({
              xs: xs.flatMap((x, i) => ys[i+1] === null ? [x,x]:[x]),
              ys: ys.flatMap((y, i) => ys[i+1] === null ? [y,null]:[y])
          })
      - map_y: 'y === null ? 0 : y'
      - resample: 2m
      - sliding_window_moving_average: null
      - map_y_numbers: 'y < 0 ? 0 : y'
  - entity: sensor.tb_house_solar_only_consumption_kw
    name: Self Consumption
    fill: tozeroy
    line:
      color: '#00eeee'
      shape: spline
    show_value: false
    extend_to_present: false
    on_legend_click: {}
    on_click: {}
    on_dblclick: {}
    filters:
      - fn: |-
          ({xs, ys}) => ({
              xs: xs.flatMap((x, i) => ys[i+1] === null ? [x,x]:[x]),
              ys: ys.flatMap((y, i) => ys[i+1] === null ? [y,null]:[y])
          })
      - map_y: 'y === null ? 0 : y'
      - resample: 2m
      - sliding_window_moving_average: null
      - map_y_numbers: 'y < 0 ? 0 : y'
hours_to_show: current_day
refresh_interval: 1
config:
  scrollZoom: false
  displayModeBar: false
  staticPlot: true
```

**Comment by Thlerry** [comment]
I noticed you used "fill: tonexty" in yours for 2 colors ? what does it do ?
If I use is instead of tozeroy my graph looks funny.

tonexty: on 2 colors like you
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/a5a163b0-73d2-4b36-b3fd-766f1cdb68c2)

tozeroy everywhere:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/99030879/77756953-a32d-4278-a3c6-4364e56a7386)

**Reply by citoki** [reply]
I found the values for `fill` here: <https://plotly.com/javascript/filled-area-plots/#overlaid-area-chart-without-boundary-lines>

Yes, I also had strange looking outputs when I used the `fill` property. The order of the entities in combination with the respective fill value is important. I tried several things and ended up with my example, see above. 😄 

How does your chart looks like, when Solar energy is below your consumption? That was my point to start optimising my chart. Before that I simply had my three inputs displayed. Which is hard to read when it comes to overall consumption and actual self consumption, as I only showed my export.

<img width="494" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/7259873/cdf4504b-5965-46bb-a2a5-0456c525c623">

<details><summary>old configuration</summary>

<p>

```yaml
type: custom:plotly-graph
hours_to_show: 12
refresh_interval: 30
entities:
  - entity: sensor.pv_ac_power_combined_integral
    name: PV Production
    statistic: state
    period: auto
    filters:
      - derivate
    line:
      width: 2
      color: palegreen
      shape: spline

  - entity: sensor.solaredge_m1_exported_kwh
    name: Exported
    statistic: state
    period: auto

    filters:
      - derivate: h
    line:
      width: 2
      color: dodgerblue
      shape: spline
  - entity: sensor.solaredge_m1_imported_kwh
    name: Import
    statistic: state
    period: auto
    filters:
      - derivate
    line:
      width: 2
      color: red
      shape: spline
```

</p>
</details>

**Reply by dbuezas** [reply]
`fill: tonexty` is "weird" when there is missing data (i.e unavailable values).
Since these are numeric values, you could remove them with the `force_numeric` filter.

**Reply by citoki** [reply]
@dbuezas indeed, what I just recognised is an issue for values on `sensor.solaredge_m1_imported_kwh`. When imported energy is the same value like before in the data point of this series (measurements come in as kWh and is a number like 514), the entity y-value should be set `0`.

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/7259873/e9e9e770-e9e9-41ea-b476-e34b3c16dca8)

I could fix it with that mapping for y-value :
```yaml
      - map_y: '(parseFloat(ys[i-1]) === parseFloat(ys[i])) ? 0 : parseFloat(vars.selfcons.ys[i]) + parseFloat(ys[i])'
```

<details><summary>whole entity config</summary>

<p>

```yaml
  - entity: sensor.solaredge_m1_imported_kwh
    name: Importiert
    statistic: state
    legendgroup: 3
    period: auto
    filters:
      - derivate
      - map_y: '(parseFloat(ys[i-1]) === parseFloat(ys[i])) ? 0 : parseFloat(vars.selfcons.ys[i]) + parseFloat(ys[i])'
    line:
      width: 1
      color: lightsalmon
      shape: spline
    fill: tozeroy
```

</p>

</details>


But then the result looks strange:

EDIT: `tozeroy` vs. `tonexty`

|tozeroy|tonexty|
|--|--|
|<img width="490" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/7259873/29b902dc-156b-4f4b-a5c9-4d25d5f28f3d">|<img width="488" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/7259873/843b4a1a-fe35-45fd-bcbf-e5015d7965c0">|

**Reply by dbuezas** [reply]
Yeah, if the curves cross each other then tonexty is not good.
Maybe you can use stacked area charts https://plotly.com/javascript/filled-area-plots/#stacked-area-chart to join your self generated and bought electricity.
Otherwise play with the order of the charts and only set the first one (or last one?) To tonexty

**Reply by citoki** [reply]
Good point, well the order didn't helped, as I need to set the `selfcons` variable from `sensor.solaredge_m1_exported_kwh` first, to use it in the next entity. Or is there a different approach possible?

A fast solution I found, and is totally fine for me, is to set the width of the imported entity (red), to 0 and now it doesn't show up anymore:

<img width="415" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/7259873/e9d7239d-f5ca-4fd6-b113-055fdeee91ba">


<details><summary>complete config for reference</summary>
<p>

```yaml
type: custom:plotly-graph
hours_to_show: 12
refresh_interval: 30
entities:
  - entity: sensor.pv_ac_power_combined_integral
    name: PV Production
    statistic: state
    period: auto
    legendgroup: 1
    filters:
      - derivate
      - store_var: pv_ac_power
    line:
      width: 1
      color: palegreen
      shape: spline
    fill: tonexty
  - entity: sensor.solaredge_m1_exported_kwh
    name: Self Consumption
    statistic: state
    legendgroup: 2
    period: auto
    fill: tozeroy
    filters:
      - derivate: h
      - map_y: parseFloat(vars.pv_ac_power.ys[i]) - parseFloat(ys[i])
      - store_var: selfcons
    line:
      width: 1
      color: dodgerblue
      shape: spline
  - entity: sensor.solaredge_m1_imported_kwh
    name: Import
    statistic: state
    legendgroup: 3
    period: auto
    filters:
      - derivate
      - map_y: '(parseFloat(y[i-1]) === parseFloat(ys[i])) ? 0 : parseFloat(vars.selfconsys[i]) + parseFloat(ys[i])'
    line:
      width: 0
      color: lightsalmon
      shape: spline
    fill: tonexty

```

</p>
</details>

**Reply by dbuezas** [reply]
Oh, good idea! 
For completeness, if you want to give the ordering a try just use a var to store the data and then bringbit back using load_var in a subsequent trace. That subsequent trace can have an empty string as entity (`entity: ''`).
I think I made a mistake somewhere and the order of the entities ends up being backwards in the plot, so `tonexty` actually means `to previous y`

**Reply by Thlerry** [reply]
Mine looks OK when the solar production is below consumption. It just looks the same as on the graph I posted above. The orange bit is just higher than the green. I don't have any issue with the rendering using the fill option "tozeroy".

The self consumption for me is the same as consumption, except that I zero it when there is no solar production. So they overlap completely since they are identical on the rest of the curve.

**Reply by citoki** [reply]
> if you want to give the ordering a try just use a var to store the data and then bringbit back using load_var in a subsequent trace. That subsequent trace can have an empty string as entity (`entity: ''`).

@dbuezas I got it now working with an additional entity, which is copied with the filters from `solaredge_m1_exported_kwh` and I set the property `internal: true`. That's working as well and I could set all `fill` properties to `tozeroy` and set the width back to `1` for the `solaredge_m1_imported_kwh` entity.
As from the documentation the data is fetch now for every entity and I have 4 instead of 3, hope this will not cause performance issues someday 😄 

<details><summary>updated code with internal entity for data sharing</summary>

<p>

```yaml
type: custom:plotly-graph
hours_to_show: 12
refresh_interval: 15
entities:
  - entity: sensor.pv_ac_power_combined_integral
    name: PV Produktion
    statistic: state
    period: auto
    legendgroup: 1
    filters:
      - derivate
      - store_var: pv_ac_power
    line:
      width: 1
      color: lime
      shape: spline
    fill: tozeroy
  - entity: sensor.solaredge_m1_exported_kwh
    internal: true
    statistic: state
    period: auto
    filters:
      - derivate: h
      - map_y: parseFloat(vars.pv_ac_power.ys[i]) - parseFloat(ys[i])
      - store_var: eigenverbrauch
  - entity: sensor.solaredge_m1_imported_kwh
    name: Importiert
    statistic: state
    legendgroup: 3
    period: auto
    filters:
      - derivate
      - map_y: >-
          (parseFloat(y[i-1]) === parseFloat(ys[i])) ? 0 :
          parseFloat(vars.eigenverbrauch.ys[i]) + parseFloat(ys[i])
    line:
      width: 1
      color: orangered
      shape: spline
    fill: tozeroy
  - entity: sensor.solaredge_m1_exported_kwh
    name: Eigenverbrauch
    statistic: state
    legendgroup: 1
    period: auto
    filters:
      - derivate: h
      - map_y: parseFloat(vars.pv_ac_power.ys[i]) - parseFloat(ys[i])
    line:
      width: 1
      color: dodgerblue
      shape: spline
    fill: tozeroy
    fillcolor: lightskyblue
```

</p>
</details>
