### DISCUSSION TITLE
Conditional color value

### DISCUSSION THREAD

**Discussion by greg80303** [dbuezas/lovelace-plotly-graph-card#321] [Q&A] [answered]
I have a very simple example where I'm trying to draw a static rectangle on a graph which changes its fill color based on the state of a binary sensor value.  Can someone tell me why it doesn't like the syntax?

```yaml
- entity: ''
    name: Zone1
    mode: lines
    fill: toself
    fillcolor: >
      $ex hass.states["binary_sensor.esp32_home_zone1_presence"].state === "off"
      ?
          RGBA(20,200,0,0.06) :
          RGBA(20,255,0,0.1)
```

it says:
> Error: at [entities.3.fillcolor]: RGBA is not defined

**Comment by citoki** [comment, marked as answer]
@greg80303 try to write the rgba values in single quotes

```yaml
    line:
      color: rgba(20,255,0,1)
    fill: tozeroy
    fillcolor: >
        $ex ys === "Idle" ?
          'rgba(20,200,0,0.06)' :
          'rgba(20,255,0,0.1)'
```
