### DISCUSSION TITLE
Plotting target movment from mmWave sensor

### DISCUSSION THREAD

**Discussion by comkubus7** [dbuezas/lovelace-plotly-graph-card#323] [Q&A]
Hello,Today, I had an interesting idea to display position data from an mmWave sensor for motion tracking. I currently have a basic Plotly graph working. However, I believe that using entities and storing values in variables might not be the most efficient approach, but it's what I have implemented for now. Or is there? And also, is it possible to display an icon inside the graph? An icon (for instance mdi:antenna) would be much nicer and easier than creating it over predefined data points... 😄

```
type: custom:plotly-graph
hours_to_show: 0.02
entities:
  - entity: sensor.everything_presence_lite_24ec8c_target_1_x
    fn: $fn ({ ys, vars }) => vars.targetx = ys
  - entity: sensor.everything_presence_lite_24ec8c_target_1_y
    fn: $fn ({ ys, vars }) => vars.targety = ys
  - entity: ''
    name: Target1
    x: $fn ({ vars }) => vars.targetx
    'y': $fn ({ vars }) => vars.targety
    show_value: true
    xaxis: x2
    yaxis: y1
    line:
      width: 0.75
  - entity: ""
    name: Positon of Sensor
    x: [0, 0, -300, 300]
    y: [300, 0, 0, 0]
    xaxis: x2
    yaxis: y1
    line:
      width: 2
layout:
  height: 450
  yaxis:
    fixedrange: true
    range:
      - 6000
      - 0
  xaxis2:
    type: number
    fixedrange: true
    range:
      - -4000
      - 4000
```

![Screenshot 2023-11-03 110323](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/111283691/1c7dd888-0c77-470c-91d6-4e7eeb15dbe0)
