### DISCUSSION TITLE
Daily data resets 50min before 12pm leads to broken graphs, how to filter/replace broken data

### DISCUSSION THREAD

**Discussion by tomatensaus** [dbuezas/lovelace-plotly-graph-card#328] [Q&A]
I gather data from an inverter, the inverter keeps a daily total of eg. PV production. At 23:09 the clock on the inverter reads 12pm and resets the counter to 0. I have no access to change the date on the inverter. Is there any way I can work around this data problem?  I tried to apply filters copied from other examples but the graphs still do not render correctly

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/1019233/135a8315-b592-417b-a4b1-f8b7a0c1c843)
This is the history of the sensor

At 23:10 every day all the graphs are not rendered and show 0 values (as the last hour of the day appears as 0)
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/1019233/cd4c591f-977f-4cf6-b3cb-3baa12c7aa3f)

This problem had me running in circles looking at reasons why data disappears, mean time it works perfectly, just the data source produces broken data with no way to fix it. How do I adjust the filters to discard all the small or 0 values at the end of the day? Below is my yaml copied from bits and pieces I found in other examples (with some filters I tried to fix the issue)
```
type: custom:plotly-graph
view_layout:
  grid-area: daily
entities:
  - entity: sensor.deyeinvertermaster_summary_day_pv
    statistic: state
    name: |
      $fn ({ ys,meta }) =>
        "Solar" + "🔆" + "(" +ys[ys.length - 1]+"kWh)"
    period: day
    type: bar
    texttemplate: '%{y}'
    marker:
      color: rgb(255, 155, 48)
    filters:
      - filter: i > 0 && i < (xs.length - 1)
      - fn: |
          ({ys,xs,hass}) => ({
            xs: [...xs, new Date().setHours(0,0,0)],
            ys: [...ys, hass.states['sensor.deyeinvertermaster_summary_day_pv'].state],
          })
  - entity: sensor.deyeinvertermaster_summary_day_load
    statistic: state
    name: |
      $fn ({ ys,meta }) =>
        "Load" + "⚡" + "(" +ys[ys.length - 1]+"kWh)"
    period: day
    type: bar
    texttemplate: '%{y}'
    marker:
      color: rgb(95, 182, 173)
    filters:
      - filter: i > 0 && i < (xs.length - 1)
      - fn: |
          ({ys,xs,hass}) => ({
            xs: [...xs, new Date().setHours(0,0,0)],
            ys: [...ys, hass.states['sensor.deyeinvertermaster_summary_day_load'].state],
          })
  - entity: sensor.deyeinvertermaster_summary_day_grid_importbuy
    statistic: state
    name: |
      $fn ({ ys,meta }) =>
        "Grid Import" + "💡" + "(" +ys[ys.length - 1]+"kWh)"
    period: day
    type: bar
    texttemplate: '%{y}'
    marker:
      color: rgb(84, 144, 194)
    filters:
      - filter: i>0
      - force_numeric
  - entity: sensor.deyeinvertermaster_summary_day_grid_exportsell
    statistic: state
    name: |
      $fn ({ ys,meta }) =>
        "Grid Export" + "💡" + "(" +ys[ys.length - 1]+"kWh)"
    period: day
    type: bar
    texttemplate: '%{y}'
    marker:
      color: rgb(244, 44, 94)
    filters:
      - filter: i>0
  - entity: sensor.deyeinvertermaster_summary_day_battery_discharge
    statistic: state
    name: |
      $fn ({ ys,meta }) =>
        "Battery Discharge" + "🖱️" + "(" +ys[ys.length - 1]+"kWh)"
    period: day
    type: bar
    texttemplate: '%{y}'
    marker:
      color: rgb(151, 90, 182)
    filters:
      - filter: i>0
      - force_numeric
  - entity: sensor.deyeinvertermaster_summary_day_battery_charge
    statistic: state
    name: |
      $fn ({ ys,meta }) =>
        "Battery Charge" + "🔋" + "(" +ys[ys.length - 1]+"kWh)"
    period: day
    type: bar
    texttemplate: '%{y}'
    marker:
      color: yellow
    filters:
      - filter: i>0
      - force_numeric
hours_to_show: 5d
title: Daily Performance
refresh_interval: 10
defaults:
  yaxes:
    fixedrange: true
layout:
  legend:
    bgcolor: rgba(0,0,0,0)
    itemsizing: constant
    font:
      size: 11
  height: 410
config:
  displayModeBar: false
  scrollZoom: true
```
