### DISCUSSION TITLE
How to add min / max temp per sensor data?

### DISCUSSION THREAD

**Discussion by dopeytree** [dbuezas/lovelace-plotly-graph-card#331] [General]
Hi am plotting garden & greenhouses temps against forecast. 

Would like to  add min / max data maybe at the top or somewhere.
Is this possible?

<img width="1512" alt="Screenshot 2023-11-24 at 12 06 59" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/103341262/a75dc755-4b1b-449c-a6ca-6e6d5f6f9974">

```
type: custom:plotly-graph
entities:
  - entity: sensor.1_garden_temperature
    filters:
      - sliding_window_moving_average:
          window_size: 10
          extended: false
          centered: true
  - entity: sensor.2_phonebox_temperature
    filters:
      - sliding_window_moving_average:
          window_size: 10
          extended: false
          centered: true
  - entity: sensor.3_greenhouse_temperature
    filters:
      - sliding_window_moving_average:
          window_size: 10
          extended: false
          centered: true
  - entity: sensor.openweathermap_forecast_temperature
    filters:
      - sliding_window_moving_average:
          window_size: 10
          extended: false
          centered: true
refresh_interval: 10
title: Temperature.
hours_to_show: 72
color_scheme:
  - 02a8f4
  - ff9800
  - f44336
  - ffffff
layout:
  xaxis:
    rangeselector:
      'y': 1.2
      buttons:
        - count: 1
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 7
          step: day
        - count: 30
          step: month
```
