### DISCUSSION TITLE
Analysis of electricity consumption compared with the previous year

### DISCUSSION THREAD

**Discussion by FillR2** [dbuezas/lovelace-plotly-graph-card#334] [Show and tell]
For a long time now, I've been looking for a graph that would enable me to analyze my electricity consumption, particularly in relation to the previous year.

Thanks to Plotly, I've been able to produce a graph that, while far from perfect and error-free, for the most part meets this need.

The main information is as follows:
- Hourly or daily consumption compared with the previous year
- Temperature and humidity compared with previous year
- Temperature forecast for the next days
- Last weeks rain and forecasts
- Daily hot water consumption.

Note:  **year and year-1 are offset aligned for 364 days** to compare a sunday with a sunday, a monday with a monday, 

Hourly analysis:
yesterday and today are much higher than last year (yellow bars), previous days were lower.

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86425615/a8c9fc55-aba7-47fd-81f2-a294cbba455c)

Daily analysis:

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86425615/796737d9-9880-4b34-8e20-6a137d33803b)

Yearly analysis:

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86425615/d2154192-b97d-4342-95d3-9fdee9653af1)

In détail:

Electricity consumption by hour compared to Year-1 (weekdays are aligned, I compare a monday with a monday with a time_offset: +364d

In yellow: this year consumption
In brown:: last year consumption
White line: forecast based on last year consumption

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86425615/84c484f9-d3d2-4d9a-b1db-77fad78c0af0)

Here temperature (outside in green, inside in red), humidity (blue line) for current year (plain lines) and previous years (dashed lines),  rain for this year (blue bars) and hot water consumption (red bars) are added:

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86425615/199689d2-99fe-488c-81da-f1fced515e22)

Daily consumption:

Yellow means consumption is higer than previous year

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86425615/cf7fa173-dea5-410e-ac9a-d7f34a6c674d)

As I'm not a developer, this was quite complex to create, mainly copy/paste of existing examples here and there are a lot of small errors , but here is the code:

![Plotly Electricity Analysis](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86425615/4991fd14-5222-4484-b34b-f92578054944)

![Plotly Fluidité](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86425615/cf0efbc5-ee90-440d-ad15-396ff995c99a)

```
type: custom:plotly-graph
defaults:
  entity:
    fill: tozeroy
  yaxes:
    rangemode: tozero
layout:
  barmode: overlay
  margin:
    t: 10
    r: 100
  xaxis:
    rangeselector:
      'y': 1.3
      buttons:
        - count: 1
          step: day
        - count: 7
          step: day
        - count: 14
          step: day
        - count: 1
          step: month
        - count: 3
          step: month
        - count: 6
          step: month
        - count: 16
          step: null
    centered: false
  yaxis:
    visible: true
    fixedrange: false
    autorange_after_scroll: true
    rangegmode: tozero
    rangemode: nonnegative
  yaxis2:
    visible: true
    fixedrange: true
    autorange_after_scroll: true
    rangegmode: tozero
    rangemode: nonnegative
  yaxis4:
    visible: false
    fixedrange: true
    autorange_after_scroll: true
    rangegmode: tozero
    rangemode: nonnegative
  yaxis5:
    visible: false
    fixedrange: true
    autorange_after_scroll: true
    rangegmode: tozero
    rangemode: nonnegative
  yaxis7:
    visible: false
    fixedrange: true
    autorange_after_scroll: true
    rangegmode: tozero
    rangemode: nonnegative
  yaxis9:
    visible: false
    fixedrange: true
    autorange_after_scroll: true
entities:
  - entity: ''
    yaxis: y9
    name: Aujourd'hui
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: $ex [Date.now(), Date.now()]
    'y':
      - 0
      - 1
  - entity: ''
    yaxis: y9
    name: Hier
    showlegend: false
    line:
      width: 1
      dash: dot
      color: rgb(100,100,200)
    x: $ex [Date.now()-86400000, Date.now()-86400000]
    'y':
      - 0
      - 1
  - entity: ''
    yaxis: y9
    name: Avant-hier
    showlegend: false
    line:
      width: 1
      dash: dot
      color: rgb(100,100,200)
    x: $ex [Date.now()-172800000, Date.now()-172800000]
    'y':
      - 0
      - 1
  - entity: ''
    yaxis: y9
    name: Un An
    showlegend: false
    line:
      width: 1
      dash: dot
      color: rgb(100,100,200)
    x: $ex [Date.now()- 31536000000, Date.now()- 31536000000]
    'y':
      - 0
      - 1
  - entity: sensor.humidite_station_meteo
    autorange_after_scroll: true
    yaxis: y5
    base: 0
    connectgaps: true
    statistic: mean
    line:
      shape: spline
      width: 1
      dash: none
      color: rgba(120, 120, 240, 1)
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: week
      6M: week
    time_offset: +0d
    name: Humidité
    show_value: true
    opacity: 0.4
    fill: tozeroy
    fillcolor: rgba(168, 216, 234, 0)
  - entity: sensor.humidite_station_meteo
    autorange_after_scroll: true
    yaxis: y5
    base: 0
    connectgaps: true
    statistic: mean
    line:
      shape: spline
      width: 1
      dash: dot
      color: rgba(120, 120, 240, 0.5)
    period:
      0m: hour
      25h: hour
      1M: day
      3M: week
      6M: week
    time_offset: +364d
    name: Humidité A-1
    show_value: true
    opacity: 0.4
    fill: tozeroy
    fillcolor: rgba(168, 216, 234, 0)
  - entity: sensor.temperature_station_meteo
    autorange_after_scroll: true
    yaxis: y2
    base: 0
    connectgaps: true
    statistic: mean
    line:
      shape: spline
      width: 1
      dash: dot
      color: rgba(40, 240, 40, 1)
    period:
      0m: hour
      25h: hour
      1M: day
      3M: week
      6M: month
    time_offset: +364d
    name: Température Ext. A-1
    show_value: true
    opacity: 0.4
    fill: none
    fillcolor: rgba(168, 216, 234, 0.1)
  - entity: sensor.openweathermap_temperature
    autorange_after_scroll: true
    legendgroup: 2
    yaxis: y2
    base: 0
    name: 🌡 Temperature
    internal: true
    filters:
      - store_var: temperature
    fill: none
    fillcolor: rgba(214, 39, 40,0)
    line:
      color: rgba(214, 39, 40, 0)
  - entity: weather.openweathermap
    autorange_after_scroll: true
    legendgroup: 2
    yaxis: y2
    base: 0
    showlegend: true
    show_value: true
    name: Température Ext. Prév.
    fill: none
    fillcolor: rgba(214, 39, 40, .3)
    line:
      dash: none
      shape: spline
      color: rgba(50,205,50, 1)
      width: 1
    unit_of_measurement: °C
    filters:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [vars.temperature.xs.slice(-1)[0],...meta.forecast.map(({ datetime }) => new Date(datetime))],
            ys: [vars.temperature.ys.slice(-1)[0],...meta.forecast.map(({ temperature }) => temperature)],
          })
  - entity: sensor.temperature_station_meteo
    autorange_after_scroll: true
    yaxis: y2
    base: 0
    statistic: mean
    line:
      shape: spline
      color: rgba(50,205,50, 1)
      width: 1
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: week
      6M: month
    time_offset: +0d
    name: Température Ext.
    show_value: true
    opacity: 0.4
    fill: tozeroy
    fillcolor: rgba(168, 216, 234, 0)
  - entity: sensor.temperature_interieure_climatisation_salon
    autorange_after_scroll: true
    yaxis: y2
    base: 0
    statistic: mean
    line:
      shape: spline
      color: rgba(178,34,34, 1)
      width: 1
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: week
      6M: month
    time_offset: +0d
    name: Température Int.
    show_value: true
    opacity: 1
    fill: tonexty
    fillcolor: rgba(168, 216, 234, 0.05)
  - entity: sensor.temperature_interieure_climatisation_salon
    autorange_after_scroll: true
    yaxis: y2
    statistic: mean
    base: 0
    line:
      shape: spline
      color: rgba(178,34,34, 1)
      width: 1
      dash: dot
    period:
      0m: hour
      25h: hour
      1M: day
      3M: week
      6M: month
    time_offset: +364d
    name: Température Int. A-1
    show_value: true
    opacity: 0.8
    fill: none
    fillcolor: rgba(168, 216, 234, 0.05)
  - entity: sensor.openweathermap_rain
    autorange_after_scroll: true
    base: 0
    yaxis: y7
    fillcolor: rgba(31, 119, 180,.3)
    line:
      color: rgba(31, 119, 180, 1)
    legendgroup: 1
    name: 🌧 Précipitation 1
    visible: legendonly
    show_value: true
    filters:
      - store_var: precipitation
    fill: tozeroy
  - entity: sensor.wupws_precipitation_rate
    visible: legendonly
    autorange_after_scroll: true
    base: 0
    yaxis: y7
    fillcolor: rgba(31, 119, 180,.3)
    line:
      color: rgba(31, 119, 180, 1)
    legendgroup: 4
    name: 🌧 Précipitation 2
    show_value: true
    fill: tozeroy
    unit_of_measurement: mm/h
  - entity: weather.openweathermap
    show_value: true
    autorange_after_scroll: true
    base: 0
    legendgroup: 1
    showlegend: false
    visible: legendonly
    name: Précipitation
    fill: tozeroy
    fillcolor: rgba(31, 119, 180,.1)
    line:
      color: rgba(31, 119, 180, 1)
      dash: dot
    unit_of_measurement: mm
    filters:
      - fn: |-
          ({ meta, vars }) => ({
            xs: [vars.precipitation.xs.slice(-1)[0],...meta.forecast.map(({ datetime }) => new Date(datetime))],
            ys: [vars.precipitation.ys.slice(-1)[0],...meta.forecast.map(({ precipitation }) => precipitation)],
          })
  - entity: sensor.energy_eau_chaude
    autorange_after_scroll: true
    visible: legendonly
    defaults:
      yaxes:
        fixedrange: true
    type: bar
    marker:
      color: rgba(220, 80, 80, 0.5)
    yaxis: 'y'
    base: 0
    statistic: state
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: month
      6M: month
    time_offset: +0.0d
    unit_of_measurement: kWh
    name: Consommation Eau Chaude
    texttemplate: '%{y:0.1f} kWh'
    connectgaps: false
    fill: tozeroy
    show_value: false
    filters:
      - filter: i>0
      - delta
      - filter: y<250
      - filter: y>=0
      - map_y_numbers: 'y'
  - entity: sensor.consommation_journaliere_edf
    autorange_after_scroll: true
    defaults:
      yaxes:
        fixedrange: true
    type: line
    line:
      shape: hvh
      width: 1
      dash: none
      color: rgba(200, 200, 200, 0.6)
    fill: tozeroy
    fillcolor: rgba(20,20,20, 0.4)
    yaxis: 'y'
    base: 0
    statistic: state
    period:
      0m: hour
      25h: hour
      1M: day
      3M: day
      6M: day
    time_offset: +364.0d
    unit_of_measurement: kWh
    name: Consommation A-1
    texttemplate: '%{y:0.1f} kWh'
    show_value: false
    filters:
      - filter: i>0
      - filter: y<150000
      - map_y_numbers: y / 1000
  - entity: sensor.consommation_journaliere_edf
    autorange_after_scroll: true
    defaults:
      yaxes:
        fixedrange: true
    type: bar
    marker:
      color: rgba(255, 215, 0, 0.5)
    yaxis: 'y'
    base: 0
    statistic: state
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: day
      6M: day
    time_offset: +0.0d
    unit_of_measurement: kWh
    name: Consommation Année
    texttemplate: '%{y:0.1f} kWh'
    connectgaps: false
    fill: tozeroy
    show_value: false
    filters:
      - filter: i>0
      - filter: y<150000
      - map_y_numbers: y / 1000
  - entity: sensor.consommation_edf
    visible: true
    autorange_after_scroll: true
    defaults:
      yaxes:
        fixedrange: true
    type: bar
    barmode: overlay
    marker:
      color: rgba(200, 255, 200, 0.4)
    yaxis: 'y'
    base: 0
    statistic: state
    period:
      0m: hour
      25h: hour
      1M: day
      3M: month
      6M: month
    time_offset: +364.0d
    unit_of_measurement: kWh
    name: Consommation période-1
    texttemplate: '%{y:0.1f} kWh'
    connectgaps: false
    fill: tozeroy
    show_value: false
    filters:
      - filter: i>0
      - delta
      - filter: y<15000000
      - map_y_numbers: y / 1000
  - entity: sensor.consommation_edf_hc
    internal: 'yes'
    statistic: state
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: month
      6M: month
    time_offset: +0.0d
    unit_of_measurement: kWh
    name: Consommation période HC
    filters:
      - filter: i>0
      - delta
      - filter: y<15000000
      - map_y_numbers: y / 1000
      - store_var: hc
  - entity: sensor.consommation_edf_hc
    internal: 'yes'
    statistic: state
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: month
      6M: month
    time_offset: +364.0d
    unit_of_measurement: kWh
    filters:
      - filter: i>0
      - delta
      - filter: y<15000000
      - map_y_numbers: y / 1000
      - store_var: hc1
  - entity: sensor.consommation_edf_hp
    internal: 'yes'
    statistic: state
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: month
      6M: month
    time_offset: +0.0d
    unit_of_measurement: kWh
    filters:
      - filter: i>0
      - delta
      - filter: y<15000000
      - map_y_numbers: y / 1000
      - store_var: hp
  - entity: sensor.consommation_edf_hp
    internal: 'yes'
    statistic: state
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: month
      6M: month
    time_offset: +364.0d
    unit_of_measurement: kWh
    filters:
      - filter: i>0
      - delta
      - filter: y<15000000
      - map_y_numbers: y / 1000
      - store_var: hp1
  - entity: sensor.consommation_edf_hp
    visible: true
    autorange_after_scroll: true
    defaults:
      yaxes:
        fixedrange: true
    type: bar
    barmode: overlay
    marker:
      color: rgba(255, 255, 255, 0.4)
    yaxis: 'y'
    base: 0
    statistic: state
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: month
      6M: month
    time_offset: +0.0d
    unit_of_measurement: kWh
    name: Consommation période
    texttemplate: '%{y:0.3f} kWh'
    connectgaps: false
    fill: tozeroy
    show_value: false
    filters:
      - map_y_numbers: vars.hp.ys[i-2] + vars.hc.ys[i-2]
  - entity: sensor.consommation_edf_hc
    visible: legendonly
    autorange_after_scroll: true
    defaults:
      yaxes:
        fixedrange: true
    type: bar
    barmode: overlay
    marker:
      color: rgba(255, 255, 100, 0.4)
    yaxis: 'y'
    base: 0
    statistic: state
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: month
      6M: month
    time_offset: +0.0d
    unit_of_measurement: kWh
    name: Consommation période HC
    texttemplate: '%{y:0.3f} kWh'
    connectgaps: false
    fill: tozeroy
    show_value: false
    filters:
      - map_y_numbers: vars.hc.ys[i-2]
  - entity: sensor.consommation_edf_hp
    visible: legendonly
    autorange_after_scroll: true
    defaults:
      yaxes:
        fixedrange: true
    type: bar
    barmode: overlay
    marker:
      color: rgba(255, 100, 255, 0.4)
    yaxis: 'y'
    base: 0
    statistic: state
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: month
      6M: month
    time_offset: +0.0d
    unit_of_measurement: kWh
    name: Consommation période HP
    texttemplate: '%{y:0.3f} kWh'
    connectgaps: false
    fill: tozeroy
    show_value: false
    filters:
      - map_y_numbers: vars.hp.ys[i-2]
  - entity: sensor.consommation_edf_hp
    visible: legendonly
    autorange_after_scroll: true
    defaults:
      yaxes:
        fixedrange: true
    type: bar
    barmode: overlay
    marker:
      color: rgba(255, 255, 255, 0.4)
    yaxis: y4
    base: 0
    statistic: state
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: month
      6M: month
    time_offset: +364.0d
    unit_of_measurement: €
    name: Prix euro avec Conso A-1
    texttemplate: '%{y:0.2f} €'
    connectgaps: false
    fill: tozeroy
    show_value: false
    filters:
      - filter: i>0
      - delta
      - map_y_numbers: |
          { 
            let KWHHP = vars.hp1.ys[i];
            let EDFHP = 0.184;
            if (x>=new Date("2023-02-01")) EDFHP = 0.223;
            if (x>=new Date("2023-08-01")) EDFHP = 0.246;
            if (x>=new Date("2024-02-01")) EDFHP = 0.246 * 1.1;
            return KWHHP * EDFHP;
          }
      - map_y_numbers: |
          { let KWHHC = vars.hc1.ys[i];
            let EDFHC = 0.147;
            if (x>=new Date("2023-02-01")) EDFHC = 0.161;
            if (x>=new Date("2023-08-01")) EDFHC = 0.1828;
            if (x>=new Date("2024-02-01")) EDFHC = 0.1828 * 1.1;
            let PRIXEDFHC = KWHHC * EDFHC;
            return y + PRIXEDFHC;
          }
      - map_y_numbers: |
          { let abonnement = 19.97;
            let prix = y
            if (x>=new Date("2023-02-01")) abonnement = 19.97;
            if (x>=new Date("2023-08-01")) abonnement = 19.97;
            if (x>=new Date("2024-02-01")) abonnement = 19.97 * 1.1;
            if (vars.hp1.ys[i] + vars.hc1.ys[i] >= 450) prix = y + abonnement;
            return prix;
          }
  - entity: sensor.consommation_edf_hp
    visible: legendonly
    autorange_after_scroll: true
    defaults:
      yaxes:
        fixedrange: true
    type: bar
    barmode: overlay
    marker:
      color: rgba(255, 255, 255, 0.4)
    yaxis: y4
    base: 0
    statistic: state
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: month
      6M: month
    time_offset: +0.0d
    unit_of_measurement: €
    name: Prix euro
    texttemplate: '%{y:0.2f} €'
    connectgaps: false
    fill: tozeroy
    show_value: false
    filters:
      - filter: i>0
      - delta
      - map_y_numbers: |
          { 
            let KWHHP = vars.hp.ys[i];
            let EDFHP = 0.184;
            if (x>=new Date("2023-02-01")) EDFHP = 0.223;
            if (x>=new Date("2023-08-01")) EDFHP = 0.246;
            return KWHHP * EDFHP;
          }
      - map_y_numbers: |
          { let KWHHC = vars.hc.ys[i];
            let EDFHC = 0.147;
            if (x>=new Date("2023-02-01")) EDFHC = 0.161;
            if (x>=new Date("2023-08-01")) EDFHC = 0.1828;
            let PRIXEDFHC = KWHHC * EDFHC;
            return y + PRIXEDFHC;
          }
      - map_y_numbers: |
          { let abonnement = 19.97;
            let prix = y
            if (x>=new Date("2023-02-01")) abonnement = 19.97;
            if (x>=new Date("2023-08-01")) abonnement = 19.97;
            if (vars.hp.ys[i] + vars.hc.ys[i] >= 450) prix = y + abonnement;
            return prix;
          }
  - entity: sensor.consommation_edf_hp
    visible: legendonly
    autorange_after_scroll: true
    defaults:
      yaxes:
        fixedrange: true
    type: bar
    barmode: overlay
    marker:
      color: rgba(255, 255, 100, 0.4)
    yaxis: y4
    base: 0
    statistic: state
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: month
      6M: month
    time_offset: +0.0d
    unit_of_measurement: €
    name: Prix euro Base
    texttemplate: '%{y:0.2f} €'
    connectgaps: false
    fill: tozeroy
    show_value: false
    filters:
      - filter: i>0
      - delta
      - map_y_numbers: |
          { 
            let KWHHP = vars.hp.ys[i];
            let EDFHP = 0.174;
            if (x>=new Date("2023-02-01")) EDFHP = 0.206;
            if (x>=new Date("2023-08-01")) EDFHP = 0.2276;
            return KWHHP * EDFHP;
          }
      - map_y_numbers: |
          { let KWHHC = vars.hc.ys[i];
            let EDFHC = 0.174;
            if (x>=new Date("2023-02-01")) EDFHC = 0.206;
            if (x>=new Date("2023-08-01")) EDFHC = 0.2276;
            let PRIXEDFHC = KWHHC * EDFHC;
            return y + PRIXEDFHC;
          }
      - map_y_numbers: |
          { let abonnement = 18.89;
            let prix = y
            if (x>=new Date("2023-02-01")) abonnement = 18.89;
            if (x>=new Date("2023-08-01")) abonnement = 18.89;
            if (vars.hp.ys[i] + vars.hc.ys[i] >= 450) prix = y + abonnement;
            return prix;
          }
  - entity: sensor.consommation_edf_hp
    visible: legendonly
    autorange_after_scroll: true
    defaults:
      yaxes:
        fixedrange: true
    type: bar
    barmode: overlay
    marker:
      color: rgba(255, 255, 255, 0.4)
    yaxis: y4
    base: 0
    statistic: state
    period:
      0m: 5minute
      25h: hour
      1M: day
      3M: month
      6M: month
    time_offset: +0.0d
    unit_of_measurement: €
    name: Prix euro 2021
    texttemplate: '%{y:0.2f} €'
    connectgaps: false
    fill: tozeroy
    show_value: false
    filters:
      - filter: i>0
      - delta
      - map_y_numbers: |
          { 
            let KWHHP = vars.hp.ys[i];
            let EDFHP = 0.1853;
            return KWHHP * EDFHP;
          }
      - map_y_numbers: |
          { let KWHHC = vars.hc.ys[i];
            let EDFHC = 0.1353;
            let PRIXEDFHC = KWHHC * EDFHC;
            return y + PRIXEDFHC;
          }
      - map_y_numbers: |
          { let abonnement = 16.88;
            let prix = y
            if (vars.hp.ys[i] + vars.hc.ys[i] >= 450) prix = y + abonnement;
            return prix;
          }
autorange_after_scroll: true
hours_to_show: 168
time_offset: 1d
refresh_interval: 1800

```

**Comment by dbuezas** [comment]
Very cool!
You may be interested in [grouped legend](https://plotly.com/javascript/legend/#grouped-legend)

**Reply by dbuezas** [reply]
Also in using time_offset to make space for the values at the end of the traces: https://github.com/dbuezas/lovelace-plotly-graph-card#show_value

**Comment by dbuezas** [comment]
By the way, this is exactly why I created this integration: to maximise customisation to the extent that I am surprised myself of the things people come out with. It makes me very happy seeing it put to good use :)

**Reply by FillR2** [reply]
Hi @dbuezas 

I'm not a developer, is there a way to create a constant based on the date ?

My goal is to calculate the electricity price based on the past dates, I want to setup a constant that will be:

0,147 before 01/02/2023
0,161 starting at 01/02/2023
0,1828 starting at 01/08/2023

This constant is the kWh price that I will use to multiply with kWh to get past prices. Any help will be appreciated :-)

**Reply by dbuezas** [reply]
You can use a `map_y` filter:
```yaml
type: custom:plotly-graph
hours_to_show: 1y
entities:
  - entity: sensor.the_kwh_sensor
    period: day
    filters:
      - map_y: |
          { 
            let price = 0.147;
            if (x>new Date("2023-02-01")) price = 0.161;
            if (x>new Date("2023-08-01")) price = 0.1828;
            return y * price;
          }

```

For the future, you may want to look into energy price entities, you may even be able to update past prices and then load that as an extra entity, use resample and do the computation by ys index.

Congratulations, you are now a developer :)
