### DISCUSSION TITLE
Generating monthly summaries of data, data that starts in middle of month will have no graph

### DISCUSSION THREAD

**Discussion by tomatensaus** [dbuezas/lovelace-plotly-graph-card#338] [Q&A]
I am trying to generate monthly graphs using a running total of data that gets reset on a daily basis.

The graph does not show unless the recording starts at the 1st of the month. Is there any way to render data even though the month is incomplete. Below is an example where there is plenty data for November (last month) but the data started recording after the 1st.

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/1019233/1ad84081-9b4d-4509-ac80-6a511bc9b8b0)

This is the data
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/1019233/6647c3b6-b8c8-49d8-ad99-100d56ff86a4)

This data is also recorded as a full total that increases every day with no resets. If this makes it easier to use, then I would switch the graph to use this data. just mentioning it in case this makes the problem easier to solve
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/1019233/4f468f86-f812-4d83-9daa-7616f617e805)

```
type: custom:plotly-graph
entities:
  - entity: sensor.deyeinvertermaster_summary_day_pv
    statistic: sum
    name: |
      $fn ({ ys,meta }) =>
        "Solar" + "🔆"
    period: month
    type: bar
    texttemplate: '%{y}'
    extend_to_present: true
    width: $fn() => 1000*60*60*24*6
    offset: $fn() => 1000*60*60*24*1
    filters:
      - delta
    marker:
      color: rgb(255, 155, 48)
  - entity: sensor.deyeinvertermaster_summary_day_load
    statistic: sum
    name: |
      $fn ({ ys,meta }) =>
        "Load" + "⚡"
    period: month
    type: bar
    width: $fn() => 1000*60*60*24*6
    offset: $fn() => 1000*60*60*24*8
    extend_to_present: true
    filters:
      - delta
    texttemplate: '%{y}'
    marker:
      color: rgb(95, 182, 173)
  - entity: sensor.deyeinvertermaster_summary_day_grid_importbuy
    statistic: sum
    name: |
      $fn ({ ys,meta }) =>
        "Grid Import" + "💡"
    period: month
    type: bar
    texttemplate: '%{y}'
    width: $fn() => 1000*60*60*24*6
    offset: $fn() => 1000*60*60*24*15
    extend_to_present: true
    filters:
      - delta
    marker:
      color: rgb(84, 144, 194)
  - entity: sensor.deyeinvertermaster_summary_day_battery_discharge
    statistic: sum
    name: |
      $fn ({ ys,meta }) =>
        "Battery Discharge" + "🖱️"
    period: month
    type: bar
    texttemplate: '%{y}'
    width: $fn() => 1000*60*60*24*6
    offset: $fn() => 1000*60*60*24*22
    extend_to_present: true
    filters:
      - delta
    marker:
      color: rgb(151, 90, 182)
  - entity: sensor.deyeinvertermaster_summary_day_battery_charge
    statistic: sum
    name: |
      $fn ({ ys,meta }) =>
        "Battery Charge" + "🔋"
    period: month
    type: bar
    texttemplate: '%{y}'
    extend_to_present: true
    width: $fn() => 1000*60*60*24*6
    offset: $fn() => 1000*60*60*24*29
    filters:
      - delta
    marker:
      color: yellow
hours_to_show: 6M
title: Monthly Production
refresh_interval: 600
defaults:
  yaxes:
    fixedrange: true
layout:
  legend:
    bgcolor: rgba(0,0,0,0)
    itemsizing: constant
    font:
      size: 11
  height: 410
config:
  displayModeBar: false
  scrollZoom: false
time_offset: 1M
```

I was hoping that the extend to present would fix that scenario.
I need a way to present the data even though it is not complete
