### DISCUSSION TITLE
Zoom Level of Detail sampling

### DISCUSSION THREAD

**Discussion by Chavife** [dbuezas/lovelace-plotly-graph-card#341] [Q&A] [answered]
Hi,
I would like to ask if it is possible to have the same level of detail throughout the zoom range.
My issue is that when my plot is way out of zoom, it is hard to read and I would like to have the same LoD/Smoothing/Sampling (not sure how to achieve the best result) on all zoom levels.

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/18663896/a0a8ae1b-59d4-4197-8930-d4867ebfac34)
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/18663896/a4786823-d361-4fc5-95ae-5a494e504c25)

```
type: custom:plotly-graph
entities:
  - entity: sensor.temperature_humidity_sensor_a048_temperature
    legendgroup: 1
    showlegend: false
    show_value: false
    yaxis: y1
    statistic: max
    line:
      width: 0
  - entity: sensor.temperature_humidity_sensor_a048_temperature
    legendgroup: 1
    showlegend: false
    show_value: false
    yaxis: y1
    statistic: min
    fill: tonexty
    fillcolor: rgba(191, 44, 44, 0.2)
    line:
      width: 0
  - entity: sensor.temperature_humidity_sensor_a048_temperature
    name: Bedroom
    legendgroup: 1
    yaxis: y1
    statistic: mean
    line:
      color: rgb(191, 44, 44)
  - entity: sensor.temperature_humidity_sensor_a048_humidity
    legendgroup: 1
    showlegend: false
    show_value: false
    yaxis: y2
    statistic: max
    line:
      width: 0
  - entity: sensor.temperature_humidity_sensor_a048_humidity
    legendgroup: 1
    showlegend: false
    show_value: false
    yaxis: y2
    statistic: min
    fill: tonexty
    fillcolor: rgba(120, 149, 178, 0.2)
    line:
      width: 0
  - entity: sensor.temperature_humidity_sensor_a048_humidity
    showlegend: false
    legendgroup: 1
    yaxis: y2
    statistic: mean
    line:
      color: rgb(120, 149, 178)
layout:
  dragmode: pan
  margin:
    l: 50
    r: 50
  showlegend: true
  height: 250
  legend:
    x: 0
    'y': 1
    bgcolor: rgba(0,0,0,0)
    orientation: v
    itemsizing: constant
    font:
      size: 10
  yaxis:
    title:
      text: Temperature
  yaxis2:
    title:
      text: Humidity
defaults:
  entity:
    line:
      width: 2
      shape: spline
      smoothing: 1.3
    show_value: true
  yaxes:
    fixedrange: true
title: Climate
hours_to_show: 24
refresh_interval: 10
```
