### DISCUSSION TITLE
Scatter with double histogram

### DISCUSSION THREAD

**Discussion by dbuezas** [dbuezas/lovelace-plotly-graph-card#342] [Show and tell]
![Screenshot_20231209-225514](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/777196/5001e11c-564e-4298-b226-3ccc0ddafcff)

![IMG-20231227-WA0003](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/777196/06068617-3b1c-43b1-be76-825639cd0f35)

```yaml
title: 2D Histogram - Last 10 days
entities:
  - entity: sensor.openweathermap_pressure
    period: hour
    internal: true
    fn: $fn ({ xs, ys, vars }) => { vars.pressure = ys; vars.xs = xs; }
  - entity: sensor.openweathermap_temperature
    period: hour
    internal: true
    fn: $fn ({ ys, vars }) => vars.temperature = ys
  - entity: sensor.openweathermap_humidity
    period: hour
    internal: true
    fn: $fn ({ ys, vars }) => vars.humidity = ys
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': $fn ({ vars }) => vars.pressure
    y2: $fn ({ vars }) => vars.humidity
    type: histogram2dcontour
    mode: lines+markers
    line:
      color: null
hours_to_show: 240
raw_plotly_config: true
ha_theme: true
layout:
  margin:
    t: 10
    l: 70
    r: 0
    b: 70
  height: 500
  zaxis:
    title:
      text: Humidity
  yaxis:
    title:
      text: Pressure
  xaxis:
    title:
      text: Temperature
    autorange: true
```

**Comment by jandechent** [comment]
Hmm, im on 3.3.4, installed via HACS, but the histograms at the border do not show at all.

**Reply by dbuezas** [reply]
This is what I have in my card:
```yaml
type: custom:plotly-graph
title: 2D Histogram - Last 10 days
entities:
  - entity: sensor.openweathermap_temperature
    period: hour
    internal: true
    fn: $fn ({ ys, vars }) => vars.temperature = ys
  - entity: sensor.openweathermap_humidity
    period: hour
    internal: true
    fn: $fn ({ ys, vars }) => vars.humidity = ys
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': $fn ({ vars }) => vars.humidity
    mode: markers
    name: points
    marker:
      color: rgb(102,0,0)
      size: 2
      opacity: 0.4
    type: scatter
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': $fn ({ vars }) => vars.humidity
    name: density
    ncontours: 20
    colorscale: Hot
    reversescale: true
    showscale: false
    line:
      color: null
    type: histogram2dcontour
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': undefined
    name: x density
    marker:
      color: rgb(219,91,40)
    yaxis: y2
    opacity: 1
    type: histogram
  - entity: ''
    x: undefined
    'y': $fn ({ vars }) => vars.humidity
    name: y density
    marker:
      color: rgb(219,91,40)
    xaxis: x2
    type: histogram
hours_to_show: 240
raw_plotly_config: true
layout:
  margin:
    t: 10
    l: 70
    r: 0
    b: 70
  height: 400
  bargap: 0.1
  showlegend: false
  xaxis:
    title:
      text: Temperature
    autorange: true
    domain:
      - 0
      - 0.85
    showgrid: false
    zeroline: false
  yaxis:
    title:
      text: Humidity
    domain:
      - 0
      - 0.85
    showgrid: false
    zeroline: false
  xaxis2:
    domain:
      - 0.85
      - 1
    showgrid: false
    zeroline: false
  yaxis2:
    domain:
      - 0.85
      - 1
    showgrid: false
    zeroline: false

```

**Reply by jandechent** [reply]
Ah yes, that brings me forward. Thanks!

**Comment by matthew73210** [comment]
Hey, sorry if its pur ignorance. Is there anyway to make the card wider? Mine is stuck like the following :
I want it to be wider but if i use the param width: xxx it's gets larger in the card but the card stays put so you loose visual 

<img width="502" alt="Screenshot 2024-08-09 at 12 06 31 PM" src="https://github.com/user-attachments/assets/a1a84380-ac52-4707-8028-7e704a420bbc">

<img width="502" alt="Screenshot 2024-08-09 at 12 08 34 PM" src="https://github.com/user-attachments/assets/bc4e5f84-56ba-4dc1-a77c-5486ef406448">

```
type: custom:plotly-graph
title: 2D Histogram - Last 10 days
entities:
  - entity: sensor.a4_c1_38_c0_99_79_9979_temperature
    period: hour
    internal: true
    fn: $fn ({ ys, vars }) => vars.temperature = ys
  - entity: sensor.a4_c1_38_c0_99_79_9979_humidity
    period: hour
    internal: true
    fn: $fn ({ ys, vars }) => vars.humidity = ys
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': $fn ({ vars }) => vars.humidity
    mode: markers
    name: points
    marker:
      color: rgb(102,0,0)
      size: 2
      opacity: 0.4
    type: scatter
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': $fn ({ vars }) => vars.humidity
    name: density
    ncontours: 20
    colorscale: Hot
    reversescale: true
    showscale: false
    line:
      color: null
    type: histogram2dcontour
  - entity: ''
    x: $fn ({ vars }) => vars.temperature
    'y': undefined
    name: x density
    marker:
      color: rgb(219,91,40)
    yaxis: y2
    opacity: 1
    type: histogram
  - entity: ''
    x: undefined
    'y': $fn ({ vars }) => vars.humidity
    name: y density
    marker:
      color: rgb(219,91,40)
    xaxis: x2
    type: histogram
hours_to_show: 240
raw_plotly_config: true
layout:
  margin:
    t: 10
    l: 40
    r: 20
    b: 40
  height: 400
  bargap: 0.2
  showlegend: false
  xaxis:
    title:
      text: Temperature
    autorange: true
    domain:
      - 0
      - 0.85
    showgrid: false
    zeroline: false
  yaxis:
    title:
      text: Humidity
    domain:
      - 0
      - 0.85
    showgrid: false
    zeroline: false
  xaxis2:
    domain:
      - 0.85
      - 1
    showgrid: false
    zeroline: false
  yaxis2:
    domain:
      - 0.85
      - 1
    showgrid: false
    zeroline: false

```
