### DISCUSSION TITLE
Compare current data with historical data over a period of time (e.g. today with yesterday, same day previous year)

### DISCUSSION THREAD

**Discussion by Steph-74** [dbuezas/lovelace-plotly-graph-card#349] [Q&A]
Hi,
my use case is as foloows: I would like to compare my electricity consumption from today with data from the past in order to see, how certain changes (i.e. installation of photovoltaics, replacing the ICE with a BEV ... and next year the heat pump) affect the electricity consumption. To get the electricity consumption I add/substract a couple of entities. With the help of plotly and some discussions here I actually came petty far:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/43385535/1c7e117c-d579-4caf-8bee-76d55933bef6)
I will focus now on the self-consumption, as getting the overall electricity consumption is only on more entity to add.  The above chart is generated with following coding:

```yaml
type: custom:plotly-graph
title: Eigenverbrauch
hours_to_show: current_day
config:
  displayModeBar: false
layout:
  dragmode: false
  legend:
    orientation: h
    itemsizing: constant
    font:
      size: 8
  xaxis:
    visible: true
    fixedrange: true
  yaxis:
    visible: true
    fixedrange: true
    rangemode: tozero
    title: Wh
  yaxis9:
    visible: false
    fixedrange: true
entities:
  - entity: sensor.total_battery_energy_charged
    internal: true
    statistic: sum
    period: 5minute
    filters:
      - derivate
      - integrate: null
      - store_var: to_battery
  - entity: sensor.total_battery_energy_discharged
    internal: true
    statistic: sum
    period: 5minute
    filters:
      - derivate
      - integrate: null
      - store_var: from_battery
  - entity: sensor.smart_meter_ts_65a_3_energy_real_produced
    internal: true
    statistic: sum
    period: 5minute
    filters:
      - derivate
      - integrate: null
      - store_var: to_grid
  - entity: sensor.wattpilot_totally_charged
    internal: true
    statistic: sum
    period: 5minute
    filters:
      - derivate
      - integrate: null
      - store_var: to_car
  - entity: sensor.total_photovoltaics_energy
    name: heute
    statistic: sum
    period: 5minute
    filters:
      - derivate
      - integrate: null
      - map_y: >-
          parseFloat(ys[i]) - parseFloat(vars.to_grid.ys[i]) -
          parseFloat(vars.to_battery.ys[i]) +
          parseFloat(vars.from_battery.ys[i]) - parseFloat(vars.to_car.ys[i])
    line:
      color: rgba(255, 0, 0, 1)
      width: 2
      shape: spline
    show_value: true
    texttemplate: <b> %{y:.0f} Wh</b>
    hovertemplate: |
      <i>Heute</i><br>
      <i>%{x}</i><br>
      <b>%{y:.0f} Wh</b>
      <extra></extra>
  - entity: sensor.total_battery_energy_charged
    internal: true
    statistic: sum
    period: 5minute
    time_offset: +1d
    filters:
      - derivate
      - integrate: null
      - store_var: to_battery_1
  - entity: sensor.total_battery_energy_discharged
    internal: true
    statistic: sum
    period: 5minute
    time_offset: +1d
    filters:
      - derivate
      - integrate: null
      - store_var: from_battery_1
  - entity: sensor.smart_meter_ts_65a_3_energy_real_produced
    internal: true
    statistic: sum
    period: 5minute
    time_offset: +1d
    filters:
      - derivate
      - integrate: null
      - store_var: to_grid_1
  - entity: sensor.wattpilot_totally_charged
    internal: true
    statistic: sum
    period: 5minute
    time_offset: +1d
    filters:
      - derivate
      - integrate: null
      - store_var: to_car_1
  - entity: sensor.total_photovoltaics_energy
    internal: true
    statistic: sum
    period: 5minute
    time_offset: +1d
    filters:
      - derivate
      - integrate: null
      - store_var: prod_1
  - entity: ''
    name: '-1 Tag'
    time_offset: +1d
    filters:
      - load_var: prod_1
      - map_y: >-
          parseFloat(vars.from_battery_1.ys[i]) + parseFloat(vars.prod_1.ys[i])
          -  parseFloat(vars.to_battery_1.ys[i]) -
          parseFloat(vars.to_grid_1.ys[i]) - parseFloat(vars.to_car_1.ys[i])
    line:
      color: rgba(52, 152, 219, .5)
      width: 1
      shape: spline
    show_value: true
    texttemplate: ' %{y:.0f} Wh'
    hovertemplate: |
      <i>Gestern</i><br>
      <b>%{y:.0f} Wh</b>
      <extra></extra>
  - entity: sensor.total_battery_energy_charged
    internal: true
    statistic: sum
    filters:
      - derivate
      - integrate:
          reset_every: 1d
      - store_var: to_battery_7
    time_offset: +7d
  - entity: sensor.total_battery_energy_discharged
    internal: true
    statistic: sum
    filters:
      - derivate
      - integrate:
          reset_every: 1d
      - store_var: from_battery_7
    time_offset: +7d
  - entity: sensor.smart_meter_ts_65a_3_energy_real_produced
    internal: true
    statistic: sum
    filters:
      - derivate
      - integrate:
          reset_every: 1d
      - store_var: to_grid_7
    time_offset: +7d
  - entity: sensor.wattpilot_totally_charged
    internal: true
    statistic: sum
    filters:
      - derivate
      - integrate:
          reset_every: 1d
      - store_var: to_car_7
    time_offset: +7d
  - entity: sensor.total_photovoltaics_energy
    internal: true
    statistic: sum
    filters:
      - derivate
      - integrate:
          reset_every: 1d
      - store_var: prod_7
    time_offset: +7d
  - entity: ''
    name: '-7 Tage'
    time_offset: +7d
    filters:
      - load_var: prod_7
      - map_y: >-
          parseFloat(vars.from_battery_7.ys[i]) + parseFloat(vars.prod_7.ys[i])
          -        parseFloat(vars.to_battery_7.ys[i]) - 
          parseFloat(vars.to_grid_7.ys[i]) - parseFloat(vars.to_car_7.ys[i])
    line:
      color: rgba(155, 89, 182, .5)
      width: 1
      shape: spline
    show_value: true
    texttemplate: ' %{y:.0f} Wh'
    hovertemplate: |
      <i>letzte Woche</i><br>
      <b>%{y:.0f} Wh</b>
      <extra></extra>
  - entity: ''
    name: Now
    yaxis: y9
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: $fn () => [Date.now(), Date.now()]
    'y': $fn () => [0,1]
```
As I dug into the source data (SQLite and Statisics Card), I discovered that I need to select the last record from the previous day in order to get the starting point for the sum correct. Therfore I need a function, but all my trials failed.

... apart from that, the vars data in the debuger also looks a bit wired - but compared to my intial [post](https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/289#discussioncomment-7970167) concerning this I can now recreate the number plotly is calculating and think, it might be related as I do not have the correct starting point:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/43385535/04c20273-ed00-4275-8a9c-5932ea1f2505)

I highly appreciate any help to get this correct ... thanks in advance.

**Comment by dbuezas** [comment]
Hey @Steph-74 !
That's a cool use case, I see you're diving deep into this card 💪

I can't test this right now, but I have some suspicions:

1. I see you are applying derivative and integration to all entities before storing them in variables. That shouldn't be necessary and it creates a `NaN` value at the beginning. This `NaN` occurs because the derivative is `(current_value - previous_value)/time_difference`, and for the first element, `previous_value` is `undefined`. Just remove those from the filters list and leave the `store_var`
2. The second NaN should be because you also use the derivate and integrate with daily reset trick, so it will be hard to get rid off. Maybe you could add a small global time_offset so the card fetches a bit of data from the previous day, this way you get an extra value in the past that can be safely discarded.
3. Another option is to use the `state` statistic (instead of `sum`) and then using `integrate` without derivating first.
4. If the data is still wrong, try searching for `reset` in the discussions and issues, there may be a custom filter there that works without having to derivate. 

Let me know how it goes!

If nothing works we can try creating a custom filter together, I'm on my phone so it will need a couple of tries. 

PS: I think I got a donation from you, thank you! I'll put it to good use in a mixture of beer and supporting other projects :)

**Reply by Steph-74** [reply]
Hi @dbuezas ,
just playing around with your points lets me think, that there might be a way to achieve it without using integrate & derivate at all. But lets go into it step by step:

- to 1.: Yep, logical ... doing it one time at the end instead of on each entity might also be a plus on the performance side
- to 2.: I added a global time_offset: -1s ... seems like it did the trick, the starting point stored int the vars is now correct. Checking this after implementing the change in (1.) is also a good idea, as the value from the plain values from the db will be written into the vars ;)
- to 3.: Does unfortunately not work out for me, as the states are reset from time to time in the ha db. Somtimes, I know the reason for it (i.e. electricity meter gets replaced for the sop of the photovoltaics) - sometimes I do not have a clue why ha reset the state to 0. The sum can be corrected with ha standard developer tools ...
- to 4.: ... this pointed me into a completely different direction, as the derivate/integrate is only a kind of workaround. I stumbeld accross a discussion with the "delta" filter and fiddled around with it, at least in the debugger.

When using the delta filter I get follwing data in the debugger:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/43385535/19c0cc4f-7e85-41df-a089-f1b75a9eae84)

I was wondering know, if this data can be used to draw the chart by ...
- ... a standard chart in plotly ==> Did not find any
- ... building a function to sum the y up again, either before writing it to the vars or before drawing the chart
- (... integrate this values again)

I think, I will also have an issue with the starting point, but I will look deeper into this next year - today is rather busy sorting out & closing 2023 in a good way.

PS: As I am from Bavaria I tried to convert the unit "Cup of coffee" into "Mass of beer", ignoring the volume parameter - I ended up with "Halbe" ;) ... have fun and a good start into 2024

**Reply by Steph-74** [reply]
cumulative sum ... this was the expression missing when writing the answer: Isn't there a possibility to draw a chart showing the cumulative sum of y?

**Reply by dbuezas** [reply]
Oh I had forgotten I added a delta filter, I probably forgot to document it.
To accumulate values yourself, you can use the fn filter
```yaml
- fn: |
    ({ys}) => {
      let acc = 0;
      return { ys: ys.map(y => acc += y) }
    }
```
But the starting point will change when you scroll around.
You could reset the acc variable when the day changes by looking into the contents of xs, but you'll have to get a bit deeper into programming.

If you have something specific in mind let me know and I'll help you, but try to be as specific as you can.

Have a good start of the year!

Ps: wo zu willst du Maß als Einheit nutzen?! Ist es nicht einfach ein halber Liter? Also eine halbe ist ein viertel Liter, oder? Ohhh deswegen, das ist auch ungefähr one cup 😂

**Reply by Steph-74** [reply]
Happy New Year .

After playing around with plotly my thougts where ambivalent, if the line chart is the way to go as I will always have issues with selecting the correct records from the history database. As my goal is to compare the development, e.g. of my self-consumption, over time I decided to stick to the line chart - minor differences due to not getting the starting point correct do not conflict with my overall goal for the line chart. As I want to compare also monthly and yearly developments, I spend some time to clean up the history database (i.e. consolidating 4 history sensors in HA for electricity from grid into 1) with some rather nasty UPDATE SQL statements - only to ran into the next challenge: I have energy meter data for a couple of years in the history database, but our photovoltaics has only been up and running since Jan, 23rd, 2023.  

The chart for our overall consumption shall look someting like this (mockup):
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/43385535/68967aba-5fba-4f36-bf26-27f6eb7c9284)


Currently, I am using the following coding to draw the chart to compare the monthly overall energy consumption:

```yaml
type: custom:plotly-graph
title: Monatswerte
hours_to_show: current_month
config:
  displayModeBar: false
layout:
  dragmode: false
  legend:
    orientation: h
    itemsizing: constant
    font:
      size: 8
  xaxis:
    visible: true
    fixedrange: true
  yaxis:
    visible: true
    fixedrange: true
    rangemode: tozero
    title: kWh
  yaxis9:
    visible: false
    fixedrange: true
entities:
  - entity: sensor.total_battery_energy_discharged
    internal: true
    statistic: sum
    time_offset: +1y
    filters:
      - delta
      - fn: |
          ({ys}) => {
            let acc = 0;
            return { ys: ys.map(y => acc += y) }
          }
      - resample: 1h
      - store_var: from_battery_1y
  - entity: sensor.total_battery_energy_charged
    internal: true
    statistic: sum
    time_offset: +1y
    filters:
      - delta
      - fn: |
          ({ys}) => {
            let acc = 0;
            return { ys: ys.map(y => acc += y) }
          }
      - resample: 1h
      - store_var: to_battery_1y
  - entity: sensor.last_meter_production_am_brundl_xx
    internal: true
    statistic: sum
    time_offset: +1y
    filters:
      - delta
      - fn: |
          ({ys}) => {
            let acc = 0;
            return { ys: ys.map(y => acc += y) }
          }
      - multiply: 1000
      - resample: 1h
      - store_var: to_grid_1y
  - entity: sensor.last_meter_consumption_am_brundl_xx
    internal: true
    statistic: sum
    time_offset: +1y
    filters:
      - delta
      - fn: |
          ({ys}) => {
            let acc = 0;
            return { ys: ys.map(y => acc += y) }
          }
      - multiply: 1000
      - resample: 1h
      - store_var: from_grid_1y
  - entity: sensor.total_photovoltaics_energy
    internal: true
    statistic: sum
    time_offset: +1y
    filters:
      - delta
      - fn: |
          ({ys}) => {
            let acc = 0;
            return { ys: ys.map(y => acc += y) }
          }
      - resample: 1h
      - store_var: pv_prod_1y
  - entity: ''
    name: Vorjahresmonat
    time_offset: +1y
    filters:
      - load_var: from_grid_1y
      - map_y: >-
          parseFloat(vars.from_grid_1y.ys[i]) +
          parseFloat(vars.pv_prod_1y.ys[i]) +
          parseFloat(vars.from_battery_1y.ys[i]) - 
          parseFloat(vars.to_battery_1y.ys[i]) -
          parseFloat(vars.to_grid_1y.ys[i]) 
      - multiply: 0.001
    line:
      color: rgba(155, 89, 182, .5)
      width: 1
      shape: spline
    show_value: true
    texttemplate: ' %{y:.1f} kWh'
    hovertemplate: |
      <i>Vorjahresmonat</i><br>
      <b>%{y:.2f} kWh</b>
      <extra></extra>
  - entity: ''
    name: Now
    yaxis: y9
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: $fn () => [Date.now(), Date.now()]
    'y': $fn () => [0,1]
```
Result is follwoing chart (current month is hidden in order to see the purple line for the prev. Jan; the purple line ends on Jan 8th, although I have grid consumption for the whole month):
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/43385535/1e8356e8-de5a-4046-bf57-ce9bb5899d92)

After looking to the coding, especially the map_y part in the last entity and the data in the array it become pretty clear for me that this will not work and the solution is beyond my skills:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/43385535/2b013872-0081-47d5-8623-ed96e7d5dcbe)

I tried to do the following:
1. Storing only the delta in the vars of each entity ==> I managed to do that
2. Doing the +/- in the empty entity not based on [i], but on [xs] to sum up the data accordint the timestamp ==> ... here i failed
3. Building the cummulative sum in the empty entity after each [xs] to have the correct data for next timestamp

I also tried to build the same amount of xs in the trace, but did not find any setting to do that - this would allow to reuse the existing filters ... but now I am struggling to combine the "map_y" in 3 with the cummulative sum, that is an fn ... :(

Is there a way to achieve this?
