### DISCUSSION TITLE
Prevent x axis ticks repeating?

### DISCUSSION THREAD

**Discussion by droidgren** [dbuezas/lovelace-plotly-graph-card#351] [Show and tell]
How can make the x axis ticks only show  under the series data, so that the ticks does not repeat?
![Screenshot_20240104-121256](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/354317/ad2a4a61-0321-4985-99fe-475b8c29eaa7)

Thanks!

**Comment by dbuezas** [comment]
That's odd, what's the yaml?

**Reply by droidgren** [reply]
```
type: custom:plotly-graph
title: Förbrukning per dag
entities:
  - entity: sensor.manadens_forbrukning_ovrigt
    name: Övrigt
    unit_of_measurement: kWh
    texttemplate: ' %{y:.0f}'
    type: bar
    statistic: sum
    period: day
    filters:
      - delta
    marker:
      color: '#E74C3C'
hours_to_show: 1w
refresh_interval: 10
autorange_after_scroll: true
layout:
  xaxis:
    nticks: 8
    tickformat: '%a'
    tickangle: -45
    hoverformat: '%B %Y'
    autorange: true
```

**Reply by dbuezas** [reply]
Remove `nticks: 8` under xaxis

**Reply by droidgren** [reply]
But then I got too few ticks... 
![Screenshot_20240105-085640](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/354317/59a9da5e-3729-40ae-b871-357bc76bdfc0)

**Reply by dbuezas** [reply]
I would have expected plotly to use a reasonable amount of ticks.
Here's a trick for you to try:

```yaml
layout:
  xaxis:
    nticks: $ex Math.ceil((+get("visible_range")[1] - get("visible_range")[0]) / 1000 / 60 / 60 / 24)
```

This may work
