### DISCUSSION TITLE
Align to y-xaxis to the same x-axis

### DISCUSSION THREAD

**Discussion by droidgren** [dbuezas/lovelace-plotly-graph-card#354] [Show and tell]
Hi, 
Is it possible somehow to adjust so that the second y axis (temperature) align to the same x axis as (kWh) ? 
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/354317/f197177e-dff8-49f7-b3fd-82234c10a854)

```
type: custom:plotly-graph
title: Daily heatproduction
entities:
  - entity: sensor.elpatron_raknare
    name: Addtional power
    texttemplate: ' %{y:.0f}'
    type: bar
    statistic: state
    period: day
  - entity: sensor.dagens_forbrukning_varmepump
    name: Heat pump
    texttemplate: ' %{y:.0f}'
    type: bar
    statistic: state
    period: day
  - entity: sensor.genomsnittlig_utomhus_temp_detta_dygn
    name: Avg temp
    texttemplate: ' %{y:.0f}'
    type: bar
    period: day
hours_to_show: 1w
refresh_interval: 10

```

**Comment by dbuezas** [comment]
Hi there!
To align the ticks use:
```yaml
layout:
  yaxis2:
    overlaying: y
    zeroline: false
    tickmode: sync
```

**Comment by dbuezas** [comment]
Oh, you mean match the yaxes?
This seems relevant, but I haven't looked into it: https://github.com/VictorBezak/Plotly_Multi-Axes_Gridlines

**Reply by droidgren** [reply]
In this case I found it better to actually to use a stacked graph ( since temperatures can go negative), than going multi-axes.

However, when scrolling the bars are resizing in width, do you know how force them using the same width (or any way to prevent this)?

![2024-01-16-07-41-34](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/354317/9e2aab5f-bf93-4a81-8785-c17f267cf6ad)

```
type: custom:plotly-graph
title: Daglig värmeproduktion
entities:
  - entity: sensor.elpatron_raknare
    name: Elpatron
    texttemplate: ' %{y:.0f}'
    type: bar
    statistic: state
    period: day
    hovertemplate: >-
      <span style="text-align: center; font-size: 17px;">%{y:.1f}
      ºC</span><br>%{x}<extra></extra>  
  - entity: sensor.dagens_forbrukning_varmepump
    name: Värmepump
    texttemplate: ' %{y:.0f}'
    type: bar
    statistic: state
    period: day
    hovertemplate: >-
      <span style="text-align: center; font-size: 17px;">%{y:.1f}
      ºC</span><br>%{x}<extra></extra>      
  - entity: sensor.nibe_164445_40004
    name: Genomsnittstemp
    statistic: mean
    texttemplate: ' %{y:.0f}'
    hovertemplate: >-
      <span style="text-align: center; font-size: 17px;">%{y:.1f}
      ºC</span><br>%{x}<extra></extra>      
    type: bar
    period: day
hours_to_show: 4d
refresh_interval: 10
autorange_after_scroll: true
layout:
  height: 550
  xaxis:
    tickformat: '%a<br>%d/%m'
    tickangle: 0
    autorange: true
    hoverformat: '%d %B %Y'
    nticks: 5
  yaxis2:
    autorange: true
    griddash: dot
    side: left
    overlaying: false
    visible: true
    showgrid: true
  grid:
    rows: 2
    columns: 1
    roworder: top to bottom
defaults:
  yaxes:
    fixedrange: true
```
