### DISCUSSION TITLE
How to add a reference line?

### DISCUSSION THREAD

**Discussion by jazzmonger** [dbuezas/lovelace-plotly-graph-card#357] [Q&A] [answered]
I'd like to add a dotted reference line so I can see if graphs fall above or below a specific value.  How might I do this?

**Comment by dbuezas** [comment, marked as answer]
Like the "Now line" https://github.com/dbuezas/lovelace-plotly-graph-card?tab=readme-ov-file#now-line but horizontal in the other axis.

## Option 1

The line spreads as wide as is currently visible:

```yaml
  - entity: ""
    name: Theshold of 15
    yaxis: y
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: "$ex get('visible_range')"
    y: [15,15]
```

## Option 2

The line spreads as wide as another entity

```yaml
  - entity: sensor.the_other_entity
    filters:
      - store_var: other_entity
  - entity: ""
    name: Theshold
    yaxis: y
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: 
      - "$ex vars.other_entity.xs.at(0)"
      - "$ex vars.other_entity.xs.at(-1)"
    y: [15,15]
```
