### DISCUSSION TITLE
Outdoor temperature with blue/red depending on temperature

### DISCUSSION THREAD

**Discussion by wormiedk** [dbuezas/lovelace-plotly-graph-card#358] [Show and tell]
![Screenshot 2024-01-19 at 10 05 31](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/4417857/c3a7ad34-4098-4837-b7fa-df1c8a85f1ef)

```
type: custom:plotly-graph
autorange_after_scroll: true
entities:
  - entity: sensor.temperature_ude
    statistic: mean
    period: auto
    yaxis: y1
    name: Ude
    fill: tozeroy
    line:
      width: 0
      color: ff2222
    filters:
      - map_y: 'y > 0 ? y : 0'
    showlegend: false
  - entity: sensor.temperature_ude
    yaxis: y1
    name: Ude
    statistic: mean
    period: auto
    fill: tozeroy
    line:
      width: 0
      color: 2222bb
    filters:
      - map_y: 'y <= 0 ? y : 0'
    showlegend: false
hours_to_show: 24h
layout:
  height: 400
  xaxis:
    rangeselector:
      'y': 1.01
      buttons:
        - count: 1
          step: day
        - count: 2
          step: day
        - count: 7
          step: day
        - count: 14
          step: day
        - count: 1
          step: month        
        - count: 6
          step: month        
        - count: 1
          step: year        
  yaxis1:
    fixedrange: true

```
