### DISCUSSION TITLE
texttemplate - display a calculated extra entity value

### DISCUSSION THREAD

**Discussion by gregmc2023** [dbuezas/lovelace-plotly-graph-card#359] [Q&A] [answered]
Sorry for the noob question, but how do you reference "y" in a customdata expression?

I'm trying to display a second value in the texttemplate which is a function of the "y" value.
In this example I've graphed the energy delivered by my Wattpilot EV charger.  I also wish to display the percentage of the car's 80kWh battery this represents.  
I've tried following the example config for customdata--but get an error when I attempt to use "y" in the expression.  (Also tried storing the value in vars, but get a similar error.)

```
type: custom:plotly-graph
entities:
  - entity: sensor.wattpilot_totally_charged
    statistic: sum
    period: 5minute
    showlegend: false
    filters:
      - map_y_numbers: (y - ys[0])/1000
    name: Energy added
    unit_of_measurement: ' '
    show_value: true
    customdata: |
      $fn ({statistics}) => 
        statistics.map( () => ({ extra_attr: (y / 80) }) )
    texttemplate: <b> %{y:.1f} kWh</b> <br> 
      %{customdata.extra_attr}
hours_to_show: 168
layout:
  height: 250
  margin:
    r: 200
    l: 40
    t: 50
```

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/126954848/d8933f05-95b2-4724-803b-6f048c74cc63)

**Comment by dbuezas** [comment]
Try with this:
```yaml
customdata: |
      $fn ({statistics}) => { 
        console.log(statistics); // look at the chrome devtools console
        return statistics.map(({mean}) => ({ extra_attr: (mean / 80) }) )
      }
```

**Comment by gregmc2023** [comment]
Thanks for your prompt reply!

If I use that code I get "NaN".  But I suspect you're giving me a nudge in the direction of the answer, however, I'm still not sure what to do with it and haven't managed to google any useful hints.  

In chrome dev tools console I can see the html produced by plotly, but don't I need to get the value from HA?  

Would I be right to assume that customdata is not returning a number, as `extra_attr: (mean / 80)` displays "NaN" and `extra_attr: (mean)` displays "%{customdata.extra_attr}"?

Sorry, I'm still completely lost.

**Comment by dbuezas** [comment]
```yaml
customdata: |
      $ex ys.map(y => ({ extra_attr: y / 80 }) )
```
Would be the shortest way to do it.

**Reply by gregmc2023** [reply]
```
customdata: |
      $ex ys.map(y => ({ extra_attr: y }) )
```
displays 0, but at least that's a number. 🙂

**Comment by dbuezas** [comment]
https://github.com/dbuezas/lovelace-plotly-graph-card?tab=readme-ov-file#debugging may help you debugging in the future 💪

**Reply by gregmc2023** [reply]
Thank you!  That gives me something to work with, so I'll see if I can figure out the next step.

**Comment by gregmc2023** [comment, marked as answer]
Well, I don't understand why, in customdata, `y` returned the first value rather than the last value, but `ys[ys.length - 1]` did the trick.
Here's where I ended up:

```
type: custom:plotly-graph
entities:
  - entity: sensor.wattpilot_totally_charged
    statistic: sum
    period: 5minute
    showlegend: false
    filters:
      - map_y_numbers: (y - ys[0])/1000
    name: Energy added
    unit_of_measurement: ' '
    show_value: true
    customdata: |
      $ex ys.map(y => ({ extra_attr: ys[ys.length - 1]/80 * 100 }) )
    texttemplate: <b> %{y:.1f} kWh</b> <br> %{customdata.extra_attr:.0f} %
hours_to_show: 168
layout:
  height: 250
  margin:
    r: 200
    l: 40
    t: 50
```

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/126954848/66d7c5d0-e8b5-451c-9665-6c5e6e67d8cb)

Thanks again for your help, and for bringing plotly-graph to us! 🙂

**Reply by dbuezas** [reply]
That's odd... Did you try:
`$ex ys.map(y => ({ extra_attr: y/80 * 100 }) )`?

**Reply by gregmc2023** [reply]
Yeah, it seems weird to me that `$ex ys.map(y => ({ extra_attr: y }) )` seems to return the first value in the series, ie zero.

Here it is:
```
type: custom:plotly-graph
entities:
  - entity: sensor.wattpilot_totally_charged
    statistic: sum
    period: 5minute
    showlegend: false
    filters:
      - map_y_numbers: (y - ys[0])/1000
    name: Energy added
    unit_of_measurement: ' '
    show_value: true
    customdata: |
      $ex ys.map(y => ({ extra_attr: y }) )
    texttemplate: <b> %{y:.1f} kWh</b> <br> %{customdata.extra_attr:.2f} 
hours_to_show: 168
layout:
  height: 250
  margin:
    r: 200
    l: 40
    t: 50
```

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/126954848/84661b9e-eac1-44c8-b4eb-3f1120dc1278)

Now, `sensor.wattpilot_totally_charged` has a state_class `total_increasing`, so if I delete the filter:
```
type: custom:plotly-graph
entities:
  - entity: sensor.wattpilot_totally_charged
    statistic: sum
    period: 5minute
    showlegend: false

    name: Energy added
    unit_of_measurement: ' '
    show_value: true
    customdata: |
      $ex ys.map(y => ({ extra_attr: y }) )
    texttemplate: <b> %{y:.1f} kWh</b> <br> %{customdata.extra_attr:.2f} 
hours_to_show: 168
layout:
  height: 250
  margin:
    r: 200
    l: 40
    t: 50
```
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/126954848/66cd2a88-f818-4e61-91a1-fdded3f3d328)
