### DISCUSSION TITLE
Precision in the name (value)

### DISCUSSION THREAD

**Discussion by luissimoes** [dbuezas/lovelace-plotly-graph-card#361] [Q&A] [answered]
I have looked but can’t find an answer.
I changed the name of a graph using the usual rules ($ex …) and it shows up… but the value has about 20 decimals…!)
I read the function round could do the job… but how to apply it in the name?

the code part
```yaml
- entity: sensor.bitshake_smartmeterreader_mt681_total_in
    period: hour
    statistic: state
    type: bar
    marker:
      color: '#ff33c7'
    filters:
      - delta
    name: |
      $ex "Hourly"  + " " + "(" + ys.at(-1) +")KWh" 
```
<img width="834" alt="Energy Graphs – Home Assistant jpeg" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/8a3b5fb5-622e-4c79-bf21-3987bcb95718">

Thanks!

**Comment by dbuezas** [comment, marked as answer]
Hi!
Try: `ys.at(-1).toFixed(2)`

**Reply by luissimoes** [reply]
Man!!! you are really amazing.
Blitz quick to support us… and it *works*!!!!

Thanks

**Reply by dbuezas** [reply]
Yeppie! :)

**Comment by r-jean-pierre** [comment]
Hi!

Me again :-)
First of all I know to do it in python but not with custom:plotly-graph, so how can I use the trick ```name: |$ex ``` to hack the legend text, while not using it in hover trace name:

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/9286cf6a-8ccd-46dc-b7b8-dac672017218)

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/d6d43417-daf4-4ab4-9660-44533f2235b8)

the ```hovertemplate``` can change the right part of the trace text in hover, but not the left name. This one seems to be linked to ```name```.
Any trick to mimic ```fig.for_each_trace``` ?

**Reply by dbuezas** [reply]
Maybe try changing `hovertemplate`
[It defaults](https://github.com/dbuezas/lovelace-plotly-graph-card/blob/master/src/parse-config/defaults.ts#L34) to 
```js
`<b>${getFromConfig(".name")}</b><br><i>%{x}</i><br>%{y} ${getFromConfig(
      ".unit_of_measurement"
    )}<extra></extra>`
```

So you could override it like this
```yaml
hovertemplate: |
   $ex `<b>TheNameToShowInTheHover</b><br><i>%{x}</i><br>%{y} ${getFromConfig(
      ".unit_of_measurement"
    )}<extra></extra>`


Although for xunified hovermode you may need hoverformat instead https://plotly.com/javascript/reference/scatter/#scatter-hovertext

**Reply by r-jean-pierre** [reply]
It works!
I think I saw the trick: ```$ex```, you're a genius!
I put ```$ex `<b>Curr</b>: %{y:.1f}${getFromConfig(".unit_of_measurement")}<extra></extra>```
and got:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/b09a3aec-01c2-47ab-9840-ebd18aaac151)

Hope it will help other people

**Reply by dbuezas** [reply]
Cool! Was it hovertemplate or another parameter?

**Reply by r-jean-pierre** [reply]
a simple hovertemplate, but the real trick was to put $ex. It seems much more low level than without

full minial code is:

```
- entity: 'sensor.[[sensor_name]]_current_temperature'
  statistic: mean
  period: 5minute
  yaxis: y1
  name: |
    $ex 'Curr ' + ys.at(-1).toFixed(1) + '°C'
  hovertemplate: |
    $ex `<b>Curr</b>: %{y:.1f}${getFromConfig(".unit_of_measurement")}<extra></extra>`
  line:
    width: 1.5
    color: #1F77B4
```
