### DISCUSSION TITLE
Any way to write last values in the card? (not as legend)

### DISCUSSION THREAD

**Discussion by luissimoes** [dbuezas/lovelace-plotly-graph-card#364] [Q&A] [answered]
is there any way to write the values like in the picture (fig 1 - ApexChart)? 
what I have is what is in Fig 2

many thanks!

<img width="477" alt="Screenshot 2024-01-24 at 12 02 21" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/5438b93d-3cd0-4b2d-994a-8a849af6f621">
<img width="477" alt="Screenshot 2024-01-24 at 12 04 41" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/bce207b6-b6ab-4450-b073-b769b6d0b690">

**Comment by dbuezas** [comment, marked as answer]
Yes,
```yaml
- type: custom:plotly-graph
        entities:
          - entity: sensor.openweathermap_temperature
            period: hour
            fn: >-
              $fn ({ys, vars}) => {vars.is = ys[ys.length-1];vars.was =
              ys[ys.length-2];}
          - entity: ''
            type: indicator
            mode: number+delta
            docs: >-
              https://plotly.com/javascript/reference/indicator/#indicator-number
            value: $fn ({ vars }) => vars.is
            bgcolor: black
            title:
              text: Temperature
            number:
              suffix: °
              valueformat: '0.1'
            delta:
              position: top
              suffix: /h
              reference: $fn ({ vars }) => vars.was
              valueformat: '0.1'
            domain:
              x:
                - 0
                - 0.3
              'y':
                - 0.5
                - 1
        hours_to_show: 24
        layout:
          margin:
            t: 30
```
See:
* https://plotly.com/javascript/indicator/
* https://gist.github.com/dbuezas/92210c8fcaf8d86d6c2d358e9d83b52d#file-dashboard-yaml-example-yaml-L231
* https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/309
