### DISCUSSION TITLE
Statistic - week vs day - inconsistent results

### DISCUSSION THREAD

**Discussion by luissimoes** [dbuezas/lovelace-plotly-graph-card#366] [Q&A] [answered]
I have an increasing energy sensor - I derived other sensors from it to get the daily, weekly and monthly total (they reset at the specific points)

In case 1 (figure1), I am using the statistic sum over a period of 1d and filter by delta
In case 2 (figure 2) I am using the statistic sum over a period of 1W and filter by delta.

case1: If I add the values for the day to get the weekly value I get eg for the first week 72.9 and 79,5 for the week after.
case 2: the weekly values are different (less)

Why are they different? why is this not the same and what has to be set

Figure 1
<img width="511" alt="Screenshot 2024-01-28 at 17 00 22" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/bc176c23-f149-4116-9293-89f11e807bf3">

Figure 2
<img width="511" alt="Screenshot 2024-01-28 at 17 00 10" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/28c2899c-ded3-4657-bd15-386fd25441a5">

Code (relevant part)
```yaml
  - entity: sensor.bitshake_smartmeterreader_mt681_total_in
    texttemplate: '%{y:.2f}'
    name: consumed
    type: bar
    statistic: sum
    period: day
    filters:
      - filter: i>0
      - delta
      - fn: |
          ({ys,xs,hass, vars}) => ({
            xs: [...xs, new Date().setHours(0,0,0)],
            ys: [...ys, hass.states['sensor.from_netz_daily'].state],
          })
```

Appreciate the insights !!!!

Luis
