### DISCUSSION TITLE
$fn inside fn in filter (syntax - don't know how)

### DISCUSSION THREAD

**Discussion by luissimoes** [dbuezas/lovelace-plotly-graph-card#368] [Q&A] [answered]
I know (thanks to David) how to have indicators.... but now I have in a filter section the following:
```yaml
   filters:
    - filter: i < xs.length - 1
      - delta
      - fn: |
          ({ys,xs,hass}) => ({
            xs: [...xs, new Date().setHours(0,0,0)],
            ys: [...ys, hass.states['sensor.from_netz_daily'].state],
          })

```
To have the indicator I need to have a line like this for the *last* value i.e. the now that is in the -fn in the filter
```yaml
     fn: $fn ({ys, vars}) => {vars.solar = ys.at(-1);}
```

How do I put this in the section?
```yaml
      - fn: |
          ({ys,xs,hass, vars}) => ({
            xs: [...xs, new Date().setHours(0,0,0)],
            ys: [...ys, hass.states['sensor.from_netz_daily'].state],
            **_vars: [??????  ]_**
          })
```
______

I have a workaround, which is to create an entity that is internal only and then use the fn for the value... ie I am basically duplicating the input stream.... 
but may be there is a more elegant or better solution

thanks

**Comment by dbuezas** [comment]
Hi again!
Try this:
```yaml
- fn: |
          ({ys,xs,hass, vars}) => {
              vars.solar = ys.at(-1);
              return {
                xs: [...xs, new Date().setHours(0,0,0)],
                ys: [...ys, hass.states['sensor.from_netz_daily'].state],
              }
          })
```

Although if you need the `hass.states['sensor.from_netz_daily'].state` just use it wherever you were about to use the var.
Beware that if you have `refresh_interval: auto`, the plot won't auto update unless you use `entity: sensor.from_netz_daily` somewhere.

**Reply by luissimoes** [reply]
Hi David,
many thanks again.
I had tried something similar and it didn't work (see the screenshots...) **- that's why I asked if there is a solution to have it **inside** the block where we have the new added point calculated**

1) with the "internal" sensors that just collect the info for the sole purpose of displayed the indicator (the values are correct i.e. 
- 32.53 and 35.11)

2) with the alternative proposed (btw: I removed the last ')' ... ) 
- the indicator (for the pink value "consumed" shows the at(-1) i.e. from previous week (74...) ... *not* the last point of the graph --> that's why I thought about bringing it "inside" the calculation.... but don't know how\

S-Shot1
<img width="558" alt="Screenshot 2024-01-31 at 14 44 15" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/19983e93-7332-4b6c-9f32-f73601229808">

S-Shot2
<img width="558" alt="Screenshot 2024-01-31 at 14 55 36" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/5e34e301-faa6-43bb-880e-ce08f562bd75">

**Reply by dbuezas** [reply, marked as answer]
Right, I think you missed my comment at the end of the last answer:
> Although if you need the hass.states['sensor.from_netz_daily'].state just use it wherever you were about to use the var.
Beware that if you have refresh_interval: auto, the plot won't auto update unless you use entity: sensor.from_netz_daily somewhere.

That means: don't use a var inside the indicator. Instead, set `entity: sensor.from_netz_daily` and use`value: $ex ys.at(-1)`.

If this doesn't solve it, please post your full yaml inside a code block
````
```yaml
type: custom:plotly-graph
entities:
  - entity: blah
```
````

**Reply by luissimoes** [reply]
Right!!!!! 
and then there was light! :-)

So... I did read but "read" something completely different.... (I was using hass.states['sensor.from_netz_daily'].state)...

Just to be sure - here is what I did:
- I still do use an **additional** entity, which is also called sensor.from_netz_daily.. 
- it is **still type Indicator** -
- the value is set with $ex 

=> this worked.... is this why you meant? (It was only clear to me when you spelled it all in the last post :-)... sorry!)


Last Q:
is this better than to create this?
In the sense, that is more efficient? I suppose so, because now I have only 2 entities (one the "real one) and the other the "indicator", as in the alternative I have 3....

Or its the same?

`  - entity: sensor.to_netz_weekly
    internal: true
    fn: $fn ({ys, vars}) => {vars.sold = ys.at(-1);}
`

thanks!!!!

**Reply by dbuezas** [reply]
Haha, no problem. It often happens that text only makes sense on the second read :) 

> => this worked.... is this why you meant? (setting value directly using `$ex ys.at(-1)`

yes!

> is this better than to create this? (another internal entity)

Oh, a perfectionist! 🚀  Yes, that's better. Performance wise you won't be able to measure the difference, but it makes sense to have an entity and use it directly, it makes little sense to fetch it in an internal one just to use it in another one (except if you are composing multiple entities into one trace).

Feel free to post your entire yaml and I can tell you if there's any extra trick to clean it up even more

**Reply by luissimoes** [reply]
man you are really good! thanks for the offer.... :-)
here is what I have
(the graph looks like this, but I am looking for making the "sold" values (blue) as negative values stacked to the other ones
--> thought about adding a filter that multiplies the y-values by -1)... again wondering if this efficient or of there is a better way)

<img width="502" alt="Screenshot 2024-02-01 at 11 21 58" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/7e6e6ff1-31be-4c68-a01b-6bef182006b2">

**Reply by dbuezas** [reply]
Sure, no problem. I'll take a look after work.
btw, please fix the code block using the format I wrote down here https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/368#discussioncomment-8321379

**Reply by luissimoes** [reply]
Damn!.... I used the 'code' icon in the answer.... (the one like this <>....)...
sorry then! here it is

```yaml
type: custom:plotly-graph
layout:
  margin:
    t: 25
  height: 400
  legend:
    'y': -0.25
    x: 0.15
  modebar:
    displayModeBar: false
  xaxis:
    fixedrange: false
    gridcolor: rgba(238,235,235,0.6)
    showgrid: false
    tickformat: |-
      %d %b
      %Y
  yaxis:
    fixedrange: true
    linecolor: rgba(238,235,235,0.5)
    gridcolor: rgba(238,235,235,0.6)
    title:
      font:
        size: 9
      text: kWh
entities:
  - entity: sensor.from_netz_daily
    texttemplate: '%{y:.2f}'
    name: from netz
    type: bar
    statistic: sum
    period: week
    marker:
      color: '#cd0797'
      opacity: 0.7
    filters:
      - delta
      - filter: i < xs.length - 1
      - fn: |
          ({ys,xs,hass, vars}) => ({
            xs: [...xs, new Date().setHours(0,0,0)],
            ys: [...ys, hass.states['sensor.from_netz_weekly'].state],
          })
  - entity: sensor.to_netz_daily
    texttemplate: '%{y:.2f}'
    name: Sold
    type: bar
    statistic: sum
    period: week
    marker:
      color: '#3361FF'
      opacity: 0.7
    filters:
      - delta
      - filter: i < xs.length - 1
      - fn: |
          ({ys,xs,hass, vars}) => ({
            xs: [...xs, new Date().setHours(0,0,0)],
            ys: [...ys, hass.states['sensor.to_netz_weekly'].state],
          })
  - entity: sensor.from_netz_weekly
    type: indicator
    mode: number
    value: $ex ys.at(-1)
    bgcolor: black
    title:
      text: From netz
      font:
        size: 8
    number:
      suffix: ' W'
      valueformat: '0.11'
      font:
        size: 14
        color: '#ff33c7'
    domain:
      x:
        - 0.9
        - 1
      'y':
        - 0.9999
        - 1
  - entity: sensor.to_netz_weekly
    type: indicator
    mode: number
    value: $ex ys.at(-1)
    bgcolor: black
    title:
      text: Sold
      font:
        size: 8
    number:
      suffix: ' W'
      valueformat: '0.11'
      font:
        size: 14
        color: '#3361FF'
    domain:
      x:
        - 0
        - 0.2
      'y':
        - 0.999
        - 1
refresh_interval: 10
hours_to_show: 672
title: Haushalt weekly
view_layout:
  grid-area: group1
```

**Reply by dbuezas** [reply]
To align the bar plot you could try:
```yaml
filters:
      - delta
      - fn: |
          ({ys,xs,hass, vars}) => ({
            xs: [...xs, new Date().setHours(0,0,0)],
            ys: [...ys, hass.states['sensor.to_netz_weekly'].state],
          })
      - resample: 1w 
```

Then set refresh_inteval to auto
```yaml
refresh_interval: auto
```

and use days here:
```yaml
hours_to_show: 28d
```

**Reply by luissimoes** [reply]
Hi David, first many, many thanks for your help.
I am fighting this :-)... but it seems not an easy thing... seems one of those things that when you pull on one side, tears something on the other side...
Not sure why this is such a complicated thing for a graph, or I am doing something very wrong (but the basic case is really basic)

I am at loss....

In steps and all explained in one post (the case and alternatives)

Originally the target is very easy (I think)
- get a daily sensor and sum it over a week
- present it in a bar graph
- the current week shows the "running" total

### 1) doing it simply as mentioned
(code 1, fig 1)
--> **problem: the "current" week is not updated**

### 2) Alternative suggested (thanks! is clever!  ;-)
suppress the last day and add the points manually
(code 2, fig 2)
--> results are correct but **there is a gap in the x graph that looks bad and is misleading** 


### 3) Alternative to the problem 
add resample (and remove the adding of the last value)
(code 3, fig 3)
--> **problem: the dates in the x axis are completely off** (the resample goes back from "today" I think

(leaving in the suppression of the last value brings even stranger (and more wrong values)
(fig4)


Code 1
```
entities:
  - entity: sensor.from_netz_daily
    texttemplate: '%{y:.2f}'
    textfont:
      size: 14
    name: from netz
    type: bar
    statistic: sum
    period: week
    marker:
      color: '#cd0797'
      opacity: 0.9
    filters:
      - delta
  - entity: sensor.to_netz_daily
    texttemplate: '%{y:.2f}'
    textfont:
      size: 14
    name: Sold
    type: bar
    statistic: sum
    period: week
    marker:
      color: '#0797cd'
      opacity: 0.9
    filters:
      - delta
```

Fig 1
<img width="481" alt="Haushalt weekly" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/6e70242f-df68-4fc4-abcb-4475c5e9ae2c">


________

Code 2
```
entities:
  - entity: sensor.from_netz_daily
    texttemplate: '%{y:.2f}'
    textfont:
      size: 14
    name: from netz
    type: bar
    statistic: sum
    period: week
    marker:
      color: '#cd0797'
      opacity: 0.9
    filters:
      - delta
      - filter: i < xs.length - 1
      - fn: |
          ({ys,xs,hass, vars}) => ({
            xs: [...xs, new Date().setHours(0,0,0)],
            ys: [...ys, hass.states['sensor.from_netz_weekly'].state],
          })
  - entity: sensor.to_netz_daily
    texttemplate: '%{y:.2f}'
    textfont:
      size: 14
    name: Sold
    type: bar
    statistic: sum
    period: week
    marker:
      color: '#0797cd'
      opacity: 0.9
    filters:
      - delta
      - filter: i < xs.length - 1
      - fn: |
          ({ys,xs,hass, vars}) => ({
            xs: [...xs, new Date().setHours(0,0,0)],
            ys: [...ys, hass.states['sensor.to_netz_weekly'].state],
          })
```

fig 2
<img width="481" alt="67 009 W" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/6597892d-0e95-440c-8a24-a351af45ba23">

_______________

Code 3
```
entities:
  - entity: sensor.from_netz_daily
    texttemplate: '%{y:.2f}'
    textfont:
      size: 14
    name: from netz
    type: bar
    statistic: sum
    period: week
    marker:
      color: '#cd0797'
      opacity: 0.9
    filters:
      - delta
      - fn: |
          ({ys,xs,hass, vars}) => ({
            xs: [...xs, new Date().setHours(0,0,0)],
            ys: [...ys, hass.states['sensor.from_netz_weekly'].state],
          })
      - resample: 1w
  - entity: sensor.to_netz_daily
    texttemplate: '%{y:.2f}'
    textfont:
      size: 14
    name: Sold
    type: bar
    statistic: sum
    period: week
    marker:
      color: '#0797cd'
      opacity: 0.9
    filters:
      - delta
      - fn: |
          ({ys,xs,hass, vars}) => ({
            xs: [...xs, new Date().setHours(0,0,0)],
            ys: [...ys, hass.states['sensor.to_netz_weekly'].state],
          })
      - resample: 1w

```

fig 3)
<img width="481" alt="Haushalt weekly" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/418aeb9e-1297-412b-898f-a000baf0971e">


fig 4)
<img width="481" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/63bff303-87d9-4ad8-9c3c-92dce081fbb0">

**Reply by dbuezas** [reply]
You are very close!
The only trick I can think of is:
```yaml
({ys,xs,hass, vars}) => ({
            xs: [...xs, +xs.at(-1)+1000*60*60*24*7],
            ys: [...ys, hass.states['sensor.from_netz_weekly'].state],
          })
```
Which will just pick the date of the last statistic and add a week to it. 
By the way, I think you shouldn't remove the last element of the statistics, that's the last week, not the current one!. With the trick above, you shouldn't get weird gaps anymore
