### DISCUSSION TITLE
dinamically calculate array for tickvals (=== no x values for non interesting y values)

### DISCUSSION THREAD

**Discussion by luissimoes** [dbuezas/lovelace-plotly-graph-card#370] [Q&A]
the case is a graph like the one below.
I just want to show the days where my EV was charged... and typically those are days where the energy is >= 10kWh
I have the chart, but for this to be good I want the x values to only show on those days.

My idea is to do this through tickvals.
So for this, would need to assign an array of XS values under the condition:

iy>10 => tickArray[ i ] = xs.at(i)

I couldn't add an fn function to tickvals....

any hint please?

<img width="481" alt="Screenshot 2024-02-05 at 23 10 33" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/645e6a6b-b407-468a-98ad-0f421a50087b">

I filtered the y values using

      - filter: y > 10

**Comment by dbuezas** [comment]
Something along these lines may work. I haven't tried this before, so you may have to fix it up :)

```yaml
entities:
  - entity: sensor.xyz
  - entity: sensor.xyz
    Internal: true
    filters:
       - filter: y>10
       - store_var: xyz
layout:
   xaxis:
      tickvals: $ex vars.xyz.xs
```

**Reply by luissimoes** [reply]
yep, I had tried something similar but always got a similar error: "undefined is not an object" (see picture)

I tried to see the console... but I have no idea what it is doing and what it means.... :-( :-(... 
From the Plotly description it seems tickvals wants an array (and I did try with explicit individual dates and it works) ... and XS as far as I understand *is* an array.... but seems that there is an object wrapper that is not recognised??







Picture
<img width="481" alt="Screenshot 2024-02-06 at 11 46 21" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/043cd504-076d-4f42-ae0f-ee6adefcc255">




Code:
```
type: custom:plotly-graph
layout:
  margin:
    t: 25
  height: 300
  legend:
    'y': -0.25
    x: 0.15
  yaxis:
    title:
      font:
        size: 9
      text: total energy
  xaxis:
    fixedrange: false
    gridcolor: rgba(238,235,235,0.6)
    showgrid: false
    tickmode: array
    tickvals: $ex vars.thevals.xs
    title:
      text: charge days
      font:
        size: 8
    tickformat: '%d %b'
entities:
  - entity: sensor.from_netz_daily
    internal: true
    filters:
      - filter: y>10
      - store_var: thevals
  - entity: sensor.from_netz_daily
    texttemplate: '%{x}'
    textposition: outside
    textfont:
      size: 18
    name: car charges
    type: bar
    statistic: sum
    period: day
    marker:
      color: '#F411B6'
      opacity: 1
    filters:
      - delta
      - filter: y > 10
hours_to_show: 6w
refresh_interval: 10
title: Car charges
```
