### DISCUSSION TITLE
Daily and Storm Rain Totals

### DISCUSSION THREAD

**Discussion by kaijk** [dbuezas/lovelace-plotly-graph-card#371] [Show and tell]
We've had  quite some rain the last few days so my Rain Chart shows some interesting data.

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/49624034/0ec87af4-4078-4821-af0c-bd419d0cffa3)

My Ecowitt rain gauge provides Daily, Hourly, and Event duration values. The columns are the daily intra-day totals that reset each day, Cumulative is the time progression and aonther view of the daily sensor, while the interval are the individual hourly readings.  The storm total sensor resets itself to zero after some hours of no rain.

```yaml
      - type: custom:plotly-graph
        title: "Daily & Storm Preciptation"
        refresh_interval: 3600
        time_offset: 6h
        entities:
          - entity: sensor.gw2000b_daily_rain_rate
            time_offset: 12h
            showlegend: true
            type: bar
            width: 82500000
            statistic: state
            period: day
            name: Day
            unit_of_measurement: in
          - entity: sensor.gw2000b_daily_rain_rate
            showlegend: true
            show_value: true
            line:
              width: 1.5
            name: Cumlitve
            unit_of_measurement: in
          - entity: sensor.gw2000b_event_rain_rate
            showlegend: true
            show_value: true
            line:
              width: 1.5
            name: Storm
            unit_of_measurement: in
          - entity: sensor.gw2000b_hourly_rain_rate 
            showlegend: true
            name: Intrvl
            unit_of_measurement: in
            type: bar
            filters:
              integrate:
                unit: h
                reset_every: 1h
        layout:
          legendwidth: 80%
          margin:
            t: 40
            b: 60
            r: 30
            l: 54
          yaxis:
            title: Inches
            minor:
              dtick: .05
              tick0: 0
              ticks: outside
          xaxis:
            type: date
            autorange: false
            rangeselector:
              'y': 1.15
              yanchor: bottom
              x: 1.00
              xanchor: center
              buttons:
                - count: 7
                  step: day
                - count: 14
                  step: day
        hours_to_show: 7d

```

**Comment by dbuezas** [comment]
New sensor, new charts! 
Thanks for sharing

**Comment by yestrdave** [comment]
Hello all,

I am trying to get this graph to work.  I am having and issue with the blue bar graph.  I know this works fine because I can pull the value from the HA web integration and it works fine.  Here is my issue.  Im pulling data for a Davis Vantage Vue from WeeWX via MQTT.  I get the value into HA fine and in the yaml I make sure the value is a float.  The sensor value I create is basically a value of .01 inch each time the cup tips.  In order for me to get the total I created          
 - data_template:
              entity_id: input_number.weather_davis_daily_rain_inch
              value: >
                {{ states('input_number.weather_davis_daily_rain_inch') | float
                + 0.01 }}
            action: input_number.set_value
I basically add the cup value to each tip.  This works fine.  Graphs fine in HA history.  When I try to use it here:
        entities:
          - entity: sensor.gw2000b_daily_rain_rate
            time_offset: 12h
            showlegend: true
            type: bar
            width: 82500000
            statistic: state
            period: day
            name: Day
            unit_of_measurement: in
The bar wont read.  I feel like it is a formatting issue in the helper/sensor. I tried creating a sensor that calls the input_number and still nothing.  Any help would be appreciated.  I'm convinced Plotly doesn't like my data for some reason

**Reply by kaijk** [reply]
First, please format your yaml blocks as:
'''yaml
your code
'''
but substitute "back tics" ( ` ) for the single quote character
```yaml 
your code
```
So,
- Did you change `entity: sensor.gw2000b_daily_rain_rate` to your sensor name? (Wrap the text in single back tics for in-line highlighting)
- If you're actually trying to plot the `input_number.davis_daily_rain_inch`. I'm not sure that will work.  There is no `device_class` or `state_class` or maybe you don't have the value going into your recorder database.

Also, it also seems like something's missing, your bucket tips sensor from the Davis rain gauge.  Is there one, and does MQTT send zeros when there is not a bucket tip event?

Regardless, I suggest using a `utility_meter` instead that resets to zero each day, like this:
```yaml
template:
  sensor:
    - unique_id: davis_rain_bucket_tips
      name:  Davis Rain Bucket Tips
      state: >-
          {{ somehow you get a lifetime increasing value for the cumulative bucket tips }}
    - unique_id: davis_rain_inches
      name:        Davis Rain Inches
      # cumulative lifetime total inches
      device_class:  precipitation
      state_class: total_increasing
      unit_of_measurement: in
      state:   "{{ states('sensor.davis_rain_bucket_tips') | float(0.0) * 0.01 }}"
      availability: "{{ is_number( states('sensor.davis_rain_bucket_tips') ) }}"
utility_meter:
  davis_rain_daily_inches:
    source:  sensor.davis_rain_inches
    cycle:  daily
  davis_rain_monthly_inches:
    source:  sensor.davis_rain_inches
    cycle:  monthly
```
You can then plot your `sensor.davis_rain_xxx_sensors` once you have added them to `reporter.`

Lastly, it seems odd that you can't get rain data itself out of the Davis...

**Reply by kaijk** [reply]
Note that there is a Davis Integration in HACS. Search HACS for "Davis"

<html><body>
<p>"This is a custom integration for the Davis Vantage Pro2. Either use a serial port or use an ip adress to connect to your device."</p>

Model | Compatible
-- | --
Davis WeatherLink SER (6510SER) | Yes
Davis WeatherLink USB (6510USB) | Yes
Davis Weatherlink IP (6555IP) | Yes
WeatherLink Live | No
Davis Weather Envoy8X (6318EU) | No
Other models | Unsure


</body>
</html>

**Reply by yestrdave** [reply]
@kaijk I was traveling today / tomorrow and just got a chance to review.  I have a MQTT sensor for bucket tips. But haven’t used it.  The sensor.rain_inch uses 0 and 0.01 inch every time it tips.  So if I get .02 inch’s I would get two reading from the rain inch sensor of  0.01.  I am using the input number to sum these values for a total for the day.  This is working but like you mentioned not correctly.

**Reply by yestrdave** [reply]
Using WeatherLink Live

**Reply by yestrdave** [reply]
https://github.com/michael-slx/weewx-weatherlink-live/blob/release/docs/installation.md

https://github.com/michael-slx/weewx-mqtt

**Reply by yestrdave** [reply]
“somehow you get a lifetime increasing value for the cumulative bucket“. Can I use the input_number. Helper there to total the values?

**Reply by kaijk** [reply]
OK, Looks like you already found from the Davis Integration's developer's answer to your question in the repository that the Davis integration I mentioned won't work for your Davis.  So, it's "roll your own."  This will be fun, but well upstream of Plotly.  

Open a discussion in the HA Community Forum and tag me and we'll take it off line from here. (I'd say no to input_number helpers in this case. You will want a bunch of weather sensors from your Davis.  That "won't-work" integration showed 51....

**Reply by yestrdave** [reply]
Let me see what I can do with what you provided.  I have all this working.  I have all the sensors in HA via MQTT.   I am just struggling with the format of this stupid rain sensor.   Once I get it in the correct format. All will work.   I’m in the home stretch.   
![IMG_2214](https://github.com/user-attachments/assets/55fdd030-9a6a-42b0-88d8-7d5d433dd4ba)

**Comment by yestrdave** [comment]
I love the graph layout.  Here is a working version using the HA Davis WeatherLink integration.  Once I figure out this last MQTT sensor I will be in good shape.  I will set up using all my local data. 

![IMG_2213](https://github.com/user-attachments/assets/0f80d58f-4238-4d95-b3ee-57bb0b1697a9)

**Reply by kaijk** [reply]
Looks like Helene missed  you, thank goodness!

**Reply by yestrdave** [reply]
I was expecting more rain for sure.

**Comment by yestrdave** [comment]
@kaijk another question.  If the sensor is showing a history graph in HA doesn’t that mean it’s in recorder?

**Reply by kaijk** [reply]
I have no idea how helpers are "recorded." 

You want a `sensor` with `state_class`, `device_class`, and `UOM` when you want other than Now data.  I've never seen a helper in a chart.  Find a way to use a `sensor`.  Template sensors are your friends.

**Reply by yestrdave** [reply]
@kaijk I have given this a go and need a little help.  https://community.home-assistant.io/t/mqtt-rain-fall-total/776838

**Comment by rgr-1** [comment]
<img width="494" height="333" alt="image" src="https://github.com/user-attachments/assets/8487e79c-c2af-4f02-8cfe-aa7ca21c67f5" />



<details><summary>The config:</summary>
<p>

```yaml
type: custom:plotly-graph
time_offset: 2h
titel: Rainfall
hours_to_show: 3d
refresh_interval: 10
entities:
  - entity: sensor.tfa_drop_720250_rain
    show_value: true
    name: cummulative
    fill: tozeroy
    fillcolor: rgba(0,0,255,0.075)
    statistics: state
    time_offset: "-2h"
    period: hour
    yaxis: "y"
    line:
      color: gray
      dash: dot
      width: 1
    filters:
      - derivate: d
      - map_y_numbers: Math.abs(y)
      - integrate:
          unit: d
          reset_every: 1d
  - entity: sensor.tfa_drop_720250_rain
    yaxis: y2
    show_value: true
    name: Rainfall
    type: bar
    statistics: state
    period: hour
    width: $fn() => 1000*60*60*0.8
    marker:
      color: rgba(0, 128, 255, 0.4)
    texttemplate: "%{y:.1f}"
    filters:
      - derivate: h
      - map_y_numbers: Math.abs(y)
  - entity: ""
    name: Now
    yaxis: y9
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: $ex [Date.now(), Date.now()]
    "y":
      - -1
      - 1
layout:
  margin:
    t: 10
    l: 40
    b: 40
  height: 320
  yaxis9:
    visible: false
    fixedrange: true
    range:
      - 0
      - 1
  xaxis:
    rangeselector:
      "y": 1.2
      buttons:
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 3
          step: day
        - count: 5
          step: day
        - count: 10
          step: day
```

</p>
</details> 


FYI the sensor setup :
- "tfa dostmann rain gauge" reports cumulative rain in mm
- [OpenMQTTGateway](https://docs.openmqttgateway.com/setitup/rf.html) RF 433MHz variant. To receive data and forward to mqtt.
