### DISCUSSION TITLE
Space between columns - strange behaviour

### DISCUSSION THREAD

**Discussion by luissimoes** [dbuezas/lovelace-plotly-graph-card#372] [Q&A] [answered]
Here is the graph I have now:
- its a stacked (relative) bar graph of 3 entities (consumed, sold and the part of solar energy that is consumed)

As can be seen the bars are very spaced.
"bargap"  doesn't do the trick, because this is already 0.1....
"bargroupgap" doesn't help too (and is not directly involved
"width" only makes the layout part different.
<img width="477" alt="Screenshot 2024-02-07 at 18 06 21" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/0d2bccb0-251a-47e7-8582-3fd1c1d42bbd">

BUT.... when I zoom in or out the graph then looks great (see pic below)
<img width="477" alt="Screenshot 2024-02-07 at 18 06 14" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/2999a12d-153a-459e-93a0-354bb9aa7d3b">

so..... 
how can I really set this?

_________________

add-on:

I have the entities as "statistic: state"..... here the case for one of the entities
```
  - entity: sensor.from_netz_daily
    texttemplate: '%{y:.2f}'
    textfont:
      size: 13
      color: '#ffffff'
    name: from netz
    type: bar
    statistic: state
    period: day
    marker:
      color: '#cd0797'
      opacity: 1
 ```

but if I use "sum" and then "delta" in the filter... then it works!!!
```
  - entity: sensor.from_netz_daily
    texttemplate: '%{y:.2f}'
    textfont:
      size: 13
      color: '#ffffff'
    name: from netz
    type: bar
    statistic: sum
    period: day
    marker:
      color: '#cd0797'
      opacity: 1
    filters:
      - delta
 ```

<img width="477" alt="Screenshot 2024-02-07 at 18 25 27" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/42578174/c98b0be0-0ac5-4c0f-a66f-2dc520010184">

(sadly I can't use this for the 3rd entity... can only use state... and as soon as there is an entity with "state" then this behaviour happens

**Comment by dbuezas** [comment, marked as answer]
This is typically because the home assistant api invents a datapoint at the beginning of the requested period.
Try removing it using
```yaml
- entity: sensor.from_netz_daily
   ...
   filters:
     - filter: i > 0

```
