### DISCUSSION TITLE
Statistics does not seems to work if attribute is used in an entity

### DISCUSSION THREAD

**Discussion by r-jean-pierre** [dbuezas/lovelace-plotly-graph-card#373] [Q&A]
Hi!

Quite recently, I got new sensors and started to toy.
I just discover something that I don't understand about the "statistic" feature
Here are tiny examples:

```
cards:
  - type: custom:plotly-graph
    entities:
      - entity: 'climate.heaterentrance'
        attribute: 'current_temperature'
    hours_to_show: 7d
```
works obviously perfectly (just to show there is data):
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/6eb9d669-b69a-44d6-8775-8606959de944)

Same with stats:
```
- type: custom:plotly-graph
    entities:
      - entity: 'climate.heaterentrance'
        attribute: 'current_temperature'
        statistic: mean
        period: hour
    hours_to_show: 7d
```
Fails: empty:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/b42670f0-f027-4834-81f7-7bc4445de102)

If I take another sensor whose values are not behind an attribute, then it works
```
  - type: custom:plotly-graph
    entities:
      - entity: 'sensor.ths_entrance_living'
    hours_to_show: 7d
```
Obviously:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/2bd36368-1acd-4ade-9a89-5057382fc828)

And with stats
```
- type: custom:plotly-graph
    entities:
      - entity: 'sensor.ths_entrance_living'
        statistic: mean
        period: hour
    hours_to_show: 7d
```
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/c4a5d58b-58f1-4285-b054-4e26a2ed3a3b)

This one works

Can someone explain what is my error?

**Comment by dbuezas** [comment]
Home assistant decides what statistics to use based on the sensor_class. I assume this may be the issue here.
You can check the sensor_class in `http://homeassistant.local:8123/developer-tools/state`

I know that `sensor_class: measurement`will store mean, min and max. others store the `sum` and other store nothing.
As per the attributes, they don't land in the statistics db afaik.

**Comment by r-jean-pierre** [comment]
Hey, thanks for the answer.
So, the main device has no "class",  
[2024-02-14 09_57_23-Window](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/5d650b3f-8875-49c1-87f9-6e863b41239d)
I started to investigate and try to find some workaround

First attempt was to create a dedicated sensor which only extract this attribute and make it "like the other working temperature sensors". I used the integration `platform: attributes` which "automatize" this work and I got `sensor.heaterentrance_current_temperature`

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/9b9fdabd-64a1-4752-a32c-2b3c3847bff5)

It seems to be consistent with your remark and also seems to work for HA:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/1afd0baf-71c3-457e-b8b6-5654db77526a)

But still, nothing in my custom:plotly-graph

Other attempt was to use `custom:apexcharts-card` (but I don't want... all my graphs are in plotly...), and both solutions works:
```
series:
      - entity: 'climate.heaterentrance'
        attribute: 'current_temperature'
        group_by:
          duration: 1h
          func: avg
      - entity: 'sensor.heaterentrance_current_temperature'
        group_by:
          duration: 1h
          func: avg
```
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/4bf70f62-8d3c-42cf-ae54-0b7da2ed22f9)

Any clue about it? I also feel is HA related, but dammed.... HA is able to send a rocket on the moon, but since I started to geek with it some years ago, I think it's not the first time where I cannot do straightforward out-of-the-box `select avg(value) from my sensor groupby something` or even more easy things...

**Reply by dbuezas** [reply]
I'm not very familiar with apex charts, but that looks like it is not using the statistics db at all. `group_by` looks more related to filters (like resampling + sliding_window_moving_average).

>  I cannot do straightforward out-of-the-box select avg(value) from my sensor groupby something or even more easy things...

Yeah, that's somehow hard and one of the reasons for me to make this custom component.

**Reply by r-jean-pierre** [reply]
So you indirectly suggest to also use filter in custom:plotly-graph like sliding_window_moving_average? After reading the documentation, it seems to be more sliding (of course!) with notion of number of point than a cutting into intervals based on timestamp
But I will try it asap

BTW the groupby of apex is really doing the same job as statistic+period of plotly, you can even precise the end span just to be sure that the interval will be for example 12:00 to 12:05 and not 12:01:57 to 12:06:57 for a 5 minutes length

There is still something weird with attributes, why all the data points are here without statistic+period (i can zoom out and see week and week of data of the attribute), but empty with statistic

Hope another user will read my post and propose a workaround :)

**Reply by dbuezas** [reply]
To achieve this you can use resampling twice: one before averaging so the window size maps to a specific time interval, and one after to remove all intermediate datapoints.

I think there's a confusion with what the statistic attribute does: It is not an operation in the history data, it uses data from a different database in home assistant. See the difference:
* https://www.home-assistant.io/integrations/statistics/
* https://www.home-assistant.io/integrations/history/

Attributes are not stored in the statistics database

**Reply by r-jean-pierre** [reply]
Yes, I understood this thing, but about the "fake" attribute mapped to regular sensor, I can found it in the correct statistic database:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/366a05f9-2a5b-44c4-b535-dff025bee618)

and there is no "issue" like for example this one:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/f9e8b684-5173-44d0-b98a-e578765f3457)

Still strange, isn't it? I will soon figure out why, it's probably simple, but for now, I'm running out of ideas

**Reply by dbuezas** [reply]
When did you create the "fake" entity? Wouldn't statistics only be populated from now on?
Have you tried the standard home assistant statistics card?
BTW, I checked their readme, and `group_by` takes any duration, so it can't be using statistics. I still think it is analogous to a filter applied on the normal history .

**Reply by r-jean-pierre** [reply]
I wrote my sensors half a day go, do you think I have to wait? There is not backward stats made by HA?

**Reply by dbuezas** [reply]
AFAIK, there is no retroactive statistics. As to waiting time, to be honest I don't know but it wouldn't surprise me.
Although this pic of yours seems to indicate that there are some stats stored
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/777196/472b2a12-4dcd-43f7-a995-6e8e028d71b3)

I suggest you:
* try different periods
* double check against the inbuilt [statistics card](https://www.home-assistant.io/dashboards/statistics-graph/)

**Reply by r-jean-pierre** [reply]
So, finally it came! But with a huge delay + shift

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/6439592e-8cc5-4a01-9b7c-ceac9982e318)

The blue curve is the first "fake" sensor I started to play with. 
For the others ones, I need to assign one by one them the ```state_class: measurement``` and wait +/- 2 days to let HA understand to make stats over them....

So sorry for the 2 topics in the same issue. Lesson learnt:
- don't insist with statistic+period using attribute
- extract attribute into a new sensor and make sure ```state_class: measurement```
- wait a looooooooooooong time and fully reboot HA (<-maybe this one is placebo, but I did it a lot :) )
- 
Thank you for the guidance!

**Reply by rrozema** [reply]
Recorder is the component that aggregates the entities' state values into the statistics. It does this every 5 minutes for the short term statistics (in the statistics_short_term table) and every hour (in the statistics table) for the long term statistics. The short term statistics -those with a granularity of 5 minutes- get deleted after a couple of days, the long term statistics -with a granularity of an hour- are kept forever.
Which entities get aggregated, and how they get aggregated is determined by the value of the "state_class" attribute on each entity. You can view the entities plus their attributes in 'Developer tools' -> 'STATES'.

## Entities with `state_class: measurement`

will be aggregated into a statistic with has_mean = 1, and will get their [min], [max] and [average] columns filled.

## Entities with `state_class: total` or `state_class: total_increasing`

will be aggregated into a statistic with has_sum=1, and will get their [state] and [sum] columns filled.

## All other entities

will not be aggregated into a statistic. Attributes can't have attributes themselves so these are not aggregated into statistics either.

---

To have a statistic aggregated for a numeric value stored in an attribute you can create a template sensor that has the desired state_class attribute. Please find two examples below, one for an increasing entity -like for example energy used-, plus another for an entity that represents a measurement (min, max, avg) -like for example instantaneous power, or a temperature-. The entities created for such template sensors will get aggregated into the statistics.
```
template:
  - sensor:
      - name: "my entity's attribute 1"
        unique_id: "124cb077-a937-4fa5-98c4-d80d57677a77"
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
        state: >
          {{ state_attr('sensor.my_entity', 'attribute_1') }}
        availability: >
          {{ has_value('sensor.my_entity.attribute_1') }}

      - name: "my entity's attribute 2"
        unique_id: "124cb077-a937-4fa5-98c4-d80d57677a78"
        unit_of_measurement: kW
        device_class: power
        state_class: measurement
        state: >
          {{ state_attr('sensor.my_entity', 'attribute_2') }}
        availability: >
          {{ has_value('sensor.my_entity.attribute_2') }}
```
