### DISCUSSION TITLE
Sun.Sun::elevation

### DISCUSSION THREAD

**Discussion by ChrisKoh83** [dbuezas/lovelace-plotly-graph-card#38] [Q&A] [answered]
Hello,

I tried to plot the suns elevation like this:

```yaml 
type: custom:plotly-graph
entities:
  - entity: sensor.garage_west_oben_generated_power
    yaxis: y1
  - entity: sensor.garage_west_unten_generated_power
    yaxis: y1
  - entity: sensor.garage_ost_oben_generated_power
    yaxis: y1
  - entity: sensor.pv_leistung_gesamt
    yaxis: y1
  - entity: sun.sun::elevation
    yaxis: y2
hours_to_show: 24
refresh_interval: 10 

```

but it’s not working
![IMG_0039](https://user-images.githubusercontent.com/13451391/166452084-00f777ee-836a-4104-8f5e-fbbe1be326bf.jpeg)

![IMG_0040](https://user-images.githubusercontent.com/13451391/166452258-e38625e0-a08f-43e0-b3b2-8c888e7e7f5d.jpeg)

**Comment by dbuezas** [comment, marked as answer]
Interesting, HomeAssistant only includes the "friendly_name" attribute in its response.

Here's the network tab in chrome:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/777196/166514207-f6bf9477-94f3-46b8-ae9f-cb8d0b31eb2b.png">

This used to work in previous home assistant versions. And it is specific for the sun.sun entity. All other I have work perfectly.

The only solution I see at the moment is too add a template sensor to your `configuration.yaml`:
```yaml
platform: template
    sensors:
      sun_sun_elevation:
        value_template: "{{state_attr(‘sun.sun’, ‘elevation’)}}"
```

I'd say this is a bug in home assistant.
