### DISCUSSION TITLE
Displaying calculated value in hovertext

### DISCUSSION THREAD

**Discussion by paradox460** [dbuezas/lovelace-plotly-graph-card#383] [Q&A] [answered]
I'm building a small graph that shows the cost per day of fuel for my car. The actual cost is derived from a few sensors: `average_gas_price`, `average_fuel_consumption`, and a statistical value calculated off differences in the odometer from one day to the next.

I've got a decent enough graph rendering:

<img width="492" alt="CleanShot 2024-03-05 at 03 04 18@2x" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/168193/7eef4aff-97e8-43fa-838e-70023e40602f">

However, I'd like to add some data to the hovertext that shows the precursor values, specifically the gallons consumed and odometer delta readings, as well as the price for that day. I am unsure as how to do this with each day's values, as I didn't see any way to access the index of the currently hovered item, so pulling the data out of `vars` seemed impossible.

<details>
<summary>YAML</summary>

```yaml
type: custom:plotly-graph
hours_to_show: $ex 7*24
title: Daily driving cost
config:
  scrollZoom: false
layout:
  xaxis:
    fixedrange: true
  yaxis:
    fixedrange: true
entities:
  - entity: sensor.2023_ascent_touring_average_fuel_consumption
    internal: true
    type: bar
    statistic: mean
    period: day
    filters:
      - store_var: mpg
  - entity: sensor.average_gas_price
    internal: true
    statistic: mean
    period: day
    filters:
      - store_var: price
  - entity: sensor.2023_ascent_touring_odometer
    type: bar
    statistic: state
    period: day
    name: Cost
    unit_of_measurement: USD
    filters:
      - delta
      - map_y: >-
          {
            const gals = y / vars.mpg.ys[i];
            return gals * vars.price.ys[i];
          }
```

</details>

**Comment by dbuezas** [comment]
Hi there!

You have two options:
* Use a universal function/expression ($fn or $ex) to fill `customdata:` with an array and then access it from `hovertemplate:`. See [this discussion](https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/359#discussioncomment-8206608)
* directly fill `text:` with a $fn/$ex, see [api](https://plotly.com/javascript/reference/scatter/#scatter-text) and [plotly docs](https://plotly.com/javascript/hover-text-and-formatting/#adding-hover-text-to-data-in-line-and-scatter-plots)

**Reply by paradox460** [reply]
I got some custom text working, _however_ it appears to have an off-by-one error, that I can't seem to track down

<details>
<summary>YAML</summary>

```yaml
type: custom:plotly-graph
hours_to_show: $ex 7*24
title: Daily driving cost
config:
  scrollZoom: false
layout:
  xaxis:
    fixedrange: true
  yaxis:
    fixedrange: true
entities:
  - entity: sensor.2023_ascent_touring_average_fuel_consumption
    internal: true
    type: bar
    statistic: mean
    period: day
    filters:
      - store_var: mpg
  - entity: sensor.average_gas_price
    internal: true
    statistic: mean
    period: day
    filters:
      - store_var: price
  - entity: sensor.2023_ascent_touring_odometer
    type: bar
    statistic: state
    period: day
    name: Cost
    unit_of_measurement: USD
    customdata: |-
      $fn ({statistics, vars}) => {
        console.log(statistics)
        return statistics.map(({change: y}, i) => {
          console.log(`customdata: ${y}, idx: ${i}`)
          const mpg = vars.mpg.ys[i];
          const price = vars.price.ys[i];
          const gals = y / vars.mpg.ys[i];
          const calc = gals * price;
          return {
            gals,
            mpg,
            price,
            distance: y,
            calc
          };
        });
      }
    hovertemplate: |-
      Cost: %{y}<br>
      Gals: %{customdata.gals}<br>
      MPG: %{customdata.mpg}<br>
      Price: %{customdata.price}<br>
      Distance: %{customdata.distance}<br>
      Calc: %{customdata.calc}
    filters:
      - delta
      - map_y: >-
          {
            console.log(`map: ${y}`)
            const gals = y / vars.mpg.ys[i];
            return gals * vars.price.ys[i];
          }
```

</details>


https://github.com/dbuezas/lovelace-plotly-graph-card/assets/168193/6f4eff12-a882-4a0b-ad38-6f5fb31d7489

As you can see in the clip, when you hover over an item, you get information for the _previous_ entity (the first line of the hover, the `Cost` line, shows the `y` value of that bin, all other lines reference customdata)

**Reply by dbuezas** [reply, marked as answer]
If you have 1-off issues, it may be that the other is missing a datapoint for early feb. To confirm, use `hours_to_show: 4d`.
If that is the case, the only solution I see is to index backwards (so from the end instead of from the start).

You can do this by 
```js
reverse_i = -statistics.length-1-i;
const mpg = vars.mpg.ys.at(reverse_i);
```
But you'll also get in trouble if some sensor is missing data at the end, although that may be fixable by adding a resample filter.

**Reply by paradox460** [reply]
Resampling each segment did fix it. Here's the updated YAML:

<details>
<summary>YAML</summary>

```yaml
type: custom:plotly-graph
hours_to_show: 7d
title: Daily driving cost
config:
  scrollZoom: false
layout:
  xaxis:
    fixedrange: true
  yaxis:
    fixedrange: true
entities:
  - entity: sensor.2023_ascent_touring_average_fuel_consumption
    internal: true
    type: bar
    statistic: mean
    period: day
    filters:
      - resample: 1d
      - store_var: mpg
  - entity: sensor.average_gas_price
    internal: true
    statistic: mean
    period: day
    filters:
      - resample: 1d
      - store_var: price
  - entity: sensor.2023_ascent_touring_odometer
    type: bar
    statistic: state
    period: day
    name: Cost
    unit_of_measurement: USD
    customdata: |-
      $fn ({statistics, vars}) => {
        console.log(statistics)
        return statistics.map(({change: y}, i) => {
          console.log(`customdata: ${y}, idx: ${i}`)
          const mpg = vars.mpg.ys[i];
          const price = vars.price.ys[i];
          const gals = y / vars.mpg.ys[i];
          const calc = gals * price;
          return {
            gals,
            mpg,
            price,
            distance: y,
            calc
          };
        });
      }
    hovertemplate: |-
      Cost: %{y}<br>
      Gals: %{customdata.gals}<br>
      MPG: %{customdata.mpg}<br>
      Price: %{customdata.price}<br>
      Distance: %{customdata.distance}<br>
      Calc: %{customdata.calc}
    filters:
      - resample: 1d
      - delta
      - map_y: >-
          {
            console.log(`map: ${y}`)
            const gals = y / vars.mpg.ys[i];
            return gals * vars.price.ys[i];
          }
```

</details>

~~When I get the chart exactly as I want it, I'll edit this comment with a second YAML which is the "final" one without the debug console logs, for other people to reference.~~

Here's a "final" YAML, that does pretty much most of what I want:

<details>
<summary>YAML</summary>

```yaml
type: custom:plotly-graph
hours_to_show: 10d
title: Daily driving costs
config:
  scrollZoom: false
layout:
  xaxis:
    fixedrange: true
    showgrid: false
    showline: false
  yaxis:
    fixedrange: true
    showgrid: false
    showline: false
entities:
  - entity: sensor.2023_ascent_touring_average_fuel_consumption
    internal: true
    type: bar
    statistic: mean
    period: day
    filters:
      - resample: 1d
      - store_var: mpg
  - entity: sensor.average_gas_price
    internal: true
    statistic: mean
    period: day
    filters:
      - resample: 1d
      - store_var: price
  - entity: sensor.2023_ascent_touring_odometer
    type: bar
    statistic: state
    period: day
    name: Cost
    unit_of_measurement: USD
    customdata: |-
      $fn ({statistics, vars}) =>
        statistics.map(({change: distance}, i) => {
          const mpg = vars.mpg.ys[i];
          const price = vars.price.ys[i];
          const gals = distance / mpg;
          return {
            gals,
            price,
            distance
          };
        });
    hovertemplate: >-
      <b>%{x}</b><br> %{y:$.2f}<br>
      %{customdata.gals:.2f} gal @ %{customdata.price:$.2f}<br>
      %{customdata.distance:2,} mi
      <extra></extra>
    texttemplate: '%{y:$.2f}<br> %{customdata.distance:2,}mi'
    filters:
      - delta
      - resample: 1d
      - map_y: |-
          {
            const gals = y / vars.mpg.ys[i];
            return gals * vars.price.ys[i];
          }
```

</details>

That will generate a graph tha looks like this:

<img width="489" alt="CleanShot 2024-03-05 at 10 57 48@2x" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/168193/6fe03604-2b4a-43c8-a60c-9634f6a5ffdf">


Thanks!
