### DISCUSSION TITLE
How to return (change) conditional values?

### DISCUSSION THREAD

**Discussion by deltamelter** [dbuezas/lovelace-plotly-graph-card#386] [Q&A]
Firstly I'm impressed with this card, I have been a big ApexCharts card user but a crippling javascript bug and unaddressed limitations are  forcing me to look for alternatives So I'm trying reproduce and improve the graphs I want with added interactive element of this plotly card.

Anyway, one of the things I could do with apex was set a data_generator and get it to spit out anything. One of the things I want to do here is add a series of fixed additions only when certain conditions are met, in example here, the condition is time of day.  I add  blocks of 12, but only ad certain hours (16, 17 and 18:00).  I tried to use the same basic code and make an array of timestamps and values of either 0 or 12 but can't figure out how to output that in the plotly series (entity)  it just shows the original entity contents.

This is what I want to achieve:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/27061628/a2742ced-55e6-458d-b03c-52d743723dc7)

The filters:
```
    filters:
      - fn: |-
          ({ meta }) => ({
            xs: meta.data.map(({ start_time }) => start_time),
            ys: meta.data.map(({ price_pence_per_kwh }) => {
            const lastIndex = meta.data.length -1;
            const arr = [16,17,18]
            let bump = 0;
            let itemTimestamp = 0;
            const data = [];  
            for (let i = 1; i < lastIndex; i++) {
              itemTimestamp = new Date(meta.data[i].start_time);
              if (arr.includes(itemTimestamp.getHours())){
                bump = 12;
                }
              else {
                bump = 0}
              data.push([itemTimestamp, bump])  
              }
              return { meta : {"data": data}}; 
            }),
          })      
```
The original data set ( for this series, I'm only interested in the datetime and whether or not the "bump" applies
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/27061628/6367003e-6a11-47c6-86c5-ba71be7f9068)

Apex chart was happy to replace the whole entity with a timestamp, value array, but I think with plotly I need to be more precise. How would I best go about this with the plotly card and filters?
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/27061628/9de0c8ec-051e-4874-9b32-db966d870531)

multi stacks and overlaid series with different semi-transparent colours are things I would want to use here too, but one thing at a time :grinning:

**Comment by dbuezas** [comment]
Wow, you started on expert mode :) 

> multi stacks

Google (or search these discussions) `plotly stackgroup`

> semi-transparent colours

you can set `opacity: 0.5` on the entity or use `rgba(r,g,b,a)`on `line:color:`

> plotly

try with:
```js
({ meta }) => ({
  xs: meta.data.map(({ start_time }) => new Date(start_time)),
  ys: meta.data.map(({ start_time }, i) =>
    [16, 17, 18].includes(new Date(start_time).getHours()) ? 12 : 0
  ),
});
```

**Reply by deltamelter** [reply]
> ({ meta }) => ({
>   xs: meta.data.map(({ start_time }) => new Date(start_time)),
>   ys: meta.data.map(({ start_time }, i) =>
>     [16, 17, 18].includes(new Date(start_time).getHours()) ? 12 : 0
>   ),
> });

This works well for "mapped" (current) data.  How would I do the same for the history data?
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/27061628/d67b78ea-12a9-4160-b5ab-50dd7cdc03e6)

I guess I will have to truncate the current entity to start from "now" to stop the overlapping stacking... 

Also wondering if conditional color of bars is possible in plotly?  In Apex I do this with 
```
    color_threshold:
      - value: 0.5
        color: '#ff0000'
      - value: 0.4
        color: '#ff6347'
      - value: 0.3
        color: '#ff6347'
      - value: 0.2999
        color: '#ffa500'
      - value: 0.2
        color: '#ffa500'
      - value: 0.1999
        color: '#3cb371'
      - value: 0.1
        color: '#3cb371'
      - value: 0.0999
        color: '#02989F'
      - value: 0.05
        color: '#02989F'
      - value: 0.04999
        color: '#0051FF'
      - value: 0
        color: '#0051FF'
```
