### DISCUSSION TITLE
Real time data plot

### DISCUSSION THREAD

**Discussion by Sb-futuretech** [dbuezas/lovelace-plotly-graph-card#389] [Q&A]
I would like to display real time mqtt data. I've created a xy-plot but no matter how small I choose the refresh_intervall it always takes around 2 to 3 seconds till data in plot is updated. Is there any way to make this faster.

**Comment by dbuezas** [comment]
Try 'auto' instead, and make sure to compare to an entity card.

**Reply by Sb-futuretech** [reply]
Thanks for your fast answer. In entity card and in mqtt explorer I see instant change of value (currently for testing a poti on an esp). With auto option it takes even longer. current card setup:

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.neigung_x_axis
    internal: true
    fn: >-
      $fn ({ xs, ys, vars }) => { vars.y = ys.slice(-1)[0]; vars.xs =
      xs.slice(-1)[0]; }
  - entity: sensor.neigung_y_axis
    internal: true
    fn: $fn ({ ys, vars }) => vars.x = ys.slice(-1)[0]
  - entity: ''
    x: $fn ({ vars }) => [vars.x]
    'y': $fn ({ vars }) => [vars.y]
    marker:
      size: 7
raw_plotly_config: true
layout:
  margin:
    t: 10
    l: 70
    r: 0
    b: 70
  height: 500
  xaxis:
    title: Neigung X
    range:
      - 0
      - 6000
  yaxis:
    title: Neigung Y
    range:
      - 0
      - 6000
refresh_interval: auto
```

**Reply by dbuezas** [reply]
Your x axis range may be interfering. Can you test the same in a new card but not changing the x axis?

**Reply by Sb-futuretech** [reply]
unfortunately same issue I tried it with fixed value 2000. And created a second chart with time as x base. On both the same. When I choose  refresh interval  auto it takes ages. If I choose 1 or smaller I am experiencing the mentioned 2 - 3 seconds delay.

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.neigung_x_axis
    internal: true
    fn: >-
      $fn ({ xs, ys, vars }) => { vars.y = ys.slice(-1)[0]; vars.xs =
      xs.slice(-1)[0]; }
  - entity: sensor.neigung_y_axis
    internal: true
    fn: $fn ({ ys, vars }) => vars.x = ys.slice(-1)[0]
  - entity: ''
    x: $fn ({ vars }) => [2000]
    'y': $fn ({ vars }) => [vars.y]
    marker:
      size: 7
raw_plotly_config: true
layout:
  margin:
    t: 10
    l: 70
    r: 0
    b: 70
  height: 500
  xaxis:
    title: Neigung X
    range:
      - 0
      - 6000
  yaxis:
    title: Neigung Y
    range:
      - 0
      - 6000
refresh_interval: auto
```
