### DISCUSSION TITLE
multiple yaxis not working for me

### DISCUSSION THREAD

**Discussion by ChrisKoh83** [dbuezas/lovelace-plotly-graph-card#39] [Q&A]
Hi,

I try to setup an plotly with multiple yaxis. But didn't get it :(

```YAML
type: custom:plotly-graph
entities:
  - entity: sensor.wu_k_2783e_state_of_charge
    yaxis: y1
  - entity: sensor.wu_k_2783e_range_electric
    yaxis: y2
layout:
  dragmode: pan
  annotations:
    - xref: paper
      yref: paper
      'y': 0.95
      text: SoC
      showarrow: false
    - xref: paper
      yref: paper
      'y': 0.8
      text: Reichweite
      showarrow: false
  margin:
    t: 30
    l: 45
    r: 30
    b: 50
  showlegend: false
  height: 400
  yaxis1:
    fixedrange: false
  yaxis2:
    fixedrange: false
  grid:
    rows: 2
    columns: 1
    pattern: coupled
    roworder: top to bottom
hours_to_show: 24
refresh_interval: 10
```
<img width="1279" alt="Bildschirmfoto 2022-05-11 um 21 40 12" src="https://user-images.githubusercontent.com/13451391/167932443-4e86e331-4ea8-4f61-a9ac-83813c6b2692.png">

**Comment by dbuezas** [comment]
Y2 is on the right. Try adding a right margin
```yaml
layout:
  margin:
    r: 50
```

If that's not what you want, feel free to describe or doodle what you expect and I'll guide you
