### DISCUSSION TITLE
Scatterplot of Sun Azimuth vs Elevation

### DISCUSSION THREAD

**Discussion by kaijk** [dbuezas/lovelace-plotly-graph-card#390] [Show and tell]
Objective: generate an elevation/azimuth arc, for the sun, 
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/49624034/80b06224-8aaf-43d7-9e2f-009b620eeb45)

Note that `show_value:` shows the `Y` value and `Undefined` for `X`.  Make sure the sensors have `state_class: measurement`.
```yaml
  - type: custom:plotly-graph
    title: Sun Azimuth and Elevation
    raw_plotly_config: true
    resample: 5m
    hours_to_show: current_day
#    hours_to_show: $ex Math.max(new Date().getHours() - 5, 1)
    entities:
      - entity: sensor.sun_azimuth
        internal: true
        fn: $fn ({ ys, vars }) => vars.azimuth = ys
      - entity: sensor.sun_elevation
        internal: true
        fn: $fn ({ ys, vars }) => vars.elevation = ys

      - entity: ''
        x: $fn ({ vars }) => vars.azimuth
        y: $fn ({ vars }) => vars.elevation
        mode: markers
        name: points
        marker:
          color: red
          size: 8
        type: scatter
#        show_value: true
    layout:
      margin:
        t: 10
        l: 70
        r: 20
        b: 70
      height: 400
      showlegend: false
      xaxis:
        title:
          text: Azimuth (Degrees)
        range: [ 80, 280 ]
        dtick: 10
        tick0: 80
        zeroline: false
      yaxis:
        title:
          text: Elevation (Degrees)
        range: [ 0, 100 ]
        dtick: 5
        tick0: 0
        zeroline: false
```
