### DISCUSSION TITLE
3D graph for sensor per day

### DISCUSSION THREAD

**Discussion by bjkluft** [dbuezas/lovelace-plotly-graph-card#391] [Show and tell]
Hi,
First of all this add-on looks very promising! The amount of options is huge, giving us a lot to play with. However I do have troubles starting with a graph I would love to create. The idea is as the image below. I have the amount of energy generated with my solar panels and i would like to be able to plot them per day over time. So the X-axis should be the days, the Y-axis the years and the Z-axis should be the amount of energy. The data is stored in a MariaDB (SQL) with one value per hour, so two columns: date (YYMMDD hh:mm:ss) and the recorded amount of energy.
Is it possible to create such a graph?

With many thanks,
Jeroen

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/12735834/eb04735e-7d57-4fda-8166-8eec1afa8ef5)

**Comment by dbuezas** [comment]
Yes it should be possible.
See this: https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/298
And this: https://plotly.com/javascript/3d-surface-plots/

Good luck!

**Comment by bjkluft** [comment]
First of all, thank you for the reply.
My js knowledge is close to nothing and I'm not able to create the correct input. I know this is a large stretch, but maybe somebody can help me out. What I have is a data set of values and dates (every 5minutes a value is stored), what I want to achieve  is an 3D overview of the max value per hour per day over the year. So the X-axis would be 24 hours, the Y-axis would be 365 days and the Z-axis the actual value (amount of energy from my solar panels).
I would be very grateful to whoever can get me started.

**Comment by dbuezas** [comment]
Maybe this gets you started
<img width="365" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/777196/9e296cc0-b580-4270-940b-e622f0a13b1c">

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.electricity_usage
    period: hour
    statistic: max
    fn: |
      $fn ({ xs, ys, vars }) => {
        const hours = Array.from({ length: 24 }, (_, i) => `${i}:00`);
        const days = Array.from({ length: 365 }, (_, i) => i + 1);
        const maxValues = Array.from({ length: 366 }, () => Array(24).fill(null));
        
        for (let i = 0; i < xs.length; i++) {
          const date = new Date(xs[i]);
          const hour = date.getHours();
          const dayOfYear = Math.floor((date - new Date(date.getFullYear(), 0, 0)) / 86400000)-1;
          const currentValue = +ys[i];
          
          if (maxValues[dayOfYear][hour] === null || currentValue > maxValues[dayOfYear][hour]) {
            maxValues[dayOfYear][hour] = currentValue;
          }
        }
        vars.x = hours; 
        vars.y = days;
        vars.z = maxValues;
      }
    x: $fn ({ vars }) => vars.x
    'y': $fn ({ vars }) => vars.y
    z: $fn ({ vars }) => vars.z
    type: surface
raw_plotly_config: true
hours_to_show: 1y
title: Solar Energy Output Over the Year
layout:
  height: 600
  margin:
    t: 50
    l: 50
    r: 50
    b: 50
  scene:
    xaxis:
      title: Hour of Day
    yaxis:
      title: Day of Year
    zaxis:
      title: Max Energy Output (kWh)

```

let me suggest you to do some iterations with chatGPT, it should be able to explain you what all the gibberish means :)
