### DISCUSSION TITLE
Plot Data with future Timestamps

### DISCUSSION THREAD

**Discussion by cmikovits** [dbuezas/lovelace-plotly-graph-card#395] [General]
I am quite new to ha and also this card. As far as I understood HA and also this card only plot values with time entries in the past. Now I have a sensor (epex_spot) with values also one day ahead which I would love to plot. Can anyone pinpoint me how to accomplish that?

https://github.com/mampfes/ha_epex_spot

With apex charts this was accomplished with:

` data_generator: >
      return entity.attributes.data.map((entry, index) => { return [new
      Date(entry.start_time).getTime(), entry.price_eur_per_mwh];}).slice(parseInt(hass.states['sensor.epex_start_low_period'].state.substring(0,2)),parseInt(hass.states['sensor.epex_start_low_period'].state.substring(0,2))+4);
`

**Comment by dbuezas** [comment]
This one should get you started https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/213

**Reply by cmikovits** [reply]
Thx for the hint. I already read through this, but I am unsure about how to apply the whole fn stuff. 
Also, my sensor has the values in one attribute. Is it even possible with data like that?

**Reply by dbuezas** [reply]
Yes it is possible, the example I linked above also has the future data inside one attribute.

**Reply by cmikovits** [reply]
ok, can you please pinnpoint me to this entry. I see the one with the meta.forecast from openweather. I am really unfamiliar on how to translate this term to the one I need.

**Reply by dbuezas** [reply]
This section may help you: https://github.com/dbuezas/lovelace-plotly-graph-card?tab=readme-ov-file#debugging

As a starting point try:
```yaml
entities:
  - entity: ''
    name: custom thing
    filter: 
      fn: |
        ({meta, hass}) => ({
           xs: meta.data.map((entry, index) => new Date(entry.start_time).getTime()),
           ys: meta.data.map((entry, index) => entry.price_eur_per_mwh];}).slice(parseInt(hass.states['sensor.epex_start_low_period'].state.substring(0,2)),parseInt(hass.states['sensor.epex_start_low_period'].state.substring(0,2))+4);
         })


```
