### DISCUSSION TITLE
Is there anyone who made a sankey diagram

### DISCUSSION THREAD

**Discussion by qinguDLI** [dbuezas/lovelace-plotly-graph-card#399] [Q&A] [answered]
I really want to make a sankey diagram, did anybody already had some progress in this?

**Comment by dbuezas** [comment, marked as answer]
What data will you put in it?
Sankey diagrams do work if you have data to feed them :) 
Here's an example with fake data
```yaml
type: custom:plotly-graph
title: sankey
entities:
  - entity: ""
    type: sankey
    orientation: h
    node:
      pad: 15
      thickness: 30
      line:
        color: black
        width: 0.5
      label:
      - A1
      - A2
      - B1
      - B2
      - C1
      - C2
      color:
      - blue
      - blue
      - blue
      - blue
      - blue
      - blue
    link:
      source:
      - 0
      - 1
      - 0
      - 2
      - 3
      - 3
      target:
      - 2
      - 3
      - 3
      - 4
      - 4
      - 5
      value:
      - 8
      - 4
      - 2
      - 8
      - 4
      - 2
raw_plotly_config: false
```

**Reply by dbuezas** [reply]
<img width="341" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/777196/5b7d6a64-cc00-4edb-8589-7a797aa2eafe">

**Reply by qinguDLI** [reply]
i want to use it to display my energy usage. So bassically dat the left i will have my power consumption en return. In the middel i have the 3 fases of my power suply seperated. Then at teh right, my solar panels(2x), heatpump, and the rest energy per fase seperated. i that makes sence. I tried to make a picture of it what i have in my mind.

<img width="391" alt="Schermafbeelding 2024-03-22 195151" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/154087893/dda7db4d-3e95-4c1a-9395-cf0212a3bba1">

**Reply by dbuezas** [reply]
That should work!
look into universal functions and expressions ($fn and $ex) in the readme and the discussions. You'll find how to source data from multiple entities. With that you can populate the values in link

**Reply by qinguDLI** [reply]
Thanks a lot i will try!

**Reply by dbuezas** [reply]
Here's an untested starting point

```yaml
type: custom:plotly-graph
title: Dynamic Energy Distribution Overview
entities:
  - entity: sensor.power_consumption
    internal: true #these are here just to trigger updates
  - entity: sensor.power_return
    internal: true
  - entity: sensor.solar_panel_1
    internal: true
  - entity: sensor.solar_panel_2
    internal: true
  - entity: sensor.heat_pump
    internal: true
  - entity: ''
    type: sankey
    orientation: h
    node:
      pad: 15
      thickness: 30
      line:
        color: black
        width: 0.5
      label:
        - Power Consumption
        - Power Return
        - Phase 1 Supply
        - Phase 2 Supply
        - Phase 3 Supply
        - Solar Panel 1
        - Solar Panel 2
        - Heat Pump
        - Rest Energy Phase 1
        - Rest Energy Phase 2
        - Rest Energy Phase 3
      color:
        - "#1f77b4" # Power Consumption
        - "#ff7f0e" # Power Return
        - "#2ca02c" # Phase 1 Supply
        - "#d62728" # Phase 2 Supply
        - "#9467bd" # Phase 3 Supply
        - "#e377c2" # Solar Panel 1
        - "#7f7f7f" # Solar Panel 2
        - "#bcbd22" # Heat Pump
        - "#17becf" # Rest Energy Phase 1
        - "#8c564b" # Rest Energy Phase 2
        - "#e7ba52" # Rest Energy Phase 3
    link:
      source:
        - 0 # Power Consumption to...
        - 1 # Power Return to...
        - 6 # Solar Panel 1 to...
        - 7 # Solar Panel 2 to...
        - 8 # Heat Pump to...
      target:
        - 2 # Phase 1 Supply
        - 3 # Phase 2 Supply
        - 4 # Phase 3 Supply
        - 5 # Solar Panel 1
        - 5 # Solar Panel 2
        - 5 # Heat Pump
      value:
        - $ex hass.states('sensor.power_consumption').state
        - $ex hass.states('sensor.power_return').state
        - $ex hass.states('sensor.solar_panel_1').state
        - $ex hass.states('sensor.solar_panel_2').state
        - $ex hass.states('sensor.heat_pump').state
raw_plotly_config: false

```

**Comment by noctividus** [comment]
<img width="2132" height="970" alt="image" src="https://github.com/user-attachments/assets/6158f16c-f80d-45bc-bcac-5f0f78929beb" />

```yaml
type: custom:plotly-graph
title: Irrigation Distribution
grid_options:
  columns: full
  rows: 15
entities:
  - entity: input_number.station_front_yard_pots_and_plan_usage
    internal: true
  - entity: input_number.station_front_yard_palnter_drip_usage
    internal: true
  - entity: input_number.station_front_yard_planter_sprin_usage
    internal: true
  - entity: input_number.station_front_lawn_west_usage
    internal: true
  - entity: input_number.station_s05_f5_f_mid_law_usage
    internal: true
  - entity: input_number.station_s06_f6_f_e_lawn_usage
    internal: true
  - entity: input_number.station_s7_b1_bk_glf_lwn_usage
    internal: true
  - entity: input_number.station_backyard_lawn_rotary_usage
    internal: true
  - entity: input_number.station_backyard_lawn_sideline_h_usage
    internal: true
  - entity: input_number.station_zen_garden_lawn_usage
    internal: true
  - entity: input_number.station_backyard_lawn_back_edge_usage
    internal: true
  - entity: input_number.station_s13c4_n_fnc_mid_usage
    internal: true
  - entity: input_number.station_s19a5_w_fnce_mid_usage
    internal: true
  - entity: input_number.station_backyard_planter_north_b_usage
    internal: true
  - entity: input_number.station_s15c6_drip_n_fnc_usage
    internal: true
  - entity: input_number.station_nw_house_corner_planter_usage
    internal: true
  - entity: input_number.station_s17_a2_bbq_drip_usage
    internal: true
  - entity: input_number.station_patio_pots_drip_usage
    internal: true
  - entity: input_number.station_backyard_planter_west_usage
    internal: true
  - entity: input_number.station_drip_east_fence_back_usage
    internal: true
  - entity: input_number.station_zen_garden_planters_usage
    internal: true
  - entity: input_number.station_zen_garden_house_planter_usage
    internal: true
  - entity: input_number.station_west_drip_behind_spa_usage
    internal: true
  - entity: input_number.station_orchard_drip_usage
    internal: true
  - entity: input_number.station_s26_b7_drip_mist_usage
    internal: true
  - entity: input_number.station_orchard_drip_pots_usage
    internal: true
  - entity: input_number.station_zen_fountain_usage
    internal: true
  - entity: ""
    type: sankey
    orientation: h
    node:
      pad: 12
      thickness: 20
      label:
        - Total
        - Front Yard
        - Back Yard
        - Front Lawns
        - Front Planters
        - Back Lawns
        - Back Planters
        - Orchard
        - S04 West Lawn
        - S05 Middle Lawn
        - S06 East Lawn
        - S01 Pots
        - S02 Planter Drip
        - S03 Planter Sprinklers
        - S07 Golf Lawn
        - S08 Rotary
        - S09 Sideline
        - S10 Zen Lawn
        - S11 Back Edge
        - S13 North Fence Mid
        - S19 West Fence Mid
        - S14 North Planter
        - S15 North Fence Drip
        - S16 NW Corner
        - S17 BBQ Drip
        - S18 Patio Pots
        - S20 West Planter
        - S21 East Fence
        - S22 Zen Planters
        - S23 Zen House
        - S24 Spa Drip
        - S28 Zen Fountain
        - S25 Orchard Drip
        - S26 Orchard Mist
        - S27 Orchard Pots
    link:
      valueformat: .0f
      valuesuffix: " gal"
      source:
        - 0
        - 0
        - 1
        - 1
        - 2
        - 2
        - 2
        - 3
        - 3
        - 3
        - 4
        - 4
        - 4
        - 5
        - 5
        - 5
        - 5
        - 5
        - 5
        - 5
        - 6
        - 6
        - 6
        - 6
        - 6
        - 6
        - 6
        - 6
        - 6
        - 6
        - 6
        - 7
        - 7
        - 7
      target:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
        - 31
        - 32
        - 33
        - 34
      value:
        - >-
          $ex
          Number(hass.states['input_number.station_front_lawn_west_usage'].state||0)+Number(hass.states['input_number.station_s05_f5_f_mid_law_usage'].state||0)+Number(hass.states['input_number.station_s06_f6_f_e_lawn_usage'].state||0)+Number(hass.states['input_number.station_front_yard_pots_and_plan_usage'].state||0)+Number(hass.states['input_number.station_front_yard_palnter_drip_usage'].state||0)+Number(hass.states['input_number.station_front_yard_planter_sprin_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_s7_b1_bk_glf_lwn_usage'].state||0)+Number(hass.states['input_number.station_backyard_lawn_rotary_usage'].state||0)+Number(hass.states['input_number.station_backyard_lawn_sideline_h_usage'].state||0)+Number(hass.states['input_number.station_zen_garden_lawn_usage'].state||0)+Number(hass.states['input_number.station_backyard_lawn_back_edge_usage'].state||0)+Number(hass.states['input_number.station_s13c4_n_fnc_mid_usage'].state||0)+Number(hass.states['input_number.station_s19a5_w_fnce_mid_usage'].state||0)+Number(hass.states['input_number.station_backyard_planter_north_b_usage'].state||0)+Number(hass.states['input_number.station_s15c6_drip_n_fnc_usage'].state||0)+Number(hass.states['input_number.station_nw_house_corner_planter_usage'].state||0)+Number(hass.states['input_number.station_s17_a2_bbq_drip_usage'].state||0)+Number(hass.states['input_number.station_patio_pots_drip_usage'].state||0)+Number(hass.states['input_number.station_backyard_planter_west_usage'].state||0)+Number(hass.states['input_number.station_drip_east_fence_back_usage'].state||0)+Number(hass.states['input_number.station_zen_garden_planters_usage'].state||0)+Number(hass.states['input_number.station_zen_garden_house_planter_usage'].state||0)+Number(hass.states['input_number.station_west_drip_behind_spa_usage'].state||0)+Number(hass.states['input_number.station_zen_fountain_usage'].state||0)+Number(hass.states['input_number.station_orchard_drip_usage'].state||0)+Number(hass.states['input_number.station_s26_b7_drip_mist_usage'].state||0)+Number(hass.states['input_number.station_orchard_drip_pots_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_front_lawn_west_usage'].state||0)+Number(hass.states['input_number.station_s05_f5_f_mid_law_usage'].state||0)+Number(hass.states['input_number.station_s06_f6_f_e_lawn_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_front_yard_pots_and_plan_usage'].state||0)+Number(hass.states['input_number.station_front_yard_palnter_drip_usage'].state||0)+Number(hass.states['input_number.station_front_yard_planter_sprin_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_s7_b1_bk_glf_lwn_usage'].state||0)+Number(hass.states['input_number.station_backyard_lawn_rotary_usage'].state||0)+Number(hass.states['input_number.station_backyard_lawn_sideline_h_usage'].state||0)+Number(hass.states['input_number.station_zen_garden_lawn_usage'].state||0)+Number(hass.states['input_number.station_backyard_lawn_back_edge_usage'].state||0)+Number(hass.states['input_number.station_s13c4_n_fnc_mid_usage'].state||0)+Number(hass.states['input_number.station_s19a5_w_fnce_mid_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_backyard_planter_north_b_usage'].state||0)+Number(hass.states['input_number.station_s15c6_drip_n_fnc_usage'].state||0)+Number(hass.states['input_number.station_nw_house_corner_planter_usage'].state||0)+Number(hass.states['input_number.station_s17_a2_bbq_drip_usage'].state||0)+Number(hass.states['input_number.station_patio_pots_drip_usage'].state||0)+Number(hass.states['input_number.station_backyard_planter_west_usage'].state||0)+Number(hass.states['input_number.station_drip_east_fence_back_usage'].state||0)+Number(hass.states['input_number.station_zen_garden_planters_usage'].state||0)+Number(hass.states['input_number.station_zen_garden_house_planter_usage'].state||0)+Number(hass.states['input_number.station_west_drip_behind_spa_usage'].state||0)+Number(hass.states['input_number.station_zen_fountain_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_orchard_drip_usage'].state||0)+Number(hass.states['input_number.station_s26_b7_drip_mist_usage'].state||0)+Number(hass.states['input_number.station_orchard_drip_pots_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_front_lawn_west_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_s05_f5_f_mid_law_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_s06_f6_f_e_lawn_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_front_yard_pots_and_plan_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_front_yard_palnter_drip_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_front_yard_planter_sprin_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_s7_b1_bk_glf_lwn_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_backyard_lawn_rotary_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_backyard_lawn_sideline_h_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_zen_garden_lawn_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_backyard_lawn_back_edge_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_s13c4_n_fnc_mid_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_s19a5_w_fnce_mid_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_backyard_planter_north_b_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_s15c6_drip_n_fnc_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_nw_house_corner_planter_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_s17_a2_bbq_drip_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_patio_pots_drip_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_backyard_planter_west_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_drip_east_fence_back_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_zen_garden_planters_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_zen_garden_house_planter_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_west_drip_behind_spa_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_zen_fountain_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_orchard_drip_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_s26_b7_drip_mist_usage'].state||0)
        - >-
          $ex
          Number(hass.states['input_number.station_orchard_drip_pots_usage'].state||0)
```
