### DISCUSSION TITLE
Smooth value transitions

### DISCUSSION THREAD

**Discussion by Photelegy** [dbuezas/lovelace-plotly-graph-card#40] [Q&A] [answered]
Is there a way to make the values look smoother?
So that it doesn't look so blocky and has vertical lines (Picture1) but make straight lines between the values (red line in Picture2).

**(Picture1) Tha's how it is now:**
![image](https://user-images.githubusercontent.com/61714583/168307725-6fbf96e9-9492-4a39-9d17-cde8c524271e.png)

**(Picture2) My wish would look somewhat like the red line:**
![image](https://user-images.githubusercontent.com/61714583/168308088-83a16fff-da2f-4139-94a7-91e9f8bef08d.png)

PS: Really awesome card!!!

**Comment by dbuezas** [comment, marked as answer]
Hey @Photelegy,
thanks for the kind words!
you are in luck, what you are after is already possible:

```yaml
[...]
entities:
  - entity: sensor.temperature_xyz
     line:
       shape: linear # also try spline!
       # you can also set the width, color, dash, ....
```
more here: https://plotly.com/javascript/reference/scatter/#scatter-line-shape

Also do check out the yamls in the discussions, there are lots of inspirations with screenshots there.
