### DISCUSSION TITLE
Standardizing Axis Ranges

### DISCUSSION THREAD

**Discussion by wormuths** [dbuezas/lovelace-plotly-graph-card#401] [Q&A] [answered]
Good day,

I have the following card to show the size of my Home Assistant database, with an overlap showing the change from the previous month.

![Screenshot_20240324_150519](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/47436307/adba2e1c-feb9-482c-9236-25ec95bad7c6)

The issue is I can't figure out how to standardize the axis values.  As you see, the first couple month increase a great deal, and that value overwrites the whole other bar.  Is there a way to align the left and right axis values to better display this?

```
type: custom:plotly-graph
config:
  displayModeBar: false
layout:
  height: 250
  dragmode: pan
  showlegend: true
  paper_bgcolor: '#EFDECD'
  plot_bgcolor: '#EFDECD'
  xaxis:
    tickfont:
      color: '#000000'
  yaxis:
    tickfont:
      color: '#000000'
hours_to_show: 1y
entities:
  - entity: sensor.home_assistant_v2_db_size
    name: Current Database
    statistic: mean
    period: month
    type: bar
    marker:
      color: rgb(10, 55, 58)
    texttemplate: '%{y:0.0f}'
  - entity: sensor.home_assistant_v2_db_size
    name: Change
    statistic: mean
    period: month
    type: bar
    marker:
      color: rgb(255, 152, 0)
    texttemplate: '%{y:0.2f}'
    filters:
      - delta: null
```

Thanks for any help you can provide....
