### DISCUSSION TITLE
shankey energy graph

### DISCUSSION THREAD

**Discussion by qinguDLI** [dbuezas/lovelace-plotly-graph-card#402] [Show and tell]
Tried to make a sankey diagram for energy usage, almost there. Only thing missing is de conversion of Vars to the value.

```
type: custom:plotly-graph
title: Energieverbruik Dag
entities:
  - entity: sensor.2001ma
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: Van_a
  - entity: sensor.2002ma
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: Van_b
  - entity: sensor.1001ma
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: Naar_a
  - entity: sensor.1002ma
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: Naar_b
  - entity: sensor.1003ma
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: Naar_c
  - entity: sensor.7034m
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: WP_a
  - entity: sensor.7035m
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: WP_b
  - entity: sensor.7037m
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: WP_c
  - entity: sensor.3001m
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: PV_d
  - entity: sensor.4001m
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: PV_s
  - entity: sensor.1001ma
    internal: true
    type: bar
    statistic: state
    name: fase 1 Rest 1
    period: day
    filters:
      - derivate: d
      - map_y: >-
          parseFloat(ys[i]) - parseFloat(vars.Van_a.ys[i]) +
          parseFloat(vars.PV_d.ys[i]) - parseFloat(vars.WP_c.ys[i])
      - store_var: Rest_a
  - entity: sensor.3001m
    internal: true
    type: bar
    name: van  fase 1 naar pvdak
    statistic: state
    period: day
    filters:
      - derivate: d
      - map_y: parseFloat(ys[i]) - parseFloat(vars.Van_a.ys[i])
      - store_var: PV_d_t
  - entity: sensor.1002ma
    internal: true
    type: bar
    statistic: state
    name: fase 2 Rest 2
    period: day
    filters:
      - derivate: d
      - map_y: >-
          parseFloat(ys[i]) - parseFloat(vars.Van_b.ys[i]) +
          parseFloat(vars.PV_s.ys[i]) - parseFloat(vars.WP_a.ys[i])
      - store_var: Rest_b
  - entity: sensor.4001m
    internal: true
    type: bar
    name: van  fase 1 naar pvdak
    statistic: state
    period: day
    filters:
      - derivate: d
      - map_y: parseFloat(ys[i]) - parseFloat(vars.Van_b.ys[i])
      - store_var: PV_s_t
  - entity: sensor.1003ma
    internal: true
    markers: null
    type: bar
    statistic: state
    name: fase 2 Rest 2
    period: day
    filters:
      - derivate: d
      - map_y: parseFloat(ys[i]) - parseFloat(vars.WP_b.ys[i])
      - store_var: Rest_c
  - entity: ''
    type: sankey
    orientation: h
    node:
      pad: 10
      thickness: 25
      line:
        color: black
        width: 0.5
      label:
        - deze
        - Van net
        - Naar net
        - Fase 1
        - Fase 2
        - Fase 3
        - PV dak
        - Rest 1
        - PV schuur
        - Rest 2
        - Warmtepomp
        - Rest 3
      color:
        - '#006b3c'
        - '#ff4500'
        - '#006b3c'
        - '#0047ab'
        - '#00ffff'
        - '#007fff'
        - '#fdee00'
        - '#00bfff'
        - '#fdee00'
        - '#ff0800'
        - '#8a2be2'
        - '#00cc99'
    link:
      color:
        - '#ffe13599'
        - '#ffe13599'
        - '#0047ab99'
        - '#00ffff99'
        - '#007fff99'
        - '#00bfff99'
        - '#ffe13599'
        - '#ff080099'
        - '#00cc9999'
        - '#ffe13599'
        - '#8a2be299'
        - '#8a2be299'
        - '#8a2be299'
      arrowlen: 8
      source:
        - 2
        - 2
        - 1
        - 1
        - 1
        - 3
        - 3
        - 4
        - 5
        - 4
        - 5
        - 4
        - 3
      target:
        - 8
        - 6
        - 3
        - 4
        - 5
        - 7
        - 6
        - 9
        - 11
        - 8
        - 10
        - 10
        - 10
      value:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 6
        - 5
        - 4
        - 3
        - 2
        - 1
raw_plotly_config: false

```

Looks like this:
<img width="680" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/154087893/659a438f-d87e-477e-af63-25ba3c587011">

**Comment by dbuezas** [comment]
Very cool! :🎉

**Comment by qinguDLI** [comment]
@dbuezas  Tried to make it work yesterday but can't figure something out.

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/154087893/0538558f-9af0-45e3-9526-cc7dd87f53d1)

If i put the fn at the red arrow but then like this:
 `fn: $fn  ({ys, vars}) => {vars.Test = ys[ys.length-1];}`
 it takes the current value. And with the following code in the value:

```
  value:
        - $fn ({ vars }) => vars.Test
```

at actually works. However i want the derivate so the change of today, and after i did some calculation with map_y, not the last known value of the sensor.

**Reply by dbuezas** [reply]
I'm not following. Can you clarify differently?

**Reply by qinguDLI** [reply]
To write the Values:  you need a number not a string or sensor so basically a single state.
If i use the following code to make a variable, i get the current state so lets say 123.456 kWh a.k.a. the current state of sensor.1003ma:

```
  - entity: sensor.1003ma
    internal: true
    statistic: state
    period: day
    fn: $fn  ({ys, vars}) => {vars.Test = ys[ys.length-1];}
    filters:
      - derivate: d
      - map_y: parseFloat(ys[i]) - parseFloat(vars.WP_b.ys[i])

```

I want the value over the new sensor including the filters, zo basically the current state of var.Rest_c
 ```
 - entity: sensor.1003ma
    internal: true
    statistic: state
    period: day
    filters:
      - derivate: d
      - map_y: parseFloat(ys[i]) - parseFloat(vars.WP_b.ys[i])
      - store_var: Rest_c
```
The code to place the call up the variable at value is als followed,:
```
      value:
        - $fn ({ vars }) => vars.Test
        - $fn ({ vars }) => vars.Rest_c

```
This results in:

 Value:
  - 123.456
  - 0 (Doesn't work basically)

**Reply by qinguDLI** [reply]
Another night of trying with different variants of code, $fn $ex. I’m lost any clues?

**Reply by dbuezas** [reply]
It may ve that one of the sensors is missing some data and one of the sensors doesn't get to the last index, which would result in NaN for the last value.
I suggest you plot a trace with the whole content of the rest_c and check that values get to the end.
If that is the case, you can:
* Reverse the Arrays before computing the diff and then reverse back
* Add an extra data point manually with the xs[0] of the other one and then use resample to fill the gap completely and ensure indexes are aligned
* map manually using fn and ensuring alignment is done looking at the x values instead of the index (i)


Regarding $ex, it is exactly the same as $fn, except that the function signature is added automatically (`({xs,ys,vars,......})=>`). That is literally added as a prefix to the string before evaluating it.

Other than that, your approach looks very reasonable to me :)

Looking forward to seeing the final plot!

**Reply by qinguDLI** [reply]
I have a clue where the problem is. The value of the sensors are all known checked it with a bar graph.
```
  - entity: sensor.1003ma
    internal: true
    statistic: state
    period: day
    fn: $fn  ({ys, vars}) => {vars.Test = ys[ys.length-1];}
    filters:
      - derivate: d
      - map_y: parseFloat(ys[i]) - parseFloat(vars.WP_b.ys[i])
   
```
The above code gives value : 215, current value of sensor.1003m.

```
  - entity: sensor.1003ma
    internal: true
    statistic: state
    period: day
    filters:
      - derivate: d
      - map_y: parseFloat(ys[i]) - parseFloat(vars.WP_b.ys[i])
    fn: $fn  ({ys, vars}) => {vars.Test = ys[ys.length-1];}
```

This code probably  gives 0 what would be correct because at point ys.length-1 the value would be 0.
using the code below, without the derivate:
```
  - entity: sensor.1003ma
    internal: true
    statistic: state
    period: day
    filters:
      - map_y: parseFloat(ys[i]) - parseFloat(vars.WP_b.ys[i])
    fn: $fn  ({ys, vars}) => {vars.Test = ys[ys.length-1];}
```
The code probably give the value 0.
```
  - entity: sensor.1003ma
    internal: true
    statistic: state
    period: day
    filters:
      - derivate: d
    fn: $fn  ({ys, vars}) => {vars.Test = ys[ys.length-1];}
```
This give again 0

The problem is in the ys[ys.length-1]. In both cases there is a shift in data so in de parsefloat(ys[i]) it reshuffles data and with the derivate it replaces date in time. while probably the ys.length stays the same. So i think i need a way to look at the last known value. without looking at ys.

**Reply by dbuezas** [reply]
See the debugging section in the readme, you'll be able to confirm your suspicions

**Reply by qinguDLI** [reply]
I tried the debugging section but what to look for?
<img width="248" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/154087893/96fd22fa-b836-4ac7-ab79-236c73b4675f">

This looks like there is an array in Ys. for the vars but:

<img width="147" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/154087893/8cdced94-d016-4ad1-b675-01581038e97d">

The ys of all the vars is NaN however if i plot them as a bar graph i get this:

<img width="563" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/154087893/784edf18-4a2f-448f-983e-3d5c0b4910ca">

they all give a correct value..... i'm lost.

**Reply by dbuezas** [reply]
Show me your full yaml

**Reply by qinguDLI** [reply]
```
type: custom:plotly-graph
title: Energieverbruik Dag
entities:
  - entity: sensor.2001ma
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: Van_a
  - entity: sensor.2002ma
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: Van_b
  - entity: sensor.1001ma
    internal: true
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: Naar_a
      - resample: 1h
  - entity: sensor.1002ma
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: Naar_b
  - entity: sensor.1003ma
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: Naar_c
  - entity: sensor.7034m
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: WP_a
  - entity: sensor.7035m
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: WP_b
  - entity: sensor.7037m
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: WP_c
  - entity: sensor.3001m
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: PV_d
  - entity: sensor.4001m
    internal: true
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
      - store_var: PV_s
  - entity: sensor.1001ma
    internal: true
    type: bar
    statistic: state
    name: fase 1 Rest 1
    period: day
    filters:
      - derivate: d
      - map_y: >-
          parseFloat(ys[i]) - parseFloat(vars.Van_a.ys[i]) +
          parseFloat(vars.PV_d.ys[i]) - parseFloat(vars.WP_c.ys[i])
      - store_var: Rest_a
  - entity: sensor.3001m
    internal: true
    type: bar
    name: van  fase 1 naar pvdak
    statistic: state
    period: day
    filters:
      - derivate: d
      - map_y: parseFloat(ys[i]) - parseFloat(vars.Van_a.ys[i])
      - store_var: PV_d_t
  - entity: sensor.1002ma
    internal: true
    type: bar
    statistic: state
    name: fase 2 Rest 2
    period: day
    filters:
      - derivate: d
      - map_y: >-
          parseFloat(ys[i]) - parseFloat(vars.Van_b.ys[i]) +
          parseFloat(vars.PV_s.ys[i]) - parseFloat(vars.WP_a.ys[i])
      - store_var: Rest_b
  - entity: sensor.4001m
    internal: true
    type: bar
    name: van  fase 1 naar pvdak
    statistic: state
    period: day
    filters:
      - derivate: d
      - map_y: parseFloat(ys[i]) - parseFloat(vars.Van_b.ys[i])
  - entity: sensor.1003ma
    internal: true
    type: bar
    statistic: state
    name: fase 2 Rest 2
    period: day
    filters:
      - derivate: d
      - map_y: parseFloat(ys[i]) - parseFloat(vars.WP_b.ys[i])
    fn: $fn  ({ys, vars}) => {vars.Rest_c = ys[ys.length-1];}
  - entity: ''
    internal: false
    type: sankey
    orientation: h
    node:
      pad: 10
      thickness: 25
      line:
        color: black
        width: 0.5
      label:
        - deze
        - Van net
        - Naar net
        - Fase 1
        - Fase 2
        - Fase 3
        - PV dak
        - Rest 1
        - PV schuur
        - Rest 2
        - Warmtepomp
        - Rest 3
      color:
        - '#006b3c'
        - '#ff4500'
        - '#006b3c'
        - '#0047ab'
        - '#00ffff'
        - '#007fff'
        - '#fdee00'
        - '#00bfff'
        - '#fdee00'
        - '#ff0800'
        - '#8a2be2'
        - '#00cc99'
    link:
      color:
        - '#ffe13599'
        - '#ffe13599'
        - '#0047ab99'
        - '#00ffff99'
        - '#007fff99'
        - '#00bfff99'
        - '#ffe13599'
        - '#ff080099'
        - '#00cc9999'
        - '#ffe13599'
        - '#8a2be299'
        - '#8a2be299'
        - '#8a2be299'
      arrowlen: 8
      source:
        - 2
        - 2
        - 1
        - 1
        - 1
        - 3
        - 3
        - 4
        - 5
        - 4
        - 5
        - 4
        - 3
      target:
        - 8
        - 6
        - 3
        - 4
        - 5
        - 7
        - 6
        - 9
        - 11
        - 8
        - 10
        - 10
        - 10
      value:
        - $fn ({ vars }) => vars.Rest_c
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 6
        - 5
        - 4
        - 3
        - 2
        - 1
raw_plotly_config: false

```

**Reply by dbuezas** [reply]
Where you have 
```
    fn: $fn  ({ys, vars}) => {vars.Rest_c = ys[ys.length-1];}
```

Replace with
```
    fn: $fn  ({ys, vars}) => {debugger; vars.Rest_c = ys[ys.length-1];}
```

And check what is the content of ys in the dev tools

**Reply by qinguDLI** [reply]
It's NaN, as suspected. it just doesn't store the vars in de ys domain.

**Reply by dbuezas** [reply]
The whole array is NaNs?
Then check the contents of ys and the other sensor before doing the subtraction. Also check the length of both arrays

**Reply by qinguDLI** [reply]
I deleted all the sensors and made a new file with just 1 sensor plain and simpel with de derivate in it.
Then it's  still says the following


<img width="107" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/154087893/c23ed4d0-1a76-453f-a6a9-01d36e65e7a1">

**Reply by dbuezas** [reply]
Good, how's the data before derivating?

**Reply by qinguDLI** [reply]
<img width="150" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/154087893/faebddde-f7ec-49ca-8dbc-dab7ef9d3b40">

**Reply by dbuezas** [reply]
Well that's where the problem lies: You can't derivate a single number.

**Comment by qinguDLI** [comment]
Got it!, had to make some new sensors, When you do a filter nomather which one it does work in the sankey.

<img width="500" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/154087893/79bd69b8-b16e-494b-a5e9-72f06157181c">

Here's the code for now:

```
type: custom:plotly-graph
title: Energieverbruik Dag
entities:
  - entity: sensor.1010
    internal: true
    fn: $fn  ({ys, vars}) => {vars.TF1 = ys[ys.length-1] }
  - entity: sensor.1020
    internal: true
    fn: $fn  ({ys, vars}) => {vars.TF2 = ys[ys.length-1] }
  - entity: sensor.1030
    internal: true
    fn: $fn  ({ys, vars}) => {vars.TF3 = ys[ys.length-1] }
  - entity: sensor.2010
    internal: true
    fn: $fn  ({ys, vars}) => {vars.RF1 = ys[ys.length-1] }
  - entity: sensor.2020
    internal: true
    fn: $fn  ({ys, vars}) => {vars.RF2 = ys[ys.length-1] }
  - entity: sensor.7034d
    internal: true
    fn: $fn  ({ys, vars}) => {vars.WPF1 = ys[ys.length-1] }
  - entity: sensor.7035d
    internal: true
    fn: $fn  ({ys, vars}) => {vars.WPF2 = ys[ys.length-1] }
  - entity: sensor.7037d
    internal: true
    fn: $fn  ({ys, vars}) => {vars.WPF3 = ys[ys.length-1] }
  - entity: sensor.3010
    internal: true
    fn: $fn  ({ys, vars}) => {vars.PVD1 = ys[ys.length-1] }
  - entity: sensor.4010
    internal: true
    fn: $fn  ({ys, vars}) => {vars.PVD2 = ys[ys.length-1]}
  - entity: sensor.5903
    internal: true
    fn: $fn  ({ys, vars}) => {vars.RES1 = ys[ys.length-1] }
  - entity: sensor.5904
    internal: true
    fn: $fn  ({ys, vars}) => {vars.RES2 = ys[ys.length-1] }
  - entity: sensor.5905
    internal: true
    fn: $fn  ({ys, vars}) => {vars.RES3 = ys[ys.length-1]  }
  - entity: ''
    internal: false
    type: sankey
    orientation: h
    node:
      pad: 10
      thickness: 25
      line:
        color: black
        width: 0.5
      label:
        - deze
        - Van net
        - Naar net
        - Fase 1
        - Fase 2
        - Fase 3
        - PV dak
        - Rest 1
        - PV schuur
        - Rest 2
        - Warmtepomp
        - Rest 3
      color:
        - '#006b3c'
        - '#ff4500'
        - '#006b3c'
        - '#0047ab'
        - '#00ffff'
        - '#007fff'
        - '#fdee00'
        - '#00bfff'
        - '#fdee00'
        - '#ff0800'
        - '#8a2be2'
        - '#00cc99'
    link:
      color:
        - '#ffe13599'
        - '#ffe13599'
        - '#0047ab99'
        - '#00ffff99'
        - '#007fff99'
        - '#00bfff99'
        - '#ffe13599'
        - '#ff080099'
        - '#00cc9999'
        - '#ffe13599'
        - '#8a2be299'
        - '#8a2be299'
        - '#8a2be299'
      arrowlen: 8
      source:
        - 2
        - 2
        - 1
        - 1
        - 1
        - 3
        - 3
        - 4
        - 5
        - 4
        - 5
        - 4
        - 3
      target:
        - 8
        - 6
        - 3
        - 4
        - 5
        - 7
        - 6
        - 9
        - 11
        - 8
        - 10
        - 10
        - 10
      value:
        - $fn ({ vars }) => vars.RF2
        - $fn ({ vars }) => vars.RF1
        - $fn ({ vars }) => vars.TF1
        - $fn ({ vars }) => vars.TF2
        - $fn ({ vars }) => vars.TF3
        - $fn ({ vars }) => vars.RES1
        - $fn ({ vars }) => vars.PVD1
        - $fn ({ vars }) => vars.RES2
        - $fn ({ vars }) => vars.RES3
        - $fn ({ vars }) => vars.PVD2
        - $fn ({ vars }) => vars.WPF3
        - $fn ({ vars }) => vars.WPF2
        - $fn ({ vars }) => vars.WPF1
raw_plotly_config: false

```
NOTE: Nagative values are not displayed in the diagram. 


Things to do:
- Labels at the outside istead of in the graph, and the values behind them
- In the hover the decimation, surfix
- In the hover the smaler values < 1 are displayed at 123M but that has to be 0,1 kWh.

@dbuezas Thanks for al the help, i will post again when it's finished, the plotly site give a lot of information about the TO do and also the Q&A is a valuable resource
