### DISCUSSION TITLE
Total of each bar in a stacked graph?

### DISCUSSION THREAD

**Discussion by droidgren** [dbuezas/lovelace-plotly-graph-card#405] [Q&A] [answered]
Is possible, somehow, to show a label of the total of each bar in a stacked graph? 

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/354317/fbb62878-546c-44c2-a120-d3fa545d9504)

I am using this code

```type: custom:plotly-graph
title: Cost per day
entities:
  - entity: sensor.dagens_varmekostnad
    name: Värme
    unit_of_measurement: SEK
    texttemplate: ' %{y:.0f}'
    type: bar
    statistic: sum
    period: day
    filters:
      - delta
      - filter: i>0
    marker:
      color: '#FF9800'
  - entity: sensor.dagens_laddkostnad
    name: Laddkostnad
    unit_of_measurement: SEK
    texttemplate: ' %{y:.0f}'
    type: bar
    statistic: sum
    period: day
    filters:
      - delta
      - filter: i>0
    marker:
      color: '#3498DB'
  - entity: sensor.dagens_kostnad_ovrigt
    name: Övrigt
    unit_of_measurement: SEK
    texttemplate: ' %{y:.0f}'
    type: bar
    statistic: sum
    period: day
    filters:
      - delta
      - filter: i>0
    marker:
      color: '#E74C3C'
hours_to_show: 9d
refresh_interval: 10
autorange_after_scroll: true
ticklabeloverflow: allow
layout:
  barmode: stack
  xaxis:
    tickformat: '%a'
    tickangle: -45
    hoverformat: '%B %Y'
    autorange: true
    dticks: 86400000
    nticks: 9
  yaxis:
    autorange: true
    griddash: dot
    overlaying: false
    visible: true
    showgrid: true
defaults:
  yaxes:
    fixedrange: true
```

**Comment by dbuezas** [comment]
You could add another trace, set it to transparent, hide it from the legend, add all values together using $ex and use the text attribute to make it show the totals

**Reply by droidgren** [reply]
Do you mean another entity? Do you have an example how to sum using $ex? I have never done that. Thanks!

**Reply by dbuezas** [reply]
Yes, another entity.

something like:
<img width="498" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/777196/f51e6ed5-ba0a-4afb-890a-89816881ac36">
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.energy_backofen
    type: bar
    filters:
      - resample
      - force_numeric
      - store_var: a
      
  - entity: sensor.energy_beamer
    type: bar
    filters:
      - resample
      - force_numeric
      - store_var: b
      
  - entity: ""
    type: bar
    name: sum
    unit_of_measurement: kWh
    text: $ex vars.a.ys.map((y,i) =>(y+vars.b.ys[i]).toFixed(2))
    showlegend: false
    marker:
      color: transparent
    filters:
      - load_var: a
      - map_y: 1
      
layout:
  barmode: stack

```

**Reply by droidgren** [reply]
Thanks works pretty well, except that autorange doesn't take the extra entity account. Is that possible to solve?
I tried specify fixed range options but does not seem to work. 
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/354317/e5660476-66c0-4c3c-9b72-8b1b51a74482)


```
type: custom:plotly-graph
title: Cost per day
entities:
  - entity: sensor.dagens_varmekostnad
    name: Värme
    unit_of_measurement: SEK
    texttemplate: ' %{y:.0f}'
    type: bar
    statistic: sum
    period: day
    filters:
      - delta
      - filter: i>0
      - force_numeric
      - store_var: a
    marker:
      color: '#FF9800'
  - entity: sensor.dagens_laddkostnad
    name: Laddkostnad
    unit_of_measurement: SEK
    texttemplate: ' %{y:.0f}'
    type: bar
    statistic: sum
    period: day
    filters:
      - delta
      - filter: i>0
      - force_numeric
      - store_var: b
    marker:
      color: '#3498DB'
  - entity: sensor.dagens_kostnad_ovrigt
    name: Övrigt
    unit_of_measurement: SEK
    texttemplate: ' %{y:.0f}'
    type: bar
    statistic: sum
    period: day
    filters:
      - delta
      - filter: i>0
      - force_numeric
      - store_var: c
    marker:
      color: '#E74C3C'
  - entity: ''
    type: bar
    name: sum
    unit_of_measurement: SEK
    text: $ex vars.a.ys.map((y,i) =>(y+vars.b.ys[i]+vars.c.ys[i]).toFixed(0))
    showlegend: false
    marker:
      color: transparent
    filters:
      - load_var: a
      - map_y: 1
hours_to_show: 9d
refresh_interval: 10
autorange_after_scroll: true
ticklabeloverflow: allow
layout:
  barmode: stack
  xaxis:
    tickformat: '%a'
    tickangle: -45
    hoverformat: '%B %Y'
    autorange: true
    dticks: 86400000
    nticks: 9
  yaxis:
    fixedrange: true
    range:
      - 10
      - 90
    griddash: dot
    overlaying: false
    visible: true
    showgrid: true
```

**Comment by dbuezas** [comment, marked as answer]
Just make map_y: 1 bigger

**Reply by droidgren** [reply]
Thanks! Would never have guessed that. :)

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/354317/b39bf64b-19aa-4990-a2ab-6f320e91cfec)

**Comment by andreamag00** [comment]
Hi guys,
I tried to copy your (super clever) solution to show the total number above a stacked bar chart.
Unfortunately, as you can see from the image, in my case it doesn’t work (I can only display the exact value from map_y, not the sum of the other bars), and I can’t figure out why… The only difference I can see between my chart and the ones in the posts above is that I’m using statistics: state (because I’m plotting electricity total_increasing sensors in my case).
If you could be so kind as to give me a suggestion, I’d be really grateful!
Anyway, thanks a lot in any case!
Have a great day!

<img width="1403" height="518" alt="Screenshot 2025-09-25 alle 20 52 53" src="https://github.com/user-attachments/assets/204fbbb5-0ed5-41e7-9aad-cafb04884f7a" />


```
type: custom:plotly-graph
hours_to_show: 7d
autorange_after_scroll: true
layout:
  barcornerradius: 2
  barmode: stack
  height: 500
  margin:
    l: 30
    r: 10
  paper_bgcolor: transparent
  plot_bgcolor: transparent
  xaxis:
    rangeselector:
      "y": 1.04
      x: 0.03
      bgcolor: rgba(130,130,130,0.4)
      buttons:
        - count: 1
          step: day
        - count: 7
          step: day
        - count: 1
          step: month
        - count: 6
          step: month
        - count: 1
          step: year
  yaxis:
    fixedrange: true
    rangemode: tozero
  legend:
    orientation: h
    x: -0.02
    "y": -0.1
    yanchor: top
    xanchor: left
    indentation: -10
  hovermode: x unified
defaults:
  entity:
    unit_of_measurement: ""
    period:
      0s: 5minute
      24h: hour
      2d: day
      2M: month
    texttemplate: "%{y:.2f}"
    textposition: inside
    hovertemplate: "%{fullData.name}: %{y:.2f} kwh<extra></extra>"
config:
  scrollZoom: false
  modeBarButtonsToRemove:
    - select2d
    - lasso2d
    - autoScale2d
    - resetScale2d
entities:
  - entity: sensor.teatrino_1_blu_altre_fonti_energia_consumata_kwh
    name: altre fonti
    type: bar
    statistic: state
    filters:
      - delta
      - filter: i>0
      - force_numeric
      - store_var: a
    marker:
      color: rgba(96,96,96,0.5)
      line:
        width: 0.2
        color: rgba(96,96,96,1)
  - entity: >-
      sensor.shelly_1pm_teatrino_1_blu_bagno_scaldasalviette_energia_consumata_kwh
    name: scaldasalviette
    type: bar
    statistic: state
    filters:
      - delta
      - filter: i>0
      - force_numeric
      - store_var: b
    marker:
      color: rgba(255,138,183,0.5)
      line:
        width: 0.4
        color: rgba(255,138,183,1)
  - entity: sensor.teatrino_1_blu_luci_energia_consumata_kwh
    name: luci
    type: bar
    statistic: state
    filters:
      - delta
      - filter: i>0
      - force_numeric
      - store_var: c
    marker:
      color: rgba(244,189,74,0.5)
      line:
        width: 0.2
        color: rgba(244,189,74,1)
  - entity: >-
      sensor.shelly_1pm_teatrino_1_blu_lavanderia_lavatrice_energia_consumata_kwh
    name: lavatrice
    type: bar
    statistic: state
    filters:
      - delta
      - filter: i>0
      - force_numeric
      - store_var: d
    marker:
      color: rgba(1,171,99,0.5)
      line:
        width: 0.4
        color: rgba(1,171,99,1)
  - entity: >-
      sensor.shelly_em_gen_3_teatrino_1_blu_piastra_induzione_energia_consumata_kwh
    name: induzione
    type: bar
    statistic: state
    filters:
      - delta
      - filter: i>0
      - force_numeric
      - store_var: e
    marker:
      color: rgba(156,107,78,0.5)
      line:
        width: 0.2
        color: rgba(156,107,78,1)
  - entity: sensor.shelly_em_gen_3_teatrino_1_blu_forno_energia_consumata_kwh
    name: forno
    type: bar
    statistic: state
    filters:
      - delta
      - filter: i>0
      - force_numeric
      - store_var: f
    marker:
      color: rgba(164,99,242,0.5)
      line:
        width: 0.2
        color: rgba(164,99,242,1)
  - entity: sensor.shelly_pro_em_teatrino_1_blu_fan_coil_energia_consumata_kwh
    name: fan coil
    type: bar
    statistic: state
    filters:
      - delta
      - filter: i>0
      - force_numeric
      - store_var: g
    marker:
      color: rgba(255,114,92,0.5)
      line:
        width: 0.4
        color: rgba(255,114,92,1)
  - entity: sensor.shelly_1pm_teatrino_1_blu_lavanderia_boiler_energia_consumata_kwh
    name: boiler
    type: bar
    statistic: state
    filters:
      - delta
      - filter: i>0
      - force_numeric
      - store_var: h
    marker:
      color: rgba(66,105,208,0.5)
      line:
        width: 0.4
        color: rgba(66,105,208,1)
  - entity: ""
    type: bar
    name: totale
    text: $ex vars.a.ys.map((y,i) =>(y+vars.b.ys[i]+vars.c.ys[i]+vars.d.ys[i]+vars.e.ys[i]+vars.f.ys[i]+vars.g.ys[i]+vars.h.ys[i]).toFixed(0))
    showlegend: false
    marker:
      color: transparent
    filters:
      - load_var: a
      - map_y: 1
```

**Reply by Blonder-Hans** [reply]
Hallo, I had the same result in indicating the sum. With me, the following code works for the new total entities (left and right bar slightly different).
<img width="574" height="755" alt="Screenshot_20260423_185343_Home Assistant" src="https://github.com/user-attachments/assets/6031cd3a-81b0-404f-ba48-4d0d5252e807" />

```
entities:
  - entity: sensor.hausverbrauch_taglich # template sensor for forming the sum "household consumption" in the left bar
    type: scatter
    mode: text
    texttemplate: "%{y:.0f}"
    textfont:
      color: white
    textposition: top
    showlegend: false
    marker:
      color: transparent
    time_offset: "-3h"
  - entity: sensor.erzeugt_taglich # template sensor for forming the sum "solar production" in the right bar
    type: scatter
    mode: markers+text
    texttemplate: "PV:%{y:.1f}" # one decimal place
    textfont:
      color: yellow
    textposition: top
    showlegend: false
    marker:
      color: red # to hide the marker dot: transparent
      size: 10
    time_offset: 3h

```
