### DISCUSSION TITLE
How to move up the title

### DISCUSSION THREAD

**Discussion by Photelegy** [dbuezas/lovelace-plotly-graph-card#41] [Q&A] [answered]
First I had a problem that when I enable "rangeselector buttons" they are over the title so the title is mostly hidden.
But there is a way to "move" title on top.
```
...
margin:
...
    t: 90
...
```
![image](https://user-images.githubusercontent.com/61714583/168315351-914c2d7f-1cec-489b-9ccb-36b600a02991.png)

```
type: custom:plotly-graph
entities:
  - entity: sensor.gersau_temperature
  - entity: sensor.openweathermap_temperature
  - entity: sensor.openweathermap_feels_like_temperature
  - entity: sensor.sensor_motion_eingang_temperature
    name: Eingang (indoor)
hours_to_show: 24
refresh_interval: 60
title: Temperaturen
layout:
  height: 400
  margin:
    t: 90
    l: 50
    r: 0
  xaxis:
    rangeselector:
      'y': 1.1
      buttons:
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 7
          step: day
        - count: 1
          step: month
        - count: 0.5
          step: year
defaults:
  entity:
    show_value:
      right_margin: 10
    line:
      shape: line
```
