### DISCUSSION TITLE
Combined statistics and short term history

### DISCUSSION THREAD

**Discussion by dbuezas** [dbuezas/lovelace-plotly-graph-card#415] [Show and tell]
<img width="444" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/777196/b0f46d01-2093-456e-8af2-b09fef032f57">

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.teich_temperature
    internal: true
    filters:
      - store_var: temperature
  - entity: sensor.teich_temperature
    period: 5minute
    internal: true
    filters:
      - filter: x<vars.temperature.xs[0]
      - fn: |
          ({xs, ys, vars}) => ({
            xs: xs.concat(vars.temperature.xs),
            ys: ys.concat(vars.temperature.ys),
          })
      - store_var: history
  - entity: sensor.teich_temperature
    period: hour
    filters:
      - filter: x<vars.temperature.xs[0]
      - fn: |
          ({xs, ys, vars}) => ({
            xs: xs.concat(vars.temperature.xs),
            ys: ys.concat(vars.temperature.ys),
          })
hours_to_show: 30d

```
