### DISCUSSION TITLE
Network bandwidth graph help

### DISCUSSION THREAD

**Discussion by H22Designs** [dbuezas/lovelace-plotly-graph-card#418] [Q&A] [answered]
I am looking to use plotly to create a bandwidth speed graph, as well as bandwith usage graph(per day, month). What would be the best way to go about this? I already have sensors in place for bandwidth speed, and usage.

**Comment by myfp31** [comment, marked as answer]
Hello,

Have done something like that if you are interrested : 
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9633358/ee1f3f6c-24ad-42fa-afdc-5fbbfc762354)

and the sample yaml with 4 entities (bandwidth usage and speed in both ways ) is : 
```yaml
type: custom:plotly-graph
autorange_after_scroll: false
entities:
  - entity: sensor.currently_used_download_bandwidth
    name: Current download bandwidth
    yaxis: y1
    line:
      color: rgb(0, 0, 200)
      width: 1
    fill: tozeroy
  - entity: sensor.maximum_download_bandwidth
    name: Maximum download bandwidth
    yaxis: y1
    line:
      color: rgb(0, 0, 200)
      width: 1
      dash: dot
  - entity: sensor.currently_used_upload_bandwidth
    name: Current upload bandwidth
    yaxis: y2
    line:
      color: rgb(205, 0, 0)
      width: 0.5
    fill: tozeroy
  - entity: sensor.maximum_upload_bandwidth
    name: Maximum upload bandwidth
    yaxis: y2
    line:
      color: rgb(205, 0, 0)
      width: 0.5
      dash: dot
hours_to_show: 12
refresh_interval: 10
layout:
  yaxis:
    title: Download
    color: rgb(0, 0, 200)
  yaxis2:
    title: Upload
    side: left
    color: rgb(205, 0, 0)
    autorange: reversed
    tickmode: sync
    overlaying: false
    visible: true
    showgrid: true
    zeroline: false
  grid:
    ygap: 0
    rows: 2
    columns: 1
    roworder: top to bottom
```

Hope it helps
