### DISCUSSION TITLE
Solar Forecast

### DISCUSSION THREAD

**Discussion by slipx06** [dbuezas/lovelace-plotly-graph-card#422] [Show and tell]
Wanted to replace my Apex Solar Forecast chart with a plotly equivalent. I'm using the [open meteo solar forecast](https://github.com/rany2/ha-open-meteo-solar-forecast)

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/7227275/f35bac8c-68d3-466d-adf4-856ae2ad5d3b)

```
type: custom:plotly-graph
hours_to_show: 4d
time_offset: 2.5d
refresh_interval: auto
entities:
  - entity: sensor.sunsynk_solar_power
    name: Solar Power
    line:
      color: rgb(255, 155, 48)
      shape: spline
      width: 1
    fill: tozeroy
    fillcolor: rgba(255, 155, 48, 0.3)
    yaxis: y3
    show_value: false
    showlegend: false
  - entity: sensor.energy_production_today_sum
    line:
      color: rgb(125, 125, 125)
      shape: spline
    fill: tozeroy
    filters:
      - fn: |
          ({meta}) => ({
             xs: meta.wh_period.map(({ start }) => new Date(start)),
             ys: meta.wh_period.map(({ value }) => value),
          })
    yaxis: y1
    showlegend: true
  - entity: sensor.energy_production_tomorrow_sum
    line:
      color: rgb(90,90,90)
      shape: spline
    fill: tozeroy
    filters:
      - fn: |
          ({meta}) => ({
             xs: meta.wh_period.map(({ start }) => new Date(start)),
             ys: meta.wh_period.map(({ value }) => value),
          })
    yaxis: y1
  - entity: sensor.energy_production_d2_sum
    line:
      color: rgb(50,50,50)
      shape: spline
    fill: tozeroy
    filters:
      - fn: |
          ({meta}) => ({
             xs: meta.wh_period.map(({ start }) => new Date(start)),
             ys: meta.wh_period.map(({ value }) => value),
          })
    yaxis: y1
    showlegend: true
  - entity: sensor.sunsynk_battery_soc
    name: Battery
    line:
      color: red
      shape: spline
      width: 1
    yaxis: y2
    show_value: true
    showlegend: false
    visible: true
  - entity: ''
    name: Now
    yaxis: y9
    showlegend: false
    line:
      width: 2
      dash: dot
      color: aqua
    x: $ex [Date.now(), Date.now()]
    'y':
      - 0
      - 1
layout:
  height: 400
  margin:
    t: 55
    l: 50
  showlegend: false
  legend:
    x: 0.1
    'y': -0.8
  yaxis2:
    range:
      - 20
      - 105
    fixedrange: true
  annotations:
    - text: |-
        $fn ({hass}) =>
          "<span style='font-size: 24px;'><span style='color: orange'>"
          + Number(hass.states['sensor.energy_production_tomorrow_sum'].state).toFixed(1) + "</span></span>kWh<br>"
          +  "</span><span style=''>Forecast Today</span><br>"
      xref: x domain
      yref: y domain
      xanchor: center
      yanchor: center
      x: 0.06
      'y': 1.2
      showarrow: false
    - text: |-
        $fn ({hass}) =>
          "<span style='font-size: 24px;'><span style='color: dodgerblue'>"
          + Number(hass.states['sensor.meteo_energy_production_today_remaining'].state).toFixed(1) + "</span></span>kWh<br>"
          +  "</span><span style=''>Remaining</span><br>"
      xref: x domain
      yref: y domain
      xanchor: center
      yanchor: center
      x: 0.28
      'y': 1.2
      showarrow: false
    - text: |-
        $fn ({hass}) =>
          "<span style='font-size: 24px;'><span style='color: '>"
          + Number(hass.states['sensor.energy_production_tomorrow_sum'].state).toFixed(1) + "</span></span>kWh<br>"
          +  "</span><span style=''>Forecast Tomorrow</span><br>"
      xref: x domain
      yref: y domain
      xanchor: center
      yanchor: centre
      x: 0.5
      'y': 1.2
      showarrow: false
    - text: |-
        $fn ({hass}) =>
          "<span style='font-size: 24px;'><span style='color: white'>"
          + Number(hass.states['sensor.energy_production_d2_sum'].state).toFixed(1) + "</span></span>kWh<br>"
          +  "</span><span style=''>Forecast Day 2</span><br>"
      xref: x domain
      yref: y domain
      xanchor: center
      yanchor: center
      x: 0.72
      'y': 1.2
      showarrow: false
    - text: |-
        $fn ({hass}) =>
          "<span style='font-size: 24px;'><span style='color: red'>"
          + Number(hass.states['sensor.sunsynk_battery_soc'].state) + "</span></span>%<br>"
          +  "</span><span style=''>SOC</span><br>"
      xref: x domain
      yref: y domain
      xanchor: center
      yanchor: center
      x: 0.94
      'y': 1.2
      showarrow: false
config:
  scrollZoom: false
```

I've created my own template sensors to sum my west and north facing PV strings and convert the sensor attributes into an array. If you want to use the integration default sensors  you can replace the function that generates the data i.e.

Replace 

```
    filters:
      - fn: |
          ({meta}) => ({
             xs: meta.wh_period.map(({ start }) => new Date(start)),
             ys: meta.wh_period.map(({ value }) => value),
          })
```

with

```
    filters:
      - fn: |
          ({meta}) => {
            const entries = Object.entries(meta.wh_period); 
            const xs = entries.map(([start, _]) => new Date(start));
            const ys = entries.map(([_, value]) => value);
            
            return { xs, ys };
          }
```

**Comment by liouma** [comment]
Hello,
Thanks for sharing, that's really interesting.
I tried to implement your dashboard but I get some errors.
Any help would be more than welcome :)

I also created templates to sum my panel clusters but without converting the sensor attributes to an array:
```
- trigger:
    - platform: state
      entity_id: sensor.ome_energy_production_d2
      not_to:
        - unknown
        - unavailable
    - platform: state
      entity_id: sensor.omo_energy_production_d2
      not_to:
        - unknown
        - unavailable
  sensor:
    - name: OM Energy production d2 - total
      unique_id: om__energy_production_d2_total
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing
      state: >
        {{ (states('sensor.ome_energy_production_d2')| float ) + (states('sensor.omo_energy_production_d2') | float ) }}
```
So I did the code replacement as you suggested.

This is the error I get:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/106532164/1f81bcf5-0ba1-415b-96ab-ddcf2a1ce53f)
And my card code:
```
type: custom:plotly-graph
hours_to_show: 4d
time_offset: 2.5d
refresh_interval: auto
entities:
  - entity: sensor.inverter_input_power
    name: Solar Power
    line:
      color: rgb(255, 155, 48)
      shape: spline
      width: 1
    fill: tozeroy
    fillcolor: rgba(255, 155, 48, 0.3)
    yaxis: y3
    show_value: false
    showlegend: false
  - entity: sensor.om_energy_production_today_total
    line:
      color: rgb(125, 125, 125)
      shape: spline
    fill: tozeroy
    filters:
      - fn: |
          ({meta}) => {
            const entries = Object.entries(meta.wh_period); 
            const xs = entries.map(([start, _]) => new Date(start));
            const ys = entries.map(([_, value]) => value);
            
            return { xs, ys };
          }
    yaxis: y1
    showlegend: true
  - entity: sensor.om_energy_production_tomorrow_total
    line:
      color: rgb(90,90,90)
      shape: spline
    fill: tozeroy
    filters:
      - fn: |
          ({meta}) => {
            const entries = Object.entries(meta.wh_period); 
            const xs = entries.map(([start, _]) => new Date(start));
            const ys = entries.map(([_, value]) => value);
            
            return { xs, ys };
          }
    yaxis: y1
  - entity: sensor.om_energy_production_d2_total
    line:
      color: rgb(50,50,50)
      shape: spline
    fill: tozeroy
    filters:
      - fn: |
          ({meta}) => {
            const entries = Object.entries(meta.wh_period); 
            const xs = entries.map(([start, _]) => new Date(start));
            const ys = entries.map(([_, value]) => value);
            
            return { xs, ys };
          }
    yaxis: y1
    showlegend: true
  - entity: sensor.battery_state_of_capacity
    name: Battery
    line:
      color: red
      shape: spline
      width: 1
    yaxis: y2
    show_value: true
    showlegend: false
    visible: true
  - entity: ''
    name: Now
    yaxis: y9
    showlegend: false
    line:
      width: 2
      dash: dot
      color: aqua
    x: $ex [Date.now(), Date.now()]
    'y':
      - 0
      - 1
layout:
  height: 400
  margin:
    t: 55
    l: 50
  showlegend: false
  legend:
    x: 0.1
    'y': -0.8
  yaxis2:
    range:
      - 20
      - 105
    fixedrange: true
  annotations:
    - text: |-
        $fn ({hass}) =>
          "<span style='font-size: 24px;'><span style='color: orange'>"
          + Number(hass.states['sensor.om_energy_production_tomorrow_total'].state).toFixed(1) + "</span></span>kWh<br>"
          +  "</span><span style=''>Forecast Today</span><br>"
      xref: x domain
      yref: y domain
      xanchor: center
      yanchor: center
      x: 0.06
      'y': 1.2
      showarrow: false
    - text: |-
        $fn ({hass}) =>
          "<span style='font-size: 24px;'><span style='color: dodgerblue'>"
          + Number(hass.states['sensor.om_energy_production_today_remaining_total'].state).toFixed(1) + "</span></span>kWh<br>"
          +  "</span><span style=''>Remaining</span><br>"
      xref: x domain
      yref: y domain
      xanchor: center
      yanchor: center
      x: 0.28
      'y': 1.2
      showarrow: false
    - text: |-
        $fn ({hass}) =>
          "<span style='font-size: 24px;'><span style='color: '>"
          + Number(hass.states['sensor.om_energy_production_tomorrow_total'].state).toFixed(1) + "</span></span>kWh<br>"
          +  "</span><span style=''>Forecast Tomorrow</span><br>"
      xref: x domain
      yref: y domain
      xanchor: center
      yanchor: centre
      x: 0.5
      'y': 1.2
      showarrow: false
    - text: |-
        $fn ({hass}) =>
          "<span style='font-size: 24px;'><span style='color: white'>"
          + Number(hass.states['sensor.om_energy_production_d2_total'].state).toFixed(1) + "</span></span>kWh<br>"
          +  "</span><span style=''>Forecast Day 2</span><br>"
      xref: x domain
      yref: y domain
      xanchor: center
      yanchor: center
      x: 0.72
      'y': 1.2
      showarrow: false
    - text: |-
        $fn ({hass}) =>
          "<span style='font-size: 24px;'><span style='color: red'>"
          + Number(hass.states['sensor.battery_state_of_capacity'].state) + "</span></span>%<br>"
          +  "</span><span style=''>SOC</span><br>"
      xref: x domain
      yref: y domain
      xanchor: center
      yanchor: center
      x: 0.94
      'y': 1.2
      showarrow: false
config:
  scrollZoom: false
```
