### DISCUSSION TITLE
Wind speed graph with markers using wind direction dataset

### DISCUSSION THREAD

**Discussion by Ralpie79** [dbuezas/lovelace-plotly-graph-card#423] [Q&A] [answered]
Hi,

I'm grabbing weather data from Open Meteo and have two sensors set up as wind speed and wind direction.

I have got a simple line graph with the markers set on the wind speed dataset, but having trouble trying to find and references or examples where you can use the wind direction values to change the angle for the markers.

It seems simple enough, but it has me baffled.

This is what I have so far and can set angle to any number, but it changes all the markers to one direction.

```
type: custom:plotly-graph
entities:
  - entity: sensor.omwindspeed
    yaxis: y1
    mode: markers
    marker:
      symbol: arrow
      size: 9
      angle: sensor.omwinddirection

hours_to_show: 24
refresh_interval: 10
```
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/19633372/8c4534b5-7d71-4cea-8111-1499fc9abf94)

This is the wind direction data added for reference.

```
type: custom:plotly-graph
entities:
  - entity: sensor.omwindspeed
    yaxis: y1
    mode: markers
    marker:
      symbol: arrow
      size: 9
      angle: sensor.omwinddirection

  - entity: sensor.omwinddirection
    yaxis: y2

hours_to_show: 24
refresh_interval: 10
```

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/19633372/785deb3a-0f1a-4d90-9802-035f9c04e0b2)

Any help or pointers in the right direction would be great!

Thanks in advance.

**Comment by dbuezas** [comment]
You were almost there!
You need to use $ex for that
```yaml
angle: $ex ys
```

**Reply by dbuezas** [reply]
Oh, right the direction is a different sensor so you'll have to store it in a var and then use that. Search for `vars` in the docs

**Reply by Ralpie79** [reply, marked as answer]
It took me a while to find something to reference, but It seems to be working alright now. Thanks for the pointer.

I assume the resample is right on both entities to reduce the number of markers displayed?


```
type: custom:plotly-graph
entities:
  - entity: sensor.omwinddirection
    yaxis: y2
    visible: true
    line:
      shape: spline
    filters:
      - resample: 100m
      - store_var: winddir
  - entity: sensor.omwindspeed
    name: Wind Speed & Direction
    mode: markers
    showlegend: true
    yaxis: y1
    show_value: true
    filters:
      - resample: 100m
    line:
      shape: spline
    marker:
      symbol: arrow
      size: 10
      angle: $ex vars.winddir.ys
hours_to_show: 24
refresh_interval: 10
layout:
  margin:
    b: auto
    t: 10
    l: 40
    r: 40

```

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/19633372/31c89f11-01d9-4599-8342-8e3d98a8669d)
