### DISCUSSION TITLE
How to lock the y-axis for labels?

### DISCUSSION THREAD

**Discussion by Photelegy** [dbuezas/lovelace-plotly-graph-card#424] [Q&A] [answered]
Hi everyone

I really love to use Plotly-Graph-Card and already have done a lot with it.
But I can't figure out how to lock the y-axis if the data is string.

I have e.g. graphs about if a door/window is open or for some even if they are locked.

When I show the data for the last 1 hours it shows this:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/61714583/9ce8f733-4d7e-45b0-9f31-cdbe9ef4274f)

And when I show the data for the last 2 days it shows this:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/61714583/1423c3f7-70e8-44f7-aef0-03e9e62d29e8)

And when I show the data for the last 7 days it shows this:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/61714583/68cd5e7a-5235-4d96-9cb6-bcb43adc5fc7)

The y-axis is always changing.

I would want to have the y-axis for the orange one to be this sequence:
- unlocked
- locking
- locked

And for the y-axis for the red one to be this sequence:
- Open
- Closed & Unlocked
- Closed & Locked

How can I achieve this?

My code is:
```
type: custom:plotly-graph
entities:
  - entity: sensor.nuki_lock_door
    name: Tür
    yaxis: y1
  - entity: sensor.nuki_barmar_nuki_lock_door_security_state
    name: Zustand
    yaxis: y3
hours_to_show: 24
refresh_interval: 5
logarithmic_scale: false
title: Door/Window Sensoren
config:
  scrollZoom: false
layout:
  paper_bgcolor: rgba(255, 255, 255, 0.0)
  plot_bgcolor: rgba(255, 255, 255, 0.0)
  font:
    size: 11
  height: 250
  margin:
    t: 20
    l: 100
    r: 50
  grid:
    rows: 3
    columns: 1
    roworder: top to bottom
  xaxis:
    rangeselector:
      'y': 1.2
      buttons:
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 1
          step: day
        - count: 2
          step: day
        - count: 5
          step: day
        - count: 7
          step: day
        - count: 1
          step: month
  yaxis:
    fixedrange: true
  yaxis3:
    fixedrange: true
  showlegend: true
  legend:
    x: 0
    'y': -0.6
    bgcolor: rgba(0,0,0,.7)
    orientation: h
    font:
      size: 11
      color: lightgrey
defaults:
  entity:
    show_value: false
  yaxes:
    side: left
    overlaying: 'y'
    visible: true
    showgrid: true
color_scheme:
  - Orange
  - Red
```

Thank you all very much for your help!
