### DISCUSSION TITLE
Stacking multiple plots with differents heights

### DISCUSSION THREAD

**Discussion by tokhay** [dbuezas/lovelace-plotly-graph-card#425] [Q&A] [answered]
Hello,
In order to record temperature and activation of my heater, I would like to have 2 plots with linked x axis, but with one plot being smaller. 
Is there a parameter to define height for each row of the grid ?

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/85199939/af7e6ded-22d1-49a9-82b7-884029b4a8d3)

```
type: custom:plotly-graph
entities:
  - entity: sensor.pac_mitsubishi_temperature_exterieure
    show_value: true
    name: Météo
    yaxis: y1
  - entity: sensor.pac_mitsubishi_zone_1_temperature_ambiante
    show_value: true
    name: Ambiante
    yaxis: y1
  - entity: sensor.consigne_temperature
    show_value: true
    name: Consigne
    yaxis: y1
  - entity: sensor.pac_mitsubishi_temperature_du_reservoir
    show_value: true
    name: Ballon
    yaxis: y2
  - entity: sensor.consigne_ecs
    show_value: true
    name: Consigne
    yaxis: y2
  - entity: binary_sensor.capteur_demande_chauffage
    show_value: false
    name: Chauffage
    fill: tozeroy
    line:
      color: red
    yaxis: y3
  - entity: binary_sensor.capteur_demande_ecs
    name: ECS
    yaxis: y3
    show_value: false
    fill: tozeroy
    line:
      color: blue
refresh_interval: 10
hours_to_show: 24
defaults:
  yaxes:
    side: left
    overlaying: 'y'
    visible: true
    showgrid: true
layout:
  grid:
    rows: 3
    columns: 1
    pattern: coupled
    roworder: top to bottom
  legend:
    x: -0.2
    title:
      text: T°C ambiante
  xaxis:
    rangeselector:
      'y': -0.3
      x: 0.6
      buttons:
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 7
          step: day
  yaxis:
    visible: true
    fixedrange: true
  height: 500

```

**Comment by dbuezas** [comment, marked as answer]
Yes, you need to set the grid cell domain, see here: https://plotly.com/javascript/subplots/#custom-sized-subplot

**Reply by tokhay** [reply]
Thank you,

I viewed this method when searching for an answer, but I'm noob in programming, and I don't know how to translate javascript into yaml :(

**Reply by tokhay** [reply]
Finally I managed to find with the help of your link the way to do it : 

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/85199939/58a68ae6-2ce8-48be-96f3-59a76e663f8e)


```
type: custom:plotly-graph
entities:
  - entity: sensor.pac_mitsubishi_temperature_exterieure
    show_value: true
    name: Météo
    yaxis: y1
  - entity: sensor.pac_mitsubishi_zone_1_temperature_ambiante
    show_value: true
    name: Ambiante
    yaxis: y1
  - entity: sensor.consigne_temperature
    show_value: true
    name: Consigne
    yaxis: y1
  - entity: sensor.pac_mitsubishi_temperature_du_reservoir
    show_value: true
    name: Ballon
    yaxis: y2
  - entity: sensor.consigne_ecs
    show_value: true
    name: Consigne
    yaxis: y2
  - entity: binary_sensor.capteur_demande_chauffage
    show_value: false
    name: Chauffage
    fill: tozeroy
    line:
      color: red
    yaxis: y3
  - entity: binary_sensor.capteur_demande_ecs
    name: ECS
    yaxis: y3
    show_value: false
    fill: tozeroy
    line:
      color: blue
refresh_interval: 10
hours_to_show: 24
defaults:
  yaxes:
    side: left
    overlaying: 'y'
    visible: true
    showgrid: true
    fixedrange: true
layout:
  grid:
    rows: 3
    columns: 1
    pattern: coupled
    roworder: top to bottom
  legend:
    x: -0.2
    title:
      text: T°C ambiante
  xaxis:
    rangeselector:
      'y': -0.07
      x: 0.6
      buttons:
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 7
          step: day
  yaxis:
    visible: true
    fixedrange: true
    domain:
      - 0.42
      - 0.95
  yaxis2:
    visible: true
    fixedrange: true
    domain:
      - 0.0.8
      - 0.5
  yaxis3:
    visible: true
    fixedrange: true
    domain:
      - 0
      - 0.05
  height: 750
autorange_after_scroll: true
```
