### DISCUSSION TITLE
Summate graphs together

### DISCUSSION THREAD

**Discussion by thisIsLiving** [dbuezas/lovelace-plotly-graph-card#429] [Q&A] [answered]
How do I summate 3 graphs together? Each is a time series dataset of energy demand (W) and I would like to show a total

This is what I currently have:
```
type: custom:plotly-graph
entities:
  - entity: sensor.meter_1_power
    name: Light + Power 1
    mode: lines+markers
    marker:
      size: 3
  - entity: sensor.meter_2_power_a
    name: Stove + Power 2
    mode: lines+markers
    marker:
      size: 3
  - entity: sensor.meter_2_power_b
    name: Hotwater
    mode: lines+markers
    marker:
      size: 3
  #- entity: (sensor.meter_1_power + sensor.meter_2_power_a + sensor.meter_2_power_b) 
  #  name: Total
hours_to_show: 24
refresh_interval: 10

```
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/20834594/dd7dd2b3-1701-4d08-9c31-44b2a6abe70c)

I would like to do something like `sensor.meter_1_power + sensor.meter_2_power_a + sensor.meter_2_power_b` but obviously that doesn't work plus the meters supplying the data provide datapoints at different times.

**Comment by dbuezas** [comment]
see the following filters in the readme:
* `resample` <- this is to align all entities, so that each index corresponds to the same time
* `store_var:` <- to store the data of an entity in a variable
* `map_y:` <- here you can do someething like `vars.meter1_power.ys[i] + vars.meter2_power_a.ys[i] + vars.meter_2_power_b[i]`

**Reply by thisIsLiving** [reply, marked as answer]
Thanks, it works great! A note for those next time would be to remember to parseFloat(y) as otherwise the resampling will store as an integer or something as I was getting rather large numbers...

Below is my code for reference for others to learn from. A higher frequency sampling rate will make the graph rather laggy so be aware.

Also is there a way to graph something without it being tied to an entity? In my code below I ended up graphing the "Total" under the "Meter 2 b" entity.

```
type: custom:plotly-graph
entities:
  - entity: sensor.meter_1_power
    name: Light + Power 1
    mode: lines+markers
    marker:
      size: 3
    filters:
      - resample: 1m
      - map_y: parseFloat(y)
      - store_var: meter_1_power_resamp
  - entity: sensor.meter_2_power_a
    name: Stove + Power 2
    mode: lines+markers
    marker:
      size: 3
    filters:
      - resample: 1m
      - map_y: parseFloat(y)
      - store_var: meter_2_power_a_resamp
  - entity: sensor.meter_2_power_b
    name: Hotwater
    mode: lines+markers
    marker:
      size: 3
  - entity: sensor.meter_2_power_b
    name: Total
    mode: lines+markers
    marker:
      size: 3
    filters:
      - resample: 1m
      - map_y: parseFloat(y)
      - map_y: >-
          vars.meter_1_power_resamp.ys[i] + vars.meter_2_power_a_resamp.ys[i] + y
hours_to_show: 24
refresh_interval: 10
```

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/20834594/3c6de907-d728-46ea-be30-974f898416eb)

**Reply by dbuezas** [reply]
Great!
Good point on the parseFloat, they are some times strings and addition means concatenation in js.

You can alternatively use `forceNumeric:` before the resample 

> Also is there a way to graph something without it being tied to an entity?

yes just use `entity: ""` [here's and example of that](https://github.com/dbuezas/lovelace-plotly-graph-card?tab=readme-ov-file#now-line)

**Comment by thisIsLiving** [comment]
Sorry I can't seem to get the no entity part working...what am I doing wrong???

```
  - entity: ""
    name: Totals
    filters:
      - map_y: vars.meter_1_power_resamp.ys[i] + vars.meter_2_power_a_resamp.ys[i] + vars.meter_2_power_b_resamp.ys[i]
      - store_var: power_total
    x: $ex vars.power_total.xs
    y: $ex vars.power_total.ys
```

**Reply by dbuezas** [reply]
```yaml
  - entity: ""
    name: Totals
    filters:
      - load_var: meter_1_power_resamp
      - map_y: y + vars.meter_2_power_a_resamp.ys[i] + vars.meter_2_power_b_resamp.ys[i]
```
