### DISCUSSION TITLE
How to make the show_value better visible on the right?

### DISCUSSION THREAD

**Discussion by Photelegy** [dbuezas/lovelace-plotly-graph-card#43] [Q&A] [answered]
I know that there is a `right_margin: ` but this is bound to the zoom of the x-axis (if I'm not mistaken).
Now I have the problem that when I choose different `rangeselector: ` `buttons: ` it doesn't show the `show_value` good visable.

[1d] looks fine and the unites are fully shown (without the need of moving the x-axis):
![image](https://user-images.githubusercontent.com/61714583/168331320-2c6708a5-b6cc-4c48-8503-94ff652bbf69.png)

[7d] doesn't look fine (the unites are cut off):            (With 1month, ... it's even worth)
![image](https://user-images.githubusercontent.com/61714583/168331569-3d4f2d5b-bfe7-435f-9a46-91855ed20dcb.png)

[12h] the space on the right is way to big:
![image](https://user-images.githubusercontent.com/61714583/168331706-5a51a9b3-5913-4538-b715-82ad5efbcb6f.png)

My card-configuration:
```
type: custom:plotly-graph
entities:
  - entity: sensor.vierwaldstettersee_temperatur
    yaxis: y1
    legendgroup: 1
    name: Vierwaldstättersee
  - entity: sensor.vierwaldstattersee_pegel
    yaxis: y2
    showlegend: false
    legendgroup: 1
  - entity: sensor.lauerzersee_temperatur
    yaxis: y1
    legendgroup: 2
    name: Lauerzersee
  - entity: sensor.lauerzersee_pegel
    yaxis: y2
    legendgroup: 2
    showlegend: false
  - entity: sensor.zugersee_temperatur
    yaxis: y1
    legendgroup: 3
    name: Zugersee
  - entity: sensor.zugersee_pegel
    yaxis: y2
    legendgroup: 3
    showlegend: false
  - entity: sensor.zurichsee_temperatur
    yaxis: y1
    legendgroup: 4
    name: Zürichsee
  - entity: sensor.zurichsee_pegel
    yaxis: y2
    legendgroup: 4
    showlegend: false
  - entity: sensor.agerisee_temperatur
    yaxis: y1
    legendgroup: 5
    name: Ägerisee
  - entity: sensor.agerisee_pegel
    yaxis: y2
    legendgroup: 5
    showlegend: false
hours_to_show: 24
refresh_interval: 60
title: Seen (Temperatur und Wasser-Pegel)
layout:
  height: 500
  margin:
    t: 80
    l: 50
    r: 5
  xaxis:
    rangeselector:
      'y': 1.05
      buttons:
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 7
          step: day
        - count: 1
          step: month
        - count: 6
          step: month
        - count: 1
          step: year
  dragmode: pan
  showlegend: true
  legend:
    x: 0
    'y': -0.12
    bgcolor: rgba(0,0,0,.7)
    orientation: h
    itemsizing: constant
    font:
      size: 10
  grid:
    rows: 2
    columns: 1
    roworder: top to bottom
  yaxis:
    title: Temperatur [°C]
  yaxis2:
    title: Pegel [m.ü.M.]
no_default_layout: true
defaults:
  entity:
    show_value:
      right_margin: 22
    line:
      shape: line
color_scheme:
  - '#1f77b4'
  - '#1f77b4'
  - '#aec7e8'
  - '#aec7e8'
  - '#ff7f0e'
  - '#ff7f0e'
  - '#9d5dcf'
  - '#9d5dcf'
  - '#2ca02c'
  - '#2ca02c'
```
