### DISCUSSION TITLE
strange behaviuor when transitioning from period day to period week/month/etc

### DISCUSSION THREAD

**Discussion by wergio** [dbuezas/lovelace-plotly-graph-card#431] [Q&A] [answered]
Could someone help me with this code?
Scrolling up or down fades from days to weeks to months, but:
1) when there is blank y data on the right the bars disappears, this doesnt appen if you first scroll a bit to the left (so there is no blank data on the right)
2) is it possible to use also year period? seems not supported...
3) how to have a button to reset to the initial position?
4) how to stop zooming in to lower than a day?
thanks
```
type: custom:plotly-graph
title: Energia in uscita Inverter Huawei
hours_to_show: 7d
autorange_after_scroll: true
refresh_interval: auto
entities:
  - entity: sensor.p1_inverter_huawei_total_yield
    name: Uscita Energia
    attribute: energy
    unit_of_measurement: kWh
    filters:
      - delta
    type: bar
    texttemplate: '%{y:.1f}'
    statistic: sum
    period:
      1d: day
      1w: day
      2w: week
      8w: month
layout:
  height: 400
  dragmode: pan
  showlegend: false
  modebar:
    remove:
      - zoom
      - autoscale
      - pan
  hoverlabel:
    bgcolor: white
  yaxis:
    fixedrange: true
  xaxis:
    showgrid: false
    rangeselector:
      buttons:
        - count: 7
          step: day
          label: Giorni
        - count: 1
          step: month
          label: Settimane
        - count: 1
          step: year
          label: Mesi
        - count: 5
          step: year
          label: Anni

```
