### DISCUSSION TITLE
Wind direction with two y-axis

### DISCUSSION THREAD

**Discussion by jjvelar** [dbuezas/lovelace-plotly-graph-card#435] [Show and tell]
Hi!

I have created a very simple wind direction histogram but I don't know how to add a secondary y-axe so in the first one, on the left, it shows degrees, and the second one, on the right, it shows N, E, W and S.
I have added below a screenshot of what I'd like to replicate.
Thanks in advance for your help!

```
type: custom:plotly-graph
refresh_interval: auto
config:
  scrollZoom: false
  staticPlot: true
layout:
  yaxis:
    range:
      - 0
      - 360
defaults:
  entity:
    showlegend: true
    show_value: true
    line:
      width: 1
    filters:
      - sliding_window_moving_average:
          window_size: 10
          extended: false
          centered: true
hours_to_show: 24
time_offset: |-
  $fn ({ getFromConfig }) => {
    const ms_to_show = getFromConfig('hours_to_show') * 60 * 60 * 1000;
    const now_utc = Date.now() - new Date().getTimezoneOffset() * 60 * 1000;
    return ms_to_show - now_utc % ms_to_show + 'ms'
  }
entities:
  - entity: sensor.weather_station_wind_direction
    name: Wind direction
    mode: markers
    marker:
      size: 3
      color: royalblue
    type: scatter
```

![image](https://github.com/user-attachments/assets/16130f88-de2c-42aa-a9c2-933ce6c6b4a2)

**Comment by dbuezas** [comment]
Try with this:
```yaml
layout:
 yaxis2:
  title: 'Cardinal Directions'
  overlaying: 'y'
  side: 'right'
  tickvals: [0, 90, 180, 270, 360]
  ticktext: ['North', 'East', 'South', 'West', 'North']
```

**Comment by jjvelar** [comment]
Thanks but it is not showing up.
That's my code:

```
type: custom:plotly-graph
refresh_interval: auto
config:
  scrollZoom: false
  staticPlot: true
layout:
  yaxis:
    range:
      - 0
      - 360
  yaxis2:
    overlaying: 'y'
    side: right
    tickvals:
      - 0
      - 90
      - 180
      - 270
      - 360
    ticktext:
      - "N"
      - "E"
      - "S"
      - "O"
      - "N"
defaults:
  entity:
    showlegend: true
    show_value: true
    line:
      width: 1
    filters:
      - sliding_window_moving_average:
          window_size: 10
          extended: false
          centered: true
hours_to_show: 24
time_offset: |-
  $fn ({ getFromConfig }) => {
    const ms_to_show = getFromConfig('hours_to_show') * 60 * 60 * 1000;
    const now_utc = Date.now() - new Date().getTimezoneOffset() * 60 * 1000;
    return ms_to_show - now_utc % ms_to_show + 'ms'
  }
entities:
  - entity: sensor.weather_station_wind_direction
    name: Wind direction
    mode: markers
    marker:
      size: 3
      color: royalblue
    type: scatter
```

And this how it is shown:

![image](https://github.com/user-attachments/assets/fa5229e5-4a96-466c-bf4b-4415f27c595c)
