### DISCUSSION TITLE
Time offset and number of days in a month.

### DISCUSSION THREAD

**Discussion by caiusseverus** [dbuezas/lovelace-plotly-graph-card#436] [Q&A] [answered]
I have a few graphs which are intended to show the current month's data, as well as that from the previous month. The problem I have is that with the time_offset switch, setting the value to 1M will show data from the last 30 days. If the month is 31 days long, it means the previous months data is displaced by a day. For example:

![image](https://github.com/user-attachments/assets/f2f2d6ca-77b1-4a80-b254-06269fb482f1)

I can correct this by changing the time_offset to 31 days, which puts the data in the correct place:

![image](https://github.com/user-attachments/assets/f8f0481f-e40a-4069-8253-a6307e12a977)

This is all very well, but not all months are 31 days and so when the length of the month changes, the graph will be incorrect again.

The question is, does there exist a method to make an entity always start at the beginning of the previous calendar month rather than by offsetting by a fixed number of days?

**Comment by dbuezas** [comment]
There's `current_month` [here](https://github.com/dbuezas/lovelace-plotly-graph-card?tab=readme-ov-file#dynamic-relative-time)
but that won't show you the previous month.
You'll have to do this "manually", [here's an example](https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/220#discussioncomment-4873252) that pre-dates the feature I just mentioned and gives you finer control.
You'll have to work with the Date javascript object

**Reply by dbuezas** [reply]
untested (thank you chatgpt)
```yaml
hours_to_show: |-
  $ex {
    const currentDate = new Date();
    const currentYear = currentDate.getUTCFullYear();
    const currentMonth = currentDate.getUTCMonth();
    const lastMonth = currentMonth === 0 ? 11 : currentMonth - 1;
    const lastMonthYear = currentMonth === 0 ? currentYear - 1 : currentYear;

    // Calculate the start and end dates
    const startOfLastMonth = new Date(Date.UTC(lastMonthYear, lastMonth, 1));
    const startOfCurrentMonth = new Date(Date.UTC(currentYear, currentMonth, 1));
    const endOfLastMonth = new Date(startOfCurrentMonth.getTime() - 1);

    // Calculate the hours to show
    const hoursToShow = (endOfLastMonth - startOfLastMonth) / (1000 * 60 * 60) + (currentDate - startOfCurrentMonth) / (1000 * 60 * 60);
    vars.lastMonthYear = lastMonthYear
    vars.lastMonth = lastMonth
    return hoursToShow
  }
time_offset: |-
  $ex {
    const now_utc = Date.now() - new Date().getTimezoneOffset() * 60 * 1000;
    const startOfLastMonth = new Date(Date.UTC(vars.lastMonthYear, vars.lastMonth, 1)).getTime();
    return now_utc - startOfLastMonth + 'ms';
  }

```

**Comment by caiusseverus** [comment, marked as answer]
> There's current_month [here](https://github.com/dbuezas/lovelace-plotly-graph-card?tab=readme-ov-file#dynamic-relative-time)
but that won't show you the previous month.

Sorry I didn't post code - that's what I was using to select the date range. It works as expected to show this months data, but the issue is overlaying data from the previous month. The `time_offset` function is fixed at 30 days, while the span of `current_month` obviously varies with the number of days.

I think that the first script there is not necessary - `current_month` does what it's supposed to. It's `time_offset` that's problematic. Thanks for the ChatGPT suggestion, I hadn't thought of using that. Here's what it gave me:

```
time_offset: |-
  $ex {
    const currentDate = new Date();
    const currentYear = currentDate.getUTCFullYear();
    const currentMonth = currentDate.getUTCMonth();
    
    // Determine the previous month and year
    const lastMonth = currentMonth === 0 ? 11 : currentMonth - 1;
    const lastMonthYear = currentMonth === 0 ? currentYear - 1 : currentYear;

    // Calculate the start and end of the previous month
    const startOfLastMonth = new Date(Date.UTC(lastMonthYear, lastMonth, 1));
    const startOfCurrentMonth = new Date(Date.UTC(currentYear, currentMonth, 1));
    
    // Calculate the number of days in the previous month
    const daysInLastMonth = (startOfCurrentMonth - startOfLastMonth) / (1000 * 60 * 60 * 24);

    return daysInLastMonth + 'd';
  }
```
this should give the number of days in the preceding month as the output and append 'd' to it so it's the correct format for the `time_offset` switch.

It appears to work correctly, but I'll have to wait for a month with a different number of days to be sure.

This is the output with the above script, which matches what I get when I set the number of days manually:

![image](https://github.com/user-attachments/assets/29eff7c5-28fe-49f6-832c-c474628c020f)

The purpose of the graph is to show the difference in cost between the Octopus Agile tariff and the standard fixed rate tariff. The top part is the range and average of rates per day, and the weighted average over the whole month which accounts for the time energy was used.

Thanks for the help. I'm not really that familiar with javascript so I muddle through with stuff like this.

Here is the code for that graph:

```
type: custom:plotly-graph
title: Month Electricity Consumption
hours_to_show: current_month
config:
  displayModeBar: false
layout:
  height: 750
  dragmode: false
  legend:
    orientation: h
    itemsizing: constant
    font:
      size: 8
  grid:
    rows: 2
    columns: 1
    roworder: bottom to top
  xaxis:
    visible: true
    fixedrange: true
  yaxis:
    visible: true
    fixedrange: true
    rangemode: tozero
    title: Consumption (kWh)
    side: left
    showgrid: true
    domain:
      - 0
      - 0.775
    range:
      - 0
      - 375
    tick0: 0
    dtick: 25
  yaxis2:
    visible: true
    rangemode: tozero
    showgrid: true
    fixedrange: true
    overlaying: y2
    side: left
    title: £/kWh
    tickmode: sync
    domain:
      - 0.8
      - 1
  yaxis3:
    visible: true
    fixedrange: true
    rangemode: tozero
    range:
      - 0
      - 90
    title: Cost (£)
    overlaying: 'y'
    side: right
    anchor: x
    tickmode: sync
    tick0: 0
  yaxis9:
    visible: false
    fixedrange: true
  annotations:
    - text: >-
        $fn ({ hass }) =>

        "<span style='font-size: 24px;'><span style='color: orange'>"

        + Number(hass.states['sensor.unit_avg_month'].state) + "</span></span>
        £/kWh<br>"

        + "</span><span style=''> Weighted Average Unit Price</span><br>"
      xref: x domain
      yref: y domain
      xanchor: center
      yanchor: center
      x: 0.075
      'y': 0.95
      showarrow: false
entities:
  - entity: sensor.electric_meter_month
    name: Week
    line:
      color: rgba(52,152,219,1)
      width: 2
      shape: linear
    filters:
      - resample: 1m
      - map_y: parseFloat(y)
      - store_var: kwh
    show_value: true
    yaxis: y1
  - entity: sensor.electric_meter_month
    yaxis: y1
    time_offset: |-
      $ex {
        const currentDate = new Date();
        const currentYear = currentDate.getUTCFullYear();
        const currentMonth = currentDate.getUTCMonth();
        const lastMonth = currentMonth === 0 ? 11 : currentMonth - 1;
        const lastMonthYear = currentMonth === 0 ? currentYear - 1 : currentYear;
        const startOfLastMonth = new Date(Date.UTC(lastMonthYear, lastMonth, 1));
        const startOfCurrentMonth = new Date(Date.UTC(currentYear, currentMonth, 1));
        const daysInLastMonth = (startOfCurrentMonth - startOfLastMonth) / (1000 * 60 * 60 * 24);
        return daysInLastMonth + 'd';
      }
    name: '-1m'
    line:
      color: rgba(52,152,219,0.5)
      width: 2
      shape: linear
      dash: dot
  - entity: sensor.electricity_monthly_energy_cost
    name: Cost
    yaxis: y3
    line:
      color: green
      width: 2
      shape: linear
    filters:
      - resample: 1m
      - map_y: parseFloat(y)
      - store_var: cost
    show_value: true
  - entity: sensor.electricity_monthly_energy_cost
    name: Cost -1 month
    time_offset: |-
      $ex {
        const currentDate = new Date();
        const currentYear = currentDate.getUTCFullYear();
        const currentMonth = currentDate.getUTCMonth();
        const lastMonth = currentMonth === 0 ? 11 : currentMonth - 1;
        const lastMonthYear = currentMonth === 0 ? currentYear - 1 : currentYear;
        const startOfLastMonth = new Date(Date.UTC(lastMonthYear, lastMonth, 1));
        const startOfCurrentMonth = new Date(Date.UTC(currentYear, currentMonth, 1));
        const daysInLastMonth = (startOfCurrentMonth - startOfLastMonth) / (1000 * 60 * 60 * 24);
        return daysInLastMonth + 'd';
      }
    yaxis: y3
    line:
      color: rgba(0,255,0,0.4)
      width: 2
      shape: linear
      dash: dot
  - entity: sensor.electricity_monthly_energy_cost_2
    name: SVT cost
    yaxis: y3
    line:
      color: darkorange
      width: 2
      shape: linear
    show_value: true
  - entity: sensor.octopus_current
    name: Price (Max)
    statistic: max
    period: day
    showlegend: false
    line:
      color: rgba(81, 117, 159, 0.4)
      width: 1
      shape: spline
    yaxis: y2
  - entity: sensor.octopus_current
    name: Price
    statistic: min
    period: day
    fill: tonexty
    fillcolor: rgba(81, 117, 159, 0.2)
    line:
      color: rgba(81, 117, 159, 0.4)
      shape: spline
    yaxis: y2
  - entity: sensor.octopus_current
    name: Price (Mean)
    statistic: mean
    period: day
    texttemplate: ' %{y:.4f}'
    line:
      color: rgba(143, 86, 164, 1)
      width: 1
      shape: spline
    showlegend: false
    show_value: false
    yaxis: y2
  - entity: sensor.octopus_svt_price
    name: SVT Price
    yaxis: y2
    connectgaps: true
    line:
      color: grey
  - entity: ''
    name: Average £/kWh
    texttemplate: ' %{y:.4f}'
    filters:
      - load_var: cost
      - load_var: kwh
      - map_y: vars.cost.ys[i] / vars.kwh.ys[i]
    line:
      color: red
      width: 1
    show_value: true
    yaxis: y2
  - entity: ''
    name: Now
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: $fn () => [Date.now(), Date.now()]
    'y': $fn () => [0,1]
```
