### DISCUSSION TITLE
Display of cyclically reset values (HCA)

### DISCUSSION THREAD

**Discussion by Skysurfer-14** [dbuezas/lovelace-plotly-graph-card#438] [Q&A]
It is about the visualization of heat cost allocators (HCA), whose monthly values I want to display as a bar graph with lovelace-plotly-graph-card. I would also like to display the previous year's values as a comparison. This works very well with "offset". However, I still have two problems:

1. the HCA value is set back to 0 on the key date, usually 31.12.
2. the reset HCA value only appears on 1.1. at around 6:00 a.m., as the heat cost allocators do not send anything at night.

Point 1. should not be unusual, as there are many sensor values that are reset daily or monthly, for example.
Point 2. could theoretically be corrected by a time offset.
![grafik](https://github.com/user-attachments/assets/c1181450-bc32-4295-a937-3950f7dbe5af)

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.hca_summe_eg_wohnung
    name: Dieses Jahr
    statistic: state
    type: bar
    filters:
      - delta: null
    period: month
  - entity: sensor.hca_summe_eg_wohnung
    name: Vorjahr
    statistic: state
    type: bar
    filters:
      - delta: null
    period: month
    time_offset: 1y
hours_to_show: 1y
refresh_interval: 10
title: Heizkostenverteiler
```

![grafik](https://github.com/user-attachments/assets/fdb2065e-df8a-4113-be17-db1db440bf6f)
Any advice and help is welcome!

**Comment by dbuezas** [comment]
This may work:
```yaml
filters:
  - derivate:
  - filter: y > 0
  - integrate:
```

**Comment by Skysurfer-14** [comment]
Hi dbuezas,
Thank you for your hint, but the result is not as desired:
![grafik](https://github.com/user-attachments/assets/8548c034-1429-4549-8708-5c6c686b9d40)
I think, - integrate: is not useful, since the HAC-value ist increasing throughout the year. And - filter: y > 0 cuts the negative values, but this helps not to display the right value for january.

**Reply by dbuezas** [reply]
Oh, I misunderstood what you needed. I thought you wanted to have a continuously increasing value across years.

I don't quite understand what you expect to have as a result, maybe you can make a drawing

**Comment by Skysurfer-14** [comment]
I changed my graph now to show bars for each week, not month. Thats more useful, I think. I now also display the original entity as a line. This allows the user to see their total consumption in addition to the current values and compare it with the previous year's values. (As I do not yet have any values from the previous year, these are of course not yet displayed). This display comes very close to my goal. Only the jump of the entity on January 1st to 0 is still a problem.
![grafik](https://github.com/user-attachments/assets/26ede8a2-2bdb-49ae-87bb-d2573164835e)
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.hca_summe_eg_wohnung
    name: Dieses Jahr
    statistic: state
    type: bar
    filters:
      - delta: null
      - filter: y > 0
    period: week
  - entity: sensor.hca_summe_eg_wohnung
    name: Dieses Jahr (Summe)
    statistic: state
    type: line
    filters:
      - filter: y > 0
    period: day
  - entity: sensor.hca_summe_eg_wohnung
    name: Vorjahr
    statistic: state
    type: bar
    filters:
      - delta: null
      - filter: y > 0
    period: week
    time_offset: 1y
hours_to_show: 1y
refresh_interval: 10
title: Heizkostenverteiler
```

**Reply by dbuezas** [reply]
> Only the jump of the entity on January 1st to 0 is still a problem

What do you want to see instead?

**Comment by Skysurfer-14** [comment]
> What do you want to see instead?

I would like to see a correct display for the time interval in which the reset takes place.  But I now doubt whether plotly-graph can correct this. The height of the jump to 0 would have to be added to all subsequent values.

The cleanest solution would probably be to change the time of the reset to summer, outside the heating period. However, I still have to investigate whether this is legally and technically possible.

**Reply by dbuezas** [reply]
you can do that with https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/438#discussioncomment-10255249

**Comment by Skysurfer-14** [comment]
> you can do that with https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/438#discussioncomment-10255249

With the settings
```
    filters:
     - derivate:
     - filter: y > 0
#     - integrate:
```
I still have a gap in January. With the integrate command I get not the bargraph that I wanted.

It is not possible to change the reset time in the heat cost allocators after installation. But I had already created a helper for the weekly consumption values earlier. This consumtion helper is resettet every week. This means that the reset on January 1 is no longer a problem.

However, there seem to be occasional errors, probably because the measured values are scanned with a time delay and then the zero value of the helper is read in and displayed. This can be observed here in the last week of March (yellow mark).
![grafik](https://github.com/user-attachments/assets/779ba63d-c6ca-45d5-89e0-9278a9aa86a5)
Is there a time_offset command to fix this?
