### DISCUSSION TITLE
How to make continuous lines for missing values?

### DISCUSSION THREAD

**Discussion by Photelegy** [dbuezas/lovelace-plotly-graph-card#44] [Q&A] [answered]
I have a cover and want to plot the position. But when the cover is not used for some time it goes into sleep mode and doesn't send any values.
How can I tell your plotly-graph-card to connect the line where there are missing values?

Somewhat like in Excel (handling missing data) https://www.nurturetechacademy.in/how-to-handle-missing-data-in-excel-charts/

![image](https://user-images.githubusercontent.com/61714583/168339041-46a75d08-3059-489f-a96a-2a5e3ef56555.png)

```
type: custom:plotly-graph
entities:
  - entity: sensor.rollo_w_sensor_position
    name: West
    line:
      color: yellow
      width: 2
  - entity: sensor.rollo_o_sensor_position
    name: Ost
    line:
      color: cyan
      dash: dot
      width: 2
hours_to_show: 24
refresh_interval: 10
title: Rollo-Position
layout:
  height: 310
  margin:
    t: 70
    l: 50
    r: 5
  dragmode: pan
  showlegend: true
  legend:
    x: 0
    'y': -0.25
    bgcolor: rgba(0,0,0,.7)
    orientation: h
    itemsizing: constant
    font:
      size: 10
  xaxis:
    rangeselector:
      'y': 1.05
      buttons:
        - count: 1
          step: hour
        - count: 2
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 2
          step: day
        - count: 7
          step: day
  yaxis:
    fixedrange: true
    range:
      - -0.5
      - 100.5
    title: Position [%]
```

**Comment by dbuezas** [comment, marked as answer]
filter the unknown/unavailable with a lambda:
```yaml
entities:
   - entity: sensor.mysensor
     lambda: |-
        ys => ys.map(y => +y)
```
The way this works is that when your cover goes to sleep, HomeAssistant will store a datapoint with "unavailable" as its value. Then the + (plus symbol) in the lambda will make javascript try to cast (convert) it to a number, and the javascript will treat the string "unavailable"  as "not a number" or NaN. Finally, Plotly should discard those NaNs.

If this doesn't work, let me know and I'll help you filter those more explicitly

**Reply by Photelegy** [reply]
Thanks for your answer!
Sadly it doesn't seem to work.

```
type: custom:plotly-graph
entities:
  - entity: sensor.rollo_w_sensor_position
    name: West
    lambda: |-
      ys => ys.map(y => +y)
    line:
      color: orange
      width: 2
  - entity: sensor.rollo_o_sensor_position
    name: Ost
    lambda: |-
      ys => ys.map(y => +y)
    line:
      color: '#1f77b4'
      dash: dot
      width: 2
hours_to_show: 24
refresh_interval: 10
layout:
  height: 310
  margin:
    t: 70
    l: 45
    r: 5
  dragmode: pan
  showlegend: true
  legend:
    x: 0
    'y': -0.25
    bgcolor: rgba(0,0,0,.7)
    orientation: h
    itemsizing: constant
    font:
      size: 10
  xaxis:
    rangeselector:
      'y': 1.05
      buttons:
        - count: 1
          step: hour
        - count: 2
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 2
          step: day
        - count: 7
          step: day
  yaxis:
    fixedrange: true
    range:
      - -5
      - 110
    title: Position [%]
```

![image](https://user-images.githubusercontent.com/61714583/168439389-3521cc4a-3504-4936-bb88-289a8ec158b8.png)

**Reply by dbuezas** [reply]
Ok I see. The trick from before solves some but not all cases.
Filtering them completely should do the trick.


Add this at the end
```yaml
defaults:
  entity:
    lambda: |-
      (ys, xs)=>({
        y:ys.filter(y=>!Number.isNaN(parseFloat(y))),
        x:xs.filter((x,i)=>!Number.isNaN(parseFloat(ys[i]))),
      })
```
it will apply to all entities

**Reply by Photelegy** [reply]
Wow, thank you!
This works!

**Reply by macbih** [reply]
David @dbuezas, can you please provide an example of how to achieve the same with the `filters` function as the `lambda` function is deprecated since version 3.0.0? Thank you!

**Reply by dbuezas** [reply]
Please search in the readme. There is the `fn`  filter which is almost like a lambda, and that specific code should be the `force_numeric` filter

**Reply by macbih** [reply]
Thank you for your fast response!

In fact I did read the readme but unfortunately I did not succeed in the first run. After playing around with the syntax a bit (honestly, I didn't really know what to do), I did have some success. For reference, the following 2 examples will both do the trick:

1.  Uses `fn` (reusing the `lambda` function from above):

```
defaults:
  entity:
    filters:
      - fn: |-
          ({xs, ys}) => {
            return {
              ys: ys.filter(ys=>!Number.isNaN(parseFloat(ys))),
              xs: xs.filter((xs,i)=>!Number.isNaN(parseFloat(ys[i]))),
            };
          }
```

2.  Uses `force_numeric` (much shorter and therefore more elegant):

```
defaults:
  entity:
    filters:
      - force_numeric
```

Thank you yery much for the new filters!
