### DISCUSSION TITLE
How to handle missing data with a scatter plot?

### DISCUSSION THREAD

**Discussion by caiusseverus** [dbuezas/lovelace-plotly-graph-card#443] [Q&A] [answered]
I have a scatter plot which should show the amount of heating time in each day on the x axis, and the corresponding amount of gas used on the y axis. I have something adapted from some other examples here, but it produces some spurious results. Because the gas data has only been available for a relatively short period of time in home assistant and the heating has been off over summer, what I was expecting to see was a line of dots down the x=0 line, but with some varying amount of gas used which corresponds to hot water and cooking.

That is mostly what it looks like, but the problem is that there are points plotted indicating days with heating time but with gas quantities which are incorrect, and that means that all of the data is likely incorrect. I think this is because the length of the arrays for each entity are different as they are not paired up with each other, so when there is a day or more with data missing, the alignment is lost.

![image](https://github.com/user-attachments/assets/291d8020-9c36-4775-9743-0dec777c34ab)

YAML:
```
type: custom:plotly-graph
title: Heating Time vs Gas usage
raw_plotly_config: true
hours_to_show: 120d
entities:
  - entity: sensor.heating_today
    internal: true
    statistic: max
    period: day
    fn: $fn ({ xs, ys, vars }) => { vars.heating = ys; vars.xs = xs; }
  - entity: sensor.gas_meter_day
    internal: true
    statistic: state
    period: day
    fn: $fn ({ ys, vars }) => vars.gas = ys
  - entity: sensor.outside_temperature
    internal: true
    statistic: mean
    period: day
    fn: $fn ({ ys, vars }) => vars.color = ys
  - entity: ''
    x: $fn ({ vars }) => vars.heating
    'y': $fn ({ vars }) => vars.gas
    mode: markers
    name: points
    filters:
      - fn: console.log
    marker:
      color: $fn ({ vars }) => vars.color
      colorscale: Viridis
      colorbar:
        title: Av Outside Temperature
      size: 8
      type: scatter
layout:
  margin:
    t: 10
    l: 70
    r: 20
    b: 70
  height: 750
  showlegend: false
  xaxis:
    title:
      text: Heating Time
    dtick: 2
    zeroline: false
    range:
      - 0
      - 15
  yaxis:
    title:
      text: Gas Usage
    dtick: 1
    zeroline: false

```

How do I go about forcing the data points to be matched with the same dates so that only those with all the data present are plotted?

Edit - answer marked, but note minor correction to include x data:

```
      $fn ({ xs, ys, vars }) => {
        let i = -1;
        vars.gas = vars.xs.map((axis_x)=>{
            while (xs[i+1] <= axis_x && i<xs.length) i++;
            return ys[i];
        })
      }
```
