### DISCUSSION TITLE
Fillgradient

### DISCUSSION THREAD

**Discussion by SNoof85** [dbuezas/lovelace-plotly-graph-card#447] [Show and tell]
Hi !
As fillgradient has been added with 3.3.5 version of the mighty plotly graph card here is a basic example on how to do it 👍 
```
type: custom:plotly-graph
entities:
  - entity: sensor.my_awesome_sensor
    type: scatter
    mode: lines
    showlegend: false
    line:
      width: 0
      color: rgba(100, 100, 100, 0.3)
    fill: tozeroy
    fillgradient:
      start: 0
      stop: 600
      colorscale:
        - - 0
          - rgba(255, 0, 0, 0.8);
        - - 0.5
          - rgba(255, 165, 0, 0.8)
        - - 1
          - rgba(0, 128, 0, 0.8)
      type: vertical
title: Example
hours_to_show: 24h
```
This will give a gradient from red to green with some orange in the middle.
Red will be from 0 to 300, orange at 300, and green from 300 to 600.

I use it for my solar production power (which was really bad today !) : 
![image](https://github.com/user-attachments/assets/a8106a6e-25e2-4277-99ea-bfd362c7f58f)
