### DISCUSSION TITLE
How to add background colors (gradient or areas) or colorize specific grid lines?

### DISCUSSION THREAD

**Discussion by Photelegy** [dbuezas/lovelace-plotly-graph-card#45] [Q&A] [answered]
Hi
(I know I asked many questions already. I really tried to find the solution at "plotly.js ..." but I'm really confused because I don't have experience with JavaScript.)

I really hope my questions here (with your amazing answers can help a lot of other people to make the plotly-graph-card more widely used in HomeAssistant!

1. Is there a way to make background color areas like in to following picture (made in "Grafana" PlugIn for HomeAssistant):
It would be really helpful e.g. for a light sensor because many people don't know how many lux is bright. And with colors (dark blue to bright yellow) it's pretty easy to understand more or less.)
![image](https://user-images.githubusercontent.com/61714583/168775251-259d9d94-4f45-41e9-9b82-5cadc1c3d8bf.png)

2. Is there a way to colorize specific grid lines (like the line at y=0 or always at midnight x=00:00)
Like the two thick red lines in the following picture.
![image](https://user-images.githubusercontent.com/61714583/168777731-6aa1d64b-33d1-4032-8f6b-b2f2265d1537.png)

Thank you very much!

**Comment by dbuezas** [comment, marked as answer]
Oh, that's an interesting idea!
For that you need to use shapes.
## Example
![image](https://user-images.githubusercontent.com/777196/168808341-18d1e1ce-4e09-4fd9-a156-532d6596108a.png)

```yaml
layout:
  shapes:
    - type: rect
      xref: paper # means that x0 and x1 are relative to the screen, not the value of the axis themselves. 
      yref: 'y' # means that y0 and y1 are relative to the first yaxis (if you have multiple yaxes, this can be y2, y3, etc)
      x0: 0 # 0 = start  (see xref)
      x1: 1 # 1 = end (see xref)
      y0: 0 # zero of the actual yaxis
      y1: 50 # in whatever units the axis shows
      fillcolor: green
      opacity: 0.2
      line:
        width: 0
    - type: rect
      xref: paper
      yref: 'y'
      x0: 0
      x1: 1
      y0: 50
      y1: 100
      fillcolor: yellow
      opacity: 0.2
      line:
        width: 0
    - type: rect
      xref: paper
      yref: 'y'
      x0: 0
      x1: 1
      y0: 100
      y1: 200
      fillcolor: red
      opacity: 0.2
      line:
        width: 0
```

## More here
* https://plotly.com/javascript/shapes/#highlighting-time-series-regions-with-rectangle-shapes
* https://plotly.com/javascript/reference/layout/shapes/#layout-shapes

--
I appreciate that you googled first, don't worry about posting more questions :)

**Reply by Photelegy** [reply]
Thank you.
Works great.
But the problem now is, that the auto-scaling (when double-clicking on the y-axis) it zooms out to show all the rectangles.
But I want to make a blue rectangle for cold temperatures (below 15°C to e.g. -10°C) but then in summer it scales out to show -10°C even if the temperatures are between 15°C ... 32°C.
(With the x-axis it's good because its relative to the screen.)

**Reply by Photelegy** [reply]
Do you have an Idea why "line" isn't working?
I can make a very narrow rectangle but when I zoom out it's to thin and when I zoom in it's to thick.
So I hoped there is a way to do it with "line" and have the y-position relative to the y-axis and the width relative to the screen (so it's always e.g. 1px no matter how much I zoom.

```
layout:
  shapes:
    - type: line
      xref: paper # means that x0 and x1 are relative to the screen, not the value of the axis themselves. 
      yref: 'y2' # means that y0 and y1 are relative to the first yaxis (if you have multiple yaxes, this can be y2, y3, etc)
      x0: -0.01 # 0 = start  (see xref)
      x1: 1 # 1 = end (see xref)
      y1: 0 # in whatever units the axis shows
      y0: 0 # zero of the actual yaxis
      fillcolor: red
      opacity: 0.8
      layer: below                       # This makes the shape go behind the graph-lines (so Opacity isn't really necessary)
      line:
        width: 0
```

**Reply by dbuezas** [reply]
You may be able to isolate autoranging from the shapes by using yanchor and ysizemode (https://plotly.com/javascript/reference/layout/shapes/#layout-shapes-items-shape-yanchor).
I haven't tried it myself, but it sounds like one can fix one side of the rectangle to the y scale, and then make the other size go a fixed number of pixels (not zoom relative) up or down.

**Reply by dbuezas** [reply]
And regarding the line type, I think it's because you set it's width to zero. Try with `width: 1`

**Reply by dbuezas** [reply]
Ok, I tried it and managed to get it to work. The idea is to make the shape position relative to the y axis' units, but then set its size in pixels. Plotly then doesn't know how to autorange that and we get (almost by accident) exactly what you needed.
Note that this will only work with the shapes at the extremes of the axis.

```yaml
layout:
  margin:
    r: 40
  shapes:
    - type: rect
      xref: paper
      x0: 0
      x1: 1
      yref: 'y'
      yanchor: 50
      ysizemode: pixel
      y0: 0
      y1: -10000 # in pixels
      fillcolor: green
      opacity: 0.2
      line:
        width: 0
    - type: rect
      xref: paper
      yref: 'y'
      x0: 0
      x1: 1
      y0: 50
      y1: 100
      fillcolor: yellow
      opacity: 0.2
      line:
        width: 0
    - type: rect
      xref: paper
      x0: 0
      x1: 1
      yref: 'y'
      yanchor: 100 # y0 and y1 are relative to this in the y scale
      ysizemode: pixel  # y0 and y1 are measured in pixels
      y0: 0
      y1: 10000 # in pixels
      fillcolor: red
      opacity: 0.2
      line:
        width: 0
```

**Reply by Photelegy** [reply]
You're a genius!
This works perfectly.
(And yes, the line works as well. I had to give `width: 1` and the color of the line (not fillcolor) = red).

PS:
You don't need opacity if you put `layer: below` in, than it's behind the graph lines.

This is now my code for a color-background for y1 (Temperatures) and 0-line for y2 (relative Temperature Inside vs. Outside):

![image](https://user-images.githubusercontent.com/61714583/170083783-d598045f-7a79-4f57-8403-4f668d04c8e6.png)

```
layout:
  shapes:
    - type: rect
      xref: paper
      x0: 0
      x1: 1
      yref: y1
      yanchor: 26
      ysizemode: pixel
      y1: 1000
      y0: 0
      fillcolor: red
      opacity: 0.1
      layer: below
      line:
        width: 0
    - type: rect
      xref: paper
      yref: y1
      x0: 0
      x1: 1
      y1: 22
      y0: 26
      fillcolor: orange
      opacity: 0.2
      layer: below
      line:
        width: 0
    - type: rect
      xref: paper
      yref: y1
      x0: 0
      x1: 1
      y1: 22
      y0: 20
      fillcolor: '#1c7d01'
      opacity: 0.4
      layer: below
      line:
        width: 0
    - type: rect
      xref: paper
      yref: y1
      x0: 0
      x1: 1
      y1: 20
      y0: 18
      fillcolor: '#02dbc6'
      opacity: 0.2
      layer: below
      line:
        width: 0
    - type: rect
      xref: paper
      yref: y1
      x0: 0
      x1: 1
      yanchor: 18
      ysizemode: pixel
      y1: 0
      y0: -1000
      fillcolor: blue
      opacity: 0.1
      layer: below
      line:
        width: 0
    - type: line
      xref: paper
      yref: y2
      x0: -0.01
      x1: 1
      y1: 0.08
      y0: -0.08
      opacity: 1
      layer: below
      line:
        width: 1
        color: red
```

**Reply by dbuezas** [reply]
Looks really good!
👏👏👏
Thanks for the tip on layer

**Reply by Qhilm** [reply]
Follow-up question: is it possible to have plotly autorange based on the entity's values only and ignore the shapes?

Example: shapes are stacked from 0 to 100%, but cruve oscillate between 40 and 60% most of the time. I would like plotly to automatically zoom in on the range of y-values that are within the time range (x-axis) displayed.

**Reply by dbuezas** [reply]
I did this so long ago that I don't remember why it works (doesn't affect autoscale)

```yaml
layout:
  margin:
    r: 40
  shapes:
    - type: rect
      xref: paper
      x0: 0
      x1: 1
      yref: 'y'
      yanchor: 50
      ysizemode: pixel
      y0: 0
      y1: -1000
      fillcolor: green
      opacity: 0.2
      line:
        width: 0
    - type: rect
      xref: paper
      yref: 'y'
      x0: 0
      x1: 1
      y0: 50
      y1: 100
      fillcolor: yellow
      opacity: 0.2
      line:
        width: 0
    - type: rect
      xref: paper
      x0: 0
      x1: 1
      yref: 'y'
      yanchor: 100
      ysizemode: pixel
      y0: 0
      y1: 1000
      fillcolor: red
      opacity: 0.2
      line:
        width: 0
```
