### DISCUSSION TITLE
Stupid beginner's question #2

### DISCUSSION THREAD

**Discussion by Tom-Bom-badil** [dbuezas/lovelace-plotly-graph-card#456] [General]
Heya,

loving this graph card, thanks for all the work David.

A new problem here at my end: For a while, I was working with some fixed values in the fn: section of a plotly graph, just to figure out how everything works, and to fiddle around:

![image](https://github.com/user-attachments/assets/74c1f092-a112-4c97-9421-acac51eaf02b)

```
                    fn: |
                      $fn ({ vars, state }) => {
                        
                        const x = []; 
                        const y = [];
                        
                        let af1= -10;
                        let tagbetrieb_rk1 = 1;
                        let tag_soll = 19;
                        let nacht_soll = 19;
                        let niveau = -1;
                        let steigung = 0.2;
                        let vorlauf_min = 20;
                        let vorlauf_max = 37;
                        
                        let AT = -20;
                        let lauf=0;

                        if (tagbetrieb_rk1)
                          SOLL = tag_soll;
                        else
                          SOLL = nacht_soll;
                        while (AT < 25) {
                          x[lauf] = AT;
                          y[lauf] =
                            24 + niveau + 2 * steigung * (SOLL - 20) -
                            (0.1 + 0.9 * steigung) * (1.5 * (AT - 20) + 0.01 * Math.pow(AT - 20, 2));
                          if (y[lauf] < vorlauf_min) y[lauf] = vorlauf_min;
                          if (y[lauf] > vorlauf_max) y[lauf] = vorlauf_max;
                          lauf += 1;
                          AT += 1;
                         }
                        vars.x = x;
                        vars.y = y;
                      };
                    x: $fn ({ vars }) => vars.x
                    y: $fn ({ vars }) => vars.y
```

So far, so good. Successfully figured out the future look-and-feel of this particular graph, which is one of 4 (the other 3 are rather complex) on the same HA page.

Now it's time to replace all those fixed `let variable=fixed_value;` lines with real-time values from HA. E.g. the `af1` variable is supposed to be read from 'sensor.aussen': Something like `let af1={{ HA.sensor.aussen }}`.

> My question is: How do I pass a HA sensor value into this?

Sorry if this question is kinda stupid - tried several approaches, all failed. Guess try-and-error won't bring me any further.

Thanks,
/tom

**Comment by dbuezas** [comment]
You do that with the `entity: sensor.xyz` property.
Cheers!

**Comment by Tom-Bom-badil** [comment]
Thanks the instant response, David, much appreciated! :) Figured it out - #362 helped A LOT.

_  --> push in 'internal' entities by using fn:, pick it up within, work with it_

Having a dynamic heating curve with controller values through Modbus now. Works like a charm (knocking on wood).

Cheers and thanks again,
/tom

**Comment by Tom-Bom-badil** [comment]
Just one more of those questions: I have a tap action set on 3 different buttons that switches a 'dummy' entity to state 1 or 2 or 3 (depending on which button is clicked). Based on that dummy entity, the same plot with different parameters is presented (see bottom left plot). All parameters are passed through internal entities (`fn: $ex vars.whatever = ys.at(-1)`) for heating curve calculation via a fn:.

So far, so good - working as intended.

HOWEVER - it seems, the passing of parameters and re-calculation are done instantly, while the graph refresh only happens after one of the involved entities is changed (it is not sufficient that only the dummy entity changes; I even tried to define the dummy twice, both as internal AND non-internal; no success).

See video, watch Y scale compared to the min/max temperatures in the text bottom right of the graph after the click - click happens at 00:10, both text annotations top left / bottom right change instantly, plot refresh happens at 00:25, so 15s later - sometimes it takes minutes).

Is there a way to externally trigger / force the refresh of the plotly graph when that 'dummy' entity changes, or a tap action is done?

https://github.com/user-attachments/assets/097cc96d-625f-41a3-b383-7ac742510c03

Thanks,
/tom

**Reply by dbuezas** [reply]
if `update_interval: auto` doesn't work, the only option left is to use a very low `update_interval: 1s`

**Reply by Tom-Bom-badil** [reply]
Thanks, David. Meanwhile I have reworked that part and moved the calculations of the heating curves out of plotly and into template sensor attributes (needs to be attributes due to the 256 character 'state' limitation). That reduced the complexity and length of the whole YAML quite significantly (I had to handle >20 internal entitties with all those calculation parameters in the end).

However, there is an odd observation of using plotly fn: vs. working with [[[ ]]] (it's a bit difficult to explain):

- The refresh problem as shown above persists when using fn:/$ex for x and y assignment. A plot refresh sometimes takes minutes after selection of another heating circuit. Logs are showing that it sometimes even seems to be stuck at some point; e.g. after clicking button # 2, it is instantly noticing the but logs are telling me that it still is on circuit # 1; then after clicking # 3, it's switching to previously selected # 2 etc:
```yaml
- entity: input_number.trovis_visu_heizkreis
- entity: input_number.trovis_visu_heizkreis
  internal: true
  fn: $ex vars.heizkreis = ys.at(-1)
- entity: sensor.trovis_hk123_heizkurven
  attribute: x_werte
  internal: true
  fn: $ex vars.trovis_hk123_x = ys.at(-1)
- entity: sensor.trovis_hk123_heizkurven
  attribute: $ex 'hk' + parseInt(vars.heizkreis);
  internal: true
  fn: $ex vars.trovis_y = ys.at(-1)
- entity: ''
  name: Heizkurve
  line:
    shape: spline
    color: black
  x: $ex JSON.parse(JSON.stringify(vars.trovis_hk123_x))
  'y': $ex JSON.parse(JSON.stringify(vars.trovis_y));
```
- If I replace the $ex, it works like a charm and as expected. Refresh is done instantly after `input_number.trovis_visu_heizkreis` gets a new value between 1...3 from a tap on the corresponding button:
```yaml
- entity: input_number.trovis_visu_heizkreis
- entity: ''
  name: Heizkurve
  line:
        shape: spline
        color: black
  x: |
    [[[
      /* replaces: 'x: $ex JSON.parse(JSON.stringify(vars.trovis_hk123_x')) */
      return states['sensor.trovis_hk123_heizkurven'].attributes.x_werte;
    ]]]
  'y': |
    [[[
      /* replaces: '"y": $ex JSON.parse(JSON.stringify(vars.trovis_y')); */
      let kreis = parseInt(states['input_number.trovis_visu_heizkreis'].state);
      if (kreis == 1)
        return states['sensor.trovis_hk123_heizkurven'].attributes.hk1;
      else if (kreis == 2)
        return states['sensor.trovis_hk123_heizkurven'].attributes.hk2;
      else if (kreis == 3)
        return states['sensor.trovis_hk123_heizkurven'].attributes.hk3;
    ]]]
```

https://github.com/user-attachments/assets/fc14a9a3-750d-40af-9de4-509e907c3373

A bit weird. But as it is working now, I will stick to the second way and avoid the internal fn:/$ex stuff. Time to move on to the plots on the right-hand side of this page, which are way easier to do. Thanks all your help!

/tom

**Reply by dbuezas** [reply]
Try removing `internal: true`, maybe there's a big with that

**Reply by Tom-Bom-badil** [reply]
Nope - also happens to 'plain' entities which are non-internal. After reworking the marker (diamond) in the video above, it is now instantly setting when the value for the current outside temperature is changed through the developer tools. Before I had to wait till next refresh, similar to waiting for the plot:

```yaml
entities:
  - entity: ''
    name: Aktuell
    mode: markers
    marker:
      color: grey
      size: 15
      line:
        color: black
        width: 3
      symbol: diamond
    x:
      - |-
        [[[
          /* replaces: '$ex hass.states['sensor.trovis_fuhler_aussen_1_af1'].state' */
          return states['sensor.trovis_fuhler_aussen_1_af1'].state;
        ]]]
    'y':
      - |-
        [[[
          /* replaces: '$ex hass.states['sensor.trovis_fuhler_vorlauf_1_vf1'].state' */
          return states['sensor.trovis_fuhler_vorlauf_1_vf1'].state;
        ]]]
```

Weird. That's for sure not nice nor elegant code, but it's working.

/tom
