### DISCUSSION TITLE
Timestamp in attribute

### DISCUSSION THREAD

**Discussion by froggi1930** [dbuezas/lovelace-plotly-graph-card#458] [Q&A]
Hi everyone,

I’ve typically used simple charts in Home Assistant so far, but I recently discovered the Plotly card, and I’m a bit overwhelmed by its potential!

I want to create a graph to display my solar production forecast.

Using the template engine, I get:

```powershell
{% set data = state_attr('sensor.my_solar_production_forecast_today', 'data') %}
{{data}}

[{'timestamp': '2024-10-08 07:43:53', 'value': 0}, {'timestamp': '2024-10-08 07:45:00', 'value': 318688}, ...]
``` 

How can I best integrate this data into the Plotly card?

Thanks in advance for any guidance - I’m feeling a bit lost here!

**Comment by dbuezas** [comment]
Either of these should work:

```yaml
 - entity: ''
    name: My solar production forecast today
    filters:
      - fn: |-
          ({hass}) => ({
            xs: hass.states['sensor.my_solar_production_forecast_today'].attributes.data.map(({ timestamp }) => new Date(timestamp)),
            ys: hass.states['sensor.my_solar_production_forecast_today'].attributes.data.map(({ value }) => value),
          })

```


```yaml
 - entity: ''
    name: My solar production forecast today
    x: "$ex hass.states['sensor.my_solar_production_forecast_today'].attributes.data.map(({ timestamp }) => new Date(timestamp))"
    y: "$ex hass.states['sensor.my_solar_production_forecast_today'].attributes.data.map(({ value }) => value)"

```
