### DISCUSSION TITLE
Plot different units in one Graph

### DISCUSSION THREAD

**Discussion by coxtor** [dbuezas/lovelace-plotly-graph-card#46] [Q&A] [answered]
Hi, 
I was wondering if it is possible to plot different units against each other in one graph e.g. having multiple y-axes in one plot. 
Essentially something like this:
[Link to graph](https://matplotlib.org/stable/_images/sphx_glr_multiple_yaxis_with_spines_001.png)

**Comment by dbuezas** [comment, marked as answer]
Yes it is, but the third one won't be shown like in your example.
The card will do that automatically if the unit_of_measurement don't match.
You can also use 
```yaml
entities:
  - entity: sensor.mysensor
    yaxis: y
  - entity: sendor.myothersensor
    yaxis: y2
```

For more google "plotly.js multiple y axes".
