### DISCUSSION TITLE
Change the units on the yaxis?

### DISCUSSION THREAD

**Discussion by ando2040** [dbuezas/lovelace-plotly-graph-card#461] [General]
Sorry if this is a newbie question - I've searched and not found this. I did find how to use ```ex``` to manipulate the legend... so now I would like to manipulate the yaxis to also /1000 and have the label 'GW' - is that possible please?

![image](https://github.com/user-attachments/assets/5d8e9a1a-a6f7-44c7-827e-4e3548a50444)

```
type: custom:plotly-graph
entities:
  - entity: sensor.national_grid_grid_generation_nuclear_mw
    fillcolor: orange
    name: |
      $ex `Nuclear ${(ys.at(-1) / 1000).toFixed(2)} GW`
  - entity: sensor.national_grid_grid_generation_solar_mw
    fillcolor: yellow
    name: |
      $ex 'Solar (now) ' + (ys.at(-1)/1000).toFixed(2) + ' GW'      
  - entity: sensor.national_grid_grid_generation_wind_mw
    fillcolor: seagreen
    name: |
      $ex 'Wind (now) ' + (ys.at(-1)/1000).toFixed(2) + ' GW'
  - entity: sensor.national_grid_grid_generation_hydro_mw
    fillcolor: cyan
    name: |
      $ex 'Hydro (now) ' + (ys.at(-1)/1000).toFixed(2) + ' GW'
  - entity: sensor.national_grid_grid_generation_pumped_storage_mw
    fillcolor: cornflowerblue
    name: |
      $ex 'Gravity (now) ' + (ys.at(-1)/1000).toFixed(2) + ' GW'
  - entity: sensor.national_grid_international_dc_total_interconnectors
    fillcolor: red
    name: |
      $ex 'Imports (now) ' + (ys.at(-1)/1000).toFixed(2) + ' GW'
  - entity: sensor.national_grid_grid_generation_gas_mw
    fillcolor: purple
    name: |
      $ex 'Gas (now) ' + (ys.at(-1)/1000).toFixed(2) + ' GW'
  - entity: sensor.national_grid_grid_generation_biomass_mw
    fillcolor: brown
    name: |
      $ex 'Biomass (now) ' + (ys.at(-1)/1000).toFixed(2) + ' GW'
defaults:
  entity:
    filters:
      - resample: 1m
    line:
      width: 0
    stackgroup: one
  yaxes:
    fixedrange: true
hours_to_show: 168
refresh_interval: 10
```

**Comment by dbuezas** [comment]
Yes you can!
```yaml
defaults:
  entity:
    unit_of_measurement: GW
    filters:
      - resample: 1m
      - multiply: 0.001
```

Wait... GW? Are countries using home assistant to manage their energy grids now? 😆

**Reply by ando2040** [reply]
Thanks! Simple when you know how. 

No, I'm just finding out why my energy is cheap/expensive today...

**Reply by dbuezas** [reply]
Chat gpt also understands this. If you paste the yaml and the question it usually gets it right.
You can always ask here too of course

**Reply by dbuezas** [reply]
> No, I'm just finding out why my energy is cheap/expensive today...

That's super interesting!
Maybe the Trendline filters can become handy for that

**Reply by ando2040** [reply]
> Chat gpt also understands this. If you paste the yaml and the question it usually gets it right. You can always ask here too of course

I'd already had a GPT fail - it decided I was talking python and could use round() for the ```ex``` transformation. So I found the answer to that here and didn't try GPT again... I did just give it a go now and it started talking about tickvals, ticktext and tickformat, which clearly isn't right!

**Reply by dbuezas** [reply]
true, but it does pick it up if you also paste the yaml as example. It does "realise" there's plotly behind it.

tickformat would be useful to add the unit to the ticks inside the axis, which is not wrong per-se. Anyway, I also use it sometimes myself for my own plots.

**Reply by ando2040** [reply]
For your amusement, below is what ChatGPT said when I showed it your answer... ;-)
-
Thank you for sharing the correct approach! You're right—using the `unit_of_measurement` and applying a transformation via `multiply: 0.001` is a more straightforward solution for your specific use case.

I didn't initially suggest this because I was focused on formatting the values visually using Plotly's `tickformat` and `ticksuffix` options, rather than applying a transformation directly to the data in the configuration. Your solution applies the transformation at the data level, ensuring that all entities are scaled properly to gigawatts (GW) and formatted consistently.

This method is cleaner and avoids any need for additional formatting tricks. Here's a recap of the correct solution:

```yaml
defaults:
  entity:
    unit_of_measurement: GW  # Set unit to GW
    filters:
      - resample: 1m
      - multiply: 0.001  # Convert MW to GW by dividing by 1000
```

This effectively transforms the data, ensuring the values are represented in GW without needing further customization on the Y-axis formatting.

Thanks again for pointing that out!


I had spent several turns toying with it, telling it the answer wasn't what I needed. The worst answer was:
-
Here’s how you can achieve dividing by 1000 and displaying the Y-axis in GW correctly:

```yaml
defaults:
  entity:
    filters:
      - resample: 1m
    line:
      width: 0
    stackgroup: one
  yaxes:
    fixedrange: true
    title: "GW"  # Change Y-axis label to GW
    tickformat: " ",  # Blank tickformat so values aren’t modified
    tickprefix: "",  # Optionally remove any prefix
    ticksuffix: " GW",  # Add a GW suffix to the values
    tickmode: "auto",  # Use auto ticks
    tickvals: [0, 10000, 20000, 30000, 40000, 50000],  # Manually specify tick values (in MW)
    ticktext: ["0", "10", "20", "30", "40", "50"]  # Corresponding GW values
hours_to_show: 168
refresh_interval: 10
```
