### DISCUSSION TITLE
Stacking bar chart with total_increasing sensor

### DISCUSSION THREAD

**Discussion by ando2040** [dbuezas/lovelace-plotly-graph-card#463] [Q&A] [answered]
I'm so close on this one, any ideas please? 

After a few bad ideas ChatGPT did come up with barmode:stack instead of stackgroup, and also suggested derivate without the d which I found myself in the readme. Two of the series are stacking correctly, but the climate/heat pump one is not. So close on the 21st (heat pump value is within 0.7), but incorrect negative values on most of the other days - 15th shown should be positive 8.6.

These are all `state_class: total_increasing` sensors so I thought `statistic: state` would be appropriate reading the notes. However, `sum` works properly for two, and makes no difference for climate!

Climate happens to be a custom sensor so I could change it... but history-explorer-card extracts the daily values correctly and consistently for all three sensors.

![image](https://github.com/user-attachments/assets/03b4e740-600f-4c8e-9cf8-8029c63c7d81)

```
type: custom:plotly-graph
layout:
  barmode: stack
entities:
  - entity: sensor.immersion_water_heater_daily_consumption
    name: Immersion
    type: bar
    statistic: sum
    period: day
    filters:
      - derivate: d
  - entity: sensor.climate_total_daily_electrical_consumption
    name: Heat Pump
    type: bar
    statistic: state
    period: day
    filters:
      - derivate: d
  - entity: sensor.myenergi_zappi_xxxxxxxx_energy_used_today_2
    name: EV
    type: bar
    statistic: sum
    period: day
    filters:
      - derivate: d
hours_to_show: 300
refresh_interval: 10
```

**Comment by dbuezas** [comment]
What is it that is not working as you want?

**Reply by ando2040** [reply]
The heat pump can't be using (generating) -6.5 kWh... on 15th it was in fact 8.6kWh so I don't know why this one series is being rendered wrongly or what else to try to fix it!

![image](https://github.com/user-attachments/assets/9c5485bf-11ee-4f3d-ad4c-8bfb0db95baf)

Sensor definition is this:
```
state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
friendly_name: Climate Total Daily Electrical Consumption
```

versus one of the sensors that is rendered correctly (using sum.) This is in fact a meter helper.
```
state_class: total_increasing
status: collecting
last_period: "0.33"
last_valid_state: "952.88"
last_reset: "2024-10-26T23:00:00.003444+00:00"
next_reset: "2024-10-28T00:00:00+00:00"
unit_of_measurement: kWh
device_class: energy
friendly_name: Immersion Water Heater Daily Consumption
```

I'm going to try a meter helper for the problematic sensor as a workaround, but this will have no history so I'd prefer to get the one that has history working. 
```
state_class: total_increasing
status: collecting
last_period: "0"
last_valid_state: "3.7"
last_reset: "2024-10-27T11:38:12.619767+00:00"
next_reset: "2024-10-28T00:00:00+00:00"
unit_of_measurement: kWh
device_class: energy
friendly_name: Climate Daily consumption
```

**Reply by dbuezas** [reply]
The derivative is the rate of change, per day in your case (as you configured it). Since the source sensor was less than the day before, the derivative is negative. 
What exactly are you going after? maybe I can point to a solution

**Reply by ando2040** [reply]
I'm looking for the positive change since the previous day (8.6kWh on 15th for example - it's a total_increasing sensor, I never expect a negative value.)

But I tried a delta filter and that was unsurprisingly rendered on a separate y axis, and the values were still (mostly) negative. I also don't really understand what's different about this sensor vs the other two.

**Reply by dbuezas** [reply]
then don't use derivate. Just plot the data as is

**Reply by ando2040** [reply, marked as answer]
David, thanks for making me go back to the beginning. 

For the record, below what I was aiming for. I started down a filters route because I decided delta between two days of the total_increasing sensors was what I needed, then the bot sent me to derivate and I didn't engage my brain. It turns out `statistic: state` was right. I think I only dismissed it because I came to it late and didn't remove either derivate or delta filter when I tried it... also because derivate was producing an answer deceptively close to desired for two of three sensors. Bots are very bad at looking holistically at a problem and changing more than one thing, I've experienced that before. 

![image](https://github.com/user-attachments/assets/264cb0f0-f5d5-4bba-9aee-ed636aa4fab4)

```
type: custom:plotly-graph
layout:
  barmode: stack
entities:
  - entity: sensor.immersion_water_heater_daily_consumption
    name: Immersion
    type: bar
    statistic: state
    period: day
    filters:
      - filter: i > 0
  - entity: sensor.climate_total_daily_electrical_consumption
    name: Heat Pump
    type: bar
    statistic: state
    period: day
    filters:
      - filter: i > 0
  - entity: sensor.myenergi_zappi_xxxxxxxx_energy_used_today_2
    name: EV
    type: bar
    statistic: state
    period: day
    filters:
      - filter: i > 0
hours_to_show: 360
refresh_interval: 10
```
