### DISCUSSION TITLE
Show date in hovertemplate

### DISCUSSION THREAD

**Discussion by AlmarAubel** [dbuezas/lovelace-plotly-graph-card#476] [Q&A]
Can someone help me? How can I display the date and time of the plotted point in the hover template?
```yaml
type: custom:plotly-graph
title: EV Battery Level and Range
raw_plotly_config: true
resample: 5m
hours_to_show: 60d
entities:
  - entity: sensor.e_niro_ev_battery_level
    internal: true
    fn: $fn ({ ys, vars, rest }) =>  vars.battery = ys
  - entity: sensor.e_niro_ev_range
    internal: true
    fn: $fn ({ ys, vars }) => vars.range = ys
  - entity: ""
    x: $fn ({ vars }) => vars.battery
    "y": $fn ({ vars }) => vars.range
    mode: markers
    name: Battery vs Range
    marker:
      size: 8
      color: $fn ({ vars }) => vars.rest
      colorscale: Viridis
      colorbar:
        title: Date
    type: scatter
    hovertemplate: "Battery: Range: %{y} km<br>Date: %{marker.color|%Y-%m-%d %H:%M}"
layout:
  margin:
    t: 10
    l: 70
    r: 20
    b: 70
  height: 400
  showlegend: false
  xaxis:
    title:
      text: Battery Level (%)
    range:
      - 0
      - 100
    dtick: 10
    tick0: 0
    zeroline: false
  yaxis:
    title:
      text: Range (km)
    range:
      - 0
      - 500
    dtick: 50
    tick0: 0
    zeroline: false
```
