### DISCUSSION TITLE
Table history (not a plot!)

### DISCUSSION THREAD

**Discussion by dbuezas** [dbuezas/lovelace-plotly-graph-card#477] [Show and tell]
I have a sensor that is actually the message shown in the screen of my 3d printer. I wanted to see previous logged messages and the standard markdown table cannot access history. Guess who does!

<img width="457" alt="image" src="https://github.com/user-attachments/assets/0d057191-7d4f-46df-83c7-f96b57115943"><img width="454" alt="image" src="https://github.com/user-attachments/assets/193c671b-0568-4cc3-8f5d-98eb2e255a79">

```yaml
type: custom:plotly-graph
hours_to_show: current_day
layout:
  margin:
    l: 10
    t: 0
    r: 10
    b: 10
entities:
  - entity: sensor.ultimaker_notification
    type: table
    columnwidth:
      - 16
      - 80
    header:
      values:
        - Time
        - Notification
      align: center
      fill:
        color: $ex css_vars["primary-color"]
      font:
        size: 12
        color: $ex css_vars["primary-text-color"]
    filters:
      - filter: i>-1 && i<ys.length-1
    cells:
      values:
        - |
          $ex xs.toReversed().map(x=>
            new Intl.DateTimeFormat('en-GB', {
              hour: '2-digit',
              minute: '2-digit',
              second: '2-digit',
              fractionalSecondDigits: 1,
              hour12: false
            }).format(x))
        - $ex ys.toReversed()
      align:
        - center
        - left
      fill:
        color: $ex css_vars["card-background-color"]
      font:
        color:
          - $ex css_vars["secondary-text-color"]
          - $ex css_vars["primary-text-color"]
```
