### DISCUSSION TITLE
Transparent plotly-graph (e.g. for in Picture-Elements-Card)

### DISCUSSION THREAD

**Discussion by Photelegy** [dbuezas/lovelace-plotly-graph-card#48] [Show and tell]
For my home-map I needed a transparent plotly-graph.
After talking with dbuezas (the creater of this card) about this (https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/47) it now is possible to make the plotly-graph partially or full transparent. 😍

Since the Version v1.3.2 (at the moment only Beta) the complete-background of the plotly-graph-card is now transparent by standard, so with `paper_bgcolor:` and `plot_bgcolor:` you can make it as transparent or colored as you like.

`paper_bgcolor:`: Color of the whole card (in this example: green with 50% opacity/transparency)
`plot_bgcolor:`: Color of the coordinate system (in this example: red with 30% opacity/transparency)
Maybe you also need to recolor the text e.g. for the axis.

![image](https://user-images.githubusercontent.com/61714583/171036737-ae581b91-59d1-4c78-aca0-4ed099ba5175.png)
```
type: picture-elements
title: How to make Plotly transparent?
elements:
  - type: custom:plotly-graph
    entities:
      - entity: sensor.openweathermap_temperature
        name: OpenWeather
        yaxis: y1
        line:
          color: red
          width: 4
    hours_to_show: 48
    refresh_interval: 60
    layout:
      paper_bgcolor: rgba(0, 100, 0, 0.5)
      plot_bgcolor: rgba(100, 0, 0, 0.3)
      font:
        size: 26
      height: 500
      margin:
        t: 10
        l: 100
        r: 5
      xaxis:
        color: black
      yaxis:
        title: Temperatur [°C]
        color: black
      showlegend: false
    style:
      top: '7%'
      left: '-16%'
      transform: scale(0.4)
image: https://demo.home-assistant.io/stub_config/floorplan.png
```

So many thanks to the awsome creator of this really powerfull card!!! 👏👏👏

I'm very interested to see with what kind of ideas other people came up.

-----------------------------------------------------------------------------------------

My full code with additional features used:
- multiple y-axes (https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/39)
- colored areas and lines (https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/45)
![image](https://user-images.githubusercontent.com/61714583/171037709-f5399868-cac3-40c7-b071-a063f9c0e9b5.png)
```
type: picture-elements
title: How to make Plotly transparent?
elements:
  - type: custom:plotly-graph
    entities:
      - entity: sensor.gersau_temperature
        name: Gersau
        yaxis: y1
        line:
          color: green
          width: 5
      - entity: sensor.openweathermap_temperature
        name: OpenWeather
        yaxis: y1
        line:
          color: blue
          width: 5
      - entity: sensor.sensor_motion_eingang_temperature
        name: Eingang (indoor)
        yaxis: y1
        line:
          color: red
          width: 5
      - entity: sensor.temperature_outdoor_difference
        name: (Δ Outdoor vs. Indoor)
        yaxis: y2
        line:
          color: violet
          width: 5
    hours_to_show: 48
    refresh_interval: 60
    layout:
      paper_bgcolor: rgba(0, 100, 0, 0.5)
      plot_bgcolor: rgba(100, 0, 0, 0.3)
      font:
        size: 26
      height: 850
      margin:
        t: 10
        l: 100
        r: 5
      grid:
        rows: 2
        columns: 1
        roworder: top to bottom
      xaxis:
        color: black
      yaxis:
        title: Temperatur [°C]
        color: black
        range:
          - 10
          - 30
      yaxis2:
        title: Δ Temperatur [°C]
        color: black
        fixedrange: false
        range:
          - -15
          - 10
      showlegend: true
      legend:
        x: 0
        'y': -0.22
        bgcolor: rgba(0,0,0,0.5)
        orientation: h
        itemsizing: constant
      shapes:
        - type: rect
          xref: paper
          x0: 0
          x1: 1
          yref: y1
          yanchor: 24
          ysizemode: pixel
          y1: 1000
          y0: 0
          fillcolor: red
          opacity: 0.3
          layer: below
          line:
            width: 0
        - type: rect
          xref: paper
          yref: y1
          x0: 0
          x1: 1
          y1: 24
          y0: 20
          fillcolor: green
          opacity: 0.4
          layer: below
          line:
            width: 0
        - type: rect
          xref: paper
          yref: y1
          x0: 0
          x1: 1
          yanchor: 20
          ysizemode: pixel
          y1: 0
          y0: -1000
          fillcolor: blue
          opacity: 0.3
          layer: below
          line:
            width: 0
        - type: line
          xref: paper
          yref: y2
          x0: -0.01
          x1: 1
          y1: 0.08
          y0: -0.08
          opacity: 1
          layer: below
          line:
            width: 1
            color: red
    no_default_layout: true
    defaults:
      entity:
        show_value:
          right_margin: 12
        line:
          shape: line
        lambda: |-
          (ys, xs) => {
            const MINUTES = 10               // <-- change here
            const window_size_ms = 1000*60*MINUTES 
            const result = {x:[], y:[]}
            let x_next = +xs[0] + window_size_ms
            let y_accum = 0
            let y_count = 0
            for (let i = 0; i < xs.length; i++) {
              const x = +xs[i]
              const y = +ys[i]
              if (x>x_next){
                result.y.push(y_accum/y_count)
                result.x.push(new Date(x_next))
                y_accum = 0
                y_count = 0
                x_next = +x + window_size_ms
              }
              if (y){
                // ignore unavailable/unknown state points
                y_accum += y
                y_count ++
              }
            } 
            return result;
          }
    style:
      top: '-26%'
      left: '-16%'
      transform: scale(0.4)
image: https://demo.home-assistant.io/stub_config/floorplan.png
```¨
![image](https://user-images.githubusercontent.com/61714583/171036164-71e75ef5-89ee-425a-8fc0-0a5ee4050e35.png)

**Comment by AleXSR700** [comment]
I tried adding paper and plot bg color to a standalone plotly graph and while it does work for transparency < 100%, I see a background when I set the transparency to 100%. In theory the entire plot should be transparent except for the lines, fonts etc. But there should not be a background.
Does anybody else see this or knows a fix?

Top is an apexcharts graph with card mod. So working background/card transparency. Bottom is plotly with rgba(0,0,0,0)

![Screenshot_20220812-144733_Home Assistant.jpg](https://user-images.githubusercontent.com/57034871/184356888-b2f7214c-0148-49a0-b37c-48a20c31a741.jpg)

**Reply by dbuezas** [reply]
I just tested it and it does work as intended for me.
You may want to paste your yaml, there may be a typo somewhere

**Reply by AleXSR700** [reply]
Of course, happy to:

```
type: custom:plotly-graph
entities:
  - entity: sensor.sony_kd_75xf9005_power
refresh_interval: 10
hours_to_show: 12
defaults:
  yaxes:
    fixedrange: true
    rangemode: tozero
layout:
  paper_bgcolor: rgba(255,0,0,0)
  plot_bgcolor: rgba(0,255,0,0)
```

**Reply by dbuezas** [reply]
I can't reproduce the problem. If I go to the developer console in chrome and change the background color of the container of all cards in the dashboard (hui-view element), I see the card is fully transparent
<img width="803" alt="image" src="https://user-images.githubusercontent.com/777196/184875434-a68517d0-0d53-42ac-95cd-0dcf768c6ed3.png">

**Reply by AleXSR700** [reply]
How does it look in the companion app for you?

I switched to light theme and still see the background:

![Screenshot_20220816-151703_Home Assistant.jpg](https://user-images.githubusercontent.com/57034871/184889356-5e6f71d2-da9c-4a88-a30a-cf6b93a9e2f0.jpg)

At the top still the apex with same code as before. And at the bottom the plotly does not look transparent to me. The background of the card is white and the theme itself seems more greyish compared.

Could you post a screenshot of a normal card (non-transparent) and then a transparent plotly card?

For reference, at the top of my screenshot are two cards. One for the input select and one for the apex chart. And as you see they have no background and no border. At the bottom the plotly has a border and a different background (in this case white).
Does plotly maybe set the background to system default or a theme or something instead of making it truly invisible?
(sorry, I am not a dev, so cannot explain better)

Edit:
Maybe also an interesting screenshot. One can clearly see how the backgrounds of the plotly are not transparent in the was as they do not see the background of the page. The background is the same as the "background" of the edit bar underneath the card (which is not the same as the actual page background).
![Screenshot_20220816-152447_Home Assistant.jpg](https://user-images.githubusercontent.com/57034871/184890901-0c7a8cb1-ca24-4e66-9ab6-e61d3f43de37.jpg)

**Reply by dbuezas** [reply]
Here's from chrome in mobile mode (phone looks the same:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/777196/184890357-515750a1-a6fe-44ba-934d-a7fe1c7617f8.png">
And here's what happens when I change the background color (using a radial gradient to make it more visible):
<img width="412" alt="image" src="https://user-images.githubusercontent.com/777196/184890541-bf21537e-7388-40b4-b0b9-ebe45c948868.png">

Can you try doing the same in chrome to rule out any other factor (like having an old version of this card or other configuration interfering with the theme, etc)

**Reply by AleXSR700** [reply]
Chrome instead of Companion App:
![Screenshot_20220816-153509_Chrome.jpg](https://user-images.githubusercontent.com/57034871/184892892-9927d318-07d6-444e-aba8-1c256ef0f827.jpg)

So same problem.

Plotly card v1.3.1. Latest Home Assistant 2022.8.5.

I will try with Chrome on my PC later to check in developer options.

Edit: You used a theme to create the gradient background? Because I have no themes installed and can only select light and dark right now. I can install a theme if you want me to.

**Reply by AleXSR700** [reply]
> If I go to the developer console in chrome and change the background color of the container of all cards in the dashboard (hui-view element), I see the card is fully transparent

How do you change that color?
By the way, could it have something to do with me having config template card / card-mod installed?

**Reply by dbuezas** [reply]
Yes, card-mod can change the background of cards, and may be the reason for that behaviour.
To change the color of the background like I did (and confirm the plotly card is/isn't transparent), follow these steps:

1. Right click on an *empty space without cards*, then click "inspect"
<img width="741" alt="image" src="https://user-images.githubusercontent.com/777196/184926484-b9834593-d48e-4e68-bca5-5b697837084a.png">

2. The developer tools window will open. It's very crowded but don't worry. The element containing whatever it is that you right clicked on will be selected

3. Go to the top right of that window, click and type `background: red`
<img width="298" alt="image" src="https://user-images.githubusercontent.com/777196/184926816-4945a740-3aba-4cad-b7eb-6259280056f0.png">

4. The background of the whole dashboard should be red. Don't worry, the changes are not stored anywhere and reloading the page will undo it.

SECURITY NOTE: Do not trust ppl telling you to do things in the developer console unless you understand what you are being asked to do and/or trust the person. In principle, it is possible to steal credentials of the open website and whatnot by asking people to execute stuff in the console.

**Comment by AleXSR700** [comment]
Thank you for the explanation :)

And here is the result:
![image](https://user-images.githubusercontent.com/57034871/185038555-af7d9c6b-7384-4054-bd79-85f1c4082081.png)

Clearly not transparent.

I cannot see how my code would be incorrect since I can change the color to whatever I want by simply setting transparency to a value > 0 and changing the RGB values. So the code seems to work. But maybe you see something?
Here is the full dashboard code:
```
views:
  - theme: Backend-selected
    title: Sony KD-75XF9005
    path: sony-kd-75xf9005
    badges: []
    cards:
      - type: entities
        card_mod:
          style: |
            ha-card {
              --ha-card-background: rgba(0, 0, 0, 0);
              --ha-card-box-shadow: none;
            }
        entities:
          - entity: input_select.days_back_to_show
            name: Number Of Days To Show
      - type: custom:config-template-card
        entities:
          - input_select.days_back_to_show
        variables:
          span: states['input_select.days_back_to_show'].state+'d'
          days: |
            -states['input_select.days_back_to_show'].state+'d'+'1d'
        card:
          type: vertical-stack
          cards:
            - type: custom:auto-entities
              sort:
                method: friendly_name
              filter:
                include:
                  - entity_id: sensor.sony_kd_75xf9005_power
                    options:
                      yaxis_id: first
                      stroke_width: 2
                      group_by:
                        func: raw
                      type: line
                      opacity: 1
                      curve: stepline
                      fill_raw: last
              card:
                type: custom:apexcharts-card
                card_mod:
                  style: |
                    ha-card {
                      --ha-card-background: rgba(0, 0, 0, 0);
                      --ha-card-box-shadow: none;
                    }
                graph_span: ${span}
                yaxis:
                  - id: first
                    show: true
                    min: 0
                    decimals: 0
                  - id: second
                    show: true
                    min: 0
                    decimals: 2
                header:
                  title: Sony KD-75XF9005
                  show: true
                  show_states: true
                  colorize_states: true
                apex_config:
                  legend:
                    show: false
                  grid:
                    show: true
                  chart:
                    zoom:
                      enabled: true
                    pan:
                      enabled: true
                    toolbar:
                      show: true
                      tools:
                        zoom: true
                        zoomin: true
                        zoomout: true
                        pan: true
                        reset: true
      - type: custom:plotly-graph
        entities:
          - entity: sensor.sony_kd_75xf9005_power
        refresh_interval: 10
        hours_to_show: 12
        defaults:
          yaxes:
            fixedrange: true
            rangemode: tozero
        layout:
          paper_bgcolor: rgba(0,0,0,0)
          plot_bgcolor: rgba(0,0,0,0)
          xaxis:
            tickmode: linear
            tick0: '1980-09-25T00:00:00.000Z'
            dtick: 3600000
```

**Reply by dbuezas** [reply]
I see. I don't see why or how the other cards would affect the plotly one, but I suggest you start with the plotly card alone and then add the other cards one by one to see at which point it stops being transparent.
Good luck!

**Reply by AleXSR700** [reply]
Removed all frontend components I installed via HACS (except apexcharts) and nothing changed.
Still not transparent.

**Reply by dbuezas** [reply]
I mean you to start remove all other cards from the dashboard (or start a new dashboard) and put the plotly card there alone

**Reply by AleXSR700** [reply]
Same :-(

Do you have a universal code example I should try?

E.g. with sun.sun or something that is on every HA install?

Or is there something I can check via the developer options in chrome?

**Reply by dbuezas** [reply]
This is so weird!
This is what I tested on:
```yaml
title: Experiment Dashboard
views:
  - title: plotly dev
    path: plotly-dev
    badges: []
    cards:
      - type: custom:plotly-graph
        entities:
          - entity: sun.sun
        title: transparent background
        layout:
          paper_bgcolor: rgba(255,0,0,0)
          plot_bgcolor: rgba(0,255,0,0)
      - type: custom:plotly-graph
        entities:
          - entity: sun.sun
        title: default backgrounds
```

And I get this: 
(changed background via devtools to show transparency)
![image](https://user-images.githubusercontent.com/777196/185056391-8f5690eb-4ba1-442c-afb6-1f2ac5227e77.png)
