### DISCUSSION TITLE
Plotly card is resizing after an edit

### DISCUSSION THREAD

**Discussion by bazcurtis** [dbuezas/lovelace-plotly-graph-card#480] [General]
I have made these very simple hot water tank graphs, but when I edit and save them, I see the below. What is going on here? I tried to give one of them a fixed axis but it still does it.

Out of interest, I also want to add an average line to cards. Can Plotly do averages?

```
type: custom:plotly-graph
entities:
  - entity: sensor.espaltherma_hot_water_tank_temperature
hours_to_show: 24
refresh_interval: 600
title: Water Tank
```

```
type: custom:plotly-graph
entities:
  - entity: sensor.espaltherma_hot_water_tank_temperature
    name: |
      $ex "Temperature" + " (" + parseFloat(ys.at(-1)) + ")c"
    showlegend: true
    line:
      width: 2
  - entity: sensor.espaltherma_hot_water_tank_temperature
    name: |
      $ex "Average" + " (" + parseFloat(ys.at(-1)) + ")c"
    showlegend: true
    line:
      width: 2
    filters:
      - filter: i <xs.length-1
    statistic: state
    period: week
hours_to_show: 4h
refresh_interval: 600
title: Hot Water Tank 4 hours (Direct)
min_y_axis: 20
max_y_axis: 60
```

![Hot Water Tank](https://github.com/user-attachments/assets/5fded133-2022-403a-b89d-7db08a0fc148)
