### DISCUSSION TITLE
Possible to get value from hover-text into legend?

### DISCUSSION THREAD

**Discussion by ando2040** [dbuezas/lovelace-plotly-graph-card#484] [Q&A] [answered]
All the similar questions seem to be related to formatting the hover-text not getting a value from it.

I've produced a curve I'm happy with using `calibrate_linear` from an imperfect tank sensor and some measured values. But I want to display in the legend the last computed value, which does appear in the hover-text... in this case 29.86 vs 25.0 - is there any way to do that, maybe a different variable than `ys` please? 

![Screenshot_20241117-231103](https://github.com/user-attachments/assets/70fe1f64-887f-4c36-aaa3-127b6ecbab89)

```
type: custom:plotly-graph
entities:
  - entity: sensor.temperature_sensor_temperature
    name: $ex 'Tank sensor ' + (ys.at(-1)/1).toFixed(1) + 'C'
    showlegend: true
  - entity: sensor.temperature_sensor_temperature
    name: $ex 'Tap measured ' + (ys.at(-1)/1).toFixed(1) + 'C'
    showlegend: true
    line:
      color: black
    filters:
      - calibrate_linear:
          - 50.6 -> 62.3
          - 25.7 -> 29.6
hours_to_show: 24
refresh_interval: 10
```
