### DISCUSSION TITLE
Battery Cell Voltage 3D Graph

### DISCUSSION THREAD

**Discussion by clowrey** [dbuezas/lovelace-plotly-graph-card#487] [Q&A] [answered]
I would like to graph these 108 sensors as parts of a 3D mesh if possible, here is the data as a normal graph:
![image](https://github.com/user-attachments/assets/43469890-4816-42ee-aa66-6fc90210187c)

Using this code:
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.bms_can_logger_cell_v_0
  - entity: sensor.bms_can_logger_cell_v_1
  - entity: sensor.bms_can_logger_cell_v_2
  - entity: sensor.bms_can_logger_cell_v_3
  - entity: sensor.bms_can_logger_cell_v_4
  - entity: sensor.bms_can_logger_cell_v_5
  - entity: sensor.bms_can_logger_cell_v_6
  - entity: sensor.bms_can_logger_cell_v_7
  - entity: sensor.bms_can_logger_cell_v_8
  - entity: sensor.bms_can_logger_cell_v_9
  - entity: sensor.bms_can_logger_cell_v_10
  - entity: sensor.bms_can_logger_cell_v_11
  - entity: sensor.bms_can_logger_cell_v_12
  etc..
  ```

The closest appearance wise is this example: https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/391

But my data source is very different in that each sensor would be one part of the graph. 

I already have a real time bar graph of the cells:
![image](https://github.com/user-attachments/assets/47bd1a41-43a8-4d6c-a58d-fc1d9b9e429d)

using this code:
```yaml
type: custom:plotly-graph
raw_plotly_config: true
title: Battery 0
fn: |-
  $ex {
    vars.x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
    vars.y = [1, 2, 3, 4, 5, 6, 7, 8];
    vars.z = [];
      

    for (let j = 0; j < 108; j++) {
      vars.z[j] = [];
      // Calculate the index in the 1D array corresponding to the 2D matrix element
      let index = j;

      // Populate the matrix with values from the 1D array
      vars.z[j][j] = hass.states["sensor.bms_can_logger_cell_v_" + (index).toString()].state
    }
    //console.log(vars.x);
    //console.log(vars.y);
    //console.log(vars.z);
    

    for (let j = 0; j < 108; j++) {
      // Calculate the index in the 1D array corresponding to the 2D matrix element
      let index = j;
      vars.x[index] = index;
      // Populate the matrix with values from the 1D array
      console.log(index);
      vars.y[index] = hass.states["sensor.bms_can_logger_cell_v_" + (index).toString()].state
    }

    
    vars.ymin = Math.min(...vars.y) - (50.0 / 1000);
    vars.ymax = Math.max(...vars.y) + (50.0 / 1000);
    console.log(vars.x);
    console.log(vars.y);
    
  }
entities:
  - entity: ""
    color: "#ff0000"
    type: bar
    x: $ex vars.x
    "y": $ex vars.y
    z: $ex vars.z
    texttemplate: "%{y}"
    refresh_interval: 2
layout:
  xaxis:
    showgrid: false
    zeroline: false
    showticklabels: false
    ticks: false
    nticks: 1
    visible: false
    height: 410
  yaxis:
    range:
      - $ex vars.ymin
      - $ex vars.ymax
config:
  displayModeBar: false
  scrollZoom: false
  ```

Any ideas on where to start?

**Comment by dbuezas** [comment, marked as answer]
That's a tricky one! Try with this:
<img width="343" alt="image" src="https://github.com/user-attachments/assets/4f0baede-5e08-4ca1-aca7-639dfb97dd48">(used some random sensors to test it)

```yaml
type: custom:plotly-graph
raw_plotly_config: true
hours_to_show: 1d

defaults:
  entity:
    internal: true
    filters: 
     - resample: 1m 
    fn: |
      $ex {
          vars.data.push(ys);
          vars.xs = xs;
       }

fn: $ex vars.data = []
layout:
  height: 400
  margin:
    t: 0 
    l: 0
    r: 90
    b: 0
  scene:
    camera: 
      eye: 
        x: 2
        y: 2
        z: 2
    xaxis:
      title: Hour of Day 
      tickformat: '%H:%M:%S'
    yaxis:
      title: BMS
      tickmode: 'linear'
      dtick: 1
    zaxis:
      title: V

entities: 
  - entity: sensor.bms_can_logger_cell_v_0
  - entity: sensor.bms_can_logger_cell_v_1
  - entity: sensor.bms_can_logger_cell_v_2
  - entity: sensor.bms_can_logger_cell_v_3
  - entity: sensor.bms_can_logger_cell_v_4
  - entity: sensor.bms_can_logger_cell_v_5
  - entity: sensor.bms_can_logger_cell_v_6
  - entity: sensor.bms_can_logger_cell_v_7
  - entity: sensor.bms_can_logger_cell_v_8
  - entity: sensor.bms_can_logger_cell_v_9
  - entity: sensor.bms_can_logger_cell_v_10
  - entity: sensor.bms_can_logger_cell_v_11
  - entity: sensor.bms_can_logger_cell_v_12  
  
  - entity: ''
    internal: false
    type: surface
    x: $ex vars.xs
    y: $ex vars.data.map((_,i)=>i)
    z: $ex vars.data
```

**Reply by clowrey** [reply]
WOW! that is amazing! thanks so much! works perfectly
![image](https://github.com/user-attachments/assets/23c2839c-6aa0-45b1-853b-b601acaffe29)

**Reply by dbuezas** [reply]
Great, those cells look well balanced!

**Reply by clowrey** [reply]
They are fairly balanced - but this data is not at top end charge state - the divergence all occurs when they get above 3.4V where one can be at 3.6V fully charged, and most of the others are still at 3.38V.. I am working on seeing if it will balance itself over time when at higher levels. To use it off grid like this the tesla pack is in "Drive" mode and does not think it is charging so we don't know how well the balance circuit performs if at all like this. 

I expect the graph to get more interesting once I have a days worth of full sun data to show it reach that level :)

**Reply by dbuezas** [reply]
great!
You could sort them by starting voltage to better evaluate how the balancer is doing its job
```yaml
    x: $ex vars.xs
    y: $ex vars.data.map((_,i)=>i)
    z: $ex vars.data.sort((a,b) => a[0] - b[0])
```

just note that the bms number in the y axis won't be the real cell number
