### DISCUSSION TITLE
How to lock Yaxis range for two sensors using different units?

### DISCUSSION THREAD

**Discussion by smartroad** [dbuezas/lovelace-plotly-graph-card#490] [Q&A] [answered]
Hi All :)

I have two sensors I am plotting for my car. One is the battery level in % and the other is charge rate in kW. How do I tell the graph to lock the Y axis for the battery level to 0-100 and the charge rate as 0-80? I have tried with the layout but it only seems to affect the first sensor. If I move the layout into the individual entity nothing happens.

```
type: custom:plotly-graph
layout:
  xaxis:
    rangeselector:
      "y": 1.2
      buttons:
        - count: 1
          step: day
        - count: 3
          step: day
        - count: 7
          step: day
        - count: 14
          step: day
        - count: 1
          step: month
  yaxis:
      range:
        - 0
        - 100
entities:
  - entity: sensor.niro_ev_battery_level
    line:
      color: cyan
  - entity: sensor.niro_ev_charging_power
    fill: tozeroy
    line:
      color: red
      dash: dot
      width: 1
hours_to_show: 72
refresh_interval: 10
```
![image](https://github.com/user-attachments/assets/38bd4b49-5b87-4a70-ae56-5ccb10ba4cb1)

**Comment by dbuezas** [comment, marked as answer]
Hi there!
```yaml
layout:
  yaxis:
    range: [0, 100]
  yaxis2:
    range: [0, 80]
```

more here: https://plotly.com/javascript/axes/#setting-the-range-of-axes-manually

**Reply by smartroad** [reply]
Perfect thank you! There is so much to configure I missed that! 😄

**Reply by dbuezas** [reply]
Infinitely much!

**Reply by Cmbeek** [reply]
Looks great! I'm relatively new here. How did you get the charging rate to use the second y-axis? 
Do they have to be with a different unit? I tried with two temperature sensors, but I cannot get them to be displayed on a different y-scale.....

**Reply by CzarDestructo** [reply]
Little late @Cmbeek but here is what I came up with for my wood stove monitor

<img width="1276" height="318" alt="image" src="https://github.com/user-attachments/assets/ae7ea937-4119-44c2-a4cf-70b7cde41c42" />

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.smoky_flue_temperature
    zorder: 0 #set the order in which the lines are plotted
    line:
      color: red
  - entity: sensor.smoky_stovetop_temperature
    zorder: 1 #set the order in which the lines are plotted
    line:
      color: darkgreen
  - entity: sensor.smoky_ambient_temperature
    yaxis: y2 #set which axis to use, default is y1
    zorder: 1 #set the order in which the lines are plotted
    line:
      color: purple
defaults:
  entity:
    fill: tozeroy
    line:
      width: 1
      shape: spline
    filters:
      - exponential_moving_average: null
        alpha: 0.1
hours_to_show: 1
refresh_interval: 10
title: Wood Stove Temperatures
config:
  scrollZoom: false
layout:
  yaxis:
    fixedrange: true
    title: Flue and Stovetop Temp
  yaxis2:
    range:
      - 10
      - 35
    title: Ambient Temp
  xaxis:
    fixedrange: true
    rangeselector:
      "y": 1.2
      buttons:
        - count: 15
          step: minute
        - count: 1
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 7
          step: day
```
