### DISCUSSION TITLE
Y axis auto range/zoom but no scroll.

### DISCUSSION THREAD

**Discussion by deltamelter** [dbuezas/lovelace-plotly-graph-card#492] [Q&A]
I might be missing something obvious, but can't find a combination that allows me to fixrange in the yaxis but still allow zooming.
I thought maybe autorange_after_scroll might do it, but seems not. Any Ideas?

eg, I want to zoom into the lows and negative values on the left:
![image](https://github.com/user-attachments/assets/85dc3ce1-0005-4b2b-a6ee-4173172680f7)

The bars stay same height and the zoomed bars in focus are still unreadable:
![image](https://github.com/user-attachments/assets/e361e2a7-09ea-4618-8255-79c681332af3)

leaving out `fixedrange` auto ranges correctly, but it's all too easily to "get lost" in the  depth of the empty yaxis...

**Comment by dbuezas** [comment]
Try with:
```yaml
layout:
  yaxis:
    autorangeoptions:    
      minallowed: 5
      maxallowed: 20
```
