### DISCUSSION TITLE
Any docs/guidance on polar bars? 🐻‍❄️💈

### DISCUSSION THREAD

**Discussion by deltamelter** [dbuezas/lovelace-plotly-graph-card#493] [Q&A] [answered]
Plotly docs show a wind rose chart and sketchy details on how to use it, but I can't get barpolar to stack like this example:
![image](https://github.com/user-attachments/assets/e5911ff4-2c43-4b8f-8de0-ef2506738417)

closest I got is:
![newplot (26)](https://github.com/user-attachments/assets/c6ca0c98-ced3-4457-88a9-91bfb86e4b7b)

what does `theta` and `an` do?  I see those in the examples for this card, but is different to plotly.js description.

**Comment by dbuezas** [comment]
Post your yaml please

**Reply by deltamelter** [reply]
ripped straight from examples with some trial and error poking about from me...
```
type: custom:plotly-graph
title: Still Energy
refresh_interval: 1
hours_to_show: current_day
layout:
  height: 350
  margin:
    l: 50
    r: 50
    t: 50
    b: 50
  showlegend: true
  legend:
    x: 0.3
    "y": -0.3
  xaxis:
    dtick: 1
    type: number
    fixedrange: true
    range:
      - 0
      - 8
  yaxis:
    dtick: 10
    fixedrange: true
    range:
      - 0
      - 100
entities:
  - entity: ""
    name: Threshold
    type: barpolar
    #line:
     # shape: spline
      #width: 2
      #color: FB239F
    #theta: [220,90,0,0,0,0,0,0]
    r:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    marker:
      offset: 1234567890
      color: ['#0d0887', '#46039f', '#7201a8', '#9c179e', '#bd3786', '#d8576b', '#ed7953', '#fb9f3a', '#fdca26', '#f0f921']
      opacity: 0.5
      width:
        - $ex hass.states["sensor.mo2410c_g0_still_energy"].state
        - $ex hass.states["sensor.mo2410c_g1_still_energy"].state
        - $ex hass.states["sensor.mo2410c_g2_still_energy"].state
        - $ex hass.states["sensor.mo2410c_g3_still_energy"].state
        - $ex hass.states["sensor.mo2410c_g4_still_energy"].state
        - $ex hass.states["sensor.mo2410c_g5_still_energy"].state
        - $ex hass.states["sensor.mo2410c_g6_still_energy"].state
        - $ex hass.states["sensor.mo2410c_g7_still_energy"].state
        - $ex hass.states["sensor.mo2410c_g8_still_energy"].state
    radialaxis:
      - 90
    angularaxis:
      - 90
    x:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    "y":
      - $ex hass.states["sensor.mo2410c_g0_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g1_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g2_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g3_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g4_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g5_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g6_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g7_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g8_still_energy"].state
  - entity: ""
    name: Energy
    mode: lines
    line:
      shape: spline
      width: 2
      color: blue
    x:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    "y":
      - $ex hass.states["sensor.mo2410c_g0_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g1_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g2_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g3_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g4_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g5_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g6_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g7_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g8_still_energy"].state
raw_plotly_config: t
```

**Reply by dbuezas** [reply]
Ok, polar plots don't work with x and y coordinates but instead with angle and distance from center, usually called theta and radial span or alpha and magnitude, etc.

Properties like an or fn don't exist, they were most likely used just to put a $fn or $ex that stores something in a var: whatever they may have returned is ignored.

In your case you have 8 sensors, so make theta be an array with 8 elements with values starting with 0 (degrees) and going up by one eight of a full rotation (360/8). I.e:
```yaml
theta:
  - 0
  - 45
  - 90
  - 135
  - 180
  - 225
  - 270
  - 315
```

Then put your sensors values inside r (not y)
```yaml
r:
      - $ex hass.states["sensor.mo2410c_g0_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g1_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g2_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g3_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g4_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g5_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g6_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g7_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g8_still_energy"].state
```

Then you should start getting something recognizable being plotted

**Reply by deltamelter** [reply]
I'm am probably not using this as intended, but that was intentional 😛 
I was trying to stack or overlay the 8 fixed distances in the same direction but with width representing the strength of the value for each distance.
This is more like I had in mind, but, all in the same direction.
![newplot (28)](https://github.com/user-attachments/assets/9b9305fd-d139-46da-a3ac-489d35f6f1a1)

```
    theta:
      - 0
      - 45
      - 90
      - 135
      - 180
      - 225
      - 270
      - 315
    r: [1,2,3,4,5,6,7,8]
    width:
      - $ex hass.states["sensor.mo2410c_g0_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g1_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g2_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g3_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g4_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g5_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g6_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g7_still_energy"].state
      - $ex hass.states["sensor.mo2410c_g8_still_energy"].state

    marker:
      offset: 0
      color: ['#0d0887', '#46039f', '#7201a8', '#9c179e', '#bd3786', '#d8576b', '#ed7953', '#fb9f3a', '#fdca26', '#f0f921']
      opacity: 0.5
```

Actually, like this, but not sure I like it 😁 
![newplot (29)](https://github.com/user-attachments/assets/5161d8ee-682f-47b3-a64f-e4d70f45f728)
```
    theta:
      - 90
      - 90
      - 90
      - 90
      - 90
      - 90
      - 90
      - 90
```
