### DISCUSSION TITLE
Removing Outliers In Graph

### DISCUSSION THREAD

**Discussion by wormuths** [dbuezas/lovelace-plotly-graph-card#495] [Q&A] [answered]
Hi there...

I have the following card.

![Screenshot_20241129_205145](https://github.com/user-attachments/assets/fc195208-9971-48f4-a15c-a4eef71338ed)

```
type: custom:plotly-graph
title: Cellular Internet Activity
hours_to_show: 1d
autorange_after_scroll: true
refresh_interval: auto
defaults:
  entity:
    filters:
      - force_numeric
layout:
  height: 250
  dragmode: pan
  showlegend: true
  xaxis:
    rangeselector:
      "y": 1.2
      buttons:
        - count: 1
          step: day
          label: Day
        - count: 7
          step: day
          label: Week
        - count: 28
          step: day
          label: Month
      bgcolor: rgb(5, 160, 226)
      activecolor: rgb(255, 152, 0)
      bordercolor: black
      font:
        color: rgb(10, 55, 58)
entities:
  - entity: sensor.opnsense_firewall_exodus_interface_wan_inbytes_kilobytes_per_second
    name: Average Received
    line:
      color: rgb(5, 160, 226)
      width: 1
    fill: tozeroy
    fillcolor: rgba(5, 160, 226, 0.25)
    show_value: true
  - entity: >-
      sensor.opnsense_firewall_exodus_interface_wan_outbytes_kilobytes_per_second
    name: Average Transmitted
    line:
      color: rgb(255, 152, 0)
      dash: dashdot
      width: 2
    show_value: true
```

I have no idea how to do this, so if someone knows, I'd appreciate the help.

Is there a way to use a filter to strip the highest 1% of the values in the graph?  The goal is to strip out those periodic speed tests which spike on the graph.  They make the rest visually unusable.

And when I say I have no idea, I'm saying it would be quicker to modify that chart for me than try to explain it.  LOL.  Honesty is the best policy.  I'm thinking it's a filter...  Maybe there is a better way?

Thanks everyone!
