### DISCUSSION TITLE
The entity will plot a line, but not bar graph

### DISCUSSION THREAD

**Discussion by bazcurtis** [dbuezas/lovelace-plotly-graph-card#497] [General]
I am a bit confused.

If I use this YAML I get the below

```
type: custom:plotly-graph
entities:
  - entity: sensor.lux_solar_output_daily
    filters:
     - filter: i >0
hours_to_show: 24
refresh_interval: 10
title: Daily Solar Generation and Export
```

<img width="477" alt="Screenshot 2024-12-04 at 16 59 13" src="https://github.com/user-attachments/assets/73cc6f6f-1b0f-472a-989e-a6de27caf045">

If I use this YAML I get nothing

```
type: custom:plotly-graph
entities:
  - entity: sensor.lux_solar_output_daily
    filters:
     - filter: i >0
    statistic: state
    period: day
    type: bar
hours_to_show: 24
refresh_interval: 10
title: Daily Solar Generation and Export
```
<img width="475" alt="Screenshot 2024-12-04 at 16 59 23" src="https://github.com/user-attachments/assets/bd0292fd-4d0e-4d18-aa5f-51f27cb66f02">

What am I missing?
