### DISCUSSION TITLE
Need help for "Now line"

### DISCUSSION THREAD

**Discussion by thoath2** [dbuezas/lovelace-plotly-graph-card#501] [Q&A] [answered]
Hello,
I built a grid-graph for temperature and humidity with two rows. It works fine
```
type: custom:plotly-graph
hours_to_show: 24
time_offset: |-
  $fn ({ getFromConfig }) => {
    const ms_to_show = getFromConfig('hours_to_show') * 60 * 60 * 1000;
    const now_utc = Date.now() - new Date().getTimezoneOffset() * 60 * 1000;
    return ms_to_show - now_utc % ms_to_show + 'ms'
  }  
entities:
  - entity: sensor.co2_temp_hum_eg_temperature
    yaxis: y1
  - entity: sensor.co2_temp_hum_dg_temperature
    yaxis: y1
  - entity: sensor.co2_temp_hum_eg_humidity
    yaxis: y2
  - entity: sensor.co2_temp_hum_dg_humidity
    yaxis: y2
layout:
  dragmode: pan
  margin:
    t: 30
    l: 45
    r: 40
    b: 50
  showlegend: false
  height: 650
  grid:
    rows: 2
    columns: 1
    roworder: top to bottom
  annotations: null
  yaxis:
    title:
      text: Temperatur
  yaxis2:
    title:
      text: Luftfeuchte
defaults:
  entity:
    show_value: true
  yaxes:
    fixedrange: false
    autorange: true
    side: left
    overlaying: "y"
    visible: true
    showgrid: true
title: Grid
refresh_interval: 10
color_scheme: 2
```
<img width="366" alt="Temp-Hum" src="https://github.com/user-attachments/assets/b39a3532-dbda-4861-8b00-ecbdfd95c99d">
 
Now i would like to add a now line like https://github.com/dbuezas/lovelace-plotly-graph-card?tab=readme-ov-file#now-line .
```
- entity: ""
    name: aktueller Zeitpunkt
    yaxis: y9
    stackgroup: null
    showlegend: true
    line:
      width: 1
      dash: dot
      color: LightSkyBlue
    x: $ex [Date.now(), Date.now()]
    "y":
      - 0
      - 1
 ```
Unfortunately it doesn't works.
What i have to change, that it works? I'am not sure, how i use the yaxis: y9

**Comment by dbuezas** [comment, marked as answer]
Try with shapes instead 

```yaml
type: custom:plotly-graph
hours_to_show: current_day
entities:
  - entity: sensor.co2_temp_hum_eg_temperature
    yaxis: y1
  - entity: sensor.co2_temp_hum_dg_temperature
    yaxis: y1
  - entity: sensor.co2_temp_hum_eg_humidity
    yaxis: y2
  - entity: sensor.co2_temp_hum_dg_humidity
    yaxis: y2
layout:
  dragmode: pan
  margin:
    t: 30
    l: 45
    r: 40
    b: 50
  showlegend: false
  height: 650
  grid:
    rows: 2
    columns: 1
    roworder: top to bottom
  annotations: null
  yaxis:
    title:
      text: Temperatur
  yaxis2:
    title:
      text: Luftfeuchte
  shapes:
    - type: line
      x0: $ex Date.now()
      x1: $ex Date.now()
      y0: 0
      y1: 1
      xref: x
      yref: paper
      line:
        color: "red"
        width: 2
defaults:
  entity:
    show_value: true
  yaxes:
    fixedrange: false
    autorange: true
    side: left
    overlaying: "y"
    visible: true
    showgrid: true
title: Grid
refresh_interval: 10
color_scheme: 2
```
