### DISCUSSION TITLE
Any ideas how to change the position of the hover label, especially "hovermode: x unified" so that is doesn't cover over the chart you are interested in?

### DISCUSSION THREAD

**Discussion by deltamelter** [dbuezas/lovelace-plotly-graph-card#502] [Q&A]
Really like the all-in-one "x unified" hover label but it would be cool to be able also see the actual chart that the hover label relates to.
![image](https://github.com/user-attachments/assets/66ae4ab7-95eb-441c-bee3-15d2cde80047)
Any ideas how to move this further away or even to a specific fixed position at the side?

Tried a few settings found in the plotly.js docs, but not sure if the are not implemented or using them incorrectly...

```
type: custom:plotly-graph
layout:
  height: 600
  hovermode: x unified
  hoverlabel:
    align: left
    x0: 1
  hoverdistance: 100
  spikedistance: 10
entities:
...
```
