### DISCUSSION TITLE
I think this is a bug

### DISCUSSION THREAD

**Discussion by funkoid** [dbuezas/lovelace-plotly-graph-card#503] [Q&A]
Here are 2 screenshots taken about 20min apart. The first illustrates the green shaded area (Heating on) correctly and the second shows the opposite with the Idle state as shaded green. At the bottom is the HVAC Heating state.
![ploty](https://github.com/user-attachments/assets/c4955c85-fcff-4228-9aa7-f3d3c4249da6) ![ploty2](https://github.com/user-attachments/assets/b37881db-a2d2-47d5-a9c6-48a558b3a986)

The yaml hasn't changed between the 2 snapshots. I can post if necessary. Has anyone seen this before and knows how to solve it?

For those interested what I'm showing there are 3 sensors; 2 that measure the rate of temperature change at the `thermostat `and the `ground floor` and the third is the `HVAC Heating state`. The `HVAC Heating state` sensor only reports if it is `heating `or `idle`, if the fan is running it reports it as `idle`. 

If I've posted this in the incorrect forum please let me know.

**Comment by dbuezas** [comment]
Can you post the yaml?
I don't know how fill: tozeroy works with categorical (non numerical) axes.

**Comment by funkoid** [comment]
Here is the yaml.

```
type: custom:plotly-graph
entities:
  - entity: sensor.thermostat_temp_change_rate
    name: thermostat
    yaxis: y1
  - entity: sensor.home_temp_change_rate
    name: ground floor
    yaxis: y1
  - entity: sensor.hvac_heating_state
    name: Heat
    fill: tozeroy
    yaxis: y2
    ys:
      - idle
      - heating
    filters:
      - map_y_numbers: "state === 'heating' ? 1 : 0"
hours_to_show: 4
refresh_interval: 120
layout:
  yaxis:
    title: Temperature Change Rate
    zeroline: true
    zerolinecolor: white
    zerolinewidth: 2
  yaxis2:
    title: HVAC State
    overlaying: "y"
    side: right
    range:
      - -0.5
      - 1.5
    tickvals:
      - 0
      - 1
    ticktext:
      - idle
      - heating
    zeroline: true
    zerolinewidth: 2
    zerolinecolor: rgba(68, 68, 68, 0.7)
```
