### DISCUSSION TITLE
Stackgroup with variable positive and negative values - needs entities split, and defaults in every entity?

### DISCUSSION THREAD

**Discussion by ando2040** [dbuezas/lovelace-plotly-graph-card#505] [Q&A]
![image](https://github.com/user-attachments/assets/30123e8d-2a12-490c-a606-4b23e1a2e961)

Problem: Series bleed into each other because `fill: tonexty` default for stackgroups uses the upper extent of the previous series as y=0, so when a series swaps to negative, it fills over the previous one. 

When I tried a workaround documented elsewhere, to filter positive/negative value series into separate stackgroups, the stackgroups didn't work - despite resample in the entity defaults.

![image](https://github.com/user-attachments/assets/069761bf-2985-4366-aca4-0c66a9d33ae6)

The solution was to move all the filter defaults into every entity - a filter is not additive, it replaces all default filters even though the new filter is not one previously specified in the defaults. This causes a lot of duplication. Does this need explicitly adding to "gotchas?"  It got me for a long time but maybe I'm dense... or could/should it be fixed? Personal preference I suspect? 

![image](https://github.com/user-attachments/assets/aec7ccaf-ea49-422c-a174-d33b22cc10ee)

Note that I have exploited a previous gotcha I added to the readme - in this case I want to display value of `ys` in a single legend whatever its value, and hide the negative legend, so I added `name:` before the filter, not after. 

One remaining niggle: blue series shows a continuous line at y<0 even when y is positive, and red shows a continuous line at y>0 when y is negative. Ideas welcome. Am I even achieving this in the best/only way?
```
type: custom:plotly-graph
title: 7-day Import/Export history
layout:
  height: 350
entities:
  - entity: sensor.national_grid_grid_generation_ireland_mw
    name: |
      $ex 'Ireland(now) ' + (ys.at(-1)/1000).toFixed(2) + 'GW'
    filters:
      - filter: y > 0
      - resample: 1m
      - multiply: 0.001
    fillcolor: seagreen
    stackgroup: positive
  - entity: sensor.national_grid_grid_generation_ireland_mw
    filters:
      - filter: y < 0
      - resample: 1m
      - multiply: 0.001
    fillcolor: seagreen
    stackgroup: negative
    name: Ireland -
    showlegend: false
  - entity: sensor.national_grid_grid_generation_denmark_mw
    name: |
      $ex 'Denmark(now) ' + (ys.at(-1)/1000).toFixed(2) + 'GW'
    filters:
      - filter: y > 0
      - resample: 1m
      - multiply: 0.001
    fillcolor: red
    stackgroup: positive
  - entity: sensor.national_grid_grid_generation_denmark_mw
    filters:
      - filter: y < 0
      - resample: 1m
      - multiply: 0.001
    fillcolor: red
    stackgroup: negative
    name: Denmark -
    showlegend: false
  - entity: sensor.national_grid_grid_generation_france_mw
    name: |
      $ex 'France(now) ' + (ys.at(-1)/1000).toFixed(2) + 'GW'
    filters:
      - filter: y > 0
      - resample: 1m
      - multiply: 0.001
    fillcolor: blue
    stackgroup: positive
  - entity: sensor.national_grid_grid_generation_france_mw
    filters:
      - filter: y < 0
      - resample: 1m
      - multiply: 0.001
    fillcolor: blue
    stackgroup: negative
    name: France -
    showlegend: false
  - entity: sensor.national_grid_grid_generation_belgium_mw
    name: |
      $ex 'Belgium(now) ' + (ys.at(-1)/1000).toFixed(2) + 'GW'      
    filters:
      - filter: y > 0
      - resample: 1m
      - multiply: 0.001
    fillcolor: black
    stackgroup: positive
  - entity: sensor.national_grid_grid_generation_belgium_mw
    filters:
      - filter: y < 0
      - resample: 1m
      - multiply: 0.001
    fillcolor: black
    stackgroup: negative
    name: Belgium -
    showlegend: false
  - entity: sensor.national_grid_grid_generation_netherlands_mw
    name: |
      $ex 'Nlands(now) ' + (ys.at(-1)/1000).toFixed(2) + 'GW'
    filters:
      - filter: y > 0
      - resample: 1m
      - multiply: 0.001
    fillcolor: orange
    stackgroup: positive
  - entity: sensor.national_grid_grid_generation_netherlands_mw
    filters:
      - filter: y < 0
      - resample: 1m
    fillcolor: orange
    stackgroup: negative
    name: Nlands -
    showlegend: false
  - entity: sensor.national_grid_grid_generation_norway_mw
    name: |
      $ex 'Norway(now) ' + (ys.at(-1)/1000).toFixed(2) + 'GW'
    filters:
      - filter: y > 0
      - resample: 1m
      - multiply: 0.001
    fillcolor: darkred
    stackgroup: positive
  - entity: sensor.national_grid_grid_generation_norway_mw
    filters:
      - filter: y < 0
      - resample: 1m
      - multiply: 0.001
    fillcolor: darkred
    stackgroup: negative
    name: Norway -
    showlegend: false
defaults:
  entity:
    unit_of_measurement: GW
    line:
      width: 0
  yaxes:
    fixedrange: true
hours_to_show: 250
refresh_interval: 10
```
