### DISCUSSION TITLE
3row x 1column graph used to work fine, all of a sudden the 3rd group of datasets takes the whole screen and 2 other groups  are not plotted anymore

### DISCUSSION THREAD

**Discussion by netweaver1970** [dbuezas/lovelace-plotly-graph-card#508] [Q&A] [answered]
hi,
I was having this graph already for 'years', never touched it anymore after initial crafting (@dbuezas thanks for the help back then) but recently (2-3 weeks ago, maybe the HA Core upgrade?) the graph stopped showing the top 2 groups of datasets (the Temp & Rel Humidity).
And it now only shows the bottom graph (the calculated Abs Humidity), now spanning all the 3 rows. 

I never touched the YAML ... so there must have been some other changes in the environment causing this behaviour, maybe in combination with some already lurking issue/problem in my YAML code.

Below is the 'bad' result, of the good screen I have no picture anymore. But I guess you can imagine how it looks like
<img width="708" alt="image" src="https://github.com/user-attachments/assets/72a9c72a-9e62-4daa-99a1-53e8d198e3cc" />

Below the YAML.

Anybody an idea what I needs to change to get my old situation back?

Thanks
```
type: custom:plotly-graph
entities:
  - entity: sensor.th_livingroom_temperature
    statistic: mean
    legendgroup: 1
    name: Livingroom
    yaxes: y1
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_livingroom
    line:
      color: red
      shape: spline
  - entity: sensor.th_kitchen_temperature
    statistic: min
    legendgroup: 2
    name: Kitchen
    yaxes: y1
    line:
      color: orange
      shape: spline
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_kitchen
  - entity: sensor.th_garage_temperature
    statistic: mean
    legendgroup: 3
    name: Garage
    yaxes: y1
    line:
      color: green
      shape: spline
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_garage
  - entity: sensor.buienradar_temperature
    statistic: mean
    legendgroup: 4
    visible: legendonly
    name: Outside
    yaxes: y2
    line:
      color: gray
      shape: spline
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_buiten
  - entity: sensor.th_office2_temperature
    statistic: mean
    legendgroup: 5
    name: Office
    yaxes: y1
    line:
      color: blue
      dash: dot
      shape: spline
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_office
  - entity: sensor.th_guest_temperature
    statistic: mean
    legendgroup: 6
    name: Guest
    yaxes: y1
    line:
      dash: dot
      shape: spline
      colour: red
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_guest
  - entity: sensor.th_master_br_temperature
    statistic: mean
    legendgroup: 7
    name: Master
    yaxes: y1
    line:
      dash: dot
      shape: spline
      color: orange
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_master
  - entity: sensor.th_alastair_temperature
    statistic: mean
    legendgroup: 8
    name: Alastair
    yaxes: y1
    line:
      color: gray
      dash: dot
      shape: spline
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_alastair
  - entity: sensor.th_bathroom_temperature
    statistic: mean
    legendgroup: 9
    name: Bathroom
    yaxes: y1
    line:
      color: yellow
      dash: dot
      shape: spline
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_bathroom
  - entity: sensor.livingroom_migo_set_temperature
    statistic: mean
    legendgroup: 10
    visible: legendonly
    name: Migo curr
    yaxes: y1
    line:
      color: yellow
      shape: spline
  - entity: sensor.livingroom_migo_current_temperature
    statistic: mean
    legendgroup: 10
    visible: legendonly
    name: Migo set
    yaxes: y1
    line:
      color: yellow
      shape: spline
  - entity: sensor.th_livingroom_humidity
    statistic: mean
    legendgroup: 1
    name: Livingroom
    yaxes: y2
    showlegend: false
    line:
      color: red
      shape: spline
  - entity: sensor.th_kitchen_humidity
    statistic: min
    legendgroup: 2
    showlegend: false
    name: Kitchen
    yaxes: y2
    line:
      color: orange
      shape: spline
  - entity: sensor.buienradar_humidity
    statistic: mean
    legendgroup: 4
    visible: legendonly
    showlegend: false
    name: Kitchen
    yaxes: y2
    line:
      color: gray
      shape: spline
  - entity: sensor.th_garage_humidity
    statistic: mean
    legendgroup: 3
    visible: legendonly
    showlegend: false
    name: Garage
    yaxes: y2
    line:
      color: green
      shape: spline
  - entity: sensor.th_office2_humidity
    statistic: mean
    legendgroup: 5
    showlegend: false
    name: Office
    yaxes: y2
    line:
      color: blue
      dash: dot
      shape: spline
  - entity: sensor.th_guest_humidity
    statistic: mean
    legendgroup: 6
    showlegend: false
    name: Guest
    yaxes: y2
    line:
      dash: dot
      shape: spline
      color: red
  - entity: sensor.th_master_br_humidity
    statistic: mean
    legendgroup: 7
    showlegend: false
    name: Master
    yaxes: y2
    line:
      dash: dot
      shape: spline
      color: orange
  - entity: sensor.th_alastair_humidity
    statistic: mean
    legendgroup: 8
    showlegend: false
    name: Alastair
    yaxes: y2
    line:
      color: gray
      dash: dot
      shape: spline
  - entity: sensor.th_bathroom_humidity
    statistic: mean
    legendgroup: 9
    showlegend: false
    name: Bathroom
    yaxes: y2
    line:
      color: yellow
      dash: dot
      shape: spline
  - entity: sensor.th_livingroom_humidity
    showlegend: false
    statistic: mean
    legendgroup: 1
    name: Livingroom
    yaxes: y3
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_livingroom.ys[i])/(vars.temperature_livingroom.ys[i]+243.5))
          * y + vars.temperature_livingroom.ys[i] *
          2.1674)/(273.15+vars.temperature_livingroom.ys[i]);
    line:
      color: red
      shape: spline
  - entity: sensor.th_kitchen_humidity
    showlegend: false
    statistic: mean
    legendgroup: 2
    name: Kitchen
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_kitchen.ys[i])/(vars.temperature_kitchen.ys[i]+243.5))
          * y+ vars.temperature_kitchen.ys[i] *
          2.1674)/(273.15+vars.temperature_kitchen.ys[i]);
    yaxes: y3
    line:
      color: orange
      shape: spline
  - entity: sensor.th_garage_humidity
    showlegend: false
    statistic: mean
    legendgroup: 3
    name: Garage
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_garage.ys[i])/(vars.temperature_garage.ys[i]+243.5))
          *y + vars.temperature_garage.ys[i] *
          2.1674)/(273.15+vars.temperature_garage.ys[i]);
    yaxes: y3
    line:
      color: green
      shape: spline
  - entity: sensor.th_bathroom_humidity
    showlegend: false
    statistic: mean
    legendgroup: 9
    name: Bathroom
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_bathroom.ys[i])/(vars.temperature_bathroom.ys[i]+243.5))
          *y + vars.temperature_bathroom.ys[i] *
          2.1674)/(273.15+vars.temperature_bathroom.ys[i]);
    yaxes: y3
    line:
      color: yellow
      shape: spline
      dash: dot
  - entity: sensor.th_alastair_humidity
    showlegend: false
    statistic: mean
    legendgroup: 8
    name: Bathroom
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_alastair.ys[i])/(vars.temperature_alastair.ys[i]+243.5))
          *y + vars.temperature_alastair.ys[i] *
          2.1674)/(273.15+vars.temperature_alastair.ys[i]);
    yaxes: y3
    line:
      color: gray
      shape: spline
      dash: dot
  - entity: sensor.th_guest_humidity
    showlegend: false
    statistic: mean
    legendgroup: 6
    name: Guestroom AH
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_guest.ys[i])/(vars.temperature_guest.ys[i]+243.5)) *
          y + vars.temperature_guest.ys[i] *
          2.1674)/(273.15+vars.temperature_guest.ys[i]);
    yaxes: y3
    line:
      color: red
      shape: spline
      dash: dot
  - entity: sensor.th_office2_humidity
    showlegend: false
    statistic: mean
    legendgroup: 5
    name: Office AH
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_office.ys[i])/(vars.temperature_office.ys[i]+243.5))
          *y + vars.temperature_office.ys[i] *
          2.1674)/(273.15+vars.temperature_office.ys[i]);
    yaxes: y3
    line:
      color: blue
      shape: spline
      dash: dot
  - entity: sensor.th_master_br_humidity
    showlegend: false
    statistic: mean
    legendgroup: 7
    name: Guestroom AH
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_master.ys[i])/(vars.temperature_master.ys[i]+243.5))
          *y + vars.temperature_master.ys[i] *
          2.1674)/(273.15+vars.temperature_master.ys[i]);
    yaxes: y3
    line:
      color: orange
      shape: spline
      dash: dot
  - entity: sensor.buienradar_humidity
    showlegend: false
    visible: legendonly
    statistic: mean
    legendgroup: 4
    name: buiten AH
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_buiten.ys[i])/(vars.temperature_buiten.ys[i]+243.5))
          *y + vars.temperature_buiten.ys[i] *
          2.1674)/(273.15+vars.temperature_buiten.ys[i]);
    yaxes: y3
    line:
      color: gray
      shape: spline
hours_to_show: 24
autorange_after_scroll: true
layout:
  dragmode: pan
  margin:
    t: 30
    l: 50
    r: 30
    b: 50
  showlegend: true
  height: 800
  legend:
    x: 0
    "y": 1.02
    bgcolor: rgba(0,0,0,.4)
    orientation: h
    itemsizing: fixed
    font:
      size: 10
  grid:
    rows: 3
    columns: 1
    roworder: top to bottom
  yaxis:
    side: left
    overlaying: "y"
    visible: true
    showgrid: true
    title:
      text: Temperature
  yaxis2:
    side: left
    overlaying: "y"
    visible: true
    showgrid: true
    title:
      text: Humidity
  yaxis3:
    side: left
    overlaying: "y"
    visible: true
    showgrid: true
    title:
      text: Abs. Humidity
  plot_bgcolor: black
  y1:
    gridcolor: whitesmoke
    zeroline: false
    fixedrange: true
  xaxis:
    rangeselector:
      "y": 1
      buttons:
        - count: 3
          step: day
        - count: 7
          step: day
        - count: 14
          step: day
        - count: 1
          step: month
        - count: 3
          step: month
        - count: 12
          step: month
        - count: 36
          step: month
defaults:
  entity:
    line: null
    period:
      24h: 5minute
      3d: 5minute
      7d: hour
      14d: hour
      1M: day
      3M: day
      12M: week
      36M: month
  width: 1
title: Climate

```

**Comment by netweaver1970** [comment]
seems I got a bit further, the "overlaying" option seems related, I got better a state but not really:
<img width="924" alt="image" src="https://github.com/user-attachments/assets/4a8de42d-f3c7-4d0c-a9d0-f4c205c317d7" />

I can't get the 2nd group(Rel. Hum.) into the 2nd row, it stays in the 1st row (together with the Temp). 
I obviously don't understand it yet...
```
type: custom:plotly-graph
entities:
  - entity: sensor.th_livingroom_temperature
    statistic: mean
    legendgroup: 1
    name: Livingroom
    yaxes: y1
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_livingroom
    line:
      color: red
      shape: spline
  - entity: sensor.th_kitchen_temperature
    statistic: min
    legendgroup: 2
    name: Kitchen
    yaxes: y1
    line:
      color: orange
      shape: spline
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_kitchen
  - entity: sensor.th_garage_temperature
    statistic: mean
    legendgroup: 3
    name: Garage
    yaxes: y1
    line:
      color: green
      shape: spline
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_garage
  - entity: sensor.buienradar_temperature
    statistic: mean
    legendgroup: 4
    visible: legendonly
    name: Outside
    yaxes: y2
    line:
      color: gray
      shape: spline
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_buiten
  - entity: sensor.th_office2_temperature
    statistic: mean
    legendgroup: 5
    name: Office
    yaxes: y1
    line:
      color: blue
      dash: dot
      shape: spline
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_office
  - entity: sensor.th_guest_temperature
    statistic: mean
    legendgroup: 6
    name: Guest
    yaxes: y1
    line:
      dash: dot
      shape: spline
      colour: red
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_guest
  - entity: sensor.th_master_br_temperature
    statistic: mean
    legendgroup: 7
    name: Master
    yaxes: y1
    line:
      dash: dot
      shape: spline
      color: orange
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_master
  - entity: sensor.th_alastair_temperature
    statistic: mean
    legendgroup: 8
    name: Alastair
    yaxes: y1
    line:
      color: gray
      dash: dot
      shape: spline
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_alastair
  - entity: sensor.th_bathroom_temperature
    statistic: mean
    legendgroup: 9
    name: Bathroom
    yaxes: y1
    line:
      color: yellow
      dash: dot
      shape: spline
    filters:
      - map_y: parseFloat(y)
      - store_var: temperature_bathroom
  - entity: sensor.livingroom_migo_set_temperature
    statistic: mean
    legendgroup: 10
    visible: legendonly
    name: Migo curr
    yaxes: y1
    line:
      color: yellow
      shape: spline
  - entity: sensor.livingroom_migo_current_temperature
    statistic: mean
    legendgroup: 10
    visible: legendonly
    name: Migo set
    yaxes: y1
    line:
      color: yellow
      shape: spline
  - entity: sensor.th_livingroom_humidity
    statistic: mean
    legendgroup: 1
    name: Livingroom
    yaxes: y2
    showlegend: false
    line:
      color: red
      shape: spline
  - entity: sensor.th_kitchen_humidity
    statistic: min
    legendgroup: 2
    showlegend: false
    name: Kitchen
    yaxes: y2
    line:
      color: orange
      shape: spline
  - entity: sensor.buienradar_humidity
    statistic: mean
    legendgroup: 4
    visible: legendonly
    showlegend: false
    name: Kitchen
    yaxes: y2
    line:
      color: gray
      shape: spline
  - entity: sensor.th_garage_humidity
    statistic: mean
    legendgroup: 3
    visible: legendonly
    showlegend: false
    name: Garage
    yaxes: y2
    line:
      color: green
      shape: spline
  - entity: sensor.th_office2_humidity
    statistic: mean
    legendgroup: 5
    showlegend: false
    name: Office
    yaxes: y2
    line:
      color: blue
      dash: dot
      shape: spline
  - entity: sensor.th_guest_humidity
    statistic: mean
    legendgroup: 6
    showlegend: false
    name: Guest
    yaxes: y2
    line:
      dash: dot
      shape: spline
      color: red
  - entity: sensor.th_master_br_humidity
    statistic: mean
    legendgroup: 7
    showlegend: false
    name: Master
    yaxes: y2
    line:
      dash: dot
      shape: spline
      color: orange
  - entity: sensor.th_alastair_humidity
    statistic: mean
    legendgroup: 8
    showlegend: false
    name: Alastair
    yaxes: y2
    line:
      color: gray
      dash: dot
      shape: spline
  - entity: sensor.th_bathroom_humidity
    statistic: mean
    legendgroup: 9
    showlegend: false
    name: Bathroom
    yaxes: y2
    line:
      color: yellow
      dash: dot
      shape: spline
  - entity: sensor.th_livingroom_humidity
    showlegend: false
    statistic: mean
    legendgroup: 1
    name: Livingroom
    yaxes: y3
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_livingroom.ys[i])/(vars.temperature_livingroom.ys[i]+243.5))
          * y + vars.temperature_livingroom.ys[i] *
          2.1674)/(273.15+vars.temperature_livingroom.ys[i]);
    line:
      color: red
      shape: spline
  - entity: sensor.th_kitchen_humidity
    showlegend: false
    statistic: mean
    legendgroup: 2
    name: Kitchen
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_kitchen.ys[i])/(vars.temperature_kitchen.ys[i]+243.5))
          * y+ vars.temperature_kitchen.ys[i] *
          2.1674)/(273.15+vars.temperature_kitchen.ys[i]);
    yaxes: y3
    line:
      color: orange
      shape: spline
  - entity: sensor.th_garage_humidity
    showlegend: false
    statistic: mean
    legendgroup: 3
    name: Garage
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_garage.ys[i])/(vars.temperature_garage.ys[i]+243.5))
          *y + vars.temperature_garage.ys[i] *
          2.1674)/(273.15+vars.temperature_garage.ys[i]);
    yaxes: y3
    line:
      color: green
      shape: spline
  - entity: sensor.th_bathroom_humidity
    showlegend: false
    statistic: mean
    legendgroup: 9
    name: Bathroom
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_bathroom.ys[i])/(vars.temperature_bathroom.ys[i]+243.5))
          *y + vars.temperature_bathroom.ys[i] *
          2.1674)/(273.15+vars.temperature_bathroom.ys[i]);
    yaxes: y3
    line:
      color: yellow
      shape: spline
      dash: dot
  - entity: sensor.th_alastair_humidity
    showlegend: false
    statistic: mean
    legendgroup: 8
    name: Bathroom
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_alastair.ys[i])/(vars.temperature_alastair.ys[i]+243.5))
          *y + vars.temperature_alastair.ys[i] *
          2.1674)/(273.15+vars.temperature_alastair.ys[i]);
    yaxes: y3
    line:
      color: gray
      shape: spline
      dash: dot
  - entity: sensor.th_guest_humidity
    showlegend: false
    statistic: mean
    legendgroup: 6
    name: Guestroom AH
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_guest.ys[i])/(vars.temperature_guest.ys[i]+243.5)) *
          y + vars.temperature_guest.ys[i] *
          2.1674)/(273.15+vars.temperature_guest.ys[i]);
    yaxes: y3
    line:
      color: red
      shape: spline
      dash: dot
  - entity: sensor.th_office2_humidity
    showlegend: false
    statistic: mean
    legendgroup: 5
    name: Office AH
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_office.ys[i])/(vars.temperature_office.ys[i]+243.5))
          *y + vars.temperature_office.ys[i] *
          2.1674)/(273.15+vars.temperature_office.ys[i]);
    yaxes: y3
    line:
      color: blue
      shape: spline
      dash: dot
  - entity: sensor.th_master_br_humidity
    showlegend: false
    statistic: mean
    legendgroup: 7
    name: Guestroom AH
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_master.ys[i])/(vars.temperature_master.ys[i]+243.5))
          *y + vars.temperature_master.ys[i] *
          2.1674)/(273.15+vars.temperature_master.ys[i]);
    yaxes: y3
    line:
      color: orange
      shape: spline
      dash: dot
  - entity: sensor.buienradar_humidity
    showlegend: false
    visible: legendonly
    statistic: mean
    legendgroup: 4
    name: buiten AH
    unit_of_measurement: g/m³
    filters:
      - map_y: parseFloat(y)
      - map_y: >-
          (6.112 * Math.exp((17.67 *
          vars.temperature_buiten.ys[i])/(vars.temperature_buiten.ys[i]+243.5))
          *y + vars.temperature_buiten.ys[i] *
          2.1674)/(273.15+vars.temperature_buiten.ys[i]);
    yaxes: y3
    line:
      color: gray
      shape: spline
hours_to_show: 24
autorange_after_scroll: true
layout:
  dragmode: pan
  margin:
    t: 30
    l: 50
    r: 30
    b: 50
  showlegend: true
  height: 800
  legend:
    x: 0
    "y": 1.02
    bgcolor: rgba(0,0,0,.4)
    orientation: h
    itemsizing: fixed
    font:
      size: 10
  grid:
    rows: 3
    columns: 1
    roworder: top to bottom
  yaxis1:
    side: left
    visible: true
    showgrid: true
    overlaying: y1
    title:
      text: Temperature
  yaxis2:
    side: left
    visible: true
    showgrid: true
    overlaying: y1
    title:
      text: Humidity
  yaxis3:
    side: left
    overlaying: y2
    visible: true
    showgrid: true
    title:
      text: Abs. Humidity
  plot_bgcolor: black
  y1:
    gridcolor: whitesmoke
    zeroline: false
    fixedrange: true
  xaxis:
    rangeselector:
      "y": 1
      buttons:
        - count: 3
          step: day
        - count: 7
          step: day
        - count: 14
          step: day
        - count: 1
          step: month
        - count: 3
          step: month
        - count: 12
          step: month
        - count: 36
          step: month
defaults:
  entity:
    line: null
    period:
      24h: 5minute
      3d: 5minute
      7d: hour
      14d: hour
      1M: day
      3M: day
      12M: week
      36M: month
  width: 1
title: Climate
```
