### DISCUSSION TITLE
How to filter the sources values of a entity for mean/ average

### DISCUSSION THREAD

**Discussion by thecem** [dbuezas/lovelace-plotly-graph-card#509] [Q&A]
I try to prefilter the values that are averaged in window from 2 to 7.

Every time slot outside this window should not be considered to build the mean.

```
type: custom:plotly-graph
entities:
  - entity: sensor.heat_pump_cop
    statistic: mean
    period: month
    name: AT
    type: bar
    show_value: true
    filters:
      - filter: y < 4.5
      - filter: y > 4
title: Heat Pump COP
hours_to_show: 8760
```

With this above filter it filters only what the graph shows but not the mean to this windows of "0.5". 
How could I achive such a filter?
thx
