### DISCUSSION TITLE
CPU Graph like Task manager

### DISCUSSION THREAD

**Discussion by DeFlanko** [dbuezas/lovelace-plotly-graph-card#511] [Q&A] [answered]
Hi,  now that Home assistant can shrink cells down to a 1x2 box, is it possible to just show plotty graph data and not show the X and Y numbers -- like a task manager CPU screen.  

update: 
Searched though some of the Examples and found the[ Heatmap for Solar panels](https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/277) being pretty close to what im looking for.  (experimenting with colorscale too...

![image](https://github.com/user-attachments/assets/9674bdc6-5d2d-4076-a09d-ac0cf9ec37c7)

```yaml
type: custom:plotly-graph
fn: |
  $ex {
    vars.z = [[
          // row 4
         'sensor.load_cpu_18', 'sensor.load_cpu_19', 'sensor.load_cpu_20', 'sensor.load_cpu_21', 'sensor.load_cpu_22', 'sensor.load_cpu_23',
        ],[
          // row 3
          'sensor.load_cpu_12', 'sensor.load_cpu_13', 'sensor.load_cpu_14', 'sensor.load_cpu_15', 'sensor.load_cpu_16', 'sensor.load_cpu_17',
        ],[
          // row 2
          'sensor.load_cpu_6', 'sensor.load_cpu_7', 'sensor.load_cpu_8', 'sensor.load_cpu_9', 'sensor.load_cpu_10', 'sensor.load_cpu_11',
        ],[
          // row 1
          'sensor.load_cpu_0', 'sensor.load_cpu_1', 'sensor.load_cpu_2', 'sensor.load_cpu_3', 'sensor.load_cpu_4', 'sensor.load_cpu_5',
        ]].map(row=>
          row.map(sensor=>
            isNaN(hass.states[sensor]?.state) ? '' : Math.round(hass.states[sensor]?.state) // Handles empty cells
      )
    )
  }
entities:
  - entity: ""
    z: $ex vars.z
    text_auto: true
    type: heatmap
    hoverongaps: false
    xgap: 2
    ygap: 2
    zmax: 100
    zmin: 0
    showscale: false
    colorscale: Rainbow
color_scales: null
raw_plotly_config: true
refresh_interval: 5
layout:
  annotations: |
    $ex vars.z.flatMap((row, y) => row.map((text="", x) => ({
      x,
      y,
      text,
      font: {
        family: 'Ariel',
        size:   '14',
        color:  'black'
      },
      showarrow: false,
    })))
  yaxis:
    showgrid: false
    zeroline: false
    showticklabels: false
    visible: false
  xaxis:
    showgrid: false
    zeroline: false
    showticklabels: false
    ticks: false
    visible: false
  height: 300
  margin:
    t: 5
    l: 15
    b: 20
    r: 20
grid_options:
  columns: null
  rows: null
```

ultimately looking for something along the lines of:
 
![image](https://github.com/user-attachments/assets/6972ccdf-db89-498f-94be-ff7342847b52)

**Comment by dbuezas** [comment]
Sure you can! Google/gpt for grid plots and axis visibility

**Comment by DeFlanko** [comment, marked as answer]
For those who are looking for this same solution. 
```YAML
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_0
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_0') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_0') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_1
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_1') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_1') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_2
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_2') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_2') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_3
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_3') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_3') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_4
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_4') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_4') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_5
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_5') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_5') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
  - type: horizontal-stack
    cards:
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_6
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_6') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_6') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_7
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_7') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_7') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_8
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_8') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_8') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_9
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_9') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_9') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_10
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_10') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_10') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_11
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_11') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_11') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
  - type: horizontal-stack
    cards:
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_12
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_12') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_12') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_13
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_13') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_13') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_14
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_14') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_14') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_15
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_15') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_15') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_16
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_16') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_16') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_17
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_17') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_17') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
  - type: horizontal-stack
    cards:
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_18
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_18') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_18') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_19
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_19') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_19') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_20
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_20') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_20') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_21
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_21') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_21') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_22
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_22') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_22') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
      - type: custom:plotly-graph
        entities:
          - entity: sensor.load_cpu_23
            name: CPU Load
            color: |
              {% if states('sensor.load_cpu_23') | float <= 74 %}
                'lime'
              {% elif states('sensor.load_cpu_23') | float <= 85 %}
                'orange'
              {% else %}
                'red'
              {% endif %}
            fill: tozeroy
        graph: line
        smooth: true
        show_legend: false
        show_ticks: false
        style: |
          .chart {
            background-color: rgba(0, 0, 0, 0);
          }
          .plotly {
            border: none;
          }
        layout:
          xaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            fixedrange: true
            ticks: ""
            tickformat: ""
          yaxis:
            showgrid: true
            zeroline: true
            showline: true
            showticklabels: false
            range:
              - 0
              - 101
            fixedrange: true
            dtick: 25
            ticks: ""
            tickformat: ""
            title: ""
          margin:
            l: 0
            r: 0
            t: 0
            b: 10
            pad: 0
          height: 60
          hovermode: false
```
![image](https://github.com/user-attachments/assets/1e99977d-3ca5-4ad1-a948-99eca70ac19d)
