### DISCUSSION TITLE
Custom buttons to change colorscale of multiple heatmap entities.

### DISCUSSION THREAD

**Discussion by deltamelter** [dbuezas/lovelace-plotly-graph-card#517] [Q&A]
I'm unsure which colour scale I want to use with heatmap so decided to add multiple options to a set of custom buttons.
I don't know how to refer to the properties of an individual entity, tried a couple of variations.
Is it even possible to affect the style (colorscale) of individual entities?

Also... Is it possible to force the "system" buttons down the right side instead of over the chart title? 
![image](https://github.com/user-attachments/assets/e7dd4045-5133-4829-b369-47fa75e89960)
```
entities:
  - entity: ""
    z: $ex vars.z
    x: $ex vars.x
    "y": $ex vars.y
    text_auto: true
    type: heatmap
    offset: 0
    colorscale: $ex vars.colorscale
    contours_coloring: heatmap
    hovertemplate: "<b>Temp: </b>%{z:.2f}°C</br><extra></extra>"
  - entity: ""
    x: $ex vars.x2
    "y": $ex vars.y2
    z: $ex vars.z2
    text_auto: true
    type: heatmap
    showscale: false
    hoverongaps: false
    colorscale: $ex vars.colorscale
    contours_coloring: heatmap
raw_plotly_config: true
refresh_interval: auto
ha_theme: true
layout:
  updatemenus:
    - buttons:
        - args:
            - entities.0.colorscale
            - RdBu
          label: RdBu
          method: restyle
        - args:
            - entities:
                - "0": 
                  colorscale: Bluered
          label: Bluered
          method: restyle
        - args:
            - colorscale
            - Portland
          label: Portland
          method: restyle
      direction: down
      active: -1
      pad:
        l: 1
        t: 1
      x: 0.1
      "y": 90
      xanchor: right
      yanchor: top
      type: buttons

```

**Comment by deltamelter** [comment]
I found [plotly python examples](https://github.com/plotly/plotly.py/issues/2170) and [doc](https://plotly.com/python/custom-buttons/) to do exactly this, but it doesn't seem to translate to plotly.js or this card.  
Any ideas on how to make the buttons reference the entity properties?

**Reply by dbuezas** [reply]
Did you try like this? https://plotly.com/javascript/custom-buttons/

Remember that plotlyjs doesn't see "entities", this card translates that to data traces, so update buttons should be configured exactly as in the docs

**Reply by deltamelter** [reply]
yes, like this..
```
        buttons: [
            {
                args: ['colorscale', 'Portland'],
                label:'Portland',
                method:'restyle'
            }
        ],
```      
as 
```
        - args:
            - colorscale
            - Portland
          label: Portland
          method: restyle
```

**Reply by deltamelter** [reply]
> Remember that plotlyjs doesn't see "entities", this card translates that to data traces, so update buttons should be configured exactly as in the docs

the entity is where the colorscale is, the examples show args referring directly to layout so I was trying to do the same with "entity" 
This works as defined in plotlyjs and plotly.py, but I don't know how to define in this card.  do I have to use raw plotly js in a $fn or $ex?

**Reply by deltamelter** [reply]
also tried like this in an `fn:` with `$ex`
```
    vars.colorscale =  (label) => ({
      args: [
        {
          "colorscale": label
        }
      ],
      label,
      "method": "restyle",    
    label})
```
```
layout:
  updatemenus:
    - buttons:
        - $fn({vars}) => vars.colorscale( 'RdBu')
```

**Reply by dbuezas** [reply]
Interestingly it works if there is a single button

**Reply by deltamelter** [reply]
> Interestingly it works if there is a single button

Oh? What yaml syntax works for you?

**Reply by dbuezas** [reply]
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.openweathermap_temperature
    fn: |
      $fn ({ xs, ys, vars }) => {
        const x = [ "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",
        ];
        const y = ["Morning", "Afternoon", "Evening"];
        const sum = y.map((time) => x.map((day) => 0));
        const count = y.map((time) => x.map((day) => 0));
        for (let i = 0; i < xs.length; i++) {
          const date = xs[i];
          const time = Math.floor(date.getHours() / 8);
          const day = date.getDay();
          sum[time][day] += +ys[i];
          count[time][day]++;
        }
        const z = sum.map((row, time) =>
          row.map((val, day) => val / count[time][day])
        );
        vars.x = x;
        vars.y = y;
        vars.z = z;
      };
    x: $fn ({ vars }) => vars.x
    'y': $fn ({ vars }) => vars.y
    z: $fn ({ vars }) => vars.z
    type: heatmap
    hoverongaps: false
raw_plotly_config: true
hours_to_show: 240
title: heatmap

layout:
  updatemenus:
    - buttons:
        - args:
            - colorscale
            - Portland
          label: Portland
          method: restyle
      direction: down
      active: -1
      pad:
        l: 1
        t: 1
      x: 0.1
      "y": 90
      xanchor: right
      yanchor: top
      type: buttons
```
