### DISCUSSION TITLE
Font size for  show_value: true

### DISCUSSION THREAD

**Discussion by jazzmonger** [dbuezas/lovelace-plotly-graph-card#529] [General]
Is there a way to change it. ie make it bigger?  Us old guys need bigger fonts :)

**Comment by dbuezas** [comment]
Yes there is!
Show_value works by internally adding a trace which inherits all settings from the source entity, which then shows text via texttemplate, so 
```yaml
entities:
   entity: sensor.xys
   show_value: true
   textfont:
       size: 15
```
will change the font size. You can change more font settings https://plotly.com/javascript/texttemplate/
