### DISCUSSION TITLE
Show_value not shown in rangebreaks

### DISCUSSION THREAD

**Discussion by elbertov** [dbuezas/lovelace-plotly-graph-card#530] [Q&A] [answered]
Hi,

I noticed that when you use _show_value_ together with _rangebreaks_ the value is not shown if the right part of the graph lies in the range that is beinig suppressed by the rangebreak:

A simple example just for demonstration, rangebreaks is not showing saterday and sunday:

```
type: custom:plotly-graph
hours_to_show: 24
entities:
  - entity: sensor.buienradar_temperature
    show_value: true
    texttemplate: 
      Some nice<br><b>%{y}</b><br>template
layout:
  xaxis:
    rangebreaks:
      - pattern: day of week
        bounds:
          - sat
          - mon
  margin:
    r: 80
```

On a weekday it shows:

![image](https://github.com/user-attachments/assets/5b96dfef-8522-4b17-a3a2-0add9ed0abbd)

In the weekend it shows:

![image](https://github.com/user-attachments/assets/e4c34c94-6def-4775-b361-eca1099a9b5d)

Is there a way to prevent the hiding of the texttemplate so it is also shown in a rangebreak period?

kind regards Martin

**Comment by dbuezas** [comment]
That's because show_value adds an extra trace with a single point at the end of the data. If the last data point is hidden by the range break, then it won't ve shown. The only option I see is to filter out all data points in the hidden part.

```yaml
entities:
  entity: sensor.xyz
  filters:
    - filter: x.getDay() != 0 && x.getDay() != 6
  show_value: true
```

**Comment by elbertov** [comment, marked as answer]
Perfect! Thx!

```
type: custom:plotly-graph
hours_to_show: 240
entities:
  - entity: sensor.buienradar_temperature
    show_value: true
    texttemplate: <i>text</i>
layout:
  xaxis:
    tickformat: "%d-%m"
    dtick: 86400000
    rangebreaks:
      - pattern: day of week
        bounds:
          - sat
          - mon
```
![image](https://github.com/user-attachments/assets/600a85c1-16cd-4c65-991e-5a1a9c970641)

```
type: custom:plotly-graph
hours_to_show: 240
entities:
  - entity: sensor.buienradar_temperature
    show_value: true
    texttemplate: <i>text</i>
    filters:
      - filter: x.getDay() != 0 && x.getDay() != 6
layout:
  xaxis:
    tickformat: "%d-%m"
    dtick: 86400000
    rangebreaks:
      - pattern: day of week
        bounds:
          - sat
          - mon
```

![image](https://github.com/user-attachments/assets/7c04c8b7-8aa2-4221-b50b-26809b698ff9)
