### DISCUSSION TITLE
Not all entites are updated in graph when tab stays open

### DISCUSSION THREAD

**Discussion by citoki** [dbuezas/lovelace-plotly-graph-card#534] [Q&A]
I've configured 3 entities, 2 are calculated via `filters` and `map_y` function. These ones aren't updated properly when the tab stays open:

<img width="374" alt="image" src="https://github.com/user-attachments/assets/5c7902ec-b642-4c5f-a239-1d55ed873c0f" />

The one which is updated properly, the `WP` line with the teal color. Is it possible to get updates for every entity?

<details><summary>complete config for reference</summary>
<p>

```yaml
type: custom:plotly-graph
hours_to_show: 12
refresh: 10
autorange_after_scroll: false
entities:
  - entity: sensor.pv_ac_power_combined_integral
    name: PV Produktion
    statistic: state
    period: auto
    legendgroup: 1
    show_value: true
    unit_of_measurement: kWh / 5min
    filters:
      - derivate
      - store_var: pv_ac_power
    line:
      width: 1
      color: gold
    fill: tozeroy
  - entity: sensor.solaredge_m1_exported_kwh
    internal: true
    statistic: state
    period: auto
    filters:
      - derivate: h
      - map_y: parseFloat(vars.pv_ac_power.ys[i]) - parseFloat(ys[i])
      - store_var: eigenverbrauch
  - entity: sensor.solaredge_m1_imported_kwh
    name: Importiert
    statistic: state
    legendgroup: 3
    show_value: true
    unit_of_measurement: kWh / 5min
    period: auto
    filters:
      - derivate
      - map_y: >-
          (parseFloat(y[i-1]) === parseFloat(ys[i])) ? 0 :
          parseFloat(vars.eigenverbrauch.ys[i]) + parseFloat(ys[i])
    line:
      width: 1
      color: orangered
    fill: tozeroy
  - entity: sensor.solaredge_m1_exported_kwh
    name: Eigenverbrauch
    statistic: state
    legendgroup: 2
    show_value: true
    unit_of_measurement: kWh / 5min
    period: auto
    filters:
      - derivate: h
      - map_y: parseFloat(vars.pv_ac_power.ys[i]) - parseFloat(ys[i])
    line:
      width: 1
      color: dodgerblue
    fill: tozeroy
    fillcolor: lightskyblue
  - entity: sensor.ebusd_hmu00_currentconsumedpower
    name: >
      $ex "WP (" + hass.states['sensor.ebusd_sensor'].state
      + "kWh) "
    unit_of_measurement: kWh / 5min
    show_value: false
    line:
      width: 2
      color: teal
layout:
  dragmode: pan
  yaxis:
    rangemode: nonnegative
  yaxis2:
    side: right
    range:
      - 0
      - 200
  xaxis:
    rangeselector:
      "y": 1.4
      buttons:
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 2
          step: day
        - count: 4
          step: day

```
</p>
