### DISCUSSION TITLE
Owlet sock stats chart.

### DISCUSSION THREAD

**Discussion by Homemaderobot** [dbuezas/lovelace-plotly-graph-card#535] [Show and tell]
My little one was born at just 25 weeks and the Plotly card has been incredibly useful for monitoring his stats when he sleeps from his Owlet Sock (v3). Allowing for far better visualisation than the app (which isn't great).  Thought I'd share in case it's of use to others. 

Nothing advanced going on, only challenge for me was to get the sleep state (awake / light sleep / deep sleep) as a background colour - only way I could figure it out was to create a new binary sensor for each state and stretch it the height of the chart.

Thank you @dbuezas for a fantastic card with immense support.

![image](https://github.com/user-attachments/assets/286e67ce-ec92-4bc3-b1a1-c9d90f30f842)

```type: custom:plotly-graph
entities:
  - entity: binary_sensor.owlet_sleep_state_awake
    name: Awake
    fill: tozeroy
    showlegend: false
    line:
      color: "#2e3a42"
      width: 0
  - entity: binary_sensor.owlet_sleep_state_deep_sleep
    name: Deep Sleep
    fill: tozeroy
    showlegend: false
    line:
      color: "#401a54"
      width: 0
  - entity: binary_sensor.owlet_sleep_state_light_sleep
    name: Light Sleep
    fill: tozeroy
    showlegend: false
    line:
      color: "#412f4a"
      width: 0
  - entity: sensor.owlet_baby_care_sock_o2_saturation
    name: SpO2
    yaxis: y3
    line:
      color: "#2778a3"
      width: 2
  - entity: sensor.owlet_baby_care_sock_o2_saturation
    name: Av SpO2
    statistic: mean
    period: 5minute
    yaxis: y3
    line:
      color: "#4eb54c"
      width: 2
  - entity: sensor.owlet_baby_care_sock_movement
    name: Wiggle
    opacity: 0.2
    yaxis: y2
    line:
      width: 2
      color: "#ffe100"
  - entity: sensor.owlet_baby_care_sock_heart_rate
    yaxis: y4
    showlegend: false
    line:
      color: "#c20000"
      width: 2
layout:
  plot_bgcolor: rgba(100, 0, 0, 0)
  height: 650
  margin:
    r: 35
  grid:
    rows: 2
    columns: 1
    roworder: bottom to top
  legend:
    x: 1.03
    "y": 1.01
    xanchor: right
  yaxis4:
    title: Heart Rate (bpm)
    overlaying: y2
    domain:
      - 0
      - 0.35
    range:
      - 0
      - 250
    fixedrange: true
    side: left
    visible: true
    showgrid: true
  yaxis:
    categoryorder: array
    categoryarray:
      - "off"
      - "on"
    domain:
      - 0
      - 1
    fixedrange: true
    visible: false
    range:
      - 0.5
      - 0.8
  yaxis2:
    domain:
      - 0.4
      - 1
    overlaying: y2
    range:
      - -100
      - 360
    fixedrange: true
    visible: false
  yaxis3:
    title: SpO2 (%)
    domain:
      - 0.4
      - 1
    overlaying: y2
    range:
      - 60
      - 110
    showgrid: true
    fixedrange: true
    visible: true
    side: left
  xaxis:
    side: top
    ticklabelposition: inside
    position: 0.5
    rangeselector:
      y: 1.0225
      x: -0.035
      buttons:
        - count: 7
          step: day
  shapes:
    - type: line
      xref: paper
      x0: 0
      x1: 1
      yref: y3
      y0: 92
      y1: 92
      opacity: 0.3
      line:
        dash: dot
        color: white
        width: 1
refresh_interval: 10
config:
  displayModeBar: false
```

**Comment by dbuezas** [comment]
Wow, that's really interesting! Would you recommend this sock outlet v3?

**Reply by Homemaderobot** [reply]
Thanks! I think it depends on your situation as to whether I'd recommend it. 

Our little one has a background of chronic lung disease and it gives us either peace of mind (or a reason to take him to the GP / hospital). We've had it for over a year now and we use it less and less as he's grown (he's 14 months corrected age) and his health has improved, just bringing it out now for periods when he's unwell to monitor his SpO2 (a number of times this winter). I suspect most customers are neurotic parents with healthy babies though and it might just make them more neurotic! 

It's proved invaluable for us but could be useful for parents when your kid is unwell and you want that reassurance.

**Reply by dbuezas** [reply]
I wish his condition keeps improving and he grows to be strong and healthy!

Good point on not over-worrying about healthy babies, I almost bought it impulsively 

It makes me very happy to hear that something I made can be useful for this, thank you sharing this

**Reply by Homemaderobot** [reply]
Thank you for your well wishes (he's doing great by the way) - and thanks for your tireless work on this card which has been brilliant for this use case.

**Comment by jtracey93** [comment]
@Homemaderobot thanks for this awesome work! Really useful for my 33 weeker that we've just brought home.

Can you advise how you did the binary sensors?

**Reply by jtracey93** [reply]
So I think I did this with creating helpers in home assistant. Is this what you did?

**Reply by Homemaderobot** [reply]
So happy someone else is finding my set up useful. I actually wasn't aware you could set up sensors via the helpers page - if that works then maybe the best approach. I configured the sensors in configuration.yaml (accessed by File Editor add on)....

```
binary_sensor:
  - platform: template
    sensors:
      owlet_sleep_state_awake:
        friendly_name: "Owlet Sleep State Awake"
        value_template: "{{ is_state('sensor.owlet_baby_care_sock_sleep_state', 'awake') }}"
      owlet_sleep_state_light_sleep:
        friendly_name: "Owlet Sleep State Light Sleep"
        value_template: "{{ is_state('sensor.owlet_baby_care_sock_sleep_state', 'light_sleep') }}"
      owlet_sleep_state_deep_sleep:
        friendly_name: "Owlet Sleep State Deep Sleep"
        value_template: "{{ is_state('sensor.owlet_baby_care_sock_sleep_state', 'deep_sleep') }}"
```
