### DISCUSSION TITLE
Incorrect summation in a stacked bar chart

### DISCUSSION THREAD

**Discussion by eiderterra** [dbuezas/lovelace-plotly-graph-card#537] [Q&A]
Hello everyone,
In my diagram for PV generation, the sum is calculated incorrectly if not all data is available in the displayed time range. I think it is due to the assignment of i(0), but I don't know how to correct this. Even with the help of chatgpt I have not found a solution. Maybe someone of you has an idea!
here it is still correct:
![grafik](https://github.com/user-attachments/assets/8692cdaf-82f1-4c66-88db-ddcac425821f)

here it is wrong:

![grafik](https://github.com/user-attachments/assets/7ff7ffef-33eb-4fd2-93e5-534eefe9e37a)

Code:

```
type: custom:plotly-graph
entities:
  - entity: sensor.sn_3020359418_pv_gen_meter
    texttemplate: "%{y:.2f}"
    textfont:
      size: 11
      color: "#ffffff"
    name: TP60
    unit_of_measurement: kWh
    type: bar
    statistic: state
    period:
      0m: 5minute
      25h: hour
      10d: day
      3M: month
      6M: month
    marker:
      color: "#CD853F"
      opacity: 2
    filters:
      - filter: i>=0
      - delta
      - force_numeric
      - store_var: d
  - entity: sensor.pv_kwh_46
    texttemplate: "%{y:.2f}"
    textfont:
      size: 11
      color: "#ffffff"
    name: SB46
    unit_of_measurement: kWh
    type: bar
    statistic: state
    period:
      0m: 5minute
      25h: hour
      10d: day
      3M: month
      6M: month
    marker:
      color: "#034f84"
      opacity: 2
    filters:
      - filter: i>=0
      - delta
      - force_numeric
      - store_var: a
  - entity: sensor.pv_kwh_25
    texttemplate: "%{y:.2f}"
    textfont:
      size: 11
    name: SB25
    unit_of_measurement: kWh
    type: bar
    statistic: state
    period:
      0m: 5minute
      25h: hour
      10d: day
      3M: month
      6M: month
    marker:
      color: "#c83349"
      opacity: 0.9
    filters:
      - filter: i>=0
      - delta
      - force_numeric
      - store_var: b
  - entity: sensor.pv_kwh_11
    texttemplate: "%{y:.2f}"
    textfont:
      size: 11
    name: SB11
    unit_of_measurement: kWh
    type: bar
    statistic: state
    period:
      0m: 5minute
      25h: hour
      10d: day
      3M: month
      6M: month
    marker:
      color: "#008080"
      opacity: 0.9  // Deckkraft
    filters:
      - filter: i>=0
      - delta
      - force_numeric
      - store_var: c
  - entity: ""
    type: bar
    name: sum
    unit_of_measurement: kWh
    statistic: mean
    period:
      0m: 5minute
      25h: hour
      10d: day
      3M: month
      6M: month
    filters:
      - load_var: a
      - map_y: 0.1
    text: >-
      $ex vars.a.ys.map((y,i) =>(y +(vars.b.ys[i] ||0)+(vars.c.ys[i]
      ||0)+(vars.d.ys[i]||0)).toFixed(2).replace('.', ','))
    textfont:
      color: black
    showlegend: false
    marker:
      color: transparent
  - entity: sensor.pv_leistung_11
    type: indicator
    mode: number
    value: $ex ys.at(-1)
    bgcolor: black
    title:
      text: SB11 (11M)
      font:
        size: 10
    number:
      suffix: W
      valueformat: "0.11"
      font:
        size: 14
        color: "#008080"
    domain:
      x:
        - 0
        - 0.1
      "y":
        - 0.999
        - 1
  - entity: sensor.pv_leistung_25_2
    type: indicator
    mode: number
    value: $ex ys.at(-1)
    bgcolor: black
    title:
      text: SB25 (23M)
      font:
        size: 10
    number:
      suffix: W
      valueformat: "0.11"
      font:
        size: 14
        color: "#c83349"
    domain:
      x:
        - 0.2
        - 0.3
      "y":
        - 0.9999
        - 1
  - entity: sensor.pv_leistung_46
    type: indicator
    mode: number
    value: $ex ys.at(-1)
    bgcolor: black
    title:
      text: SB46 (38M)
      font:
        size: 10
    number:
      suffix: W
      valueformat: "0.11"
      font:
        size: 14
        color: "#034f84"
    domain:
      x:
        - 0.45
        - 0.55
      "y":
        - 0.9999
        - 1
  - entity: sensor.pv_leistung_60
    type: indicator
    mode: number
    value: $ex ys.at(-1)
    bgcolor: black
    title:
      text: TP60 (15M)
      font:
        size: 10
    number:
      suffix: W
      valueformat: "0.11"
      font:
        size: 14
        color: "#CD853F"
    domain:
      x:
        - 0.7
        - 0.8
      "y":
        - 0.9999
        - 1
  - entity: sensor.pv_leistung
    type: indicator
    mode: number
    value: $ex ys.at(-1)
    bgcolor: black
    title:
      text: gesamt
      font:
        size: 10
    number:
      suffix: W
      valueformat: "0.11"
      font:
        size: 14
        color: "#8B0000"
    domain:
      x:
        - 0.9
        - 1
      "y":
        - 0.9999
        - 1
layout:
  updatemenus:
    - buttons:
        - args:
            - xaxis.range
            - >-
              $fn({getFromConfig}) => getFromConfig("visible_range").map(t => t
              - 1000*60*60*24*10)
          label: <
          method: relayout
        - args:
            - xaxis.range
            - >-
              $fn({getFromConfig}) => getFromConfig("visible_range").map(t => t
              + 1000*60*60*24*10)
          label: ">"
          method: relayout
      direction: right
      active: -1
      pad:
        r: 100
        t: -80
      type: buttons
      x: 1
      xanchor: right
      "y": 1
      yanchor: top
  paper_bgcolor: rgba(0,0,0,0)
  plot_bgcolor: rgba(0,0,0,0)
  barmode: relative
  bargap: 0.2
  uniformtext:
    minsize: 12
    mode: show
  modebar:
    orientation: h
    remove: pan
  margin:
    t: 30
    l: 40
    r: 30
    b: 0
  height: 600
  legend:
    "y": -0.25
    x: 0.02
  xaxis:
    rangeselector:
      "y": 1.15
      buttons:
        - count: 3
          step: day
        - count: 10
          step: day
        - count: 30
          step: day
        - count: 6
          step: month
        - count: 12
          step: month
    gridcolor: rgba(238,235,235,0.3)
    showgrid: true
    linewidth: 0
    linecolor: null
    nticks: 12
    tickformat: |-
      %d %b
       %Y
  yaxis:
    visible: true
hours_to_show: 10d
refresh_interval: 10
title: PV - kWh
view_layout:
  position: main
autorange_after_scroll: true
defaults:
  yaxes:
    fixedrange: true
```

I would be happy about a solution.
Greetings from the north of Germany
