### DISCUSSION TITLE
How to properly make a horizontal bar chart?

### DISCUSSION THREAD

**Discussion by henriknordgren** [dbuezas/lovelace-plotly-graph-card#539] [Q&A] [answered]
I couldn't find any example on how to make a horizontal bar chart which show sums from statistics? Here is a very basic example.

Basically I want a horizontal bar chart, where each energy sensor get a delta sum based on what period I choose. One bar for each device/entity. I know how to make bar vertical diagrams with offsets and statistics, but I can't figure this one out, and there are no examples. What differs from a vertical bar is that I have fixed values for the Y axis. The X axis should be in kWh like the other X axis. I tried to change them around, but it got me nowhere. Any advise?

```
type: custom:plotly-graph         
        layout:         
          showlegend: false
          width: 1100
          height: 500    
          xaxis:
            autotick: true
          yaxis:
            title: ''
            autotick: true
        entities:
          - entity: sensor.qubino_3_phase_smart_meter_electric_consumption_kwh
            type: bar 
            statistic: state
            period: day
            y: ['Heat Pump']              
            orientation: 'h'
          - entity: sensor.easee_kWh
            type: bar      
            statistic: state
            period: day
            y: ['Easee Charger']            
            orientation: 'h'           
        refresh_interval: 30
```
