### DISCUSSION TITLE
I need some help on how to configure the bar diagram to show X axis properly

### DISCUSSION THREAD

**Discussion by henriknordgren** [dbuezas/lovelace-plotly-graph-card#540] [General]
I am trying to make a simple bar diagram for days, months and years. No interactivity, just simple bar diagrams.

I have spent better part of the day trying to figure out how this works, but I am getting more and more confused. Look att this simple diagram:

This is by month, so I want to show on x axis 01-31 or whatever range the current month has. The data is in the statistics database.

I use autorange, since It seems like the way to go. I have set some key properties such as:

- hours_to_show: current_month
- time_offset: ${parseInt(states['input_number.month_offset'].state) + 'M';}
- autoRange: true
-

With the above, I assumed that current month is this month (february) and offset -1M means January.
autoRange should then be 01-31 for X-axis since I set 

-  dtick: D1
- tickformat: "%d"

and 

-  type: bar
-  statistic: state
- period: day

The results are very confusing. Here is when I just load it (with offset -1):

![image](https://github.com/user-attachments/assets/5b67f0e7-4337-42cd-b950-6baaabd4e252)

It stats at the third of january

And here is when I drag the diagram slightly to the left

![image](https://github.com/user-attachments/assets/fc329e05-4d8a-443c-a3e6-1ad53a00e2ca)

Behold, there are the missing bars for 01 and 02!!!

Why doesn't the x axis start from 01 then? How can I modify the yaml below to make the x-axis show bars and ticks prperly for year (2025, 2024, 2023), month (Jan-Dec) and Day (01-31) ?

What is it that I have messed up here?

```
type: custom:config-template-card
      entities:
        - sensor.offset_template
        - input_number.month_offset
        - sensor.energy_graph_sensor_name
      card:
        type: custom:plotly-graph
        card_mod:
          
        hours_to_show: current_month
        time_offset: ${parseInt(states['input_number.month_offset'].state) + 'M';}
        layout:
          font:
            family: Amazon Ember Bold, sans-serif
            size: 14
            color: "#444444"
          plot_bgcolor: rgba(0,0,0,0)
          paper_bgcolor: rgba(0,0,0,0)
          showlegend: false
          width: 950
          height: 500
          yaxis:
            title: Usage (kWh)
          xaxis:
            showgrid: false
            dtick: D1
            tickformat: "%d"
            tickmode: linear
            tickangle: 0
            autoRange: true

        entities:
          - entity: ${states['sensor.energy_graph_sensor_name'].state}
            type: bar
            statistic: state
            period: day
            texttemplate: "%{y:.0f}"
            extend_to_present: false
            filters:
              - delta              
        refresh_interval: 30
        config:
          scrollZoom: false
          displayModeBar: false    
```
