### DISCUSSION TITLE
How to create groups of data for stacked bar chart?

### DISCUSSION THREAD

**Discussion by henriknordgren** [dbuezas/lovelace-plotly-graph-card#545] [General]
I have spent hours looking through the documentation, but can't find any good example on this. I have like 14 utility sensors that store energy consumption data into statistics. I have created a stacked bar chart using these 14 sensors, and it doesnt look good, it is too cluttered.

I want to group say 5 of these utility sensors into a group "Appliances". I can't do it with a new template sensor, because then I dont get the long term statistics. I want plotly to take these 5 entities and make an "internal" group. Surely this is possible? Please  note that the utility sensors are a mix of Wh and kWh so for some entities (the Wh) I do this:

```
 filters:
      - delta
      - multiply: 0.001 <--- to get kWh
```
 
A typical entity in my bar chrt looks like this:

```
 - entity: sensor.qubino_3_phase_smart_meter_electric_consumption_kwh
                              type: bar
                              unit_of_measurement: kWh
                              statistic: state
                              period: hour
                              name: Climate
                              texttemplate: ""
                              filters:
                                - delta
```

Regards
Henrik
