### DISCUSSION TITLE
Make x axe shorter than hours_to_show

### DISCUSSION THREAD

**Discussion by miljbee** [dbuezas/lovelace-plotly-graph-card#547] [Q&A] [answered]
How to have x_min greater than what's computed with hours_to_show ?
 \- or -
How to get data older than hours_to_show ?

That's because I am plotting a 'sliding delta' to observe energy consumption evolution over a year.
To get the delta, I map y values to y-ys[i-52] (52 weeks in one year)
So, for i<52 I have no data
and to get values for i> 52 I need more than 52 weeks of data
So, I have hours_to_show: 2y

The result is that I get a plot on the right half of x. How to have x starting only one year ago ?

![image](https://github.com/user-attachments/assets/a9cb2912-eb0b-4444-8c54-a72add81db50)

```yaml
type: custom:plotly-graph
defaults:
  entity:
    period: week
    showlegend: false
entities:
  - entity: sensor.plu_ce_energy
    name: Energy
    statistic: sum
    filters:
      - force_numeric
      - map_y: y-ys[i-52]
      - filter: i>=52
  - entity: sensor.tmp_garage_temperature
    name: Température
    statistic: mean
    unit_of_measurement: °C
    filters:
      - filter: i>52
layout:
  yaxis:
    title: Energie (kWh)
    titlefont:
      color: "#1f77b4"
  yaxis2:
    title: Temp. (°C)
    titlefont:
      color: "#FF8811"
config:
  staticPlot: true
hours_to_show: 2y
refresh_interval: auto
title: 1y Energy
```

**Comment by dbuezas** [comment, marked as answer]
Try adding range to your xaxis:
```yaml
layout:
  xaxis:
    range: $ex [Date.now()-1*365*24*60*60*1000, Date.now()]
```
The initial data fetch will be done based on hours_to_show, but plotly will render the specified.
