### DISCUSSION TITLE
How to make a card with historical PV-Power Data compared to sun rise?

### DISCUSSION THREAD

**Discussion by Micha12323** [dbuezas/lovelace-plotly-graph-card#548] [Q&A] [answered]
Hey-Hoo, 

i am looking for a better comparison for my PV-Data. Everyone uses nice graphs but the "real" historical informations are mostly hidden in the data beyond the autoscale... 

I was thinking about line drawings on a daily basis normalized to sunrise time. Maybe in a 3d plot? 

Correct me, but I haven't found anything into that direction

**Comment by fpdragon** [comment]
This is what I currently have, not the best but it works.

![image](https://github.com/user-attachments/assets/08efe3c0-b07a-4f1c-9d78-19bbc7f21d71)

```
type: custom:plotly-graph
entities:
  - entity: sensor.sun_elevation
    name: Sun Elevation
    showlegend: false
    line:
      color: rgba(70, 70, 70, 1)
    fillcolor: rgba(70, 70, 70, 0.5)
    fill: tozeroy
    yaxis: "y"
  - entity: sensor.xx_pv_power_gesamt
    name: PV Power gesamt
    showlegend: false
    line:
      color: yellow
    filters:
      - resample: 1m
    fill: tozeroy
    yaxis: y2
  - entity: sensor.xx_pv_overpower
    name: PV Overpower
    showlegend: false
    line:
      color: blueviolet
    filters:
      - resample: 1m
    fill: tozeroy
    yaxis: y2
hours_to_show: 24
refresh_interval: 10
defaults:
  yaxes:
    fixedrange: true
layout:
  height: 150
  yaxis:
    title: ""
    showticklabels: false
    side: left
  yaxis2:
    side: left
    showticklabels: true
```

And you need to have this template defined:

```
- sensor:
    #---------------------------------------------------------------------------
    # Sun "{{ state_attr('sun.sun', 'elevation')|float }}"
    - name: "Sun Elevation"
      unique_id: "xx_sun_elevation"
      unit_of_measurement: "°"
      # device_class: "temperature"
      state_class: "measurement"
      state: >
        {% if state_attr('sun.sun', 'elevation')|float > 0.0 %}
          {{ state_attr('sun.sun', 'elevation')|float }}
        {% else %}
          {{ 0.0 }}
        {% endif %}
      icon: "mdi:weather-sunset"
``` 

And of course you need to add a sun entity.

Hopefully this helps. Change for Energy and so on.
