### DISCUSSION TITLE
How to set automatic range for the y axis?

### DISCUSSION THREAD

**Discussion by henriknordgren** [dbuezas/lovelace-plotly-graph-card#549] [General]
I have a table that show energy consumption in kWh on the y axis. I have set

hours_to_show: 25h
time_offset: 0h

xaxis;
 range:
        - '2025-03-18 23:30:00'
        - '2025-03-19 23:59:00'

Within this interval we have (yet) very little sun, yet the chart look like this:

![image](https://github.com/user-attachments/assets/4cf4b46d-f067-442c-bd14-404e4003d06c)

Why does plotly determine that it should draw the y axis to -8 kWh? We had this production yesterday, but that should not be included, right? 

Y axis is set to:

  yaxis:
                title: Energy (kWh)
                tickformat: .1f

**Comment by dbuezas** [comment]
Post the full yaml ([make sure to use code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))

**Reply by henriknordgren** [reply]
You got it maestro!


```yaml
 type: custom:plotly-graph
            card_mod:
              style: |
                ha-card {         
                  border: none;
                  margin-top: -20px!important;
                }
            hours_to_show: 25h
            time_offset: 0h
            entities:
              - entity: sensor.qubino_3_phase_smart_meter_electric_consumption_kwh
                type: bar
                unit_of_measurement: kWh
                statistic: state
                period: hour
                name: Climate
                marker:
                  color: '#F18303'
                texttemplate: ''
                filters:
                  - delta
              - entity: sensor.easee_lifetime_energy
                type: bar
                unit_of_measurement: kWh
                statistic: state
                period: hour
                name: Easee
                marker:
                  color: '#EA23FB'
                texttemplate: ''
                filters:
                  - delta
              - entity: sensor.ovrigt_lifetime_energy
                type: bar
                unit_of_measurement: kWh
                statistic: state
                period: hour
                name: Övrigt
                marker:
                  color: '#92A0A9'
                texttemplate: ''
                filters:
                  - delta                 
              - entity: sensor.diskmaskin_lifetime_energy
                type: bar
                unit_of_measurement: kWh
                statistic: state
                period: hour
                marker:
                  color: '#92A0A9'
                name: Diskmaskin
                hidden: false
                legendgroup: appliances
                showlegend: false
                texttemplate: ''
                filters:
                  - delta
              - entity: sensor.frysbox_lifetime_energy
                type: bar
                unit_of_measurement: kWh
                statistic: state
                period: hour
                marker:
                  color: '#92A0A9'
                name: Frysbox
                legendgroup: appliances
                showlegend: false
                hidden: true
                texttemplate: ''
                filters:
                  - delta
              - entity: sensor.honshus_lifetime_energy
                type: bar
                unit_of_measurement: kWh
                statistic: state
                hidden: true
                period: hour
                marker:
                  color: '#92A0A9'
                name: Hönshus
                legendgroup: appliances
                texttemplate: ''
                filters:
                  - delta
              - entity: sensor.solar_panels_lifetime_energy
                type: bar
                unit_of_measurement: kWh
                statistic: state
                period: hour
                marker:
                  color: '#FFCC00'
                name: Solar
                texttemplate: ''
                filters:
                  - delta
                  - multiply: -1
            refresh_interval: 30
            config:
              scrollZoom: false
              displayModeBar: false
            layout:
              width: 910
              height: 430
              plot_bgcolor: rgba(0,0,0,0)
              paper_bgcolor: rgba(0,0,0,0)
              font:
                family: Amazon Ember Bold, sans-serif
                size: 14
                color: '#444444'
              barmode: relative
              barcornerradius: 5
              showlegend: false
              legend:
                orientation: h
              xaxis:
                showgrid: false
                dtick: 3600000
                tickformat: '%H'
                tickmode: linear
                tickangle: 0
                range:
                  - '2025-03-18 23:30:00'
                  - '2025-03-19 23:59:00'
              yaxis:
                title: Energy (kWh)
                tickformat: .1f
```
