### DISCUSSION TITLE
Bar chart for 15min (k)Wh data  ?

### DISCUSSION THREAD

**Discussion by heebo1974** [dbuezas/lovelace-plotly-graph-card#554] [General]
I am trying to create chart with plotly which shows bars (15 min wide) from my template sensor which reset every 15min.
I have done it with apexchart like this:

![image](https://github.com/user-attachments/assets/cd551c49-5172-4a20-845c-949cae673ada)

```
type: custom:apexcharts-card
apex_config: null
graph_span: 14h
span:
  start: day
  offset: +7h
yaxis:
  - id: pankkitase
    apex_config:
      tickAmount: 4
show:
  last_updated: false
series:
  - entity: sensor.energiapankki_per_vartti
    transform: return x * 1000;
    unit: Wh
    type: column
    extend_to: now
    group_by:
      start_with_last: false
      func: last
      duration: 15min
    stroke_width: 4
```
I am totally lost and tried to get help with AI, but not getting any working solution.

**Comment by dbuezas** [comment]
You could try with:
```sql
filters:
  - derivate
  - filter: y>0
  - integrate:
        reset_every: 15m
```

**Comment by heebo1974** [comment]
I think I finally got it !!

Here is apex and plotly side by side comparison:
![image](https://github.com/user-attachments/assets/51007bbb-a13f-45ba-a040-23504ad6f0e8)

```
type: custom:plotly-graph
hours_to_show: 3h
refresh_interval: 10
autorange_after_scroll: true
entities:
  - entity: sensor.energy_bank_per_15_min
    type: bar
    time_offset: "-15m"
    filters:
      - resample: 15m
layout:
  height: 320
  xaxis:
    fixedrange: false
    nticks: 16
    tickformat: "%-H:%M"
    tickangle: -45
    range: $ex [new Date().setHours(6,30,0,0), new Date().setHours(20,0,0,0)]
  yaxis:
    title: ""
    fixedrange: true
    rangemode: tozero
    showgrid: true
    griddash: dot
    zeroline: true
    zerolinewidth: 1
    zerolinecolor: lightgray
config:
  scrollZoom: false

```
