### DISCUSSION TITLE
Bar chart one bar per year

### DISCUSSION THREAD

**Discussion by droidgren** [dbuezas/lovelace-plotly-graph-card#555] [Q&A]
Is it possible to make bar graph with one bar year in plotly? Like this (Apexchart)

![image](https://github.com/user-attachments/assets/3b2195fb-1a77-47c6-86c3-63ba049e5d3d)

I have tried but not succeed since the "period" field does not support year. 

Is it possible work around this limitation ?

**Comment by dbuezas** [comment]
Yes, you can do this combining the integration and resample filters:
Something like this:

```yaml
filters:
   - integrate:
        reset_every: 1y
        unit: y
   - resample: 1y
 ```

**Reply by droidgren** [reply]
I tried this:  but get nothing, did I miss something?

```
type: custom:plotly-graph
title: Yearly Power Consumption
entities:
  - entity: sensor.arets_elforbrukning_total
    type: bar
    name: Consumption
    filters:
       - integrate:
            reset_every: 1y
            unit: y
       - resample: 1y
layout:
  xaxis:
    title: Year
    tickformat: '%Y'
    rangemode: tozero 
  yaxis:
    title: Energy (kWh) # Adapt unit if necessary
    rangemode: tozero 
    autorange: true
```

**Reply by dbuezas** [reply]
You'll need to use the statistics table instead. Check 
https://github.com/dbuezas/lovelace-plotly-graph-card?tab=readme-ov-file#statistics-support

**Reply by hafnerra** [reply]
Can you give me a complete example please? I dont unterstand your note. I have utility meter with a yearly reset.
Thx for help!

**Reply by dbuezas** [reply]
Read that section, there are examples there

**Comment by droidgren** [comment]
I could not find any specific examples, that's why posted this thread in the first place.

I tried with the code below, which is not working. 
It is based on a Utility Meter which has data back from October 2024 and resets yearly
I get no totals for 2024 and wrong total for 2025, it should be something 13 000kWh for 2024 and 5000kWh for 2025
I have also another utility meter sensor that that resets every month and has data from 2023, and it also get wrong totals.
I have tried to change statistic: state -> statistic: sum, but still not correct totals. 

```
type: custom:plotly-graph
entities:
  - entity: sensor.manadens_forbrukning_total
    name: ""
    unit_of_measurement: kWh
    texttemplate: " %{y:.0f}"
    type: bar
    statistic: state
    filters:
      - integrate:
          reset_every: 1y
          unit: "y"
      - resample: 1y
hours_to_show: 36M
refresh_interval: 10
layout:
  xaxis:
    title: Year
    tickformat: "%Y"
    rangemode: tozero
  yaxis:
    title: Energy (kWh)
    rangemode: tozero
    autorange: true
```
![image](https://github.com/user-attachments/assets/b1bc6b9f-382b-4cbf-8428-6c4299b8f37c)
