### DISCUSSION TITLE
Complex buttons: input fields (date-chooser) and changing config values

### DISCUSSION THREAD

**Discussion by georgh** [dbuezas/lovelace-plotly-graph-card#558] [Q&A]
Hello 

I have problems getting buttons to work:

I would like to display informations for specific time ranges I can choose via some button/input field. Best would be something similar to the way the log is shown in HA. Is this possible with plotly? I only got it to work with fixed values like a week:

```
layout:
  dragmode: pan
  showlegend: true
  hovermode: x
  xaxis:
    tickfont:
      color: "#000000"
    rangeselector:
      "y": 0.9
      buttons:
        - count: 1
          step: day
          label: Day
        - count: 48
          step: hour
          label: 2 Days
          stepmode: backward
        - count: 7
          step: day
          label: Week
```

Is it possible to change filter configs based on button presses? I would love to change the resample value of my plot dynamicly.

Maybe someone can point me to additional documentation about buttons?

Thank you a lot for your help!
