### DISCUSSION TITLE
Adding latest value to graph title (& custom legend colours)

### DISCUSSION THREAD

**Discussion by CKerswell** [dbuezas/lovelace-plotly-graph-card#56] [Q&A] [answered]
I have a graph to show the current temperature and thermostat setpoint for a given room and I wanted to put the room name and current temperature at the top of the graph as a title:

![image](https://user-images.githubusercontent.com/70297519/175149009-bd144659-7753-4f6d-a63e-c4c04d9cbf21.png)

As you can see, I have achieve the goal, but I think in a very complicated way!
I could not see how to pull in an entity value to a text label, so instead I created a whole new entity and messed with the series formatting and axis values to position it where I wanted!

My question is, is there a better way to achieve what I am looking for that I have missed, and if not, is this a feature that others may also be interested in to add to the pot of future improvements?

```
type: custom:plotly-graph
entities:
  - entity: climate.loungetrv_climate::current_temperature
    name: °C
  - entity: climate.loungetrv_climate::temperature
    name: Target
  - entity: climate.loungetrv_climate
    showlegend: false
    show_value: false
    mode: text
    textfont:
      color: '#7f7f7f'
      size: 20
    texttemplate: 'Lounge: %{y:.1f}°C'
    yaxis: y2
    lambda: |-
      (ys, xs, entity) => {
      const result = {x:[], y:[]}
      result.y.push(+entity[ys.length-1].attributes.current_temperature)
      result.x.push(+(+xs[xs.length-1])-43200000)
      return result;
      }
hours_to_show: 24
refresh_interval: 10
layout:
  showlegend: true
  legend:
    'y': -0.12
  yaxis:
    range:
      - 8
      - 28
    tickmode: array
    tickvals:
      - 10
      - 12
      - 14
      - 16
      - 18
      - 20
      - 22
      - 24
      - 26
  yaxis2:
    visible: false
    range:
      - -500
      - 60
  xaxis:
    tickformat: '%H:%M'
```

**Comment by dbuezas** [comment, marked as answer]
Wow, that's extremely creative! Very impressive!

It would be super easy if jinja templates were supported in card yamls, but it doesn't seem like they are.
Therefore, I'm not aware of any easier way to achieve what you did.

**Reply by dbuezas** [reply]
You could use this: https://github.com/gadgetchnnel/lovelace-card-templater
And write:
```yaml
title: {{sensors.blahbla}}}
```

**Reply by CKerswell** [reply]
Thanks for the compliment, but your solution is much smarter!
Work smarter, not harder!!

For anyone else who is interested, here is the neater solution as suggested by David:

![image](https://user-images.githubusercontent.com/70297519/175422134-b6dd1605-6abb-4f42-9eec-d65e3794c7ea.png)

```
type: custom:card-templater
card:
  type: custom:plotly-graph
  entities:
    - entity: climate.loungetrv_climate::current_temperature
      name: °C
    - entity: climate.loungetrv_climate::temperature
      name: Target
  hours_to_show: 24
  refresh_interval: 10
  layout:
    showlegend: true
    legend:
      'y': -0.12
    title:
      text_template: >-
        Lounge: {{ state_attr("climate.loungetrv_climate","current_temperature")
        }}°C
      'y': 0.9
      font:
        size: 20
    yaxis:
      range:
        - 8
        - 28
      tickmode: array
      tickvals:
        - 10
        - 12
        - 14
        - 16
        - 18
        - 20
        - 22
        - 24
        - 26
    xaxis:
      tickformat: '%H:%M'
entity: climate.loungetrv_climate
```

**Reply by dbuezas** [reply]
Looks perfect 👍 
For reference, here's another alternative templatable card but based on JavaScript instead pf jinja2:
https://github.com/iantrich/config-template-card

**Reply by mdisabato** [reply]
Would this kind of thing work to change the color of the line based on a sensor value change?

Thanks.

**Reply by dbuezas** [reply]
In plotly, lines can have only one color

**Comment by AleXSR700** [comment]
Thank you for sharing :)
I was wondering if this could maybe be modified in a way that the value is formatted in the same color as the corresponding line?
I have a few graphs with multiple entities and I would like to have the current value matching the color of the line.
Kind of similar to this:
![image](https://user-images.githubusercontent.com/57034871/190536300-0151350b-9bcb-4772-bb86-a82d5ce8819e.png)

**Reply by CKerswell** [reply]
Hi, just had a quick look at this, I can't see any native way to match the test colour to the line colour...

However, if you are happy to specify both the line and text colour you could achieve this:
![image](https://user-images.githubusercontent.com/70297519/190712004-75537c86-7434-427d-9df8-c06f4095de8b.png)

like this:
```
type: custom:config-template-card
entities:
  - climate.kitchenmaintrv_climate
card:
  type: custom:plotly-graph
  entities:
    - entity: sensor.outside_environmental_temperature
      name: >-
        ${'<span style="color:red">Outside ' +
        states['sensor.outside_environmental_temperature'].state + '°C</span>'}
      line:
        width: 2
        color: '#666666'
        shape: spline
        dash: dash
    - entity: climate.kitchenmaintrv_climate::current_temperature
      name: >-
        ${'<span style="color:#00FFFF; font-weight:bold">' +
        states['climate.kitchenmaintrv_climate'].attributes.current_temperature
        + '°C</span> Kitchen'}
      line:
        width: 2
        color: '#00FFFF'
        shape: spline
  hours_to_show: 12
  refresh_interval: 10
  config:
    scrollZoom: false
    dragmode: false
    displayModeBar: false
  layout:
    showlegend: true
    legend:
      'y': -0.15
    margin:
      l: 30
      r: 30
      b: 0
      t: 5
    yaxis:
      dtick: 1
      title: ''
      rangemode: normal
    yaxis2:
      mirroraxis: true
      matches: 'y'
      dtick: 1
      title: ''
    xaxis:
      tickformat: '%H:%M'
      fixedrange: true
      dtick: 3600000
  defaults:
    yaxes:
      fixedrange: true

```

NB: I've started to prefer using https://github.com/iantrich/config-template-card as it seems more flexible and easier to accommodate this sort of thing.
