### DISCUSSION TITLE
Visible bars sum approach?

### DISCUSSION THREAD

**Discussion by PaTara43** [dbuezas/lovelace-plotly-graph-card#561] [Q&A] [answered]
Hello, community and thanks devs for the astonoshing card!

I have a bar chart (this is a bit complicated, basically, it's a bar chart of sums of other bars but anyway). My goal is to display somewhere a sum of all visible bars' values. And I want it to be updated on pan

E.g. here it would be 1,27 kWh
![image](https://github.com/user-attachments/assets/768e0573-836d-41aa-9057-a56acaf0a6e0)

Some of my understandings:

1. There is an annotation thing that can be placed anywhere on the graph. This will do
2. Chatbots told me there is some sort of events like `plotly_relayout` which I can track and trigger.
3. I can somehow use graphDiv to calculate the values of only those of visible bars

So, right now there is a mess in my head about all this and I'm fairly new to plotly and js. 

My questions are:

1. Is there a dedicated chapter in card setting for scripts? 
2. Is there a simple way to trigger this script on pan?
3. Can I use gd data in the script to calculate sum of visible bars? 
4. Can I also use this script to aupdate annotations?

Any clues would be appreciated!

**Comment by PaTara43** [comment]
One of my thoughts is that I can somehow reach graph data from an expression 
`text: $ex {return 123 }` 
replace 123 here with something like `this.layout.xaxis.range[0]` to begin with. But that doesn't work

**Comment by PaTara43** [comment, marked as answer]
Okay this turn out to be waaaaaaay easier

For the entity I'm interested in:

`fn: $ex vars.sum = ys.reduce((acc, val) => acc + val, 0);`

And then for the annotation text 
```
  annotations:
    - x: 1
      xref: paper
      "y": 1
      yref: paper
      showarrow: false
      text: $ex vars.sum
```

https://github.com/user-attachments/assets/a8ae43ad-35dd-4d83-bd0a-c6ee81b401f8

**Reply by dbuezas** [reply]
You can also make an indicator trace

```yaml
  - entity: ""
    type: indicator
    mode: number
    docs: https://plotly.com/javascript/reference/indicator/#indicator-number
    value: |
      $ex vars.sum.toFixed(2)
    color: green
    number:
      suffix: Wh
    domain:
      x:
        - 0.8
        - 1
      "y":
        - 0.7
        - 1
  ```
