### DISCUSSION TITLE
Scatter Graph - filter X value out

### DISCUSSION THREAD

**Discussion by luissimoes** [dbuezas/lovelace-plotly-graph-card#566] [Q&A] [answered]
Hi
I'm sure it is possible, but I didn't manage to make it work.

I have a scatter graph, and want that the X-AXIS only has a point where Y >0....
As I have the X Scale is weekly

My code (I want to control all the car charges where the energy charged is > 9 kWh, because I have a "stupid" wall box :-) )

thank You!
```
type: custom:plotly-graph
entities:
  - entity: sensor.from_netz_daily
    texttemplate: "%{x}<br>%{y:.2f}"
    textposition: top center
    textfont:
      size: 15
    name: car charges
    type: scatter
    mode: markers+text+lines
    statistic: state
    period: day
    line:
      width: 1
      dash: 3px
      shape: vhv
      color: "#C8CCCC"
    marker:
      color: "#FF5733"
      opacity: 1
      size: 15
      symbol: 215
      line:
        width: 1
        color: "#000000"
    filters:
      - filter: y > 9
layout:
  barmode: scatter
  paper_bgcolor: rgba(0,0,0,0)
  plot_bgcolor: rgba(0,0,0,0)
  margin:
    t: 25
    l: 15
  height: 450
  legend:
    "y": -0.25
    x: 0.15
  yaxis:
    visible: false
    title:
      font:
        size: 9
      text: total energy
  xaxis:
    fixedrange: false
    gridcolor: rgba(238,235,235,0.2)
    showgrid: false
    linecolor: null
    tickformat: "%d %b"
hours_to_show: 6w
refresh_interval: auto
title: 🚙 Car charges (> 9 kwh)
card_mod:
  style: |
    ha-card {
       font-size: 18px !important;
        --secondary-text-color: '#000000';
        border-width: 0px;
        padding-top: 30px
       }
view_layout:
  grid-area: view4
```
