### DISCUSSION TITLE
Different time_offset for different periods

### DISCUSSION THREAD

**Discussion by hendrik001973** [dbuezas/lovelace-plotly-graph-card#567] [General]
Hi,

I want to display the amount of rainfall in a plotly card.

I use following code:

```
type: custom:plotly-graph
layout:
  yaxis:
    fixedrange: true
  xaxis:
    showgrid: false
    ticklabelmode: period
entities:
  - entity: sensor.wetterstation_yearly_rain_piezo
    name: Niederschlag in mm
    type: bar
    statistic: state
    period:
      0s: hour
      5d: day
      2M: week
      6M: month
    time_offset: "-30m"
    filters:
      - derivate: h
      - filter: y > 0
hours_to_show: 48
```
I inserted the time offset, so that the bar is between the ticks.
The time_offset fits for the hourly period, however, for the daily period it should be -12h, for the weekly period -84h and so on
I tried this:
```
  time_offset:
    0s: -30m
    5d: -12h
    2M: -84h
    6M: -15d
```
but it is not accepted. Any ideas, how I can do this?

Greetings
Hendrik
