### DISCUSSION TITLE
How to get a cross-hair cursor?

### DISCUSSION THREAD

**Discussion by jazzmonger** [dbuezas/lovelace-plotly-graph-card#570] [General]
Is there a way to show a cross hair cursor? like this?  Possibly just an X or a Y? I often find it necessary.

![image](https://github.com/user-attachments/assets/4176891e-ba88-44f5-9b70-9fa4d7a798b6)

**Comment by dbuezas** [comment]
Hovermode x unified should help

**Comment by jazzmonger** [comment]
where?  I also saw this in a Plotly related post but have no idea where to put it.

```
fig.update_xaxes(showspikes=True, spikemode="across")
fig.update_yaxes(showspikes=True, spikemode="across")
```
Here's my config
```
type: custom:plotly-graph
refresh_interval: 2
hours_to_show: 0.25
entities:
  - entity: sensor.1_traeger_smoker_rtd_temperature
    name: RTD Temp
    yaxis: y1
    line:
      color: yellow
      shape: spline
      width: 3
      smoothing: 0
  - entity: number.1_traeger_smoker_smoker_set_temperature
    name: SET Temp
    yaxis: y1
    line:
      color: white
      shape: spline
      width: 1
      smoothing: 0
  - entity: number.1_traeger_smoker_pid_error_temp
    name: Error
    yaxis: y3
    line:
      color: white
      shape: spline
      width: 2
      smoothing: 0
  - entity: weather.wilder_id
    name: Outside temp
    attribute: temperature
    internal: false
    yaxis: y4
    line:
      color: grey
    smoothing: 1
  - entity: number.1_traeger_smoker_augers_heating_on_time
    unit_of_measurement: s
    name: Auger On Time
    internal: false
    yaxis: y2
    show_value: true
    line:
      color: red
      shape: spline
      width: 1
      smoothing: 0
  - entity: number.1_traeger_smoker_augers_heating_off_time
    unit_of_measurement: s
    name: Auger Off Time
    internal: false
    yaxis: y2
    show_value: true
    line:
      color: light grey
      shape: spline
      width: 1
      smoothing: 0
  - entity: sensor.1_traeger_smoker_firepot_temperature
    unit_of_measurement: F
    name: Burn Pot temp
    internal: false
    yaxis: y4
    show_value: true
    line:
      color: light red
      shape: spline
      width: 1
      smoothing: 0
defaults:
  entity:
    show_value: true
  yaxes:
    side: left
    overlaying: "y"
    visible: true
    showgrid: true
    fixedrange: true
layout:
  margin:
    r: 100
  annotations:
    - xref: paper
      yref: paper
      "y": 1.01
      text: RTD Meassured Temp vs Set Temp
      showarrow: false
    - xref: paper
      yref: paper
      "y": 0.77
      text: Auger 1 Time On vs Time Off
      showarrow: false
    - xref: paper
      yref: paper
      "y": 0.5
      text: RTD Temp Error
      showarrow: false
    - xref: paper
      yref: paper
      "y": 0.22
      text: Outside Temp & Firepot Temp
      showarrow: false
  grid:
    rows: 4
    columns: 1
    pattern: coupled
    roworder: top to bottom
  legend:
    x: 0
    title:
      text: Trager Controller
  xaxis:
    rangeselector:
      bgcolor: "#474747"
      "y": 1.06
      buttons:
        - count: 15
          step: minute
        - count: 30
          step: minute
        - count: 1
          step: hour
        - count: 2
          step: hour
        - count: 3
          step: hour
        - count: 12
          step: hour
  yaxis:
    visible: true
    fixedrange: true
  yaxis2:
    visible: true
    fixedrange: true
    domain:
      - 0
      - 0
  yaxis3:
    visible: true
    fixedrange: true
  yaxis4:
    visible: true
    fixedrange: true
  height: 800
autorange_after_scroll: true
```
