### DISCUSSION TITLE
Repeat X Axis and Separate Legends in Subplots

### DISCUSSION THREAD

**Discussion by thisIsLiving** [dbuezas/lovelace-plotly-graph-card#572] [Q&A]
Is it possible to repeat the x-axis legend in each subplot? I'm planning to add a number of other stats which require locking of the x-axis between graphs as I scroll around. And with the number of plots it's too hard to figure out what the times are in the top plot if you have to scroll down to the bottom plot.

Also can you move the legend for each line down to the respective plot instead of all being up at the top plot?

![image](https://github.com/user-attachments/assets/d8fdce37-bdb3-4dd9-bca0-f67398ca0cd1)

Also is it possible to have the current values formatted to have a comma separating out the thousands?

![image](https://github.com/user-attachments/assets/c2a1a659-84b0-48aa-a0fc-0ffc2d597a9a)

For anyone who's interested below is the code I've used for my PV and battery system:

```
type: custom:plotly-graph
entities:
  - entity: sensor.goodwe_battery_power
    name: Battery
    legendgroup: "1"
  - entity: sensor.goodwe_pv_power
    name: PV
    legendgroup: "1"
  - entity: sensor.goodwe_meter_active_power_total
    name: Grid
    legendgroup: "1"
  - entity: sensor.goodwe_back_up_load
    name: Load
    legendgroup: "1"
  - entity: sensor.goodwe_house_consumption
    name: Load + Inverter
    legendgroup: "1"
  - entity: sensor.goodwe_battery_state_of_charge
    legendgroup: "2"
    line:
      color: 1f77b4
layout:
  dragmode: pan
  height: 800
  grid:
    rows: 2
    columns: 1
    roworder: top to bottom
  legend:
    x: 0
    "y": 1
    orientation: h
    itemsizing: constant
    font:
      size: 10
  annotations:
    - xref: paper
      yref: paper
      "y": 1
      text: ""
      showarrow: false
    - xref: paper
      yref: paper
      "y": 0.5
      text: Battery SoC
      showarrow: false
  xaxis:
    rangeselector:
      "y": 1.2
      buttons:
        - count: 30
          step: minute
        - count: 1
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 3
          step: day
  yaxis:
    tickformat: ",.0f"
  yaxis2:
    range:
      - 0
      - 100
defaults:
  entity:
    show_value: true
    line:
      width: 1.5
  yaxes:
    side: left
    overlaying: false
    visible: true
    showgrid: true
    fixedrange: true
autorange_after_scroll: true
hours_to_show: 24

```
And here's the code to get the daily values from a cumulative sensor:

![image](https://github.com/user-attachments/assets/41dd9930-6094-4b1f-9fc8-502405c52cbc)
```
type: custom:plotly-graph
title: Daily Export
entities:
  - entity: sensor.goodwe_meter_total_energy_export
    statistic: sum
    period: day
    filters:
      - delta
    type: bar
layout:
  barcornerradius: 3.5
  dragmode: pan
  height: 400
  xaxis:
    rangeselector:
      "y": 1.2
      buttons:
        - count: 1
          step: month
        - count: 3
          step: month
        - count: 6
          step: month
        - count: 12
          step: month
  yaxis:
    title:
      text: kWh
defaults:
  yaxes:
    fixedrange: true
autorange_after_scroll: true
hours_to_show: 3M

```
