### DISCUSSION TITLE
Disable hover and annotation text not visible

### DISCUSSION THREAD

**Discussion by VBA-N7** [dbuezas/lovelace-plotly-graph-card#575] [Q&A]
Hi guys, 
I'm trying to plot a minimalist line graph, i'm close to finish. 
The goal is to display the next 24h temperature forecast and annotate the maximum and the minimum tempereture for the next 24h. 

My first problem is: i cannot disable the hover info. Even with `hoverinfo: "skip"` or `hoverinfo: "none"`
And my second problem is that the text for the maximum and the minimum is not displayed. The marker is visible but not the text. 
What am I doing wrong ?

Thanks for your help ! 

![image](https://github.com/user-attachments/assets/dcdc2f8f-4217-47d0-8d1c-93085a172417)

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.weather_hourly
    attribute: forecast
    filters:
      - fn: |-
          ({states}) => {
                  const forecast = states[0]?.attributes?.forecast || [];
                  return {
                          xs: forecast.map(f => new Date(f.datetime)),
                          ys: forecast.map(f => f.temperature),
                          meta: { unit_of_measurement: '°C' },
                  };
          }
    line:
      color: orange
      width: 2
      shape: spline
    
  - entity: sensor.weather_hourly
    attribute: forecast
    filters:
      - fn: |-
          ({states}) => {
            const forecast = states[0]?.attributes?.forecast || [];
            const now = new Date();
            const next24h = new Date(now.getTime() + 24 * 60 * 60 * 1000);
            const limited = forecast.filter(f => {
              const dt = new Date(f.datetime);
              return dt >= now && dt <= next24h;
            });
            if (limited.length === 0) return null;
            const maxPoint = limited.reduce((a, b) => a.temperature > b.temperature ? a : b);
            return {
              xs: [new Date(maxPoint.datetime)],
              ys: [maxPoint.temperature],
              text: [`MAX: ${maxPoint.temperature.toFixed(1)} °C`],
              hoverinfo: 'text',
              meta: { unit_of_measurement: '°C' },
            };
          }
    type: scatter
    mode: markers+text
    marker:
      color: dodgerblue
      size: 10
    textposition: top center
    line:
      width: 0
  - entity: sensor.weather_hourly
    attribute: forecast
    filters:
      - fn: |-
          ({states}) => {
            const forecast = states[0]?.attributes?.forecast || [];
            const now = new Date();
            const next24h = new Date(now.getTime() + 24 * 60 * 60 * 1000);
            const limited = forecast.filter(f => {
              const dt = new Date(f.datetime);
              return dt >= now && dt <= next24h;
            });
            if (limited.length === 0) return null;
            const minPoint = limited.reduce((a, b) => a.temperature < b.temperature ? a : b);
            return {
              xs: [new Date(minPoint.datetime)],
              ys: [minPoint.temperature],
              text: [`MIN: ${minPoint.temperature.toFixed(1)} °C`],
              hoverinfo: 'text',
              meta: { unit_of_measurement: '°C' },
            };
          }
    type: scatter
    mode: markers+text
    marker:
      color: orange
      size: 10
    textposition: bottom center
    line:
      width: 0
hours_to_show: 1d
time_offset: 1d
config:
  displayModeBar: false
defaults:
  yaxes:
    fixedrange: true
  entity:
    showlegend: false
layout:
  xaxis:
    visible: false
  yaxis:
    visible: false
```
