### DISCUSSION TITLE
BSH Gezeiten(Tide) Home Assistant based implementation

### DISCUSSION THREAD

**Discussion by sgmobiledev** [dbuezas/lovelace-plotly-graph-card#576] [Show and tell]
Hi have implemented follow ploty in ha:

![image](https://github.com/user-attachments/assets/73430e35-bb2c-4940-bcaf-38bbcd446efc)

after 20 hours implementation, i become not what i won't. This is the follow chart from the website of bsh.

![image](https://github.com/user-attachments/assets/795f7947-c5f7-4239-8e0c-e8f2ddaab935)

My Sourcecode ist the following:

```yaml
type: custom:plotly-graph
title: Gezeiten HH St. Pauli (Elbe) – Pegel in Meter
entities:
  - entity: sensor.mittleres_hochwasser_in_m
    name: MHW
    line:
      color: darkgreen
      width: 2
    yaxis: "y"
    valueformat: .2f
  - entity: sensor.abweichung_hochwasser_in_m
    name: Abw. Hochwasser
    line:
      color: lightgreen
      dash: dot
    yaxis: "y"
    valueformat: .2f
  - entity: sensor.mittleres_niedrigwasser_in_m
    name: MNW
    line:
      color: darkred
      width: 2
    yaxis: "y"
    valueformat: .2f
  - entity: sensor.abweichung_niedrigwasser_in_m
    name: Abw. Niedrigwasser
    line:
      color: lightcoral
      dash: dot
      shape: spline
    //fill: tonexty
    yaxis: "y"
    valueformat: .2f
  - entity: sensor.pegelstand_hochwasser_in_m
    name: Hochwasser
    line:
      color: blue
      width: 1
    yaxis: "y"
    valueformat: .2f
  - entity: sensor.pegelstand_niedrigwasser_in_m
    name: Niedrigwasser
    line:
      color: blue
      width: 1
    yaxis: "y"
    valueformat: .2f
refresh_interval: 4h
days_to_show: 7
shape: spline
layout:
  legend:
    orientation: h
    "y": -0.3
    x: 0.5
    xanchor: center
    yanchor: top
    traceorder: normal
    font:
      size: 12
    bordercolor: black
    borderwidth: 1
    bgcolor: rgba(18, 31, 13, 0.8)
    itemwidth: 0
  xaxis:
    rangeselector:
      "y": 1.2
      buttons:
        - count: 7
          step: day
          label: 7d
          stepmode: forward
  yaxis:
    title: Höhe über gelnullpunkt in M
```

Is there a way to structure this chart like the one on the BSH website?

I would be very grateful for any help.

Thanks very much, Sebastian

**Comment by dbuezas** [comment]
`days_to_show: 7` is wrong 

It should be `hours_to_show: 7d`

**Reply by sgmobiledev** [reply]
Thanks @dbuezas , it is better view but not curved and i want the abweichungen under the middle tide but i dot know how can i to do in my yaml configuration. do you have an tip do show me a way to my dream:-)

**Reply by dbuezas** [reply]
Sorry I don't understand what that means.

**Reply by sgmobiledev** [reply]
No Problem, i mean the chartlines are noch curve(spline i.m) and i want sensor.abweichung_niedrigwasser_in_m shows under sensor.pegelstand_niedrigwasser_in_m it is difference value

**Reply by dbuezas** [reply]
Schreib's auf deutsch

**Reply by sgmobiledev** [reply]
ok ist einfacher ich würde gerne eine Darstellung wie in dem BSH Beispiel mit Plotly machen also Kurvenzeige und die Differenz Entitäten an Hochwasser bzw. Niedrigwasser angleichen weil das ja nur die Diffenzen sind. Leider habe ich das nicht hinbekommen.

**Reply by dbuezas** [reply]
Ok, I think you want to show a trace with the difference between 2 entities.
To do that you need to do something like this:
```yaml
entities:
   - entity: sensor.min
     internal: true
     filters:
        - resample: 1h
        - store_var: min
   - entity: sensor.max
      filters:
         - resample: 1h
         - map_y: y - vars.min.ys[i]
```
