### DISCUSSION TITLE
Stacking area odd behaviour - crashing to zero

### DISCUSSION THREAD

**Discussion by deltamelter** [dbuezas/lovelace-plotly-graph-card#577] [Q&A]
I am trying to show a stacked total area for 2 solar outputs but for some reason when stacked the same 2 entities take turns to be zero,  the image here show that neither is actually zero, is this some kind of refresh rate/redraw issue?
![newplot (23)](https://github.com/user-attachments/assets/0aaa2cfa-5e4c-4e5b-869e-492a9831bd8f)

```
type: custom:plotly-graph
entities:
  - entity: sensor.powerstream_0801_solar_1_watts
    yaxis: "y"
    fill: tonexty
    stackgroup: stacked
  - entity: sensor.powerstream_0801_solar_2_watts
    yaxis: "y"
    fill: tonexty
    stackgroup: stacked
  - entity: sensor.powerstream_0801_solar_1_watts
    yaxis: y6
    fill: tozeroy
  - entity: sensor.powerstream_0801_solar_2_watts
    yaxis: y7
    fill: tozeroy
  - entity: sensor.solcast_pv_forecast_forecast_today
    name: Solcast estimate
    type: bar
    offset: 0
    width: 1750000
    marker:
      color: rgba(255, 255, 0, 0.3)
      line:
        color: rgba(0, 255,128, 1)
        width: 0
    filters:
      - multiply: 0.001
      - fn: |-
          (
          { meta }) => ({          
            xs: meta.detailedForecast.map(({ period_start }) => period_start),
            ys: meta.detailedForecast.map(({ pv_estimate  }) => pv_estimate*900) 
          })     
    yaxis: "y"
  - entity: sensor.solcast_pv_forecast_forecast_today
    name: Solcast 10%
    type: bar
    offset: 0
    width: 1750000
    marker:
      color: rgba(255, 255, 0, 0.3)
      line:
        color: rgba(0, 255,128, 1)
        width: 0
    filters:
      - multiply: 0.001
      - fn: |-
          (
          { meta }) => ({          
            xs: meta.detailedForecast.map(({ period_start }) => period_start),
            ys: meta.detailedForecast.map(({ pv_estimate10  }) => pv_estimate10*900) 
          })     
    yaxis: "y"
  - entity: sensor.solcast_pv_forecast_forecast_today
    name: Solcast 90%
    type: bar
    offset: 0
    width: 1750000
    marker:
      color: rgba(255, 255, 0, 0.2)
      line:
        color: rgba(0, 255,128, 1)
        width: 0
    filters:
      - multiply: 0.001
      - fn: |-
          (
          { meta }) => ({          
            xs: meta.detailedForecast.map(({ period_start }) => period_start),
            ys: meta.detailedForecast.map(({ pv_estimate90  }) => pv_estimate90*900) 
          })     
    yaxis: "y"

  - entity: ""
    name: Now
    yaxis: y5
    showlegend: false
    showvalue: "no"
    stackgroup: null
    line:
      width: 1
      dash: dot
    x: $fn () => [Date.now(), Date.now()]
    "y": $fn () => [0,18]
layout:
  height: 800
  yaxis:
    fixedrange: true
    title: Solar W
    domain:
      - 0.55
      - 1
  yaxis5:
    fixedrange: true
  yaxis6:
    fixedrange: true
    title: Solar 1 W
    visible: true
    domain:
      - 0.25
      - 0.5
    overlaying: y6
  yaxis7:
    fixedrange: true
    title: Solar 2 W
    visible: true
    domain:
      - 0
      - 0.25
    overlaying: y7
  hovermode: x unified
  shapes:
    - type: line
      texttemplate: NOW
      x0: $ex Date.now()
      x1: $ex Date.now()
      y0: 0
      y1: 0.5
      xref: x
      yref: paper
      line:
        width: 1
        dash: dot
        color: blue
refresh_interval: 10
title: Solar
grid_options:
  columns: full
logarithmic_scale: false
hours_to_show: current_day
time_offset: 5h
config:
  modeBarButtonsToRemove:
    - resetScale2d
    - lasso2d
    - select2d

```
