### DISCUSSION TITLE
Binary order flipping

### DISCUSSION THREAD

**Discussion by aburow** [dbuezas/lovelace-plotly-graph-card#62] [Q&A] [answered]
EDIT NOTE: This is not the answer to solving this - the issue persisted.

I am tracking two binary sensors, a fan and a motion sensor for a pet toileting area.
I would normally expect the graph to show "on [1]" at the top and "off [0]" at the bottom.
Quite often this value flips the on and off for the y-axis until the page is reloaded.
Is there a way to prevent this? Is this a potential bug?

![image](https://user-images.githubusercontent.com/5871716/182336478-e6d9dcae-0c7a-4d53-897a-14e19ab47d3e.png)

```
 type: custom:plotly-graph
 entities:
   - entity: binary_sensor.kitties_occupancy
   - entity: fan.pet_fan
 hours_to_show: 12
 refresh_interval: 10
 layout:
   height: 400
   dragmode: pan
   yaxis:
     fixedrange: true 
```

**Comment by aburow** [comment, marked as answer]
Noted another person having issues with fixedrange and noted they had additional range values in the mix. This prompted me to give the range directive a try with upper and lower values of on and off in top down order on the graph.

These values need to be in the correct order in order to display as expected.

```
type: custom:plotly-graph
entities:
  - entity: binary_sensor.kitties_occupancy
  - entity: fan.pet_fan
hours_to_show: 12
refresh_interval: 10
layout:
  height: 400
  dragmode: pan
  yaxis:
    range:
      - 'on'
      - 'off'

```

**Reply by Tommatheussen** [reply]
Does this solution still work for you? I can't to get this to work, it just takes over the first values it sees from the entities

**Comment by aburow** [comment]
No, I’m starting to ignore it because it’s frustrated me. Not the best way to help point out an ongoing issue - but that’s where I’m at with it.On 13 May 2025, at 7:16 pm, Tom Matheussen ***@***.***> wrote:﻿
Does this solution still work for you? I can't to get this to work, it just takes over the first values it sees from the entities

**Comment by dbuezas** [comment]
Try with this:
```yaml
layout:
  yaxis:
    categoryorder: array
    categoryarray: ['off', 'on']
  
```

**Reply by aburow** [reply]
Thank you. I've implemented on 2 graphs and will check... seems legit  :)

**Reply by Tommatheussen** [reply]
Thanks! That does seem to work perfect for me!

**Comment by rvplan** [comment]
Hello,
Sorry to bring back this discussion, but actually, the different solutions proposed aren't working in my plotly graphs...
I have 2 graphs showing temperatures and a switch. When difference of temperatures are ok, switch activate.
I also expect the graph to show "on [1]" at the top and "off [0]" at the bottom.
In fact whatever the position of the "on" and "off", but at least consistent through all the graphs.

Here follows the simplest code for left and right graphs.
And the resulting drawing, where you can see inversion in "on/off".

I've tried both correction syntaxes proposed, no ones work...

Another solution to force positioning is to cheat with this filter:
```
filters:
      - map_y: |- 
          y === "on" ? 1 : 0
```

BTW Editor corrects this code:
```
layout:
  yaxis:
    categoryorder: array
    categoryarray: ['off', 'on']
```
Into this:
```
layout:
  yaxis:
    categoryorder: array
    categoryarray:
      - "off"
      - "on"
```
```
type: custom:plotly-graph
hours_to_show: 18
refresh_interval: 1m
entities:
  - entity: sensor.capzbtemp_09_temperature
    name: Temp. Grenier
  - entity: sensor.nbre_rdc_temp_moyenne
    name: Temp. Moy. RdC
  - entity: binary_sensor.seuil_temp_ventil_grenier_rdc
    name: Ventil. vers RdC
```
```
type: custom:plotly-graph
hours_to_show: 18
refresh_interval: 1m
entities:
  - entity: sensor.capzbtemp_09_temperature
    name: Temp. Grenier
  - entity: sensor.nbre_ssol_temp_moyenne
    name: Temp. Moy. Ssol
  - entity: binary_sensor.seuil_temp_ventil_grenier_ssol
    name: Ventil. vers SSol
```

<img width="1062" height="338" alt="Capture d’écran 2026-04-04 à 14 31 51" src="https://github.com/user-attachments/assets/57a4801a-22e0-4f79-ba8a-3e1088d70529" />
