### DISCUSSION TITLE
How to convert a sensor on-the-fly from date to delta t

### DISCUSSION THREAD

**Discussion by AleXSR700** [dbuezas/lovelace-plotly-graph-card#70] [Q&A] [answered]
Hello everyone,
I am enjoying playing with plotly and I would like to transform a date sensor (last restart time) to a delta t (uptime).

I thought I could use `lambda` but I think my ayntax is not quite right yet.
```
type: custom:plotly-graph
entities:
  - entity: sensor.esp32_wroom_32d_devkitc_v4_1_last_restart_time
    lambda: (ys) => ys.map(y => now().timestamp - y)
```
Essentially the current time minus the sensors value should result in an uptime in seconds.

Could anybody help me understand where I am going wrong?

Thank you
Alex

P.S.: In case David is reading this, I think the indentation on the lambda example is off. At least they were showing bad indentation when I tried to start with them as templates.

-----------------------
Edit:
All credit to @dbuezas who solved the issue and explained my errors in the following posts. Please read if you are a noob like me. 😉 
The solution is
```
type: custom:plotly-graph
entities:
  - entity: sensor.esp32_wroom_32d_devkitc_v4_1_last_restart_time
    line:
       shape: linear
    lambda: (ys,xs) => ys.map(((y,i) => (xs[i] - Date.parse(y))/1000)); #updated!
    unit_of_measurement: s
```

**Comment by dbuezas** [comment]
Try with: 
```js
 (ys) => ys.map(y => Date.now() - new Date(y))
```
You can check the js logs by opening the "dev console" in the browser. Makes easy to spot syntax errors and what not.

By the way, https://esphome.io/components/sensor/uptime.html

Thanks for noting the indentation error. I'll check it out soon. Can you point me to the exact example?

**Reply by AleXSR700** [reply]
Ah, I am watching NFL and ploting on my phone, so no developer tools. But I will try it also tomorrow with the dev tools.

The graph is now plotting but the data is not correct.
![Screenshot_20220911-232903_Home Assistant.jpg](https://user-images.githubusercontent.com/57034871/189549621-7c8aff41-d714-461c-a0cf-70a7fd0fc535.jpg)

I do have a sensor template using the previous code (so using the now().timestamp.
Is maybe the date() assuming a different input format or something?
What does the "new" do?

The current state is ```2022-09-11T12:05:40+00:00```.


Indentation is off in these examples:
From https://github.com/dbuezas/lovelace-plotly-graph-card#normalisation-wrt-to-last
to https://github.com/dbuezas/lovelace-plotly-graph-card#right-hand-riemann-integration

**Reply by AleXSR700** [reply]
I cannot edit anymore, but it seems that after a few minutes the graph changed and now seems to be showing large values.
Not sure what the unit is. Is it ms or something?

But again, a constant value which does not make sense in a delta t value.
![Screenshot_20220911-234928_Home Assistant.jpg](https://user-images.githubusercontent.com/57034871/189550314-7905fdb6-d7e5-405a-8b77-2c3e2d8476cc.jpg)

Strange ...

**Reply by AleXSR700** [reply]
Template code for sensor I was using:
state: "{{ now().timestamp - states('sensor.last_restart_time')|as_timestamp(0) }}"

**Reply by dbuezas** [reply]
Indentation fixed now. Thanks again.

With respect to lambdas, those are javascript and not python, that's why `now().timestamp` can't be used.

Also, the "new" keyword in javascript is used to create new objects. I thought this would work when combined with the subtractions because js casts dates to milliseconds. 

In any case, I now see that the date format needs to be parsed differently, try this one instead:

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.esp32_wroom_32d_devkitc_v4_1_last_restart_time
    lambda: (ys) => ys.map((y => Date.now() - Date.parse(y))/1000)
    unit_of_measurement: s


```

**Reply by AleXSR700** [reply]
It is comforting to see that would seem simple is sometimes not that simple even for absolute pros :-)

The new parse approsch does not quite fix it.
Now the values are no longer in milliseconds.
![Screenshot_20220912-151552_Home Assistant.jpg](https://user-images.githubusercontent.com/57034871/189664551-2ec66450-5199-44e7-b766-01f66bb9764d.jpg)

I had previsouly already divided by 1000 and fount that the value is then more reasonable, but like now, it is plotting a constant value and not an increasing slope.
Is this calculation maybe only being applied to the last data point or something like that?

**Reply by dbuezas** [reply]
It is applied to each value, I don't see anything wrong with the lambda 🤔 

The thing is that the "last_restart_time" will only be updated once per restart. Try to zoom out a lot in the x axis (you can zoom out and the click the autoscale button)
<img width="127" alt="image" src="https://user-images.githubusercontent.com/777196/189668396-cb936d00-c7aa-4ec0-8fa8-71917cdb89ab.png">

What exactly are you aiming at?
If you want something like an uptime plot, try this:
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.esp32_wroom_32d_devkitc_v4_1_last_restart_time
    line:
       shape: linear
    lambda: (ys,xs) => ys.map(((y,i) => (xs[i] - Date.parse(y))/1000)); #updated!
    unit_of_measurement: s
```

**Reply by AleXSR700** [reply]
Yes, I am trying to create a delta time, so an uptime sensor.
the last_restart_time will of course be constant for a long time (until the device restarts), so the value that is changing is of course the date.now()

So it should create a line with a constant slope (depending on the ratio between yaxis in seconds and xaxis in hours, days or whatever).

**Reply by dbuezas** [reply]
Got it.

Then you need to subtract the x axis, not Date.now() (or the python equivalent of now().timestamp). That will work in a template sensor because the value of "now" is stored in the db as time passes, but if you do that while plotting, then "now" is... well... now... for all datapoints :) 
Try the yaml I sent above, it should do what you need

**Reply by AleXSR700** [reply]
Thank you for the explanation!
I tried your code but it is still a horizontal line (even after autoscale) and the y-axis is formatted as a date and not a number. If the value was being transformed to a number, the y-axis would automatically switch to number, correct?

**Reply by dbuezas** [reply]
oh, missed a parenthesis, try it again (I updated it)

**Reply by AleXSR700** [reply]
That's it, that's it! You solved it!
**Thank you so so much!**

**Comment by dbuezas** [comment, marked as answer]
Solution:
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.esp32_wroom_32d_devkitc_v4_1_last_restart_time
    lambda: (ys) => ys.map((y => Date.now() - Date.parse(y))/1000)
    unit_of_measurement: s
```
