### DISCUSSION TITLE
Resetting "LegendOnly" Entities to YAML Defaults

### DISCUSSION THREAD

**Discussion by JTertin** [dbuezas/lovelace-plotly-graph-card#71] [Ideas]
I have a swell chart set up that uses the `visible: legendonly` property on several entities, which allows me to add several pens and have them default "disabled" (hidden from graph) when the dashboard opens, but still give the option of enabling them by clicking on the legend item.

Example:

```
entities:
  - entity: sensor.main_power_monitor_123_1min
    name: Main Power
    fillcolor: rgba(76,120,168,.2)
    line:
      color: rgb(76,120,168)
  - entity: sensor.main_power_monitor_balance_1min
    name: Balance Power
    line:
      color: rgb(245, 133, 24)
    fillcolor: rgba(245, 133, 24,.1)
  - entity: sensor.addison_room_bath_lights_b6_12_1min
    name: Addison
    visible: legendonly
  - entity: sensor.basement_b18_16_1min
    name: Gracie/Ivy
    visible: legendonly
...
```

![image](https://user-images.githubusercontent.com/13434665/190492564-0061d527-435f-4f64-8708-5f0cdcb0d421.png)

However, when I click the "reset" button, it sets all of the traces to 'visible' rather than reverting to what is defined in the YAML.  Would be swell if it would revert to the YAML settings so traces set as "legendonly" were re-hidden when the chart is reset.

Overall a fantastic add-in!
