### DISCUSSION TITLE
Mimic statistics-graph, add min/max/mean aggregation

### DISCUSSION THREAD

**Discussion by r-jean-pierre** [dbuezas/lovelace-plotly-graph-card#75] [Q&A]
Dear all,

I discovered recently this custom:plotly-graph. I would like to "replicate" what statistics-graph is able to do by displaying min/mean/max of a sensor. As the final result is quite beautiful, there is no way to really tweak statistics-graph or to have an hand on how statistics are computed.

Here is where I am:
![2022-10-10 00_08_28-YAML Dashboard – Home Assistant](https://user-images.githubusercontent.com/9727894/194781737-4f0320b0-3859-4a14-b5df-92491b77d59f.png)

Obviously I used the trick 
`line: 
          shape: spline`
to smooth a bit the original raw data on the bottom plotly graph, but how to really control an aggregation such as min/mean/max over 8H without too much pain :-) as in the top graph?

I already saw a piece of code to average over M minutes, but it seems tricky (or probably not sustainable) and doesn't compute well for first & last valuers of the time series (well, maybe for that part it's just because I'm not good in coding/maths :-) )
Anyhow, it will required to code min & max and add to any sensor and handle may degenerate cases 

Any magic command to do it without an headache and a 10MB yaml file?

Thanks!

**Comment by FrnchFrgg** [comment]
I just filed #77 to have long-term statistics support, because the vanilla statistics graph card does not compute nor aggregate this data but relies on the backend statistics.

**Comment by dbuezas** [comment]
Yeah, I guess I'll have to sooner or later bite the bullet and implement both pre-made filters and long term statistics support.
I think the latter is not that easy, so I need to first motivate myself to do it. In that regard, what is it that you use the long statistics so much for? If I miss it myself, I'm more likely to get to it :)

**Reply by FrnchFrgg** [reply]
I plot longer-term daily mean temperature for my swimming pool. I also plot a 4 day history of air temperatures both inside and outside, and 1-hour mean statistics is totally enough for those.

Last but not least, I have an auto-entities card listing all my device batteries with a popup graph that plots the value over at least 6 months. This enables forecasting how long they will last and 10-15 days of history for such slowly changing percentages is just not going to cut it.

Note that I don't think that fetching and handling statistics is hard. I even wrote some javascript doing exactly that for `apexcharts-card` which passes the `hass` object to its equivalent of your `lambda` because even though it supports long-term statistics, its filtering system works point-wise which is too limited to compute local extrema.

See the link given in #77 from which I derived a MWE.

**Reply by FrnchFrgg** [reply]
See https://community-assets.home-assistant.io/original/4X/7/4/5/745adea2c86b8020e1d8458a0231952474f8e20c.png for a look of my air temp history with local extrema (yes, `apexcharts` smoothing is horrendous because it creates horizontal tangents at every point so I even disabled it and live with straight-line interpolation now)

**Reply by r-jean-pierre** [reply]
Your last graph is already great as besides my question about "aggregation", I also wanted to display a text on min/max value on the line itself.  It even seems that you were able to display local extremum on your green line, how did you do that?

**Reply by FrnchFrgg** [reply]
This is not `lovelace-plotly-graph-card` but `apexcharts-card`. If `lovelace-plotly-graph-card` is able to display individual points with values for series, then it is a matter of correctly decimating the list of points to only keep local extrema in the `lambda` transform. I'll post a show and tell or a pull request for the readme once I have investigated further (I am totally new to this card, hoping to transition from `apexcharts` to `plotly`). Note that this *will* probably mean a somewhat big lambda and thus a big YAML definition (not more than the derivative or Riemann examples but probably as big).

**Reply by r-jean-pierre** [reply]
Okay nice, I started to be jealous to not be able to replicate it. 
I also played with apexcharts-card, it has also cool stuff, and aggregates easily, but at some point, I could find "one line ticks" in other cards that are also missing in apex. I'm still looking for the holy grail with one unique component to do everything I want :) 
Besides, I played with plotly directly in python, then I have to recognize that if the coder do the statistical job and store computations and intermediate results in a dataframe, then the magic of plotly appears :). If you do the maths yourself, it's as fancy as seaborn or other similar libs. Unfortunately I doubt it could be transposed as easily as in a flat yaml file in HA...

**Reply by FrnchFrgg** [reply]
`apexcharts-card` is the first (and only, as far as I know, until my PR is merged) third-party graph card supporting long term statistics. That is why I used it. But it is sometimes overly complex to do simple stuff (like adding a vertical grid), and its filtering system equivalent to `lambda` is not able to "see" the set of points as a whole.

**Comment by FrnchFrgg** [comment]
@r-jean-pierre plotly now can fetch long-term statistics for you to play with.

**Reply by r-jean-pierre** [reply]
This is wonderful, I'm gonna test!

**Reply by dbuezas** [reply]
It is! And @FrnchFrgg made that possible!

**Reply by FrnchFrgg** [reply]
I only wrote a proof of concept and most of the real work was done by @dbuezas including the much better way to configure attributes.

**Comment by r-jean-pierre** [comment]
So I played with it and it's exactly what I expected!
Great job!

Here is where I am:
![2022-10-26 21_22_49-](https://user-images.githubusercontent.com/9727894/198118070-2983209f-cc8a-4409-bc05-43ee1d5a2d91.png)

On the left the new statistic of plotly-graph (min-mean-max), and on right the statistics-graph component
Although I need to put some efforts on tiny cosmetic, I think the look&feel and the functionalities of plotly-graph are more suitable for me. I will also see if I can drop some apex-charts and other graph components i used in order to focus only on plotly-graph

Again: a huge "thank you!"

**Reply by dbuezas** [reply]
Oh, looks quite good already!
I'll have to work around how plotly handles the title thing at some point. In the meanwhile, you can use:

```
layout:
 margin:
    t: 100
```

**Reply by FrnchFrgg** [reply]
You know that `plotly` can fill-in the space between the min and max as the statistics graph does, by defining them next to each other (or perhaps setting integer order information) and using https://plotly.com/javascript/reference/scatter/#scatter-fill with the value `tonexty`.

**Reply by r-jean-pierre** [reply]
Hi,

I "knew" it because I saw it somewhere and then I tried to use this feature but unfortunately, after many possible combinations etc. it seems I can only fill a curve like if the parameter is set to tonext**x** and not tonext**y**. If the entity is the last one, then it behaves as a to**zeroy**. Did I miss something?

I tried in a python cmdline, using the documentation https://plotly.com/python/filled-area-plots/, section "Interior Filling for Area Chart" , and this works

By any chance, do you have an example in HA-yaml?

**Reply by FrnchFrgg** [reply]
I tried with the "Try it on CodePen" button of the first example here https://plotly.com/javascript/line-charts/#basic-line-plot by adding `fill: 'tonexty'` to `trace2` and it works here. In HA, adding `fill: tonexty` at the same level as the `entity` works here and links with the previous entity in the yaml list. Warning: AFAICT it links to the previous one that is enabled. If you disable it in the legend then it links to the previous one and so on.

**Reply by dbuezas** [reply]
As you say, that's the gotcha: tonexty actually fills to the previous trace, not the next one.

**Reply by r-jean-pierre** [reply]
> Oh, looks quite good already! I'll have to work around how plotly handles the title thing at some point. In the meanwhile, you can use:
> 
> ```
> layout:
>  margin:
>     t: 100
> ```

Yes, you right, in fact, if I don't want the title to stick the legend, I need a huge t:100, but it also increases the blank margin between the top of the card and the upper part of the title text:
Here is an example with t:80
![2022-10-27 11_11_03-YAML Dashboard – Home Assistant](https://user-images.githubusercontent.com/9727894/198243592-c2f6dd85-976f-4865-984f-6cb86182e6d1.png)
It's visually better, but it eats my space in the vertical axis
I also presume the legend has something to do with all the v-spaces

**Reply by r-jean-pierre** [reply]
> I tried with the "Try it on CodePen" button of the first example here https://plotly.com/javascript/line-charts/#basic-line-plot by adding `fill: 'tonexty'` to `trace2` and it works here. In HA, adding `fill: tonexty` at the same level as the `entity` works here and links with the previous entity in the yaml list. Warning: AFAICT it links to the previous one that is enabled. If you disable it in the legend then it links to the previous one and so on.

It makes me crazy... i can do it outside HA, but not inside...
Here is one of my example:

```yaml
  - entity: sensor.ths_fridge_humidity
      name: φ[%] (max)
      fill: none
      line:
        color: rgba(143, 86, 164, 0.6)
        width: 1
      statistic: max
      period: 1day
      showlegend: true
      
    - entity: sensor.ths_fridge_humidity
      fill: tonexty
      name: φ[%] (min)
      line:
        color: rgba(143, 86, 164, 0.6)
        width: 1
      statistic: min
      period: 1day
      showlegend: true
      
    - entity: sensor.ths_fridge_humidity
      fill: none
      name: φ[%] (mean)
      line:
        color: rgba(143, 86, 164, 1.0)
      statistic: mean
      period: 4hour
```

The result:
![2022-10-27 11_16_01-YAML Dashboard – Home Assistant](https://user-images.githubusercontent.com/9727894/198244778-be9318ae-415d-40d6-bfbf-46c62889d08d.png)
I think I was exhaustive in trying different combinations of fill, order of entities, but I get similar results....

**Reply by dbuezas** [reply]
Try with this:
* Min first
* Max second with fill: tonexy
* Then mean

**Reply by FrnchFrgg** [reply]
This works perfectly here, no matter whether I put max first or second. `tonexty` has to be set on the second one.

```
type: custom:plotly-graph
entities:
  - entity: sensor.temperature_exterieure
    name: max
    statistic: max
  - entity: sensor.temperature_exterieure
    name: min
    statistic: min
    fill: tonexty
  - entity: sensor.temperature_exterieure
    name: Extérieur
defaults:
  entity:
    statistic: mean
    line:
      shape: spline
      width: 2
hours_to_show: 10
```

**Reply by r-jean-pierre** [reply]
Thanks for your help, but in my specific case, it fails.
But on a tinier example:
```

  - type: custom:plotly-graph  # Fridge
    entities:
    - entity: sensor.ths_fridge_humidity
      statistic: max
    - entity: sensor.ths_fridge_humidity
      statistic: min
      fill: tonexty
    defaults:
      entity:
        statistic: mean
        line:
          shape: spline
          width: 2
    hours_to_show: 10`
```

![2022-10-27 12_32_21-YAML Dashboard – Home Assistant](https://user-images.githubusercontent.com/9727894/198262251-fc16d427-7ebf-46a0-99f1-7a857e8be34a.png)

I think I need to start from this state and reconstruct line after line what I wanted to see and understand when it breaks

I'll keep you informed
