### DISCUSSION TITLE
Long term statistics support

### DISCUSSION THREAD

**Discussion by dbuezas** [dbuezas/lovelace-plotly-graph-card#81] [Announcements]
Thanks to @FrnchFrgg , this version brings support for statistics!
```yaml
type: custom:plotly-graph-dev
entities:
  - entity: sensor.temperature
    statistic: mean # min, mean, max or sum
    period: hour # 5minute, hour, day or month
```
This means that multi day plots can now be very snappy, and you can look way back in the past too.

After we added statistics support, I decided to make a fairly big refactor to improve the API of both statistics and attributes.
Because of that, this one is marked as beta version. Please feel encouraged to report any bugs as issues, or drop a thanks to @FrnchFrgg in the discussions section if you were missing the feature!

<hr /><em>This discussion was created from the release <a href='https://github.com/dbuezas/lovelace-plotly-graph-card/releases/tag/v1.4.0'>Long term statistics support</a>.</em>

**Comment by netweaver1970** [comment]
thanks @FrnchFrgg and @dbuezas ! How do I install this beta version next to the normal version?

**Reply by dbuezas** [reply]
It's quick and simple, see here:
https://hacs.xyz/docs/faq/beta/

**Comment by dbuezas** [comment]
Out of beta in the next 5 minutes

**Comment by Zingel1986** [comment]
Hi, thanks for the good work. I wanted this feature since the first version.
Is it possible to change the statistic period when changing the view with the range selector?

**Reply by dbuezas** [reply]
It's not possible at the moment to have dynamic periods

**Reply by Zingel1986** [reply]
OK... THX for the reply

**Reply by dbuezas** [reply]
I think it's a good idea though.
What do you think about having `period: auto`, which dynamically changes the period so that there are neither too many, nor to little data points in the currently visible range?
@r-jean-pierre wdyt?

**Reply by netweaver1970** [reply]
Grafana also has this auto functionality, but it doesn't auto switch between **preset** time periods, it seems to use fractional time period, to always end up with a preset fixed amount of data points.

I would still like an auto switching between the default discreet time windows (5 min, hr, day, week, month, year), based on a wanted 'range' of data points. Maybe make the wanted number of data point flexible, kind of resolution setting. Either prefixed in the YAML, made optional at runtime, or both.

And when zooming in the time domain, it would take lower time period values. 
That would be awesome ! Fast (and aggregated) when possible and detailed when needed.

**Reply by r-jean-pierre** [reply]
> I think it's a good idea though. What do you think about having `period: auto`, which dynamically changes the period so that there are neither too many, nor to little data points in the currently visible range? @r-jean-pierre wdyt?

If it comes alive, it would be wonderful + usefull

**Reply by dbuezas** [reply]
@netweaver1970 as a starter, I'll try an automatic mode with reasonable hardcoded resolutions

**Reply by dbuezas** [reply]
I exaggerated the effect a lot so it is visible (set the resolution to a minimum of 25 datapoints in screen)
![auto stats](https://user-images.githubusercontent.com/777196/198689843-30036763-ae93-4beb-a0ac-ab56d6c935a0.gif)

**Reply by dbuezas** [reply]
And here is with a minimum of 500 datapoints. The difference between hour and day is because I'm plotting temperatures (which obviously have a cycle of exactly 1 day).
But between 5 minutes and 1 hour, it looks great
![500](https://user-images.githubusercontent.com/777196/198691044-76cf41fb-4d8c-4209-9389-d4e90c66b58e.gif)

**Reply by dbuezas** [reply]
Experimental branch:
https://github.com/dbuezas/lovelace-plotly-graph-card/tree/feat/statistics-automatic-period
It shows the selected period in the title 
It's a bit of a hack, but it does seem to work.
Feedback appreciated.

**Reply by Qhilm** [reply]
Is the behavior of `period: auto` documented somewhere?

**Reply by dbuezas** [reply]
Yes, in the readme https://github.com/dbuezas/lovelace-plotly-graph-card?tab=readme-ov-file#automatic-period

**Comment by dbuezas** [comment]
Here is a gorgeous example from @r-jean-pierre
Do you mind posting your yaml Jean Pierre?
![image](https://user-images.githubusercontent.com/777196/198362426-9c4437ae-ddfe-470a-8117-752bfbff2203.png)

**Comment by r-jean-pierre** [comment]
Here is where I am so far

```yaml
cards:
  - type: custom:plotly-graph  # Kid's room
    defaults: &mon_defaults
      entity:
        texttemplate: "%{y:.1f}"
        connectgaps: false
        hovertemplate: ''
        line:
          shape: spline
          width: 2
    entities:
    - entity: sensor.ths_kids_temperature
      name: T[°C] (max)
      line:
        color: rgba(81, 117, 159, 0.4)
        width: 1
      statistic: max
      period: 1day
      showlegend: false
      show_value: false
    - entity: sensor.ths_kids_temperature
      name: T[°C] (min)
      fill: tonexty
      fillcolor : rgba(81, 117, 159, 0.2)
      line:
        color: rgba(81, 117, 159, 0.4)
        width: 1
      statistic: min
      period: 1day
      showlegend: false
      show_value: false
    - entity: sensor.ths_kids_temperature
      texttemplate: "%{y:.1f}°C"
      name: T[°C] (mean)
      line:
        color: rgba(81, 117, 159, 1.0)
      statistic: mean
      period: 4hour
      show_value: true
    
    - entity: sensor.ths_kids_humidity
      name: φ[%] (max)
      line:
        color: rgba(143, 86, 164, 0.4)
        width: 1
      statistic: max
      period: 1day
      showlegend: false
      show_value: false
    - entity: sensor.ths_kids_humidity
      name: φ[%] (min)
      fill: tonexty
      fillcolor : rgba(143, 86, 164, 0.2)
      line:
        color: rgba(143, 86, 164, 0.4)
        width: 1
      statistic: min
      period: 1day
      showlegend: false
      show_value: false
    - entity: sensor.ths_kids_humidity
      texttemplate: "%{y:.1f}%"
      name: φ[%] (mean)
      line:
        color: rgba(143, 86, 164, 1.0)
      statistic: mean
      period: 4hour
      show_value: true
    
    layout: &mon_layout
      hovermode: "x unified"
      yaxis:
        range:
          - 10
          - 40
        gridcolor: rgba(233, 233, 233, 0.4)
        zeroline: false
        showticklabels: true
        tickfont:
          color: rgba(81, 117, 159, 1.0)
        title: false
      yaxis2:
        range:
          - 40
          - 90
        gridcolor: rgba(233, 233, 233, 0.4)
        zeroline: false
        tickfont:
          color: rgba(143, 86, 164, 1.0)
        title: false

      margin:
        "l": 32
        "r": 32
        "t": 64
        "b": 40

      xaxis:
        gridcolor: rgba(233, 233, 233, 0.4)
        rangeselector:
          "y": 1.12
          "x": 0.72
          buttons:
            - count: 12
              step: hour
            - count: 5
              step: day
            - count: 30
              step: day
    hours_to_show: 72
    refresh_interval: 30
    title: Kid's room
```

**Reply by dbuezas** [reply]
Did you see this?

https://www.home-assistant.io/images/blog/2022-11/long-term-stats-more-info-dialog.png

**Comment by netweaver1970** [comment]
I saw it too, I'm on an early beta, since I saw the water usage metering and the LTS/week support. Both are something I wanted.
 But they just went to LTS instead of real state values. Lots of discussion on this change on the Beta Discord channel on the (un)usability of this change ... 
For me it's not enough, I like the flexibility, the auto-ranging, zooming etc from Plotly, if all works out as planned/hoped. 
Their (HA team) reason was just to reduce the cpu/system load by using the LTS instead of state values.

**Comment by Qhilm** [comment]
@r-jean-pierre , I am unable to use `period: 1minute`. I also tested "1day" like in your yaml example. The error I get says:
>period: "1minute" is not valid. Use 5minute,hour,day,week,month

Do I need to define custom periods somewhere else?

**Reply by dbuezas** [reply]
Were those added in home assistant's statistics API?

**Reply by r-jean-pierre** [reply]
I think it's the 5 periods we can select with the combination statistic/period:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/08ca5af6-6186-4928-b3ef-8e09c0fa610b)

and true that it's not possible to tweak it

Now I look at my own example, it shouldn't work, and currently this is not what I have in my running Yaml.
I switched to this technique:
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/0ee283d1-2e9c-4331-85a8-424bc5280810)

I don't remember why it did it, more powerful or had technical issue (?)...

**Reply by Qhilm** [reply]
thanks.

I don't fully understand the new syntax: is this dynamic depending on the time windows displayed on the chart?

And secondly, what does "0s" mean in this case?

**Reply by dbuezas** [reply]
The left side is the minimum visible range, see readme

**Comment by r-jean-pierre** [comment]
Hi!

I'm posting here cause the title makes sense  ("Long term statistics support")

I have a simple and easy graph with 5mins average

```
      - type: custom:plotly-graph
        entities:
        - entity: "sensor.waterheater_temperature"
          statistic: mean
          period: 5minute
          showlegend: false
          line:
            width: 3
            shape: spline
            smoothing: 0.5
          show_value: true
```

![2024-04-23 16_50_20-History – Home Assistant](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/0cdab3d2-b570-4ce1-b9f8-957c1e456dca)

If you look on bottom left corner (red), I tried to display 2 weeks, but data history length seems to stop ~10 days ago
It matches (?) with the source "History" of HA , but there is data in the source "Long Term Statistics" (as you can see on the right side of the screenshot in blue)

I just noticed "recently", when I was forced to restore a backup to restart my HA setup and therefore lost some of my history (it was two months ago)
Before, I was able to zoom out indefinitely, thus display months of data (I suppose I was using without knowing some internal cache/history from your integration or something else (?) ) but since, I had time to accumulate data and only the last 10 days are displayed.

It seems to have the same behaviour without `statistic: mean          period: 5minute`

Is there something I missed (or misuse) ?

**Reply by dbuezas** [reply]
Mmm the 5 minutes statistics aren't long lived. Only above hours. Maybe it is that?

**Reply by r-jean-pierre** [reply]
Yes! Correct!:

![2024-04-24 14_08_03-YAML Dashboard – Home Assistant](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/07748edf-f31e-453d-a72b-6e113f286034)

```
  - type: custom:plotly-graph
    entities:
    - entity: "sensor.waterheater_temperature"
      statistic: mean
      period: hour
  - type: custom:plotly-graph 
    entities:
    - entity: "sensor.waterheater_temperature"
      statistic: mean
      period: 5minute
```

So basically, I'm restricted to `5minute`, `hour`, `day`, `week`, `month` according to:

https://github.com/dbuezas/lovelace-plotly-graph-card#for-entities-with-state_classmeasurement-normal-sensors-like-temperature

If I cannot use 5minute, this is because of HA granularity in long statistics, or the number of points to be displayed by plotly?
What could be the minimum duration to be able for fine-grained plot? (maybe 1H is already the shortest (?)), do you know it?

**Reply by dbuezas** [reply]
Yes 1h is the shortest which is never deleted. You can configure that.
Here are the relevant docs: https://data.home-assistant.io/docs/statistics/

**Reply by r-jean-pierre** [reply]
So one hour should be okay in most of the cases
I have a last question, one of my sensor behaves strangely with plotly:
![2024-04-24 21_04_00-Developer Tools – Home Assistant](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/e3207e0e-e1aa-40f5-99db-59af5053c005)
The integration set it as `device_class: energy`. 
On one hand, user knows that it could restart at zero, should be increasing, and some extra options are available through HA-gui. 
On the other hand, it seems to not be compatible with the combo statistic/period in plotly. In the best case scenario I can have my 10 days of short term history, but without any aggregation, otherwise the graph is blank

Do you have any idea how to easily bypass this behaviour?

**Reply by dbuezas** [reply]
As far as I know the behavior determines what statistic is stored in the db. I suggest you see what's available in the standard statistics plot card and then get back to this card, its config editor is more user friendly than yaml

**Reply by r-jean-pierre** [reply]
So, (if you prefer I can create another thread), but long reply/question.
For the same integration (Shelly), let's start by what I think is a classical measurement sensor, like it happens 99% of the time,
`sensor.waterheater_voltage`
Let's inspect HA/DevTools/Statistics for ~1month:
![2024-04-26 10_19_05-History – Home Assistant](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/fab052c2-dfcc-4bc6-91be-c592e74f338b)
No surprise, 10 days of fine-grained data, and a long history (with of course less data points)

Now super easy Yaml:
<details>

```
cards:
  - type: history-graph
    entities: 
      - sensor.waterheater_voltage
    hours_to_show: 720
    
  - type: custom:apexcharts-card
    series:
      - entity: sensor.waterheater_voltage
    graph_span: 30d
    
  - type: custom:apexcharts-card
    series:
      - entity: sensor.waterheater_voltage
        group_by: 
          func: max
          duration: 1h
    graph_span: 30d
    
  - type: custom:plotly-graph
    entities:
      - entity:  sensor.waterheater_voltage
    hours_to_show: 30d
    
  - type: custom:plotly-graph
    entities:
      - entity:  sensor.waterheater_voltage
        statistic: max
        period: hour
    hours_to_show: 30d
```
</details>

![2024-04-26 10_46_10-YAML Dashboard – Home Assistant](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/06b4da8d-2114-488f-b909-e9fbb5913267)
Built-ins fail to display history, apex and plotly too (but that's normal)
If we ask stats per day ploty (blue) can do it, not apex (orange)
For me another good reason to use custom:plotly-graph

Now, the strange sensor `waterheater_energy`, same yaml, just changed entity name:
![2024-04-26 10_50_47-YAML Dashboard – Home Assistant](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/72f8c0c8-721e-4e1a-9907-ee56dc6b7f74)

So all of them failed, but custom:plotly-graph really displays nothing when using `statistic` (which was its asset over other cards)
And there is long history data:
![2024-04-26 10_54_38-History – Home Assistant](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/9727894/0765186a-ded1-4179-97bc-a6045fde9b5a)

What is likely the root cause (according to my very little understanding) is either device_class or state_class:
```
state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
friendly_name: WaterHeater energy
```
Have you already encountered this weirdness?

**Reply by dbuezas** [reply]
Yes those determine what is stored. 
I find it easiest to use the built in home assistant statistics card to find what's available.
I think this are the docs you are looking for: https://data.home-assistant.io/docs/statistics/

**Reply by r-jean-pierre** [reply]
Totally agree, so then it still means that if something (like plotly-graph) is able to retrieve long term stats, why in the case of (eventually total_increasing state_class) it fails?
But right also, and you don't have to investigate: type: statistics-graph  fails too! Blank graph. Few people talk about it, no clear solution is given. 
Damn, I really did a few things with HA, but 99% of the time, I fall in the 1% of case which is difficult for something visually of functionality obvious 😢

**Reply by dbuezas** [reply]
Haha, I also tend to happen to want to do the thing that doesn't work :)

**Reply by r-jean-pierre** [reply]
Pure sadness of the situation:

```
hacked_waterheater_energy:
      unique_id: "4T9viWiD9a82X8Nf"
      friendly_name: "WaterHeater energy"
      icon_template: "mdi:flash-outline"
      value_template: >-
        {{states('sensor.waterheater_energy')}}
      unit_of_measurement: "kWh"
      device_class: "energy"
    #
```
in my template file...
then it won't be a `state_class: total_increasing` and starting today, I will receive my infinite history (but of starting today...)
8 lines of code and lost of potential history for something super stupid
