### DISCUSSION TITLE
show daily energy consumption as a bar graph

### DISCUSSION THREAD

**Discussion by Jn115759** [dbuezas/lovelace-plotly-graph-card#92] [Q&A] [answered]
I am new using this fantastic plotly integration and was hoping someone could help me with the issue above.
I defined a utility meter helper "sensor.helper_elektriciteit_aanvoer_net" which resets daily. Values are shown in the graph below in blue.
![image](https://user-images.githubusercontent.com/91130738/198865697-c160be9f-2e32-4612-8e07-81d7cf6e3d54.png)

Now I would like to see the daily consumption as a bar graph.
According to the documentation this should be fairly simple.
![image](https://user-images.githubusercontent.com/91130738/198865738-75fbdc23-5839-4080-b713-14f6fe2fa7da.png)

I used the code below.

```
type: custom:plotly-graph
entities:
  - entity: sensor.helper_elektriciteit_aanvoer_net
    statistic: max
    period: day
hours_to_show: 144
refresh_interval: 30
title: Energy
```
Unfortunately this only results in a flat line.

![image](https://user-images.githubusercontent.com/91130738/198865855-12d27379-5b42-4951-ac5a-4d660c3c4a69.png)

Would appreciate some hints to learn what I am doing wrong.
Many thanks.

**Comment by dbuezas** [comment]
From [here](https://data.home-assistant.io/docs/statistics/), you probably need to use 'state' instead of max, but we didn't implement that.
Can you try with 'sum' ? If that should something, then I'll add 'state' later today.

**Reply by Jn115759** [reply]
Many thanks for your superswift reply and for helping out on this !
I added "sum" and I think this is working :-). The graph now shows the cummulative result of course.
![image](https://user-images.githubusercontent.com/91130738/198867897-1aca6d08-df47-4b24-ac6a-6469ce78a84c.png)


```
type: custom:plotly-graph
entities:
  - entity: sensor.helper_elektriciteit_aanvoer_net
    statistic: sum
    period: day
hours_to_show: 144
refresh_interval: 30
title: Energy
```

**Comment by dbuezas** [comment, marked as answer]
Fixed in v1.4.8! see #93 
```yaml
type: custom:plotly-graph-dev
entities:
  - entity: sensor.electricity_total
    statistic: state
```
<img width="434" alt="image" src="https://user-images.githubusercontent.com/777196/198876488-19b9de7f-8c32-4e44-986f-c2082a8a55a0.png">

**Comment by dbuezas** [comment]
BTW, you can do bar charts too, see #28

**Reply by Jn115759** [reply]
Many thanks for helping me out. All is working fine!
Below the final result.

Just 1 specific issue I can't explain : the current day is shown with 2 bars. Any idea ? Would help me to better understand how all is working.

![image](https://user-images.githubusercontent.com/91130738/198949813-13093a48-9a05-404e-b89f-110686d61d58.png)
```
type: custom:plotly-graph
entities:
  - entity: sensor.helper_elektriciteit_aanvoer_net
    statistic: state
    period: day
    type: bar
hours_to_show: 288
refresh_interval: 30
title: Energy
```

**Reply by dbuezas** [reply]
I introduced a bug in v1.5.0, I'll make a new release today and ask you to confirm if this issue remains

**Reply by Jn115759** [reply]
Hi there, I just updated to version 1.5.3  and to be certain also restarted HA, but the double value still is present.
![image](https://user-images.githubusercontent.com/91130738/199214076-a5d77f60-8973-4861-a07e-58c0f9861cfd.png)

**Reply by dbuezas** [reply]
@Jn115759 stick around, the next version should fix this :)

**Comment by trianglesis** [comment]
I can't get why the bar chart shows a lower value on Nov 8

<img width="915" height="711" alt="image" src="https://github.com/user-attachments/assets/1b98b3c9-9f3e-4f57-9216-22ecdf4394fc" />

<img width="918" height="760" alt="image" src="https://github.com/user-attachments/assets/ca8cbc04-802a-4b8f-9c84-dcd093a28e4e" />

Tried different filters, and none can show a real number.

Can only show "bar" with true values like this:

<img width="919" height="484" alt="image" src="https://github.com/user-attachments/assets/3c039fd6-c234-405b-b409-97cc8d879df6" />

**Comment by kppr0** [comment]
I guess you need to include period: day and filters: - delta:

<img width="216" height="150" alt="image" src="https://github.com/user-attachments/assets/d351f9c2-5857-4caa-9405-2035352aaa3e" />

**Reply by trianglesis** [reply]
Thanks, I've tried.

Unfortunately, the meter is 'net' so it can go to negative or positive numbers when the battery is dis/charging.

Here is what it looks like with a graph, deep dive peaks - discharge of the battery.

<img width="944" height="1062" alt="image" src="https://github.com/user-attachments/assets/a762dbcd-af4e-44df-96df-6cf253483e61" />

I'm now trying to use an alternative approach to register the wattage of dis/charge with two different meters, without displaying negative numbers. It looks better in bars view and is pretty close to reality:

<img width="945" height="1059" alt="image" src="https://github.com/user-attachments/assets/948fc2af-3447-4441-b752-298e6dee3638" />

**Reply by dbuezas** [reply]
You could try the integration filter

**Reply by trianglesis** [reply]
> You could try the integration filter

It's already that way with template sensors:

inverter battery power usage sensor -> integration sensor -> utility meter

So I only wanted to show peaks of battery consumption over time, to know when the last time it was discharged more than usual and how often.

**Reply by dbuezas** [reply]
For peaks you could use the max statistic

**Reply by trianglesis** [reply]
> For peaks you could use the max statistic

It works pretty weirdly, not showing half of the records.

<img width="761" height="509" alt="image" src="https://github.com/user-attachments/assets/475802e7-c5a5-4b3c-a503-3387c93cfec9" />

Max | Min | State

<img width="2309" height="379" alt="image" src="https://github.com/user-attachments/assets/a4091bd6-a807-426c-b822-b44744d18116" />

Code:


<details> 
  <summary>Code is the same, only statistics method changes </summary>

```yaml
title: sensor.invertor_discharging_kwh_2
type: custom:plotly-graph
entities:
  - entity: sensor.invertor_discharging_kwh_2
    statistic: max
    period: day
    type: bar
    texttemplate: "%{y:0.1f}"
    filters:
      - filter: i>=1
hours_to_show: 14d
refresh_interval: 60
grid_options:
  columns: full
layout:
  dragmode: pan
  height: 350
  margin:
    b: 90
  legend:
    itemwidth: 50
  xaxis:
    rangeselector:
      "y": "-.3"
      buttons:
        - count: 1
          step: day
        - count: 2
          step: day
        - count: 7
          step: day
        - count: 14
          step: day
        - count: 30
          step: day
        - count: 90
          step: day
config:
  scrollZoom: true
  doubleClickDelay: 600
```
</details>

Oh, there is also a DT problem, for cases when the battery is discharging during the night, 23:59 till the next day 00:01.
So the history data is now split between days, so I must not rely on the date in such statistics but rather on the period when the utility meter was calibrated to 0 zero value (when the battery is fully charged).

It's not the ultimate issue, but could I build the graph like that?

For example:
0-0-0-0-0-1-2-3-4-5-0-0-0-0-0-1-2-3-4-0-0-0-0

- 0 zeros is a period when the main grid is present and the battery is charged 100% so the utility meter resets to zero and stays zero till the next blackout
- 1-2-3-4-5 are new history points when the battery was in use, and how many watts it gives back into the system

Ideally, bars should indicate maximum battery discharge for n periods of blackouts (not counting days, but blackouts between zero values)
