### DISCUSSION TITLE
Support for `period: auto`, automatic statistic period

### DISCUSSION THREAD

**Discussion by dbuezas** [dbuezas/lovelace-plotly-graph-card#95] [Announcements]
## What's Changed
* Automatic statistic period support by @dbuezas in https://github.com/dbuezas/lovelace-plotly-graph-card/pull/94

**Full Changelog**: https://github.com/dbuezas/lovelace-plotly-graph-card/compare/v1.4.8...v1.5.0

<hr /><em>This discussion was created from the release <a href='https://github.com/dbuezas/lovelace-plotly-graph-card/releases/tag/v1.5.0'>Support for `period: auto`, automatic statistic period</a>.</em>

**Comment by dbuezas** [comment]
Idea by @Zingel1986

**Reply by r-jean-pierre** [reply]
Hi,

I started to experiment this new feature and it works as expected. Do you think it could be possible to expose some parameters to adapt the logic of the aggregation with maybe a user coefficient such as 
`if time_period_displayed > foobar then aggregate per something `
becomes:
`if time_period_displayed * user_coefficient > foobar then aggregate per something `

or maybe a list of cases  displayed_time_periods <-> user_defined_aggregations

**Reply by dbuezas** [reply]
Hey @r-jean-pierre, in case you missed it, you can now do this instead:
```yaml
type: custom:plotly-graph-dev
entities:
  - entity: sensor.garden_temperature
    period:
      0s: 5minute
      1d: hour
      1M: day
      1y: month
```
