### DISCUSSION TITLE
Show difference of 2 sensors in a bar graph

### DISCUSSION THREAD

**Discussion by Jn115759** [dbuezas/lovelace-plotly-graph-card#98] [Q&A]
I currently have a nice bar graph with 2 helper utility sensors resetting daily (see below).

However, I would like a bar graph with only the difference between both of them (the red piece).
`{{ (states('sensor.helper_elektriciteit_aanvoer_net')|float - states('sensor.helper_elektriciteit_terugvoer_net')|float)|round(2)}}`
Can this be done without creating an additional template sensor as part of the graph definition ?

Many thanks in advance for helping me out!

![image](https://user-images.githubusercontent.com/91130738/198977845-dfdb62d4-1431-4ee6-a88e-a96b4469aad4.png)

```
type: custom:plotly-graph
entities:
  - entity: sensor.helper_elektriciteit_aanvoer_net
    statistic: state
    period: day
    type: bar
    width: null
  - entity: sensor.helper_elektriciteit_terugvoer_net
    statistic: state
    period: day
    type: bar
    width: null
hours_to_show: 168
refresh_interval: 30
title: Energy
```
