### ISSUE TITLE
Ghost traces when data has single non-unavailable states sandwiched between unavailable ones

### ISSUE THREAD

**Issue by dbuezas** [dbuezas/lovelace-plotly-graph-card#103]
Although it is a plotly.js bug (not this card's) it can be fixed by creating fake duplicates or simply removing the rogue points

To reproduce:
```yaml
type: custom:plotly-graph-dev
entities:
  - entity: sensor.nothin
    lambda: |-
      () => ({
        x:[-60, -50, -40, -30, -20, -10, 0].map(x => new Date(Date.now()+x*1000*60)),
        y:[0, 1, null, 3, null, 4, 5],
      })
hours_to_show: 1
```

in [time-offsets](https://github.com/dbuezas/lovelace-plotly-graph-card/tree/feat/time-offsets) branch
