### ISSUE TITLE
Style:  New borders in HA 2022.11.1 

### ISSUE THREAD

**Issue by Masterz69** [dbuezas/lovelace-plotly-graph-card#115]
Just installed HA Core 2022.11.1.
Plotly graph card have some issues with new borders in default dashboard theme - right one and corners: see attached.
Looks like right border & corners overlapped with background color.

![image](https://user-images.githubusercontent.com/15225823/200135503-91f067f6-9c9d-4451-86e8-bf70a3cb443d.png)

In my case all ```type: custom:plotly-graph``` cards demonstrate same behavior.
Most of them have simplest config, like
```
- type: custom:plotly-graph
  entities:
    - entity: sensor.sth_hall_temperature
      name: Hall
    - entity: sensor.sth_bedroom_temperature
      name: BedRoom
  hours_to_show: 24
  refresh_interval: 60
```
