### ISSUE TITLE
Rendering issue: when panning, duplicate of graph sometimes stays static

### ISSUE THREAD

**Issue by b3nn0** [dbuezas/lovelace-plotly-graph-card#124]
Hi,
See gif below. It seems to have started recently, around the time when `period: auto` was introduced, but can't say a specific version.

Card definition:
```
type: custom:plotly-graph
layout:
  height: 400
entities:
  - entity: sensor.wolf_aussentemperatur
    line:
      shape: linear
  - entity: sensor.dachboden_temperatur
    line:
      shape: linear
  - entity: sensor.bme680_temperature
    name: Bürotemperatur
    line:
      shape: linear
  - entity: sensor.wohnzimmertemperatur
    line:
      shape: linear
defaults:
  entity:
    show_value:
      right_margin: 15
  yaxes:
    fixedrange: true
refresh_interval: 60
hours_to_show: 48
title: Außentemperatur

```

Issue:
![graph](https://user-images.githubusercontent.com/1858945/200262776-a56bf3a2-f787-46cb-a344-307e79239656.gif)

Some hints:
- It happens in both, Firefox and Chromium
- It doesn't happen for all my graphs, only some, and always for the same (i.e. always for the red one in above example, but never the others)
- It also happens when zooming

EDIT: Just noticed: `period: auto` seems to have stopped working for me in the latest versions, too. Only shows daily all the time now. If I explicitly set the period definitions for different zooms like in the readme, it works fine. Should I open another issue for that?

EDIT2: Just retested with older versions. In 1.5.3 everything is fine, in 1.6.0 the issue appears.
