### ISSUE TITLE
End the graph line with a marker and current value

### ISSUE THREAD

**Issue by markuska00** [dbuezas/lovelace-plotly-graph-card#15]
Is it possible to end the graph line with a marker and current value?

Like this:
![psme0 (1)](https://user-images.githubusercontent.com/37914650/147876909-1437e6b3-fdf7-4835-8ed4-2318028bd331.png)

Info here:
https://stackoverflow.com/questions/66190574/plotly-how-to-annotate-end-of-multiple-lines-with-text-and-marker-colors-that-m

**Comment by dbuezas** [comment]
This I the best I managed:
![image](https://user-images.githubusercontent.com/777196/147880111-422e9386-6356-45e8-85b0-bcb6029560a9.png)

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.openweathermap_temperature
    yaxis: y1
    line:
      color: red
  - entity: sensor.openweathermap_temperature
    yaxis: y1
    unit_of_measurement: W floor
    mode: markers+text
    texttemplate: '%{y}'
    textposition: top middle
    showlegend: false
    marker:
      color: red
    textfont:
      color: red
    lambda: (ys, xs) => ys.map((y,i)=> (i=== ys.length-1) && y)

hours_to_show: 24
refresh_interval: 10

```

Here are the default plotly colors:
```
[
    '#1f77b4',  # muted blue
    '#ff7f0e',  # safety orange
    '#2ca02c',  # cooked asparagus green
    '#d62728',  # brick red
    '#9467bd',  # muted purple
    '#8c564b',  # chestnut brown
    '#e377c2',  # raspberry yogurt pink
    '#7f7f7f',  # middle gray
    '#bcbd22',  # curry yellow-green
    '#17becf'   # blue-teal
]
```
More about colors [here](https://community.plotly.com/t/plotly-colours-list/11730/3)

More info about texttemplate [here](https://plotly.com/javascript/reference/scatter/#scatter-texttemplate)

You can do `textposition: middle right` but you'll sometimes have to scroll to the right

**Comment by dbuezas** [comment]
Oh, I found a way to force a right padding in the graph so the text fits to the right.
The idea is to add an invisible but big marker.

![image](https://user-images.githubusercontent.com/777196/147880424-6d4a1e15-7d64-420a-ae78-ac949ee1cbc5.png)

```yaml
type: custom:plotly-graph-dev
entities:
  - entity: sensor.openweathermap_temperature # the lines
    yaxis: y1
    line:
      color: '#1f77b4'
  - entity: sensor.openweathermap_temperature # the text
    yaxis: y1
    unit_of_measurement: W floor
    mode: text+markers
    texttemplate: '%{y}'
    textposition: middle right
    showlegend: false
    marker:
      color: '#1f77b4'
    textfont:
      color: '#1f77b4'
    lambda: (ys, xs) => ys.map((y,i)=> (i=== ys.length-1) && y)
  - entity: sensor.openweathermap_temperature # the invisible marker to make space for the text
    yaxis: y1
    mode: markers
    showlegend: false
    marker:
      opacity: 0
      size: 50
    lambda: (ys, xs) => ys.map((y,i)=> (i=== ys.length-1) && y)
hours_to_show: 24
refresh_interval: 10

```
