### ISSUE TITLE
Filters example in readme to add two entities is wrong

### ISSUE THREAD

**Issue by thecem** [dbuezas/lovelace-plotly-graph-card#179]
**Describe the bug**
The Example is not showing the expected results of adding both temps:

```
type: custom:plotly-graph
entities:
  - entity: sensor.temperature1
    internal: true
    period: 5minute
    filters:
      store_var: temp1
  - entity: sensor.temperature2
    period: 5minute
    name: sum of temperatures
    filters:
      map_y: y + vars.temp1[i].y
```

**Screenshots**

**yaml**
```yaml

type: custom:plotly-graph
entities:
  - entity: sensor.temperature1
    internal: true
    period: 5minute
    filters:
      store_var: temp1
  - entity: sensor.temperature2
    period: 5minute
    name: sum of temperatures
    filters:
      map_y: y + vars.temp1[i].y
```

**Additional context**
I try to add a graph for added energy consumption, but even the temp example do not work.
Is there a possibility to draw a trend line like this:

![2813CFDF-E5E0-41C2-B445-7B4E14131058](https://user-images.githubusercontent.com/46648579/211298606-6856009c-c8b3-4c72-a66e-85400bebbf6b.jpeg)

**Comment by dbuezas** [comment]
Use map_y_numeric and use force_numeric before storing the first one. The variables are strings so it is doing string concatenation instead of addition.
There is no built in trendlines feel free to add a separate feature request for them and we can discuss deetails :)

**Comment by dbuezas** [comment]
Oh, i see the example in the readme is wrong. I'll keep this open until i fix it

**Comment by thecem** [comment]
this way?

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.temperature1
    internal: true
    period: 5minute
    filters:
      - map_y_numbers: y
      - force_numeric
      - store_var: temp1
  - entity: sensor.temperature2
    period: 5minute
    name: sum of temperatures
    filters:
      - map_y_numbers: y + vars.temp1[i].y
```

**Comment by dbuezas** [comment]
Oh, the force_numeric may disalign them. Just remove it.

**Comment by dbuezas** [comment]
I just saw that in your example, you also want to change the x axis. You can do that with `fn` and returning `xs`

**Comment by thecem** [comment]
Thank you so much for your instant help!

**Comment by thecem** [comment]
Plan is to get a graph for Heat Energy consumption of a house in relation to the daily outside temperature. (Heating curve (Heizkurve) and building heating load (Heizlast)).

![grafik](https://user-images.githubusercontent.com/46648579/211321783-e8a96688-537a-4557-9fe1-534dd02d0bdd.png)

**Comment by dbuezas** [comment]
Oh, what a cool idea! I want that too!
Drop a feature request for the trendlines filter :)
We can probably add a bunch of them (linear, polynomial, exponential, power series...)

**Comment by dbuezas** [comment]
@zanna-37 look offsets in the wild :)

**Comment by thecem** [comment]
Is the adding two y values solved? Or at least a example how to do this?
thx!

**Comment by thecem** [comment]
I got it working: 
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.hmip_sens_out_stho_temperature
    statistic: mean
    period: hour
    name: Aussentemp
  - entity: sensor.at_yesterday
    statistic: mean
    period: day
    offset: '-1d'
  - entity: sensor.daily_heizoel
    statistic: state
    period: day
    unit_of_measurement: kWh
    name: Heizöl
    filters:
      - map_y_numbers: y * 10
  - entity: sensor.eg_energy_daily
    statistic: state
    period: day
    filters:
      - map_y_numbers: parseFloat(y)
      - store_var: egenergy
  - entity: sensor.odg_energy_daily
    statistic: state
    period: day
  - entity: sensor.odg_energy_daily
    statistic: state
    period: day
    name: Heating Energy
    filters:
      - map_y_numbers: y + vars.egenergy.ys[i]
title: Heat Energy LTS
hours_to_show: 500
refresh_interval: 10

```

**Comment by thecem** [comment]
![grafik](https://user-images.githubusercontent.com/46648579/211545338-bb7cd9ed-b1f9-4d9a-8219-51eb70298bcf.png)

```YAML
type: custom:plotly-graph
entities:
  - entity: sensor.hmip_sens_out_stho_temperature
    statistic: mean
    period: hour
    name: Aussentemp
  - entity: sensor.at_yesterday
    statistic: mean
    period: day
    offset: '-1d'
  - entity: sensor.eg_energy_daily
    statistic: state
    period: day
    filters:
      - store_var: egenergy
  - entity: sensor.odg_energy_daily
    statistic: state
    period: day
  - entity: sensor.odg_energy_daily
    statistic: state
    period: day
    type: bar
    opacity: 0.4
    width: 60000000
    texttemplate: '%{y:0.0f}'
    name: Heating Energy
    filters:
      - map_y: y + vars.egenergy.ys[i]
  - entity: sensor.daily_heizoel
    statistic: state
    period: day
    unit_of_measurement: kWh
    name: Heizöl
    texttemplate: '%{y:0.1f}'
    type: bar
    opacity: 0.4
    filters:
      - map_y_numbers: y * 10
title: Heat Energy LTS
hours_to_show: 576
refresh_interval: 10

```
