### ISSUE TITLE
But in HomeAssistant statistics API

### ISSUE THREAD

**Issue by andrekuehne** [dbuezas/lovelace-plotly-graph-card#180]
**Describe the bug**
When scrolling in time and using a derivative filter, the currently displayed first (oldest) datapoints appear to jump around (change their y-value). Similarly, clicking "Autoscale" triggers the same behavior, with values jumping around & additionally the x-axis expanding with each click.

**Screenshots**
A video of this effect in action is shown here:
[https://photos.app.goo.gl/bb7JfDMtFLbSyMm68](url)
![screen-20230109-135305_2](https://user-images.githubusercontent.com/777196/211360707-57520be8-bc16-484d-9d49-ff0c3a9845c9.gif)

**YAML**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.temp_out_c308_temperature
    statistic: mean
    type: bar
    period: day
    filters:
      - derivate: d
hours_to_show: 240
refresh_interval: 10
title: Derivate test
```
