### ISSUE TITLE
Integrate filter but resetting each day

### ISSUE THREAD

**Issue by kaijk** [dbuezas/lovelace-plotly-graph-card#181]
I'm trying to move kWh bar charts for daily, and hourly, and stacked daily and hourly (by time of day) energy from lambda to filters.  No joy.  The data come from Watt readings.  What I'm trying to accomplish is to have bar graphs begin at midnight 'x'  days or months, or some hours ago and continue through the current partial period, with multiple traces stacked by separate on-peak, off-peak accumulations (for which I have separate Watt sensors).

The `integrate:` function currently produces a continuously increasing (cumulative) trace over the `hours_to_show:`.  This does not lend itself to interval-based charting within those `hours-to-show`.

Comments in the Discussion about this Issue suggest a `reset_every: 1d`, etc. parameter to `integrate:` may be an approach to segmenting the integration by the desired intervals.
  
Here is my simplest setup, trying to achieve one column per day with a single series, no stacking. In HA I use the Rhimann integration with the `left` method against this same sensor to get energy: 
```
 - type: custom:plotly-graph
    entities:
      - entity: sensor.power_meter_total_watts
        type: bar
        filters:
          - integrate: h
          - multiply: 0.001 # to derive kWh/h from Wh/h
    hours_to_show: 72
    refresh_interval: 30
    title: Energy Consumption Daily
    layout:
      yaxis:
        title: kWh per Day
```
This produces three days of continuously increasing interval data, not binned by day, but in bar format by native intervals that looks more like a fill. (Note that is is in Wh, not kWh)
![image](https://user-images.githubusercontent.com/49624034/211213810-07dfdf74-2b26-4969-b51c-43eaf6e96c25.png)
Removing the `type: bar` just removes the "fill" appearance.
![image](https://user-images.githubusercontent.com/49624034/211213675-a8058413-5353-4d38-b349-d93969291607.png)

This is the most complex example I'm trying to reproduce that uses lambda. It happens to be hourly, but I also want monthly and daily by Bus and by TOD, stacked.  Computation efficiency is important to not overwhelm my RasPi 4, if possible.
![image](https://user-images.githubusercontent.com/49624034/211214223-effd50da-ea5e-4821-bd4c-b0562d872814.png)

_Originally posted by @kaijk in https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/168#discussioncomment-4627117_

**Comment by dbuezas** [comment]
I'm thinking of `zero_y_every: d # ms, s, m, h, d, w, M, y`  which also covers 195

**Comment by dbuezas** [comment]
Ups, closed by mistake

**Comment by kaijk** [comment]
> I'm thinking of `zero_y_every: d # ms, s, m, h, d, w, M, y` which also covers 195

That would work. Although, is there perhaps a reason to set y to values other than zero?  I don't have one.

I presume that with V3.0's expansion of the use of functions that one could be used to reset or set y on any schedule one might envision. A direct way like you lay out above would be useful, though.

**Comment by dbuezas** [comment]
Setting to  value different than zero should be equivalent to adding a constant in the next filter I think.

To reset on a different schedule you mean e.g. every 5 minutes? If so, that would require this filter to allow numbers before the units.
I could implement that by resetting each time `(y + timezone) % duration_constant` changes (`%` means modulo). Good idea.

**Comment by dbuezas** [comment]
I'll go back to you initial suggestion, I don't like `zero_y_every` anymore.

```yaml
    - integrate: h # computes area under the curve per unit of time using Right hand riemann integration. Same units as the derivative
    - integrate: 
        unit: h # defaults to h
        reset_every: 1h # Defaults to 0 (never reset). Any duration unit (ms, s, m, h, d, w, M, y). 
        offset: 30m # defaults to 0. Resets happen 30m later
```

**Comment by dbuezas** [comment]
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/777196/215519755-c4ac1f26-4733-4d64-a356-7174d5051a1b.png">

**Comment by kaijk** [comment]
Very Nice!

**Comment by dbuezas** [comment]
It's in v3.0.2, let me know how it went!
I added an `offset` option too, I doubt anybody needs it, but it made it 100% controlable, so why not :).
Implementation wise, I check how may times does the x coordinate timestamp fit inside the `reset_every`, and each time it changes I reset the accumulator. There is also an inbuilt offset to account for time zones, and I add the user offset to that too.

**Comment by kaijk** [comment]
Did you intend to have `offset:` be `time_offset:` as per your breaking change WRT Bar Graph Offset?  Or, since this one is a child parameter you want it to be `offset:`

**Comment by dbuezas** [comment]
oh, true. That's ok though, the issue is at the root of an entity only

**Comment by kaijk** [comment]
`Integration` and `reset_every` seem to work fine.  But, I'm trying to create a `bar chart` with one bar for each `reset_every:` interval (daily in this case).  I'm integrating hourly to get wH accumulations, resetting daily to get daily wH accumulations, multiplying by 0.001 to get kWh/day accumulations, So far, so good.

How do I then get a daily kWh bar chart?  The `yaml` below  returns a bar per observation (about every 10s), not one bar per `reset_every:` interval.  It seems that I may need to take a `max` for each `reset_every:` interval (or for the latest value for current interval).  Does that require a function as well as the integration and the reset_value?  (javascript is not my native language)

The `integrate` filter doesn't seem to return `statistics` from which I can do `max` using the `period:` that aligns with the `reset_every:` interval.

```yaml
  - type: custom:plotly-graph
    entities:
      - entity: sensor.power_meter_total_watts # New values arrive at about 10s intervals
        type: bar
        filters:
          - integrate:
              unit: h
              reset_every: 1d
          - multiply: .001
    hours_to_show: 168
    title: Energy Consumption Daily
    layout:
      yaxis:
        title: kWh per Day
```

**Comment by dbuezas** [comment]
Have you seen the utility meter entitiy functionality in home assistant? it's built exactly for that. You get an extra entity, with all you need

**Comment by kaijk** [comment]
Yes, I use `utility_meter:` extensively for daily, monthly, etc.  I was really hoping that for hourly I could integrate and just plot those values using the last value per `reset_every` interval using either a function or a native parameter.  Integration is one half the way to plotting `integrated` values accumulated to every `reset_every` time interval.

**Comment by kaijk** [comment]
Yes, I use Utility Meter and related extensively for daily, monthly, etc., but thought I could plot at least hourly with or extended from `reset_every` on the fly using integrated data and avoid creating persistent hourly HA entities with demands on the Recorder DB.  I don't see much use for `integrate:` without a way to bucket and plot the results by defined intervals.

**Comment by dbuezas** [comment]
Maybe you can add a resample filter after integrating?

Feel free to add a feature request issue proposing how you envision the yaml to look like and I'll take a look.

**Comment by kaijk** [comment]
It looks like adding `resample: 1h` did the trick!

Thank you for that idea, and for `reset_every` as well

![image](https://user-images.githubusercontent.com/49624034/217296770-0cd24583-5556-4ac6-bd80-b3b6e9ab5bcc.png)

```yaml
  - type: custom:plotly-graph
    entities:
      - entity: sensor.power_meter_west_bus_a_watts
        filters:
          - integrate:
              unit: h
              reset_every: 1h
          - multiply: 0.001
          - resample: 1h
        name: Power Meter West Bus A
        unit_of_measurement: kWh
      - entity: sensor.power_meter_west_bus_b_watts
        filters:
          - integrate:
              unit: h
              reset_every: 1h
          - multiply: 0.001
          - resample: 1h
        name: Power Meter West Bus B
        unit_of_measurement: kWh
    hours_to_show: 1d
    layout:
      barmode: stack
      yaxis:
        title: kWh per Hour
    defaults:
      entity:
        type: bar
```
