### ISSUE TITLE
Broken Line

### ISSUE THREAD

**Issue by Stephan1908** [dbuezas/lovelace-plotly-graph-card#183]
Hello,

I have broken lines in the plot. When I look at the values in Home Assistant's history card, they aren't there.

![grafik](https://user-images.githubusercontent.com/60405276/211385566-e8065f9f-78dd-467a-a19f-927014ab490c.png)

```
type: custom:plotly-graph
entities:
  - entity: sensor.km271_brennerausschalttemperatur
    yaxis: y1
    legendgroup: 1
    name: Ausschalttemperatur
    line:
      width: 1
  - entity: sensor.km271_kesselvorlauftemperatur
    yaxis: y1
    legendgroup: 2
    name: Kesselvorlauftemperatur
    line:
      width: 1
  - entity: sensor.km271_kesselvorlaufsolltemperatur
    yaxis: y1
    legendgroup: 3
    name: Kesselsolltemperatur
    line:
      width: 1
  - entity: sensor.km271_brennereinschalttemperatur
    yaxis: y1
    legendgroup: 4
    name: Brennereinschalttemperatur
    line:
      width: 1
  - entity: sensor.km271_raumsolltemperatur
    yaxis: y1
    legendgroup: 6
    name: Raumsolltemperatur
    line:
      width: 1
  - entity: sensor.km271_aussentemperatur
    yaxis: y1
    legendgroup: 7
    name: Aussentemperatur
    line:
      width: 1
  - entity: sensor.km271_warmwassersolltemperatur
    yaxis: y2
    legendgroup: 8
    name: Warmwassersolltemperatur
    line:
      width: 1
  - entity: sensor.km271_warmwassertemperatur
    yaxis: y2
    legendgroup: 9
    name: Warmwasseristtemperatur
    line:
      width: 1
layout:
  grid:
    rows: 2
    columns: 1
    roworder: top to bottom
  yaxis:
    title:
      text: Heizkreis
  xaxis:
    rangeselector:
      'y': 1.2
      buttons:
        - count: 1
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 7
          step: day
        - count: 14
          step: day
  yaxis2:
    title:
      text: Warmwasser
no_default_layout: true
defaults:
  entity:
    show_value:
      right_margin: 10
  yaxes:
    fixedrange: true
hours_to_show: 6
refresh_interval: 10
```
Version 2.1.0

Thanks for Help
Greetings
Stephan
