### ISSUE TITLE
Line attribute "smoothing" when using "shape: spline" has no effect

### ISSUE THREAD

**Issue by patfelst** [dbuezas/lovelace-plotly-graph-card#185]
To smoth line graphs, I set shape to spline. This works ok, but I wanted to tune the amount of smoothing as documented [here](https://plotly.com/javascript/reference/scatter/#scatter-line-smoothing), however changing the smoothing values seems to have no effect on the line.

Without spline
<img width="433" alt="image" src="https://user-images.githubusercontent.com/11342773/211428578-6da0de99-603b-4a0b-a576-9a0b821f6d7e.png">

With spline and any value of smoothing
<img width="433" alt="image" src="https://user-images.githubusercontent.com/11342773/211428414-c54d8921-9ad8-454a-be45-2a27570b969a.png">

``` yaml
type: custom:plotly-graph
entities:
  - entity: climate.ac_front_lounge
    line:
      color: red
      dash: solid
      shape: spline
      smoothing: 0.5
      width: 1
    attribute: current_temperature
hours_to_show: 24
refresh_interval: 10
period: auto
title: Air con temp sensors
```
Am I doing something wrong, or is this a bug? Thanks for this great HACS add on.
