### ISSUE TITLE
Add a trendline filter

### ISSUE THREAD

**Issue by thecem** [dbuezas/lovelace-plotly-graph-card#187]
**Describe the solution you'd like**
In xls there is a possibility to get a trendline for datapoint’s.
This would be nice if this function could be added.

Background:

To calculate the building heat load or the heating curve of a building (consumption in relation to temperature), every data is in HA, but up to now there is now possibility to do this with LTS-Data in an easy way. With this implementation it could!!!

Why it so important?

To change a heating system’s configuration or even replace it, you need to know the building heat load. Even with the best calculations, there is no way to be as precise as with real data.
With this result it is possibly to optimise the heating system in a easy way.

**How would it be defined in yaml?**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.monthly_internet_energy
     entity_feature_config: xxx
     filters:
       - trendline: linear ## (linear, polynomial, exponential, power series)
global_feature_config: xxx
```

**Scribble**
All trendline are welcome, but a linear should be a good start.
Additional a function to forecast values for x or y based of the trendline function would be nice.

**Additional context**
A greener trendline Funktion could not be in place, since to set the relation of daly consumption to daly average outdoor temperature 🤒 !

A BIG THANK YOU!

**Comment by kaijk** [comment]
This could be a place to start; https://plotly.com/python/linear-fits/

**Comment by dbuezas** [comment]
Progress!
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/777196/215315471-17a2b316-ac04-4400-9b70-57889b3ac62f.png">

**Comment by dbuezas** [comment]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/777196/215334911-f1ad909d-b900-4dc9-b83e-67753e888589.png">

**Comment by dbuezas** [comment]
Closed by the release of v3.0.0

**Comment by dbuezas** [comment]
Let me know if you know of more trendlines, those were very fun to implement and test!

**Comment by thecem** [comment]
I will do as soon I have fixed my basic charts. Then we could present a really complex energy chart easy.

**Comment by r-jean-pierre** [comment]
Hi,

I played and it works!

```yaml
- entity: sensor.waterheater_voltage # sensor.veolia_daily_consumption
      # type: bar
      showlegend: false
      time_offset: -65h
      line:
        width: 2
        shape: linear
      show_value: true
      
      filters:
        # - deduplicate_adjacent
        - store_var: orig
    - entity: ''
      line:
        width: 1
        # shape: linear
      filters:
        - load_var: orig
        - trendline:
            type: polynomial
            forecast: 1d
            degree: 3 
            show_formula: true
            show_r2: true
```
gives already something cool:

![2023-02-07 22_50_28-Window](https://user-images.githubusercontent.com/9727894/217374738-96a22669-8bef-4a64-8994-dbbc5afb75ef.png)

If you still look for challenge, the reasample - interpolate - spline mechanism is +/- what the final user would like to see but don't know how to express it. 
In my example, if I want to fit better the blue curve (increase r-square), it would force me to use a 10+ degree polynomial (-> which is really bad for forecast later)
