### ISSUE TITLE
Support binary sensors

### ISSUE THREAD

**Issue by jazzmonger** [dbuezas/lovelace-plotly-graph-card#193]
**Describe the solution you'd like**
A way to transform a binary sensor so it can be shown near other data
Apex charts does it this way

**How would it be defined in yaml?**
```
type: custom:apexcharts-card
update_delay: 3s
update_interval: 1min
series:
  - entity: binary_sensor.heating
    transform: "return x === 'on' ? 1 : 0;"

```

**Scribble**
When applicable, paste a drawing of how the feature would look like

**Additional context**
