### ISSUE TITLE
Sensor is inverted, then its not... and blank graphs

### ISSUE THREAD

**Issue by jazzmonger** [dbuezas/lovelace-plotly-graph-card#194]
**Describe the bug**
a binary sensor sometimes shows inverted, then hitting reset display shows it correctly

**Screenshots**
Correct:
![image](https://user-images.githubusercontent.com/52110065/213255869-af2070c6-5c30-4dbd-acfe-ed15200f7e42.png)

Incorrect
![image](https://user-images.githubusercontent.com/52110065/213255968-484e606a-8d64-44df-9987-5f0be48ab0bc.png)

Also, often (not always) when I first start home assistant on iOS ipad all the graphs are completely blank. it doesnt matter what I use, Safari, Brave or the naitive ios home assistant app, they all behave the same.  dragging my finger to the right on the graph at least brings back the controls (still a lank graph) and then I can reset the graph making it normal.

**yaml**
```
type: custom:plotly-graph
defaults:
  entity:
    texttemplate: <b> %{y}</b> %{customdata.unit_of_measurement}
    show_value: null
hours_to_show: 4
entities:
  - entity: sensor.esph_house_stove_pipe_temp
    unit_of_measurement: Pipe Temp
    yaxis: y1
    show_value: true
    right_margin: 40
    line:
      color: aqua
      shape: spline
      width: 1
      smoothing: 0
    filters:
      - exponential_moving_average:
          alpha: 1.5
  - entity: binary_sensor.house_stoke_fire_flag
    yaxis: y3
    show_value: true
    right_margin: 40
    line:
      color: red
      dash: dashdot
refresh_interval: 10
default_trace:
  line:
    width: 1
layout:
  height: 500
  yaxis:
    zeroline: false
    fixedrange: true
    range:
      - 100
      - 350
  yaxis2:
    gridcolor: whitesmoke
    fixedrange: true
    zeroline: false
  yaxis3:
    gridcolor: whitesmoke
    zeroline: false
    range:
      - 0
      - 1.5
    fixedrange: true
  grid:
    ygap: 0.07
    rows: 1
    columns: 1
    pattern: coupled
    roworder: top to bottom
  xaxis:
    rangeselector:
      'y': 1.2
      buttons:
        - count: 30
          step: minute
        - count: 1
          step: hour
        - count: 3
          step: hour
        - count: 8
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 2
          step: day
        - count: 7
          step: day

```
type: custom:plotly-graph
entities:
  - entity: sensor.my_sensor
```

**Additional context**
Add any other context about the problem here.

**Comment by dbuezas** [comment]
If you want to fix the order of categorical axes (like on off instead of numbers), you need to do it manually.
Like this but in the y axis https://stackoverflow.com/a/45479905

Otherwise, plotly will use the order they come in.

Regarding the empty plot, I'll take a look, I saw that too a couple of times.

**Comment by dbuezas** [comment]
And thanks for the issue btw :) 
One dedicated issue for each report would be even better

**Comment by jazzmonger** [comment]
> If you want to fix the order of categorical axes (like on off instead of numbers), you need to do it manually.
> Like this but in the y axis https://stackoverflow.com/a/45479905

That doesn't make sense.
It arbitrarily changing by itself.  Sometimes it looks right, others it's inverted.

**Comment by dbuezas** [comment]
You have to set a defined order for non numerical values lile on/off or heat/cold, etc.
Otherwise plotlyjs sorts them in the order it sees them in the data. I sent you a link about how to "fix" or "fixate" the values. It's json instead of yaml, but you'll see what to do if you read it.

**Comment by dbuezas** [comment]
```js
var layout = {
    "xaxis": {
        "categoryorder": "array",
        "categoryarray":  ["A", "B", "C", "D", "E"]
    }
};
```
Translates to 
```yaml
layout:
  xaxis:
    categoryorder: array
    categoryarray:
      - on
      - off
```

**Comment by nebojisa79** [comment]
xaxis doesn't work for me, but yaxis does.
````
layout:
  yaxis:
    categoryorder: array
    categoryarray:
      - false
      - true
````
Thanks @dbuezas
