### ISSUE TITLE
Add a filter to translate y values so they start from 0

### ISSUE THREAD

**Issue by miljbee** [dbuezas/lovelace-plotly-graph-card#195]
Hello,

I am playing with filters, seems great :wink: thx
I plot energy consumption from a total_increasing sensor over certain periods.
the difficulty is to start the graph from zero at the begining of the period, I mean subtracting from all y the first y value.
with the previous version of plotly, I was doing :

```yaml
  - entity: sensor.total_increasing_sensor
    statistic: sum
    period: hour
    lambda: |-
      (ys, xs) => {
        start = ys[0]
        y = ys.map(y => {
          return y-start
        } )
        return { x: xs, y:y}
      }
```

With the new filters, I made this:

```yaml
  - entity: sensor.total_increasing_sensor
    statistic: sum
    period: hour
    filters:
      - force_numeric
      - fn: |-
          ({xs, ys, meta, states, statistics, hass}) => {
            return { ys: ys.map(y => y - ys[0]) } }
```

It does save a few lines, but I have the feeling that it could be simpler.
Have I missed something ?
Perhaps adding a new filter ‘start_y_zero’ or ‘shift_y_zero’ or ‘- add: -1*ys[0]’.

What do you think ?

**Comment by dbuezas** [comment]
I think this is exactly the way to do it :) 
You can shorten it a bit by leaving out the unused parameters:
```yaml
    filters:
      - force_numeric
      - fn: ({ ys }) => ({ ys: ys.map(y => y - ys[0]) })
```

In the next release this will also work:
```yaml
      - force_numeric
      - map_y: y - ys[0]
```

I think this will become easy enough that a new filter would be unnecessary.
