### ISSUE TITLE
Button for browsings days

### ISSUE THREAD

**Issue by xalex75** [dbuezas/lovelace-plotly-graph-card#2]
Hi.
Your graph has the great feature to be able to scroll along the timeline, so I think that a button that can shift the displayed  data +/- 12 or 24 or maybe a configurable amount of hours would be very useful.

Since "hours_to_show" is a configurable parameter, the +/- button could simply move the displayed data forward or back for the value used in "hous_to_show".

Thank you again for this very useful card.

**Comment by dbuezas** [comment]
That's a great idea!
and you can do something quite similar already, try adding this to your yaml:
```yaml
layout:
  xaxis:
    rangeselector:
      buttons:
        - count: 10
          step: minute
          stepmode: backward
        - count: 1
          step: hour
          stepmode: backward
        - count: 2
          step: hour
          stepmode: backward
        - count: 4
          step: hour
          stepmode: backward
        - count: 8
          step: hour
          stepmode: backward
        - count: 1
          step: day
          stepmode: backward
        - count: 7
          step: day
          stepmode: backward
        - count: 30
          step: day
          stepmode: backward
```
Here's what you get:
![image](https://user-images.githubusercontent.com/777196/141507768-6e8766a7-7293-456a-aa64-6a00acb57ca2.png)
Far from perfect (the buttons cover the trace names), but near enough for now :) 

I'll fix a bug and add this as an example this weekend.
