### ISSUE TITLE
"deduplicate_adjacent" filter

### ISSUE THREAD

**Issue by dbuezas** [dbuezas/lovelace-plotly-graph-card#201]
**Describe the solution you'd like**
removes adjacent values if they are equal . 

**How would it be defined in yaml?**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.monthly_internet_energy
     filters: 
       - deduplicate_adjancent
```

**Additional context**
Useful for `type: marker+text`
