### ISSUE TITLE
problems after upgrade

### ISSUE THREAD

**Issue by jazzmonger** [dbuezas/lovelace-plotly-graph-card#225]
**Describe the bug**
ALL my graphos on MACOS have this problem.  Brave and Safari both.  Not iOS - that works fine.

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/52110065/215860578-642e9299-33da-4e18-90ed-aca68022f92d.png">

**Screenshots**

**yaml**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.my_sensor
```

**Additional context**
