### ISSUE TITLE
Universal functions aren't evaluated when in filter parameters

### ISSUE THREAD

**Issue by dbuezas** [dbuezas/lovelace-plotly-graph-card#238]
**Describe the bug**
Instead of being evaluated, the raw string of the function is given as a parameter to the filters

**Screenshots**
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/777196/216809847-765b71fd-c540-4bbd-bbf0-a0cacc235786.png">

**yaml**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.electricity_total
    filters:
      - add: $ex 1
```

**Additional context**
The problem is that the filters are evaluated on the way back of the tree traversal. If the children subtree is a string literal, the result of the function evaluation does not replace the `value` variable, and it has to be picked from `parent[key]` instead.
