### ISSUE TITLE
Secondary y-axis is shifted when I add layout: xaxis

### ISSUE THREAD

**Issue by FSund** [dbuezas/lovelace-plotly-graph-card#243]
**Describe the bug**
If I add for example
```yaml
layout:
  xaxis:
    tickformat: '%H:%M'
```

the title for the secondary y-axis ends up on top of the tick labels.

Without `layout: xaxis`

![image](https://user-images.githubusercontent.com/3352483/217179012-1ff8a01c-bb4d-4a59-960e-784f72ef6c7f.png)

With `layout: xaxis`

![image](https://user-images.githubusercontent.com/3352483/217178841-ef3ee250-5dda-463c-a702-67a0fd1d5fed.png)

The same issue appears if I for example add a yaxis config (from the "now line" example)
```yaml
layout:
  yaxis9:
    visible: false
    fixedrange: true
```

**Screenshots**

**yaml**
```yaml
type: custom:plotly-graph
hours_to_show: current_day
refresh_interval: 10
defaults:
  entity:
    line:
      width: 2
config:
  staticPlot: true

entities:
  - entity: sensor.kaifa_active_power_import
    name: Forbruk
    marker:
      color: '#FF4560'
    statistic: mean
    type: bar
    unit_of_measurement: kW
    filters:
      - map_y_numbers: y/1000.0
  - entity: sensor.nordpool_kwh_krsand_nok_3_10_025
    attribute: raw_today
    name: Pris
    line:
      color: '#008FFB'
    filters:
      - fn: |-
          ({states}) => {
            const ys = [];
            const xs = [];
            let state = states.slice(-1)[0]
            let raw = state.attributes.raw_today
            for (let i = 0; i < raw.length; i++){
              let start = new Date(raw[i].start)
              xs.push(start);
              let end = new Date(raw[i].end)
              xs.push(end);
              ys.push(raw[i].value);
              ys.push(raw[i].value);
            }
            return { xs, ys };
          }
  - entity: sensor.nordpool_kwh_krsand_nok_3_10_025
    attribute: raw_tomorrow
    name: Pris i morgen
    line:
      color: '#00E396'
    filters:
      - fn: |-
          ({states}) => {
            const ys = [];
            const xs = [];
            let state = states.slice(-1)[0]
            let raw = state.attributes.raw_tomorrow
            for (let i = 0; i < raw.length; i++){
              let start = new Date(raw[i].start)
              start.setDate(start.getDate() - 1); // subtract one day
              xs.push(start);
              end = new Date(raw[i].end)
              end.setDate(end.getDate() - 1); // subtract one day
              xs.push(end);
              ys.push(raw[i].value);
              ys.push(raw[i].value);
            }
            return { xs, ys };
          }

```

**Additional context**

**Comment by FSund** [comment]
I'm kind of able to fix it with the following config, with the downside that I have to manually set the y-axis label.

```yaml
layout:
  xaxis:
    tickformat: '%H:%M'
  yaxis2:
    title:
      text: "NOK/kWh"
      standoff: 10
    autoshift: true
    anchor: 'free'
```

![image](https://user-images.githubusercontent.com/3352483/217184158-81c37c5f-975f-4ecd-95b0-761863f6d17c.png)

**Comment by FSund** [comment]
I was able to fix it in a more flexible way, by adding `yaxis: y` and `yaxis: y2` to the respective entities (and keeping `yaxis: y9` for the "now" line). Perhaps this is useful for fixing the underlying issue?

Here's the result:
![image](https://user-images.githubusercontent.com/3352483/217212809-1dc0eca3-a94d-4b84-abd0-9daf96f06fec.png)

Full card config:
```yaml
type: custom:plotly-graph
hours_to_show: current_day
refresh_interval: 10
defaults:
  entity:
    line:
      width: 2
config:
  staticPlot: true
layout:
  xaxis:
    tickformat: '%H:%M'
  yaxis9:
    visible: false
    fixedrange: true
    range: [0,1]
entities:
  - entity: sensor.kaifa_active_power_import
    name: Forbruk
    yaxis: y
    marker:
      color: '#FF4560'
    statistic: mean
    type: bar
    unit_of_measurement: kW
    filters:
      - map_y_numbers: y/1000.0
  - entity: sensor.nordpool_kwh_krsand_nok_3_10_025
    attribute: raw_today
    name: Pris
    yaxis: y2
    line:
      color: '#008FFB'
    filters:
      - fn: |-
          ({states}) => {
            const ys = [];
            const xs = [];
            let state = states.slice(-1)[0]
            let raw = state.attributes.raw_today
            for (let i = 0; i < raw.length; i++){
              let start = new Date(raw[i].start)
              xs.push(start);
              let end = new Date(raw[i].end)
              xs.push(end);
              ys.push(raw[i].value);
              ys.push(raw[i].value);
            }
            return { xs, ys };
          }
  - entity: sensor.nordpool_kwh_krsand_nok_3_10_025
    attribute: raw_tomorrow
    name: Pris i morgen
    yaxis: y2
    line:
      color: '#00E396'
    filters:
      - fn: |-
          ({states}) => {
            const ys = [];
            const xs = [];
            let state = states.slice(-1)[0]
            let raw = state.attributes.raw_tomorrow
            for (let i = 0; i < raw.length; i++){
              let start = new Date(raw[i].start)
              start.setDate(start.getDate() - 1); // subtract one day
              xs.push(start);
              end = new Date(raw[i].end)
              end.setDate(end.getDate() - 1); // subtract one day
              xs.push(end);
              ys.push(raw[i].value);
              ys.push(raw[i].value);
            }
            return { xs, ys };
          }
  - entity: ""
    name: Now
    yaxis: y9
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: $ex [Date.now(), Date.now()]
    y: [0, 1]

```

**Comment by dbuezas** [comment]
This looks like a bug in plotlyjs, but I'll take a look to make sure it's not me (this card).
You could also try setting the right margin manually, which is set automatically by the card depending on if any entity uses the y2 axis, but you can override it like this:
```yaml
layout:
  margin:
    r: 60
```

Congratulations on posting the issue #100 by the way 😁

**Comment by dbuezas** [comment]
Interesting, I can't reproduce this. I removed the filters and plugged some thermometers and I get this:
<img width="506" alt="image" src="https://user-images.githubusercontent.com/777196/217344972-21a7635a-1869-40de-ae45-9f6d6b4083d7.png">
Note I added the **now line** and the right margin still looks intact.
Which version of the card are you using? Are you sure it is the latest one?

**Comment by dbuezas** [comment]
On a side note, nice job transforming the data from the attribute, power user 💪!
Just watch out on the missing "let" for the `end` variable, and missing semicolons at the end. On certain cases the missing semicolon results in very unexpected behaviour (two statements in two lines end up being interpreted as a single one in ways one doesn't expect)

**Comment by FSund** [comment]
I'm on v3.3.1 via HACS. I'll try to make a simpler example and see if something different happens.

Thanks for the JS pointers! It's pretty hard to debug JavaScript inside YAML :D

**Comment by FSund** [comment]
I managed to reproduce it 

![image](https://user-images.githubusercontent.com/3352483/217449035-9004d80e-e19b-45db-9c60-06d825b6e17d.png)

```yaml
type: custom:plotly-graph
hours_to_show: current_day
layout:
  xaxis:
    tickformat: '%H:%M'
entities:
  - entity: sensor.waveplus_temperature
  - entity: sensor.waveplus_humidity
```

If I remove the `layout`-section it looks as expected

![image](https://user-images.githubusercontent.com/3352483/217449211-3ff07b1d-115a-4a29-849b-872c5c06c855.png)

I've cleared my cache and done hard refreshes, but the bug still appears.
