### ISSUE TITLE
statistics: 'all' for measurements

### ISSUE THREAD

**Issue by Rvh91** [dbuezas/lovelace-plotly-graph-card#247]
**Describe the solution you'd like**
Inspired by the [example given by r-jean-pierre](https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/81#discussioncomment-3984546). 
It would be great if it was possible to add an additional option for statistics for measurements, where we can select 'all' instead of 'min', 'max', 'mean'.  This would then display for each entity a single line for the mean values, and a shaded area that covers the range from min to max. This type of plot is essentially what is also used by the sensor plots in home assistant, where the shaded area is used to represent the range in which the measurements are made.

some considerations:
- The 'mean' line is treated as the 'base', meaning that for example 'show_value' is enabled it only shows it for the mean line by default. Also in the legend only the 'mean' line is showed, and if it is toggled, the shaded area associated with the min/max is also toggled.
- The color of the shaded area would follow that of the color from the 'mean' line, and ideally have some opacity or shaded slightly lighter. The lines for min and max should be thin and slightly darker than the shaded fill area.
- If for example a 'spline' is specified for the line associated to this entity, this specification would also be inherited by the min and max lines.

**How would it be defined in yaml?**
```yaml
entities:
  - entity: sensor.temperature
    statistic: all # `min`, `mean` `max` of 'all'
```

**Scribble**
for example as in [example given by r-jean-pierre](https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/81#discussioncomment-3984546):
![image](https://user-images.githubusercontent.com/99890657/217349178-cfd76b4f-9b3d-4fd6-882e-f524ce9d2e4d.png)

**Additional context**

**Comment by dbuezas** [comment]
Interesting yaml proposal, this is quite different from anything we've got because a single entity would generate 3 traces. I'll give it a shot when I have some time. It may get messy when configuring it, particularly for filters, but maybe it works ok. Configs would be applied equally to all traces, except maybe for show_value and the fill color.

The only issue I have with this is that it goes against a general principle I'm trying to maintain, which is to expose plotly more or less as directly as possible.

If any other user reads this, please do drop some opinion and/or ideas.

**Comment by dbuezas** [comment]
Oh, one extra consideration: 
Some statistics don't have min/max/mean, but have sum and state instead. This may generate some confusion.

**Comment by Rvh91** [comment]
> Interesting yaml proposal, this is quite different from anything we've got because a single entity would generate 3 traces. I'll give it a shot when I have some time. It may get messy when configuring it, particularly for filters, but maybe it works ok. Configs would be applied equally to all traces, except maybe for show_value and the fill color.
> 
> The only issue I have with this is that it goes against a general principle I'm trying to maintain, which is to expose plotly more or less as directly as possible.
> 
> If any other user reads this, please do drop some opinion and/or ideas.

I can imagine that if it gets to messy it might become to convoluted indeed. I have not played around yet with filters, so it's hard for me to grasp where exactly it would fall apart. If we do filters like offsets or moving averages for example, those would be applied to the values contained in the long term statistics I guess? As a first start I would indeed apply those to the three traces equally. I don't directly see an application where you would want to filter the statistics, but that is probably my lack of imagination.

> Oh, one extra consideration: Some statistics don't have min/max/mean, but have sum and state instead. This may generate some confusion.

As far as I understand the sum and state would be for the statistics in the case of state_class=total, wheras my proposal would only apply to those where state_class = measurement. So for those entities with state_class = total, this 'all' option would not apply. Out of curiosity, what happens if you set statistics: mean, for an entity with state_class = total? Perhaps we can handle the new case in a similar way?

So Essentially in the doc we would get:

for entities with state_class=measurement (normal sensors, like temperature)
```
type: custom:plotly-graph
entities:
  - entity: sensor.temperature
    statistic: max # `min`, `mean` `max` of 'all'
    period: 5minute # `5minute`, `hour`, `day`, `week`, `month`, `auto` # `auto` varies the period depending on the zoom level
```
and this would remain the same:
for entities with state_class=total (such as utility meters) 
```
type: custom:plotly-graph
entities:
  - entity: sensor.temperature
    statistic: state # `state` or `sum`
```

**Comment by r-jean-pierre** [comment]
Hi guys!

I vote +1 for any improvement reducing the number of lines I had to wrote :-)

If you want something challenging and more general, I have something to "propose":  in my own perfect world of numpy-pandas-seaborn, I spend my entire day of grouping data per "something", and then displaying a trend inside an "error" band. For example, when you helped me here:   #229 my ultimate dream is to group by day of week, plot the median as a main trend and display for example the 10 - 90 percentiles

A simple
```
sns.lineplot(data=data, x="day", y="y", 
             estimator=lambda x: np.median(x),
             errorbar=lambda x: (np.percentile(x, 10), np.percentile(x, 90)))
```
Already gives
![Figure_1](https://user-images.githubusercontent.com/9727894/217361158-e0c84a66-3937-4494-8ffe-86cc3d1fb8a2.png)

which is, at least for me, beautiful enough while having tiny code to maintain and still open to custom functions to really focus on different statistics rather than tweaking pixels...)
So if you have plans like this, I will add a +1 also!

Note that I grouped on a "fake" categorical variable which is the day of week, but in general I do the same on rolling window over timestamp which I suppose is more interesting for HA community

**Comment by r-jean-pierre** [comment]
> Interesting yaml proposal, this is quite different from anything we've got because a single entity would generate 3 traces. I'll give it a shot when I have some time. It may get messy when configuring it, particularly for filters, but maybe it works ok. Configs would be applied equally to all traces, except maybe for show_value and the fill color.
> 
> The only issue I have with this is that it goes against a general principle I'm trying to maintain, which is to expose plotly more or less as directly as possible.
> 
> If any other user reads this, please do drop some opinion and/or ideas.

I think it won't be a piece of cake, I far I know, there no one-line-method to solve it in plotly, the closest is this: [https://plotly.com/python/continuous-error-bars/](url) which forces the developer to use plotly.graph_objs and not plotly.express, and in general the developer has also to precompute the statistics before with pandas for example for python guys
Unless I missed the perfect solution, it's also quite a headache to handle missing values, maintain the legend, smooth the lines, etc.

**Comment by dbuezas** [comment]
> there no one-line-method to solve it in plotly

Yeah, I'm not aware of any plotly feature to do this either. What I have in mind is to generate 3 independent traces and then style them via `fill: tonexty` (like in the link you posted or your original plot actually, the one with the popular screenshot :) )

**Comment by dbuezas** [comment]
> my ultimate dream is to group by day of week, plot the median as a main trend and display for example the 10 - 90 percentiles

This sounds kind of similar to the heatmap example here: https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/215

I could could potentially add 2 filters to compute the lower and upper limits of a parametrisable percentile. Something like:
```yaml
- entity: sensor.temperature
   filters:
    - error_band: # <-- how would you name this?
         window_size: 10
         percentile: 10 #<-- and this?
- entity: sensor.temperature
   filters:
    - error_band:
         window_size: 10
         percentile: 90
- entity: sensor.temperature
   filters:
    - error_band:
         window_size: 10
         percentile: 50 # <-- which would equal the mean
```
This is kind of different to what this feature request aims at, but would this help with your dream @r-jean-pierre ?
