### ISSUE TITLE
Bar chart does not update on "always on" Android tablet

### ISSUE THREAD

**Issue by FSund** [dbuezas/lovelace-plotly-graph-card#250]
**Describe the bug**
I have an Android tablet that I use do display my Home Assistant dashboard. I've checked "keep screen on" option in the HA companion app.

The red bars ("Forbruk") in the attached screenshot does not seem to update correctly when the screen is left on, and I have to manually close and reopen the app to fix this. I have highlighted the area with missing bars in the screenshot.

This might appear on other devices/interfaces other than Android tablets, but it's the only device I have that is kept on and not interacted with for long periods :)

**Screenshots**
![image](https://user-images.githubusercontent.com/3352483/218656424-d7024323-a60c-4786-846b-0103a0b0ec54.png)

**yaml**

The full config is pretty complex, but the config for the red bars is pretty standard

The only thing I can think of that might be causing an issue is `xperiod: 3600000`, which I've used to align the bars in the center between full hours, instead of _on_ each hour.

```yaml
  - entity: sensor.kaifa_active_power_import
    name: Forbruk
    yaxis: 'y'
    marker:
      color: '#FF4560'
    xperiod: 3600000
    statistic: mean
    period: hour
    type: bar
    unit_of_measurement: kWh
    filters:
      - map_y_numbers: y/1000.0
```

Full config:

```yaml
type: custom:plotly-graph
title: Strømpris og forbruk
hours_to_show: current_day
refresh_interval: 300
defaults:
  entity:
    line:
      width: 2
config:
  staticPlot: true
layout:
  height: 320
  xaxis:
    tickformat: '%H:%M'
    tickangle: -45
    dtick: 10800000
    minor:
      showgrid: true
      griddash: dot
      dtick: 3600000
      gridcolor: '#00000020'
      ticks: outside
  yaxis:
    title:
      font:
        color: '#FF4560'
      text: Forbruk (kWh)
  yaxis2:
    title:
      text: Pris (kr/kWh)
    tickmode: sync
    tickformat: .2f
  yaxis3:
    visible: false
    range:
      - 0
      - 1
  yaxis9:
    visible: false
    range:
      - 0
      - 1
entities:
  - entity: sensor.kaifa_active_power_import
    name: Forbruk
    yaxis: 'y'
    marker:
      color: '#FF4560'
    xperiod: 3600000
    statistic: mean
    period: hour
    type: bar
    unit_of_measurement: kWh
    filters:
      - map_y_numbers: y/1000.0
  - entity: sensor.hourly_cumulative_power_import
    xperiod: 3600000
    yaxis: 'y'
    showlegend: false
    type: bar
    filters:
      - fn: |-
          ({states}) => {
            const state = states.slice(-1)[0];
            const ys = [state.state];
            let d = new Date(state.last_changed);
            //d.setHours(d.getHours(), 30, 0, 0); // 30 minutes to center bar on period
            d.setHours(d.getHours(), 0, 0, 0); // use xperiod unstead of 30 minutes offset
            const xs = [d];
            return { xs, ys };
          }
  - entity: sensor.nordpool_kwh_krsand_nok_3_10_025
    attribute: raw_today
    name: Pris
    yaxis: y2
    line:
      color: '#008FFB'
    filters:
      - fn: |-
          ({meta}) => {
            const ys = [];
            const xs = [];
            //let state = states.slice(-1)[0];
            let raw = meta.raw_today;
            for (let i = 0; i < raw.length; i++){
              let start = new Date(raw[i].start);
              xs.push(start);
              let end = new Date(raw[i].end);
              xs.push(end);
              ys.push(raw[i].value);
              ys.push(raw[i].value);
            }
            return { xs, ys };
          }
  - entity: sensor.nordpool_kwh_krsand_nok_3_10_025
    attribute: raw_tomorrow
    name: Pris i morgen
    yaxis: y2
    line:
      color: '#00E396'
    filters:
      - fn: |-
          ({meta}) => {
            const ys = [];
            const xs = [];
            //let state = states.slice(-1)[0];
            let raw = meta.raw_tomorrow;
            for (let i = 0; i < raw.length; i++){
              let start = new Date(raw[i].start);
              start.setDate(start.getDate() - 1); // subtract one day
              xs.push(start);
              let end = new Date(raw[i].end);
              end.setDate(end.getDate() - 1); // subtract one day
              xs.push(end);
              ys.push(raw[i].value);
              ys.push(raw[i].value);
            }
            return { xs, ys };
          }
  - entity: sensor.ps_lowest_price_output
    attribute: schedule
    yaxis: y3
    name: Strømsparing
    fill: tozeroy
    fillcolor: '#00FF0025'
    line:
      width: 0
    filters:
      - fn: |-
          ({states, meta}) => {
            const ys = [];
            const xs = [];
            let schedule = meta.schedule;
            for (let i = 0; i < schedule.length; i++){
              let start = new Date(schedule[i].time);
              xs.push(start);
              ys.push(schedule[i].value);
            }
            // extend to midnight
            let end = new Date(schedule.slice(-1)[0].time);
            end.setDate(end.getDate() + 1);
            xs.push(end);
            ys.push(schedule.slice(-1)[0].value);

            return { xs, ys };
          }
  - entity: ''
    name: Now
    yaxis: y9
    showlegend: false
    line:
      width: 1
      color: deepskyblue
      dash: dash
    x: $ex [Date.now(), Date.now()]
    'y':
      - 0
      - 1
```

**Additional context**

**Comment by dbuezas** [comment]
Interesting, can you try changing to "refresh_interval: auto"?
This will use updates coming to from the websocket instead of actively making requests. If this behaves differently, it may ve a clue as to what's going wrong

**Comment by FSund** [comment]
I'll try auto, thanks!

The "now" line and rightmost, orange bar (`sensor.hourly_cumulative_power_import`) do update, by the way, if that helps.

**Comment by jazzmonger** [comment]
Im having the same issue.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/52110065/218837186-789c7ebe-abca-4197-8c8f-484bab6ed53f.png">

you can see all values flatline after a minute or so.  then I have to reload the page.  happens on all devices, all browsers.

setting it to :auto seems to resolve it, but it is nice having granular control over update time.  some graphs you really want more realtime info, other can go hours before you need an update.

**Comment by dbuezas** [comment]
> other can go hours before you need an update

Note that `auto` does exactly that automatically. It receives updates pushed directly from home assistant. The only reason I left the update_interval option is for compatibility with the standard history card. I'll look into it when I have time, but don't be afraid of using `auto` :)

**Comment by FSund** [comment]
Quick update: `auto` does not seem to resolve the issue on the tablet. Any debugging steps I can do?

**Comment by dbuezas** [comment]
That's super odd!
* What OS does the table have? 
* Do you use the HA app or a browser (which?)
* What kinds of entities does is happen with? (statistics, periods, etc)
* Is it consistent?
* Anything else you can provide

**Comment by jazzmonger** [comment]
Auto works great.  I changed all my graphs to use that.  

> On Feb 16, 2023, at 1:50 PM, David Buezas ***@***.***> wrote:
> 
> ﻿
> other can go hours before you need an update
> 
> Note that auto does exactly that automatically. It receives updates pushed directly from home assistant. The only reason I left the update_interval option is for compatibility with the standard history card. I'll look into it when I have time, but don't be afraid of using auto :)
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.

-- 


This message may contain confidential and/or privileged information. If 
you are not the addressee or are not authorized to receive this for the 
addressee, you must not use, copy, disclose, or take any action based on 
this message or any information herein. If you have received this message 
in error, please advise the sender immediately by reply email and delete 
this message.

**Comment by FSund** [comment]
> That's super odd!
> 
> * What OS does the table have?

Android 12

> * Do you use the HA app or a browser (which?)

I'm using the HA app.

I'll try using [Wallpanel](https://github.com/TheTimeWalker/wallpanel-android) today and see if anything changes.

> * What kinds of entities does is happen with? (statistics, periods, etc)

It seems to only happen to the statistics entity

```yaml
  - entity: sensor.kaifa_active_power_import
    name: Forbruk
    yaxis: 'y'
    marker:
      color: '#FF4560'
    xperiod: 3600000
    statistic: mean
    period: hour
    type: bar
    unit_of_measurement: kWh
    filters:
      - map_y_numbers: y/1000.0
```

> * Is it consistent?

Yes, it's been happening since I created the plot about two weeks ago.
