### ISSUE TITLE
Static chart support

### ISSUE THREAD

**Issue by r03n-d** [dbuezas/lovelace-plotly-graph-card#251]
**Describe the solution you'd like**
Plotly supports "static chart" using the `staticPlot: true` arguement. I would like this to be added to to plotly lovelace card too.

**How would it be defined in yaml?**
```yaml
type: custom:plotly-graph
entities:
  - entity: xxx
    entity_feature_config: xxx
global_feature_config: 
    static_chart: true
```

**Additional context**
Plotly example: https://plotly.com/javascript/configuration-options/#making-a-static-chart

**Comment by dbuezas** [comment]
Hi 👋 

you are in luck: you can customise the `config` parameter (the third argument passed to plotly) like this:

```yaml
config:
  staticPlot: true
```
@FSund also used that in [this](https://github.com/dbuezas/lovelace-plotly-graph-card/issues/243) discussion. Also I've seen it used inside the layout [here](https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/241#discussioncomment-4894188).

**Comment by dbuezas** [comment]
By the way, consider these alternatives:
```yaml
defaults:
  yaxes: 
    fixedrange: true
```
