### ISSUE TITLE
When data is generated by a filters-fn combination, then the show show_value displays the first timestamp and not the last one

### ISSUE THREAD

**Issue by r-jean-pierre** [dbuezas/lovelace-plotly-graph-card#256]
**Describe the bug**

If data is built from a filters-fn combo, e.g.
```yaml
filters:
  - fn: |-
      ({ meta }) => ({
        xs: meta.dailyweek.map((date) => new Date(date)-3600*1000),
        ys: meta.dailyweek_HP.map((value) => value)
      })
```
then the value of the first timestamp is displayed and not the last one as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/9727894/222273420-fd747786-193d-4cd2-a4e7-8919ed2dec55.png)

**Comment by dbuezas** [comment]
Interesting. This should actually work. Could it be that the x axis is backwards?
Please try with this:
```yaml
({ meta }) => ({
        xs: meta.dailyweek.map((date) => new Date(date)-3600*1000).reverse(),
        ys: meta.dailyweek_HP.map((value) => value).reverse()
      })
```

**Comment by r-jean-pierre** [comment]
Yes it works!

![image](https://user-images.githubusercontent.com/9727894/222277162-65372926-5259-4d83-bb71-e3c09b440937.png)

**Comment by dbuezas** [comment]
Cool!
BTW, I think your left margin would look better with a slightly larger margin

**Comment by r-jean-pierre** [comment]
> Cool! BTW, I think your left margin would look better with a slightly larger margin

![image](https://user-images.githubusercontent.com/9727894/222280735-55d25d1d-8bee-4926-9d3d-af7ff66faa37.png)

Like this (equals green distances?)

**Comment by dbuezas** [comment]
I mean
```yaml
layout:
  margin:
    l: 60
```

so the kWh axis title has some breading space. hehe
