### ISSUE TITLE
The legend of the datapoint corresponding to show_value is polluted when data is generated by a filters-fn combination

### ISSUE THREAD

**Issue by r-jean-pierre** [dbuezas/lovelace-plotly-graph-card#257]
**Describe the bug**
Only if data is generated by `filters-fn`, the legend of the first point (`show_value`) gets extra information from I suppose the underlying-fake-scatterplot

**Screenshots**
![image](https://user-images.githubusercontent.com/9727894/222274598-a85c4c18-6d4d-4f4d-ada2-7a9c85f33d5b.png)

while other data points are perfect:
![image](https://user-images.githubusercontent.com/9727894/222274628-75e86ed3-7f9f-4441-92dd-d154966b7f79.png)

**yaml**
```yaml
filters:
  - fn: |-
      ({ meta }) => ({
        xs: meta.dailyweek.map((date) => new Date(date)-3600*1000),
        ys: meta.dailyweek_HP.map((value) => value)
      })
```

**Comment by dbuezas** [comment]
Interesting, I do add `hoverinfo: 'skip'` on the "fake" traces used for `show_value`
https://github.com/dbuezas/lovelace-plotly-graph-card/blob/master/src/parse-config/parse-config.ts#LL208C22-L208C22

Is there anything special in the rest of the yaml?

**Comment by r-jean-pierre** [comment]
> Interesting, I do add `hoverinfo: 'skip'` on the "fake" traces used for `show_value` https://github.com/dbuezas/lovelace-plotly-graph-card/blob/master/src/parse-config/parse-config.ts#LL208C22-L208C22
> 
> Is there anything special in the rest of the yaml?

except:
`hovermode: "x unified"`
and a personal `hovertemplate`, i really have nothing special

**Comment by dbuezas** [comment]
Uhm. The hovertemplate may be overriding it.
I could add an extra property to remove the hovertemplate from the "fake" trace I use for `show_value`. Can you check if removing "hovertemplate" from the entity makes it disappear?

**Comment by r-jean-pierre** [comment]
So, almost sure that it's not related to the templating, here is a minimalistic, but complete, example:

```yaml
  - type: custom:plotly-graph  # test nrj
    entities:
    - entity: sensor.myenedis_05606946388355
      filters:
        - fn: |-
            ({ meta }) => ({
              xs: meta.dailyweek.map((date) => new Date(date)-3600*1000).reverse(),
              ys: meta.daily.map(value => value).reverse()
            })
      show_value: true
    - entity: sensor.myenedis_05606946388355
      filters:
        - fn: |-
            ({ meta }) => ({
              xs: meta.dailyweek.map((date) => new Date(date)-3600*1000).reverse(),
              ys: meta.daily.map(value => value).reverse()
            })
      show_value: true

    layout:
      hovermode: "x unified"    # -> this option is guilty

    hours_to_show: 180h
    time_offset: -30h
```

![image](https://user-images.githubusercontent.com/9727894/222369312-ac039005-2685-4bab-8528-f78f10295635.png)

if i use the default hovermode, than it is what could be expected:
![image](https://user-images.githubusercontent.com/9727894/222369563-d4fcea8e-d84d-4e40-a097-c07d8a1461ea.png)
![image](https://user-images.githubusercontent.com/9727894/222369669-45d39e8c-adc5-4c6e-a33c-9175d66edeb8.png)
