### ISSUE TITLE
Add markers point on lineplot (but let it optional), as it could be done in python-ploty

### ISSUE THREAD

**Issue by r-jean-pierre** [dbuezas/lovelace-plotly-graph-card#258]
**Describe the solution you'd like**
In plotly documentation (https://plotly.com/python/line-charts/) it seems that we can put markers on top of line (e.g: `px.line(df, x='year', y='lifeExp', color='country', markers=True)` ), could it be possible with the card? 

**Scribble**
If possible, it would display that:
![image](https://user-images.githubusercontent.com/9727894/222275828-94ece361-48e1-417a-94e1-e5514474e223.png)

**How would it be defined in yaml?**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.monthly_internet_energy
    line:
      markers: true
```
