### ISSUE TITLE
Display min and max values on top of the trace as text, at the correct x positions

### ISSUE THREAD

**Issue by r-jean-pierre** [dbuezas/lovelace-plotly-graph-card#259]
**Describe the solution you'd like**
If not already asked, can we have the min and max value text on top of the curve?" it seems that plotly do not have this option right out the box, but they suggest to the users to construct this feature with the add_annotation feature (https://plotly.com/python/text-and-annotations/)
and then, a possible result could be equivalent to:

![image](https://user-images.githubusercontent.com/9727894/222281769-d9d16b49-83d4-4494-ac51-e92d4ee4786e.png)

**How would it be defined in yaml?**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.monthly_internet_energy
    show_extremas: true
```

**Comment by dbuezas** [comment]
wdyt about `show_extrema` or `show_extremes` or `show_min_max_value` ?

**Comment by r-jean-pierre** [comment]
All of them are okay. As a lazy boy I did the concatenation of
```
show:
  extremas: true
```
from the apex-charts card into show_extremas

But now I just realized that's wrong extrema**s**  with the S, it's a latin word, so:  1 extremum, several extrema, so apex-charts writes it wrong :)

**Comment by dbuezas** [comment]
exactly!

**Comment by Heppi911** [comment]
I would love this feature as well. Same reason in my case. I want to move from ApexCharts to Plotly in home-assistant, but I miss these extrema feature. Especially because the tap to show datapoint info does work acceptable on mobile app.

**Comment by dbuezas** [comment]
@Heppi911 In the meantime you can use 
```yaml
entities:
  - entity: sensor.xxx
    statistic: max
    fill: tonexty
entities:
  - entity: sensor.xxx
    statistic: min
    fill: tonexty
```
