### ISSUE TITLE
Text sensor on graphs 

### ISSUE THREAD

**Issue by jazzmonger** [dbuezas/lovelace-plotly-graph-card#265]
**Describe the solution you'd like**

I have complex logic for several sensors that I track in in a graph.  One of them is a text sensor that changes state from idle/heat/cool/off and I'd like to be able to illustrate that in a graph WITH the text. Of course I can represent that with a 1/2/3/4 step function, but knowing when that sensor changes and what the state is would be very cool.

**How would it be defined in yaml?**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.monthly_internet_energy
     entity_feature_config: xxx
global_feature_config: xxx
```

**Scribble**
When applicable, paste a drawing of how the feature would look like 

I'd like to annotate the changing state on a line at the bottom of this graph:

![517E0B54-E982-4826-A965-36755D59221E](https://user-images.githubusercontent.com/52110065/229415794-5321e172-2569-42c9-b1db-13de53490959.jpeg)

**Additional context**
