### ISSUE TITLE
customdata.name not properly replaced in hovertemplate

### ISSUE THREAD

**Issue by CendaL** [dbuezas/lovelace-plotly-graph-card#282]
**Describe the bug**
customdata.name not properly replaced in hovertemplate - the template text is not replaced but the actual value is appended to it:
`%{customdata.name}` -> `%{customdata.name} Konvice`

**Screenshots**
![image](https://user-images.githubusercontent.com/840665/236834118-da99f03f-7e5c-48cb-a502-8f0a1c2605a1.png)

**yaml**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.konvice_energy
    statistic: state
    name: Konvice
    period:
      0s: hour
      3d: day
      2M: month
    type: bar
    texttemplate: '%{y}'
    hovertemplate: '%{customdata.name}<br><i>%{x}</i><br>%{y} Wh'
    filters:
      - delta
      - map_y_numbers: Math.round(y*10000, 1)/10
```

**Comment by dbuezas** [comment]
Oh, yes, thank you. That example became out of date.
PRs welcome :) 
in your example you are filling customdata but then not using it. I suggest to either:
* not fill customdata, or
* fill it only with what will be used (i.e `name`) and then using that in the hovertemplate. (This way is less misterious for newcomers)

**Comment by CendaL** [comment]
Ah - I forgot to change `hovertemplate` back to use variable. But I cannot make it work.

I've tried

```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.konvice_energy
    statistic: state
    name: Konvice
    period:
      0s: hour
      3d: day
      2M: month
    type: bar
    texttemplate: '%{y}'
    hovertemplate: <b>%{name}</b><br><i>%{x}</i><br>%{y} Wh <extra></extra>
    filters:
      - delta
      - map_y_numbers: Math.round(y*10000, 1)/10
hours_to_show: 18
```
![image](https://user-images.githubusercontent.com/840665/236913947-f6c04c0b-7060-4bae-aacf-dfbf0da9449f.png)
and warning: **Variable 'name' in hovertemplate could not be found!**

Nor custom data:
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.konvice_energy
    statistic: state
    name: Konvice
    period:
      0s: hour
      3d: day
      2M: month
    type: bar
    texttemplate: '%{y}'
    customdata: |
      $fn () => {name: 'Konvice'}
    hovertemplate: <b>%{customdata.name}</b><br><i>%{x}</i><br>%{y} Wh <extra></extra>
    filters:
      - delta
      - map_y_numbers: Math.round(y*10000, 1)/10
hours_to_show: 18
```
or
```yaml
    customdata:
      name: Konvice
```
![image](https://user-images.githubusercontent.com/840665/236916288-b6bce886-1af8-4af4-82c9-e3f7d82015b4.png)

It seems to me that nothing except `%{x}`, `%{y}` is replaced with value...
