### ISSUE TITLE
reset_every filter does not consider start of [day|week|month]

### ISSUE THREAD

**Issue by JvdMaat** [dbuezas/lovelace-plotly-graph-card#290]
**Describe the bug**
When using a filter and using the reset_every setting, it resets everything based on current day

**yaml**
```
filters:
  - derivate
  - integrate:
      reset_every: 1M # 1 month (Should reset on 1st of month, but resets today instead)
```
