### ISSUE TITLE
Data not being updated on real time

### ISSUE THREAD

**Issue by Seba-VT** [dbuezas/lovelace-plotly-graph-card#302]
**Describe the bug**
The data is not updating in real-time. When I click refresh, it plots all the historical data, but there is a flat line displayed where the new data should be.

**Screenshots**
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/67033534/08ca6511-97b1-4c44-9b1a-d0abb5866a9a)
red line represents when I hit refresh (F5).

On top is the Plotly and below the default lovelace graph.

**yaml**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.master_bedroom_detection_value
  - entity: number.master_bedroom_presence_off_detection_threshold
hours_to_show: 0.1
refresh_interval: 0.5
autorange_after_scroll: true
layout:
  height: 500
  xaxis:
    rangeselector:
      'y': 1.2
      buttons:
        - count: 1
          step: minute
        - count: 10
          step: minute
        - count: 1
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
```

**Additional context**
