### ISSUE TITLE
Pie chart not working

### ISSUE THREAD

**Issue by plord12** [dbuezas/lovelace-plotly-graph-card#333]
**Describe the bug**
Trying to create a pie chart appears to fail.  No errors reported in console log.

**Screenshots**
Just a blank screen.

**yaml**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.arm3_cpu_used_percent
    type: pie
hours_to_show: 24
refresh_interval: 10
```

**Additional context**
I couldn't find any docs or examples on how to create a pie chart (in yaml) so I'm guessing a bit.

**Comment by dbuezas** [comment]
Pie charts work differently, there are no x and y arrays.
You need to use universal functions ($fn or $ex) to massage the data into values and labels. Search the readme of this repo and see this: https://plotly.com/javascript/pie-charts/

Please do post your results! :)

**Comment by plord12** [comment]
Thanks for the hinds ... although still challenging to figure out I now have -

```
type: custom:plotly-graph
entities:
  - entity: sensor.octopus_peak_energy_daily
    type: pie
    values: >-
      $ex [ hass.states["sensor.octopus_peak_energy_daily"].state,
      hass.states["sensor.octopus_offpeak_energy_daily"].state,
      hass.states["sensor.myenergi_libbi_solar_generation_today"].state ]
    labels:
      - Grid Peak
      - Grid Offpeak
      - Solar
    marker:
      colors:
        - red
        - green
        - orange
    textinfo: value+percent
hours_to_show: 24
refresh_interval: 10
```

<img width="328" alt="Screenshot 2023-11-26 at 13 43 09" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/63543143/b5418c22-814e-4abc-8020-e9628a388749">
