### ISSUE TITLE
Edition window moves under Safari

### ISSUE THREAD

**Issue by ooii** [dbuezas/lovelace-plotly-graph-card#340]
**Describe the bug**
When editing a card under Safari, the edition window moves which makes it difficult to edit.

**Screenshots**
![plotly](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/6420072/445bf743-53b5-469d-a797-b3b6986cca4e)

**yaml**
```yaml
type: custom:plotly-graph
hours_to_show: 22
title: Delta
entities:
  - entity: sensor.delta_temp
    fill: tonexty
    fillcolor: rgba(0, 255, 100, 0.3)
    line:
      color: rgba(0, 255, 100, 1)
```

**Additional context**
Tried with refresh_rate to 0, same issue. Whatever the code.
Note that it may stop moving then it restarts when navigating in the code.
