### ISSUE TITLE
Range of data not updating when zooming out

### ISSUE THREAD

**Issue by Kroonos** [dbuezas/lovelace-plotly-graph-card#350]
**Describe the bug**
the range of the data doesn't update when zooming out. it 's stuck on the "hours to show" range

**Screenshots**
![Screenshot_20240104-100803](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/34813104/1f1c1dda-f8fc-47ab-92b5-4a356de84368)

**yaml**
```yaml
type: custom:plotly-graph
entities:
  - entity: sun.sun
hours_to_show: 24
refresh_interval: 10

```

**Additional context**
