### ISSUE TITLE
Show value missing when using filter

### ISSUE THREAD

**Issue by jazzmonger** [dbuezas/lovelace-plotly-graph-card#375]
**Describe the bug**

When using this filter, show value doesn't work:
```
      - sliding_window_moving_average:
          window_size: 20
          extended: true
          centered: true
```
**Screenshots**
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/52110065/b55a7d93-ee93-4274-9812-fc74e221ce50)

**yaml**
```
  - entity: climate.house_wood_pellet_stove
    attribute: current_temperature
    name: Temp@Stove
    yaxis: y1
    filters:
      - sliding_window_moving_average:
          window_size: 20
          extended: true
          centered: true
```

**Additional context**
The sensor I have is EXTREMELY noisy.  If there's another filter I can use, I'm all ears.  I've tried several.
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/52110065/4df473cd-e159-4e75-96c4-832ba17cd4fe)
