### ISSUE TITLE
Statistic data is not renewed within graphs's live time

### ISSUE THREAD

**Issue by marcelhoogantink** [dbuezas/lovelace-plotly-graph-card#388]
**Describe the bug**
Having a bar-graph of statistic data, the graph is not renewed with an extra new bar when the set period of the graph is crossed by time.
In [this link in point (2) ](https://community.home-assistant.io/t/plotly-interactive-graph-card/347746/644?u=marcelhoogantink
) example it is discussed in more detail.

**Screenshots**
Here is a screenshot of twice the same graph. The upper one was opened before the set period was crossed, the lower one after:

![53972d5c5f06d1b8fd698b80af458b78e62cd706_2_494x500](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/51886888/d94bece0-14f8-4eb5-af88-09248851ba29)

**Additional context**
I think the sttistics of the entities in the graph should be updated right after   a period is crossed by time. So the 5_minute period every 5 minutes, therhour-period every and so on.

**Comment by dbuezas** [comment]
Thanks.
Note to self: statistics don't auto update. Likely because the cache indicates that it already has requested data for the past period and statistics add data retroactively

**Comment by scinos** [comment]
In case it helps, I have another instance of the same bug.

First image was loaded around 10:00. Note how the curve "flattens" after that time. Second image is after reloading the dashboard.

![image](https://github.com/user-attachments/assets/55809077-cd8c-485b-b293-1027f4b2a16c)
![image](https://github.com/user-attachments/assets/a6914db2-cca1-4849-882e-72e1b42dad98).

This is the card config:

```
- type: custom:plotly-graph
  view_layout:
    grid-area: electricity
  style:
    .: |
      ha-card {
        height: 100px;
      }
      layout-card {
        height: 100%;
        display: block;
      }
  defaults:
    entity:
      extend_to_present: true
      period: auto
      line:
        width: 0
  layout:
    hovermode: "x unified"
  hours_to_show: 24
  entities:
    - entity: sensor.grid_import_energy
      filters:
        - resample: 5m
        - map_y_numbers: Math.round(Number(y))
        - store_var: grid_import
      internal: true

    - entity: sensor.battery_drain_energy
      filters:
        - resample: 5m
        - map_y_numbers: Math.round(Number(y))
        - store_var: battery_import
      internal: true

    - entity: sensor.house_consumption
      name: Usage from PV
      filters:
        - resample: 5m
        - map_y_numbers: Math.round(Number(y))
        - fn: |-
            ({ ys, xs, vars }) => {
              return {
                ys: ys.map( (v,idx) => v - vars.grid_import.ys[idx] - vars.battery_import.ys[idx])
              }
            }
      stackgroup: 1
      fillcolor: "#e0a21f"

    - entity: sensor.battery_store_energy
      name: Battery store
      filters:
        - resample: 5m
        - map_y_numbers: Math.round(Number(y))
      stackgroup: 1
      fillcolor: "#36b336"

    - entity: sensor.grid_export_energy
      name: Back to grid
      filters:
        - resample: 5m
        - map_y_numbers: Math.round(Number(y))
      stackgroup: 1
      fillcolor: "#1d621d"

    - entity: sensor.battery_drain_energy
      name: Battery usage
      filters:
        - resample: 5m
        - map_y_numbers: Math.round(Number(y))
      stackgroup: 1
      fillcolor: "#e06f1f"

    - entity: sensor.grid_import_energy
      name: Grid usage
      filters:
        - resample: 5m
        - map_y_numbers: Math.round(Number(y))
      stackgroup: 1
      fillcolor: "#e03e1f"
```
