### ISSUE TITLE
Fillgradient in scatter graphs

### ISSUE THREAD

**Issue by wrowlands3** [dbuezas/lovelace-plotly-graph-card#393]
**Describe the solution you'd like**
[Scatter fillgradient](https://plotly.com/python/reference/scatter/#scatter-fillgradient) defaults to fillcolor when used in home assistant, could support for this be added in a future release or am I missing something? It would be great to use colorscale in the fillgradient.

**How would it be defined in yaml?**
```
type: custom:plotly-graph
entities:
  - entity: ''
    y: 1
    x: $ex [new Date(Date.now()).setHours(-24), new Date(Date.now()).setHours(-23), new Date(Date.now()).setHours(24)]
    fill: tozeroy
    fillgradient:
      colorscale:
        - 0, red
        - 1, blue
      start: 0
      stop: 1
      type: vertical
hours_to_show: 24
```

**Scribble**
Currently looks like this,
![current](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86292646/d1680681-7edb-4be5-b07c-74983a322aca)
Should like more like this
![should](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/86292646/4a0a3005-b011-445d-b495-e03915946ad8)

**Additional context**
https://plotly.com/python/reference/scatter/#scatter-fillgradient
Colorscales detailed here: https://plotly.com/python/colorscales/

**Comment by dbuezas** [comment]
I didn't know about fill gradients.
I suggest you try using this in plain plotlyjs, I don't think this card changes anything about it.
You can start with this codepen: https://codepen.io/chris3edwards3/pen/BaNxxwY and test it in the browser

**Comment by SNoof85** [comment]
Managed to make it work on codepen :
https://codepen.io/SNoof/pen/JjQEZmP

**Comment by SNoof85** [comment]
https://github.com/SNoof85/lovelace-plotly-graph-card/releases/tag/3.3.6 here you will find with updated plotly.js to 2.34.0 and works fine with : 
```
    fill: tozeroy
    fillgradient:
      colorscale:
        - - 0
          - red
        - - 1
          - green
      type: vertical
```

**Comment by locussss** [comment]
@SNoof85 
Tested your repo and gradient works.
Also barcornerradius works, maybe more.

But the transparency is gone

**Comment by SNoof85** [comment]
What transparency are you talking about ?

**Comment by locussss** [comment]
Like the transparancy in the top diagram in the screenshot below, top is original plotly without gradient, bottom is with your repo.

I did not mean to be offensive or rude, I liked to try out...

<img width="516" alt="Screenshot 2024-08-06 at 15 08 01" src="https://github.com/user-attachments/assets/d21ec5ae-94b3-40c6-8070-28c72dc8f6cd">

**Comment by SNoof85** [comment]
You need to set the colors from the gradient to rgba values.
```
fillgradient:
  start: 0
  stop: 600
  colorscale:
    - - 0
      - rgba(255, 0, 0, 0.8);
    - - 0.5
      - rgba(255, 165, 0, 0.8)
    - - 1
      - rgba(0, 128, 0, 0.8)
  type: vertical
```
![image](https://github.com/user-attachments/assets/99707a89-92f1-4e2b-ab13-69ed2f883bb2)
