### ISSUE TITLE
No Range Buttons when date is not on axis

### ISSUE THREAD

**Issue by bj00rn** [dbuezas/lovelace-plotly-graph-card#410]
**Describe the bug**
Range selector buttons are not rendering.

Im trying to reproduce the mould risk index chart from https://github.com/Strixx76/mold_risk_index/blob/master/plot.png

The chart has temperature in x-axis, and humidity on x-axis and I use functions to map values from sensors accordingly.

Here is my attempt:

![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/10961167/871bd91f-20b6-4dcc-bc1f-f30aa786c449)

The problem i am experiencing is that range selector buttons are not rendering when using raw_plotly_config

**Screenshots**

**yaml**
```yaml
type: custom:plotly-graph
title: Mould risk
raw_plotly_config: true
hours_to_show: 1y
entities:
  - entity: sensor.lumi_lumi_weather_temperature_5
    internal: true
    statistic: mean
    fn: $fn ({ ys, vars }) => {vars.temp = ys }
  - entity: sensor.lumi_lumi_weather_humidity_5
    internal: true
    statistic: mean
    fn: $fn ({ ys, vars }) => vars.rf = ys
  - entity: ''
    x: $fn ({ vars }) => vars.temp
    'y': $fn ({ vars }) => vars.rf
    mode: markers
    name: index
    marker:
      color: red
      size: 1
    type: scatter
  - entity: ''
    internal: true
    name: Now
    showlegend: true
    line:
      width: 1
      dash: dot
      color: deepskyblue
    fn: |-
      $fn ({vars}) => {
        function r(start, stop, step) {
          return Array.from({ length: (stop - start) / step + 1}, (_, i) => start + (i * step))
        }
        vars.temp_x = r(-10, 60, 1)
      }
  - entity: ''
    x: $fn ({vars}) => vars.temp_x
    'y': |-
      $fn ({vars}) => {
        function p(x) {
          if (0 <= x <= 50) {
              var limit = 20 * Math.exp( -x * 0.15 ) + 73
              return Math.max(Math.min(100,limit),72)
          } else {
              return 100
          }
        }
        return vars.temp_x.map(x => p(x))
      }
    name: lvl1
  - entity: ''
    x: $fn ({vars}) => vars.temp_x
    'y': |-
      $fn ({vars}) => {
        function p(x) {
          if (0 <= x <= 50) {
          limit = 17 * Math.exp( -x * 0.11 ) + 80
          return Math.max(Math.min(100,limit),79)
          } else {
              return 100
          }
        }
        return vars.temp_x.map(x => p(x))
      }
    name: lvl2
  - entity: ''
    x: $fn ({vars}) => vars.temp_x
    'y': |-
      $fn ({vars}) => {
        function p(x) {
          if (0 <= x <= 50) {
           limit = 15 * Math.exp( -x * 0.10 ) + 85
           return Math.max(Math.min(100,limit),84)
          } else {
              return 100
          }
        }
        return vars.temp_x.map(x => p(x))
      }
    name: lvl3
  - entity: ''
    x:
      - 50
      - 50
    'y':
      - 50
      - 100
    name: Too hot
  - entity: ''
    x:
      - 0
      - 0
    'y':
      - 50
      - 100
    name: Too cold
layout:
  xaxis:
    title:
      text: Temperature (Degrees)
    rangeselector:
      'y': 1.2
      buttons:
        - count: 1
          step: minute
        - count: 1
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 7
          step: day
    zeroline: false
  yaxis:
    title:
      text: Humidity
    tick: 1
    zeroline: true
```

**Additional context**
The example from https://github.com/dbuezas/lovelace-plotly-graph-card#range-selector-buttons works fine
