### ISSUE TITLE
SolarEdge Photovoltaik Production and Consumption as Daily Graph

### ISSUE THREAD

**Issue by FFoXXaNN55** [dbuezas/lovelace-plotly-graph-card#427]
### Discussed in https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/320

<div type='discussions-op-text'>

<sup>Originally posted by **citoki** October 23, 2023</sup>
This is an implementation of Home Assistant Plotly graph library, to show a daily graph in a very similar way like the vendor iOS app is doing it.

| Original Vendor App | Plotly Graph Card |
|:---:|:---:|
|<img src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/7259873/5372d584-92df-4892-852e-712ee716b9f0" alt="solaredge original app picture show graph of production and consumption" width="80%" />|<img width="1400rem" alt="Plotly Custom Graph implementation" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/7259873/e9d7239d-f5ca-4fd6-b113-055fdeee91ba"/>|

```yaml
type: custom:plotly-graph
hours_to_show: 12
refresh_interval: 30
entities:
  - entity: sensor.pv_ac_power_combined_integral
    name: PV Production
    statistic: state
    period: auto
    legendgroup: 1
    filters:
      - derivate
      - store_var: pv_ac_power
    line:
      width: 1
      color: palegreen
      shape: spline
    fill: tonexty
  - entity: sensor.solaredge_m1_exported_kwh
    name: Self Consumption
    statistic: state
    legendgroup: 2
    period: auto
    fill: tozeroy
    filters:
      - derivate: h
      - map_y: parseFloat(vars.pv_ac_power.ys[i]) - parseFloat(ys[i])
      - store_var: selfcons
    line:
      width: 1
      color: dodgerblue
      shape: spline
  - entity: sensor.solaredge_m1_imported_kwh
    name: Import
    statistic: state
    legendgroup: 3
    period: auto
    filters:
      - derivate
      - map_y: '(parseFloat(y[i-1]) === parseFloat(ys[i])) ? 0 : parseFloat(vars.selfconsys[i]) + parseFloat(ys[i])'
    line:
      width: 0
      color: lightsalmon
      shape: spline
    fill: tonexty

```

Some remarks: 
- I used standard CSS colours and didn't go for specific RGBA numbers
- I use (SolarEdge Modbus Multi)[https://github.com/WillCodeForCats/solaredge-modbus-multi] integration to get SolarEdge data directly from the inverters every 10 seconds. It's needed to add RJ45 cable to the inverters, as Modbus isn't available via Wifi anymore
- since I've got two inverters running I combine the photovoltaik production with an template
- the data aggregation for the Solar Edge output API (iOS app) is 15 minutes and cannot be changed, therefore you'll see slightly different graph values

Edit: updated configuration after discussion here with some improvements

</div>

**Comment by FFoXXaNN55** [comment]
Good morning to you,

Love you solaredge plotly, but i got a problem: the entity do not match my entities (see picture)
I only have 1 Solaredge inverter. WHich sensors should i pick from my list in order to have nice graph like you have?
<img width="401" alt="solaredge1" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/66896528/be24bb86-0ee2-4291-b3dd-45f315c2bd06">
i thought: 
  - sensor.solaredge_ac_energy_kwh
  - sensor.solaredge_ac_power
  - sensor.solaredge_dc_power

But that didn't work

Is there something i am missing (something in configuation.yaml?) i have to add or ...

I am a newbie

**Comment by Saentist** [comment]
@FFoXXaNN55 
why not put under self consumption
```yaml
  - entity: sensor.solaredge_m1_exported_kwh
    name: Self Consumption
    filters:
      - multiply: -1
```
with will make negative values on graph /aka under zero graph/ 
It is more detailed and logical to be seen as negative?
