### ISSUE TITLE
All axis same Zero line

### ISSUE THREAD

**Issue by Saentist** [dbuezas/lovelace-plotly-graph-card#428]
When there is a left and right set values they both have ZERO line but is on different location in graph.
Is there a option to have option to merge Zero line to graphs will be good visualisation option.

**Additional context**
![image](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/16975883/813d54be-4084-4baf-805e-d383514ff065)

**Comment by Emse79** [comment]
Same issue, fix would be nice, thx.
![Screenshot 2024-07-10 213234](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/128181134/4dddfcf7-aa1c-438b-ab8e-fe8f08fbca41)

**Comment by Saentist** [comment]
@dbuezas any timeline?

**Comment by dbuezas** [comment]
@Saentist make a feature request to plotly itself

**Comment by Saentist** [comment]
@caiusseverus 
I have from 0 ... + something
and -something to + something.
But in case they are from different type, with I guess make thing graph to merge different types just in visualization area and ignore ZERO location.

Can you include some example of your suggestion.

**Comment by caiusseverus** [comment]
Yes, here's an example:

![image](https://github.com/user-attachments/assets/3ad470be-f74b-4107-8198-3189cd385dfe)

Note that all axes have a ranges with a scale factor of -4 between the minimum and maximum, so y1 is -1.25 to 5, y2 is -5 to 20, and y3 is -0.1 to 0.4.

Here's what it looks like if I remove the manually set ranges

![image](https://github.com/user-attachments/assets/905edf55-53a6-4752-93d6-25d3137b7bf2)

All three axes now have different zero lines and the tick marks no longer line up. There is no way that I'm aware of to force it to use the same zero line while automatically scaling.

**Comment by Saentist** [comment]
@caiusseverus post YAML code if possible. 
Can you add also for example `Sun Elevation`

**Comment by caiusseverus** [comment]
I don't know what I would do with sun elevation on that graph. Here is the yaml though:

```
type: custom:plotly-graph
title: Electricity Consumption
hours_to_show: current_day
config:
  displayModeBar: false
layout:
  height: 750
  dragmode: false
  legend:
    orientation: h
    itemsizing: constant
    font:
      size: 8
  xaxis:
    visible: true
    fixedrange: true
    domain:
      - 0
      - 0.95
  yaxis:
    visible: true
    fixedrange: true
    title: Consumption (kWh)
    tickmode: linear
    range:
      - -5
      - 20
  yaxis2:
    visible: true
    fixedrange: true
    overlaying: 'y'
    side: right
    position: 1
    title: £/kWh
    rangemode: tozero
    tickmode: sync
    range:
      - -0.1
      - 0.4
  yaxis3:
    visible: true
    fixedrange: true
    title: Cost (£)
    overlaying: 'y'
    side: left
    anchor: free
    autoshift: true
    rangemode: tozero
    tickmode: sync
    range:
      - -1.25
      - 5
  yaxis9:
    visible: false
    fixedrange: true
  annotations:
    - text: >-
        $fn ({ hass }) =>

        "<span style='font-size: 24px;'><span style='color: orange'>"

        + Number(hass.states['sensor.unit_avg_day'].state) + "</span></span>
        £/kWh<br>"

        + "</span><span style=''> Weighted Average Unit Price</span><br>"
      xref: x domain
      yref: y domain
      xanchor: center
      yanchor: center
      x: 0.1
      'y': 0.95
      showarrow: false
entities:
  - entity: sensor.electricity
    name: Today
    filters:
      - derivate
      - integrate: null
      - resample: 1m
      - map_y: parseFloat(y)
      - store_var: kwh
    line:
      color: rgba(52,152,219,1)
      width: 2
      shape: spline
    show_value: true
  - entity: sensor.electricity
    time_offset: 1d
    name: '-1d'
    filters:
      - derivate
      - integrate: null
    line:
      color: rgba(52,152,219,0.5)
      width: 2
      shape: spline
      dash: dot
    show_value: true
  - entity: sensor.octopus_current
    internal: false
    name: Price
    connectgaps: true
    texttemplate: ' %{y:.4f}'
    line:
      color: rgba(255,0,0,1)
      width: 1
      shape: hv
    yaxis: y2
    show_value: true
  - entity: sensor.octopus_current
    internal: false
    name: Price -1d
    time_offset: 1d
    connectgaps: true
    line:
      color: rgba(255,0,0,0.75)
      width: 1
      dash: dot
      shape: hv
    yaxis: y2
  - entity: sensor.octopus_energy_cost_tracker_electricity_cost
    name: Cost
    yaxis: y3
    line:
      color: green
      width: 2
      shape: spline
    show_value: true
    filters:
      - filter: i>1
      - resample: 1m
      - map_y: parseFloat(y)
      - store_var: cost
  - entity: sensor.octopus_energy_cost_tracker_electricity_cost
    name: Cost -1d
    time_offset: 1d
    yaxis: y3
    line:
      color: rgba(0,255,0,0.4)
      width: 2
      shape: spline
      dash: dot
    filters:
      - filter: i>1
    show_value: true
  - entity: sensor.svt_cost_today
    name: SVT cost
    yaxis: y3
    line:
      color: darkorange
      width: 2
      shape: spline
    filters:
      - filter: i>1
    show_value: true
  - entity: sensor.live_electricity_usage
    yaxis: y1
    fill: tozeroy
    line:
      color: rgba(100,75,50,0.25)
    filters:
      - multiply: 0.001
  - entity: ''
    name: Now
    showlegend: false
    line:
      width: 1
      dash: dot
      color: deepskyblue
    x: $fn () => [Date.now(), Date.now()]
    'y': $fn () => [0,1]
view_layout:
  position: main
```

**Comment by Saentist** [comment]
@caiusseverus cannot make it work with my config, any suggestions accepted
![image](https://github.com/user-attachments/assets/826e0621-94d9-4f61-964c-5dc0e8f82b33)

```yaml
type: custom:plotly-graph
defaults:
  entity:
    show_value: true
  yaxes:
    visible: true
    showgrid: true
  yaxis2:
    visible: true
    fixedrange: true
    overlaying: 'y'
    side: left
    position: 1
    title: radiation
    rangemode: tozero
    tickmode: sync
    range:
      - -0.1
      - 1000
  yaxis3:
    visible: true
    fixedrange: true
    title: watt
    overlaying: 'y'
    side: left
    anchor: free
    autoshift: true
    rangemode: tozero
    tickmode: sync
    range:
      - -1.25
      - 12000
hours_to_show: 12
autorange_after_scroll: true
refresh_interval: 10
title: Средна стойност за деня
layout:
  legend:
    orientation: h
    itemsizing: constant
    font:
      size: 10
  xaxis:
    visible: true
    fixedrange: false
    domain:
      - 0
      - 0.95
    rangeselector:
      'y': 1.1
      buttons:
        - count: 30
          step: minute
        - count: 3
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 3
          step: day
        - count: 7
          step: day
entities:
  - entity: sensor.ups_input_voltage
    name: UPS V
  - entity: sensor.ups_nominal_input_voltage
    name: 230V
  - entity: sensor.upsa_nominal_input_voltage
    name: 220V
  - entity: sensor.clamp_meter_voltage_2
    name: clamp V
  - entity: sensor.clamp_meter_power_2
    name: clamp power
    filters:
      - multiply: -1
    yaxis: y3
    fill: tozeroy
  - entity: sensor.output_1_wattage
    name: MIN600Tl-x
    yaxis: y3
    fill: tozeroy
    line:
      color: lightgreen
  - entity: sensor.8266_growatt_grid_active_power
    name: 4200TL-XE
    line:
      color: green
    fill: tozeroy
  - entity: sensor.esp8266_sun_elevation
    name: sun pos
  - entity: sensor.sp2_watt
    name: fridge
    fill: tozeroy
    yaxis: y3
    filters:
      - multiply: -1
  - entity: sensor.smartplug3_power
    name: serv
    yaxis: y3
    fill: tozeroy
    filters:
      - multiply: -1
  - entity: sensor.power
    name: LG
    filters:
      - multiply: -1
  - entity: sensor.solar_radiation
    name: Sun radiation
    yaxis: y2
    line:
      - color: red
  - entity: sensor.toko_price
    name: тарифа
```
