### ISSUE TITLE
Second Y-axis remains visible even after removing references and layout

### ISSUE THREAD

**Issue by sofkaski** [dbuezas/lovelace-plotly-graph-card#433]
**Describe the bug**
Sequence:

1. I made a graph showing statistics on entities and using both primary and secondary Y-axis.
1.  After some trials I decided to split the  graph so that I would not use any more the secondary Y-axis. 
1. I removed all references to secondary Y-axis and also the layout definition
1. Secondary Y axis is still visible. Browser deep refresh with cache clear does not help.

**Screenshots**

Screenshot after step 3:

![Screenshot from 2024-07-29 11-47-42](https://github.com/user-attachments/assets/30196d8c-05d3-4b5d-b245-11e85df1083f)

**yaml**

YAML after step 3:

```yaml
type: custom:plotly-graph
title: Tehot
hours_to_show: 24h
entities:
  - entity: sensor.inverter_external_power
    name: Verkko
  - entity: sensor.inverter_load_power
    name: Kuorma
  - entity: sensor.inverter_pv1_power
    name: Panelit
  - entity: sensor.inverter_today_battery_charge
    name: Akun lataus
  - entity: sensor.inverter_today_battery_discharge
    name: Akun purku
layout:
  xaxis:
    rangeselector:
      buttons:
        - count: 1
          step: minute
        - count: 1
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 7
          step: day
  yaxis:
    fixedrange: true
  margin:
    r: 100

```

**Additional context**

Removed secondary Y-axis is visible also when viewing the card in the companion app in Android phone.
