### ISSUE TITLE
Init only variables

### ISSUE THREAD

**Issue by iamwyza** [dbuezas/lovelace-plotly-graph-card#446]
**Describe the solution you'd like**

Presently you interact with the global variables like `myVarFunction: $ex vars.myvariable = 1`.  However, things within `$ex` seem to get executed on every internal loop.  In my example, I wanted to setup certain parts of the graph to be init only which includes creating a couple of arrays of data and doing some math on them.  Ideally I'd want to cache those so that it's only done at the beginning and then reused going forward. 

For example, below what I was, hoping, would happen is that I could hold the calculated data in `vars.zoneCacheX`, but unfortunately it seems like every loop wipes out those values.   The console log statements run seemingly about once a second.

```yaml

entities:
  - entity: ''
    fn_getZoneX: $ex vars.getZoneX = (zoneNumber) => {
      if (vars.zoneCacheX !== undefined &&  vars.zoneCacheX[zoneNumber] !== undefined) 
        return vars.zoneCacheX[zoneNumber];

      if (vars.zoneCacheX === undefined)
        vars.zoneCacheX = {};

      console.log(vars.zoneCacheX[zoneNumber]);
      console.log("reloaded x zonex");
      
     
      vars.zoneCacheX[zoneNumber] = [ 
        hass.states[vars.number_name_prefix + "zone_" + zoneNumber + "_begin_x"].state,      
        hass.states[vars.number_name_prefix + "zone_" + zoneNumber + "_begin_x"].state,      
        hass.states[vars.number_name_prefix + "zone_" + zoneNumber + "_end_x"].state,      
        hass.states[vars.number_name_prefix + "zone_" + zoneNumber + "_end_x"].state,     
        hass.states[vars.number_name_prefix + "zone_" + zoneNumber + "_begin_x"].state
      ];

      return vars.zoneCacheX[zoneNumber];
      }
```

**How would it be defined in yaml?**
```yaml
type: custom:plotly-graph
init:
  - fn_OnlyRunsOnce: $ex { if (vars.number === undefined) { console.log("setting vars.number"); vars.number = 1; }
# and you'd only ever see the one "setting vars.number" in the console.
entities:
  - entity: sensor.monthly_internet_energy
     entity_feature_config: xxx
```

**Scribble**
When applicable, paste a drawing of how the feature would look like

**Additional context**
