### ISSUE TITLE
the graph looks terrible

### ISSUE THREAD

**Issue by man55** [dbuezas/lovelace-plotly-graph-card#449]
The graph looks terrible.
Why is it so chewed? How to smooth it out?

The top graph is lovelace-plotly-graph-card and the bottom graph is the original graph which looks great as any normal graph should look like.

![Снимок экрана 2024-09-06 163436](https://github.com/user-attachments/assets/a8e744b8-90fa-4c0c-b50d-46a62e580650)

**yaml**
```
type: custom:plotly-graph
entities:
  - entity: sensor.jk_bms_temperature_sensor_1
    name: t1
  - entity: sensor.jk_bms_temperature_sensor_2
    name: t2
  - entity: sensor.jk_bms_temperature_sensor_3
    name: t3
  - entity: sensor.jk_bms_temperature_sensor_4
    name: t4
  - entity: sensor.jk_bms_temperature_sensor_5
    name: t MOS
hours_to_show: 24
refresh_interval: 10
```

How to fix this?

**Comment by dbuezas** [comment]
Plotly is doing everything it can to not hide data, if you zoom in the data is likely not smooth at all.

To smooth out data search for `sliding_window_moving_average` in the readme of this repo

**Comment by man55** [comment]
Thanks, that helped. It looks much nicer.
![Снимок экрана 2024-09-06 180957](https://github.com/user-attachments/assets/f0383d26-d4e3-4647-a5d4-e8e42ab5ece5)


I don't understand why it can't be done normally by default, or at least an option added to UI.
Instead of a normal solution, I have to sit and add a bunch of text to each entity in each graph...
```
type: custom:plotly-graph
entities:
  - entity: sensor.jk_bms_temperature_sensor_1
    name: t1
    filters:
      - sliding_window_moving_average: # best for smoothing
          # default parameters:
          window_size: 10
  - entity: sensor.jk_bms_temperature_sensor_2
    name: t2
    filters:
      - sliding_window_moving_average: # best for smoothing
          # default parameters:
          window_size: 10
  - entity: sensor.jk_bms_temperature_sensor_3
    name: t3
    filters:
      - sliding_window_moving_average: # best for smoothing
          # default parameters:
          window_size: 10
  - entity: sensor.jk_bms_temperature_sensor_4
    name: t4
    filters:
      - sliding_window_moving_average: # best for smoothing
          # default parameters:
          window_size: 10
  - entity: sensor.jk_bms_temperature_sensor_5
    name: t MOS
    filters:
      - sliding_window_moving_average: # best for smoothing
          # default parameters:
          window_size: 10
hours_to_show: 24
refresh_interval: 10

```
