### ISSUE TITLE
Maximum call stack size exceeded on IOS App

### ISSUE THREAD

**Issue by Woodstockskipper** [dbuezas/lovelace-plotly-graph-card#452]
**Describe the bug**
Hi, since some days I get the following error (see screenshot) on the IOS App on all devices. Android App and Browser work fine:

**Screenshots**
This is the error respond: (IOS)
![grafik](https://github.com/user-attachments/assets/45b5f20e-1f37-4ed7-a7c2-24c615566ea8)
This it should look like: (browser)
![newplot](https://github.com/user-attachments/assets/93dd2a7b-cb78-4c2e-9a47-2ecb81ec154f)

**yaml**
```
type: custom:plotly-graph

entities:
  - entity: sensor.si_6_0_battery_voltage_a
    filters:
      - resample: 0.5h
    internal: true
    fn: $fn ({ xs, ys, vars }) => { vars.y_axis = ys; vars.xs = xs; }
  - entity: sensor.si_6_0_battery_soc_total
    filters:
      - resample: 0.5h
    internal: true
    fn: |-
      $fn ({xs, ys, vars }) => { vars.x_axis = ys; 
        const clr =[]
      for (let i = 1; i < xs.length; i++){         
              if(i < xs.length -1)
              {clr[i] = "blue"}
              else
              {clr[i] = "crimson"}
       }
       vars.clr = clr;}
  - entity: ''
    name: Ladezustände
    x: $fn ({ vars }) => vars.x_axis
    'y': $fn ({ vars }) => vars.y_axis
    type: scatter
    mode: markers
    marker:
      size: 5
      color: $fn ({ vars }) => vars.clr
  - entity: ''
    name: Nom. Entladekurve
    x:
      - 10
      - 20
      - 30
      - 80
      - 95
      - 98
      - 100.01
    'y':
      - 46.6
      - 49.6
      - 50.1
      - 51.7
      - 52.2
      - 53
      - 55
    mode: lines
    line:
      color: darkslateblue
      shape: spline
hours_to_show: 750
raw_plotly_config: true
ha_theme: true
layout:
  margin:
    t: 10
    l: 60
    r: 10
    b: 70
  height: 500
  yaxis:
    title:
      text: Batteriespannung [V]
  xaxis:
    title:
      text: SOC [%]
    autorange: true
  legend:
    orientation: h
    bgcolor: transparent
    x: 0
    'y': 1
    yanchor: bottom
```

**Additional context**
I had a long search to find this powerful tool and I´m verry excited. It would be nice if someone could help me to make it work again.

**Comment by dbuezas** [comment]
That's odd.

Maybe try adding all semicolons, just in case there's any ambiguous statement:

```yaml
type: custom:plotly-graph

entities:
  - entity: sensor.si_6_0_battery_voltage_a
    filters:
      - resample: 0.5h
    internal: true
    fn: |
      $fn({ xs, ys, vars }) => { 
        vars.y_axis = ys; 
        vars.xs = xs; 
      }
  - entity: sensor.si_6_0_battery_soc_total
    filters:
      - resample: 0.5h
    internal: true
    fn: |
      $fn({ xs, ys, vars }) => { 
        vars.x_axis = ys; 
        const clr = [];
        for (let i = 1; i < xs.length; i++) {         
          if (i < xs.length - 1) {
            clr[i] = "blue";
          } else {
            clr[i] = "crimson";
          }
        }
        vars.clr = clr;
      }
  - entity: ''
    name: Ladezustände
    x: $fn({ vars }) => vars.x_axis
    y: $fn({ vars }) => vars.y_axis
    type: scatter
    mode: markers
    marker:
      size: 5
      color: $fn({ vars }) => vars.clr
  - entity: ''
    name: Nom. Entladekurve
    x:
      - 10
      - 20
      - 30
      - 80
      - 95
      - 98
      - 100.01
    y:
      - 46.6
      - 49.6
      - 50.1
      - 51.7
      - 52.2
      - 53
      - 55
    mode: lines
    line:
      color: darkslateblue
      shape: spline
hours_to_show: 750
raw_plotly_config: true
ha_theme: true
layout:
  margin:
    t: 10
    l: 60
    r: 10
    b: 70
  height: 500
  yaxis:
    title:
      text: Batteriespannung [V]
  xaxis:
    title:
      text: SOC [%]
    autorange: true
  legend:
    orientation: h
    bgcolor: transparent
    x: 0
    y: 1
    yanchor: bottom
```
