### ISSUE TITLE
Time axis in AM/PM not 24 hr

### ISSUE THREAD

**Issue by jazzmonger** [dbuezas/lovelace-plotly-graph-card#453]
Is there a way to set 12h time on the bottom axis vs 24hr?

**Comment by dbuezas** [comment]
Try with Tickformat

```yaml
layout:
  xaxis: 
    tickformat: '%I:%M %p'  
```
