### ISSUE TITLE
Statistic auto zoom level

### ISSUE THREAD

**Issue by firstcolle** [dbuezas/lovelace-plotly-graph-card#455]
I’m experiencing strange behavior in the display of a sensor from the long-term statistics.

```
`type: custom:plotly-graph
entities:
  - entity: sensor.sonoff_a480097298_temperature
    name: Temp.
    statistic: max
    period: auto`

```

If I set a wide zoom (7 days), I can see the data, but when I zoom in for more detail, I can't see the data.
![Senza titolo-1](https://github.com/user-attachments/assets/4fa3153e-10cb-4601-bba2-41b20fc49cd3)
