### ISSUE TITLE
Adaptive min/max filter

### ISSUE THREAD

**Issue by Elarion245** [dbuezas/lovelace-plotly-graph-card#457]
**Describe the solution you'd like**
I am plotting an entity which has many datapoints, as it changes once every second (power consumption).
I am currently plotting it as follows:

```
type: custom:plotly-graph
title: Ungetrackte Leistung
entities:
  - entity: sensor.wohnung_ungetrackte_leistung
    fill: tozeroy
    line:
      color: blue
hours_to_show: 24
refresh_interval: 30
period: auto
layout:
  xaxis:
    rangeselector:
      "y": 1.2
      buttons:
        - count: 10
          step: minute
        - count: 1
          step: hour
        - count: 3
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day

```

This works on my laptop, but my phone browser already complains. Also, it takes very long to load. 
I now tried implementing a min/max filter, as follows:

```
type: custom:plotly-graph
title: Ungetrackte Leistung
entities:
  - entity: sensor.wohnung_ungetrackte_leistung
    fill: tozeroy
    line:
      color: blue
    filters:
      map_y: |
        let resampled = []; let interval = 10; 
        for (let i = 0; i < y.length; i += interval) {
          let subset = y.slice(i, i + interval);
          let minVal = Math.min(...subset);
          let maxVal = Math.max(...subset);
          
          resampled.push(minVal);
          resampled.push(maxVal);
        }
        return resampled;  
      map_x: |
        let resampledX = []; let interval = 10;
        for (let i = 0; i < x.length; i += interval) {
          let subsetX = x.slice(i, i + interval);
          
          let meanX = subsetX[subsetX.length - 1];
          resampledX.push(meanX);
          resampledX.push(meanX);  // Add twice for min and max
        }
        return resampledX;    
hours_to_show: 24
refresh_interval: 30
period: auto
layout:
  xaxis:
    rangeselector:
      "y": 1.2
      buttons:
        - count: 10
          step: minute
        - count: 1
          step: hour
        - count: 3
          step: hour
        - count: 6
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
```
This also seems to work, but it has one drawback: if I set the plot to a shorter time-scale, obviously the filter is kept active. Ideally I would like to be able so configure the intervall adaptively based on the selection of the window.

**How would it be defined in yaml?**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.wohnung_ungetrackte_leistung
     filters:
         min_max: [1,1,1,2,5,10] // define interval for each configured range selector
```
