### ISSUE TITLE
Trendline for scatter plots

### ISSUE THREAD

**Issue by Heronimonimo** [dbuezas/lovelace-plotly-graph-card#471]
First off, what a great card. I'm really having a lot of fun making new visualizations of my data.

**Describe the solution you'd like**
I want to add a trendline to my scatter plots.

**How would it be defined in yaml?**
```yaml
  - entity: ""
    x: $fn ({ vars }) => vars.temperature
    "y": $fn ({ vars }) => vars.heat
    filters:
       - trendline:
           type: linear
           show_formula: true
           show_r2: true
    type: scatter
```

**Scribble**
Examples of how this could look like in Plotly can be found here: https://plotly.com/python/linear-fits/

**Comment by dbuezas** [comment]
Hi there!
I'm not quite sure what you mean, the feature exists, has multiple different regression algorithms and offers the exact same api you mentioned

**Comment by dbuezas** [comment]
Is it because you are also setting the x axis?
Maybe try setting it inside a filter (e.g with map_x and map_y) instead of setting x and y in the entity.

Btw, happy to hear you are having fun with it!

**Comment by Heronimonimo** [comment]
Thanks for the quick reply.

An example, I'm using one entity (heat produced by heatpump) to set Y and another (outdoor temperature to set X. When I define a trendline as set above I'm getting a line from point to point in the scatter, but not a trendline fitted trough the dataset.

**Comment by Heronimonimo** [comment]
![newplot (3)](https://github.com/user-attachments/assets/0157f893-099c-49ca-a70c-6f60bab7f295)
This is what my plot looks like. Using this code:
```
  - entity: ""
    x: $fn ({ vars }) => vars.temperature
    "y": $fn ({ vars }) => vars.heat
    filters:
      trendline:
       trendline: ols
    name: points+line
    marker:
      color: white
      size: 6
```

**Comment by dbuezas** [comment]
See my comment above, also make sure your yaml is well defined (you have issues with the filters there.

Try the yaml editor helper linked at the top of the readme to validate your yaml

**Comment by Heronimonimo** [comment]
> See my comment above, also make sure your yaml is well defined (you have issues with the filters there.
> 
> Try the yaml editor helper linked at the top of the readme to validate your yaml

Unfortunately I don't understand how I could use 'map_y' and 'map_x' to get to a correct trendline in the scatter plot.

My full code looks like this:
```
type: custom:plotly-graph
title: Warmteproductie per week
entities:
  - entity: sensor.buienradar_temperature
    period: day
    internal: true
    fn: $fn ({ ys, vars }) => vars.temperature = ys
  - entity: sensor.panasonic_heat_pump_main_heat_energy_production
    period: day
    internal: true
    fn: $fn ({ ys, vars }) => vars.heat = ys
  - entity: ""
    x: $fn ({ vars }) => vars.temperature
    "y": $fn ({ vars }) => vars.heat
    mode: markers
    name: points
    marker:
      color: green
      size: 6
    type: scatter
hours_to_show: 12000
raw_plotly_config: true
layout:
  showlegend: true
  margin:
    r: 50
    l: 75
    t: 50
    b: 75
  legend:
    orientation: h
  xaxis:
    title:
      text: Temperature
    range:
      - -5
      - 18
    showgrid: false
    zeroline: false
  yaxis:
    title:
      text: Heat produced (W)
    range:
      - 0
      - 7500
    showgrid: false
    zeroline: false

```

**Comment by dbuezas** [comment]
Oh, sorry, not map_y/x, the fn filter:
```yaml
filters:
  - fn: |
          ({vars}) => ({xs: vars.temperature, ys: vars.heat})
  - trendline:
           type: linear
           show_formula: true
           show_r2: true
```


I think this may work

**Comment by Heronimonimo** [comment]
> Uhmmmm on a second thought, I think the problem is just that your x axis isn't sorted. Try this:
> 
> ```yaml
> - fn: |
>     ({vars}) => {
>       const records = vars.temperature.map((x,i)=>({
>           x,
>           y:vars.heat[i]
>       }).sort((a,b)=>a.x-b.x);
>       return {
>           xs: records.map(({x})=>x),
>           ys: records.map(({y})=>y)
>       };
>     }
> ```
> 
> Followed by the Trendline filter

Oke, just tried it. Getting this now:
`Error: at [entities.3.filters.0]: Error in filter: TypeError: {(intermediate value)(intermediate value)}.sort is not a function`

**Comment by dbuezas** [comment]
try again, corrected a missing parenthesis.

**Comment by Heronimonimo** [comment]
> try again, corrected a missing parenthesis.

That fixes the code but still gives me a scatter with a line from dot to dot.

**Comment by dbuezas** [comment]
show me what you've got

**Comment by Heronimonimo** [comment]
Yes, I've got this now.

```
type: custom:plotly-graph
title: Warmteproductie per dag
entities:
  - entity: sensor.buienradar_temperature
    period: day
    internal: true
    fn: $fn ({ ys, vars }) => vars.temperature = ys
  - entity: sensor.panasonic_heat_pump_main_heat_energy_production
    period: day
    internal: true
    fn: $fn ({ ys, vars }) => vars.heat = ys
  - entity: ""
    x: $fn ({ vars }) => vars.temperature
    "y": $fn ({ vars }) => vars.heat
    mode: markers
    name: points
    marker:
      color: green
      size: 6
    type: scatter
  - entity: ""
    x: $fn ({ vars }) => vars.temperature
    "y": $fn ({ vars }) => vars.heat
    mode: line
    filters:
      - fn: >
          ({vars}) => { const records =
          vars.temperature.map((x,i)=>({x,y:vars.heat[i]})).sort((a,b)=>a.x-b.x);
          return {
           xs: records.map(({x})=>x),
           ys: records.map(({y})=>y)
          }; }
      - trendline:
          type: linear
          show_formula: true
          show_r2: true
  - entity: ""
    name: 375W/deg = 7.5kW @ -5 deg
    x:
      - 18
      - 15
      - -5
    "y":
      - 0
      - 0
      - 7500
    line:
      color: red
      shape: linear
  - entity: ""
    name: 325W/deg = 6.5kW @ -5 deg
    x:
      - 18
      - 15
      - -5
    "y":
      - 0
      - 0
      - 6500
    line:
      color: blue
      shape: linear
hours_to_show: 336
raw_plotly_config: true
layout:
  showlegend: true
  margin:
    r: 50
    l: 75
    t: 50
    b: 75
  legend:
    orientation: h
  xaxis:
    title:
      text: Temperature
    range:
      - -5
      - 18
    showgrid: false
    zeroline: false
  yaxis:
    title:
      text: Heat produced (W)
    range:
      - 0
      - 7500
    showgrid: false
    zeroline: false
```
![Screenshot_20241106_202934_Home Assistant](https://github.com/user-attachments/assets/382ecf04-6846-40b1-be9e-fcfa727e6b42)

**Comment by dbuezas** [comment]
Try with this:
<img width="534" alt="image" src="https://github.com/user-attachments/assets/2363b1f3-52ba-4e41-918a-dfa6dcb9f80c">

```yaml
type: custom:plotly-graph
$fn: |
  $ex {
    // ignore this block
    vars.temperature = [2,4,12,2,4,5,67,3,3,2];
    vars.heat =        [4000,2000,2000,3000,1000,4000,6000,7000,5000,3000,1];
  }
entities:
  - entity: ""
    mode: lines
    name: sorted data
    fn: |
      $ex {
        const records = vars.temperature
          .map((x, i) => ({
            x,
            y: vars.heat[i],
          }))
          .sort((a, b) => a.x - b.x);
        vars.sorted = {
          xs: records.map(({ x }) => x),
          ys: records.map(({ y }) => y),
        };
      }
    x: $ex vars.sorted.xs
    y: $ex vars.sorted.ys
  - entity: ""
    name: trendline
    mode: lines
    filters:
      - load_var: sorted
      - trendline:
          type: linear
          show_formula: true
          show_r2: true
      - store_var: trendline
    x: $ex vars.trendline.xs.map(x=>+x)
    y: $ex vars.trendline.ys
    
raw_plotly_config: true
layout:
  showlegend: true
  margin:
    r: 50
    l: 75
    t: 50
    b: 75
  legend:
    orientation: h
  xaxis:
    title:
      text: Temperature
    range:
      - -5
      - 18
    showgrid: false
    zeroline: false
  yaxis:
    title:
      text: Heat produced (W)
    range:
      - 0
      - 7500
    showgrid: false
    zeroline: false

```
