### ISSUE TITLE
Documentation Error/Typo

### ISSUE THREAD

**Issue by CzarDestructo** [dbuezas/lovelace-plotly-graph-card#475]
I believe there is a bug in the documentation front page, took me a while of stepping on that rake until I noticed it, there is several mentions of 'yaxes' the plural of 'yaxis' but then in some of the configuration examples 'yaxes' is used but this doesn't parse, only 'yaxis'.

![image](https://github.com/user-attachments/assets/b24a2293-a96b-4ccd-9732-85ce30fced25)

In summary, config _should_ be:
```
defaults:
  entity:
    fill: tozeroy
    line:
      width: 2
  yaxis: 
    fixedrange: true # disables vertical zoom & scroll
```

**Comment by dbuezas** [comment]
I think you are mixing two similar ones:
```yaml
layout:
   yaxis:
   yaxis2:
   ...etc...
```

And 
```yaml
defaults:
   yaxes:
      .... <--- default for layout: yaxis, yaxis2, yaxis3, etc
```
