### ISSUE TITLE
entities not disponible ?

### ISSUE THREAD

**Issue by Pascal66** [dbuezas/lovelace-plotly-graph-card#498]
**Describe the bug**
Uncaught (in promise) TypeError: r.entities.map is not a function

**Screenshots**
empty

**yaml**
```yaml
type: custom:plotly-graph
title: Production par panneau
raw_plotly_config: true
hours_to_show: 168
refresh_interval: 60
layout:
  title: Production des panneaux (W)
  xaxis:
    title: Temps
  yaxis:
    title: Puissance (W)
entities: |
  {{ states.sensor 
     | selectattr('entity_id', 'match', 'sensor.envoy_122040041654_inverter_*') 
     | map(attribute='entity_id') | list }}
fn: |-
  $fn ({ entities, vars }) => {
    // Créer les tracés pour chaque panneau
    const traces = entities.map((entity) => ({
      type: 'scatter',
      mode: 'lines',
      name: vars[entity].friendly_name || entity, // Nom du capteur
      x: vars[entity].timestamps, // Temps
      y: vars[entity].values, // Puissance
    }));

    return {
      data: traces,
      layout: { ...vars.layout }
    };
  }

```

**Additional context**
