### ISSUE TITLE
Gaps in plots of unchanged entities after restart; spikes are not 'needles' but large triangles

### ISSUE THREAD

**Issue by Tom-Bom-badil** [dbuezas/lovelace-plotly-graph-card#514]
**Describe the bug**
Basically, I have 2 issues, and both seem to have the same source: constant data over time. Done quite a bunch of plotly graphs over the last months; but this one leaves me clueless.

Background:
I am currently developing a new integration, which is polling data from a device every 60s. Development means a lot of restarts for testing etc. Also, sometimes there are single (!) measured 'spikes', e.g. due to misinterpretation of readings by my new integration (which is the reason for debugging and long-term monitoring it).

The plotly-related problem: Both events (restarts and spikes) will lead to wrong plots if an entity hasn't changed, e.g. for hours or days. It will either draw 'cutted' lines with spaces (in case of restarts), or a direct line between the 'spike reading' and the last change of the entitie's value (which might be hours ago - the spike always is a single event/measurement, so 1 minute early the old value was still valid and measured).

I was over and over debugging my new integration to find my mistake in it's data handling and storing through recorder:. Until I made a plain history-graph that showed me that it was my beloved plotly that was misbehaving. history-graph of HA as well as the mini-graph show the data correctly (see 2nd screenshot).

**Screenshots**
Screenshot of the problem, with an edit for the expected values:
Example after 2 restarts:
![image](https://github.com/user-attachments/assets/4a6ff44c-abd3-4166-a523-89c25b48128e)

Minimalistic comparizion of plotly, history-graph and mini-graph (YAML below):
![image](https://github.com/user-attachments/assets/d700eef9-dfc3-4233-b324-10b6458412aa)

**yaml**
Here is the yaml for the second screenshot where the 3 graphs are compared:

```yaml
type: custom:plotly-graph
hours_to_show: 24
entities:
  - entity: sensor.ventilation_temperature_outdoor_air
```

```yaml
type: history-graph
entities:
  - sensor.ventilation_temperature_outdoor_air
```

```yaml
type: custom:mini-graph-card
entities:
  - sensor.ventilation_temperature_outdoor_air
```

**Additional context**
Appreciate your ideas on how to deal with this - any known filters or such that will make plotly showing the data correctly? Thanks in advance!

/tom
