### ISSUE TITLE
Color_scheme not working with bar graphs

### ISSUE THREAD

**Issue by janeaujanssen** [dbuezas/lovelace-plotly-graph-card#523]
The **color_scheme:** can be set, which changes the colors of your line graphs. It even works when i create a scatter plot using **mode: markers**. But the color scheme does not influence the color of the bar graphs.

**yaml**
```yaml
type: custom:plotly-graph
color_scheme: 1
entities:
  - entity: sensor.energy
    name: Energy
    unit_of_measurement: kWh
    type: bar
```
