### ISSUE TITLE
Weird artifacts or clipping when combining `autorange_after_scroll` with negative `time_offset`

### ISSUE THREAD

**Issue by dcbr** [dbuezas/lovelace-plotly-graph-card#532]
**Describe the bug**
When setting `autorange_after_scroll: true`, the line of a shifted entity (negative `time_offset`) shows weird artifacts or gets clipped (when a resample filter is applied) after scrolling back in time.

**Screenshots**
Initial plot

![Image](https://github.com/user-attachments/assets/d87fd931-451a-4956-918a-690301341bbe)

After scrolling back (without `resample` filter): weird glitches at the end

![Image](https://github.com/user-attachments/assets/236acbb1-8b6f-4357-881c-a837e1ab2a2e)

After scrolling back (with `resample` filter): clipped line at the end, even though this data should be available

![Image](https://github.com/user-attachments/assets/9dc74274-3ad7-47ef-af3f-1040a2d07640)

After scrolling back (without `autorange_after_scroll`): normal, expected behaviour

![Image](https://github.com/user-attachments/assets/7d3a37ac-f501-4b7b-984e-ed0e3d0112ef)

**yaml**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.p1_meter_power
    name: Power
    filters:
      - resample: 5s
  - entity: sensor.elec_mean_quarter_power
    name: Average
    filters:
      - resample: 5s  # Remove to observe 'glitchy' behaviour instead of 'clipping' behaviour
    time_offset: "-450s"
hours_to_show: 1
autorange_after_scroll: true  # Set to false to observe 'normal' behaviour
layout:
  yaxis:
    fixedrange: true
```
