### ISSUE TITLE
Can't set gridwidth and linewidth for xaxis in defaults

### ISSUE THREAD

**Issue by ziffusion** [dbuezas/lovelace-plotly-graph-card#551]
**Describe the bug**
I am trying to set gridwidth and linewidth for xaxis in defaults. Doesn't seem to work. Same configuration for yaxes works fine.

**Screenshots**
[Screenshot](https://imgur.com/a/nb4mZLJ)

**yaml**
```yaml
views:
  - title: Stats
    sections:
      - type: grid
        column_span: 4
        cards:
          - type: custom:plotly-graph
            entities:
              - entity: sensor.xxx
                name: Jeanie
              - entity: sensor.yyy
                name: Sanjay
            hours_to_show: 720
            refresh_interval: 10
            title: Xxx
            grid_options:
              columns: full
            config:
              scrollZoom: false
              displayModeBar: false
            defaults:
              entity:
                mode: lines+markers+text
                type: scatter
                show_value: false
              yaxes:
                fixedrange: true
                tick0: 0
                dtick: 50
                gridwidth: 3
                minor:
                  showgrid: true
                  nticks: 5
                  gridwidth: 1
              xaxes:
                tick0: 0
                dtick: 50
                gridwidth: 3
                minor:
                  showgrid: true
                  nticks: 5
                  gridwidth: 1
```
