### ISSUE TITLE
Statisitcs use the wrong timestamp column

### ISSUE THREAD

**Issue by georgh** [dbuezas/lovelace-plotly-graph-card#557]
**Describe the bug**
Plotted statisitc values (5minute and hourly) are shifted on the x-axis for state-statistics.

The value listed for example at 23:10 uses the entry collected at 23:14:43. 
I think that is due to using the start_ts-column in statistics_short_term instead of the created_ts column.

**Screenshots**

![Image](https://github.com/user-attachments/assets/c6817030-cdbd-4268-84b9-177126f7a93b)

![Image](https://github.com/user-attachments/assets/410ebd62-5ea6-476b-9820-88dae8bf0996)

![Image](https://github.com/user-attachments/assets/e1ce04b3-7a4f-454d-aae2-c2ffa4f70daa)

**yaml**
```yaml
type: custom:plotly-graph
title: Verschiedene EnergieQuellen
hours_to_show: 4h
autorange_after_scroll: false
refresh_interval: auto
ha_theme: true
grid_options:
  columns: 48
  rows: 8
entities:
  - entity: sensor.total_energy
    name: normal db
  - entity: sensor.total_energy
    name: statistics db - state / hour
    statistic: state
    period: hour
    line: true
  - entity: sensor.total_energy
    name: statistics db - state / 5 min
    statistic: state
    period: 5minute
    line: true
```

**Additional context**
