### ISSUE TITLE
Filters are kinda cumulative, kinda not

### ISSUE THREAD

**Issue by FrnchFrgg** [dbuezas/lovelace-plotly-graph-card#560]
According to the documentation, the following code should only have `resample: 3m` applied to `sun.sun`, but the second filter actually gets applied.

```yaml
type: custom:plotly-graph
defaults:
  entity:
    filters:
      - resample: 1m
      - map_y: "0"
entities:
  - entity: sun.sun
    filters:
      - resample: 3m
hours_to_show: 24
refresh_interval: 10
```

From my testing, it seems that per-entity filters overwrite default filters, but only on an item-by-item basis: the first filter is overwritten by the first filter, the second by the second, and so on. Any remaining filters will stay there. This is probably a side-effect of the `...` merging that merges the arrays instead of squarely replacing the old by the new.

**Comment by FrnchFrgg** [comment]
Note that the following correctly disables all default filters, so this is a little more complicated:
```yaml
type: custom:plotly-graph
defaults:
  entity:
    filters:
      - resample: 1m
      - map_y: "0"
entities:
  - entity: sun.sun
    filters: []
hours_to_show: 24
refresh_interval: 10
```
