### ISSUE TITLE
Data derived from esphome does not show up past long term statistics

### ISSUE THREAD

**Issue by gideonyong** [dbuezas/lovelace-plotly-graph-card#573]
**Describe the bug**
When data comes from esphome, after the long term statistics takes into effect, the data does not show up in plotly.
**Screenshots**

Data in HA history:
![Image](https://github.com/user-attachments/assets/825d56a6-234e-4bbb-8bea-8dec757f8d33)

Data with plotly:

![Image](https://github.com/user-attachments/assets/a9d5bc1d-6ea3-4bf4-b8cc-4773fa659eb1)

**yaml**
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.particulate_matter_2_5um_concentration_3
    name: PM2.5 Concentration
layout:
  title: Particulates
  yaxis:
    title: Concentration (µg/m³)

hours_to_show: 168
refresh_interval: 300
```

**Additional context**
I tried this with other data types such as temperature and it has the same issue.
