### ISSUE TITLE
Feature request: programmable y axis limits

### ISSUE THREAD

**Issue by Rvh91** [dbuezas/lovelace-plotly-graph-card#60]
It would be great if we could change the autoscale behavior. For example one of the following  (or all) would be nice: 

1. Exclude certain entities from the automatically computed axis limits.
2. Specify either a hard coded lower or upper bound for an axis, but have the other bound automatically computed.
3. Specify a function for automatical computation of limits, for example:
```
range:
  - max(entities)
  - max( min(entities), 20 )
```
4. Potentially have 'range selector' buttons like we have for the x-axis, but then for various settings. For example button 1 could represent fixed range of 0 - 20, button 2 could be from 12-30, button 3 could be automatic computation, button 4 could be automatic computation with a certain entity excluded, etc.

**Comment by dbuezas** [comment]
Yes, I really wish plotly had that option.
Here's the relevant requesthttps://github.com/plotly/plotly.js/issues/887

One workaround is for me to update the ranges AFTER the user interaction, which will make the UI very jumpy

**Comment by FrnchFrgg** [comment]
I suppose that universal functions can handle at least a big part of this, provided one can disable the autoscaling feature.

**Comment by dbuezas** [comment]
I haven't tried it yet, but i think so, yes. Using vars or getFromConfig. If you try it please let me know how it went!

**Comment by dbuezas** [comment]
I couldn't resist:
```yaml
type: custom:plotly-graph-dev
hours_to_show: current_week
entities:
  - entity: sensor.senseair_temperature    
layout:
  uirevision: $fn () => Math.random() // force rescale on scroll
  yaxis:
    range: |
        $fn ({ getFromConfig }) => {
          const all = getFromConfig("entities").flatMap(({ y }) => y);
          return [
            Math.max(12, Math.min(...all)), // cap to lowest value, but at least 12
            Math.min(18, Math.max(...all)), // cap to highest value, but at most 18
          ]
        }
```

You can also:
* filter the `y` values by x[i] being inside `getFromConfig('visible_range')` (if you this to only be applied to what is currently visible)
* put this in the default yaxes, and only take the entities whose yaxis index matches the one from `"y" + path.match(/layout\.yaxis(.*)\..*/)[1];`(if you have multiple yaxes and want to cap them independently)

I tried this and it works, but the code gets too contrived to serve as an example.
