### ISSUE TITLE
Weird resizing behavior with horizontal stack

### ISSUE THREAD

**Issue by paccerdk** [dbuezas/lovelace-plotly-graph-card#61]
Using plotly-graph-card with horizontal-stack causes some weird behavior from the plotly-graph-card.
It just keeps resizing from some maximum to some minimum size, over and over again.
I found it a little difficult to describe the issue, so I've attached a video showing the problem.

https://user-images.githubusercontent.com/16404760/180327051-7f10d5d0-6941-4ee1-8bac-eb8961a20d24.mp4

I've had the same problem with multiple configurations, but this is the dashboard configuration I'm using in the example:
```
views:
  - title: Home
    cards:
      - type: horizontal-stack
        cards:
          - type: gauge
            entity: sensor.apc_br1200gi_load
            name: Load
            needle: true
            severity:
              green: 0
              yellow: 30
              red: 70
          - type: gauge
            entity: sensor.apc_br1200gi_battery_voltage
            max: 27
            min: 20
            needle: true
            name: Batt. Voltage
            severity:
              green: 24
              yellow: 23
              red: 0
          - type: gauge
            entity: sensor.apc_br1200gi_input_voltage
            min: 200
            max: 260
            needle: false
            unit: V
            name: AC In
          - type: gauge
            entity: sensor.apc_br1200gi_battery_runtime
      - type: horizontal-stack
        cards:
          - type: custom:plotly-graph
            entities:
              - entity: sensor.apc_br1200gi_load
            hours_to_show: 1
            refresh_interval: 30
            title: Load/Time
          - type: gauge
            entity: sensor.apc_br1200gi_battery_charge
            max: 100
            min: 0
            needle: true
            name: Batt. Charge
            severity:
              green: 75
              yellow: 25
              red: 0
          - type: custom:plotly-graph
            entities:
              - entity: sensor.apc_br1200gi_input_voltage
            hours_to_show: 24
            refresh_interval: 10
            title: AC In/Time
          - type: custom:plotly-graph
            entities:
              - entity: sensor.apc_br1200gi_battery_runtime
            hours_to_show: 1
            refresh_interval: 10
            title: Runtime/Time
```
