### ISSUE TITLE
Title and Legend Overlapping

### ISSUE THREAD

**Issue by brennanmuir** [dbuezas/lovelace-plotly-graph-card#76]
<img width="237" alt="image" src="https://user-images.githubusercontent.com/18177606/194974374-4432d1ca-1ed3-455b-9246-169de387963e.png">

**Comment by Bascht74** [comment]
same here: 
![image](https://user-images.githubusercontent.com/66269310/197833402-871dbb4f-8132-4ee3-a3c8-f0cca75083e0.png)

```
type: custom:plotly-graph
entities:
  - entity: number.eg_andrea_arbeitsraum_rechts_level
    name: Andrea
  - entity: number.eg_studio_klein_level
    name: Studio klein
  - entity: number.eg_studio_gross_level
    name: Studio groß
  - entity: number.eg_laden_theke_level
    name: Laden
  - entity: sensor.eg_martina_durchfluss
    name: Martina
title: Heizung EG
layout:
  height: 330
hours_to_show: 24

```

**Comment by Bascht74** [comment]
I just tried to add "pad" to layout->title but I have not figurered out how to use it. 
It would be great that if you use the default layout of your card, the padidng wil be added automatically it you use a title for the card.

**Comment by dbuezas** [comment]
The solution is
```yaml
layout:
  margin:
    t: 70
```
But so many people have the same problem, that I just made it so that the extra margin is added automatically if there is a title.
