### ISSUE TITLE
Fixed range for binary sensor include unknown value

### ISSUE THREAD

**Issue by Ivan-Firefly** [dbuezas/lovelace-plotly-graph-card#79]
Hi there!

I'm trying to use ploty for showing graph for my binary open/close sensor. I fixed range with the following:

```yaml
layout:
  yaxis:
    range:
      - 'off'
      - 'on'
    fixedrange: true
```

However, for the first day graph looked ok (only on and off values were shown), but now it shows me also "unknown" value:
![image](https://user-images.githubusercontent.com/90849921/196644961-599c5c98-2e02-4d8b-a614-066a8f245052.png)

How could I avoid it?
