### ISSUE TITLE
Limit zoom to x axis

### ISSUE THREAD

**Issue by dbuezas** [dbuezas/lovelace-plotly-graph-card#8]
[from xalex75 in the HA community]

About zoom… yes, probably zooming only x axis would be more effective, otherwise I noticed that I need to move down the graph everytime

**Comment by dbuezas** [comment]
solution:
```yaml
layout:
    yaxis:
        fixedrange: true
```
