### ISSUE TITLE
Add optional buttons to scroll in the x axis

### ISSUE THREAD

**Issue by dbuezas** [dbuezas/lovelace-plotly-graph-card#9]
[from xalex75 in the HA community]

Hi.
I just saw the reply in issues section.
There you proposed something little different from what you realized here, buttons for shifting back he view, not just for changing hours to view.
On the screen they look the same, so probably using both at the same time could be a little confusing.
What about left and right buttons for shifting the view back or forward for the amount of hours selected?
I don’t know if this would be something that would require too much work or not, I’m just asking from the user point of view :wink:

**Comment by dbuezas** [comment]
Here's a way of doing this that just became possible in v3

```yaml
type: custom:plotly-graph-dev
hours_to_show: 6h
entities:
  - entity: sensor.openweathermap_temperature
layout:
  updatemenus:
    - buttons:
        - args:
            - xaxis.range
            - $fn({getFromConfig}) => getFromConfig("visible_range").map(t => t - 1000*60*60)
          label: <
          method: relayout
        - args:
            - xaxis.range
            - $fn({getFromConfig}) => getFromConfig("visible_range").map(t => t + 1000*60*60)
          label: '>'
          method: relayout
      direction: right
      active: -1
      pad:
        r: 10
        t: 10
      showactive: true
      type: buttons
      x: 1
      xanchor: right
      'y': 1
      yanchor: top
```
