### ISSUE TITLE
show daily energy consumption as a bar graph

### ISSUE THREAD

**Issue by dbuezas** [dbuezas/lovelace-plotly-graph-card#93]
### Discussed in https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/92

<div type='discussions-op-text'>

<sup>Originally posted by **Jn115759** October 30, 2022</sup>
I am new using this fantastic plotly integration and was hoping someone could help me with the issue above.
I defined a utility meter helper "sensor.helper_elektriciteit_aanvoer_net" which resets daily. Values are shown in the graph below in blue.
![image](https://user-images.githubusercontent.com/91130738/198865697-c160be9f-2e32-4612-8e07-81d7cf6e3d54.png)

Now I would like to see the daily consumption as a bar graph.
According to the documentation this should be fairly simple.
![image](https://user-images.githubusercontent.com/91130738/198865738-75fbdc23-5839-4080-b713-14f6fe2fa7da.png)

I used the code below.

```
type: custom:plotly-graph
entities:
  - entity: sensor.helper_elektriciteit_aanvoer_net
    statistic: max
    period: day
hours_to_show: 144
refresh_interval: 30
title: Energy
```
Unfortunately this only results in a flat line.

![image](https://user-images.githubusercontent.com/91130738/198865855-12d27379-5b42-4951-ac5a-4d660c3c4a69.png)

Would appreciate some hints to learn what I am doing wrong.
Many thanks.
</div>
